[[fbdevgd30-intro]]
= About the Firebird Developer's Guide: for Firebird 3.0

This volume consists of chapters that walk through the development of a simple application for several language platforms, notably Delphi, Microsoft Entity Framework and MVC.NET ("`Model-View-Controller`") for web applications, PHP and Java with the Spring framework.
It is hoped that the work will grow in time, with contributions from authors using other stacks with Firebird.

[[fbdevgd30-intro-author]]
== About the Author

Denis Simonov...

[[fbdevgd30-intro-funding]]
=== Translation...

Development of the original Russian version was sponsored by IBSurgeon and Moscow Exchange Bank.
A crowd-funding campaign was launched by the Firebird Foundation in 2017 to fund the translation into English to provide this document as the foundation for translation by Firebird Project document writers into other languages.

The campaign succeeded in raising enough to get the process under way.

[[fbdevgd30-intro-translation]]
=== ... and More Translation

Once the DocBook source appears in GitHub, we hope the trusty translators will start making versions in German, Japanese, Italian, French, Portuguese, Spanish, Czech.
Certainly, we never have enough translators so please, you Firebirders who have English as a second language, do consider translating some chapters into your first language.

[[fbdevgd30-acknowledgements]]
== Acknowledgments

We acknowledge these contributions of sponsors and donors with gratitude and thank you all for stepping up.

[float]
[[sponsors-donors]]
==== Sponsors and Other Donors

[float]
[[sponsors01-native]]
===== Sponsors of the Russian Languageversion of this Guide

* http://www.moex.com[Moscow Exchange] (Russia) 
+
_Moscow Exchange is the largest exchange holding in Russia and Eastern Europe, founded on December 19, 2011, through the consolidation of the MICEX (founded in 1992) and RTS (founded in 1995) exchange groups.
Moscow Exchange ranks among the world's top 20 exchanges by trading in bonds and by the total capitalization of shares traded, as well as among the 10 largest exchange platforms for trading derivatives._

* http://www.ib-aid.com[IBSurgeon] (http://ibase.ru[ibase.ru]) (Russia)
+
_Technical support and developer of administrator tools for the Firebird DBMS._

[float]
[[sponsors01-translate]]
===== Sponsors of the Translation Project

* http://www.firebirddevelopersday.com.br/fdd/14fdd_donors.html[Firebird Developers' Day contributors, 2017] (Brazil)
* http://www.syntess.nl[Syntess Software BV] (Netherlands)

[float]
[[donors-2017]]
===== Other Donors

Listed below are the names of companies and individuals whose cash contributions covered the costs for translation into English, editing of the raw, translated text and conversion of the whole into the Firebird Project's standard DocBook 4 documentation source format.

[cols="3*",frame=none,grid=none,stripes=none]
|===
| Peter Lee (Australia)
| Marknadsinformation i Sverige AB (Sweden)
| Thomas M. Conrad (U.S.A.)
| Transdata GmbH (Germany)
| Doug Chamberlin (U.S.A)
| Francis Mullan (South Africa)
| Francis Moore (U.K.)
| Laurent Guétin (Burkina Faso)
| Juan Antonio Mendoza Gil
| Massimilliano Coros
| Robert Firl
| Roland van Morckhoven (Netherlands)
| Aparecido Silva
| Andrew Kipcharsky (Russian Federation)
| Deon van Niekerk
| Hartmuth Prüfer (Germany)
| Martin Mutiku
| Martin Köditz (Germany)
| Myles Wakeham (U.S.A.)
| Mark Rotteveel (Netherlands)
| Pal Lillejord
| Roknic Dusan
| Chong Ray
| Solucionalia Consultores Auditores, S.L. (Spain)
| Jean-Marc Couret
| Nilson Kenji Aguena
| Gabor Boros
| Guiseppe Minutillo (Italy)
| Artur Henneberg
| Chris Mathews (U.S.A.)
| Ivan Cruz
| James Batson
| Kjell Rilbe (Sweden)
| Paolo Sciarrini (Italy)
| Antonis Tsourinakis (Greece)
| Arkadiusz Wolanski (Poland)
| Gerdus van Zyl (South Africa)
| Michele Denys
| Michael Trowe
| Ralf Stegemann
| Shaymon Gracia Campos
| Alessandro Marcellini
| Juan Carlos Ramirez
| Alexander K. Bowie
| Alberto Fornes Llodra
| Cserna Zsombor
| Jozo Leko
| Juergen Bachsteffel (Germany)
| Jose Antonio Amate Belchi
| Michele Giordano
| Vasily Vasilov
|===
