[[fbdevgd30]]
= Firebird 3.0 Developer's Guide
Denis Simonov
1.1, 27 June 2020
:doctype: book
:sectnums:
:sectanchors:
:toc: left
:toclevels: 3
:outlinelevels: 6:0
:icons: font
:experimental:
:imagesdir: ../../images
:docimagepath: refdocs/fbdevgd30

Author of the written material and creator of the sample project on five development platforms, originally as a series of magazine articles: Denis Simonov

Translation of original Russian text to English: Dmitry Borodin (MegaTranslations Ltd)

Editor of the translated text: Helen Borrie

Copyright (C) 2017-2020 Firebird Project and all contributing authors, under the https://www.firebirdsql.org/manual/pdl.html[Public Documentation License Version 1.0].
Please refer to the <<fbdevgd30-license,License Notice in the Appendix>>

[abstract]
--
This volume consists of chapters that walk through the development of a simple application for several language platforms, notably Delphi, Microsoft Entity Framework and MVC.NET ("`Model-View-Controller`") for web applications, PHP and Java with the Spring framework.
It is hoped that the work will grow in time, with contributions from authors using other stacks with Firebird.
--

toc::[]

include::_fbdevgd30-intro.adoc[leveloffset=1]


include::_fbdevgd30-db.adoc[leveloffset=1]


include::_fbdevgd30-firedac.adoc[leveloffset=1]


include::_fbdevgd30-efw.adoc[leveloffset=1]


include::_fbdevgd30-mvc.adoc[leveloffset=1]


include::_fbdevgd30-php.adoc[leveloffset=1]


include::_fbdevgd30-java.adoc[leveloffset=1]


include::_fbdevgd30-license.adoc[leveloffset=1]


include::_fbdevgd30-dochist.adoc[leveloffset=1]
