[[fblangref30-security-role-de]]
= `ROLE`

Eine _Rolle_ ist ein Datenbankobjekt, das einen Satz von <<fblangref30-security-privs-de,Privilegien>> verpackt.
Rollen implementieren das Konzept der Zugriffskontrolle auf Gruppenebene.
Der Rolle werden mehrere Berechtigungen gewährt, und diese Rolle kann dann einem oder mehreren Benutzern gewährt oder entzogen werden.

Ein Benutzer, dem eine Rolle zugewiesen wurde, muss diese Rolle in seinen Anmeldeinformationen angeben, um die zugehörigen Berechtigungen auszuüben.
Alle anderen Berechtigungen, die dem Benutzer direkt gewährt werden, sind von seiner Anmeldung mit der Rolle nicht betroffen.
Die gleichzeitige Anmeldung mit mehreren Rollen wird nicht unterstützt.

In diesem Abschnitt werden die Aufgaben zum Erstellen und Löschen von Rollen erläutert.

[[fblangref30-security-role-create-de]]
== `CREATE ROLE`

.Verwendet für
Erstellen eines neuen `ROLE`-Objekts

.Verfügbar in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
CREATE ROLE _rolename_
----

[[fblangref30-security-tbl-createrole-de]]
.`CREATE ROLE`-Anweisungsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|rolename
|Rollenname
Die maximale Länge beträgt 31 Zeichen
|===

Die Anweisung `CREATE ROLE` erzeugt ein neues Rollenobjekt, dem nachträglich ein oder mehrere Privilegien erteilt werden können.
Der Name einer Rolle muss unter den Rollennamen in der aktuellen Datenbank eindeutig sein.

[WARNING]
====
Es ist ratsam, den Namen einer Rolle auch unter den Benutzernamen eindeutig zu machen.
Das System verhindert nicht die Erstellung einer Rolle, deren Name mit einem bestehenden Benutzernamen kollidiert, aber in diesem Fall kann der Benutzer keine Verbindung zur Datenbank herstellen.
====

[[fblangref30-security-role-createpriv-de]]
=== Wer kann eine Rolle erstellen?

Die `CREATE ROLE`-Anweisung kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Benutzer mit der Berechtigung `CREATE ROLE`

Der Benutzer, der die `CREATE ROLE`-Anweisung ausführt, wird Eigentümer der Rolle.

[[fblangref30-security-role-create-exmpl-de]]
=== `CREATE ROLE`-Beispiele

.Erstellen einer Rolle namens `SELLERS`
[source]
----
CREATE ROLE SELLERS;
----

.Siehe auch
<<fblangref30-security-role-drop-de>>, <<fblangref30-security-grant-de,`GRANT`>>, <<fblangref30-security-revoke-de,`REVOKE`>>

[[fblangref30-security-alterrole-de]]
== `ALTER ROLE`

.Verwendet für
Ändern einer Rolle (Aktivieren oder Deaktivieren der automatischen Administratorzuordnung)

.Verfügbar in
DSQL

.Syntax
[listing,subs=+quotes]
----
ALTER ROLE _rolename_
  {SET | DROP} AUTO ADMIN MAPPING
----

[[fblangref30-security-tbl-alterrole-de]]
.`ALTER ROLE`-Anweisungsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|rolename
|Rollenname;
die Angabe von etwas anderem als `RDB$ADMIN` schlägt fehl
|===

`ALTER ROLE` hat keinen Platz im Create-Alter-Drop-Paradigma für Datenbankobjekte, da eine Rolle keine Attribute hat, die geändert werden können.
Seine eigentliche Wirkung besteht darin, ein Attribut der Datenbank zu ändern: Firebird verwendet es, um die Fähigkeit für Windows-Administratoren zu aktivieren und zu deaktivieren, beim Anmelden automatisch <<fblangref30-security-administrators,administratorprivilegien>> zu übernehmen.

Diese Fähigkeit kann nur eine Rolle betreffen: die vom System generierte Rolle `RDB$ADMIN`, die in jeder Datenbank von ODS 11.2 oder höher vorhanden ist.
Mehrere Faktoren sind an der Aktivierung dieser Funktion beteiligt.

Weitere Informationen finden Sie unter <<fblangref30-security-autoadminmapping,`AUTO ADMIN MAPPING`>>.

[[fblangref30-security-role-alterpriv-de]]
=== Wer kann eine Rolle ändern?

Die `ALTER ROLE`-Anweisung kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>

[NOTE]
====
Obwohl ein DDL-Privileg "ALTER ANY ROLE" vorhanden ist, gilt es nicht, da das Erstellen oder Löschen von Zuordnungen Administratorrechte erfordert.
====

[[fblangref30-security-role-drop-de]]
== `DROP ROLE`

.Verwendet für
Eine Rolle löschen

.Verfügbar in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
DROP ROLE _rolename_
----

Die Anweisung `DROP ROLE` löscht eine bestehende Rolle.
Es braucht nur ein einziges Argument, den Namen der Rolle.
Nachdem die Rolle gelöscht wurde, wird allen Benutzern und Objekten, denen die Rolle gewährt wurde, der gesamte Satz von Berechtigungen entzogen.

[[fblangref30-security-role-droppriv-de]]
=== Wer kann eine Rolle löschen?

Die `DROP ROLE`-Anweisung kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Der Besitzer der Rolle
* Benutzer mit dem `DROP ANY ROLE`-Privileg

[[fblangref30-security-role-drop-exmpl-de]]
=== `DROP ROLE`-Beispiele

.Löschen der Rolle SELLERS
[source]
----
DROP ROLE SELLERS;
----

.Siehe auch
<<fblangref30-security-role-create-de>>, <<fblangref30-security-grant-de,`GRANT`>>, <<fblangref30-security-revoke-de,`REVOKE`>>
