[[fblangref30-security-privs-de]]
= SQL-Privilegien

Die zweite Ebene des Firebird-Sicherheitsmodells sind SQL-Berechtigungen.
Während eine erfolgreiche Anmeldung - die erste Ebene - den Zugriff eines Benutzers auf den Server und auf alle Datenbanken unter diesem Server autorisiert, bedeutet dies nicht, dass der Benutzer Zugriff auf Objekte in Datenbanken hat.
Wenn ein Objekt erstellt wird, haben nur der Benutzer, der es erstellt hat (sein Besitzer) und Administratoren Zugriff darauf.
Der Benutzer benötigt _privileges_ für jedes Objekt, auf das er zugreifen muss.
Als allgemeine Regel müssen Rechte einem Benutzer explizit vom Objektbesitzer oder einem <<fblangref30-security-administrators,administrator>> der Datenbank _gewährt_ werden.

Ein Privileg besteht aus einer DML-Zugriffsart (`SELECT`, `INSERT`, `UPDATE`, `DELETE`, `EXECUTE` und `REFERENCES`), dem Namen eines Datenbankobjekts (Tabelle, View, Prozedur, Rolle) und der Name des Zuwendungsempfängers (Benutzer, Verfahren, Auslöser, Rolle).
Es stehen verschiedene Mittel zur Verfügung, um mehreren Benutzern in einer einzigen "GRANT"-Anweisung mehrere Arten von Zugriff auf ein Objekt zu gewähren.
Berechtigungen können von einem Benutzer mit "REVOKE" -Anweisungen widerrufen werden.

Eine zusätzliche Art von Berechtigungen, DDL-Berechtigungen, bietet Rechte zum Erstellen, Ändern oder Löschen bestimmter Arten von Metadatenobjekten

Berechtigungen werden in der Datenbank gespeichert, für die sie gelten, und gelten nicht für andere Datenbanken, mit Ausnahme der DDL-Berechtigungen `DATABASE`, die in der Sicherheitsdatenbank gespeichert sind.

[[fblangref30-security-privs-owner-de]]
== Der Objektbesitzer

Der Benutzer, der ein Datenbankobjekt erstellt hat, wird sein Besitzer.
Nur der Eigentümer eines Objekts und Benutzer mit Administratorrechten in der Datenbank, einschließlich des Datenbankeigentümers, können das Datenbankobjekt ändern oder löschen.

Administratoren, der Datenbankeigentümer oder der Objekteigentümer können anderen Benutzern Berechtigungen erteilen und diese widerrufen, einschließlich der Berechtigungen, anderen Benutzern Berechtigungen zu erteilen.
Der Prozess des Erteilens und Widerrufens von SQL-Berechtigungen wird mit zwei Anweisungen implementiert, <<fblangref30-security-grant-de,`GRANT`>> und <<fblangref30-security-revoke-de,`REVOKE`>>.
