:sectnums!:

[appendix]
[[fblangref25-dochist-de]]
= Dokumenthistorie

Die exakte Dateihistorie ist im Git-Repository des `firebird-documentation`-Repository zu finden; siehe https://github.com/FirebirdSQL/firebird-documentation

[%autowidth, width="100%", cols="4", options="header", frame="none", grid="none", role="revhistory"]
|===
4+|Revision History
|1.3-de
|13. Jun 2020
|MR
a|Umstellung auf AsciiDoc.
Verschiedene Kopierbearbeitung und Behebung von Sachfehlern und anderen Problemen beim Überprüfen und Korrigieren von AsciiDoc.

Möglicherweise fehlen einige Korrekturen aus den englischen Versionen 1.1 und 1.2.

|1.1
|1. Sep 2015
|H.E.M.B.
a|Das Original stammt aus dem Russischen, übersetzt durch Dmitry Borodin (MegaTranslations).
Rohübersetzungen bearbeitet und in DocBook konvertiert, in dieser Revision (1.1) durch Helen Borrie.

Diese Revision wurde nur als PDF-Datei verteilt, für die Überprüfung von Dmitry Yemanov, u.a.

Reviewer, bitte beachten Sie Kommentare wie diese: _Editor's note {two-colons} The sky is falling, take cover!_

|1.000-de
|11. Mär 2018
|MK
a|Deutsche Übersetzung basierend auf der englischen Dokumentenversion 1.000.

|1.000
|11. Aug 2017
|H.E.M.B.
a|Während des letzten Überprüfungszeitraums wurden keine weiteren Änderungen am Inhalt vorgenommen.
Die Kapitel DML, PSQL, Funktionen und Variablen, Transaktionen und Sicherheit wurden in dieser Phase nicht überprüft.

|0.906
|11. Aug 2016
|H.E.M.B.
a|Mehrere Revisionen wurden im Laufe des Jahres als Beta 1 veröffentlicht, mit Überprüfungen verschiedener Abschnitte von Paul Vinkenoog, Aage Johansen und Mark Rotteveel.
Diese Überarbeitung (0.906) wartet auf die endgültige Überarbeitung einiger späterer Abschnitte, die in rot kursiv als "`Editor's Note`" markiert sind.
|===

:sectnums: