:sectnums!:

[appendix]
[[fblangref25-dochist-de]]
= Dokumenthistorie

Die exakte Dateihistorie ist im _Git_-Repository des `firebird-documentation`-Repository zu finden; siehe https://github.com/FirebirdSQL/firebird-documentation

[%autowidth, width="100%", cols="4", options="header", frame="none", grid="none", role="revhistory"]
|===
4+|Revision History

|1.10-de
|18. Juli 2022
|MR
a|* Dokumentation für `RDB$INDICES.RDB$INDEX_TYPE` korrigiert (https://github.com/FirebirdSQL/firebird-documentation/issues/174[#174])
* Zusätzliches `SELECT` in Select-Syntax entfernt
* Behebung des für `SNAPSHOT TABLE STABILITY` dokumentierten Verhaltens (https://github.com/FirebirdSQL/firebird-documentation/issues/158[#158])
* `EXECUTE STATEMENT` benannte Parameter sind reguläre Bezeichner (https://github.com/FirebirdSQL/firebird-documentation/issues/164[#164])

|1.6-de
|21. Juni 2021
|MK
a|* Korrekturen aus der englischen Dokumentation übernommen. 
* Kleinere Korrekturen in der deutschen Übersetzung.

|1.6
|13. Juni 2021
|MR
a|* Falsche Tabellenübschrift korrigiert `NUMERIC` -> `DECIMAL`
* Falschen Linktitel korrigiert `DATEADD` -> `DATEDIFF`

|1.5-de
|16. Mai 2021
|MK
a|* Deutsche Übersetzung der vorigen Anpassungen
* Korrektur der Dokumenthistorie
* Einige Schreibfehler behoben

|1.5
|27. April 2021
|MR
a|* Fehlende `}` in regulären Ausdruck für Sonderzeichen hinzugefügt (siehe https://github.com/FirebirdSQL/firebird-documentation/issues/124[issue 124])
* Problem beim Rendern mit unsichtbarem `_` im regulären Ausdruck für Sonderzeichen behoben
* Verbesserungen des Ausdrucks von `CURRENT_CONNECTION` und `CURRENT_TRANSACTION` (siehe https://github.com/FirebirdSQL/firebird-documentation/issues/96[issue 96])

|1.4
|27. April 2021
|MR
|Verbesserung der `GRANT`-Syntax (siehe https://github.com/FirebirdSQL/firebird-documentation/issues/130[issue 130])

|1.3-de
|13. Juni 2020
|MR
a|Umstellung auf AsciiDoc.
Verschiedene Kopierbearbeitung und Behebung von Sachfehlern und anderen Problemen beim Überprüfen und Korrigieren von AsciiDoc.

Möglicherweise fehlen einige Korrekturen aus den englischen Versionen 1.1 und 1.2.

|1.3
|13. Juni 2020
|MR
|Diverse kleinere Verbessungen der Kopien und des Aussehens während Prüfung und Migration deutschen Version nach AsciiDoc

|1.2
|6. Juni 2020
|MR
a|* Kapitel Integrierte Funktionen und Kontextvariablen in zwei separate Kapitel getrennt
* Falsche Warnung im `ORDER BY`-Ausdruck entfernt
* Reihenfolge der Beschreibungen der Funktions- und Kontextvariablen vereinheitlicht

|1.1
|1. Juni 2020
|MR
|Konvertierung nach AsciiDoc.
Verschiedene Kopierbearbeitung und Behebung von Sachfehlern und anderen Problemen beim Überprüfen und Korrigieren von AsciiDoc.

|1.001
|22. Januar 2018
|H.E.M.B.
a|Der Dateiverlaufslink oben in diesem Kapitel wurde aktualisiert, um die Migration des Doc-Quellbaums nach Github widerzuspiegeln.

Rechtschreibfehler behoben / aktualisiert durch M. Rotteveel Dez. 2017 / Jan. 2018

* 14.12.2017 psql.xml Zeile 544 'stored procedures' durch 'triggers' ersetzt
* 14.12.2017 psql.xml Zeile 1070 Fremdes Symbol '>' entfernt
* 21.01.2018 functions-vars.xml Zeile 1222 'CURRENT_TIME' durch 'CURRENT_TIMESTAMP' ersetzt
* 21.01.2018 dml.xml Zeile 19 'INSERT OR UPDATE' durch 'UPDATE OR INSERT' ersetzt
* 21.01.2018 dml.xml Zeile 3344 Unnötiges 'the' entfernt
* 21.01.2018 ddl.xml Zeile 3359 Fehlendes Schlüsselwort 'INDEX' in SET STATISTICS-Syntax ergänzt
* 21.01.2018 commons.xml Zeile 1330 Schlüsselwörter 'horizontal' und 'vertical' getauscht
* 21.01.2018 structure.xml Zeilen 276 bis 278 Literal-Format 'yyyy-mm-dd' angepasst und Hex-Repräsentation in Beispiel integriert


|1.000-de
|11. März 2018
|MK
a|Deutsche Übersetzung basierend auf der englischen Dokumentenversion 1.000.

|1.000
|11. August 2017
|H.E.M.B.
a|Während des letzten Überprüfungszeitraums wurden keine weiteren Änderungen am Inhalt vorgenommen.
Die Kapitel DML, PSQL, Funktionen und Variablen, Transaktionen und Sicherheit wurden in dieser Phase nicht überprüft.

|0.906
|11. August 2016
|H.E.M.B.
a|Mehrere Revisionen wurden im Laufe des Jahres als Beta 1 veröffentlicht, mit Überprüfungen verschiedener Abschnitte von Paul Vinkenoog, Aage Johansen und Mark Rotteveel.
Diese Überarbeitung (0.906) wartet auf die endgültige Überarbeitung einiger späterer Abschnitte, die in rot kursiv als "`Editor's Note`" markiert sind.

|0.900
|1. September 2015
| H.E.M.B.
|Original in Russisch, übersetzt durch Dmitry Borodin (MegaTranslations).
Rohe Übersetzung, bearbeitet und konvertiert in DocBook, in der Version (0.900) von Helen Borrie.

Diese Revision wird nur als PDF-Ausgabe zur Überprüfung durch Dmitry Yemanov et al.

Rezensenten, bitte beachtet die folgenden Kommentare: _Editor's note {two-colons} The sky is falling, take cover!_
|===

:sectnums: