[[fblangref25-intro-de]]
= Über die Firebird SQL Sprachreferenz: für Firebird 2.5

Diese Firebird SQL Sprachreferenz ist das erste zusammenhängende Dokument, das alle Aspekte der Abfragesprache betrachtet, die von Entwicklern für die Kommunikation ihrer Anwendungen mit dem Firebird Relation Database Management System benötigt werden.
Diese Sprachreferenz hat eine lange Vorgeschichte.

[[fblangref25-intro-subject]]
== Thema

Das Kernthema dieses Dokuments ist die vollständige Implementierung der SQL-Abfragesprache.
Firebird entspricht weitestgehend den internationalen Standards für SQL in Bezug auf Datentypen, Datenspeicherstrukturen, Mechanismen zur referentiellen Integrität sowie Fähigkeiten zur Datenmanipulation und Zugriffsrechte.
Firebird beinhaltet außerdem eine robuste Prozedursprache -- procedural SQL (PSQL) -- für gespeicherte Prozeduren, Trigger und dynamisch ausführbare Code Blöcke.
Dies sind die Themen, die in diesem Dokument behandelt werden. 

[[fblangref25-intro-authors]]
== Urheberschaft

Das Material für die Zusammenstellung dieser Sprachreferenz wurde durch die Open Source Community der Firebird-Entwickler über die letzten 15 Jahre zusammengetragen.
Die Übergabe der Interbase 6 Open Source-Codebasis im Juli 2000 durch das (damaligen) Inprise / Borland-Konglomerat war herzlich willkommen.
Allerdings kam diese Übergabe ohne Rechte zu bestehenden Dokumentationen.
Seit dem Fork der Code-Basis durch die Besitzer für private und kommerzielle Zwecke, wurde klar, dass die nichtkommerzielle Firebird Open Source-Community niemals Nutzungsrechte hierfür erhalten würde.

Die zwei wichtigen Bücher des InterBase 6-Sammlung waren das [ref]_Data Definition Guide_ und die [ref]_Language Reference_.
Während ersteres die Untermenge der Data Definition Language (DDL) abdeckte, war der Rest im zweiten Buch enthalten.
Glücklicherweise war es jahrelang für Firebird-Benutzer möglich, die PDF-Handbücher online zu finden.

[[fblangref25-intro-authors-lru]]
=== Aktualisierungen der Sprachreferenz

Das [ref]_Data Definition Guide_, welches die Erstellung und Wartung der Metadaten für Datenbanken behandelt, war über Jahre hinweg "`gut genug`": Die Data Definition Language eines DBMS ist üblicherweise stabil und wächst nur langsam im Vergleich zur Data Manipulation Language (DML), die der Abfrage dient und die PSQL für Serverbasierte Programmierung nutzt. 

Der Vorsitzende des Firebird Dokumentations-Teams, Paul Vinkenoog, nahm sich der Aufgabe an, die große Masse an Verbesserungen und Neuerungen in der DML und PSQL im Rahmen der Veröffentlichungen zu dokumentieren.
Paul war persönlich verantwortlich für das Zusammentragen sowie Zusammenstellen und, zum Großteil, Schreiben der kumulativen Reihe der "`Language Reference Updates`" -- eine für jede Hauptversion seit v.1.5.

[[fblangref25-intro-bigbook]]
=== Die Geburt des Bigbooks

Ab etwa 2010 arbeitete Paul, mit Firebird Projektleitung Dmitry Yemanov und einem Dokumentationskollegen Thomas Woinke, an der Planung und dem Aufbau einer kompletten SQL-Sprachreferenz für Firebird.
Sie begannen damit auf Basis der LangRef-Updates, die voluminös ist.
Es würde eine große Aufgabe sein und für alle Beteiligten ein Freizeitersatz. 

Dann, in 2013-4, zeigten zwei wohltätige Unternehmen -- MICEX und IBSurgeon -- erbarmen und beschäftigten drei Autoren, die sich der liegengebliebenen Arbeit annahmen und die Firebird 2.5 Language Reference in russisch veröffentlichten.
Sie schrieben den Großteil der fehlenden DDL-Abschnitte und erstellten, übersetzten oder verwendeten DML- und PSQL-Material aus den LangRef Updates, russischsprachigen Support-Forums, Firebird Release Notes, Readme-Dateien und anderen Quellen.
Ende 2014 war die Aufgabe weitestgehend erfüllt, in Form eines Microsoft Word-Dokumentes.

[[fblangref25-intro-funding]]
==== Übersetung ...

Die russischen Sponsoren erkannten, dass ihre Anstrengungen mit der weltweiten Firebird Community geteilt werden mussten, und fragten einige Projektmitglieder eine Crowd-Funding-Kampagne zu starten, welche den russischen Text professionell ins  Englische übersetzen sollte.
Dieser übersetzte Text würde dann bearbeitet und in das Projektkonforme DocBook-Format übertragen sowie als Zusatz in die offene Dokumentationsbibliothek der Firebird-Projektes aufgenommen werden.
Hier wären die Quellen für weitere Übersetzungen in andere Sprachen verfügbar. 

Die Kampagne zum Einsammeln der Gelder startete Ende 2014 und war erfolgreich.
Im Juni, 2015, begann der professionelle Übersetzer Dmitry Borodin mit der Übersetzung des russischen Textes.
Durch ihn gelangte der Text zur Überarbeitung und DocBook-Konvertierung an Helen Borrie -- und hier ist [ref]_Die Firbeird SQL Sprachreferenz für V.2.5_, von ...allen!

[[fblangref25-intro-translation]]
==== ... und noch mehr Übersetzungen

Nach dem Erscheinen der DocBook-Quellen im CVS, werden unsere vertrauensvollen Übersetzer hoffentlich mit der Arbeit an deutschen, japanischen, italienischen, französischen, portugisischen, spanischen und tschechischen Übersetzungen beginnen.
Gewiss ist, dass wir nie genug Übersetzer haben, so bitten wir Sie, die Firebirder, welche der englischen Sprache mächtig sind, über die Übersetzungsarbeiten in Ihre Muttersprache nachzudenken.
Auch die Übersetzung von Abschnitten ist hilfreich.

[[fblangref25-intro-contributors]]
=== Mitwirkende

[float]
==== Direkter Inhalt

* Dmitry Filippov (writer)
* Alexander Karpeykin (writer)
* Alexey Kovyazin (writer, editor)
* Dmitry Kuzmenko (writer, editor)
* Denis Simonov (writer, editor, coordinator)
* Paul Vinkenoog (writer, designer)
* Thomas Woinke (writer)
* Dmitry Yemanov (writer)

[float]
==== Ressourcen Inhalt

* Adriano dos Santos Fernandes
* Alexander Peshkov
* Vladyslav Khorsun
* Claudio Valderrama
* Helen Borrie
* and others

[float]
==== Übersetzungen

* Dmitry Borodin, megaTranslations.ru
* Martin Köditz, it & synergy GmbH

[float]
==== Bearbeitung und Konvertierung des englischen Textes

* Helen Borrie

[[fblangref25-acknowledgements]]
== Anmerkungen

Die erste komplette Sprachreferenz wäre ohne die Finanzierung nicht möglich gewesen.
Wir danken allen Beteiligten für Ihren Beitrag.

[float]
[[sponsors-donors]]
==== Sponsoren und andere Spender[[sponsors_donors]]

[float]
[[sponsors01-native]]
===== Sponsoren der russischen Sprachreferenz

* https://www.moex.com[Moscow Exchange] (Russland)
+
_Moscow Exchange ist die größte Börse in Russland sowie Osteuropa, gegründet am 19 Dezember 2011, durch den Zusammenschluss der Börsengruppen MICEX (gegründet 1992) und RTS (gegründet 1995).
Moscow Exchange zählt zu den 20 weltweit führenden Börsen im Handel von Anleihen und Aktien,
als zu den 10 größten Börsenplattformen für Handelsderivate._

* https://www.ib-aid.com[IBSurgeon] (https://ibase.ru[ibase.ru]) (Russland)
+
_Technischer Support und Entwickler administrativer Tools für das Firebird DBMS._

[float]
[[sponsors01-translate]]
===== Sponsoren des Übersetzungsprojektes

* https://www.syntess.nl[Syntess Software BV] (Niederlande)
* https://www.mitaro.li[Mitaro Business Solutions] (Liechtenstein)

[float]
[[donors]]
===== Weitere Spender

Folgend sind die Namen der Unternehmen und Personen aufgelistet, die Barmittel für die Kosten der Übersetzung ins Englische, Weiterverwarbeitung des rohen übersetzten Textes und die Konvertierung des Ganzen in das DocBook 4-Format des Firebird-Projektes freigemacht haben.

[cols="3*",frame=none,grid=none,stripes=none]
|===
|Integrity Software Design, Inc. (U.S.A.)
|dimari GmbH (Deutschland)
|beta Eigenheim GmbH (Deutschland)
|KIMData GmbH (Deutschland)
|Jason Wharton (U.S.A)
|Trans-X (Schweden)
|Sanchez Balcewich (Uruguay)
|Cointec Ingenieros y Consultores, S.L. (Spanien)
|Aage Johansen (Norwegen)
|Mattic Software (Niederlande)
|André Knappstein (Deutschland)
|Paul F. McGuire (U.S.A.)
|Marcus Marques da Rocha (Brasilien)
|Martin Kerkhoff
|Thomas Vedel (Dänemark)
|Bulhan Bulhan (Australien)
|Alexandre Benson Smith (Brasilien)
|Guillermo Nabrink (Brasilien)
|Pierre Voirin (Frankreich)
|Heiko Tappe (Deutschland)
|Doug Chamberlain (U.S.A.)
|Craig Cox (U.S.A.)
|OMNet, Inc. (Schweiz)
|Alfred Steller (Deutschland)
|Konrad Butz (Deutschland)
|Thomas Smekal (Kanada)
|Carlos H. Cantu (Brasilien)
|XTRALOG SARL (Frankreich)
|Laszlo Urmenyi (Brasilien)
|Fernando Pimenta (Brasilien)
|Rudolf Grauberger (Deutschland)
|Thomas Steinmaurer (Austria)
|Rene Lobsiger (Schweiz)
|Hian Pin Tjioe
|Xavier Codina
|Mick Arundell (Australien)
|Russell Belding (Neuseeland)
|Anticlei Scheid (Brasilien)
|Luca Minuti (Italien)
|Mark Rotteveel (Niederlande)
|Chris Mathews (U.S.A.)
|Hannes Streicher (Deutschland)
|Wolfgang Lemmermeyer (Deutschland)
|Paolo Sciarrini (Italien)
|Acosta Belzusarri
|Daniel Motos Guerra
|Alberto Alfonso Luna
|Simeon Bodurov
|Cees Meijer
|Robert Nixon
|Olivier Dehorter (Frankreich)
|András Omacht (Ungarn)
|Web Express
|Sergio Conzalez
|Marc Bleuwart
|Gabor Boros
|Shaymon Gracia Campos
|Cserna Zsombor (Ungarn)
|David Keith
|Uwe Gerold
|Daniele Teti (Italien)
|Pedro Pablo Busto Criado
|Istvan Szabo
|Spiridon Pavlovic
|J. L. Garcia Naranjo
|A. Morales Morales
|Helen Cullen (Neuseeland)
|Francisco Ibarra Ozuna
|{nbsp}
|===
