:sectnums!:

[appendix]
[[fblangref25-license-de]]
= Lizenzhinweise

Die Inhalte dieser Dokumentation sind Gegenstand der Public Documentation License Version 1.0 (die "`Lizenz`");
Sie d端rfen diese Dokumentation nur verwenden, sofern Sie die Bedingungen dieser Lizenz akzeptieren.
Kopien der Lizenz sind verf端gbar unter http://www.firebirdsql.org/pdfmanual/pdl.pdf (PDF) und http://www.firebirdsql.org/manual/pdl.html (HTML).

Die originale Dokumentation wurde unter dem Titel [ref]_Firebird 2.5 Language Reference_ erfasst.

Die urspr端nglichen Schreiber der Originaldokumentation sind: Paul Vinkenoog, Dmitry Yemanov und Thomas Woinke.
Verfasser der urspr端nglichen Texte in russisch sind Denis Simonov, Dmitry Filippov, Alexander Karpeykin, Alexey Kovyazin und Dmitry Kuzmenko.

Copyright (C) 2008-2020.
Alle Rechte vorbehalten.
Kontakt mit den Verfassern: paul at vinkenoog dot nl.

Verfasser und Bearbeiter des inkludierten PDL-lizenzierten Materials sind: J. Beesley, Helen Borrie, Arno Brinkman, Frank Ingermann, Vlad Khorsun, Alex Peshkov, Nickolay Samofatov, Adriano dos Santos Fernandes, Dmitry Yemanov.

Enthaltene Teile unterliegen dem Copyright (C) 2001-2020 ihrer jeweiligen Verfasser.
Alle Rechte vorbehalten.

Contributor(s): Mark Rotteveel.

Portions created by Mark Rotteveel are Copyright (C) 2018-2020.
All Rights Reserved.
(Contributor contact(s): mrotteveel at users dot sourceforge dot net).

:sectnums:
