[[fblangref25-de]]
= Firebird 2.5 Sprachreferenz
Dmitry Filippov; Alexander Karpeykin; Alexey Kovyazin; Dmitry Kuzmenko; Denis Simonov; Paul Vinkenoog; Thomas Woinke; Dmitry Yemanov; Martin Köditz; Mark Harris
1.10-de, 18. Juli 2022
:doctype: book
:sectnums:
:sectanchors:
:toc: left
:toclevels: 3
:outlinelevels: 6:0
:icons: font
:experimental:
:imagesdir: ../../images
include::../../attributes-de.adoc[]

Die Quelle des meist kopierten Referenzmaterials: Paul Vinkenoog +
Weitere Quelle kopierten Referenzmaterials: Thomas Woinke +
Übersetzung ins Deutsche: Martin Köditz, Mark Harris +
Copyright (C) 2017-2021 Das Firebird Projekt und alle beteiligten Autoren, unter der https://www.firebirdsql.org/manual/pdl.html[Public Documentation License Version 1.0].
Bitte vergleichen Sie auch <<fblangref25-license-de,Lizenzhinweise>> im Anhang.

[abstract]
--
Dieser Band ist eine Zusammenstellung von Themen rund um die Firebird SQL-Sprache, geschrieben von Mitgliedern der russischsprachigen Firebird Benutzer- und Entwickler-Gemeinschaft.
Im Jahr 2014 erreichte diese Zusammenstellung ihren Höhepunkt in einem russischsprachigen Referenzhandbuch.
Auf Veranlassung von Alexey Kovyazin wurde eine Kampagne unter den weltweit verteilten Firebird-Benutzern gestartet, um Mittel für eine professionelle Übersetzung ins Englische freizumachen.
Hieraus sollen wiederum Übersetzungen in andere Sprachen unter der Schirmherrschaft des Firebird Dokumentations-Projektes erstellt werden. 
--

toc::[]

include::_fblangref25-intro-de.adoc[leveloffset=1]


include::_fblangref25-structure-de.adoc[leveloffset=1]


include::_fblangref25-datatypes-de.adoc[leveloffset=1]


include::_fblangref25-commons-de.adoc[leveloffset=1]


include::_fblangref25-ddl-de.adoc[leveloffset=1]


include::_fblangref25-dml-de.adoc[leveloffset=1]


include::_fblangref25-psql-de.adoc[leveloffset=1]


include::_fblangref25-functions-de.adoc[leveloffset=1]


include::_fblangref25-context-vars-de.adoc[leveloffset=1]


include::_fblangref25-transacs-de.adoc[leveloffset=1]


include::_fblangref25-security-de.adoc[leveloffset=1]


include::_fblangref25-appx01-supplement-de.adoc[leveloffset=1]


include::_fblangref25-appx02-errorcodes-de.adoc[leveloffset=1]


include::_fblangref25-appx03-reskeywords-de.adoc[leveloffset=1]


include::_fblangref25-appx04-systables-de.adoc[leveloffset=1]


include::_fblangref25-appx05-montables-de.adoc[leveloffset=1]


include::_fblangref25-appx06-charsets-de.adoc[leveloffset=1]


include::_fblangref25-appx07-license-de.adoc[leveloffset=1]


include::_fblangref25-dochist-de.adoc[leveloffset=1]
