[[fbodbc205-connection]]
= Connecting to Firebird from Applications

The ODBC/JDBC driver attempts to connect a client to the Firebird server according to a set of attributes that default to those provided by the DSN definition.
Those stored attributes can be -- and usually are -- overridden by parameters passed by the application or read from a file (FILEDSN) when it prepares to connect.

[[fbodbc205-conn-params]]
== Connection Parameters

The connection parameters for the driver comprise a list of strings in the form `KEYWORD=value`, separated by semicolons ('```;```').
The following table enumerates the keywords with their verbose meanings and, where it is not obvious, their possible values.
 
[[fbodbc205-conn-keywords-tbl]]
.Keywords for Connection Attributes
[cols="1m,1,3", options="header", stripes="none"]
|===
^| Keyword
^| Description
^| More Information

|UID
.2+|Database account, i.e. username
.2+|{nbsp}

|USER

|PWD
.2+|Password
.2+|{nbsp}

|PASSWORD

|ROLE
|Role
|{nbsp}

|DSN
|Data source name
|{nbsp}

|DRIVER
|Driver name
|e.g., the string `Firebird/InterBase(r) driver`.
Defaults to the driver defined in the DSN.

|DBNAME 
.2+|Database
.2+|Full path to the database *as seen by the server*, including IP address {vbar} server name[/port] for a remote connection.
Defaults to the database defined in the DSN.

|DATABASE

|CLIENT
|Local path to the required `fbclient` library
|May be needed if the connection is to be via an embedded server library located in an application folder.

|CHARSET
.2+|Client-side default character set
.2+|Should be the same as the default character set of the database, if possible;
or one that is known to be codepage-compatible.

|CHARACTERSET

|READONLY
|Read-only
|Set transactions in this connection to be read-only.
The default is read/write.

|NOWAIT
|No wait
|Set transactions in this connection to have NO WAIT lock resolution.
The default is WAIT.

|LOCKTIMEOUT
|Set the lock timeout on WAIT transaction
|Pass the number of seconds to elapse after encountering a lock conflict until a transaction is to return an error.
Not valid if the transaction is set for NO WAIT resolution.

|DIALECT
|Set SQL dialect
|Only 1 or 3 is valid.
Normally this would have been set in the DSN.
It must match the dialect of the database.

|QUOTED
|Set on quoted identifiers
|If set in the DSN, the setting should be correct, i.e. already `ON` or `OFF`.

|SENSITIVE
|Set on case-sensitive identifiers
|If set in the DSN, the setting should be correct, i.e. already `ON` or `OFF`.

|AUTOQUOTED
|Set on auto-quoting identifiers
|If set in the DSN, the setting should be correct, i.e. already `ON` or `OFF`.

|USESCHEMA
|Set on "`use schema`"
|If set in the DSN, the setting should be correct.

|SAFETHREAD
|Safe threading
|{nbsp}

|FILEDSN
|File DSN
|Path to a file where the attribute strings from a previous connection are stored.
If this string is present, the contents of the file will take priority over the main DSN.

|SAVEDSN
|Save DSN
|Path to a file where the attribute strings from this connection, if successful, are to be stored.
The password will be saved in encrypted format.
|===

[[fbodbc205-dsnkeys-readseq]]
=== Read Sequence of the Keys

The ODBC function `SQLDriverConnect` gives priority to the attributes defined in the connection string, only fetching those stored in the DSN, or in a cited `FILEDSN`, to fill in any gaps.

[[fbodbc205-examples-connection]]
=== Connection Examples

Some examples of connection strings for applications that use the ODBC function `SQLDriverConnect`:

[source]
----
Open("DSN=myDb;")
----

Here, the function is expected to read everything it needs from the DSN.
User name and password are not supplied in the string.
If they are not present in the DSN, either

. it will use the environment variables `ISC_PASSWORD` and `ISC_USER` if they are are set; otherwise
. it will prompt the user for the login credentials


[source]
----
Open("DSN=myDb; UID=MCSSITE; PWD=mcssite;")
----

The function should have what it needs to make this connection, provided the user name  and password are authenticated by the server.

[source]
----
Open("DSN=myDb; UID=MCSSITE; PWD=mcssite; DBNAME=172.17.2.10:/usr/local/db/myDb.fdb;")

Open("DSN=myDb; UID=MCSSITE; PWD=mcssite; DBNAME=myserver:/usr/local/db/myDb.fdb;")
----

The `DBNAME` key points to the server IP address in the first example, with the path to the database file in the POSIX format.
The second example is making the same connection, using the server's host name instead of the IP address.

Three examples including the `DRIVER` attribute in the string:

[source]
----
Open("DRIVER=Firebird/InterBase(r) driver; DBNAME=172.17.2.10:/usr/local/db/myDb.fdb;")

Open("DRIVER=Firebird/InterBase(r) driver; UID=MCSSITE; PWD=mcssite; DBNAME=172.17.2.10:/usr/local/db/myDb.fdb;")

Open("DRIVER=Firebird/InterBase(r) driver; UID=MCSSITE; PWD=mcssite; DBNAME=dummy;")
----

In the last example, a local connection using a database alias in place of the database file path.
Of course, the alias must be present in `aliases.conf` in the root directory of the Firebird server (or, for Firebird 3 and up, in `databases.conf`). 

Using the server IP address and specifying an alternative port, with the target database on a POSIX server;
and the same using the server's host name instead:

[source]
----
172.17.2.10/3051:/usr/local/db/myDb.fdb

myserver/3051:/usr/local/db/myDb.fdb
----

Using the server IP address, with the target database on a Windows server;
and the same using the server's host name instead:

[source]
----
172.17.2.10:c:\db\myDb.fdb

myserver:c:\db\myDb.fdb
----

Using the server IP address and specifying an alternative port, with the target database on a Windows server;
and the same using the server's host name instead:

[source]
----
172.17.2.10/3051:c:\db\myDb.fdb

myserver/3051:c:\db\myDb.fdb
----

Using TCP/IP local loopback, using the local loopback IP address on a POSIX server;
and the same using the local loopback host name `localhost`:

[source]
----
127.0.0.1:/usr/local/db/myDb.fdb

localhost:/usr/local/db/myDb.fdb
----

The same things on a Windows server:

[source]
----
127.0.0.1:c:\db\myDb.fdb

localhost:c:\db\myDb.fdb
----

[[fbodbc205-examples-embedded]]
==== DBNAME for Embedded Connections

The `DBNAME` value for embedded connections and for the "`Windows Local`" (XNET) style of connection uses just the file path or alias, without host name, IP address or any port number.

[NOTE]
====
From Firebird 3 on, the way we conceptualise non-network connections on all platforms is more unified than for the earlier versions.
However, from the point of view of the ODBC/JDBC driver, the expression of the `DBNAME` value has not changed, regardless  of the platform on which we are making our embedded connection.
====

Local connection on a Windows server using first the file path and next an alias:

[source]
----
DBNAME=C:\db\myDb.fdb

DBNAME=C:dummy
----

On a POSIX server:

[source]
----
DBNAME=/usr/local/db/myDb.fdb

DBNAME=dummy
----

[[fbodbc205-examples-aliases]]
==== DBNAME Using Aliases

It is strongly recommended to define and use aliases to simplify life for you and your users.
It makes your `DBNAME` values completely neutral to the filesystem and so much less cumbersome.
In our last pairs of examples, the same alias was used on both Windows and POSIX.
The one on the Windows server would be defined thus:

[source]
----
dummy = C:\db\myDb.fdb
----

while, on the Linux server, it would be defined thus:

[source]
----
dummy = /usr/local/db/myDb.fdb
----
