:sectnums!:

[appendix]
[[fbodbc205-licence]]
= Licence Notices

[[doc-licence]]
== Documentation Licence

The contents of this Documentation are subject to the Public Documentation License Version 1.0 (the "`License`");
you may only use this Documentation if you comply with the terms of this License.
Copies of the License are available at https://www.firebirdsql.org/pdfmanual/pdl.pdf[https://www.firebirdsql.org/pdfmanual/pdl.pdf] (PDF) and https://www.firebirdsql.org/manual/pdl.html[https://www.firebirdsql.org/manual/pdl.html] (HTML).

The Original Documentation is titled [ref]_Firebird ODBC/JDBC Driver Manual_.

The Initial Writers of the Original Documentation are Alexander Potapchenko, Vladimir Tsvigun, James Starkey and others. 

Copyright (C) 2017.
All Rights Reserved.
Initial Writers contact: paul at vinkenoog dot nl.

Included portions are Copyright (C) 2001-2020 by the authors.
All Rights Reserved.

== Software Licence

The contents of this manual refer to the Firebird ODBC/JDBC driver contributed originally to the Firebird Project by James Starkey and developed since then by Vladimir Tsvigun, Alexander Potapchenko and others under the https://firebirdsql.org/en/initial-developer-s-public-license-version-1-0/[Initial Developer's
Public License V.1.0].

:sectnums:
