:sectnums!:

[appendix]
[[ufb-dochist]]
= Document history

The exact file history is recorded in the firebird-documentation git repository; see https://github.com/FirebirdSQL/firebird-documentation

[%autowidth, width="100%", cols="4", options="header", frame="none", grid="none", role="revhistory"]
|===
4+|Revision History

|0.0
|2002
|IBP
a|Written and published by IBPhoenix.

|1.0
|2005
|IBP
a|Donated to Firebird Project by IBPhoenix.

|2.0
|12 Nov 2006
|PV
a|[ref]_Preface_ added.

[ref]_About Firebird_: Updated to 1.5 and 2.0.
Rewrote/corrected/extended a number of sections.
Added section on Foundation.
Introduced Embedded Server.
Introduced aliases and (other) security features.
Introduced nbackup.
Introduced Services Manager + API.
Added rows [ref]_Availability_, [ref]_Local access on Windows_, [ref]_Multiprocessor support_, [ref]_Services Manager {plus} API_, [ref]_Guardian on Windows_ and [ref]_Guardian on Linux_ to the Classic-Super table.
Added same-named sections to the Classic-Super discussion following the table.
Explained bulkiness of Linux Classic client.
Added note on AMD processors.

[ref]_About Clients and Servers_: Updated to 1.5 and 2.0.
Rewrote/corrected/extended a number of sections.
Added sections on client filenames, multiple servers and server filenames.
Added major section on embedded servers.
Introduced SQLDirect.
Warned against use of IBX with higher Firebird versions.
Introduced UIB and JVCL.
Introduced .NET data provider.
Introduced IBPP.
Explained the concept of executable stored procedures.
Added section on PSQL limitations.

[ref]_Document History_ added.

[ref]_License Notice_ added.

|2.0.1
|31 Dec 2006
|PV
a|[ref]_About this book {two-colons} More documentation_: Changed text and hyperlink.

[ref]_About Firebird_: Changed title of memory requirements table.

[ref]_About Clients and Servers_: Added ZeosLib to Direct-to-API Components section.

Gave all tables and figures an ID to make their URLs persistent across builds.

|2.0.2
|16 Jul 2007
|PV
a|[ref]_About this book {two-colons} Summary of features_: Gave table a "```keep-together=auto```" PI, necessary with FOP 0.93+

[ref]_About Clients and Servers {two-colons} Client and server combined: Firebird Embedded Server_: Added titleabbrev.
Also corrected the first Note, which incorrectly stated that Fb2's `fbembed.dll` can't be used as a network client (altered 1st sentence, dropped last). Put "```localhost:```" in a `quote` in that same note.

[ref]_License notice_: Updated copyright year.

|2.0.2
|12 Jul 2020
|MR
|Conversion to AsciiDoc, minor copy-editing, fixed some (but not all) broken links
|===

:sectnums:

ifdef::backend-docbook[]
[index]
== Index
// Generated automatically by the DocBook toolchain.
endif::backend-docbook[]