[[ufb-preface]]
= About this book

[[ufb-preface-wip]]
== Work in progress!

This document is a work in progress.
The Firebird documenters -- all volunteers who work on this project in their spare time -- will publish more chapters as they go along.
As we are but a few, the pace is pretty slow.
However, the few chapters that _are_ present are up to date and will hopefully be a useful source of information for you.

If you find any errors or inconsistencies, please report them to the maintainers.
Email addresses are at the end of the book.

[[ufb-preface-origins]]
== Origins

[ref]_Using Firebird_ is not a new book.
The http://www.ibphoenix.com[IBPhoenix] editors wrote it years ago for distribution on their Developer's CD, when Firebird was still at version 1.0.
Since then, we have seen the arrival of Firebird 1.5 and 2.0, and most of the book is now in serious need of updating.
In 2005 the IBPhoenix company decided to open-source the entire 26-chapter manual and hand it over to the Firebird Project for upgrading and maintenance.

We would like to thank IBPhoenix here for making this work freely available.

[[ufb-preface-moredocs]]
== More documentation

If you're new to Firebird or want to brush up on the basics, read the [ref]_Firebird Quick Start Guide_ first.
There's one available for every version of Firebird.
Pick up yours from http://www.firebirdsql.org/index.php?op=doc.
This is also a good starting place to find links to more Firebird documentation.
