[[fblangref50-ddl-comment]]
= Comments

Database objects and a database itself may be annotated with comments.
It is a convenient mechanism for documenting the development and maintenance of a database.
Comments created with `COMMENT ON` will survive a _gbak_ backup and restore.

[[fblangref50-ddl-comment-create]]
== `COMMENT ON`

.Used for
Documenting metadata

.Available in
DSQL

.Syntax
[listing,subs=+quotes]
----
COMMENT ON <object> IS {'_sometext_' | NULL}

<object> ::=
    {DATABASE | SCHEMA}
  | <basic-type> _objectname_
  | USER _username_ [USING PLUGIN _pluginname_]
  | COLUMN _relationname_._fieldname_
  | [{PROCEDURE | FUNCTION}] PARAMETER
      \[__packagename__.]_routinename_._paramname_
  | {PROCEDURE | [EXTERNAL] FUNCTION}
      \[__package_name__.]_routinename_
  | [GLOBAL] MAPPING _mappingname_

<basic-type> ::=
    CHARACTER SET | COLLATION | DOMAIN
  | EXCEPTION     | FILTER    | GENERATOR
  | INDEX         | PACKAGE   | ROLE
  | SEQUENCE      | TABLE     | TRIGGER
  | VIEW
----

[[fblangref50-ddl-tbl-commenton]]
.`COMMENT ON` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|sometext
|Comment text

|basic-type
|Metadata object type

|objectname
|Metadata object name

|username
|Username

|pluginname
|User manager plugin name

|relationname
|Name of table or view

|fieldname
|Name of the column

|package_name
|Name of the package

|routinename
|Name of stored procedure or function

|paramname
|Name of a stored procedure or function parameter

|mappingname
|Name of a mapping
|===

The `COMMENT ON` statement adds comments for database objects (metadata).
Comments are saved to the `RDB$DESCRIPTION` column of the corresponding system tables.
Client applications can view comments from these fields.

[NOTE]
====
. If you add an empty comment ("```''```"), it will be saved as `NULL` in the database.
. By default, the `COMMENT ON USER` statement will create comments on users managed by the default user manager (the first plugin listed in the `UserManager` config option).
The `USING PLUGIN` can be used to comment on a user managed by a different user manager.
. Comments on users are not stored for the `Legacy_UserManager`.
. Comments on users are stored in the security database.
. Comments on global mappings are stored in the security database.
. `SCHEMA` is currently a synonym for `DATABASE`;
this may change in a future version, so we recommend to always use `DATABASE`
====

[WARNING]
====
Comments on users are visible to that user through the <<fblangref50-appx06-users,`SEC$USERS`>> virtual table.
====

[[fblangref50-ddl-comment-createpriv]]
=== Who Can Add a Comment

The `COMMENT ON` statement can be executed by:

* <<fblangref50-security-administrators,Administrators>>
* The owner of the object that is commented on
* Users with the `ALTER ANY __object_type__` privilege, where _object_type_ is the type of object commented on (e.g. `PROCEDURE`)

[[fblangref50-ddl-comment-create-exmpl]]
=== Examples using `COMMENT ON`

. Adding a comment for the current database
+
[source]
----
COMMENT ON DATABASE IS 'It is a test (''my.fdb'') database';
----
. Adding a comment for the `METALS` table
+
[source]
----
COMMENT ON TABLE METALS IS 'Metal directory';
----
. Adding a comment for the `ISALLOY` field in the `METALS` table
+
[source]
----
COMMENT ON COLUMN METALS.ISALLOY IS '0 = fine metal, 1 = alloy';
----
. Adding a comment for a parameter
+
[source]
----
COMMENT ON PARAMETER ADD_EMP_PROJ.EMP_NO IS 'Employee ID';
----
. Adding a comment for a package, its procedures and functions, and their parameters
+
[source]
----
COMMENT ON PACKAGE APP_VAR IS 'Application Variables';

COMMENT ON FUNCTION APP_VAR.GET_DATEBEGIN
IS 'Returns the start date of the period';

COMMENT ON PROCEDURE APP_VAR.SET_DATERANGE
IS 'Set date range';

COMMENT ON
PROCEDURE PARAMETER APP_VAR.SET_DATERANGE.ADATEBEGIN
IS 'Start Date';
----
