:sectnums!:

[appendix]
[[fbodbc205-licence-de]]
= Lizenzhinweise

[[doc-licence-de]]
== Dokumentations-Lizenz

Die Inhalte dieser Dokumentation sind Gegenstand der Public Documentation License Version 1.0 (die "`Lizenz`");
Sie dürfen diese Dokumentation nur verwenden, sofern Sie die Bedingungen dieser Lizenz akzeptieren.
Kopien der Lizenz sind verfügbar unter https://www.firebirdsql.org/pdfmanual/pdl.pdf (PDF) und https://www.firebirdsql.org/manual/pdl.html (HTML).

Die originale Dokumentation wurde unter dem Titel [ref]_Firebird ODBC/JDBC Driver Manual_ veröffentlicht.

Die ursprünglichen Schreiber der Originaldokumentation sind: Alexander Potapchenko, Vladimir Tsvigun, James Starkey und andere. 

Copyright (C) 2017.
Alle Rechte vorbehalten.
Kontakt mit den Verfassern: paul at vinkenoog dot nl.

Included portions are Copyright (C) 2001-2017 by the authors.
All Rights Reserved.

[[software-licence-de]]
== Software-Lizenz

Der Inhalt dieses Handbuchs bezieht sich auf den Firebird ODBC/JDBC-Treiber, der ursprünglich von James Starkey zum Firebird Project beigetragen wurde und seither von Vladimir Tsvigun, Alexander Potapchenko und anderen unter der https://firebirdsql.org/en/initial-developer-s-public-license-version-1-0/[Initial Developer's
Public License V.1.0] weiterentwickelt.

:sectnums:
