[[fbodbc205-connection-de]]
= Verbindung zu Firebird über Anwendungen herstellen

Der ODBC/JDBC-Treiber versucht, einen Client mit dem Firebird-Server gemäß einer Reihe von Attributen zu verbinden, die standardmäßig denen entsprechen, die von der DSN-Definition bereitgestellt werden.
Diese gespeicherten Attribute können und werden normalerweise von Parametern überschrieben, die von der Anwendung übergeben oder aus einer Datei (FILEDSN) gelesen werden, wenn sie die Verbindung vorbereitet.

[[fbodbc205-conn-params-de]]
== Verbindungsparameter

Die Verbindungsparameter für den Treiber bestehen aus einer Liste von Strings in der Form `KEYWORD=value`, die durch Semikolons ('```;```') getrennt sind.
In der folgenden Tabelle sind die Schlüsselwörter mit ihren ausführlichen Bedeutungen und, wenn sie nicht offensichtlich sind, mit ihren möglichen Werten aufgelistet.
 
[[fbodbc205-conn-keywords-tbl-de]]
.Schlüsselwörter für Verbindungsattribute
[cols="1m,1,3", options="header", stripes="none"]
|===
^| Schlüsselwort
^| Beschreibung
^| Weitere Informationen

|UID
.2+|Datenbankaccount, z.B. Benutzername
.2+|{nbsp}

|USER

|PWD
.2+|Kennwort
.2+|{nbsp}

|PASSWORD

|ROLE
|Role
|{nbsp}

|DSN
|Name der Datenquelle
|{nbsp}

|DRIVER
|Treibername
|z.B. die Zeichenkette `Firebird/InterBase(r) driver`.
Der Standardwert ist der im DSN definierte Treiber.

|DBNAME
.2+|Datenbank
.2+|Vollständiger Pfad zur Datenbank *vom Server* aus gesehen, einschließlich der IP-Adresse {vbar} Servername [/ Port] für eine Remoteverbindung.
Der Standardwert ist die im DSN definierte Datenbank.

|DATABASE

|CLIENT
|Lokaler Pfad zur erforderlichen ``fbclient``-Bibliothek
|Wird möglicherweise benötigt, wenn die Verbindung über eine eingebettete Serverbibliothek in einem Anwendungsordner hergestellt werden soll.

|CHARSET
.2+|Clientseitiger Standardzeichensatz
.2+|Sollte nach Möglichkeit der Standardzeichensatz der Datenbank sein;
oder eine, die bekanntermaßen Codepage-kompatibel ist.

|CHARACTERSET

|READONLY
|Nur-Lesen
|Setzen Sie Transaktionen in dieser Verbindung auf schreibgeschützt.
Der Standard ist Lesen / Schreiben.

|NOWAIT
|Nicht warten
|Setzen Sie Transaktionen in dieser Verbindung auf NO WAIT-Sperrmechanismus.
Der Standardwert ist WAIT.

|LOCKTIMEOUT
|Setzen Sie das Sperrzeitlimit für die WAIT-Transaktion
|Übergeben Sie die Anzahl der Sekunden, nach denen ein Sperrkonflikt auftritt, bis eine Transaktion einen Fehler zurückgibt.
Nicht gültig, wenn die Transaktion auf NO WAIT-Sperrmechanismus gesetzt ist.

|DIALECT
|Legt den SQL-Dialekt fest
|Nur 1 oder 3 ist gültig.
Normalerweise wäre dies in der DSN festgelegt worden.
Es muss dem Dialekt der Datenbank entsprechen.

|QUOTED
|In Anführungszeichen gesetzte Bezeichner festlegen
|Wenn im DSN festgelegt, sollte diese Einstellung korrekt sein, d.h. bereits EIN oder AUS.

|SENSITIVE
|Legt die Bezeichner für Groß- und Kleinschreibung fest.
|Wenn im DSN festgelegt, sollte die Einstellung korrekt sein, d.h. bereits EIN oder AUS.

|AUTOQUOTED
|Automatisch-Zitierende Bezeichner festlegen
|Wenn im DSN festgelegt, sollte die Einstellung korrekt sein, d.h. bereits EIN oder AUS.

|USESCHEMA
|Setzt "`use schema`" auf an
|Wenn im DSN festgelegt, sollte die Einstellung korrekt sein.

|SAFETHREAD
|Safe threading
|{nbsp}

|FILEDSN
|Datei-DSN
|Pfad zu einer Datei, in der die Attributstrings einer vorherigen Verbindung gespeichert sind.
Wenn diese Zeichenfolge vorhanden ist, hat der Inhalt der Datei Vorrang vor dem Haupt-DSN.

|SAVEDSN
|Save-DSN
|Pfad zu einer Datei, in der die Attributstrings dieser Verbindung bei Erfolg gespeichert werden sollen.
Das Passwort wird verschlüsselt gespeichert.
|===

[[fbodbc205-dsnkeys-readseq-de]]
=== Leserichtung der Schlüssel

Die ODBC-Funktion `SQLDriverConnect` weist den in der Verbindungszeichenfolge definierten Attributen ihre Priorität zu, wobei nur die in der DSN oder in einer angegebenen Datei-DSN gespeicherten Attribute abgerufen werden, um Lücken zu füllen.

[[fbodbc205-examples-connection-de]]
=== Verbindungsbeispiele

Einige Beispiele für Verbindungszeichenfolgen für Anwendungen, die die ODBC-Funktion `SQLDriverConnect` verwenden:

[source]
----
Open("DSN=myDb;")
----

Hier wird erwartet, dass die Funktion alles, was sie benötigt, aus dem DSN liest.
Benutzername und Passwort werden nicht in der Zeichenfolge angegeben.
Wenn sie auch nicht im DSN vorhanden werden

. die Umgebungsvariablen `ISC_PASSWORD` und `ISC_USER` verwendet, wenn sie gesetzt sind. Andernfalls
. wird es nach Benutzername und Kennwort fragen


[source]
----
Open("DSN=myDb; UID=MCSSITE; PWD=mcssite;")
----

Die Funktion sollte über die erforderlichen Voraussetzungen für die Herstellung dieser Verbindung verfügen,  vorausgesetzt, der Benutzername und das Kennwort werden vom Server authentifiziert.


[source]
----
Open("DSN=myDb; UID=MCSSITE; PWD=mcssite; DBNAME=172.17.2.10:/usr/local/db/myDb.fdb;")

Open("DSN=myDb; UID=MCSSITE; PWD=mcssite; DBNAME=myserver:/usr/local/db/myDb.fdb;")
----

Der Schlüssel `DBNAME` zeigt im ersten Beispiel auf die IP-Adresse des Servers mit dem Pfad zur Datenbankdatei im POSIX-Format.
Im zweiten Beispiel wird dieselbe Verbindung hergestellt, wobei der Host-Name des Servers anstelle der IP-Adresse verwendet wird. 

Drei Beispiele, die das ``DRIVER``-Attribut in der Zeichenfolge enthalten:

[source]
----
Open("DRIVER=Firebird/InterBase(r) driver; DBNAME=172.17.2.10:/usr/local/db/myDb.fdb;")

Open("DRIVER=Firebird/InterBase(r) driver; UID=MCSSITE; PWD=mcssite; DBNAME=172.17.2.10:/usr/local/db/myDb.fdb;")

Open("DRIVER=Firebird/InterBase(r) driver; UID=MCSSITE; PWD=mcssite; DBNAME=dummy;")
----

Im letzten Beispiel eine lokale Verbindung mit einem Datenbankalias anstelle des Datenbankdateipfads.
Natürlich muss der Alias  in `aliases.conf` im Root-Verzeichnis des Firebird-Servers vorhanden sein (oder, für Firebird 3 und höher, in `databases.conf`).

Verwenden der Server-IP-Adresse und Angabe eines alternativen Ports mit der Zieldatenbank auf einem POSIX-Server;
und  dasselbe mit dem Hostnamen des Servers:

[source]
----
172.17.2.10/3051:/usr/local/db/myDb.fdb

myserver/3051:/usr/local/db/myDb.fdb
----

Verwenden der Server-IP-Adresse mit der Zieldatenbank auf einem Windows-Server;
und dasselbe mit dem Hostnamen des Servers:

[source]
----
172.17.2.10:c:\db\myDb.fdb

myserver:c:\db\myDb.fdb
----

Verwenden der Server-IP-Adresse und Angeben eines alternativen Ports mit der Zieldatenbank auf einem Windows-Server;
und dasselbe mit dem Hostnamen des Servers:

[source]
----
172.17.2.10/3051:c:\db\myDb.fdb

myserver/3051:c:\db\myDb.fdb
----

Verwenden von lokalen TCP/IP-Loopbacks unter Verwendung der Loopback-IP-Adresse auf einem POSIX-Server;
und dasselbe mit dem Loopback Host-Namen `localhost`:
[source]
----
127.0.0.1:/usr/local/db/myDb.fdb

localhost:/usr/local/db/myDb.fdb
----

Die gleichen Dinge auf einem Windows-Server:

[source]
----
127.0.0.1:c:\db\myDb.fdb

localhost:c:\db\myDb.fdb
----

[[fbodbc205-examples-embedded-de]]
==== DBNAME für Embedded-Verbindungen

Der ``DBNAME``-Wert für eingebettete Verbindungen und für den Verbindungsstil "`Windows Local`" (XNET) verwendet nur den Dateipfad oder Alias ohne Hostnamen, IP-Adresse oder Portnummer.

[NOTE]
====
Ab Firebird 3 ist die Art und Weise, wie wir Nicht-Netzwerkverbindungen auf allen Plattformen konzeptualisieren, einheitlicher als für die früheren Versionen.
Aus der Sicht des ODBC/JDBC-Treibers hat sich jedoch der Ausdruck des ``DBNAME``-Werts nicht geändert, unabhängig von der Plattform, auf der wir unsere eingebettete Verbindung herstellen.
====

Lokale Verbindung auf einem Windows-Server, wobei zuerst der Dateipfad und anschließend ein Alias verwendet wird:

[source]
----
DBNAME=C:\db\myDb.fdb

DBNAME=C:dummy
----

Auf einem POSIX-Server:

[source]
----
DBNAME=/usr/local/db/myDb.fdb

DBNAME=dummy
----

[[fbodbc205-examples-aliases-de]]
==== DBNAME unter Verwendung eines Alias

Es wird dringend empfohlen, Aliase zu definieren und zu verwenden, um das Leben für Sie und Ihre Benutzer zu vereinfachen.
Es macht Ihre ``DBNAME``-Werte für das Dateisystem vollkommen neutral und um vieles weniger umständlich.
In unseren letzten Beispielpaaren wurde derselbe Alias sowohl für Windows als auch für POSIX verwendet.
Der auf dem Windows-Server wäre so definiert:

[source]
----
dummy = C:\db\myDb.fdb
----

während dieser auf dem Linux-Server definiert werden würde:

[source]
----
dummy = /usr/local/db/myDb.fdb
----
