[[fblangref30-ddl-exception-de]]
= `EXCEPTION`

In diesem Abschnitt wird beschrieben, wie Sie _benutzerdefinierte Ausnahmen_ zur Verwendung in Fehlerhandlern in PSQL-Modulen erstellen, ändern und löschen.

[[fblangref30-ddl-exception-create-de]]
== `CREATE EXCEPTION`

.Verwendet für
Erstellen einer neuen Ausnahme zur Verwendung in PSQL-Modulen

.Verfügbar in
DSQL, ESQL

[[fblangref30-ddl-exception-create-syntax-de]]
.Syntax
[listing,subs=+quotes]
----
CREATE EXCEPTION _exception_name_ '<message>'

<message> ::= <message-part> [<message-part> ...]

<message-part> ::=
    <text>
  | @<slot>

<slot> ::= _one of 1..9_
----

[[fblangref30-ddl-tbl-crtexcep-de]]
.`CREATE EXCEPTION`-Anweisungsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|exception_name
|Ausnahmename.
Die maximale Länge beträgt 31 Zeichen

|message
|Standardfehlermeldung.
Die maximale Länge beträgt 1.021 Zeichen

|text
|Text beliebiger Zeichen

|slot
|Slotnummer eines Parameters.
Die Nummerierung beginnt bei 1.
Die maximale Steckplatznummer ist 9.
|===

Die Anweisung `CREATE EXCEPTION` erzeugt eine neue Ausnahme zur Verwendung in PSQL-Modulen.
Existiert eine gleichnamige Ausnahme, schlägt die Anweisung mit einer entsprechenden Fehlermeldung fehl.

Der Ausnahmename ist ein Standardbezeichner.
In einer Dialect 3-Datenbank kann es in doppelte Anführungszeichen eingeschlossen werden, um die Groß-/Kleinschreibung zu berücksichtigen und bei Bedarf Zeichen zu verwenden, die in regulären Bezeichnern nicht gültig sind.
Weitere Informationen finden Sie unter <<fblangref30-structure-identifiers-de,Bezeichner>>.

Die Standardnachricht wird im Zeichensatz `NONE` gespeichert, d.h. in Zeichen eines beliebigen Einzelbyte-Zeichensatzes.
Der Text kann im PSQL-Code überschrieben werden, wenn die Ausnahme ausgelöst wird.

Die Fehlermeldung kann "`Parameter-Slots`" enthalten, die beim Auslösen der Ausnahme gefüllt werden können.

[WARNING]
====
Wenn die _message_ eine Parameter-Slot-Nummer enthält, die größer als 9 ist, werden die zweite und die nachfolgenden Ziffern als Literaltext behandelt.
Zum Beispiel wird `@10` als Slot 1 interpretiert, gefolgt von einem Literal '```0```'.
====

[NOTE]
====
Benutzerdefinierte Ausnahmen werden in der Systemtabelle <<fblangref-appx04-Exceptions-de,`RDB$EXCEPTIONS`>> gespeichert.
====

[[fblangref30-ddl-exception-createpriv-de]]
=== Wer kann eine Ausnahme erstellen

Die `CREATE EXCEPTION`-Anweisung kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Benutzer mit dem Privileg `CREATE EXCEPTION``

Der Benutzer, der die Anweisung `CREATE EXCEPTION` ausführt, wird Eigentümer der Ausnahme.

[[fblangref30-ddl-exception-exmpl-de]]
=== `CREATE EXCEPTION`-Beispiele

.Erstellen einer Ausnahme namens `E_LARGE_VALUE`
[source]
----
CREATE EXCEPTION E_LARGE_VALUE
  'The value is out of range';
----

.Erstellen einer parametrisierten Ausnahme `E_INVALID_VALUE`
[source]
----
CREATE EXCEPTION E_INVALID_VALUE
  'Invalid value @1 for field @2';
----

.Tips
[TIP]
====
Die Gruppierung von `CREATE EXCEPTION`-Anweisungen in Systemaktualisierungsskripten vereinfacht die Arbeit mit ihnen und deren Dokumentation.
Ein System von Präfixen zur Benennung und Kategorisierung von Ausnahmegruppen wird empfohlen.
====

.Siehe auch
<<fblangref30-ddl-exception-alter-de>>, <<fblangref30-ddl-exception-crtalter-de>>, <<fblangref30-ddl-exception-drop-de>>, <<fblangref30-ddl-exception-recreate-de>>

[[fblangref30-ddl-exception-alter-de]]
== `ALTER EXCEPTION`

.Verwendet für
Ändern der von einer benutzerdefinierten Ausnahme zurückgegebenen Nachricht

.Verfügbar in
DSQL, ESQL

.Syntax
[listing,subs="+quotes,macros"]
----
ALTER EXCEPTION _exception_name_ '<message>'

!! Vgl. auch <<fblangref30-ddl-exception-create-syntax-de,`CREATE EXCEPTION`>> für weitere Regeln !!
----

Die Anweisung `ALTER EXCEPTION` kann jederzeit verwendet werden, um den Standardtext der Nachricht zu ändern.

[[fblangref30-ddl-exception-alterpriv-de]]
=== Wer kann eine Ausnahme ändern?

Die Anweisung `ALTER EXCEPTION` kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Der Inhaber der Ausnahme
* Benutzer mit der Berechtigung `ALTER ANY EXCEPTION`

[[fblangref30-ddl-exception-alter-exmpl-de]]
=== `ALTER EXCEPTION`-Beispiele

.Ändern der Standardnachricht für die Ausnahme `E_LARGE_VALUE`
[source]
----
ALTER EXCEPTION E_LARGE_VALUE
  'The value exceeds the prescribed limit of 32,765 bytes';
----

.Siehe auch
<<fblangref30-ddl-exception-create-de>>, <<fblangref30-ddl-exception-crtalter-de>>, <<fblangref30-ddl-exception-drop-de>>, <<fblangref30-ddl-exception-recreate-de>>

[[fblangref30-ddl-exception-crtalter-de]]
== `CREATE OR ALTER EXCEPTION`

.Verwendet für
Ändern der von einer benutzerdefinierten Ausnahme zurückgegebenen Nachricht, falls die Ausnahme vorhanden ist;
andernfalls eine neue Ausnahme erstellen

.Verfügbar in
DSQL

.Syntax
[listing,subs="+quotes,macros"]
----
CREATE OR ALTER EXCEPTION _exception_name_ '<message>'

!! Vgl. Syntax von <<fblangref30-ddl-exception-create-syntax-de,`CREATE EXCEPTION`>> für weitere Regeln !!
----

Die Anweisung `CREATE OR ALTER EXCEPTION` wird verwendet, um die angegebene Ausnahme zu erstellen, falls sie nicht existiert, oder um den Text der von ihr zurückgegebenen Fehlermeldung zu ändern, wenn sie bereits existiert.
Wenn eine bestehende Ausnahme durch diese Anweisung geändert wird, bleiben alle bestehenden Abhängigkeiten erhalten.

[[fblangref30-ddl-exception-crtalter-exmpl-de]]
=== `CREATE OR ALTER EXCEPTION`-Beispiel

.Ändern der Nachricht für die Ausnahme `E_LARGE_VALUE`
[source]
----
CREATE OR ALTER EXCEPTION E_LARGE_VALUE
  'The value is higher than the permitted range 0 to 32,765';
----

.Siehe auch
<<fblangref30-ddl-exception-create-de>>, <<fblangref30-ddl-exception-alter-de>>, <<fblangref30-ddl-exception-recreate-de>>

[[fblangref30-ddl-exception-drop-de]]
== `DROP EXCEPTION`

.Verwendet für
Löschen einer benutzerdefinierten Ausnahme

.Verfügbar in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
DROP EXCEPTION _exception_name_
----

[[fblangref30-ddl-tbl-dropexcep-de]]
.`DROP EXCEPTION`-Anweisungsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|exception_name
|Exception name
|===

Die Anweisung `DROP EXCEPTION` dient zum Löschen einer Ausnahme.
Alle Abhängigkeiten von der Ausnahme führen dazu, dass die Anweisung fehlschlägt und die Ausnahme nicht gelöscht wird.

[[fblangref30-ddl-exception-droppriv-de]]
=== Wer kann eine Ausnahme fallen lassen?

Die `DROP EXCEPTION`-Anweisung kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Der Inhaber der Ausnahme
* Benutzer mit dem Privileg `DROP ANY EXCEPTION`

[[fblangref30-ddl-exception-drop-exmpl-de]]
=== `DROP EXCEPTION`-Beispiele

.Ausnahme `E_LARGE_VALUE` wird gelöscht
[source]
----
DROP EXCEPTION E_LARGE_VALUE;
----

.Siehe auch
<<fblangref30-ddl-exception-create-de>>, <<fblangref30-ddl-exception-recreate-de>>

[[fblangref30-ddl-exception-recreate-de]]
== `RECREATE EXCEPTION`

.Verwendet für
Erstellen einer neuen benutzerdefinierten Ausnahme oder Neuerstellen einer vorhandenen Ausnahme

.Verfügbar in
DSQL

.Syntax
[listing,subs="+quotes,macros"]
----
RECREATE EXCEPTION _exception_name_ '<message>'

!! Vgl. Syntax <<fblangref30-ddl-exception-create-syntax,`CREATE EXCEPTION`>> für weitere Regeln !!
----

Die Anweisung `RECREATE EXCEPTION` erzeugt eine neue Ausnahme zur Verwendung in PSQL-Modulen.
Wenn bereits eine Ausnahme mit demselben Namen existiert, versucht die Anweisung `RECREATE EXCEPTION`, sie zu löschen und eine neue zu erstellen.
Wenn Abhängigkeiten von der bestehenden Ausnahme bestehen, schlägt der Löschversuch fehl und `RECREATE EXCEPTION` wird nicht ausgeführt.

[[fblangref30-ddl-exception-recreate-exmpl-de]]
=== `RECREATE EXCEPTION`-Beispiel

.Ausnahme `E_LARGE_VALUE` neu erstellen
[source]
----
RECREATE EXCEPTION E_LARGE_VALUE
  'The value exceeds its limit';
----

.Siehe auch
<<fblangref30-ddl-exception-create-de>>, <<fblangref30-ddl-exception-drop-de>>, <<fblangref30-ddl-exception-crtalter-de>>
