[[fblangref30-ddl-package-de]]
= `PACKAGE`

Ein Paket ist eine Gruppe von Prozeduren und Funktionen, die als eine Einheit verwaltet werden.

[[fblangref30-ddl-pkg-create-de]]
== `CREATE PACKAGE`

.Verwendet für
Paket-Header deklarieren

.Verfügbar in
DSQL

[[fblangref30-ddl-pkg-create-syntax-de]]
.Syntax
[listing,subs="+quotes,macros"]
----
CREATE PACKAGE _package_name_
AS
BEGIN
  [ <package_item> ... ]
END

<package_item> ::=
    <function_decl>;
  | <procedure_decl>;

<function_decl> ::=
  FUNCTION _funcname_ [ ( [ <in_params> ] ) ]
  RETURNS <domain_or_non_array_type> [COLLATE _collation_]
  [DETERMINISTIC]

<procedure_decl> ::=
  PROCEDURE _procname_ [ ( [ <in_params> ] ) ]
  [RETURNS (<out_params>)]

<in_params> ::= <inparam> [, <inparam> ... ]

<inparam> ::= <param_decl> [ { = | DEFAULT } <value> ]

<out_params> ::= <outparam> [, <outparam> ...]

<outparam> ::= <param_decl>

<value> ::= { _literal_ | NULL | _context_var_ }

<param-decl> ::= _paramname_ <domain_or_non_array_type> [NOT NULL]
  [COLLATE _collation_]

<domain_or_non_array_type> ::=
  !! Siehe auch <<fblangref30-datatypes-syntax-scalar-de,Skalardatentypen-Syntax>> !!
----

[[fblangref30-ddl-tbl-createpkg-de]]
.`CREATE PACKAGE`-Anweisungsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|package_name
|Paketname bestehend aus bis zu 31 Zeichen.
Der Paketname muss unter allen Paketnamen eindeutig sein.

|function_decl
|Funktionsdeklaration

|procedure_decl
|Prozedurdeklaration

|func_name
|Funktionsname bestehend aus bis zu 31 Zeichen.
Der Funktionsname muss innerhalb des Pakets eindeutig sein.

|proc_name
|Prozedurname bestehend aus bis zu 31 Zeichen.
Der Funktionsname muss innerhalb des Pakets eindeutig sein.

|collation
|Sortierreihenfolge

|inparam
|Deklaration der Eingabeparameter

|outparam
|Deklaration der Ausgabeparameter

|literal
|Ein Literalwert, der mit dem Datentyp des Parameters zuweisungskompatibel ist

|context_var
|Jede Kontextvariable, die mit dem Datentyp des Parameters zuweisungskompatibel ist

|paramname
|Der Name eines Eingabeparameters einer Prozedur oder Funktion oder eines Ausgabeparameters einer Prozedur.
Er kann aus bis zu 31 Zeichen bestehen.
Der Name des Parameters muss unter den Eingabe- und Ausgabeparametern der Prozedur oder Funktion eindeutig sein.
|===

Die Anweisung `CREATE PACKAGE` erstellt einen neuen Paket-Header.
Im Paketheader deklarierte Routinen (Prozeduren und Funktionen) sind außerhalb des Pakets unter Verwendung des vollständigen Bezeichners (__package_name__.__proc_name__ oder __package_name__.__func_name__) verfügbar.
Routinen, die nur im Paketrumpf definiert sind – aber nicht im Paketkopf – sind außerhalb des Pakets nicht sichtbar.

[[fblangref30-ddl-pkg-routine-shadowing-de]]
.Paketprozedur- und Funktionsnamen können globale Routinen überschatten
[NOTE]
====
Wenn ein Paketheader oder Paketrumpf eine Prozedur oder Funktion mit demselben Namen wie eine gespeicherte Prozedur oder Funktion im globalen Namespace deklariert, ist es nicht möglich, diese globale Prozedur oder Funktion aus dem Paketrumpf aufzurufen.
In diesem Fall wird immer die Prozedur oder Funktion des Pakets aufgerufen.

Aus diesem Grund wird empfohlen, dass sich die Namen von gespeicherten Prozeduren und Funktionen in Paketen nicht mit Namen von gespeicherten Prozeduren und Funktionen im globalen Namespace überschneiden.
====

[[fblangref30-ddl-terminators04-de]]
=== Statement-Terminatoren

Einige SQL-Anweisungseditoren – insbesondere das mit Firebird gelieferte Dienstprogramm _isql_ und möglicherweise einige Editoren von Drittanbietern – verwenden eine interne Konvention, die erfordert, dass alle Anweisungen mit einem Semikolon abgeschlossen werden.
Dies führt beim Codieren in diesen Umgebungen zu einem Konflikt mit der PSQL-Syntax.
Wenn Sie dieses Problem und seine Lösung nicht kennen, lesen Sie bitte die Details im PSQL-Kapitel im Abschnitt <<fblangref30-sidebar01-de,Umschalten des Terminators in _isql_>>.

[[fblangref30-ddl-pkg-create-procfunc-de]]
=== Verfahrens- und Funktionsparameter

Ausführliche Informationen zu Parametern für gespeicherte Prozeduren finden Sie unter <<fblangref30-ddl-proc-params-de>> in <<fblangref30-ddl-proc-create-de>>.

Einzelheiten zu Funktionsparametern finden Sie unter <<fblangref30-ddl-func-params-de>> in <<fblangref30-ddl-func-create-de>>.

[[fblangref30-ddl-pkg-create-who-de]]
=== Wer kann ein Paket erstellen

Die `CREATE PACKAGE`-Anweisung kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Benutzer mit dem Privileg `CREATE PACKAGE`

Der Benutzer, der den Paketheader erstellt hat, wird sein Besitzer.

[[fblangref30-ddl-pkg-create-example-de]]
=== Beispiele für `CREATE PACKAGE`

.Erstellen Sie einen Paket-Header
[source]
----
CREATE PACKAGE APP_VAR
AS
BEGIN
  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC;
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC;
  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE,
      ADATEEND DATE DEFAULT CURRENT_DATE);
END
----

.Siehe auch
<<fblangref30-ddl-pkg-body-create-de,`CREATE PACKAGE BODY`>>, <<fblangref30-ddl-pkg-body-recreate-de,`RECREATE PACKAGE BODY`>>, <<fblangref30-ddl-pkg-alter-de>>, <<fblangref30-ddl-pkg-drop-de>>, <<fblangref30-ddl-pkg-recreate-de>>

[[fblangref30-ddl-pkg-alter-de]]
== `ALTER PACKAGE`

.Verwendet für
Ändern des Paketheaders

.Verfügbar in
DSQL

.Syntax
[listing,subs="+quotes,macros"]
----
ALTER PACKAGE _package_name_
AS
BEGIN
  [ <package_item> ... ]
END

!! Vgl. Syntax <<fblangref30-ddl-pkg-create-syntax-de,`CREATE PACKAGE`>> für weitere Regeln!!
----

Die `ALTER PACKAGE`-Anweisung modifiziert den Paket-Header.
Es kann verwendet werden, um die Anzahl und Definition von Prozeduren und Funktionen einschließlich ihrer Ein- und Ausgabeparameter zu ändern.
Der Quelltext und die kompilierte Form des Paketkörpers werden jedoch beibehalten, obwohl der Körper nach der Änderung des Paketheaders möglicherweise inkompatibel ist.
Die Gültigkeit eines Paketkörpers für den definierten Header wird in der Spalte `RDB$PACKAGES.RDB$VALID_BODY_FLAG` gespeichert.

[[fblangref30-ddl-pkg-alter-who-de]]
=== Wer kann ein Paket ändern

Die `ALTER PACKAGE`-Anweisung kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Der Besitzer des Pakets
* Benutzer mit der Berechtigung `ALTER ANY PACKAGE`

[[fblangref30-ddl-pkg-alter-example-de]]
=== Beispiel für `ALTER PACKAGE`

.Ändern eines Paketheaders
[source]
----
ALTER PACKAGE APP_VAR
AS
BEGIN
  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC;
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC;
  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE,
      ADATEEND DATE DEFAULT CURRENT_DATE);
END
----

.Siehe auch
<<fblangref30-ddl-pkg-create-de>>, <<fblangref30-ddl-pkg-drop-de>>, <<fblangref30-ddl-pkg-body-alter-de,`ALTER PACKAGE BODY`>>, <<fblangref30-ddl-pkg-body-recreate-de,`RECREATE PACKAGE BODY`>>

[[fblangref30-ddl-pkg-createalter-de]]
== `CREATE OR ALTER PACKAGE`

.Verwendet für
Erstellen eines neuen oder Ändern eines bestehenden Paket-Headers

.Verfügbar in
DSQL

.Syntax
[listing,subs="+quotes,macros"]
----
CREATE OR ALTER PACKAGE _package_name_
AS
BEGIN
  [ <package_item> ... ]
END

!! Siehe auch Syntax <<fblangref30-ddl-pkg-create-syntax-de,`CREATE PACKAGE`>> für weitere Regeln!!
----

Die Anweisung `CREATE OR ALTER PACKAGE` erstellt ein neues Paket oder ändert einen vorhandenen Paket-Header.
Existiert der Paket-Header nicht, wird er mit `CREATE PACKAGE` erstellt.
Wenn es bereits existiert, wird es mit `ALTER PACKAGE` modifiziert, während bestehende Privilegien und Abhängigkeiten beibehalten werden.

[[fblangref30-ddl-pkg-createalter-example-de]]
=== Beispiel für `CREATE OR ALTER PACKAGE`

.Erstellen eines neuen oder Ändern eines vorhandenen Paketheaders
[source]
----
CREATE OR ALTER PACKAGE APP_VAR
AS
BEGIN
  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC;
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC;
  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE,
      ADATEEND DATE DEFAULT CURRENT_DATE);
END
----

.Siehe auch
<<fblangref30-ddl-pkg-create-de>>, <<fblangref30-ddl-pkg-alter-de>>, <<fblangref30-ddl-pkg-recreate-de>>, <<fblangref30-ddl-pkg-body-alter-de,`ALTER PACKAGE BODY`>>, <<fblangref30-ddl-pkg-body-recreate-de,`RECREATE PACKAGE BODY`>>

[[fblangref30-ddl-pkg-drop-de]]
== `DROP PACKAGE`

.Verwendet für
Einen Paket-Header löschen

.Verfügbar in
DSQL

.Syntax
[listing,subs="+quotes"]
----
DROP PACKAGE _package_name_
----

[[fblangref30-ddl-tbl-droppkg-de]]
.`DROP PACKAGE`-Anweisungsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|package_name
|Paketname
|===

Die `DROP PACKAGE`-Anweisung löscht einen vorhandenen Paket-Header.
Wenn ein Paketkörper vorhanden ist, wird er zusammen mit dem Paketkopf gelöscht.
Wenn noch Abhängigkeiten vom Paket bestehen, wird ein Fehler ausgegeben.

[[fblangref30-ddl-pkg-drop-who-de]]
=== Wer kann ein Paket abgeben

Die `DROP PACKAGE`-Anweisung kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Der Besitzer des Pakets
* Benutzer mit der Berechtigung `DROP ANY PACKAGE`

[[fblangref30-ddl-pkg-drop-example-de]]
=== Beispiel für `DROP PACKAGE`

.Einen Paket-Header löschen
[source]
----
DROP PACKAGE APP_VAR
----

.Siehe auch
<<fblangref30-ddl-pkg-create-de>>, <<fblangref30-ddl-pkg-body-drop-de,`DROP PACKAGE BODY`>>

[[fblangref30-ddl-pkg-recreate-de]]
== `RECREATE PACKAGE`

.Verwendet für
Erstellen eines neuen oder erneuten Erstellens eines vorhandenen Paketheaders

.Verfügbar in
DSQL

.Syntax
[listing,subs="+quotes,macros"]
----
RECREATE PACKAGE _package_name_
AS
BEGIN
  [ <package_item> ... ]
END

!! Siehe auch Syntax <<fblangref30-ddl-pkg-create-syntax-de,`CREATE PACKAGE`>> für weitere Regeln!!
----

Die Anweisung `RECREATE PACKAGE` erstellt ein neues Paket oder erstellt einen vorhandenen Paket-Header neu.
Wenn bereits ein Paketheader mit demselben Namen vorhanden ist, wird dieser durch diese Anweisung zuerst gelöscht und dann ein neuer Paketheader erstellt.
Es ist nicht möglich, den Paketheader neu zu erstellen, wenn noch Abhängigkeiten von dem vorhandenen Paket bestehen oder wenn der Hauptteil des Pakets vorhanden ist.
Bestehende Privilegien des Pakets selbst werden nicht beibehalten, ebenso wenig Privilegien zum Ausführen der Prozeduren oder Funktionen des Pakets.

[[fblangref30-ddl-pkg-recreate-example-de]]
=== Beispiel für `RECREATE PACKAGE`

.Erstellen eines neuen oder erneuten Erstellens eines vorhandenen Paketheaders
[source]
----
RECREATE PACKAGE APP_VAR
AS
BEGIN
  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC;
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC;
  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE,
      ADATEEND DATE DEFAULT CURRENT_DATE);
END
----

.Siehe auch
<<fblangref30-ddl-pkg-create-de>>, <<fblangref30-ddl-pkg-drop-de>>, <<fblangref30-ddl-pkg-body-create-de,`CREATE PACKAGE BODY`>>, <<fblangref30-ddl-pkg-body-recreate-de,`RECREATE PACKAGE BODY`>>
