[[fblangref30-ddl-function-de]]
= `FUNCTION`

Eine gespeicherte Funktion ist eine benutzerdefinierte Funktion, die in den Metadaten einer Datenbank gespeichert ist und auf dem Server ausgeführt wird.
Gespeicherte Funktionen können von gespeicherten Prozeduren, gespeicherten Funktionen (einschließlich der Funktion selbst), Triggern und Client-Programmen aufgerufen werden.
Wenn sich eine gespeicherte Funktion selbst aufruft, wird eine solche gespeicherte Funktion als rekursive Funktion bezeichnet.

Im Gegensatz zu gespeicherten Prozeduren geben gespeicherte Funktionen immer einen einzelnen Skalarwert zurück.
Um einen Wert aus einer gespeicherten Funktion zurückzugeben, verwenden Sie die `RETURN`-Anweisung, die die Funktion sofort beendet.

.Siehe auch
<<fblangref30-ddl-extfunc-de,`EXTERNAL FUNCTION`>>

[[fblangref30-ddl-func-create-de]]
== `CREATE FUNCTION`

.Verwendet für
Erstellen einer neuen gespeicherten Funktion

.Verfügbar in
DSQL

[[fblangref30-ddl-func-create-syntax-de]]
.Syntax
[listing,subs="+quotes,macros"]
----
CREATE FUNCTION _funcname_ [ ( [ <in_params> ] ) ]
  RETURNS <domain_or_non_array_type> [COLLATE _collation_]
  [DETERMINISTIC]
  <module-body>

<module-body> ::=
  !! Vgl. <<fblangref30-psql-elements-body-syntax-de,Syntax des Modulrumpfes>> !!

<in_params> ::= <inparam> [, <inparam> ... ]

<inparam> ::= <param-decl> [ { = | DEFAULT } <value> ]

<value> ::= { <literal> | NULL | <context-var> }

<param-decl> ::= _paramname_ <domain_or_non_array_type> [NOT NULL]
  [COLLATE _collation_]

<domain_or_non_array_type> ::=
  !! Vgl. <<fblangref30-datatypes-syntax-scalar-de,Skalardatentyp-Syntax>> !!
----

[[fblangref30-ddl-tbl-createfunc-de]]
.`CREATE FUNCTION`-Anweisungsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|funcname
|Gespeicherter Funktionsname bestehend aus bis zu 31 Zeichen.
Muss unter allen Funktionsnamen in der Datenbank eindeutig sein.

|inparam
|Beschreibung der Eingabeparameter

|collation
|Sortierreihenfolge

|literal
|Ein Literalwert, der mit dem Datentyp des Parameters zuweisungskompatibel ist

|context-var
|Jede Kontextvariable, deren Typ mit dem Datentyp des Parameters kompatibel ist

|paramname
|Der Name eines Eingabeparameters der Funktion.
Er kann aus bis zu 31 Zeichen bestehen.
Der Name des Parameters muss unter den Eingabeparametern der Funktion und ihren lokalen Variablen eindeutig sein.
|===

Die Anweisung `CREATE FUNCTION` erstellt eine neue gespeicherte Funktion.
Der gespeicherte Funktionsname muss unter den Namen aller gespeicherten und externen (alten) Funktionen eindeutig sein, mit Ausnahme von Unterfunktionen oder Funktionen in Paketen.
Bei Unterfunktionen oder Funktionen in Paketen muss der Name innerhalb ihres Moduls (Paket, Stored Procedure, Stored Function, Trigger) eindeutig sein.

[NOTE]
====
Es ist ratsam, Funktionsnamen zwischen globalen gespeicherten Funktionen und gespeicherten Funktionen in Paketen nicht wiederzuverwenden, obwohl dies zulässig ist.
Momentan ist es nicht möglich, eine Funktion oder Prozedur aus dem globalen Namensraum innerhalb eines Pakets aufzurufen, wenn dieses Paket eine Funktion oder Prozedur mit demselben Namen definiert.
In dieser Situation wird die Funktion oder Prozedur des Pakets aufgerufen.
====

`CREATE FUNCTION` ist eine zusammengesetzte Anweisung mit einem Header und einem Body.
Der Header definiert den Namen der gespeicherten Funktion und deklariert Eingabeparameter und Rückgabetyp.

Der Funktionsrumpf besteht aus optionalen Deklarationen von lokalen Variablen, benannten Cursorn und Unterprogrammen (Unterfunktionen und Unterprozeduren) und einer oder mehreren Anweisungen oder Anweisungsblöcken, eingeschlossen in einen äußeren Block, der mit dem Schlüsselwort `BEGIN` beginnt und endet mit dem Schlüsselwort `END`.
Deklarationen und Anweisungen innerhalb des Funktionsrumpfs müssen mit einem Semikolon ('```;```') abgeschlossen werden.

[[fblangref30-ddl-terminators03-de]]
=== Statement-Terminatoren

Einige SQL-Anweisungseditoren – insbesondere das mit Firebird gelieferte Dienstprogramm _isql_ und möglicherweise einige Editoren von Drittanbietern – verwenden eine interne Konvention, die erfordert, dass alle Anweisungen mit einem Semikolon abgeschlossen werden.
Dies führt beim Codieren in diesen Umgebungen zu einem Konflikt mit der PSQL-Syntax.
Wenn Sie dieses Problem und seine Lösung nicht kennen, lesen Sie bitte die Details im PSQL-Kapitel im Abschnitt <<fblangref30-sidebar01-de,Terminator in _isql_>> umschalten.

[[fblangref30-ddl-func-params-de]]
=== Parameter

Jeder Parameter hat einen Datentyp.

Eine Kollatierungssequenz kann für String-Typ-Parameter mit der `COLLATE`-Klausel angegeben werden.

Eingabeparameter::
Eingabeparameter werden als Liste in Klammern nach dem Namen der Funktion angezeigt.
Sie werden als Wert an die Funktion übergeben, sodass Änderungen innerhalb der Funktion keine Auswirkungen auf die Parameter im Aufrufer haben.
Die `NOT NULL`-Einschränkung kann auch für jeden Eingabeparameter angegeben werden, um zu verhindern, dass `NULL` übergeben oder zugewiesen wird.
Eingabeparameter können Standardwerte haben.
Parameter mit angegebenen Standardwerten müssen am Ende der Parameterliste hinzugefügt werden.

Ausgabeparameter::
Die `RETURNS`-Klausel gibt den Rückgabetyp der gespeicherten Funktion an.
Wenn eine Funktion einen String-Wert zurückgibt, ist es möglich, die Sortierung mit der `COLLATE`-Klausel anzugeben.
Als Rückgabetyp können Sie einen Datentyp, einen Domänennamen, den Typ einer Domäne (mit `TYPE OF`) oder den Typ einer Spalte einer Tabelle oder View (mit `TYPE OF COLUMN`) angeben.

[[fblangref30-ddl-func-create-deterministic-de]]
=== Deterministische Funktionen

Die optionale `DETERMINISTIC`-Klausel gibt an, dass die Funktion deterministisch ist.
Deterministische Funktionen geben immer das gleiche Ergebnis für den gleichen Satz von Eingaben zurück.
Nicht-deterministische Funktionen können für jeden Aufruf unterschiedliche Ergebnisse zurückgeben, sogar für denselben Satz von Eingaben.
Wenn eine Funktion als deterministisch angegeben ist, wird eine solche Funktion möglicherweise nicht erneut aufgerufen, wenn sie bereits einmal mit den angegebenen Eingaben aufgerufen wurde, sondern übernimmt das Ergebnis aus einem Metadaten-Cache.

[NOTE]
====
Aktuelle Versionen von Firebird speichern Ergebnisse deterministischer Funktionen nicht wirklich.

Die Angabe der `DETERMINISTIC`-Klausel ist eigentlich so etwas wie ein "`Versprechen`", dass die Funktion für gleiche Eingaben dasselbe zurückgibt.
Im Moment wird eine deterministische Funktion als Invariante betrachtet und funktioniert wie andere Invarianten.
Das heißt, sie werden auf der aktuellen Ausführungsebene einer bestimmten Anweisung berechnet und zwischengespeichert.

Dies lässt sich leicht an einem Beispiel demonstrieren:

[source]
----
CREATE FUNCTION FN_T
RETURNS DOUBLE PRECISION DETERMINISTIC
AS
BEGIN
  RETURN rand ();
END;

- die Funktion wird zweimal ausgewertet und gibt 2 verschiedene Werte zurück
SELECT fn_t () FROM rdb $ database
UNION ALL
SELECT fn_t () FROM rdb $ database;

- die Funktion wird einmal ausgewertet und gibt 2 identische Werte zurück
WITH t (n) AS (
  SELECT 1 FROM rdb $ database
  UNION ALL
  SELECT 2 FROM rdb $ database
)
SELECT n, fn_t () FROM
----
====

[[fblangref30-ddl-func-declarations-de]]
=== Variablen-, Cursor- und Sub-Routine-Deklarationen

Der optionale Deklarationsabschnitt, der sich am Anfang des Hauptteils der Funktionsdefinition befindet, definiert Variablen (einschließlich Cursors) und funktionslokale Unterroutinen.
Lokale Variablendeklarationen folgen den gleichen Regeln wie Parameter bezüglich der Angabe des Datentyps.
Weitere Informationen finden Sie im <<fblangref30-psql-de,PSQL-Kapitel>> für <<fblangref30-psql-declare-variable-de,`DECLARE VARIABLE`>>, <<fblangref30-psql-declare-cursor-de,`DECLARE CURSOR`>>, <<fblangref30-psql-declfunc-de,`DECLARE FUNCTION`>> und <<fblangref30-psql-declproc-de,`DECLARE PROCEDURE`>>.

[[fblangref30-ddl-func-funcbody-de]]
=== Funktionsrumpf

Auf den Header-Abschnitt folgt der Funktionsrumpf, der aus einer oder mehreren PSQL-Anweisungen besteht, die zwischen den äußeren Schlüsselwörtern `BEGIN` und `END` eingeschlossen sind.
Mehrere `BEGIN ... END`-Blöcke von beendeten Anweisungen können in den Prozedurrumpf eingebettet werden.

[[fblangref30-ddl-func-create-udr-de]]
=== Externe UDR-Funktionen

Eine gespeicherte Funktion kann sich auch in einem externen Modul befinden.
In diesem Fall spezifiziert `CREATE FUNCTION` anstelle eines Funktionsrumpfs die Position der Funktion im externen Modul mit der `EXTERNAL`-Klausel.
Die optionale `NAME`-Klausel spezifiziert den Namen des externen Moduls, den Namen der Funktion innerhalb des Moduls und – optional – benutzerdefinierte Informationen.
Die erforderliche `ENGINE`-Klausel gibt den Namen der UDR-Engine an, die die Kommunikation zwischen Firebird und dem externen Modul handhabt.
Die optionale `AS`-Klausel akzeptiert ein String-Literal "`body`", das von der Engine oder dem Modul für verschiedene Zwecke verwendet werden kann.

[WARNING]
====
Externe UDR (User Defined Routine)-Funktionen, die mit `CREATE FUNCTION ... EXTERNAL ...` erstellt wurden, sollten nicht mit älteren UDFs (User Defined Functions) verwechselt werden, die mit `DECLARE EXTERNAL FUNCTION` deklariert wurden.

UDFs sind veraltet und ein Erbe früherer Firebird-Funktionen.
Ihre Fähigkeiten sind den Fähigkeiten der neuen Art von externen UDR-Funktionen deutlich unterlegen.
====

[[fblangref30-ddl-func-create-who-de]]
=== Wer kann eine Funktion erstellen?

Die `CREATE FUNCTION`-Anweisung kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Benutzer mit dem Privileg `CREATE FUNCTION`TION

Der Benutzer, der die gespeicherte Funktion erstellt hat, wird deren Eigentümer.

[[fblangref30-ddl-func-create-example-de]]
=== `CREATE FUNCTION`-Beispiele

. Erstellen einer gespeicherten Funktion
+
[source]
----
CREATE FUNCTION ADD_INT (A INT, B INT DEFAULT 0)
RETURNS INT
AS
BEGIN
  RETURN A + B;
END
----
+
Aufruf einer Auswahl:
+
[source]
----
SELECT ADD_INT(2, 3) AS R FROM RDB$DATABASE
----
+
Aufruf innerhalb von PSQL-Code, der zweite optionale Parameter wird nicht angegeben:
+
[source]
----
MY_VAR = ADD_INT(A);
----

. Erstellen einer deterministischen gespeicherten Funktion
+
[source]
----
CREATE FUNCTION FN_E()
RETURNS DOUBLE PRECISION DETERMINISTIC
AS
BEGIN
  RETURN EXP(1);
END
----

. Erstellen einer gespeicherten Funktion mit Parametern vom Typ Tabellenspalte
+
Gibt den Namen eines Typs nach Feldname und Wert zurück
+
[source]
----
CREATE FUNCTION GET_MNEMONIC (
  AFIELD_NAME TYPE OF COLUMN RDB$TYPES.RDB$FIELD_NAME,
  ATYPE TYPE OF COLUMN RDB$TYPES.RDB$TYPE)
RETURNS TYPE OF COLUMN RDB$TYPES.RDB$TYPE_NAME
AS
BEGIN
  RETURN (SELECT RDB$TYPE_NAME
          FROM RDB$TYPES
          WHERE RDB$FIELD_NAME = :AFIELD_NAME
          AND RDB$TYPE = :ATYPE);
END
----

. Erstellen einer extern gespeicherten Funktion
+
Erstellen Sie eine Funktion, die sich in einem externen Modul (UDR) befindet.
Die Funktionsimplementierung befindet sich im externen Modul `udrcpp_example`.
Der Name der Funktion innerhalb des Moduls ist `wait_event`.
+
[source]
----
CREATE FUNCTION wait_event (
  event_name varchar (31) CHARACTER SET ascii
) RETURNS INTEGER
EXTERNAL NAME 'udrcpp_example!Wait_event'
ENGINE udr
----

. Erstellen einer gespeicherten Funktion mit einer Unterfunktion
+
Erstellen einer Funktion zum Konvertieren einer Zahl in das Hexadezimalformat.
+
[source]
----
CREATE FUNCTION INT_TO_HEX (
  ANumber BIGINT ,
  AByte_Per_Number SMALLINT = 8)
RETURNS CHAR (66)
AS
DECLARE VARIABLE xMod SMALLINT ;
DECLARE VARIABLE xResult VARCHAR (64);
DECLARE FUNCTION TO_HEX (ANum SMALLINT ) RETURNS CHAR
  AS
  BEGIN
    RETURN CASE ANum
      WHEN 0 THEN '0'
      WHEN 1 THEN '1'
      WHEN 2 THEN '2'
      WHEN 3 THEN '3'
      WHEN 4 THEN '4'
      WHEN 5 THEN '5'
      WHEN 6 THEN '6'
      WHEN 7 THEN '7'
      WHEN 8 THEN '8'
      WHEN 9 THEN '9'
      WHEN 10 THEN 'A'
      WHEN 11 THEN 'B'
      WHEN 12 THEN 'C'
      WHEN 13 THEN 'D'
      WHEN 14 THEN 'E'
      WHEN 15 THEN 'F'
      ELSE NULL
    END;
  END
BEGIN
  xMod = MOD (ANumber, 16);
  ANumber = ANumber / 16;
  xResult = TO_HEX (xMod);
  WHILE (ANUMBER> 0) DO
  BEGIN
    xMod = MOD (ANumber, 16);
    ANumber = ANumber / 16;
    xResult = TO_HEX (xMod) || xResult;
  END
  RETURN '0x' || LPAD (xResult, AByte_Per_Number * 2, '0' );
END
----

.Siehe auch
<<fblangref30-ddl-func-creatalter-de>>, <<fblangref30-ddl-func-alter-de>>, <<fblangref30-ddl-func-recreate-de>>, <<fblangref30-ddl-func-drop-de>>, <<fblangref30-ddl-extfunc-declare-de>>

[[fblangref30-ddl-func-alter-de]]
== `ALTER FUNCTION`

.Verwendet für
Ändern einer vorhandenen gespeicherten Funktion

.Verfügbar in
DSQL

.Syntax
[listing,subs="+quotes,macros"]
----
ALTER FUNCTION _funcname_
  [ ( [ <in_params> ] ) ]
  RETURNS <domain_or_non_array_type> [COLLATE _collation_]
  [DETERMINISTIC]
  <module-body>

!! Vgl. Syntax <<fblangref30-ddl-func-create-syntax-de,`CREATE FUNCTION`>> für weitere Regeln !!
----

Die `ALTER FUNCTION`-Anweisung erlaubt die folgenden Änderungen an einer gespeicherten Funktionsdefinition:

* der Satz und die Eigenschaften des Eingangs- und Ausgangstyps
* lokale Variablen, benannte Cursor und Unterprogramme
* Code im Hauptteil der gespeicherten Prozedur

Für externe Funktionen (UDR) können Sie den Einstiegspunkt und den Engine-Namen ändern.
Für ältere externe Funktionen, die mit `DECLARE EXTERNAL FUNCTION` deklariert wurden – auch als UDFs bekannt – ist es nicht möglich, in PSQL zu konvertieren und umgekehrt.

Nachdem `ALTER FUNCTION` ausgeführt wurde, bleiben bestehende Privilegien intakt und Abhängigkeiten werden nicht beeinflusst.

[CAUTION]
====
Achten Sie darauf, die Anzahl und den Typ der Eingabeparameter und den Ausgabetyp einer gespeicherten Funktion zu ändern.
Vorhandener Anwendungscode und Prozeduren, Funktionen und Trigger, die ihn aufrufen, könnten ungültig werden, weil die neue Beschreibung der Parameter nicht mit dem alten Aufrufformat kompatibel ist.
Informationen zur Fehlerbehebung in einer solchen Situation finden Sie im Artikel <<fblangref30-appx01-supp-rdb-validblr-de,Das `RDB$VALID_BLR`-Feld>> im Anhang.
====

[[fblangref30-ddl-func-alter-who-de]]
=== Wer kann eine Funktion ändern

Die `ALTER FUNCTION`-Anweisung kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Inhaber der gespeicherten Funktion
* Benutzer mit der Berechtigung `ALTER ANY FUNCTION`

[[fblangref30-ddl-func-alter-example-de]]
=== Beispiele für `ALTER FUNCTION`

.Ändern einer gespeicherten Funktion
[source]
----
ALTER FUNCTION ADD_INT(A INT, B INT, C INT)
RETURNS INT
AS
BEGIN
  RETURN A + B + C;
END
----

.Siehe auch
<<fblangref30-ddl-func-create-de>>, <<fblangref30-ddl-func-creatalter-de>>, <<fblangref30-ddl-func-recreate-de>>, <<fblangref30-ddl-func-drop-de>>

[[fblangref30-ddl-func-creatalter-de]]
== `CREATE OR ALTER FUNCTION`

.Verwendet für
Erstellen einer neuen oder Ändern einer vorhandenen gespeicherten Funktion

.Verfügbar in
DSQL

.Syntax
[listing,subs="+quotes,macros"]
----
CREATE OR ALTER FUNCTION _funcname_
  [ ( [ <in_params> ] ) ]
  RETURNS <domain_or_non_array_type> [COLLATE _collation_]
  [DETERMINISTIC]
  <module-body>

!! Vgl. Syntax <<fblangref30-ddl-func-create-syntax-de,`CREATE FUNCTION`>> für weitere Regeln !!
----

Die Anweisung `CREATE OR ALTER FUNCTION` erstellt eine neue gespeicherte Funktion oder ändert eine vorhandene.
Wenn die gespeicherte Funktion nicht existiert, wird sie durch transparentes Aufrufen einer `CREATE FUNCTION`-Anweisung erstellt.
Wenn die Funktion bereits existiert, wird sie geändert und kompiliert (durch `ALTER FUNCTION`), ohne ihre bestehenden Privilegien und Abhängigkeiten zu beeinträchtigen.

[[fblangref30-ddl-func-creatalter-exmpl-de]]
=== Beispiele für `CREATE OR ALTER FUNCTION`

.Erstellen Sie eine neue oder ändern Sie eine vorhandene gespeicherte Funktion
[syntax]
----
CREATE OR ALTER FUNCTION ADD_INT(A INT, B INT DEFAULT 0)
RETURNS INT
AS
BEGIN
  RETURN A + B;
END
----

.Siehe auch
<<fblangref30-ddl-func-create-de>>, <<fblangref30-ddl-func-alter-de>>, <<fblangref30-ddl-func-drop-de>>

[[fblangref30-ddl-func-drop-de]]
== `DROP FUNCTION`

.Verwendet für
Löschen einer gespeicherten Funktion

.Verfügbar in
DSQL

.Syntax
[listing,subs="+quotes,macros"]
----
DROP FUNCTION _funcname_
----

[[fblangref30-ddl-tbl-dropfunc]]
.`DROP FUNCTION`-Anweisungsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|funcname
|Gespeicherter Funktionsname bestehend aus bis zu 31 Zeichen.
Muss unter allen Funktionsnamen in der Datenbank eindeutig sein.
|===

Die `DROP FUNCTION`-Anweisung löscht eine vorhandene gespeicherte Funktion.
Wenn die gespeicherte Funktion Abhängigkeiten aufweist, schlägt der Versuch, sie zu löschen, fehl und der entsprechende Fehler wird ausgegeben.

[[fblangref30-ddl-func-drop-who-de]]
=== Wer kann eine Funktion löschen?

Die `DROP FUNCTION`-Anweisung kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Inhaber der gespeicherten Funktion
* Benutzer mit dem Privileg `DROP ANY FUNCTION`

[[fblangref30-ddl-func-drop-example-de]]
=== Beispiele für `DROP FUNCTION`

[source]
----
DROP FUNCTION ADD_INT;
----

.Siehe auch
<<fblangref30-ddl-func-create-de>>, <<fblangref30-ddl-func-creatalter-de>>, <<fblangref30-ddl-func-recreate-de>>

[[fblangref30-ddl-func-recreate-de]]
== `RECREATE FUNCTION`

.Verwendet für
Erstellen einer neuen gespeicherten Funktion oder Neuerstellen einer vorhandenen Funktion

.Verfügbar in
DSQL

.Syntax
[listing,subs="+quotes,macros"]
----
RECREATE FUNCTION _funcname_
  [ ( [ <in_params> ] ) ]
  RETURNS <domain_or_non_array_type> [COLLATE _collation_]
  [DETERMINISTIC]
  <module-body>

!! Vgl. Syntax <<fblangref30-ddl-func-create-syntax-de,`CREATE FUNCTION`>> für weitere Regeln !!
----

Die Anweisung 'RECREATE FUNCTION' erstellt eine neue gespeicherte Funktion oder erstellt eine vorhandene neu.
Wenn es bereits eine Funktion mit diesem Namen gibt, versucht die Engine, sie zu löschen und dann eine neue zu erstellen.
Das Neuerstellen einer vorhandenen Funktion schlägt bei `COMMIT` fehl, wenn die Funktion Abhängigkeiten hat.

[NOTE]
====
Beachten Sie, dass Abhängigkeitsfehler erst in der `COMMIT`-Phase dieser Operation erkannt werden.
====

Nachdem eine Prozedur erfolgreich neu erstellt wurde, werden vorhandene Berechtigungen zum Ausführen der gespeicherten Funktion und der
Berechtigungen der gespeicherten Funktion selbst werden verworfen.

[[fblangref30-ddl-func-recreate-example-de]]
=== Beispiele für `RECREATE FUNCTION`

.Erstellen oder Wiederherstellen einer gespeicherten Funktion
[source]
----
RECREATE FUNCTION ADD_INT(A INT, B INT DEFAULT 0)
RETURNS INT
AS
BEGIN
  RETURN A + B;
EN
----

.Siehe auch
<<fblangref30-ddl-func-create-de>>, <<fblangref30-ddl-func-drop-de>>
