[[fblangref30-ddl-package-body-de]]
= `PACKAGE BODY`

[[fblangref30-ddl-pkg-body-create-de]]
== `CREATE PACKAGE BODY`

.Verwendet für
Erstellen des Paketrumpfes

.Verfügbar in
DSQL

[[fblangref30-ddl-pkg-body-create-syntax-de]]
.Syntax
[listing,subs="+quotes,macros"]
----
CREATE PACKAGE BODY _name_
AS
BEGIN
  [ <package_item> ... ]
  [ <package_body_item> ... ]
END

<package_item> ::=
  !! Siehe auch <<fblangref30-ddl-pkg-create-syntax-de,`CREATE PACKAGE`-Syntax>> !!

<package_body_item> ::=
  <function_impl> |
  <procedure_impl>

<function_impl> ::=
  FUNCTION _funcname_ [ ( [ <in_params> ] ) ]
  RETURNS <domain_or_non_array_type> [COLLATE _collation_]
  [DETERMINISTIC]
  <module-body>

<procedure_impl> ::=
  PROCEDURE _procname_ [ ( [ <in_params> ] ) ]
  [RETURNS (<out_params>)]
  <module-body>

<module-body> ::=
  !! Siehe auch <<fblangref30-psql-elements-body-syntax-de,Syntax des Modul-Bodys>> !!

<in_params> ::=
  !! Siehe auch <<fblangref30-ddl-pkg-create-syntax-de,`CREATE PACKAGE`-Syntax>> !!
  !! Siehe auch die _Regeln_ weiter unten !!

<out_params> ::=
  !! Siehe auch <<fblangref30-ddl-pkg-create-syntax-de,`CREATE PACKAGE`-Syntax>> !!

<domain_or_non_array_type> ::=
  !! Siehe auch <<fblangref30-datatypes-syntax-scalar-de,Syntax der Skalardatentypen>> !!
----

[[fblangref30-ddl-tbl-createpkgbdy-de]]
.`CREATE PACKAGE BODY`-Anweisungsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|package_name
|Paketname bestehend aus bis zu 31 Zeichen.
Der Paketname muss unter allen Paketnamen eindeutig sein.

|function_impl
|Funktionsimplementierung.
Im Wesentlichen eine <<fblangref30-ddl-func-create-de,`CREATE FUNCTION`>>-Anweisung ohne `CREATE`.

|procedure_impl
|Verfahrensimplementierung
Im Wesentlichen eine <<fblangref30-ddl-proc-create-de,`CREATE PROCEDURE`>>-Anweisung ohne `CREATE`.

|func_name
|Funktionsname bestehend aus bis zu 31 Zeichen.
Der Funktionsname muss innerhalb des Pakets eindeutig sein.

|collation
|Sortierreihenfolge

|proc_name
|Prozedurname bestehend aus bis zu 31 Zeichen.
Der Funktionsname muss innerhalb des Pakets eindeutig sein.
|===

Die Anweisung `CREATE PACKAGE BODY` erstellt einen neuen Paketkörper.
Der Paketkörper kann erst erstellt werden, nachdem der Paketkopf erstellt wurde.
Wenn kein Paketheader mit dem Namen _package_name_ vorhanden ist, wird ein entsprechender Fehler ausgegeben.

Alle im Paketkopf deklarierten Prozeduren und Funktionen müssen im Paketrumpf implementiert werden.
Zusätzliche Prozeduren und Funktionen dürfen nur im Paketrumpf definiert und implementiert werden.
Prozeduren und Funktionen, die im Paketrumpf definiert, aber nicht im Paketkopf definiert sind, sind außerhalb des Paketrumpfs nicht sichtbar.

Die Namen von Prozeduren und Funktionen, die im Paketrumpf definiert sind, müssen unter den Namen von Prozeduren und Funktionen, die im Paketkopf definiert und im Paketrumpf implementiert sind, eindeutig sein.

[[fblangref30-ddl-pkg-body-routine-shadowing-de]]
.Paketprozedur- und Funktionsnamen können globale Routinen überschatten
[NOTE]
====
Wenn ein Paketheader oder Paketrumpf eine Prozedur oder Funktion mit demselben Namen wie eine gespeicherte Prozedur oder Funktion im globalen Namespace deklariert, ist es nicht möglich, diese globale Prozedur oder Funktion aus dem Paketrumpf aufzurufen.
In diesem Fall wird immer die Prozedur oder Funktion des Pakets aufgerufen.

Aus diesem Grund wird empfohlen, dass sich die Namen von gespeicherten Prozeduren und Funktionen in Paketen nicht mit Namen von gespeicherten Prozeduren und Funktionen im globalen Namespace überschneiden.
====

.Regeln
* Im Paketrumpf müssen alle Prozeduren und Funktionen mit derselben Signatur implementiert werden, die im Header und am Anfang des Paketrumpfs deklariert ist
* Die Standardwerte für Prozedur- oder Funktionsparameter können nicht überschrieben werden (wie im Paketkopf oder in _<package_item>_ angegeben).
Dies bedeutet, dass Standardwerte nur in _<package_body_item>_ für Prozeduren oder Funktionen definiert werden können, die nicht im Paketkopf oder früher im Paketrumpf definiert wurden.

[NOTE]
====
UDF-Deklarationen (`DECLARE EXTERNAL FUNCTION`) werden für Pakete nicht unterstützt.
Verwenden Sie stattdessen UDR.
====

[[fblangref30-ddl-pkg-body-create-who-de]]
=== Wer kann einen Paketkörper erstellen

Die Anweisung `CREATE PACKAGE BODY` kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Der Besitzer des Pakets
* Benutzer mit der Berechtigung `ALTER ANY PACKAGE`

[[fblangref30-ddl-pkg-body-create-example-de]]
=== Beispiel für `CREATE PACKAGE BODY`

.Erstellen des Paketkörpers
[source]
----
CREATE PACKAGE BODY APP_VAR
AS
BEGIN
  - Gibt das Startdatum der Periode zurück
  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEBEGIN');
  END
  - Gibt das Enddatum des Zeitraums zurück
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEEND');
  END
  - Legt den Datumsbereich des Arbeitszeitraums fest
  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE)
  AS
  BEGIN
    RDB$SET_CONTEXT('USER_SESSION', 'DATEBEGIN', ADATEBEGIN);
    RDB$SET_CONTEXT('USER_SESSION', 'DATEEND', ADATEEND);
  END
END
----

.Siehe auch
<<fblangref30-ddl-pkg-body-alter-de>>, <<fblangref30-ddl-pkg-body-drop-de>>, <<fblangref30-ddl-pkg-body-recreate-de>>, <<fblangref30-ddl-pkg-create-de,`CREATE PACKAGE`>>

[[fblangref30-ddl-pkg-body-alter-de]]
== `ALTER PACKAGE BODY`

.Verwendet für
Ändern des Paketrumpfes

.Verfügbar in
DSQL

.Syntax
[listing,subs="+quotes,macros"]
----
ALTER PACKAGE BODY _name_
AS
BEGIN
  [ <package_item> ... ]
  [ <package_body_item> ... ]
END

!! Siehe auch Syntax <<fblangref30-ddl-pkg-body-create-syntax-de,`CREATE PACKAGE BODY`>> für weitere Regeln !!
----

Die Anweisung `ALTER PACKAGE BODY` modifiziert den Paketrumpf.
Es kann verwendet werden, um die Definition und Implementierung von Prozeduren und Funktionen des Paketkörpers zu ändern.

Siehe <<fblangref30-ddl-pkg-body-create-de>> für weitere Details.

[[fblangref30-ddl-pkg-body-alter-who-de]]
=== Wer kann einen Paketkörper ändern?

Die Anweisung `ALTER PACKAGE BODY` kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Der Besitzer des Pakets
* Benutzer mit der Berechtigung `ALTER ANY PACKAGE`

[[fblangref30-ddl-pkg-body-alter-example-de]]
=== Beispiel für `ALTER PACKAGE BODY`

.Ändern des Paketkörpers
[source]
----
ALTER PACKAGE BODY APP_VAR
AS
BEGIN
  - Gibt das Startdatum der Periode zurück
  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEBEGIN');
  END
  - Gibt das Enddatum des Zeitraums zurück
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEEND');
  END
  - Legt den Datumsbereich des Arbeitszeitraums fest
  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE)
  AS
  BEGIN
    RDB$SET_CONTEXT('USER_SESSION', 'DATEBEGIN', ADATEBEGIN);
    RDB$SET_CONTEXT('USER_SESSION', 'DATEEND', ADATEEND);
  END
END
----

.Siehe auch
<<fblangref30-ddl-pkg-body-create-de>>, <<fblangref30-ddl-pkg-body-drop-de>>, <<fblangref30-ddl-pkg-body-recreate-de>>, <<fblangref30-ddl-pkg-alter-de,`ALTER PACKAGE`>>

[[fblangref30-ddl-pkg-body-drop-de]]
== `DROP PACKAGE BODY`

.Verwendet für
Löschen des Paketrumpfes

.Verfügbar in
DSQL

.Syntax
[listing,subs="+quotes"]
----
DROP PACKAGE _package_name_
----

[[fblangref30-ddl-tbl-droppkg-body-de]]
.`DROP PACKAGE BODY`-Anweisungsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|package_name
|Paketname
|===

Die Anweisung `DROP PACKAGE BODY` löscht den Paketkörper.

[[fblangref30-ddl-pkg-body-drop-who-de]]
=== Wer kann einen Paketkörper fallen lassen?

Die `DROP PACKAGE BODY`-Anweisung kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Der Besitzer des Pakets
* Benutzer mit der Berechtigung `ALTER ANY PACKAGE`

[[fblangref30-ddl-pkg-body-drop-example-de]]
=== Beispiel für `DROP PACKAGE BODY`

.Löschen des Paketrumpfes
[source]
----
DROP PACKAGE BODY APP_VAR;
----

.Siehe auch
<<fblangref30-ddl-pkg-body-create-de>>, <<fblangref30-ddl-pkg-body-alter-de>>, <<fblangref30-ddl-pkg-drop-de,`DROP PACKAGE`>>

[[fblangref30-ddl-pkg-body-recreate-de]]
== `RECREATE PACKAGE BODY`

.Verwendet für
Erstellen eines neuen oder erneuten Erstellens eines vorhandenen Paketrumpfes

.Verfügbar in
DSQL

.Syntax
[listing,subs="+quotes,macros"]
----
RECREATE PACKAGE BODY _name_
AS
BEGIN
  [ <package_item> ... ]
  [ <package_body_item> ... ]
END

!! Siehe auch Syntax <<fblangref30-ddl-pkg-body-create-syntax-de,`CREATE PACKAGE BODY`>> für weitere Regeln !!
----

Die Anweisung `RECREATE PACKAGE BODY` erstellt einen neuen oder erstellt einen bestehenden Paketkörper neu.
Wenn bereits ein Paketkörper mit demselben Namen vorhanden ist, versucht die Anweisung, ihn zu löschen und dann einen neuen Paketkörper zu erstellen.
Nach der Neuerstellung des Paketkörpers bleiben die Berechtigungen des Pakets und seiner Routinen erhalten.

Siehe <<fblangref30-ddl-pkg-body-create-de>> für weitere Details.

[[fblangref30-ddl-pkg-body-recreate-example-de]]
=== Beispiele für `RECREATE PACKAGE BODY`

.Neuerstellen des Paketrumpfes
[source]
----
RECREATE PACKAGE BODY APP_VAR
AS
BEGIN
  - Gibt das Startdatum der Periode zurück
  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEBEGIN');
  END
  - Gibt das Enddatum des Zeitraums zurück
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEEND');
  END
  - Legt den Datumsbereich des Arbeitszeitraums fest
  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE)
  AS
  BEGIN
    RDB$SET_CONTEXT('USER_SESSION', 'DATEBEGIN', ADATEBEGIN);
    RDB$SET_CONTEXT('USER_SESSION', 'DATEEND', ADATEEND);
  END
END
----

.Siehe auch
<<fblangref30-ddl-pkg-body-create-de>>, <<fblangref30-ddl-pkg-body-alter-de>>, <<fblangref30-ddl-pkg-body-drop-de>>, <<fblangref30-ddl-pkg-alter-de,`ALTER PACKAGE`>>
