[[fblangref30-ddl-domn-de]]
= `DOMAIN`

`DOMAIN` ist einer der Objekttypen in einer relationalen Datenbank.
Eine Domain wird als ein bestimmter Datentyp mit einigen daran angehängten Attributen erstellt.
Nachdem es in der Datenbank definiert wurde, kann es wiederholt verwendet werden, um Tabellenspalten, PSQL-Argumente und lokale PSQL-Variablen zu definieren.
Diese Objekte erben alle Attribute der Domain.
Einige Attribute können bei Bedarf überschrieben werden, wenn das neue Objekt definiert wird.

In diesem Abschnitt wird die Syntax von Anweisungen zum Erstellen, Ändern und Löschen von Domainn beschrieben.
Eine detaillierte Beschreibung der Domains und ihrer Verwendung finden Sie in <<fblangref30-datatypes-custom-de,Benutzerdefinierte Datentypen -- Domains>>.

[[fblangref30-ddl-domn-create-de]]
== `CREATE DOMAIN`

.Verwendet für
Erstellen einer neuen Domain

.Verfügbar in
DSQL, ESQL

[[fblangref30-ddl-domn-create-syntax-de]]
.Syntax
[listing,subs="+quotes,macros"]
----
CREATE DOMAIN _name_ [AS] <datatype>
  [DEFAULT {<literal> | NULL | <context_var>}]
  [NOT NULL] [CHECK (<dom_condition>)]
  [COLLATE _collation_name_]

<datatype> ::=
  <scalar_datatype> | <blob_datatype> | <array_datatype>

<scalar_datatype> ::=
  !! Siehe auch <<fblangref30-datatypes-syntax-scalar-de,Skalardatentyp-Syntax>> !!

<blob_datatype> ::=
  !! Siehe auch <<fblangref30-datatypes-syntax-blob-de,BLOB-Datentyp-Syntax>> !!

<array_datatype> ::=
  !! Siehe auch <<fblangref30-datatypes-syntax-array-de,Array-Datentyp-Syntax>> !!

<dom_condition> ::=
    <val> <operator> <val>
  | <val> [NOT] BETWEEN <val> AND <val>
  | <val> [NOT] IN ({<val> [, <val> ...] | <select_list>})
  | <val> IS [NOT] NULL
  | <val> IS [NOT] DISTINCT FROM <val>
  | <val> [NOT] CONTAINING <val>
  | <val> [NOT] STARTING [WITH] <val>
  | <val> [NOT] LIKE <val> [ESCAPE <val>]
  | <val> [NOT] SIMILAR TO <val> [ESCAPE <val>]
  | <val> <operator> {ALL | SOME | ANY} (<select_list>)
  | [NOT] EXISTS (<select_expr>)
  | [NOT] SINGULAR (<select_expr>)
  | (<dom_condition>)
  | NOT <dom_condition>
  | <dom_condition> OR <dom_condition>
  | <dom_condition> AND <dom_condition>

<operator> ::=
    <> | != | ^= | ~= | = | < | > | <= | >=
  | !< | ^< | ~< | !> | ^> | ~>

<val> ::=
    VALUE
  | <literal>
  | <context_var>
  | <expression>
  | NULL
  | NEXT VALUE FOR _genname_
  | GEN_ID(_genname_, <val>)
  | CAST(<val> AS <cast_type>)
  | (<select_one>)
  | _func_([<val> [, <val> ...]])

<cast_type> ::= <domain_or_non_array_type> | <array_datatype>

<domain_or_non_array_type> ::=
  !! See <<fblangref30-datatypes-syntax-scalar-syntax-de,Syntax für Skalardatentypen>> !!
----

[[fblangref30-ddl-tbl-createdomn-de]]
.`CREATE DOMAIN`-Anweisungsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|name
|Domainname bestehend aus bis zu 31 Zeichen

|datatype
|SQL-Datentyp

|literal
|Ein Literalwert, der mit _datatype_ kompatibel ist

|context_var
|Jede Kontextvariable, deren Typ mit _datatype_ kompatibel ist

|dom_condition
|Domain-Bedingung

|collation_name
|Name einer Kollatierungssequenz, die für _charset_name_ gültig ist, wenn sie mit _datatype_ versorgt wird oder ansonsten für den Standardzeichensatz der Datenbank gültig ist

|select_one
|Eine skalare `SELECT`-Anweisung – Auswahl einer Spalte und Rückgabe nur einer Zeile

|select_list
|Eine `SELECT`-Anweisung, die eine Spalte auswählt und null oder mehr Zeilen zurückgibt

|select_expr
|Eine `SELECT`-Anweisung, die eine oder mehrere Spalten auswählt und null oder mehr Zeilen zurückgibt

|expression
|Ein Ausdruck, der in einen Wert aufgelöst wird, der mit _datatype_ kompatibel ist

|genname
|Sequenzname (Generatorname)

|func
|Interne Funktion oder UDF
|===

Die `CREATE DOMAIN`-Anweisung erstellt eine neue Domain.

Als Domaintyp kann jeder SQL-Datentyp angegeben werden.

[[fblangref30-ddl-domn-typespec-de]]
=== Typspezifische Details

Array-Typen::
* Wenn die Domain ein Array sein soll, kann der Basistyp ein beliebiger SQL-Datentyp außer `BLOB` und Array sein.
* Die Dimensionen des Arrays sind in eckigen Klammern angegeben.
(Im Syntaxblock erscheinen diese Klammern in Anführungszeichen, um sie von den eckigen Klammern zu unterscheiden, die optionale Syntaxelemente kennzeichnen.)
* Für jede Array-Dimension definieren eine oder zwei ganze Zahlen die untere und obere Grenze ihres Indexbereichs:
** Arrays sind standardmäßig 1-basiert.
Die untere Grenze ist implizit und nur die obere Grenze muss angegeben werden.
Eine einzelne Zahl kleiner als 1 definiert den Bereich __num__..1 und eine Zahl größer als 1 definiert den Bereich 1..__num__.
** Zwei durch einen Doppelpunkt getrennte Zahlen ('```:```') und optionales Leerzeichen, das zweite größer als das erste, können verwendet werden, um den Bereich explizit zu definieren.
Eine oder beide Grenzen können kleiner als Null sein, solange die obere Grenze größer als die untere ist.
* Wenn das Array mehrere Dimensionen hat, müssen die Bereichsdefinitionen für jede Dimension durch Kommas und optionales Leerzeichen getrennt werden.
* Indizes werden _nur_ validiert, wenn tatsächlich ein Array existiert.
Das bedeutet, dass keine Fehlermeldungen bezüglich ungültiger Indizes zurückgegeben werden, wenn die Auswahl eines bestimmten Elements nichts zurückgibt oder wenn ein Array-Feld [constant]`NULL` ist.

String-Typen::
Mit der `CHARACTER SET`-Klausel können Sie den Zeichensatz für die Typen `CHAR`, `VARCHAR` und `BLOB` (`SUB_TYPE TEXT`) angeben.
Wenn der Zeichensatz nicht angegeben ist, wird der als `DEFAULT CHARACTER SET` angegebene Zeichensatz der Datenbank verwendet.
Wenn kein Zeichensatz angegeben wurde, wird beim Erstellen einer Zeichendomäne standardmäßig der Zeichensatz `NONE` verwendet.
+
[WARNING]
====
Mit dem Zeichensatz `NONE` werden Zeichendaten so gespeichert und abgerufen, wie sie übermittelt wurden.
Daten in einer beliebigen Codierung können einer Spalte basierend auf einer solchen Domain hinzugefügt werden, aber es ist unmöglich, diese Daten zu einer Spalte mit einer anderen Codierung hinzuzufügen.
Da keine Transliteration zwischen den Quell- und Zielcodierungen durchgeführt wird, können Fehler auftreten.
====

`DEFAULT`-Klausel::
Mit der optionalen `DEFAULT`-Klausel können Sie einen Standardwert für die Domain angeben.
Dieser Wert wird der Tabellenspalte hinzugefügt, die diese Domain erbt, wenn die `INSERT`-Anweisung ausgeführt wird, wenn kein Wert dafür in der DML-Anweisung angegeben ist.
Lokale Variablen und Argumente in PSQL-Modulen, die auf diese Domain verweisen, werden mit dem Standardwert initialisiert.
Verwenden Sie als Standardwert ein Literal eines kompatiblen Typs oder eine Kontextvariable eines kompatiblen Typs.

`NOT NULL` Constraint::
Spalten und Variablen, die auf einer Domain mit der Einschränkung `NOT NULL` basieren, werden daran gehindert, als `NULL` geschrieben zu werden, d.h. ein Wert ist _erforderlich_.
+
[CAUTION]
====
Achten Sie beim Anlegen einer Domain darauf, keine Einschränkungen anzugeben, die sich widersprechen würden.
Zum Beispiel sind `NOT NULL` und `DEFAULT NULL` widersprüchlich.
====

`CHECK` Constraint(s)::
Die optionale `CHECK`-Klausel gibt Einschränkungen für die Domain an.
Eine Domainneinschränkung gibt Bedingungen an, die von den Werten von Tabellenspalten oder Variablen erfüllt werden müssen, die von der Domain erben.
Eine Bedingung muss in Klammern eingeschlossen werden.
Eine Bedingung ist ein logischer Ausdruck (auch Prädikat genannt), der die booleschen Ergebnisse `TRUE`, `FALSE` und `UNKNOWN` zurückgeben kann.
Eine Bedingung gilt als erfüllt, wenn das Prädikat den Wert `TRUE` oder „`unknown value`“ (entspricht `NULL`) zurückgibt. Liefert das Prädikat `FALSE`, ist die Annahmebedingung nicht erfüllt.

`VALUE` Keyword::
Das Schlüsselwort `VALUE` in einer Domainneinschränkung ersetzt die Tabellenspalte, die auf dieser Domain basiert, oder eine Variable in einem PSQL-Modul.
Es enthält den Wert, der der Variablen oder der Tabellenspalte zugewiesen wurde. `VALUE` kann überall in der `CHECK`-Bedingung verwendet werden, obwohl es normalerweise im linken Teil der Bedingung verwendet wird.

`COLLATE`::
Mit der optionalen `COLLATE`-Klausel können Sie die Kollatierungssequenz angeben, wenn die Domain auf einem der String-Datentypen basiert, einschließlich ``BLOB``s mit Textuntertypen.
Wenn keine Kollatierungssequenz angegeben ist, ist die Kollatierungssequenz diejenige, die zum Zeitpunkt der Erstellung der Domain für den angegebenen Zeichensatz voreingestellt ist.

[[fblangref30-ddl-domn-create-who-de]]
=== Wer kann eine Domain erstellen

Die `CREATE DOMAIN`-Anweisung kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Benutzer mit der Berechtigung `CREATE DOMAIN`

[[fblangref30-ddl-createdomnexmpls-de]]
=== `CREATE DOMAIN`-Beispiele

. Erstellen einer Domain, die Werte über 1.000 annehmen kann, mit einem Standardwert von 10.000.
+
[source]
----
CREATE DOMAIN CUSTNO AS
  INTEGER DEFAULT 10000
  CHECK (VALUE > 1000);
----
. Erstellen einer Domain, die die Werte 'Yes' und 'No' in dem beim Erstellen der Datenbank angegebenen Standardzeichensatz annehmen kann.
+
[source]
----
CREATE DOMAIN D_BOOLEAN AS
  CHAR(3) CHECK (VALUE IN ('Yes', 'No'));
----
. Erstellen einer Domain mit dem Zeichensatz `UTF8` und der Kollatierungssequenz `UNICODE_CI_AI`.
+
[source]
----
CREATE DOMAIN FIRSTNAME AS
  VARCHAR(30) CHARACTER SET UTF8
  COLLATE UNICODE_CI_AI;
----
. Erstellen einer Domain vom Typ `DATE`, die NULL nicht akzeptiert und das aktuelle Datum als Standardwert verwendet.
+
[source]
----
CREATE DOMAIN D_DATE AS
  DATE DEFAULT CURRENT_DATE
  NOT NULL;
----
. Erstellen einer Domain, die als Array aus 2 Elementen des Typs `NUMERIC(18, 3)` definiert ist. Der Array-Startindex ist 1.
+
[source]
----
CREATE DOMAIN D_POINT AS
  NUMERIC(18, 3) [2];
----
+
[NOTE]
====
Über einen Array-Typ definierte Domainn können nur zum Definieren von Tabellenspalten verwendet werden.
Sie können keine Arraydomänen verwenden, um lokale Variablen in PSQL-Modulen zu definieren.
====
. Erstellen einer Domain, deren Elemente nur Ländercodes sein können, die in der Tabelle `COUNTRY` definiert sind.
+
[source]
----
CREATE DOMAIN D_COUNTRYCODE AS CHAR(3)
  CHECK (EXISTS(SELECT * FROM COUNTRY
         WHERE COUNTRYCODE = VALUE));
----
+
[NOTE]
====
Das Beispiel wird nur gegeben, um die Möglichkeit zu zeigen, Prädikate mit Abfragen in der Domainntestbedingung zu verwenden.
Es wird nicht empfohlen, diesen Domainnstil in der Praxis zu erstellen, es sei denn, die Nachschlagetabelle enthält Daten, die niemals gelöscht werden.
====

.Siehe auch
<<fblangref30-ddl-domn-alter-de>>, <<fblangref30-ddl-domn-drop-de>>

[[fblangref30-ddl-domn-alter-de]]
== `ALTER DOMAIN`

.Verwendet für
Die aktuellen Attribute einer Domain ändern oder umbenennen

.Verfügbar in
DSQL, ESQL

.Syntax
[listing,subs="+quotes,macros"]
----
ALTER DOMAIN _domain_name_
  [TO _new_name_]
  [TYPE <datatype>]
  [{SET DEFAULT {<literal> | NULL | <context_var>} | DROP DEFAULT}]
  [{SET | DROP} NOT NULL]
  [{ADD [CONSTRAINT] CHECK (<dom_condition>) | DROP CONSTRAINT}]

<datatype> ::=
   <scalar_datatype> | <blob_datatype>

<scalar_datatype> ::=
  !! Vgl. <<fblangref30-datatypes-syntax-scalar-de,Syntax für Skalardatentypen>> !!

<blob_datatype> ::=
  !! Vgl. <<fblangref30-datatypes-syntax-blob-de,Syntax für BLOB-Datentypen>> !!

!! Siehe auch <<fblangref30-ddl-domn-create-syntax-de,`CREATE DOMAIN`-Syntax>> !!
----

[[fblangref30-ddl-tbl-alterdomn-de]]
.`ALTER DOMAIN`-Anweisungsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|new_name
|Neuer Name für Domain, bestehend aus bis zu 31 Zeichen

|literal
|Ein Literalwert, der mit _datatype_ kompatibel ist

|context_var
|Jede Kontextvariable, deren Typ mit _datatype_ kompatibel ist
|===

Die `ALTER DOMAIN`-Anweisung ermöglicht Änderungen an den aktuellen Attributen einer Domain, einschließlich ihres Namens.
Sie können beliebig viele Domain-Änderungen in einer `ALTER DOMAIN`-Anweisung vornehmen.

[[fblangref30-ddl-domn-alter-opts-de]]
=== `ALTER DOMAIN`-Klausel

`TO __name__`::
Verwenden Sie die `TO`-Klausel, um die Domain umzubenennen, solange keine Abhängigkeiten von der Domain bestehen, d.h.
Tabellenspalten, lokale Variablen oder Prozedurargumente, die darauf verweisen.

`SET DEFAULT`::
Mit der `SET DEFAULT`-Klausel können Sie einen neuen Standardwert setzen.
Wenn die Domain bereits einen Standardwert hat, muss dieser nicht zuerst gelöscht werden – er wird durch den neuen ersetzt.

`DROP DEFAULT`::
Verwenden Sie diese Klausel, um einen zuvor angegebenen Standardwert zu löschen und durch `NULL` zu ersetzen.

`SET NOT NULL`::
Verwenden Sie diese Klasse, um der Domain eine `NOT NULL`-Einschränkung hinzuzufügen;
Spalten oder Parameter dieser Domain werden daran gehindert, als `NULL` geschrieben zu werden, d.h. ein Wert ist _erforderlich_.
+
[NOTE]
====
Das Hinzufügen einer `NOT NULL`-Einschränkung zu einer vorhandenen Domain unterzieht alle Spalten, die diese Domain verwenden, einer vollständigen Datenvalidierung. Stellen Sie daher sicher, dass die Spalten keine Nullen enthalten, bevor Sie die Änderung vornehmen.
====

`DROP NOT NULL`::
Löschen Sie die Einschränkung `NOT NULL` aus der Domain.
+
[NOTE]
====
Eine explizite `NOT NULL`-Einschränkung für eine Spalte, die von einer Domain abhängt, hat Vorrang vor der Domain.
In dieser Situation wird die Änderung der Domain, um sie auf NULL zu setzen, nicht an die Spalte weitergegeben.
====

`ADD CONSTRAINT CHECK`::
Verwenden Sie die `ADD CONSTRAINT CHECK`-Klausel, um der Domain eine `CHECK`-Beschränkung hinzuzufügen.
Wenn die Domain bereits eine `CHECK`-Beschränkung hat, muss sie zuerst mit einer `ALTER DOMAIN`-Anweisung gelöscht werden, die eine `DROP CONSTRAINT`-Klausel enthält.

`TYPE`::
Die `TYPE`-Klausel wird verwendet, um den Datentyp der Domain in einen anderen, kompatiblen zu ändern.
Das System verbietet jede Änderung des Typs, die zu Datenverlust führen könnte.
Ein Beispiel wäre, wenn die Anzahl der Zeichen im neuen Typ kleiner wäre als im bestehenden.

[IMPORTANT]
====
Wenn Sie die Attribute einer Domain ändern, kann vorhandener PSQL-Code ungültig werden.
Informationen zur Erkennung finden Sie im Artikel <<fblangref30-appx01-supp-rdb-validblr-de,[ref]_Das RDB$VALID_BLR-Feld_>> in Anhang A.
====

[[fblangref30-ddl-domn-cannotalter-de]]
=== Was kann `ALTER DOMAIN` nicht ändern

* Wenn die Domain als Array deklariert wurde, ist es nicht möglich, ihren Typ oder ihre Dimensionen zu ändern;
auch kann kein anderer Typ in einen Array-Typ geändert werden.
* Es gibt keine Möglichkeit, die Standardsortierung zu ändern, ohne die Domain zu löschen und mit den gewünschten Attributen neu zu erstellen.

[[fblangref30-ddl-domn-alter-who-de]]
=== Wer kann eine Domain ändern

Die `ALTER DOMAIN`-Anweisung kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Der Inhaber der Domain
* Benutzer mit der Berechtigung `ALTER ANY DOMAIN`

Domainnänderungen können durch Abhängigkeiten von Objekten verhindert werden, für die der Benutzer nicht über ausreichende Berechtigungen verfügt.

[[fblangref30-ddl-domn-alterdomnexmpls-de]]
=== `ALTER DOMAIN`-Beispiele

. Ändern des Datentyps auf `INTEGER` und Einstellen oder Ändern des Standardwerts auf 2.000:
+
[source]
----
ALTER DOMAIN CUSTNO
  TYPE INTEGER
  SET DEFAULT 2000;
----
. Domainnamen ändern
+
[source]
----
ALTER DOMAIN D_BOOLEAN TO D_BOOL;
----
. Löschen des Standardwerts und Hinzufügen einer Einschränkung für die Domain:
+
[source]
----
ALTER DOMAIN D_DATE
  DROP DEFAULT
  ADD CONSTRAINT CHECK (VALUE >= date '01.01.2000');
----
. Ändern der `CHECK`-Beschränkung:
+
[source]
----
ALTER DOMAIN D_DATE
  DROP CONSTRAINT;

ALTER DOMAIN D_DATE
  ADD CONSTRAINT CHECK
    (VALUE BETWEEN date '01.01.1900' AND date '31.12.2100');
----
. Ändern des Datentyps, um die zulässige Zeichenanzahl zu erhöhen:
+
[source]
----
ALTER DOMAIN FIRSTNAME
  TYPE VARCHAR(50) CHARACTER SET UTF8;
----
. Hinzufügen einer `NOT NULL`-Einschränkung:
+
[source]
----
ALTER DOMAIN FIRSTNAME
  SET NOT NULL;
----
. Entfernen einer `NOT NULL`-Einschränkung:
+
[source]
----
ALTER DOMAIN FIRSTNAME
  DROP NOT NULL;
----

.Siehe auch
<<fblangref30-ddl-domn-create-de>>, <<fblangref30-ddl-domn-drop-de>>

[[fblangref30-ddl-domn-drop-de]]
== `DROP DOMAIN`

.Verwendet für
Löschen einer bestehenden Domain

.Verfügbar in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
DROP DOMAIN _domain_name_
----

Die `DROP DOMAIN`-Anweisung löscht eine in der Datenbank vorhandene Domain.
Es ist nicht möglich, eine Domain zu löschen, wenn sie von Datenbanktabellenspalten referenziert oder in einem PSQL-Modul verwendet wird.
Um eine verwendete Domain zu löschen, müssen alle Spalten in allen Tabellen, die auf die Domain verweisen, gelöscht und alle Verweise auf die Domain aus den PSQL-Modulen entfernt werden.

[[fblangref30-ddl-domn-drop-who-de]]
=== Wer kann eine Domain löschen

Die `DROP DOMAIN`-Anweisung kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Der Inhaber der Domain
* Benutzer mit dem `DROP ANY DOMAIN`-Privileg

[[fblangref30-ddl-domn-drop-example-de]]
=== Example of `DROP DOMAIN`

.Löschen der COUNTRYNAME-Domain
[source]
----
DROP DOMAIN COUNTRYNAME;
----

.Siehe auch
<<fblangref30-ddl-domn-create-de>>, <<fblangref30-ddl-domn-alter-de>>
