[[fblangref30-ddl-charset-de]]
= `CHARACTER SET`

[[fblangref30-ddl-charset-alter-de]]
== `ALTER CHARACTER SET`

.Verwendet für
Festlegen der Standardsortierung für einen Zeichensatz

.Verfügbar in
DSQL

.Syntax
[listing,subs=+quotes]
----
ALTER CHARACTER SET _charset_
  SET DEFAULT COLLATION _collation_
----

[[fblangref30-ddl-tbl-charsetalter]]
.`ALTER CHARACTER SET`-Anweisungsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|charset
|Zeichensatzkennung

|collation
|Der Name der Kollation
|===

Die Anweisung `ALTER CHARACTER SET` ändert die Standardsortierung für den angegebenen Zeichensatz.
Sie wirkt sich auf die zukünftige Verwendung des Zeichensatzes aus, außer in Fällen, in denen die `COLLATE`-Klausel explizit überschrieben wird.
In diesem Fall bleibt die Kollatierungsreihenfolge bestehender Domänen, Spalten und PSQL-Variablen nach der Änderung der Standardkollation des zugrunde liegenden Zeichensatzes erhalten.

[NOTE]
====
Wenn Sie die Standardsortierung für den Datenbankzeichensatz ändern (der beim Erstellen der Datenbank definierte), wird die Standardsortierung für die Datenbank geändert.

Wenn Sie die Standardsortierung für den während der Verbindung angegebenen Zeichensatz ändern, werden Zeichenfolgenkonstanten gemäß dem neuen Sortierungswert interpretiert, außer in den Fällen, in denen der Zeichensatz und/oder die Sortierung überschrieben wurden.
====

[[fblangref30-ddl-charset-alterpriv-de]]
=== Wer kann einen Zeichensatz ändern?

Die Anweisung `ALTER CHARACTER SET` kann ausgeführt werden durch:

* <<fblangref30-security-administrators-de,Administratoren>>
* Benutzer mit der Berechtigung `ALTER ANY CHARACTER SET`

[[fblangref30-ddl-charset-alter-exmpl-de]]
=== `ALTER CHARACTER SET`-Beispiel

.Festlegen der Standardsortierung `UNICODE_CI_AI` für die `UTF8`-Codierung
[source]
----
ALTER CHARACTER SET UTF8
  SET DEFAULT COLLATION UNICODE_CI_AI;
----
