= 2025-01: Naming Convention Changes for Language Reference
:docwriting-guide: https://firebirdsql.org/file/documentation/html/en/firebirddocs/docwritehowto/firebird-docwriting-guide.html

== Status

* Published: 2025-07-07

== Type

* Project-Specification

== Context

The _firebird-documentation_ project has a general naming convention for section ids (including table ids, and so on) and -- by extension -- fragment filenames, which are based on the top-level section id of the fragment.
The convention is basically that the id starts with the _docId_ of the book (manual/guide).

See also {docwriting-guide}#docwritehowto-asciidoc-sectionid[Section IDs] and {docwriting-guide}#docwritehowto-asciidoc-project-layout[Project layout] in the _Firebird Docwriting Guide_.

Historically, this convention was chosen to allow building a larger reference comprised of the various guides and manuals as a single book (or book of books), the _Firebird Documentation Set_.
As this required ids to be unique, this convention was established to ensure uniqueness across the various guides.

The idea of building an all-encompassing documentation set has since been abandoned, but the convention generally still makes sense.

However, in the case of the Firebird Language Reference, which is versioned per Firebird version, this convention has downsides:

. Links to a specific section, or -- for the multipage or "`chunked`" build -- a page, are unique to that version of the Language Reference, making it harder to update links to a newer version.
You can't just replace the main URL (e.g. from `.../fblangref50/firebird-50-language-reference.html` to `.../fblangref60/firebird-60-language-reference.html`)footnote:adr-files[We're also considering some other changes to naming of URLs used for publishing, but that will be the subject of a separate ADR], you also need to update the specific anchor id and -- for multipage -- the page name.
. Introducing a Language Reference for a new version, requires a lot of work of renaming fragment files and ids (most of which is a simple search and replace, but zero work is better than some work).
. While maintaining the various versions of the Language Reference, it is not uncommon to copy the same text between the versions.
It's easy to forget to correct an id-reference (link) or section-id, resulting in broken links in the published documentation.

== Decision

Starting with the Firebird 6.0 Language Reference, section ids and fragment files of the Firebird Language Reference (and only the Firebird Language Reference!) will no longer use the _docId_ (e.g. `fblangref60`) in their names, but a shorter id, `langref` (let's call it a "`family-id`").

The _docId_ (e.g. `fblangref60`) is still used in the directory name containing the files, and the main file still contains the version number (e.g. `firebird-60-language-reference.++{adoc | html | pdf }++`)footnote:adr-files[].
The top-level id of the document will also continue to use the _docId_

The shorter family-id (i.e. `langref`) does away with the version suffix (e.g. `60`), and the `fb` prefix, as all documentation in the project is about Firebird.
We have considered even shorter abbreviations, like `lr` or `lang`, but think `langref` is more understandable.
We also considered simply doing away with the entire prefix, but think maintaining a similarity with the normal naming convention will better communicate intent.

This change will *not* be backported to existing Language References as that would break existing links, though that can be addressed with alternative ids, and -- more importantly -- it would change the page names of the multipage documentation build, which would either break links, or result in older links pointing to pages that will no longer get updated, or require the tedious work of declaring additional redirects.

We have considered adding the new ids as alternative ids to the existing documentation, to make it easier to "`downgrade`" from a Firebird 6.0 link to an older version, but will not do so at this time.
We will consider this again after the Firebird 6.0 Language Reference has been published.
(If only to avoid having to redo work if we make further changes to the id naming, for example, if we decide to remove the sequence number from appendix ids.)

== Consequences

The Firebird 6.0 Language Reference will use ids with the prefix `langref`, except the top-level document id, which will be the _docId_, i.e. `fblangref60`.
The fragment files will use `_langref-` as their prefix (matching the top-level id of the fragment file), not `_fblangref60-`.
The ids and fragment files will be renamed as part of the initial documentation setup (i.e. copying `fblangref50`).

Future Firebird Language References after Firebird 6.0 will follow these conventions as well.

The _Firebird Docwriting Guide_ will be updated to mention the deviation of the convention for the Language Reference and link to this ADR as published on GitHub.
