= 2026-01: Remove DocBook 4 Build Code

== Status

* Published: 2026-05-30

== Type

* Project-Specification

== Context

Back in 2020, the project switched to AsciiDoc for writing documentation.
Actively maintained documentation was migrated from DocBook 4 to AsciiDoc.

The intent back then was that if it turned out there was a reason to update/maintain documentation which had not been migrated, that it should be converted to AsciiDoc before doing such updates.

The remaining (unmaintained) DocBook 4 documentation can still be built with the `docbook[Html|Pdf|Monohtml]` tasks.
Apart from adding links referring to the "`Firebird 5.0 Language Reference`" to the old "`Language Reference Updates`" back in 2024, these tasks are not actively used.
Note that these language reference updates were not converted to AsciiDoc, as the whole point was to add those links in place, in the exact same file structure as published previously.

These DocBook 4 tasks use older libraries, and it is hard to say -- without active use -- if these still work under newer Java and Gradle versions.

== Decision

To avoid unnecessary busywork like updating dependencies or tweaking build script code to retain compatibility with newer Java and/or Gradle versions, for something that is not actively used, the code to build DocBook 4 documentation will be removed.

A tag `before-docbook4-code-removal` is added.
This tag can be used as an easy way to locate the code if it turns we do need to build DocBook 4 documentation for some reason.

The remaining DocBook 4 sources will not be removed and remain in place.
Any DocBook 4 sources will only be removed if and when they have been converted to AsciiDoc.

== Consequences

Code and dependencies to build the DocBook 4 documentation are removed.
This includes the DocBook 4 XSLT (in `src/docs/xsl`).
The DocBook 5 related code and XSLT (for the chunked output from AsciiDoc) will remain in place.

The "`Getting and building the Firebird documentation`" (`docbuildhowto`) and "`Firebird Docwriting Guide`" (`docwritehowto`) are revised to remove (most) references to DocBook.

If there is ever any reason to build DocBook 4 documentation, the tag `before-docbook4-code-removal` can be used (e.g. for checkout or as a branch point).
However, wanting to build the DocBook 4 code should be taken as a sign that such documentation needs to be migrated to AsciiDoc instead.
