[#fbconf-allow-update-overwrite]
= `AllowUpdateOverwrite`

Defines behaviour of a record update when the record was already updated by a trigger or by another positional `UPDATE` in the same cursor.

.Availability
[horizontal.compact]
Added:: 5.0.4

.Configuration
Global, and per-database

.Syntax
[listing,subs=+quotes]
----
AllowUpdateOverwrite = _Boolean_
----

During execution of a modifying statement (`UPDATE`, `MERGE`, `UPDATE OR INSERT`), it's possible that the current record under update was already modified by a trigger fired previously for another record affected by the current statement.
Due to cursor stability, the update should not see such changes, and could silently overwrite them.

Setting `AllowUpdateOverwrite` manages how the engine should handle such cases:

- if set to `true` (the default), prior changes will be overwritten,
- if set to `false`, error "`UPDATE will overwrite changes made by the trigger or by the another UPDATE in the same cursor`" will be raised.

[CAUTION]
====
There is no guarantee that this setting will be available in future Firebird versions.
====
