[#fbconf-allow-encrypted-security-database]
= `AllowEncryptedSecurityDatabase`

Enables use of an encrypted security database.

.Configuration
Global, and per-database

.Syntax
[listing,subs=+quotes]
----
AllowEncryptedSecurityDatabase = _Boolean_
----

.Default
`false`

With the default setting, it is not possible to authenticate against an encrypted security database.

Depending on the database encryption plugin used and its configuration, the client may hold the encryption key and needs to send it to the server to be able to access the database.
With the default configuration, this key exchange will only happen after authentication completed successfully and -- if enabled -- wire encryption was set up (which depends on the session key of authentication).

However, if the security database is encrypted, this key exchange must occur _before_ authentication.
As this needs to happen before wire encryption is established, and could lead to key exposurefootnote:[This depends on the specific implementation of the database encryption plugin, secure solutions are possible], this must be explicitly enabled.

In general, the security database -- assuming use of SRP and long/quality passwords -- is pretty good at protecting itself and doesn't need to be encrypted.
One use case of an encrypted security database is if a database is its own security database and needs to be encrypted for other reasons.

[CAUTION]
====
Please understand what you are doing before enabling this feature.

Enabling this feature may expose the database encryption key if it is transmitted from client to server, as the encrypted security database needs to be accessed _before_ wire encryption can be established, as that depends on the successful completion of authentication.

Enabling this option may also cause the database encryption handshake to occur before authentication and wire encryption even if the security database itself is not encrypted, but the destination database is.
====

Authenticating against an encrypted security database is not supported by the `Legacy_Auth` authentication plugin.

.Example
[listing]
----
AllowEncryptedSecurityDatabase = false
----
