[#fbconf-auth-client]
= `AuthClient`

Authentication plugins tried by Firebird _fbclient_.

.Configuration
Global, per-database, client-side, and per-connection

.Syntax
[listing,subs=+quotes]
----
AuthClient = <plugin-list>

<plugin-list> ::= _plugin_ [<separator> _plugin_ ...]

<separator> ::=
  _one of <space> (' '), <comma> (','), <semicolon> (';')_
----

.Default
`Srp256, Srp, Legacy_Auth` (non-Windows) +
`Srp256, Srp, Win_Sspi, Legacy_Auth` (Windows)

The authentication plugins determine how a user authenticates.
Some authentication plugins also generate the encryption key for wire encryption.

For a list of plugins supported by a default Firebird installation, see <<fbconf-standard-auth-plugins>>.

When configured server-side (in `firebird.conf` or `databases.conf`), this setting controls which plugins are tried when the server creates a connection to another database (e.g. using `EXECUTE STATEMENT ... ON EXTERNAL`).

When configured client-side -- in `firebird.conf` read by the client, or using `isc_dpb_config` (key/value) or `isc_dpb_auth_plugin_list` (value only) -- it controls which plugins are tried for connecting.

The server and client must agree on the plugins used.
The list of plugins accepted by the server is configured through <<fbconf-auth-server>>.
However, the client will always try the first plugin listed, even if not supported by the server.
Subsequent plugins will only be tried if they are also listed in the `AuthServer` setting of the server.

.Insecurity of `Legacy_Auth`
[CAUTION]
====
The `Legacy_Auth` plugin is insecure, as it sends a UnixCrypt hash of the first 8 bytes of the password over the wire.
This hash is easily crackable with a rainbow table, and the method of transfer is susceptible to replay attacks.
In general, it is advisable to remove the `Legacy_Auth` plugin from consideration entirely.

If `Legacy_Auth` is listed first in `AuthClient`, it will send an easily crackable hash of the first 8 bytes of the password, even if the user in question is -- for example -- an SRP user.
This also happens if `Legacy_Auth` is listed in both `AuthClient` (of the client) and `AuthServer` (of the server), and none of the earlier plugins authenticated the user.
====

.Example
[listing]
----
AuthClient = Srp256
----

.See also
<<fbconf-auth-server>>
