[#fbconf-auth-server]
= `AuthServer`

Authentication plugins accepted by Firebird server.

.Configuration
Global, and per-database

.Syntax
[listing,subs=+quotes]
----
AuthServer = <plugin-list>

<plugin-list> ::= _plugin_ [<separator> _plugin_ ...]

<separator> ::=
  _one of <space> (' '), <comma> (','), <semicolon> (';')_
----

.Default
`Srp256`

Authentication plugins have a server-side part and client-side part.
The authentication plugins implement how a user is authenticated.
Some authentication plugins also generate the encryption key for wire encryption.
Generally, users are managed by a user manager that is specific to a plugin or family of plugins.

The authentication plugins the client tries are specified by the <<fbconf-auth-client>> setting.

// TODO Maybe move list of plugins to separate section?

A default Firebird installation supports the following authentication plugins:

.Standard authentication plugins included in Firebird
[horizontal.compact#fbconf-standard-auth-plugins]
`Srp`::
SRP (Secure Remote Password) with SHA-1 client-proof
`Srp224`::
SRP with SHA-224 client-proof
`Srp256`::
SRP with SHA-256 client-proof
`Srp384`::
SRP with SHA-384 client-proof
`Srp512`::
SRP with SHA-512 client-proof
`Win_Sspi`::
Windows SSPI authentication (a.k.a. trusted authentication);
Windows-only.
+
Users are not managed in Firebird, but may require a https://firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref50/fblangref50-security-mapping.html#fblangref50-security-mapping[mapping (`++CREATE [GLOBAL] MAPPING++`)], e.g. for role assignment based on Windows groups, etc.
`Legacy_Auth`::
Legacy authentication (max 8 character password; considered insecure!)

From these plugins, only `Legacy_Auth` does not generate an encryption key for wire encryption.
Additional third-party plugins may be available.

.Secure Remote Password and hashes
[NOTE]
====
Firebird's SRP implementation internally uses SHA-1 for hashing.
The various Srp__NNN__ plugins only change the hash used for the client-proof.

See also https://github.com/FirebirdSQL/firebird/issues/6051[firebird#6051^].
====

.Example
[listing]
----
AuthServer = Srp256, Srp
----

.See also
<<fbconf-auth-client>>, <<fbconf-user-manager>>
