[#fbconf-connection-idle-timeout]
= `ConnectionIdleTimeout`

Connection idle timeout.

.Configuration
Global, and per-database

.Availability
[horizontal.compact]
Added:: 4.0

.Syntax
[listing,subs=+quotes]
----
ConnectionIdleTimeout = _integer_
----

.Unit
Minute

.Default
`0`

The connection idle timeout -- or session idle timeout -- is the maximum time a connection may be idle (i.e. the engine receives no requests) before it shuts down the connection.
A setting of `0` disable the connection idle timeout.

By default, the idle timeout is not enabled.
No minimum or maximum limit is imposed, but a reasonably large period -- such as a few hours -- is recommended.

The connection idle timeout can be configured on three levels:

. Database level (through `firebird.conf` or `database.conf`)
. Connection level (through https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-management-setsessionidle[`SET SESSION IDLE TIMEOUT`] or the API)
+
If the database-level timeout is non-zero and lower than the connection-level timeout, the database-level timeout applies instead.

When a connection is shutdown by the expiration of the idle timeout, the next user API call returns the error `isc_att_shutdown` with secondary error `isc_att_shut_idle`.

.Example
[listing]
----
# One hour
ConnectionIdleTimeout = 60
----
