[#fbconf-cpu-affinity-mask]
= `CpuAffinityMask`

Which CPUs should be used (Windows Only)

.Configuration
Global

.Syntax
[listing,subs=+quotes]
----
CpuAffinityMask = _integer_
----

.Default
`0` (all CPUs)

Sets which processors can be used by the server.
The value is taken from a bitmap in which each bit represents a CPU.
Thus, to use only the first processor (CPU 0), the value is 1.
To use both CPU 0 and CPU 1, the value is 3 (binary `11`).
To use CPU 1 and CPU 2, the value is 6 (binary `110`).
The default value is 0 - no affinity will be set.

In Firebird 5 and later, on Windows 10 and later, if affinity is not set by `CpuAffinityMask`, nor by the caller process, then the server tries to exclude efficiency cores from its own affinity mask, i.e. default affinity mask includes performance cores only.

On 32-bit Windows, this can configure at most 32 CPUs;
on 64-bit Windows, at most 64 CPUs.
On systems with more than 64 processors, it can only configure the processors in the processor group assigned to the Firebird process.

For technical information, see the Microsoft documentation of https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setprocessaffinitymask[`SetProcessAffinityMask`^].

.Example
[listing]
----
# Use CPU 7 only (binary 10000000)
CpuAffinityMask = 128
# Use CPU 15 and CPU 7 (binary 1000000010000000)
CpuAffinityMask = 32896
----
