[#fbconf-data-type-compatibility]
= `DataTypeCompatibility`

Configures if newer data types are automatically converted to data types available in an older version.

.Configuration
Global, and per-database

.Availability
[horizontal.compact]
Added:: 4.0

.Syntax
[listing,subs=+quotes]
----
DataTypeCompatibility = [{ 2.5 | 3.0 }]
----

.Default
No value

The `DataTypeCompatibility` setting controls if input parameters (e.g. query parameters) and output columns (e.g. columns of a result set) using new data types are automatically converted to "`legacy`" data types of the specified older version.

Setting to an empty value will return the data type as is.
This can be used in `databases.conf` to override (clear) the configuration from `firebird.conf`.

Configure this setting as a last resort, as it affects all clients to the server -- if set in `firebird.conf` -- or database -- in `databases.conf` -- even if a client supports the newer data types.
Whenever possible, use the `isc_dpb_set_bind` connection property or the https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-management-setbind[`SET BIND`] statement instead.

[#fbconf-data-type-compatiblity-coercion-rules]
.`DataTypeCompatibility` coercion rules
[cols="2m,2m,1", options="header",stripes="none"]
|===
|Source data type
|Target data type
|Active for

|BOOLEAN
|CHAR(5)
|2.5

|DECFLOAT
|DOUBLE PRECISION
|2.5, 3.0

|INT128
|BIGINT
|2.5, 3.0

|NUMERIC(p[,s]) p&nbsp;>&nbsp;18
|NUMERIC(18[,s])
|2.5, 3.0

|DECIMAL(p[,s]) p&nbsp;>&nbsp;18
|DECIMAL(18[,s])
|2.5, 3.0

|TIME WITH TIME ZONE
|TIME WITHOUT TIME ZONE
|2.5, 3.0

|TIMESTAMP WITH TIME ZONE
|TIMESTAMP WITHOUT TIME ZONE
|2.5, 3.0

|===

[CAUTION]
====
This setting only affects how statement bindings of input parameters and output columns are described to the client, and how values of those parameters and columns are converted between the client and server.
It does not change the data types reported by the metadata tables, or on the server itself.
====

.Example
[listing]
----
DataTypeCompatibility = 2.5
----