[#fbconf-database-access]
= `DatabaseAccess`

Configures the database paths -- other than aliases -- the server accepts for opening databases.

.Configuration
Global

.Syntax
[listing,subs=+quotes]
----
DatabaseAccess = <database-access-config>

<database-access-config> ::=
    None
  | Full
  | Restrict <path-list>

<path-list> ::= _path_ [; _path_ ...]
----

.Default
`Full` (see <<fbconf-database-access-security-note>>!)

.Supported values
`None`::
Firebird only accepts database aliases defined in <<fbconf-databases,`databases.conf`>>.

`Full`::
Firebird accepts database aliases, and all paths accessible to the Firebird server (i.e. read/write access, or read access for a read-only database).

`Restrict <path-list>`::
Firebird accepts database aliases, and databases with a path rooted in the directories listed in `<path-list>` (that is, the database file is in a listed directory or in a subdirectory of a listed directory).
+
The `<path-list>` is a semicolon-separated list of directories.
It is possible to use absolute paths (e.g. Windows -- `C:\Database`, Linux -- `/db`), and relative paths.
Relative paths are resolved against the root directory of Firebird.
Given relative paths are not always obvious, it is recommended to use absolute paths.
+
The first directory listed is also used to resolve relative database paths.
// TODO I've read it might also try to resolve against the Firebird root directory; maybe check order?

.Security recommendation
[WARNING#fbconf-database-access-security-note]
====
The default value of `Full` is not recommended for production systems.
Full database access may compromise your systemfootnote:[Think of denial of service by filling the wrong disk until it runs out of space, or by creating a database that another program will use _if_ it exists, allowing unintended data-exfiltration, or by creating a file that causes a program to change its behaviour, checking if files exist or not, etc.].

The most secure option is to use `None`, so all databases must be listed in `databases.conf`.
If your users or applications must be able to dynamically create databases, then use `Restrict` with a list of allowed database paths.

We also recommend that there is no overlap with the directories listed in <<fbconf-external-file-access>>.
That is, directories listed in `DatabaseAccess` should not be the same as, be contained in, or contain the directories listed in `ExternalFileAccess`.
See <<fbconf-external-file-access>> for more information.
====

.Examples
[listing]
----
# Only allow aliases
DatabaseAccess = None
# Full access
DatabaseAccess = Full
# Restricted (Windows)
DatabaseAccess = Restrict C:\Databases;D:\CRM
# Restricted (Linux)
DatabaseAccess = Restrict /var/db;/var/crm
----

.See also
<<fbconf-external-file-access>>
