[#fbconf-default-db-cache-pages]
= `DefaultDbCachePages`

Default number of cached database pages

.Configuration
Global, and per-database

.Syntax
[listing,subs=+quotes]
----
DefaultDbCachePages = _integer_
----

.Unit
Database page

.Default
[horizontal.compact]
SuperServer:: `2048` (per database)
SuperClassic:: `256` (per connection)
Classic:: `256` (per connection)

Firebird uses the page cache to store recently used database pages in memory.
For SuperServer, the page cache is _per database_, and it's shared by all connections to that database;
for SuperClassic and Classic, the cache is _per connection_.

On SuperServer, the cache for each database will use `(page count) * (page size)`. +
On (Super)Classic, the cache will use `(page count) * (page size) * (connection count)`.

This setting only takes effect if the database has not been configured with an explicit number of page buffers using https://firebirdsql.org/file/documentation/html/en/firebirddocs/gfix/firebird-gfix.html#gfix-buffers[`gfix -buffers`].
// TODO Add link to relevant db config section
A backup with https://firebirdsql.org/file/documentation/html/en/firebirddocs/gbak/firebird-gbak.html[`gbak`] will record the current configuration in the backup file -- even if it is not explicitly set and derived from `DefaultDbCachePages`.
After a restore, the database will have this value explicitly configured in its database header, unless overridden with https://firebirdsql.org/file/documentation/html/en/firebirddocs/gbak/firebird-gbak.html#gbak-cmdline-buffers[`-{wj}BUFFERS`].

On (Super)Classic the cache can also be overridden for a specific connection using the `isc_dpb_num_buffers` connection property.

.Example
[listing]
----
DefaultDbCachePages = 4096
----
