[#fbconf-default-time-zone]
= `DefaultTimeZone`

Default session or client time zone.

.Configuration
Global, client-side and per-connection

.Availability
[horizontal.compact]
Added:: 4.0

.Syntax
[listing,subs=+quotes]
----
DefaultTimeZone = _time-zone-name_
----

.Default
No value (for server: derive from OS time zone)

* If empty, the default time zone for the server is derived from the OS time zone.
+
The derived time zone uses the rules in the ICU time zone database loaded by Firebird, not the OS time zone database.
Additional OS settings, like disabling daylight saving time, have no effect.
* When set in the server, it defines the default session time zone for attachments that don't specify `isc_dpb_session_time_zone`.
* When set in the client, it defines the default time zone used with client-side API functions and the default value of `isc_dpb_session_time_zone`.

The value of _time-zone-name_ is a time zone identifier string, as documented in https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-datatypes-tz-format[Firebird 4.0 Language Reference -- Time Zone Format].

.Example
[listing]
----
# Default to Europe/Berlin
DefaultTimeZone = Europe/Berlin
----
