[#fbconf-dummy-packet-interval]
= `DummyPacketInterval`

Seconds to wait on a silent client connection before the server sends a dummy packet to request acknowledgment.

// TODO: Unclear if it actually works as per-database and per-connection/client-side (asked question on firebird-devel, waiting on response)
.Configuration
Global, per-database, client-side, and per-connection

.Syntax
[listing,subs=+quotes]
----
DummyPacketInterval = _integer_
----

.Unit
Second

.Default
`0`

The dummy packet interval is a way to detect broken connections.
If a client is idle for more than the configured interval, the server will send a dummy packet to the client, which will result in a TCP/IP-level acknowledgement if the connection is still alive, and otherwise will result in detection of the broken connection.

[TIP]
====
Do not set this setting too low: use a value of tens of minutes or even hours, not just a few seconds.

A too low value can result in a lot of unnecessary busywork for the server for little gain.
====

Configuring this setting should generally be unnecessary as Firebird configures its sockets with `SO_KEEPALIVE` which will do a similar check at a lower level.
If you do not like the default 2-hour keepalive timeout used by the TCP/IP stack, adjust your server OS settings appropriately.

On UNIX-like OS's, modify contents of `/proc/sys/net/ipv4/tcp_keepalive_*` (which also apply to IPv6!).

For Windows, see the https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc782936(v=ws.10)[`KeepAliveTime` registry documentation^].

.Example
[listing]
----
# Set interval to 30 minutes
DummyPacketInterval = 1800
----
