[#fbconf-file-system-cache-size]
= `FileSystemCacheSize`

The maximum percentage of RAM used for the filesystem cache on 64-bit Windows.

.Syntax
[listing,subs=+quotes]
----
FileSystemCacheSize = _integer_
----

.Unit
Percent

.Range
`0`, `10` - `95`

.Default
`0`

[NOTE]
====
This setting only has effect on 64-bit Windows;
it is ignored on 32-bit Windows and other operating systems.
====

If `0`, Firebird will use the current filesystem cache settings and will not attempt to change the setting.

Values in the range of `10` to `95` specify the maximum percentage of RAM the host will use for the filesystem cache.
Values outside this range -- other than `0` -- will apply a default value of `30`.

[CAUTION]
====
This setting configures the maximum size of the filesystem cache of Windows, and will not only affect Firebird.

The user running the `firebird.exe` server process needs to have the `SeIncreaseQuotaPrivilege` to change the maximum filesystem cache size.
Built-in service accounts and administrators have it by default.
If you use a custom user account for running Firebird, you will need to assign this privilege yourself.
If the engine fails to adjust the cache size setting, it will log a warning message in `firebird.log` and continue.

If it has already been set before Firebird was started, a restart may be required for the change to take effect.
====
