[#fbconf-gc-policy]
= `GCPolicy`

Garbage collection policy.

.Configuration
Global, and per-database

.Syntax
[listing]
----
GCPolicy = { cooperative | background | combined }
----

.Default
`combined` (SuperServer) +
`cooperative` (Classic/SuperClassic)

The garbage collection policy configures how Firebird SuperServer performs garbage collection.
For Classic and SuperClassic, this setting is ignored;
they always use the _cooperative_ policy.

[horizontal.compact]
_cooperative_::
When a connection encounters garbage -- old record versions that are no longer interesting -- while reading a record, it will collect that garbage immediately.
If there is a lot of garbage, this can reduce performance of statement execution and fetching.
_background_::
When a connection encounters garbage while reading a record, it will queue the record for the garbage collector.
The garbage collector will -- at a later time -- collect garbage on that record.
_combined_::
A combination of _cooperative_ and _background_.
Some types of garbage will be queued for the garbage collector, while others will be collected by the connection itself.

.Example
[listing]
----
# Use background garbage collection policy
GCPolicy = background
----
