[#fbconf-inline-sort-threshold]
= `InlineSortThreshold`

Maximum sort record size that can be stored inline in the sort block.

.Configuration
Global, and per-database

.Syntax
[listing,subs=+quotes]
----
InlineSortThreshold = _integer_
----

.Unit
Byte

.Default
1000

This controls if non-key fields are stored inside the sort block, or to refetch them from the data pages after sorting.
If the sort record size with non-key fields exceeds the configured maximum, only the key fields are stored in the sort block.

A value of `0` (zero) disables storing non-key fields and always refetches non-key fields.

This setting is a balance between the cost of refetching data, and the cost of sorting when including non-key data.
If a sort block is very large (e.g. due to a lot of rows and/or large sort record size), the sort will be performed on disk.
The I/O cost of sorting including non-key fields may be larger than the I/O cost of refetching data.

.Examples
[listing]
----
# 2000 bytes
InlineSortThreshold = 2000

# Disabled
InlineSortThreshold = 0
----
