[#fbconf-ipc-name]
= `IpcName`

Name of the shared memory area used as the transport channel for the XNET (a.k.a. local) protocol (Windows only).

.Configuration
Global, client-side, and per-connection

.Syntax
[listing,subs=+quotes]
----
IpcName = _string_
----

.Default
`FIREBIRD`

Server-side, the configuration is used to create the shared memory to accept XNET connections, and for creating XNET connections to other servers.
Client-side, the configuration is used to open the shared memory to make XNET connections to the server.

The user running the server process should have the `SE_CREATE_GLOBAL_NAME` privilege (or `SeCreateGlobalPrivilege`), so the shared memory area can be registered in the `Global\` namespace.
If the user does not have this privilege, it will be registered in the local namespace, and only processes running in the same session will be able to connect using XNET.

If you're running Firebird as a service, and the user does not have `SeCreateGlobalPrivilege`, processes on the same machine will not be able to connect with XNET, as the service runs in its own session.

You can configure this value if you have multiple Firebird servers running on the same machine which all need to be able to accept XNET connections.
In that case, clients will need to be configured with that `IpcName` as well, either in their `firebird.conf`, or through `isc_dpb_config`.

.Example
[listing]
----
IpcName = FIREBIRD_2_5
----
