[#fbconf-lock-acquire-spins]
= `LockAcquireSpins`

The number of times that the lock manager will try acquiring a lock in a loop before waiting.

.Configuration
Global, and per-database

.Syntax
[listing,subs=+quotes]
----
LockAcquireSpins = _Integer_
----

.Default
`0`

The lock table of a database can only be accessed by one server process or thread at a time, and this is governed by a mutex.
This mutex can be requested conditionally or unconditionally.
A conditional request either succeeds immediately or fails and must be retried.
An unconditional request will make the process or thread wait (block) until the request succeeds.

This setting is only relevant for SuperClassic and Classic.

It is hard to give specific advice for configuring `LockAcquireSpins`.
On multicore machines -- when using Classic and SuperClassic -- it can be advantageous to spin on the lock a few times before waiting unconditionally, on the other hand if the lock table is heavily contested, this is likely to "`burn`" CPU cycles.
As such, the advice is to experiment with it, and tune it per database in `databases.conf`.

.Example
[listing]
----
# Spin 5 times while acquiring lock
LockAcquireSpins = 5
----
