[#fbconf-max-parallel-workers]
= `MaxParallelWorkers`

Maximum number of parallel workers per database per process.

.Configuration
Global

.Availability
[horizontal.compact]
Added:: 5.0

.Syntax
[listing,subs=+quotes]
----
MaxParallelWorkers = _integer_
----

.Range
`1` - `64`

.Default
`1` (no parallelism)

This configures the total number of parallel workers that can be created within a single Firebird process for each attached database.
Workers are accounted for each attached database independently.

Parallel workers are used to parallelize certain database operations.
In Firebird 5.0, that includes index creation and rebuilding, and sweep.

In SuperServer worker attachments are implemented as light-weight system attachments, while in Classic and SuperClassic they look like usual user attachments.
All worker attachments are embedded into the creating server process.
Thus, in Classic there are no additional server processes.
Worker attachments are present in monitoring tables.
Idle worker attachments are destroyed after 60 seconds of inactivity.
Also, in Classic, worker attachments are destroyed immediately after the last user connection detaches from the database.

// This is the effective result, code wise, a too low value sets the default
Setting out of range values will use the boundary values.

[CAUTION]
====
This number is *per database* and *per process*.

This means that if you use SuperServer or SuperClassic, and set `MaxParallelWorkers` to 8, and you serve 10 databases, then in theory you can have 80 parallel workers (8 per database).
Similarly, if you use Classic, and you have 10 connections to a single database, then you could have 80 parallel workers in total (8 per process, each connection is a process).
====

.Example
[listing]
----
MaxParallelWorkers = 8
----

.See also
<<fbconf-parallel-workers>>