[#fbconf-max-unflushed-write-time]
= `MaxUnflushedWriteTime`

Maximum time asynchronous writes may be pending.

.Configuration
Global, and per-database

.Syntax
[listing,subs=+quotes]
----
MaxUnflushedWriteTime = _integer_
----

.Unit
Second

.Default
`5` (Windows) +
`-1` (other platforms)

This parameter determines how frequently pending asynchronous writes are flushed to disk when Forced Writes are disabled (or, asynchronous writing is enabled).
Its value is the maximum time in seconds an asynchronous write may be pending before a flush is flagged to be done next time a transaction commits.
A setting of `-1` disables this (i.e. pending writes are not flushed).

This setting only applies when forced-writes are off.

If the <<fbconf-max-unflushed-writes>> is reached before this timeout, the currently pending pages are flushed as well.

.Primarily for Windows
[NOTE]
====
This setting was introduced in Firebird 1.5 to address problems on Windows where asynchronous writes were not written to disk until controlled shutdown of Firebird.
If Firebird crashed, this could result in data loss.
====

.Example
[listing]
----
# 10 seconds
MaxUnflushedWriteTime = 10
----

.See also
<<fbconf-max-unflushed-writes>>
