[#fbconf-max-identifier-char-length]
= `MaxIdentifierCharLength`

Maximum identifier length in characters.

.Configuration
Global and per-database

.Syntax
[listing,subs=+quotes]
----
MaxIdentifierCharLength = _integer_
----

.Unit
Character

.Range
`1` - `63`
// TODO Verify minimum value

.Default
`63`

Since Firebird 4.0, identifiers can be a maximum 252 bytes, or 63 characters UTF8.
Set to `31` to use the same limit as in Firebird 3.0 and earlier.

This setting combined with <<fbconf-max-identifier-byte-length>> determines the actual maximum length.
For example, if `MaxIdentifierCharLength` setting is `31`, and `MaxIdentifierCharLength` is not set, or set to `124` or higher, then an identifier can have maximum 31 characters of any UTF8 character.
On the other hand, if `MaxIdentifierCharLength` is set to `31`, and `MaxIdentifierCharLength` is also set to `31`, then you can have 31 characters from the ASCII range, but using characters that require 2, 3, or 4 bytes to be encoded will reduce the actual maximum length in characters (to a minimum of 7 if all characters of an identifier are 4 bytes in UTF8).

[CAUTION]
====
Setting this value too low may make databases with longer identifiers inaccessible.
For that reason, do not configure this globally, but only configure it per database in `databases.conf` when you _know_ the identifiers will not be longer.

In general, we recommend not to touch this setting and use the default.
Only use this for compatibility reasons, for example for applications that break when receiving longer identifiers that you cannot fix in any other way.
====

.Example
[listing]
----
MaxIdentifierCharLength = 31
----
