[#fbconf-max-unflushed-writes]
= `MaxUnflushedWrites`

Maximum number of pending asynchronous writes.

.Configuration
Global and per-database

.Syntax
[listing,subs=+quotes]
----
MaxUnflushedWrites = _integer_
----

.Unit
Data page/pending write

.Default
`100` (Windows) +
`-1` (other platforms)

This parameter determines how frequently pending asynchronous writes are flushed to disk when Forced Writes are disabled (or, asynchronous writing is enabled).
Its value is the number of asynchronous writes that may be pending before a flush is flagged to be done next time a transaction commits.
A setting of `-1` disables this (i.e. pending writes are not flushed).

This setting only applies when forced-writes are off.

If the <<fbconf-max-unflushed-write-time>> expires before the maximum number of pending pages is reached, the currently pending pages are flushed as well.

.Primarily for Windows
[NOTE]
====
This setting was introduced in Firebird 1.5 to address problems on Windows where asynchronous writes were not written to disk until controlled shutdown of Firebird.
If Firebird crashed, this could result in data loss.
====

.Example
[listing]
----
MaxUnflushedWrites = 50
----
