[#fbconf-outer-join-conversion]
= `OuterJoinConversion`

Enables optimizer conversion of outer joins to inner joins.

.Configuration
Global, and per-database

.Availability
[horizontal.compact]
Added:: 5.0
Deprecated:: 5.0

.Syntax
[listing,subs=+quotes]
----
OuterJoinConversion = _Boolean_
----

.Default
`true` (enabled)

Defines whether the optimizer attempts to convert outer joins into inner joins, provided that such a transformation is possible from the query result perspective.
This can be done if -- for example -- a `LEFT OUTER JOIN` is used, but the "`missing`" rows of the right table are filtered out in the `WHERE` by a condition that excludes `NULL` for a column of that table.

Enabled by default.
Disable to simplify the migration path if outer joins are used intentionally in SQL queries (e.g. as optimizer hints) even if they are known to be semantically equivalent to inner joins.

[CAUTION]
====
This setting is intended as a temporary backward compatibility option.
If you have a reason to disable this, we'd appreciate us if you tell us why on https://groups.google.com/g/firebird-devel[firebird-devel^].

There is no guarantee that this setting will be available in future Firebird versions.
====

.Example
[listing]
----
# Disable outer join conversion
OuterJoinConversion = false
----
