[#fbconf-parallel-workers]
= `ParallelWorkers`

Default number of parallel workers for a connection.

.Configuration
Global

.Availability
[horizontal.compact]
Added:: 5.0

.Syntax
[listing,subs=+quotes]
----
ParallelWorkers = _integer_
----

.Range
`1` - <<fbconf-max-parallel-workers>>

.Default
`1` (no parallelism)

This configures the default number of parallel workers that can be created by a single connection.
This default can be overridden with the `isc_dpb_parallel_workers` connection property (up to the maximum <<fbconf-max-parallel-workers>>).

For accounting purposes, the connection itself also counts as a worker connection, which is why value `1` means no parallelism.

Parallel workers are allocated on a first come, first served basis, so -- in SuperServer and SuperClassic -- when multiple connections to a database ask for parallel workers, at most <<fbconf-max-parallel-workers>> workers can be created.
For example, if `ParallelWorkers` is `3` and `MaxParallelWorkers` is `4`, and three connections ask for parallel workers, only `4` are allocated, e.g. two workers for the first, two for the second, and none for the third connection.

A connection only asks for parallel workers when performing a parallel operation.
Once the operation is complete, the worker is released.

Parallel workers are used to parallelize certain database operations.
In Firebird 5.0, that includes index creation and rebuilding, and sweep.

// This is the effective result, code wise, a too low value sets the default
Setting out of range values will use the boundary values.

.Example
[listing]
----
ParallelWorkers = 4
----

.See also
<<fbconf-max-parallel-workers>>