[#fbconf-providers]
= `Providers`

Connection providers used to connect to a database.

.Configuration
Global, per-database, client-side, and per-connection

.Syntax
[listing,subs=+quotes]
----
Providers = <plugin-list>

<plugin-list> ::= _plugin_ [<separator> _plugin_ ...]

<separator> ::=
  _one of <space> (' '), <comma> (','), <semicolon> (';')_
----

.Default
`Remote,Engine13,Loopback`

Providers are plugins used to connect to a database.

A default Firebird 4.0 installation supports the following provider plugins:

[#fbconf-standard-provider-plugins]
.Standard provider plugins included in Firebird
[horizontal]
`Remote`::
Connect to a remote Firebird server using TCP/IP, or WNET (Windows-only, removed in Firebird 5.0).
+
This provider expects the legacy URL including a hostname (e.g. TCP/IP `servername/port:database`, or WNET `\\servername:port\database`), or explicit protocols (e.g.`xnet://database`, `inet://servername:port/database`, etc.)
`Engine13`::
Connect using the Firebird ODS 13 database engine.
Client-side, this is what is called an _embedded_ connection.
+
This provider only expects a database name (filename or alias).
`Loopback`::
Connect to the locally running server.
On Windows, it tries XNET, TCP/IP (using `localhost`) and finally WNET (prepending `\\.\`).
On other OSes, only TCP/IP is tried.
+
The `Loopback` provider is basically the same as `Remote`, except it always connects to the local server.
+
This provider only expects a database name (filename or alias).

Additional providers may be added.
For example, copying the `Engine12.dll`/`libEngine12.so` from Firebird 3.0 to the `plugins` directory of Firebird 4.0 or 5.0 and including `Engine12` in `Providers` adds support for opening Firebird 3.0 (ODS 12) databases.

This configuration property serves multiple purposes:

. server-side (`firebird.conf` or `databases.conf` of the server)
** The plugins accepted for incoming connections.
However, unless `Redirection` is enabled, `Remote` is ignored for incoming connections.
** The plugins tried for outgoing connections (i.e. server as client)
. client-side (`firebird.conf` read by client, or key/value in `isc_dpb_config`)
** The plugins tried for outgoing connections

.Example
[listing]
----
Providers = Engine13
----
