[#fbconf-process-priority-level]
= `ProcessPriorityLevel`

Priority level/class for the server process (Windows only).

.Configuration
Global

.Syntax
[listing,subs=+quotes]
----
ProcessPriorityLevel = _integer_
----

.Default
`0` (normal priority)

.Supported values
[horizontal.compact]
[.nowrap]`< 0`:: low priority (sets `IDLE_PRIORITY_CLASS`)
`0`:: normal priority (sets `NORMAL_PRIORITY_CLASS`)
[.nowrap]`> 0`:: high priority (sets `HIGH_PRIORITY_CLASS`);
equivalent to using the `-b[oostpriority]` commandline option of `instsvc.exe`

Configures the process priority on Windows, which is used by the CPU scheduler to decide how and when to schedule threads of the Firebird process(es).

Setting a negative value may reduce responsiveness of the Firebird server if the system is otherwise busy, and setting a positive value may result in Firebird starving other process of CPU cycles.
In general, do not set this to anything other than `0`, and if you do set it, carefully test if your system responds correctly.

For technical information, see the Microsoft documentation of https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setpriorityclass[`SetPriorityClass`^].

.Example
[listing]
----
# Set high priority
ProcessPriorityLevel = 1
# Set idle priority
ProcessPriorityLevel = -1
----