[#fbconf-read-consistency]
= `ReadConsistency`

Configures if `READ COMMITTED` transactions always use `READ CONSISTENCY` mode.

.Availability
[horizontal.compact]
Added:: 4.0

.Syntax
[listing,subs=+quotes]
----
ReadConsistency = _Boolean_
----

.Default
`1` (true)

Since Firebird 4.0, `READ COMMITTED` by default always uses the `READ CONSISTENCY` mode, even if `[NO] RECORD VERSION` (`isc_tpb_rec_version`/`isc_tpb_no_rec_version`) is requested.
If `ReadConsistency` is set to `0` (false), the requested mode is used.

This setting is intended for backwards compatibility, if your application specifically depends on the behaviour of `[NO] RECORD VERSION`.
In general, we recommend to leave it at its default value.

[CAUTION]
====
This is intended as an interim workaround to be able to run legacy code which relies on the old behaviour.
We recommend that you fix such code, so you don't rely on this workaround.

There is no guarantee that this setting will be available in future Firebird versions.
====

.Example
[listing]
----
# Disable always using read consistency mode for READ COMMITTED
ReadConsistency = 0
----
