[#fbconf-redirection]
= `Redirection`

Allow multi-hop connections to other Firebird servers.

.Configuration
Global

.Availability
[horizontal.compact]
Deprecated:: 5.0

.Syntax
[listing,subs=+quotes]
----
Redirection = _Boolean_
----

.Default
`0` (false)

A multi-hop connection allows you to redirect a connection to a database through intermediate servers.

.Deprecated in Firebird 5, to be removed in Firebird 6
[WARNING]
====
This feature was partially broken in Firebird 3 with early (in remote listener) user authentication, and some plugins cannot be used with `Redirection`.
We did not receive any related bug reports, i.e. it's unused.
Therefore, `Redirection` is declared deprecated in Firebird 5 and will be removed in Firebird 6.
====

With this setup, a connection string specifies a list of servers to connect through, where the last server is the server that actually hosts the database.

For example, with the connection string `host1:host2:database`, the client will connect to `host1` with the database `host2:database`.
If `host1` has redirection enabled, it will -- *without authentication on ``host1``* -- forward the connection to `host2` to open database `database` -- where the connection will be authenticated.
Packets will be routed through `host1` between `host2` and the client.

In effect, `host1` serves as a pass-through proxy to `host2`.

.Security recommendation
[CAUTION]
====
*Do not enable this feature unless you really know what you're doing!*

Careless use of this feature may allow for circumventing security measures like firewalls and other access control measures.
For example if `host1` is public facing, while `host2` should only be internally accessible, but is accessible from `host1`, with redirection enabled, `host2` can also be accessed from the internet as long as people know the hostname.
====

.Example
[listing]
----
# Explicitly disable redirection
Redirection = 0
----
