[#fbconf-relaxed-alias-checking]
= `RelaxedAliasChecking`

Relaxes relation alias checking rules in SQL.

.Availability
[horizontal.compact]
Deprecated:: 2.0

.Syntax
[listing,subs=+quotes]
----
RelaxedAliasChecking = _Boolean_
----

.Default
`0` (false)

In Firebird 2.0, stricter parser rules for aliases of relations (e.g. tables, views) were implemented to conform to SQL standard requirements.
Enabling this setting relaxes the relation alias checking rules to the Firebird 1.5 and older behaviour.

With the default setting, if a relation is aliased, you are only allowed to reference that relation using its alias.
If `RelaxedAliasChecking` is set to `1` (true), you can also reference the relation using its original name.

For example:

[listing,sql]
----
-- Reference by alias (strict and non-strict)
select E.FIRST_NAME
from EMPLOYEE as E

-- Reference by relation name (non-strict only)
select EMPLOYEE.FIRST_NAME
from EMPLOYEE as E
----

[CAUTION]
====
This is intended as an interim workaround to be able to run legacy code which relies on the old behaviour.
We recommend that you fix such code, so you don't rely on this workaround.

There is no guarantee that this setting will be available in future Firebird versions.
====
