[#fbconf-remote-bind-address]
= `RemoteBindAddress`

Network interface of the TCP/IP listener.

.Configuration
Global

.Syntax
[listing,subs=+quotes]
----
RemoteBindAddress = _string_
----

.Default
Empty (bind to `::`)

The setting accepts an IPv4, IPv6 address, or a hostname;
the value may optionally be enclosed in square brackets.

By default -- when not specified, or explicitly empty -- Firebird listens on `::` (the zero IPv6 address).
The exact behaviour of the zero IPv6 address depends on <<fbconf-ipv6-v6-only>>:

* if disabled (the default), Firebird listens on all IPv4 and IPv6 network interfaces of the host.
* if enabled, Firebird only listens on all IPv6 network interfaces of the host (not IPv4).

It is not possible to specify multiple bind addresses.

If <<fbconf-ipv6-v6-only>> is enabled, IPv4-mapped IPv6 addresses are rejected.

When using a hostname, that hostname is used to resolve an IP address, preferring IPv6 over IPv4;
the resolved address is then used to bind the server.
So, make sure the hostname resolves to one IP address only (i.e. not be multihomed or otherwise multiplexed, nor be both IPv4 and IPv6).
Otherwise, the server may bind to a different IP address on each restart (e.g. if the DNS resolution does a round-robin), and clients may have connection failures when they resolve a different IP address than the one the server was bound to.

.Examples
[listing]
----
# listen on IPv4 localhost
RemoteBindAddress = 127.0.0.1

# listen on IPv6 localhost
RemoteBindAddress = ::1

# listen on all IPv4 network interfaces of the host
RemoteBindAddress = 0.0.0.0

# listen on the IP address of fbserver.local
RemoteBindAddress = fbserver.local
----
