[#fbconf-remote-file-open-ability]
= `RemoteFileOpenAbility`

Configures if Firebird allows opening of database files on mounted network volumes.

.Configuration
Global

.Syntax
[listing,subs=+quotes]
----
RemoteFileOpenAbility = _Boolean_
----

.Default
`0` (`false`)

.Enabling this option can cause database corruption
[CAUTION]
====
*Do not enable this option unless you really know what you're doing!*

This option removes an important safety feature of Firebird and can cause irrecoverable database corruption.
Do not use this option unless you understand the risks and are prepared to accept the loss of the contents of your database.

Unless this configuration option is changed from `0` to `1`, Firebird can only open a database if the database is stored on a drive physically attached to the local computer -- the computer running that copy of Firebird.
Requests for connections to databases stored on NFS mounted drives are redirected to a Firebird server running on the computer that "owns" the disk.

This restriction prevents two different copies of Firebird from opening the same database without coordinating their activities.
Uncoordinated access by multiple copies of Firebird will corrupt a database.
On a local system, the system-level file locking prevents uncoordinated access to the database file.

NFS does not provide a reliable way to detect multiple users of a file on an NFS mounted disk.
If a second copy of Firebird connects to a database on an NFS mounted disk, it will corrupt the database.
Under some circumstances, running a Firebird server on the computer that owns NFS mounted volumes is inconvenient or impossible.
Applications that use the "embedded" variant of Firebird and never share access to a database can use this option to permit direct access to databases on NFS mounted volumes.

The situation for SMB/CIFS is quite similar to NFS, with not all configurations providing file locking mechanisms needed for safe operation.
Using SuperServer with the database on a Windows Server file server may be considered relatively safe as file locking protects the database from being used by several engines.
The network stack can still change order of writes, so you may get a corrupted database in case of network errors or power outage.

The useful and safe case is working with a shared database marked read-only.
====

By default, Firebird only opens database files on local disks.
When `RemoteFileOpenAbility` is enabled, Firebird can also open databases from mounted NFS volumes (Linux) or SMB/CIFS volumes (Windows)

.Example
[listing]
----
RemoteFileOpenAbility = 0
----