[#fbconf-remote-service-name]
= `RemoteServiceName`

The TCP service name/port number to be used for database connections.

.Configuration
Global, client-side, and per-connection

.Syntax
[listing,subs=+quotes]
----
RemoteServiceName = _service-name_
----

.Default
`gds_db`

If _service-name_ is defined in the `services` definition file (e.g. `/etc/services` or `C:\Windows\System32\drivers\etc\services`), it is used to determine the TCP port to use.
If _service-name_ is not found, the value or default of <<fbconf-remote-service-port>> is used.

Server-side::
Determines the port that the server listens for connections
Client-side and per-connection::
Determines the port to use if none is specified in the connection URL

The order of precedence is explicitly set values before defaults, and `RemoteServiceName` -- if an entry is found in the `services` file -- before `RemoteServicePort`.
In other words, if `RemoteServiceName` is not explicitly set, and `RemoteServicePort` is explicitly set, the value of `RemoteServicePort` is used.

.Example
[listing]
----
RemoteServiceName = gds_db
----

.See also
<<fbconf-remote-service-port>>
