[#fbconf-remote-access]
= `RemoteAccess`

Enables or disables remote access of databases.

.Configuration
Global and per-database

.Syntax
[listing,subs=+quotes]
----
RemoteAccess = _Boolean_
----

.Default
`true`

The Boolean option `RemoteAccess` controls if databases can be opened remotely -- via TCP/IP, or WNETfootnote:[WNET is Windows-only, and was removed in Firebird 5.0], or only locally using _embedded_ or -- on Windows -- XNET.

Any TCP/IP or WNET connection is considered remote, including connections created from the same machine (localhost).

// TODO Verify if above applies for WNET too

.Security recommendation
[TIP]
====
The security database (`security__N__.fdb`, alias `security.db`) has `RemoteAccess` set to `false` in `databases.conf` in a standard Firebird installation.
If you use additional dedicated security databases, we recommend disabling remote access for them too.

If you have high-security requirements, consider setting `RemoteAccess` to `false` in `firebird.conf` to disallow remote access for all databases, and enabling it per database in `databases.conf` as needed.
====

.Examples
[listing]
----
# Enable remote access
RemoteAccess = true
# Disable remote access
RemoteAccess = false
----