[#fbconf-security-database]
= `SecurityDatabase`

Location of the security database.

.Configuration
Global, and per-database

.Syntax
[listing,subs=+quotes]
----
SecurityDatabase = { _path_ | _alias_ }
----

.Default
`$(dir_secDb)/security__N__.fdb` (with _N_ the major version of Firebird)

The security database is used for authentication and certain global configuration and user privileges (e.g. global authentication mapping, and `CREATE DATABASE` privileges).
When using embedded mode, no authentication is performed.

The `SecurityDatabase` can be configured per database in `databases.conf`.
Such a security database can be created as a normal database.
Initialization as a security database happens per authentication plugin, the first time that authentication plugin is used to create a user.
This initialization must be done with an embedded connection otherwise you cannot connect, or authenticated with a `SYSDBA` or `RDB$ADMIN` user of an already initialized authentication plugin.

It is possible to configure a database as its own security database, but only _after_ the database has been created.

.Example in `databases.conf`
----
# Configure employee example database as its own security database
employee = $(dir_sampleDb)/employee.fdb
{
  SecurityDatabase = employee
}
----
