[#fbconf-server-mode]
= `ServerMode`

Configures database access, process, and caching behaviour of the Firebird engine.

.Configuration
Global

.Syntax
[listing,subs=+quotes]
----
ServerMode =
  { Super | ThreadedDedicated
  | SuperClassic | ThreadedShared
  | Classic | MultiProcess }
----

.Default
`Super`

.Supported values
`Super`/`ThreadedDedicated`::
Databases are opened by a single server process with exclusive access.
User attachments are processed by threads launched from a common pool, and all share a single database page cache inside the process.
+
Generally known as "`SuperServer`".
`SuperClassic`/`ThreadedShared`::
Databases are opened by a single server process with shared access.
Databases may be opened by multiple processes (including embedded).
User attachments are processed by threads launched from a common pool, each having its own database page cache.
+
Generally known as "`SuperClassic`".
`Classic`/`MultiProcess`::
For each attachment to the server, a separate process is started.
Databases are opened with shared access, and may be opened by multiple processes (including embedded).
Each attachment (process) has its own database page cache.
+
Generally known as "`Classic`".

The `ServerMode` affects how Firebird opens databases, and the memory use per attachment.
There is no single "`best`" choice.

// TODO Document things influencing choice in server mode here or elsewhere in this manual?

[TIP]
====
Historically, for Firebird 2.1 and older, SuperServer did not scale well with multiple CPU cores.
This was improved in Firebird 2.5, and fully addressed in Firebird 3.0.

In other words, CPU scalability is no longer a reason to not use SuperServer.
====

.Example
[listing]
----
ServerMode = SuperClassic
----
