[#fbconf-statement-timeout]
= `StatementTimeout`

Statement timeout.

.Configuration
Global and per-database

.Availability
[horizontal.compact]
Added:: 4.0

.Syntax
[listing,subs=+quotes]
----
StatementTimeout = _integer_
----

.Unit
Second

.Default
`0`

The statement timeout is the maximum duration of statement execution and cursor use.
The engine will automatically cancel the statement after the configured number of seconds.
A value of `0` means that no statement timeout is set.

The statement timeout can be configured on three levels:

. Database level (through `firebird.conf` or `database.conf`)
. Connection level (through https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-management-setstatementtimeout[`SET STATEMENT TIMEOUT`] or the API)
+
If the database level setting is non-zero and lower, that timeout applies instead.
. Statement level (through the API)
+
If the database level setting is non-zero and lower, that timeout applies instead.

The timeout is reported when the client sends a request involving the statement handle.
The request will complete with error `isc_cancelled` and a secondary error code indicating which timeout expired:

`isc_cfg_stmt_timeout`::
Config level timeout expired
`isc_att_stmt_timeout`::
Attachment level timeout expired
`isc_req_stmt_timeout`::
Statement level timeout expired

.Timeout includes duration of open cursor
[NOTE]
====
In the case of a result set producing statement (e.g. a `SELECT`), the timeout covers the time from statement execution until cursor close.
That means that even if Firebird executes the query quickly, but the application takes a long time to fetch rows from the cursor (e.g. because it waits for user action -- like scrolling a grid -- to fetch rows), the statement will be cancelled if the fetch occurs after the timeout.

In other words, be careful with setting this too low.
====

[NOTE]
.Notes about statement timeouts
====
. A client application could wait longer than the time set by the timeout value if the engine needs to undo a large number of actions as a result of the statement cancellation
. When the engine runs an `EXECUTE STATEMENT` statement, it passes the remainder of the currently active timeout to the new statement.
If the external (remote) engine does not support statement timeouts, the local engine silently ignores any corresponding error.
. When the engine acquires a lock from the lock manager, it tries to lower the value of the lock timeout using the remainder of the currently active statement timeout, if possible.
Due to lock manager internals, any statement timeout remainder will be rounded up to whole seconds.
====

.Example
[listing]
----
# Five minute timeout
StatementTimeout = 300
----
