[#fbconf-sub-query-conversion]
= `SubQueryConversion`

Enables experimental optimizer conversion of subqueries in `EXISTS` and `IN` to semi-joins.

.Configuration
Global, and per-database

.Availability
[horizontal.compact]
Added:: 5.0
Deprecated:: 5.0

.Syntax
[listing,subs=+quotes]
----
SubQueryConversion = _Boolean_
----

.Default
`false` (disabled)

Defines whether the optimizer attempts to merge subqueries in `EXISTS` and `IN` with the outer query by converting them to semi-joins, provided that such a transformation is possible from the query result perspective.

[CAUTION]
====
This is an experimental feature in Firebird 5.0, so it's disabled by default.
Enable and give it a try for a possibly improved performance due to subqueries being evaluated just once and then cached.

If you run into problems like decreased performance or wrong query results with this option enabled, we'd appreciate us if you tell us on https://groups.google.com/g/firebird-devel[firebird-devel^] or on the https://github.com/FirebirdSQL/firebird/issues[issue tracker^].

Once this feature is proved to be superior in most use cases, this setting will be removed, and this conversion will become unconditional.

There is no guarantee that this setting will be available in future Firebird versions.
====

.Example
[listing]
----
SubQueryConversion = true
----
