[#fbconf-tcp-loopback-fast-path]
= `TcpLoopbackFastPath`

Enables the "`TCP Loopback Fast Path`" feature (`SIO_LOOPBACK_FAST_PATH`).

.Configuration
Global, client-side, and per-connection

.Availability
[horizontal.compact]
Deprecated:: 3.0.11, 4.0.3
Removed:: 5.0

.Syntax
[listing,subs=+quotes]
----
TcpLoopbackFastPath = _Boolean_
----

.Default
`0` (disabled) -- since Firebird 3.0.11 and 4.0.3 +
`1` (enabled) -- in older versions

[NOTE]
====
This setting only has effect on Windows 8 and higher and Windows Server 2012 and higher.
Microsoft now discourages its use and advises not to use it as it can cause problems with kernel-level filter drivers on socket connections.

In response, Firebird has deprecated this setting in Firebird 3.0.11 and 4.0.3 -- changing its default to `0` (disabled).
This configuration item was removed in Firebird 5.0.
====

The "`TCP Loopback Fast Path`" can improve performance of localhost connections on Windows systems.
For it to work, both the client and the server need to enable the `SIO_LOOPBACK_FAST_PATH` option on the socket before connecting.

As this option is now deprecated, and Microsoft advises not to use it, exercise caution with this option, and leave or set it disabled.

.Example
[listing]
----
# Disable the "TCP Loopback Fast Path"
TcpLoopbackFastPath = 0
----
