[#fbconf-tcp-remote-buffer-size]
= `TcpRemoteBufferSize`

Buffer size for send and receive buffers of both the client and server for TCP/IP connections.

.Configurability
Global, client-side, and per-connection

.Syntax
[listing,subs=+quotes]
----
TcpRemoteBufferSize = _integer_
----

.Unit
Byte

.Range
`1448` - `32767`

.Default
`8192`

The engine reads ahead of the client and can send several rows of data in a single packet.
With a larger buffer size, more data can be sent per request (e.g. per fetch).

The server-side configuration only configures the server buffer sizes, and the client-side (and per-connection) configuration only configures the client buffer sizes.

[TIP]
====
Set `TcpRemoteBufferSize` to the maximum value for the server.

The buffer size influences -- among other things -- how many rows a single fetch can return.
Current Firebird versions will return at most 10 rows, or however many rows fit into 16 packets (whichever is higher), even if a larger number of rows is requested by the client.

Using <<fbconf-wire-compression>> can also increase the number of rows returned per fetch, if the row data compresses well.
====

.Example
[listing]
----
# Use maximum buffer size of 32767
TcpRemoteBufferSize = 32767
----
