[#fbconf-tip-cache-block-size]
= `TipCacheBlockSize`

Block size of shared memory allocated for TIP cache.

.Configuration
Global, and per-database

.Syntax
[listing,subs=+quotes]
----
TipCacheBlockSize = _integer_
----

.Unit
Byte

.Default
`4M` (4 MiB, 4,194,304 bytes)

The TIP cache is a list of all known transactions with associated Commit Numbers (_CN_), which are used to determine record visibility of active transactions.

The memory for the TIP cache is allocated per database.
Each transaction uses 8 bytes of memory.
The default size of a TIP cache block is 4 MiB, providing capacity for 512 * 1024 transactions.

A reason to reduce this value is if you have a small TIP cache (or, a small difference between OIT and Next Transaction) and want to conserve memory.
A reason to increase this value is if you need a very large TIP cache (or, a very large difference between OIT and Next Transaction) and approach limits on kernel objects allocated for each block (files, mutexes, etc).

The TIP cache is implemented as an array indexed by transaction ID, with as value the corresponding Commit Number.
This array is split into blocks of `TipCacheBlockSize` bytes containing the CN's for all transactions between the OIT and Next Transaction markers.
When Next Transaction moves beyond the range of the highest block, a new block is allocated.
The oldest block is released when the OIT moves beyond the range of that block.

.Example
[listing]
----
# Block size of 1 MiB (128 * 1024 transactions per block)
TipCacheBlockSize = 1M
----