[#fbconf-udf-access]
= `UdfAccess`

Configures paths allowed for loading UDF -- User-Defined Function -- libraries.

.Configuration
Global

.Availability
[horizontal.compact]
Deprecated:: 4.0

.Syntax
[listing,subs=+quotes]
----
UdfAccess = <udf-access-config>

<udf-access-config> ::=
    None
  | Full
  | Restrict <path-list>

<path-list> ::= _path_ [; _path_ ...]
----

.Default
`None`

.Supported values
`None`::
UDF libraries are not loaded.

`Full`::
All paths are allowed for UDF libraries

`Restrict <path-list>`::
Files with a path rooted in the directories listed in `<path-list>` (that is, the file is in a listed directory or in a subdirectory of a listed directory) are allowed for UDF libraries.
+
The `<path-list>` is a semicolon-separated list of directories.
It is possible to use absolute paths (e.g. Windows -- `C:\ExternalFiles`, Linux -- `/externalfiles`), and relative paths.
Relative paths are resolved against the root directory of Firebird.
Given relative paths are not always obvious, it is recommended to use absolute paths.

UDFs and -- by extension -- `UdfAccess` are deprecated.
The recommended replacements are built-in functions, PSQL functions (introduced in Firebird 3.0), or UDR functions (User-Defined Routine, introduced in Firebird 3.0).

.Security recommendation
[CAUTION]
====
UDFs are inherently insecure and can compromise the security of your system and database.
If possible, do not use UDFs and keep `UdfAccess` set to `None`, and if you do need UDFs, do not use `Full`, but explicitly list the allowed directories using `Restrict`.

We also recommend that there is no overlap with the directories listed in <<fbconf-external-file-access>>.
That is, directories listed in `UdfAccess` should not be the same as, be contained in, or contain the directories listed in `ExternalFileAccess`.
See <<fbconf-external-file-access>> for more information.
====

.Examples
[listing]
----
# No access
UdfAccess = None
# Full access (DO NOT USE!)
UdfAccess = Full
# Restricted (Windows)
UdfAccess = Restrict UDF;C:\UDF
# Restricted (Linux)
ExternalFilesAccess = UDF;/var/udf
----
