[#fbconf-use-legacy-kernel-objects-names]
= `UseLegacyKernelObjectsNames`

Configures how Firebird creates named Windows kernel objects, such as events, memory mapped files, etc. (Windows only).

.Configuration
Global

.Availability
[horizontal.compact]
Added:: 4.0.3
Deprecated:: 4.0.3
Removed:: 5.0

.Syntax
[listing,subs=+quotes]
----
UseLegacyKernelObjectsNames = _Boolean_
----

.Default
`false`

Since version 4.0.3, Firebird creates named kernel objects in a private namespace.
This allows processes to interact within different Windows sessions, such as a user session and a service session.
Also, it uses the engine version in some shared event names;
this allows a single process to host Firebird engines of different versions.

This setting is for backward compatibility only;
enabling it allows simultaneous running of Firebird processes of newer (>= 4.0.3) and older (< 4.0.3) subreleases of Firebird 4.0.

This setting is for backward compatibility between Firebird 4.0 releases only, and is not present in Firebird 5.0 and higher.

.Example
[listing]
----
# Enable legacy behaviour
UseLegacyKernelObjectsNames = true
----
