[#fbconf-user-manager]
= `UserManager`

List of enabled user manager plugins.

.Configuration
Global, and per-database

.Syntax
[listing,subs=+quotes]
----
UserManager = <plugin-list>

<plugin-list> ::= _plugin_ [<separator> _plugin_ ...]

<separator> ::=
  _one of <space> (' '), <comma> (','), <semicolon> (';')_
----

.Default
`Srp`

User manager plugins manage users, generally in the security database.
The user manager plugins are also used to populate the https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-appx06-users[`SEC$USERS`^] and https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-appx06-userattr[`SEC$USER_ATTRIBUTES`^] virtual tables.

The first plugin listed is the _default_ user manager.
The default user manager is used if the `USING PLUGIN` clause is absent from https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-security-user[user management statements^].
The default user manager is also used by _gsec_ and the user management service APIfootnote:[__gsec__ and the user management service API have been deprecated since Firebird 3.0 and may be removed in a future version, use user management statements instead].

Setting `UserManager` explicitly to an empty value (blank) will disallow management of users.

A default Firebird installation supports the following user manager plugins:

[#fbconf-standard-user-manager-plugins]
.Standard user manager plugins included in Firebird
[horizontal]
`Srp`::
User manager for the SRP-family of authentication plugins
`Legacy_UserManager`::
User manager of the `Legacy_Auth` authentication plugin

The per-database configuration in `databases.conf` enables which user manager plugins are allowed  -- and which is the default -- when connecting to that specific database.
When configured on a security database, it only manages which user manager plugins are allowed when connecting directly to that security database;
it does not configure which user manager plugins may store data in that security database.

.Security recommendations
[CAUTION]
====
. Where possible, replace insecure `Legacy_Auth`/`Legacy_UserManager` users with `Srp` users (and drop those insecure users).

. Some Firebird documentation suggest that if you need to manage `Legacy_Auth` users, to put `Legacy_UserManager` first.
*Do not do that unless you absolutely have to!*
+
Listing `Legacy_UserManager` first means that you will create insecure users by default if you forget to specify the `USING PLUGIN` clause, or use the deprecated _gsec_ or user management service API.
Creating insecure users should be a conscious and explicit choice (i.e. by specification of `USING PLUGIN Legacy_UserManager` in the statement).
+
You may even want to consider not listing `Legacy_UserManager`, except on a specific database to manage these insecure users.

. Consider setting `UserManager` explicitly blank in `firebird.conf`, and selectively enable user management for specific databases in `databases.conf`.
If you enable this only for a database marked with <<fbconf-remote-access, `RemoteAccess = false`>> (like the default security database), you will also disallow remote user management.
+
Doing this may improve security, by preventing attack vectors that exploit loopholes/bugs or insecure/leaked admin accounts to drop, create, or alter users, but it will also make user management harder.
Disabling user management this way will also prevent users from changing their own passwords (e.g. using https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-security-user-alter[`ALTER CURRENT USER`]).
====

.Examples
[listing]
----
# Enable Srp and Legacy_UserManager, with Srp as default
UserManager = Srp, Legacy_UserManager
# Disable user management
UserManager =
----
