[#fbconf-wire-crypt-plugin]
= `WireCryptPlugin`

List of wire crypt plugins tried by the client and/or accepted by the server.

.Configuration
Global, per-database, client-side, and per-connection

.Syntax
[listing,subs=+quotes]
----
WireCryptPlugin = <plugin-list>

<plugin-list> ::= _plugin_ [<separator> _plugin_ ...]

<separator> ::=
  _one of <space> (' '), <comma> (','), <semicolon> (';')_
----

.Default
`ChaCha64, ChaCha, Arc4`

Wire encryption plugins allow for encryption of the database connection _after_ authentication.
The default plugins included in Firebird use a session-key generated by the authentication plugin (not supported by `Legacy_Auth`) to encrypt the connection.

A default Firebird installation supports the following wire encryption plugins:

[#fbconf-standard-auth-plugins]
.Standard wire encryption plugins included in Firebird
[horizontal]
`ChaCha`::
ChaCha#20 (https://datatracker.ietf.org/doc/html/rfc8439[RFC 8439^]) with 32-bit counter (4 byte counter, 12 byte nonce, 20 (10 + 10) rounds).
The session key is stretched (or reduced) to 256-bit using SHA-256.
Session keys shorter than 16 bytes are rejected.
+
Due to implementation limitations, this plugin is limited to 256 GiB of data in one direction.
`ChaCha64`::
ChaCha#20 variant with 64-bit counter (8 byte counter, 8 byte nonce, 20 (10 + 10) rounds).
The session key is stretched (or reduced) to 256-bit using SHA-256.
Session keys shorter than 16 bytes are rejected.
`Arc4`::
Alleged RC4.
+
RC4 is considered insecure these days.

This configuration property serves multiple purposes:

. server-side (`firebird.conf` or `databases.conf` of the server)
** The plugins accepted for incoming connections
** The plugins tried for outgoing connections (i.e. server as client)
. client-side (`firebird.conf` read by client, or key/value in `isc_dpb_config`)
** The plugins tried for outgoing connections

The intersection of server-side and client-side wire encryption plugins decides which plugins are tried.
The server-side order of plugins decides in which order they are tried.

.Example
[listing]
----
# Only enable Arc4
WireCryptPlugin = Arc4
----
