[#fbconf-wire-crypt]
= `WireCrypt`

Controls if wire encryption is used or even required.

.Configuration
Global, per-database, client-side, and per-connection

// TODO Double check support in databases.conf

.Syntax
[listing]
----
WireCrypt = { Disabled | Enabled | Required }
----

.Default
`Required` (server) +
`Enabled` (client)

By default, encryption is _Required_ for incoming connections and _Enabled_ for outgoing connections (client connections).

To access a server using an older client library which does not support wire encryption, `WireCrypt` in the server configuration file should be set to `Enabled` instead of the default `Required`.
It is recommended to not set `WireCrypt` to `Disabled`, because then newer clients will also not encrypt their connections.

The rules are simple:

* If one side has `WireCrypt = Disabled`:
** If the other side has `WireCrypt = Required`, the connection is rejected
** Otherwise, the connection is established without encryption
* If the server and client don't have matching wire encryption plugins, or the encryption key is missing:
** If either side has `WireCrypt = Required`, the connection is rejected
** Otherwise, the connection is established without encryption
// TODO Double check if this doesn't result in a failure
* In all other cases, an encrypted connection is established.
