[[fblangref50-aggfuncs]]
= Aggregate Functions

Aggregate functions operate on groups of records, rather than on individual records or variables.
They are often used in combination with a `GROUP BY` clause.

.Syntax
[listing,subs=+quotes]
----
<aggregate_function> ::=
    _aggragate_function_ ([<expr> [, <expr> ...]])
      [FILTER (WHERE <condition>)]
----

The aggregate functions can also be used as window functions with the `OVER ()` clause.
See <<fblangref50-windowfuncs,Window (Analytical) Functions>> for more information.

Aggregate functions are available in DSQL and PSQL.
Availability in ESQL is not tracked by this Language Reference.

[[fblangref50-aggfuncs-filter]]
== `FILTER` Clause for Aggregate Functions

The `FILTER` clause extends aggregate functions (`SUM`, `AVG`, `COUNT`, etc.) with an additional `WHERE` clause.
This limits the rows processed by the aggregate functions to the rows that satisfy the conditions of both the main `WHERE` clause and those inside the `FILTER` clause.

It can be thought of as a more explicit form of using an aggregate function with a condition (<<fblangref50-scalarfuncs-decode,`DECODE`>>, <<fblangref50-commons-conditional-case,`CASE`>>, <<fblangref50-scalarfuncs-iif,`IIF`>>, <<fblangref50-scalarfuncs-nullif,`NULLIF`>>) to ignore some values that would otherwise be considered by the aggregation.

The `FILTER` clause can be used with any aggregate functions in aggregate or windowed (`OVER`) statements, but not with window-only functions like `DENSE_RANK`.

[float]
===== Example of `FILTER`

Suppose you need a query to count the rows with `status = 'A'` and the row with `status = 'E'` as different columns.
The old way to do it would be:

[source]
----
select count(decode(status, 'A', 1)) status_a,
       count(decode(status, 'E', 1)) status_e
from data;
----

The `FILTER` clause lets you express those conditions more explicitly:

[source]
----
select count(*) filter (where status = 'A') status_a,
       count(*) filter (where status = 'E') status_e
from data;
----

[TIP]
====
You can use more than one `FILTER` modifier in an aggregate query.
You could, for example, use 12 filters on totals aggregating sales for a year to produce monthly figures for a pivot set.
====

[[fblangref50-aggfuncs-general]]
== General-purpose Aggregate Functions

[[fblangref50-aggfuncs-avg]]
=== `AVG()`

Average

.Result type
Depends on the input type

.Syntax
[listing]
----
AVG ([ALL | DISTINCT] <expr>)
----

[[fblangref50-aggfuncs-tbl-avg]]
.`AVG` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF that returns a numeric data type.
Aggregate functions are not allowed as expressions
|===

`AVG` returns the average argument value in the group.
`NULL` is ignored.

* Parameter `ALL` (the default) applies the aggregate function to all values.
* Parameter `DISTINCT` directs the `AVG` function to consider only one instance of each unique value, no matter how many times this value occurs.
* If the set of retrieved records is empty or contains only `NULL`, the result will be `NULL`.

The result type of `AVG` depends on the input type:

[[fblangref50-aggfuncs-avg-types]]
[cols="<3m,<2m",stripes="none",frame="none",grid="none"]
|===
|FLOAT, DOUBLE PRECISION
|DOUBLE PRECISION

|SMALLINT, INTEGER, BIGINT
|BIGINT

|INT128
|INT128

|DECIMAL/NUMERIC(__p__, __n__) with _p_ < 19
|DECIMAL/NUMERIC(18, __n__)

|DECIMAL/NUMERIC(__p__, __n__) with _p_ >= 19
|DECIMAL/NUMERIC(38, __n__)

|DECFLOAT(16)
|DECFLOAT(16)

|DECFLOAT(34)
|DECFLOAT(34)
|===

[[fblangref50-aggfuncs-avg-exmpl]]
==== `AVG` Examples

[source]
----
SELECT
  dept_no,
  AVG(salary)
FROM employee
GROUP BY dept_no
----

.See also
<<fblangref50-dml-select,`SELECT`>>

[[fblangref50-aggfuncs-count]]
=== `COUNT()`

Counts non-``NULL`` values

.Result type
`BIGINT`

.Syntax
[listing]
----
COUNT ([ALL | DISTINCT] <expr> | *)
----

[[fblangref50-aggfuncs-tbl-count]]
.`COUNT` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF that returns a numeric data type.
Aggregate functions are not allowed as expressions
|===

`COUNT` returns the number of non-null values in a group.

* `ALL` is the default: it counts all values in the set that are not `NULL`.
* If `DISTINCT` is specified, duplicates are excluded from the counted set.
* If `COUNT ({asterisk})` is specified instead of the expression _expr_, all rows will be counted.
`COUNT ({asterisk})` --
** does not accept parameters
** cannot be used with the keyword `DISTINCT`
** does not take an _expr_ argument, since its context is column-unspecific by definition
** counts each row separately and returns the number of rows in the specified table or group without omitting duplicate rows
** counts rows containing `NULL`
* If the result set is empty or contains only `NULL` in the specified column(s), the returned count is zero.

[[fblangref50-aggfuncs-count-exmpl]]
==== `COUNT` Examples

[source]
----
SELECT
  dept_no,
  COUNT(*) AS cnt,
  COUNT(DISTINCT name) AS cnt_name
FROM employee
GROUP BY dept_no
----

.See also
<<fblangref50-dml-select,`SELECT`>>.

[[fblangref50-aggfuncs-list]]
=== `LIST()`

Concatenates values into a string list

.Result type
`BLOB`

.Syntax
[listing,subs=+quotes]
----
LIST ([ALL | DISTINCT] <expr> [, _separator_ ])
----

[[fblangref50-aggfuncs-tbl-list]]
.`LIST` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF that returns the string data type or a `BLOB`.
Fields of numeric and date/time types are converted to strings.
Aggregate functions are not allowed as expressions.

|separator
|Optional alternative separator, a string expression.
Comma is the default separator
|===

`LIST` returns a string consisting of the non-``NULL`` argument values in the group, separated either by a comma or by a user-supplied separator.
If there are no non-``NULL`` values (this includes the case where the group is empty), ``NULL`` is returned.

* `ALL` (the default) results in all non-``NULL`` values being listed.
With `DISTINCT`, duplicates are removed, except if _expr_ is a `BLOB`.
* The optional _separator_ argument may be any string expression.
This makes it possible to specify e.g. `ascii_char(13)` as a separator.
* The _expr_ and _separator_ arguments support ``BLOB``s of any size and character set.
* Datetime and numeric arguments are implicitly converted to strings before concatenation.
* The result is a text `BLOB`, except when _expr_ is a `BLOB` of another subtype.
* The ordering of the list values is undefined -- the order in which the strings are concatenated is determined by read order from the source set which, in tables, is not generally defined.
If ordering is important, the source data can be pre-sorted using a derived table or similar.
+
[CAUTION]
====
This is a trick/workaround, and it depends on implementation details of the optimizer/execution order.
This trick doesn't always work, and it is not guaranteed to work across versions.

Some reports indicate this no longer works in Firebird 5.0, or only in more limited circumstances than in previous versions.
====

[[fblangref50-aggfuncs-list-exmpl]]
==== `LIST` Examples

. Retrieving the list, order undefined:
+
[source]
----
SELECT LIST (display_name, '; ') FROM GR_WORK;
----
. Retrieving the list in alphabetical order, using a derived table:
+
[source]
----
SELECT LIST (display_name, '; ')
FROM (SELECT display_name
      FROM GR_WORK
      ORDER BY display_name);
----

.See also
<<fblangref50-dml-select,`SELECT`>>

[[fblangref50-aggfuncs-max]]
=== `MAX()`

Maximum

.Result type
Returns a result of the same data type the input expression.

.Syntax
[listing]
----
MAX ([ALL | DISTINCT] <expr>)
----

[[fblangref50-aggfuncs-tbl-max]]
.`MAX` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

`MAX` returns the maximum non-``NULL`` element in the result set.

* If the group is empty or contains only ``NULL``s, the result is `NULL`.
* If the input argument is a string, the function will return the value that will be sorted last if `COLLATE` is used.
* This function fully supports text ``BLOB``s of any size and character set.

[[fblangref50-aggfuncs-max-exmpl]]
==== `MAX` Examples

[source]
----
SELECT
  dept_no,
  MAX(salary)
FROM employee
GROUP BY dept_no
----

.See also
<<fblangref50-aggfuncs-min>>, <<fblangref50-dml-select,`SELECT`>>

[[fblangref50-aggfuncs-min]]
=== `MIN()`

Minimum

.Result type
Returns a result of the same data type the input expression.

.Syntax
[listing]
----
MIN ([ALL | DISTINCT] <expr>)
----

[[fblangref50-aggfuncs-tbl-min]]
.`MIN` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

`MIN` returns the minimum non-``NULL`` element in the result set.

* If the group is empty or contains only ``NULL``s, the result is `NULL`.
* If the input argument is a string, the function will return the value that will be sorted first if `COLLATE` is used.
* This function fully supports text ``BLOB``s of any size and character set.

[[fblangref50-aggfuncs-min-exmpl]]
==== `MIN` Examples

[source]
----
SELECT
  dept_no,
  MIN(salary)
FROM employee
GROUP BY dept_no
----

.See also
<<fblangref50-aggfuncs-max>>, <<fblangref50-dml-select,`SELECT`>>

[[fblangref50-aggfuncs-sum]]
=== `SUM()`

Sum

.Result type
Depends on the input type

.Syntax
[listing]
----
SUM ([ALL | DISTINCT] <expr>)
----

[[fblangref50-aggfuncs-tbl-sum]]
.`SUM` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Numeric expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

`SUM` calculates and returns the sum of non-``NULL`` values in the group.

* If the group is empty or contains only ``NULL``s, the result is `NULL`.
* `ALL` is the default option -- all values in the set that are not `NULL` are processed.
If `DISTINCT` is specified, duplicates are removed from the set and the `SUM` evaluation is done afterward.

The result type of `SUM` depends on the input type:

[[fblangref50-aggfuncs-sum-types]]
[cols="<3m,<2m",stripes="none",frame="none",grid="none"]
|===
|FLOAT, DOUBLE PRECISION
|DOUBLE PRECISION

|SMALLINT, INTEGER
|BIGINT

|BIGINT, INT128
|INT128

|DECIMAL/NUMERIC(__p__, __n__) with _p_ < 10
|DECIMAL/NUMERIC(18, __n__)

|DECIMAL/NUMERIC(__p__, __n__) with _p_ >= 10
|DECIMAL/NUMERIC(38, __n__)

|DECFLOAT(16), DECFLOAT(34)
|DECFLOAT(34)
|===

[[fblangref50-aggfuncs-sum-exmpl]]
==== `SUM` Examples

[source]
----
SELECT
  dept_no,
  SUM (salary),
FROM employee
GROUP BY dept_no
----

.See also
<<fblangref50-dml-select,`SELECT`>>

[[fblangref50-aggfuncs-stats]]
== Statistical Aggregate Functions

[[fblangref50-aggfuncs-corr]]
=== `CORR()`

Correlation coefficient

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
CORR ( <expr1>, <expr2> )
----

[[fblangref50-aggfuncs-tbl-corr]]
.`CORR` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr__N__
|Numeric expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The `CORR` function return the correlation coefficient for a pair of numerical expressions.

The function `CORR(<expr1>, <expr2>)` is equivalent to

[listing]
----
COVAR_POP(<expr1>, <expr2>) / (STDDEV_POP(<expr2>) * STDDEV_POP(<expr1>))
----

This is also known as the _Pearson correlation coefficient_.

In a statistical sense, correlation is the degree to which a pair of variables are linearly related.
A linear relation between variables means that the value of one variable can to a certain extent predict the value of the other.
The correlation coefficient represents the degree of correlation as a number ranging from -1 (high inverse correlation) to 1 (high correlation).
A value of 0 corresponds to no correlation.

If the group or window is empty, or contains only `NULL` values, the result will be `NULL`.

[[fblangref50-aggfuncs-corr-exmpl]]
==== `CORR` Examples

[source]
----
select
  corr(alength, aheight) AS c_corr
from measure
----

.See also
<<fblangref50-aggfuncs-covar-pop>>, <<fblangref50-aggfuncs-stddev-pop>>

[[fblangref50-aggfuncs-covar-pop]]
=== `COVAR_POP()`

Population covariance

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
COVAR_POP ( <expr1>, <expr2> )
----

[[fblangref50-aggfuncs-tbl-covar-pop]]
.`COVAR_POP` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr__N__
|Numeric expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `COVAR_POP` returns the population covariance for a pair of numerical expressions.

The function `COVAR_POP(<expr1>, <expr2>)` is equivalent to

[listing]
----
(SUM(<expr1> * <expr2>) - SUM(<expr1>) * SUM(<expr2>) / COUNT(*)) / COUNT(*)
----

If the group or window is empty, or contains only `NULL` values, the result will be `NULL`.

[[fblangref50-aggfuncs-covar-pop-exmpl]]
==== `COVAR_POP` Examples

[source]
----
select
  covar_pop(alength, aheight) AS c_covar_pop
from measure
----

.See also
<<fblangref50-aggfuncs-covar-samp>>, <<fblangref50-aggfuncs-sum>>, <<fblangref50-aggfuncs-count>>

[[fblangref50-aggfuncs-covar-samp]]
=== `COVAR_SAMP()`

Sample covariance

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
COVAR_SAMP ( <expr1>, <expr2> )
----

[[fblangref50-aggfuncs-tbl-covar-samp]]
.`COVAR_SAMP` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr__N__
|Numeric expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `COVAR_SAMP` returns the sample covariance for a pair of numerical expressions.

The function `COVAR_SAMP(<expr1>, <expr2>)` is equivalent to

[listing]
----
(SUM(<expr1> * <expr2>) - SUM(<expr1>) * SUM(<expr2>) / COUNT(*)) / (COUNT(*) - 1)
----

If the group or window is empty, contains only 1 row, or contains only `NULL` values, the result will be `NULL`.

[[fblangref50-aggfuncs-covar-samp-exmpl]]
==== `COVAR_SAMP` Examples

[source]
----
select
  covar_samp(alength, aheight) AS c_covar_samp
from measure
----

.See also
<<fblangref50-aggfuncs-covar-pop>>, <<fblangref50-aggfuncs-sum>>, <<fblangref50-aggfuncs-count>>

[[fblangref50-aggfuncs-stddev-pop]]
=== `STDDEV_POP()`

Population standard deviation

.Result type
`DOUBLE PRECISION` or `NUMERIC` depending on the type of _expr_

.Syntax
[listing]
----
STDDEV_POP ( <expr> )
----

[[fblangref50-aggfuncs-tbl-stddev-pop]]
.`STDDEV_POP` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Numeric expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `STDDEV_POP` returns the population standard deviation for a group or window.
`NULL` values are skipped.

The function `STDDEV_POP(<expr>)` is equivalent to

[listing]
----
SQRT(VAR_POP(<expr>))
----

If the group or window is empty, or contains only `NULL` values, the result will be `NULL`.

[[fblangref50-aggfuncs-stddev-pop-exmpl]]
==== `STDDEV_POP` Examples

[source]
----
select
  dept_no
  stddev_pop(salary)
from employee
group by dept_no
----

.See also
<<fblangref50-aggfuncs-stddev-samp>>, <<fblangref50-aggfuncs-var-pop>>, <<fblangref50-scalarfuncs-sqrt,`SQRT`>>

[[fblangref50-aggfuncs-stddev-samp]]
=== `STDDEV_SAMP()`

Sample standard deviation

.Result type
`DOUBLE PRECISION` or `NUMERIC` depending on the type of _expr_

.Syntax
[listing]
----
STDDEV_POP ( <expr> )
----

[[fblangref50-aggfuncs-tbl-stddev-samp]]
.`STDDEV_SAMP` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Numeric expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `STDDEV_SAMP` returns the sample standard deviation for a group or window.
`NULL` values are skipped.

The function `STDDEV_SAMP(<expr>)` is equivalent to

[listing]
----
SQRT(VAR_SAMP(<expr>))
----

If the group or window is empty, contains only 1 row, or contains only `NULL` values, the result will be `NULL`.

[[fblangref50-aggfuncs-stddev-samp-exmpl]]
==== `STDDEV_SAMP` Examples

[source]
----
select
  dept_no
  stddev_samp(salary)
from employee
group by dept_no
----

.See also
<<fblangref50-aggfuncs-stddev-pop>>, <<fblangref50-aggfuncs-var-samp>>, <<fblangref50-scalarfuncs-sqrt,`SQRT`>>

[[fblangref50-aggfuncs-var-pop]]
=== `VAR_POP()`

Population variance

.Result type
`DOUBLE PRECISION` or `NUMERIC` depending on the type of _expr_

.Syntax
[listing]
----
VAR_POP ( <expr> )
----

[[fblangref50-aggfuncs-tbl-var-pop]]
.`VAR_POP` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Numeric expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `VAR_POP` returns the population variance for a group or window.
`NULL` values are skipped.

The function `VAR_POP(<expr>)` is equivalent to

[listing]
----
(SUM(<expr> * <expr>) - SUM (<expr>) * SUM (<expr>) / COUNT(<expr>))
  / COUNT (<expr>)
----

If the group or window is empty, or contains only `NULL` values, the result will be `NULL`.

[[fblangref50-aggfuncs-var-pop-exmpl]]
==== `VAR_POP` Examples

[source]
----
select
  dept_no
  var_pop(salary)
from employee
group by dept_no
----

.See also
<<fblangref50-aggfuncs-var-samp>>, <<fblangref50-aggfuncs-sum>>, <<fblangref50-aggfuncs-count>>

[[fblangref50-aggfuncs-var-samp]]
=== `VAR_SAMP()`

Sample variance

.Result type
`DOUBLE PRECISION` or `NUMERIC` depending on the type of _expr_

.Syntax
[listing]
----
VAR_SAMP ( <expr> )
----

[[fblangref50-aggfuncs-tbl-var-samp]]
.`VAR_SAMP` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Numeric expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `VAR_POP` returns the sample variance for a group or window.
`NULL` values are skipped.

The function `VAR_SAMP(<expr>)` is equivalent to

[listing]
----
(SUM(<expr> * <expr>) - SUM(<expr>) * SUM (<expr>) / COUNT (<expr>))
  / (COUNT(<expr>) - 1)
----

If the group or window is empty, contains only 1 row, or contains only `NULL` values, the result will be `NULL`.

[[fblangref50-aggfuncs-var-samp-exmpl]]
==== `VAR_SAMP` Examples

[source]
----
select
  dept_no
  var_samp(salary)
from employee
group by dept_no
----

.See also
<<fblangref50-aggfuncs-var-pop>>, <<fblangref50-aggfuncs-sum>>, <<fblangref50-aggfuncs-count>>

[[fblangref50-aggfuncs-regr]]
== Linear Regression Aggregate Functions

Linear regression functions are useful for trend line continuation.
The trend or regression line is usually a pattern followed by a set of values.
Linear regression is useful to predict future values.
To continue the regression line, you need to know the slope and the point of intersection with the y-axis.
As set of linear functions can be used for calculating these values.

In the function syntax, _y_ is interpreted as an _x_-dependent variable.

The linear regression aggregate functions take a pair of arguments, the dependent variable expression (_y_) and the independent variable expression (_x_), which are both numeric value expressions.
Any row in which either argument evaluates to `NULL` is removed from the rows that qualify.
If there are no rows that qualify, then the result of `REGR_COUNT` is `0` (zero), and the other linear regression aggregate functions result in `NULL`.

[[fblangref50-aggfuncs-regr-avgx]]
=== `REGR_AVGX()`

Average of the independent variable of the regression line

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_AVGX ( <y>, <x> )
----

[[fblangref50-aggfuncs-tbl-regr-avgx]]
.`REGR_AVGX` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `REGR_AVGX` calculates the average of the independent variable (_x_) of the regression line.

The function `REGR_AVGX(<y>, <x>)` is equivalent to

[listing]
----
SUM(<exprX>) / REGR_COUNT(<y>, <x>)

<exprX> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN <x> END
----

.See also
<<fblangref50-aggfuncs-regr-avgy>>, <<fblangref50-aggfuncs-regr-count>>, <<fblangref50-aggfuncs-sum>>

[[fblangref50-aggfuncs-regr-avgy]]
=== `REGR_AVGY()`

Average of the dependent variable of the regression line

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_AVGY ( <y>, <x> )
----

[[fblangref50-aggfuncs-tbl-regr-avgy]]
.`REGR_AVGY` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `REGR_AVGY` calculates the average of the dependent variable (_y_) of the regression line.

The function `REGR_AVGY(<y>, <x>)` is equivalent to

[listing]
----
SUM(<exprY>) / REGR_COUNT(<y>, <x>)

<exprY> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN <y> END
----

.See also
<<fblangref50-aggfuncs-regr-avgx>>, <<fblangref50-aggfuncs-regr-count>>, <<fblangref50-aggfuncs-sum>>

[[fblangref50-aggfuncs-regr-count]]
=== `REGR_COUNT()`

Number of non-empty pairs of the regression line

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_COUNT ( <y>, <x> )
----

[[fblangref50-aggfuncs-tbl-regr-count]]
.`REGR_COUNT` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `REGR_COUNT` counts the number of non-empty pairs of the regression line.

The function `REGR_COUNT(<y>, <x>)` is equivalent to

[listing]
----
COUNT(*) FILTER (WHERE <x> IS NOT NULL AND <y> IS NOT NULL)
----

.See also
<<fblangref50-aggfuncs-count>>

[[fblangref50-aggfuncs-regr-intercept]]
=== `REGR_INTERCEPT()`

Point of intersection of the regression line with the y-axis

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_INTERCEPT ( <y>, <x> )
----

[[fblangref50-aggfuncs-tbl-regr-intercept]]
.`REGR_INTERCEPT` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `REGR_INTERCEPT` calculates the point of intersection of the regression line with the y-axis.

The function `REGR_INTERCEPT(<y>, <x>)` is equivalent to

[listing]
----
REGR_AVGY(<y>, <x>) - REGR_SLOPE(<y>, <x>) * REGR_AVGX(<y>, <x>)
----

[[fblangref50-aggfuncs-regr-intercept-exmpl]]
==== `REGR_INTERCEPT` Examples

Forecasting sales volume

[source]
----
with recursive years (byyear) as (
  select 1991
  from rdb$database
  union all
  select byyear + 1
  from years
  where byyear < 2020
),
s as (
  select
    extract(year from order_date) as byyear,
    sum(total_value) as total_value
  from sales
  group by 1
),
regr as (
  select
    regr_intercept(total_value, byyear) as intercept,
    regr_slope(total_value, byyear) as slope
  from s
)
select
  years.byyear as byyear,
  intercept + (slope * years.byyear) as total_value
from years
cross join regr
----

[listing]
----
BYYEAR TOTAL_VALUE
------ ------------
  1991    118377.35
  1992    414557.62
  1993    710737.89
  1994   1006918.16
  1995   1303098.43
  1996   1599278.69
  1997   1895458.96
  1998   2191639.23
  1999   2487819.50
  2000   2783999.77
...
----

.See also
<<fblangref50-aggfuncs-regr-avgx>>, <<fblangref50-aggfuncs-regr-avgy>>, <<fblangref50-aggfuncs-regr-slope>>

[[fblangref50-aggfuncs-regr-r2]]
=== `REGR_R2()`

Coefficient of determination of the regression line

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_R2 ( <y>, <x> )
----

[[fblangref50-aggfuncs-tbl-regr-r2]]
.`REGR_R2` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The REGR_R2 function calculates the coefficient of determination, or R-squared, of the regression line.

The function `REGR_R2(<y>, <x>)` is equivalent to

[listing]
----
POWER(CORR(<y>, <x>), 2)
----

.See also
<<fblangref50-aggfuncs-corr>>, <<fblangref50-scalarfuncs-power,`POWER`>>

[[fblangref50-aggfuncs-regr-slope]]
=== `REGR_SLOPE()`

Slope of the regression line

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_SLOPE ( <y>, <x> )
----

[[fblangref50-aggfuncs-tbl-regr-slope]]
.`REGR_SLOPE` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `REGR_SLOPE` calculates the slope of the regression line.

The function `REGR_SLOPE(<y>, <x>)` is equivalent to

[listing]
----
COVAR_POP(<y>, <x>) / VAR_POP(<exprX>)

<exprX> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN <x> END
----

.See also
<<fblangref50-aggfuncs-covar-pop>>, <<fblangref50-aggfuncs-var-pop>>

[[fblangref50-aggfuncs-regr-sxx]]
=== `REGR_SXX()`

Sum of squares of the independent variable

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_SXX ( <y>, <x> )
----

[[fblangref50-aggfuncs-tbl-regr-sxx]]
.`REGR_SXX` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `REGR_SXX` calculates the sum of squares of the independent expression variable (_x_).

The function `REGR_SXX(<y>, <x>)` is equivalent to

[listing]
----
REGR_COUNT(<y>, <x>) * VAR_POP(<exprX>)

<exprX> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN <x> END
----

.See also
<<fblangref50-aggfuncs-regr-count>>, <<fblangref50-aggfuncs-var-pop>>

[[fblangref50-aggfuncs-regr-sxy]]
=== `REGR_SXY()`

Sum of products of the independent variable and the dependent variable

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_SXY ( <y>, <x> )
----

[[fblangref50-aggfuncs-tbl-regr-sxy]]
.`REGR_SXY` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `REGR_SXY` calculates the sum of products of independent variable expression (_x_) times dependent variable expression (_y_).

The function `REGR_SXY(<y>, <x>)` is equivalent to

[listing]
----
REGR_COUNT(<y>, <x>) * COVAR_POP(<y>, <x>)
----

.See also
<<fblangref50-aggfuncs-covar-pop>>, <<fblangref50-aggfuncs-regr-count>>

[[fblangref50-aggfuncs-regr-syy]]
=== `REGR_SYY()`

Sum of squares of the dependent variable

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_SYY ( <y>, <x> )
----

[[fblangref50-aggfuncs-tbl-regr-syy]]
.`REGR_SYY` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `REGR_SYY` calculates the sum of squares of the dependent variable (_y_).

The function `REGR_SYY(<y>, <x>)` is equivalent to

[listing]
----
REGR_COUNT(<y>, <x>) * VAR_POP(<exprY>)

<exprY> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN <y> END
----

.See also
<<fblangref50-aggfuncs-regr-count>>, <<fblangref50-aggfuncs-var-pop>>
