:sectnums!:

[appendix]
[[fblangref50-dochist]]
= Document History

The exact file history is recorded in our _git_ repository; see https://github.com/FirebirdSQL/firebird-documentation

[%autowidth, width="100%", cols="4", options="header", frame="none", grid="none", role="revhistory"]
|===
4+|Revision History

|0.2
|TBD
a|* Documented "`standard`" plugin tables in new appendix <<fblangref50-appx07-plgtables>>
* Removed _Upgraders: PLEASE READ!_ sidebar from <<fblangref50-functions>>, the _Possible name conflict_ sections from function descriptions and the _Name Clash_ note on `LOWER()`
* Integrated (most) changes from the Firebird 5.0 beta 1 release notes
* Add new chapter <<fblangref50-sys-pckg>>, and move `RDB$TIME_ZONE_UTIL` documentation to it, and add `RDB$BLOB_UTIL` and `RDB$PROFILER` documentation
* Documented that subroutines can access variables of their parent
* Simplified `CONTINUE` and `LEAVE` examples, by removing unnecessary `ELSE`
* ...

|0.1
|05 May 2023
|MR
a|Copied the _Firebird 4.0 Language Reference_ as a starting point:

* renamed files and reference using _fblangref40_ to _fblangref50_
* where applicable, replaced reference to Firebird 4.0 with Firebird 5.0, or rephrased sentences referencing Firebird 4.0
|===

:sectnums:
