:sectnums!:

[appendix]
[[fblangref50-dochist]]
= Document History

The exact file history is recorded in our _git_ repository; see https://github.com/FirebirdSQL/firebird-documentation

[%autowidth, width="100%", cols="4", options="header", frame="none", grid="none", role="revhistory"]
|===
4+|Revision History

|0.2
|10 May 2023
|MR
a|* Documented "`standard`" plugin tables in new appendix <<fblangref50-appx07-plgtables>>
* Removed _Upgraders: PLEASE READ!_ sidebar from <<fblangref50-functions>>, the _Possible name conflict_ sections from function descriptions and the _Name Clash_ note on `LOWER()`
* Integrated (most) changes from the Firebird 5.0 beta 1 release notes
* Added new chapter <<fblangref50-sys-pckg>>, and moved `RDB$TIME_ZONE_UTIL` documentation to it, and added `RDB$BLOB_UTIL` and `RDB$PROFILER` documentation
* Documented that subroutines can access variables of their parent
* Simplified `CONTINUE` and `LEAVE` examples, by removing unnecessary `ELSE`
* Documented `PLAN`, `ORDER BY` and `ROWS` for `UPDATE OR INSERT` and `PLAN` and `ORDER BY` for `MERGE`
* Added <<fblangref50-dml-select-full-syntax>> as a first step to address current incomplete/simplified syntax used in <<fblangref50-dml-select>>
* Removed incorrect `<common-table-expression>` production in SELECT syntax
* Revised syntax used in <<fblangref50-dml-select>> and <<fblangref50-windowfuncs>> for completeness and correctness
* Document _<parenthesized-joined-table>_ in <<fblangref50-dml-select>>

|0.1
|05 May 2023
|MR
a|Copied the _Firebird 4.0 Language Reference_ as a starting point:

* renamed files and reference using _fblangref40_ to _fblangref50_
* where applicable, replaced reference to Firebird 4.0 with Firebird 5.0, or rephrased sentences referencing Firebird 4.0

|===

:sectnums:
