:sectnums!:

[appendix]
[[fblangref50-dochist]]
= Document History

The exact file history is recorded in our _git_ repository; see https://github.com/FirebirdSQL/firebird-documentation

[%autowidth, width="100%", cols="4", options="header", frame="none", grid="none", role="revhistory"]
|===
4+|Revision History

|1.0
|TBD
|MR
a|* Transformed a lot of NOTE-admonitions to be simple paragraphs or lists, or removed them entirely
* Documented where to find time zone region names

|0.9
|20 Apr 2024
|MR
|Corrected description of `RDB$CHECK_CONSTRAINTS` (https://github.com/FirebirdSQL/firebird-documentation/issues/206[#206])

|0.8
|2 Apr 2024
|MR
|Protocol names are lowercase (https://github.com/FirebirdSQL/firebird-documentation/issues/205[#205])

|0.7
|17 Jan 2024
|MR
a|* Changed note regarding `SKIP LOCKED` to (once again) match release notes
* Added columns `RDB$CONDITION_BLR` and `RDB$CONDITION_SOURCE` to `RDB$INDICES` (https://github.com/FirebirdSQL/firebird-documentation/issues/198[#198])
* Misc. copy editing of BLR column descriptions for consistent language
* Removed `ALTER PACKAGE BODY` documentation, as this feature doesn't exist (https://github.com/FirebirdSQL/firebird-documentation/issues/200[#200])

|0.6
|15 Dec 2023
|MR
a|* Fixed incorrect syntax documentation of forward declaration of subroutines (https://github.com/FirebirdSQL/firebird-documentation/issues/188[#188])
* Wrong link from `ALTER TRIGGER` to `CREATE TRIGGER` (https://github.com/FirebirdSQL/firebird-documentation/issues/189[#189])
* Fixed description of `RDB$INDICES.RDB$FOREIGN_KEY` (https://github.com/FirebirdSQL/firebird-documentation/issues/191[#191])
* Updated keywords with state as of snapshot 5.0.0.1271
* Added types 4 and 5 to `RDB$FUNCTION_ARGUMENTS.RDB$MECHANISM` (https://github.com/FirebirdSQL/firebird-documentation/issues/192[#192])
* Fixed formatting of `RDB$FUNCTION_ARGUMENTS.RDB$FIELD_TYPE` (https://github.com/FirebirdSQL/firebird-documentation/issues/194)

|0.5
|29 Sep 2023
|MR
a|* Removed unnecessary references to older Firebird versions
* Misc. copy-editing
* `CHAR_LENGTH`, `OCTET_LENGTH` and `BIT_LENGTH` use `BIGINT` for `BLOB`
* Fixed incorrect "equivalent" for `REGR_COUNT`
* Fixed incorrect references to idle timeout in `SET STATEMENT TIMEOUT`
* Documented that `OVERRIDING USER VALUE` also works for `GENERATED ALWAYS` identity columns
* Document `QUARTER` for `EXTRACT`, `FIRST_DAY`, and `LAST_DAY`
* Document `DECFLOAT_ROUND` and `DECFLOAT_TRAPS` for `RDB$GET_CONTEXT`
* Document `LEVEL` in `PLG$PROF_RECORD_SOURCES` and `PLG$PROF_RECORD_SOURCE_STATS_VIEW`, order of columns for profiler tables
* Document new limit for `IN`-list
* Document `OPTIMIZE FOR {FIRST {vbar} ALL} ROWS` on `SELECT` and `SET OPTIMIZE`
* Added negative subtype to `RDB$FIELDS.RDB$FIELD_SUB_TYPE`, and fixed formatting

|0.4
|20 Jun 2023
|MR
a|* Computed columns can be indexed with expression indexes
* Fixed wrong section levels for subsections of <<fblangref50-management-setdecfloat>>
* Replaced firebird-docs references with firebird-devel
* Updated <<fblangref50-appx02-tbl-errcodes01>> with error information from 5.0.0.1068
* Add caution about relying on ordered derived tables for <<fblangref50-aggfuncs-list>>

|0.3
|26 May 2023
|MR
a|* Added missing context variable names for <<fblangref50-scalarfuncs-get-context>>
* Documented hex-literal support for `INT128`
* `CURRENT_CONNECTION` returns `BIGINT`
* `PLG$PROF_RECORD_SOURCES.ACCESS_PATH` changed to `VARCHAR(255)`
* Example for `RDB$ROLE_IN_USE()` should use `RDB$ROLES` (https://github.com/FirebirdSQL/firebird-documentation/issues/184[#184])
* Changed explanation of maximum blob size (https://github.com/FirebirdSQL/firebird-documentation/issues/160[#160])
* Notes on RETURNING and updatable views (https://github.com/FirebirdSQL/firebird-documentation/issues/95[#95])
* Replaced occurrence of "`collation sequence`" with "`collation`"
* Removed section _Joins with stored procedures_ as it no longer applies
* Replaced mention that implicit join is deprecated and might get removed;
its use is merely discouraged.
* Removed "`Available in`" sections if they listed both DSQL and PSQL
* Replaced "`Used for`" paragraphs with a plain paragraph (so, without explicit "`Used for`" title)
* Rewrote function descriptions to include a short description at the top of each function section
* Added note in <<fblangref50-scalarfuncs-tbl-encrypt-req>> about AES variants
* Replaced incorrect `ROLE` keyword with `DEFAULT` in example in <<fblangref50-security-rdbadmin01>>
* Miscellaneous copy-editing

|0.2
|10 May 2023
|MR
a|* Documented "`standard`" plugin tables in new appendix <<fblangref50-appx07-plgtables>>
* Removed _Upgraders: PLEASE READ!_ sidebar from <<fblangref50-functions>>, the _Possible name conflict_ sections from function descriptions and the _Name Clash_ note on `LOWER()`
* Integrated (most) changes from the Firebird 5.0 beta 1 release notes
* Added new chapter <<fblangref50-sys-pckg>>, and moved `RDB$TIME_ZONE_UTIL` documentation to it, and added `RDB$BLOB_UTIL` and `RDB$PROFILER` documentation
* Documented that subroutines can access variables of their parent
* Simplified `CONTINUE` and `LEAVE` examples, by removing unnecessary `ELSE`
* Documented `PLAN`, `ORDER BY` and `ROWS` for `UPDATE OR INSERT` and `PLAN` and `ORDER BY` for `MERGE`
* Added <<fblangref50-dml-select-full-syntax>> as a first step to address current incomplete/simplified syntax used in <<fblangref50-dml-select>>
* Removed incorrect `<common-table-expression>` production in SELECT syntax
* Revised syntax used in <<fblangref50-dml-select>> and <<fblangref50-windowfuncs>> for completeness and correctness
* Document _<parenthesized-joined-table>_ in <<fblangref50-dml-select>>

|0.1
|05 May 2023
|MR
a|Copied the _Firebird 4.0 Language Reference_ as a starting point:

* renamed files and reference using _fblangref40_ to _fblangref50_
* where applicable, replaced reference to Firebird 4.0 with Firebird 5.0, or rephrased sentences referencing Firebird 4.0

|===

:sectnums:
