[[fblangref50-intro]]
= About the Firebird 5.0 Language Reference

This Language Reference describes the SQL language supported by Firebird 5.0.

This Firebird 5.0 Language Reference is the fourth comprehensive manual to cover all aspects of the query language used by developers to communicate, through their applications, with the Firebird relational database management system.

[[fblangref50-intro-subject]]
== Subject

The subject of this volume is Firebird's implementation of the SQL ("`Structured Query Language`") relational database language.
Firebird conforms closely with international standards for SQL, from data type support, data storage structures, referential integrity mechanisms, to data manipulation capabilities and access privileges.
Firebird also implements a robust procedural language -- procedural SQL (PSQL) -- for stored procedures, stored functions, triggers, and dynamically-executable code blocks.
These are the areas addressed in this volume.

This document does not cover configuration of Firebird, Firebird command-line tools, nor its programming APIs.

[[fblangref50-intro-authors]]
== Authorship

For the Firebird 5.0 version, the _Firebird 4.0 Language Reference_ was taken as the base, and Firebird 5.0 information was added based on the _Firebird 5.0 Release Notes_ and feature documentation.

[[fblangref50-intro-contributors]]
=== Contributors

[float]
==== Direct Content

* Dmitry Filippov (writer)
* Alexander Karpeykin (writer)
* Alexey Kovyazin (writer, editor)
* Dmitry Kuzmenko (writer, editor)
* Denis Simonov (writer, editor)
* Paul Vinkenoog (writer, designer)
* Dmitry Yemanov (writer)
* Mark Rotteveel (writer, editor)

[float]
==== Resource Content

* Adriano dos Santos Fernandes
* Alexander Peshkov
* Vladyslav Khorsun
* Claudio Valderrama
* Helen Borrie
* and others

[[fblangref50-intro-bugs]]
== Reporting Errors or Missing Content

If you find errors, missing content or other problems in this document, please report this in our https://github.com/FirebirdSQL/firebird-documentation/issues[issue tracker^] of the https://github.com/FirebirdSQL/firebird-documentation[firebird-documentation GitHub repository].

Pull requests with changes and fixes are also much appreciated.

[[fblangref50-acknowledgements]]
== Acknowledgments

[float]
[[sponsors-donors]]
=== Sponsors and Other Donors

See also the https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref25/firebird-25-language-reference.html#fblangref25-acknowledgements[Acknowledgements^] in the Firebird 2.5 Language Reference for the sponsors of the initial Russian version and its translation.

[float]
[[sponsors01-native]]
==== Sponsors of the Russian Language Reference Manual

[none]
* https://www.moex.com[Moscow Exchange] (Russia)
+
_Moscow Exchange is the largest exchange holding in Russia and Eastern Europe, founded on December 19, 2011, through the consolidation of the MICEX (founded in 1992) and RTS (founded in 1995) exchange groups.
Moscow Exchange ranks among the world's top 20 exchanges by trading in bonds and by the total capitalization of shares traded, as well as among the 10 largest exchange platforms for trading derivatives._

* https://www.ib-aid.com[IBSurgeon] (https://ibase.ru[ibase.ru]) (Russia)
+
_Technical support and developer of administrator tools for the Firebird DBMS._

[[fblangref50-contributing]]
== Contributing

There are several ways you can contribute to the documentation of Firebird, or Firebird in general:

* Participate on the mailing lists (see https://www.firebirdsql.org/en/mailing-lists/)
* Report bugs or submit pull requests on GitHub (https://github.com/FirebirdSQL/)
* Become a developer (contact us on https://groups.google.com/g/firebird-devel[firebird-devel])
* Donate to the Firebird Foundation (see https://www.firebirdsql.org/en/donate/)
* Become a paying member or sponsor of the Firebird Foundation (see
https://www.firebirdsql.org/en/firebird-foundation/)
