[#fbconf-env-firebird-msg]
= `FIREBIRD_MSG`

Location of Firebird message files.

.Configuration
Client, Server/Embedded

This setting is primarily a client-side setting, but may get used by the server if it formats and prints messages itself.

[#fbconf-concept-msg-file-resolve]
.How Firebird resolves a message file
. File specified by <<fbconf-env-isc-msgs>>
. Locale-specific file with relative path `intl/__locale__.msg` in the Firebird message directory (see <<fbconf-concept-msg-dir>>)
+
The value of _locale_ is derived from the first 10 characters of the last segment of environment variable `LC_MESSAGES` (after the last `/`, or otherwise after the last `\`, otherwise the entire value)
. File `firebird.msg` in the Firebird message directory (see <<fbconf-concept-msg-dir>>)

[#fbconf-concept-msg-dir]
.The Firebird message directory
* The directory specified by environment variable `FIREBIRD_MSG`, or
* the default Firebird message directory (if `FB_MSGDIR` was defined in the build configuration), or
* the Firebird root directory (see <<fbconf-env-firebird>>).

.See also
<<fbconf-env-firebird>>, <<fbconf-env-isc-msgs>>