[#fbconf-env-firebird-tmp]
= `FIREBIRD_TMP`

Default location for temporary files.

.Configuration
Server/Embedded

The directory specified in the `FIREBIRD_TMP` environment variables is used as the default location for temporary files.

The values of configuration items <<fbconf-temp-directories>> and <<fbconf-temp-table-directory>> take precedence.

The specified directory must exist.
The user of the Firebird process -- or the process running embedded -- must have sufficient privileges to create, write, and delete files and directories in that directory.

If `FIREBIRD_TMP` is not specified, Firebird will fall back as follows:

.Fallback on Android
. `TMP` (environment variable)
. Use `/data/local/tmp`

.Fallback on macOS
. `TMP` (environment variable)
. Use `/tmp` *or* -- if sandboxed -- the temporary directory of the current user

.Fallback on Linux and other non-Windows OSes
. `TMP` (environment variable)
. Use `/tmp`

.Fallback on Windows
. Result of https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppatha[`GetTempPath`^]
+
According to the Microsoft documentation, this determines its location on the first path found in:
+
--
.. `TMP` (environment variable)
.. `TEMP` (environment variable)
.. `USERPROFILE` (environment variable)
.. The Windows directory
--
. Use ``C:\temp\``footnote:[Given the directories checked for `GetTempPath`, this fallback is unlikely to get used in practice.]

.See also
<<fbconf-temp-directories>>, <<fbconf-temp-table-directory>>
