[#fbconf-env-firebird-lock]
= `FIREBIRD_LOCK`

Overrides the location of the Firebird lock files and other shared memory files.

.Configuration
Server/Embedded

The value must be set to an absolute path on the physical filesystem of the host.
The user running Firebird (or its embedded engine) needs to have sufficient privileges to create and delete files and subdirectories.

If there are multiple processes and/or different OS users accessing the same database files, they all need to use the same lock directory, and they all need sufficient privileges to this lock directory.
On Linux, this is generally achieved by giving the permissions to the `firebird` group and adding the users to this group.

.Incorrect use of FIREBIRD_LOCK can result in database corruption or other forms of data loss.
[WARNING]
====
Database corruption can happen when multiple processes and/or multiple OS users open the same database with different lock directories.
When using different lock directories, these processes cannot coordinate their access.

When in doubt, do not set this and use the server defaults.

This risk exists primarily when using Classic or SuperClassic (see also <<fbconf-server-mode>>);
SuperServer opens databases with exclusive access.
====

The default lock directory is:

Windows::
Subdirectory `firebird` in the common appdata directory (`CSIDL_COMMON_APPDATA`) -- for example `C:\ProgramData\firebird` -- with a fallback to the Firebird root directoryfootnote:[Given the common appdata directory should always be returned, this fallback shouldn't occur in practice, as far as we're aware.].

Android::
`/data/local/tmp/firebird`.

macOS::
`/tmp/firebird` *or* -- if sandboxed -- subdirectory `firebird` of the temporary directory of the current user.

Linux and other OSes::
`/tmp/firebird`
