[#fbconf-env-isc-inet-server-home]
= `ISC_INET_SERVER_HOME`

Sets the current working directory of the server (non-Windows only).

.Configuration
Server

.Use of ISC_INET_SERVER_HOME is not recommended
[CAUTION]
====
The exact use case of this environment variable is unclear.
It may affect how some relative paths are resolved.
We recommend not to set it.

The Firebird sources (`remote/inet.cpp`) have the following comment on this environment variable:

[quote,David Schnepper,remote/inet.cpp]
____
If the environment variable ISC_INET_SERVER_HOME is set, change the home directory to the specified directory.
Note that this will overrule the normal setting of the current directory to the effective user's home directory.
This feature was added primarily for testing via remote loopback - but does seem to be of good general use, so is activated for the release version. +
1995-February-27 David Schnepper
____

_The Firebird Book (Second Edition)_ by Helen Borrie says about this environment variable:

[quote,Helen Borrie,The Firebird Book (Second Edition)]
____
Sets the working directory for Classic server _ONLY_.
Make certain this variable is not set if you are running Superserver or Superclassic.
____

We can't corroborate that this is for Classic only, but it will reset the current working directory on each connection received by the server, which seems odd to say the least.
====
