[[rnfb30-bug]]
= Bugs Fixed

////
_https://github.com/FirebirdSQL/firebird/issues/nnnn[#nnnn (CORE-mmmm)]_
-- A description

_fixed by A. Person_

'''
////

[[bug-3010]]
== Firebird 3.0.10 Release: Bug Fixes

[[bug-3010-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/7176[#7176]_
-- Incorrect error "Invalid token. Malformed string." with union + blob + non-UTF8 varchar

_fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7147[#7147]_
-- Problems with use of big timeout (or no timeout at all) in trace service

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7141[#7141]_
-- Services manager breaks long lines into 1023 bytes portions when using _isc_info_svc_line_ in _Service::query()_

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7140[#7140]_
-- Wrong select result in case of special sort character

_fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7138[#7138]_
-- Problems accessing FB4 database, copied from another host

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7137[#7137]_
-- Optimizer regression: bad plan (HASH instead of JOIN) is chosen for some inner joins

_fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7135[#7135]_
--Firebird engine randomly fails when delivering mapping clear to other processes

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7122[#7122]_
-- Invalid state of mapping cache after replacement of database

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7121[#7121]_
-- Mapping error when server tries to use mapping rules from database in full shutdown state

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7106[#7106]_
-- Wrong detection of must-be-delimited user names

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7094[#7094]_
-- Incorrect indexed lookup of strings when the last keys characters are part of collated contractions and there is multi-segment insensitive descending index

_fixed by Adriano dos Santos Fernandes_

'''

[[bug-3010-crashes]]
=== Server Crashes/Hang-ups

_https://github.com/FirebirdSQL/firebird/issues/7160[#7160]_
-- Missing checkout in trace manager when performing user mapping may cause server hang

_fixed by Alex Peshkov_

'''

[[bug-3010-winonly]]
=== Windows Only

_https://github.com/FirebirdSQL/firebird/issues/7158[#7158]_
-- Serious issue with SYSDBA user after a Windows install with _EnableLegacyClientAuth_

_fixed by Paul Reeves_

'''

[[bug-3010-api]]
=== API/Remote Interface

_https://github.com/FirebirdSQL/firebird/issues/7128[#7128]_
-- Incorrect error message with _isc_sql_interprete()_

_fixed by Vlad Khorsun_

'''

[[bug-3010-utilities]]
=== Utilities

[[bug-3010-utilities-gbak]]
==== gbak

_https://github.com/FirebirdSQL/firebird/issues/7184[#7184]_
-- _gbak_ output is not being flushed to disk

_fixed by Alex Peshkov_

'''

[[bug-3010-utilities-gstat]]
==== gstat

_https://github.com/FirebirdSQL/firebird/issues/7191[#7191]_
-- _gstat_ fails, but return 0 error code with incorrect databases.conf

_fixed by Alexey Mochalov_

'''


[[bug-309]]
== Firebird 3.0.9 Release: Bug Fixes

[[bug-309-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/7119[#7119]_
-- Database statistics service could not find existing table(s)

_fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7118[#7118]_
-- Chained `JOIN .. USING` across the same column names may be optimized badly

_fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7112[#7112]_
-- Avoid unload of plugins in MacOS due to problematic reload of them

_fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7084[#7084]_
-- Creating unique constraints on MacOS fails on larger tables

_fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7057[#7057]_
-- Client-side positioned updates work wrongly with scrollable cursors

_fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7056[#7056]_
-- Fetching from a scrollable cursor may overwrite user-specified buffer and corrupt memory

_fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7043[#7043]_
-- Wrong message when user has no access to _/tmp/firebird_

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6966[#6966]_
-- Status vector for `EXECUTE STATEMENT(<empty string>)` is unstable if another execute block with correct statement was executed before

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/3357[#3357]_
-- Bad execution plan if some stream depends on multiple streams via a function

_fixed by Dmitry Yemanov_

'''

[[bug-309-crashes]]
=== Server Crashes/Hang-ups

_https://github.com/FirebirdSQL/firebird/issues/7115[#7115]_
-- Server hangs in trace code when it tries to update mapping cache

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7103[#7103]_
-- Server hangs and cannot be stopped after several `DELETE FROM MON$STATEMENTS` being issued in order to stop external `EXECUTE STATEMENT` which waits record for updating

_fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7067[#7067]_
-- Deadlock when using not initialized security database

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7060[#7060]_
-- Deadlock when execute test for CORE-4337

_fixed by Alex Peshkov_

'''

[[bug-309-winonly]]
=== Windows Only

_https://github.com/FirebirdSQL/firebird/issues/7109[#7109]_
-- Content of database file can be overwritten with zero bytes in some (rare) cases

_fixed by Vlad Khorsun_

'''


[[bug-308]]
== Firebird 3.0.8 Release: Bug Fixes

[[bug-308-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/7044[#7044]_
-- Validation error: Data page N {sequence M} marked as secondary but contains primary record versions in table T

_fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7036[#7036]_
-- Unexpected messages "Missing security context ..." in firebird.log

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6987[#6987]_
-- DATEDIFF does not support fractional value for MILLISECOND

_fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6984[#6984]_
-- Committed transaction could be marked as dead in some very special and rare case

_fixed by Vlad Khorsun, Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6967[#6967]_
-- PIO_read / PIO_write may falsely return success in a case when block was read/written incompletely

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6932[#6932]_
-- GTT's pages are not released while dropping it

_fixed by Ilya Eremin, Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/6918[#6918]_
-- Service detach is always traced

_fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/6866[#6866]_
-- Orphan records are left in RDB$SECURITY_CLASSES and RDB$USER_PRIVILEGES after DROP PROCEDURE/FUNCTION

_fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/6836[#6836]_
-- fb_shutdown() does not wait for self completion in other thread

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6782[#6782]_
-- Cannot get "records fetched" counter for procedures/functions in trace

_fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/6768[#6768 (CORE-6542)]_
-- Backup cannot be restored on a raw device (error during "open O_CREAT" operation for file "/dev/sda1")

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6759[#6759 (CORE-6532)]_
-- Results of concatenation with blob has no info about collation of source columns (which are declared with such info)

_fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/6758[#6758 (CORE-6531)]_
-- COMPUTED BY column looses charset and collate of source field <F> when <F> is either of type BLOB or VARCHAR casted to BLOB

_fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/6750[#6750 (CORE-6521)]_
-- CAST of infinity values to FLOAT doesn't work

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6747[#6747 (CORE-6518)]_
-- Wrong message when connecting to tiny trash database file

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6724[#6724 (CORE-6494)]_
-- Inconsistent translation "string->timestamp->string->timestamp" in the Dialect 1

_fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6719[#6719 (CORE-6489)]_
-- User without ALTER ANY ROLE privilege can use COMMENT ON ROLE

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6717[#6717 (CORE-6487)]_
-- FETCH ABSOLUTE and RELATIVE beyond bounds of cursor should always position immediately before-first or after-last

_fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6716[#6716 (CORE-6486)]_
-- FETCH RELATIVE has an off by one error for the first row

_fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6710[#6710 (CORE-6479)]_
-- COMMENT ON USER can only apply comment on user defined by the default UserManager plugin

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6698[#6698 (CORE-6466)]_
-- Comments before the first line of code are removed

_fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6683[#6683 (CORE-6450)]_
-- Races in cache of opened security databases

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6680[#6680 (CORE-6447)]_
-- Unexpectedly different text of message for parameterized expression starting from second run

_fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/6674[#6674 (CORE-6440)]_
-- Expression indexes containing COALESCE inside cannot be matched by the optimizer after migration from v2.5 to v3.0

_fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/2367[#2367 (CORE-6441)]_
-- Srp plugin keeps connection after database has been removed for ~10 seconds (SS and SC)

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6646[#6646 (CORE-6408)]_
-- RETURNING clause in MERGE cannot reference column in aliased target table using qualified reference (alias.column) if DELETE action present

_fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6624[#6624 (CORE-6385)]_
-- Wrong line and column information after IF statement

_fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6220[#6220 (CORE-5966)]_
-- Slow performance when executing SQL scripts as non-SYSDBA user

_fixed by Roman Simakov_

'''

_https://github.com/FirebirdSQL/firebird/issues/5877[#5877 (CORE-5611)]_
-- Higher memory consumption for prepared statements

_fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/5534[#5534 (CORE-5255)]_
-- String truncation exception on UPPER/LOWER functions, UTF8 database and some multibyte characters

_fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/5173[#5173 (CORE-4878)]_
-- Compound ALTER TABLE statement with ADD and DROP the same constraint failed if this constraint involves index creation (PK/UNQ/FK)

_fixed by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/5082[#5082 (CORE-4783)]_
-- Exception "too few key columns found for index" raises when attempt to create table with PK and immediatelly drop this PK within the same transaction

_fixed by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/3886[#3886 (CORE-3529)]_
-- RECREATE TABLE T with PK or UK is impossible after duplicate typing w/o commit when ISQL is launched in AUTODDL=OFF mode

_fixed by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/2469[#2469 (CORE-2032)]_
-- Stored procedure recursively called by calculated field fails after reconnect

_fixed by Vlad Khorsun_
'''

[[bug-308-crashes]]
=== Server Crashes/Hang-ups

_https://github.com/FirebirdSQL/firebird/issues/7034[#7034]_
-- Scroll cursor server crash

_fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6854[#6854]_
-- Crash occurs when SIMILAR TO is used

_fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6781[#6781]_
-- Crashing (due to UDF exception) server process hangs

_fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/6777[#6777]_
-- AV when engine shut down and cancels attachment that is waiting in lock manager

_fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/6755[#6755 (CORE-6528)]_
-- Connect to a database that contains broken pages can lead to server crash

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6731[#6731 (CORE-6501)]_
-- Segfault when shutting down database which got encrypted by another process

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6708[#6708 (CORE-6477)]_
-- Rare race condition in Plugin Manager could lead to the server crash

_fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/6670[#6670 (CORE-6433)]_
-- Firebird server crashes during a daily maintenance / set statistics index

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6650[#6650 (CORE-6412)]_
-- Firebird freezes when trying to manage users via triggers

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6265[#6265 (CORE-6015)]_
-- Segfault when using expression index with complex expression

_fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/1210[#1210 (CORE-2917)]_
-- Server hangs on I/O error during "open" operation for file "/tmp/firebird/fb_trace_ksVDoc"

_fixed by Alex Peshkov_

'''

[[bug-308-api]]
=== API/Remote Interface

_https://github.com/FirebirdSQL/firebird/issues/6896[#6896]_
-- Client forcing server to encryption

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6752[#6752 (CORE-6525)]_
-- Segfaults in fbclient when receiving invalid / unexpected data from server

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6751[#6751 (CORE-6524)]_
-- Various segfaults in fbclient

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6746[#6746 (CORE-6517)]_
-- CREATE DATABASE fails with 'Token unknown' error when DB name is enclosed in double quotes and 'DEFAULT CHARACTER SET' is specified after DB name

_fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6718[#6718 (CORE-6488)]_
-- Event delivery could be missed when local (XNET) protocol is used

_fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/6700[#6700 (CORE-6468)]_
-- Wire compression causes sporadic "Error reading data from the connection" errors

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6679[#6679 (CORE-6446)]_
-- CLOOP envelopes are wrong regarding IStatus

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6669[#6669 (CORE-6432)]_
-- Possible buffer overflow in client library in Attachment::getInfo() call

_fixed by Alex Peshkov_

'''

[[bug-308-winonly]]
=== Windows Only

_https://github.com/FirebirdSQL/firebird/issues/6949[#6949]_
-- On Windows, engine may hang on initialization when another instance with different lock directory is running

_fixed by Vlad Khorsun_

'''

[[bug-308-builds]]
=== Builds

_https://github.com/FirebirdSQL/firebird/issues/6780[#6780]_
-- firebird.msg is missing in Firebird Android builds

_fixed by Alex Peshkov_

'''

[[bug-308-utilities]]
=== Utilities

[[bug-308-utilities-isql]]
==== isql

_https://github.com/FirebirdSQL/firebird/issues/6796[#6796]_
-- Buffer overflow when padding line with national characters causes ISQL to crash

_fixed by Adriano dos Santos Fernandes_

'''

[[bug-308-utilities-gbak]]
==== gbak

_https://github.com/FirebirdSQL/firebird/issues/7031[#7031]_
-- gbak -b fails with "invalid transaction handle (expecting explicit transaction start)"

_fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/6999[#6999]_
-- GBAK removes database and backup files if finished unsuccessfully

_fixed by Ilya Eremin, Alex Peshkov_

'''

[[bug-308-utilities-gfix]]
==== gfix

_https://github.com/FirebirdSQL/firebird/issues/6817[#6817]_
-- -fetch_password passwordfile does not work with GFIX

_fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6672[#6672 (CORE-6437)]_
-- GFIX cannot set big value for buffers

_fixed by Vlad Khorsun_

'''

[[bug-308-utilities-gstat]]
==== gstat

_https://github.com/FirebirdSQL/firebird/issues/6729[#6729 (CORE-6499)]_
-- GSTAT with switch -t executed via services fails with "found unknown switch" error

_fixed by Alex Peshkov_

'''


[[bug-307]]
== Firebird 3.0.7 Release: Bug Fixes

The following bug fixes were reported prior to the version 3.0.7 official release:

[[bug-307-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-6370[CORE-6370])_
-- Memory leak was possible when a computed field containing COALESCE/CAST is selected.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6358[CORE-6358])_
-- Adding NOT NULL column with DEFAULT value could cause default values to be volatile or have the wrong charset.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6351[CORE-6351])_
-- Inter-dependent computed fields could be wrongly evaluated as NULL in some cases.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6346[CORE-6346])_
-- Alternate quoting did not work on some particular cases.

_fixed by A. dos Santos Fernandes_

'''

[[bug-307-crashes]]
=== Server Crashes/Hang-ups

_(http://tracker.firebirdsql.org/browse/CORE-6411[CORE-6411])_
-- Server would crash attempting to create a table with many (more than 5460) fields.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6367[CORE-6367])_
-- Server would crash receiving a malformed packet from the network.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6360[CORE-6360])_
-- Engine could hang due to races when starting the crypt thread and simultaneous shutdown.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6348[CORE-6348])_
-- Wire compression could cause the server to freeze.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6347[CORE-6347])_
-- New connections to the server could stall, when there is an existing connection to the database.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6346[CORE-6346])_
-- New connection to the server could hang inside the engine.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6253[CORE-6253])_
-- Locked fb_lock file could cause a server crash.

_fixed by V. Khorsun_

'''

[[bug-307-api]]
=== API/Remote Interface

_(http://tracker.firebirdsql.org/browse/CORE-6388[CORE-6388])_
-- Client library code could assert when closing the event thread in the debug build.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6364[CORE-6364])_
-- Wrong reference counting in the UDR trigger sample.

_fixed by V. Khorsun_

'''

[[bug-307-utilities]]
=== Utilities

[[bug-307-utilities-isql]]
==== isql

_(http://tracker.firebirdsql.org/browse/CORE-6147[CORE-6147])_
-- Script with extracted (using isql -x) metadata could fail creating the global mapping.

_fixed by A. Peshkov_

'''

[[bug-307-utilities-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-6392[CORE-6392])_
-- Space inside the database path could prevent backup using GBAK in the -SE mode.

_fixed by A. Peshkov_

'''

[[bug-307-utilities-fbsvcmgr]]
==== fbsvcmgr

_(http://tracker.firebirdsql.org/browse/CORE-6396[CORE-6396])_
-- Error "Unknown tag (0) in isc_svc_query() result" could be reported when running trace with fbsvcmgr.

_fixed by A. Peshkov_

'''

[[bug-306]]
== Firebird 3.0.6 Release: Bug Fixes

The following bug fixes were reported prior to the version 3.0.6 official release:

[[bug-306-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-6343[CORE-6343])_
-- Rolled back transaction could produce unexpected results leading to duplicate values in the primary key.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6331[CORE-6331])_
-- Memory leak was possible when executing some statements and expressions.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6323[CORE-6323])_
-- File-system ID could be duplicated among databases located on different volumes.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6314[CORE-6314])_
-- Assigning `RDB$DB_KEY` to a multi-byte `CHAR`/`VARCHAR` variable/parameter did not enforce the target limit.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6310[CORE-6310])_
-- Varchar length limit was not enforced when assigning a string with trailing spaces in multi-byte character sets.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6296[CORE-6296])_
-- Many connections could result in poor performance.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6290[CORE-6290])_
-- Hex number used at the end of statement could read invalid memory and produce wrong values or exceptions.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6280[CORE-6280])_
-- `MERGE` statement could lose parameters in the "```WHEN [NOT] MATCHED```" clause that will never be matched.
This could also cause server crashes in some situations.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6266[CORE-6266])_
-- Deleting records from `MON$ATTACHMENTS` using the `ORDER BY` clause didn't close the corresponding attachments.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6252[CORE-6252])_
-- UNIQUE CONSTRAINT violation could be possible.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6250[CORE-6250])_
-- Signature mismatch error could be raised when creating package body on identical packaged procedure header.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6246[CORE-6246])_
-- Output parameters could be wrongly described if there are too many number of columns in the result set.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6230[CORE-6230])_
-- It was impossible to connect to a database if the security.db reference was removed from `databases.conf`.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6221[CORE-6221])_
-- Incorrect implementation of `allocFunc()` for zlib1: memory leak was possible.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6110[CORE-6110])_
-- 64-bit transaction IDs were not stored properly inside the status vector.

_fixed by I. Eremin_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5862[CORE-5862])_
-- `RDB$CHARACTER_LENGTH` in `RDB$FIELDS` was not being populated when the column was a computed `VARCHAR` without an explicit type.

_fixed by A. dos Santos Fernandes_

'''

[[bug-306-crashes]]
=== Server Crashes/Hang-ups

_(http://tracker.firebirdsql.org/browse/CORE-6345[CORE-6345])_
-- Server could crash on overflow of numeric division result.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6317[CORE-6317])_
-- Server could crash executing long `GRANT` statements.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6254[CORE-6254])_
-- Server could crash when using `SET TRANSACTION` and `ON TRANSACTION START` trigger uses `EXECUTE STATEMENT` against current transaction.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6251[CORE-6251])_
-- Server would crash when built-in function `LEFT` or `RIGHT` is missing its 2nd argument.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6231[CORE-6231])_
-- Server would crash during shutdown of XNET connection to a local database when events have been registered.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6224[CORE-6224])_
-- Server could crash due to double destruction of the `rem_port` object.

_fixed by D. Kovalenko, A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6217[CORE-6217])_
-- Dangerous (possibly leading to a crash) work with pointer: `delete ptr; ptr=new ;`.

_fixed by D. Kovalenko, A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5972[CORE-5972])_
-- External engine trigger would crash the server if the table has computed fields.

_fixed by A. dos Santos Fernandes_

'''

[[bug-306-builds]]
=== Builds

_(http://tracker.firebirdsql.org/browse/CORE-6295[CORE-6295])_
-- Distributed header files were incomplete (missing some type declarations).

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6189[CORE-6189])_
-- Building the bundled libtommath could fail.

_fixed by A. Peshkov_

'''

[[bug-306-api]]
=== API/Remote Interface

_(http://tracker.firebirdsql.org/browse/CORE-6283[CORE-6283])_
-- Result of `isNullable()` in message metadata, returned by metadata builder, did not match datatype set by `setType()` in metadata builder.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6227[CORE-6227])_
-- `isc_info_svc_user_dbpath` was always returning an alias of the main security database.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6212[CORE-6212])_
-- Authentication plugin on the server could read garbage data from the client instead of the empty packet.

_fixed by A. Peshkov_

'''

[[bug-306-posixonly]]
=== POSIX Only

_(http://tracker.firebirdsql.org/browse/CORE-6269[CORE-6269])_
-- Server could ignore `KeepAlive` settings (server connection/process is not killed when its client endpoint is lost).

_fixed by A. Peshkov_

'''

[[bug-306-utilities]]
=== Utilities

[[bug-306-utilities-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-6329[CORE-6329])_
-- GBAK with `service_mgr` and `Win_Sspi_ authentication could raise an error in clumplet API.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6265[CORE-6265])_
-- Existing mapping rules were removed by the backup/restore cycle.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6264[CORE-6264])_
-- GBAK with PIPE to `stdout`: invalid content in the 'service_mgr' mode.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6233[CORE-6233])_
-- Wrong dependencies of stored function on view were created after backup/restore.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6208[CORE-6208])_
-- `CREATE DATABASE` permission would disappear from security.db after the backup/restore cycle.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6130[CORE-6130])_
-- Creating backup to `STDOUT` using the service manager was broken.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2251[CORE-2251])_
-- GBAK doesn't return the error code in some cases.

_fixed by A. Peshkov_

'''

[[bug-306-utilities-gfix]]
==== gfix

_(http://tracker.firebirdsql.org/browse/CORE-5364[CORE-5364])_
-- `gfix -online normal` did not raise an error when there was another SYSDBA-owned session open.

_fixed by A. Peshkov_

'''

[[bug-306-utilities-isql]]
==== isql

_(http://tracker.firebirdsql.org/browse/CORE-6260[CORE-6260])_
-- Warnings were not always displayed in ISQL.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6116[CORE-6116])_
-- Metadata script extracted with ISQL from a database restored from a version 2.5 backup was invalid if some table has `COMPUTED BY` fields.

_fixed by A. dos Santos Fernandes_

'''

[[bug-306-utilities-nbackup]]
==== nBackup

_(http://tracker.firebirdsql.org/browse/CORE-6319[CORE-6319])_
-- NBACKUP called via the Services API was locking the database file after error.

_fixed by V. Khorsun_

'''

[[bug-306-utilities-svcmgr]]
==== fbsvcmgr

_(http://tracker.firebirdsql.org/browse/CORE-6309[CORE-6309])_
-- fbsvcmgr could not decode information buffer returned by GFIX list limbo service.

_fixed by A. Peshkov_

'''

[[bug-305]]
== Firebird 3.0.5 Release: Bug Fixes

The following bug fixes were reported prior to the version 3.0.5 official release:

[[bug-305-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-6203[CORE-6203])_
-- "`Error reading data from the connection`" could be raised sometimes when using a non-default authentication plugin.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6197[CORE-6197])_
-- The client library could leak memory when resolving the remote host name.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6182[CORE-6182])_
-- Firebird's internal timer could incorrectly reset the other existing timer entries.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6171[CORE-6171])_
-- Error "`No current record for fetch operation`" could be raised for queries containing an aggregated sub-select.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6163[CORE-6163])_
-- Generator pages were not encrypted.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6150[CORE-6150])_
-- Bugcheck could be raised when some PK\UK\FK constraint checks a record already marked as damaged.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6144[CORE-6144])_
-- Inconsistent behaviour of the `NEW` context variable was observed in `AFTER UPDATE OR DELETE` triggers.

_fixed by I. Eremin_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6143[CORE-6143])_
-- Error "`Multiple maps found for ...`" was raised in not appropriate case.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6138[CORE-6138])_
-- Inconsistent behavior was observed regarding visibility of the master record while inserting the detail record.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6134[CORE-6134])_
-- Different error messages ("`Your user name and password are not defined`" vs "`Missing security context`") could be reported for a failed login depending on whether the `Win_Sspi` plugin is present in the configuration.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6108[CORE-6108])_
-- Error "`Datatypes are not comparable in expression`" could be raised for a `COALESCE` function used inside an expression.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6097[CORE-6097])_
-- Connection could not see itself in `MON$ATTACHMENTS` when Windows domain/username (using `Win_Sspi` authentication) is exactly 31 bytes long.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6090[CORE-6090])_
-- BLOB fields could be suddenly set to ``NULL``s during `UPDATE` after a table format change.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6089[CORE-6089])_
-- BLOBs were unnecessarily copied during `UPDATE` after a table format change.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6087[CORE-6087])_
-- `CAST` function used inside a union could be ignored.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6078[CORE-6078])_
-- `CREATE OR ALTER` series of statements were ignoring the existing permissions.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6067[CORE-6067])_
-- The client library could leak memory if DSQL cursors are closed after the transaction commit.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6063[CORE-6063])_
-- Firebird server could return the `op_accept` packet instead of the expected `op_accept_data` one.

_fixed by D. Kovalenko_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6050[CORE-6050])_
-- The client library was attempting to open files not existent on the client host when connecting to a remove version 2.5 server.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6043[CORE-6043])_
-- Global temporary tables created with the `ON COMMIT DELETE ROWS` clause were not releasing their used space in the temporary file(s) at `COMMIT RETAINING` or `ROLLBACK RETAINING`.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6038[CORE-6038])_
-- Srp user manager could sporadically create user accounts that cannot pass the authentication.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5995[CORE-5995])_
-- The "`creator`" user name was empty in user trace sessions.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5993[CORE-5993])_
-- Error message was missing inside `firebird.log` after failure to create the audit log file.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5991[CORE-5991])_
-- Trace could not work correctly with quoted file names in the trace configurations.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5986[CORE-5986])_
-- Condition `NULL IS [NOT] {FALSE | TRUE}` was evaluated incorrectly (`NULL` was returned instead of the expected `FALSE`/`TRUE`).

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5985[CORE-5985])_
-- `ROLE` option was ignored when specified for a remote `EXECUTE STATEMENT` command.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5982[CORE-5982])_
-- Error "`no permission for SELECT access`" could be raised when a BLOB is used as input or output parameter of a stored procedure.

_fixed by D. Starodubov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5966[CORE-5966])_
-- Slow performance could be noticed when executing SQL scripts as non-SYSDBA user.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5965[CORE-5965])_
-- Firebird 3 optimizer could choose a less efficient plan than the Firebird 2.5 optimizer.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5949[CORE-5949])_
-- Bugcheck could happen when a read-only database with non-zero linger is converted into a read-write mode.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5935[CORE-5935])_
-- Bugcheck 165 ("`cannot find tip page`") could happen under load in Classic and SuperClassic.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5926[CORE-5926])_
-- `CREATE MAPPING` with non-ASCII user name could lead to the "`Malformed string`" error message.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5918[CORE-5918])_
-- Memory statistics ('used' / 'mapped' counters) was not always accurate.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5907[CORE-5907])_
-- Trace session could not be started if the 'database' section contains a pattern including curvy brackets.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5888[CORE-5888])_
-- Firebird server on Android had problems with `NUMERIC` values (scale was not reported properly).

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5823[CORE-5823])_
-- Error "`no permission for SELECT access`" was raised when selecting a BLOB field from a stored procedure.

_fixed by D. Starodubov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5795[CORE-5795])_
-- `ORDER BY` clause on compound index could prevent from using other available indices.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5784[CORE-5784])_
-- Lock folder inizialization was not multi-process safe.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5639[CORE-5639])_
-- Mapping created for the `Win_Sspi` plugin did not cause the Windows user group to be converted to a Firebird role.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5395[CORE-5395])_
-- Error "`Invalid data type for negation`" was raised for a query containing a negated parameter.

_fixed by A. dos Santos Fernandes, D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5074[CORE-5074])_
-- Charset ID of the array element could be lost (zero was always reported) when preparing a query selecting from that array field.

_fixed by D. Kovalenko_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5070[CORE-5070])_
-- Compound index could not be used for filtering in some `ORDER/GROUP BY` queries.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3925[CORE-3925])_
-- Bugcheck could be raised after attempting to create a self-referencial FK that violates the existing data.

_fixed by V. Khorsun_

'''

[[bug-305-crashes]]
=== Server Crashes/Hang-ups

_(http://tracker.firebirdsql.org/browse/CORE-6086[CORE-6086])_
-- Server could crash while creating some complex stored procedure (containing multiple CTEs).

_fixed by V. Khorsun, D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6068[CORE-6068])_
-- Server could hang while compiling a large package body containing a syntax error.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6027[CORE-6027])_
-- Server could hang at the incoming attachment if it happened immediately after the trace session has been stopped.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6015[CORE-6015])_
-- Server crash could happen while using the computed index based on a complex expression.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5980[CORE-5980])_
-- Firebird could crash during concurrent operations with expression indices.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5972[CORE-5972])_
-- External engine trigger was causing the server to crash if the underlying table has computed field(s).

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5950[CORE-5950])_
-- Server could deadlock when some user attaches a bugchecked database.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5943[CORE-5943])_
-- The server could crash preparing a query having `DISTINCT` or `ORDER BY` together with a non-field expression in the select list.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5936[CORE-5936])_
-- The Firebird server could crash at the end of a _gbak_ backup.

_fixed by V. Khorsun_

'''

[[bug-305-builds]]
=== Builds

_(http://tracker.firebirdsql.org/browse/CORE-6007[CORE-6007])_
-- Firebird would not build on MacOS with the fresh toolchain installed, compilation failed while building the `editline` library.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5989[CORE-5989])_
-- Linking the binaries could fail due to missing `libiconv_open` reference if the `libiconv` library is installed.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5934[CORE-5934])_
-- _gpre_boot_ was failing to link using CMake, reporting undefined reference `dladdr` and `dlerror`.

_fixed by A. Peshkov_

'''

[[bug-305-api]]
=== API/Remote Interface

_(http://tracker.firebirdsql.org/browse/CORE-6142[CORE-6142])_
-- Error "`connection lost to database`" could be raised when application creates multiple local attachments (using the XNET protocol) simultaneously.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5927[CORE-5927])_
-- Connection could remain not encrypted using some non-standard authentication plugins even if a correct key was provided.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5902[CORE-5902])_
-- Events processing was not working between Windows and MacOS hosts.

_fixed by A. dos Santos Fernandes, V. Khorsun_

'''

[[bug-305-posixonly]]
=== POSIX Only

_(http://tracker.firebirdsql.org/browse/CORE-6031[CORE-6031])_
-- The first connection to any database was causing a small memory leak related to the `binreloc` library initialization.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6026[CORE-6026])_
-- Incorrect alignment was used for the `BIGINT` data type transferred from/to UDR libraries in 32-bit Linux builds.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5955[CORE-5955])_
-- The `binreloc` library could fail to initialize properly with `ld` versions 2.31 and above, causing the Firebird binaries to wrongly detect its root directory.

_fixed by R. Simakov_

'''

[[bug-305-maconly]]
=== MacOS Only

_(http://tracker.firebirdsql.org/browse/CORE-6122[CORE-6122])_
-- An attempt to call the properly declared UDF was raising the "`module name or entrypoint could not be found`" error on MacOS Mojave (10.14.3).

_fixed by P. Beach_

'''

[[bug-305-winonly]]
=== Windows Only

_(http://tracker.firebirdsql.org/browse/CORE-5959[CORE-5959])_
-- Firebird could return incorrect (outdated) current time/timestamp after the time zone was changed at the operating system level.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3900[CORE-3900])_
-- VC runtime installer could reboot the system before the Firebird installation process finishes.

_fixed by B. Walker, P. Reeves_

'''

[[bug-305-utilities]]
=== Utilities

[[bug-305-utilities-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-6028[CORE-6028])_
-- User-defined triggers declared for system tables were included into backups, and it is impossible to alter/drop them due to system tables protection in Firebird 3.
Starting with version 3.0.5, _gbak_ skips such triggers during both backup and restore operations.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6000[CORE-6000])_
-- _gbak_ was reporting the authentication error "`Your user name and password are not defined`" when the "```-fe(tch_password)```" command switch is specified and _gbak_ was running as a service.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5118[CORE-5118])_
-- Indices on computed fields were broken after a restore, with all keys being set to `NULL`.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2440[CORE-2440])_
-- Restoring a database with a computed index on a computed field was providing the wrong index and wrong query results.

_fixed by D. Yemanov_

'''

[[bug-305-utilities-gpre]]
==== gpre

_(http://tracker.firebirdsql.org/browse/CORE-6104[CORE-6104])_
-- Incorrect error "`invalid request handle`" was raised by the __gpre__-generated code when an embedded user does not have proper permissions for the table.

_fixed by D. Yemanov_

'''

[[bug-305-utilities-isql]]
==== isql

_(http://tracker.firebirdsql.org/browse/CORE-6040[CORE-6040])_
-- Metadata script extracted using `isql -x` was invalid if some table contains a `COMPUTED BY` column.

_fixed by A. dos Santos Fernandes_

'''

[[bug-305-utilities-nbackup]]
==== nBackup

{nbsp}

[[bug-305-utilities-svcmgr]]
==== fbsvcmgr

_(http://tracker.firebirdsql.org/browse/CORE-6141[CORE-6141])_
-- `fbsvcmgr action_repair rpr_list_limbo_trans` was not showing the expected list of 'in limbo' transactions.

_fixed by A. Peshkov_

'''

[[bug-305-utilities-tracemgr]]
==== fbtracemgr

_(http://tracker.firebirdsql.org/browse/CORE-6045[CORE-6045])_
-- Segmentation fault could happen in _fbtracemgr_ while closing it using the Ctrl-C keystroke.

_fixed by A. Peshkov_

'''

[[bug-304]]
== Firebird 3.0.4 Release: Bug Fixes

The following bug fixes were reported prior to the version 3.0.4 official release:

[[bug-304-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-5905[CORE-5905])_
-- Fixed some inconsistencies that could  occur when using `ALTER FUNCTION` to replace a legacy UDF with a PSQL function having the same name.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5904[CORE-5904])_
-- An attempt to create global mapping with a `FROM` field length greater than the SQL identifier length would fail.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5900[CORE-5900])_
-- Login attempts during engine shutdown would cause unnecessary delays in the shutdown process.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5898[CORE-5898])_
-- ROLE was not passed in `EXECUTE STATEMENT ... ON EXTERNAL`.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5891[CORE-5891])_
-- The wrong events were released when a dead process was detected, i.e. valid events of a valid connection were  released instead of the events of the broken connection.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5884[CORE-5884])_
-- An initial global mapping from the `Srp` plugin would not work.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5881[CORE-5881])_
-- Network server would ignore any error that occurred in the `KeyHolderPlugin` when establishing the initial callback with a client.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5880[CORE-5880])_
-- Unhandled: C0000005.ACCESS_VIOLATION could cause the server to crash.
The issue was related with events processing and could happen when `POST_EVENT` ran from an `ON DISCONNECT` trigger.
The same exception could occur if the application failed to cancel events when disconnecting.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5879[CORE-5879])_
-- Error reading/writing data to connection: appears to be related to CORE-5880 (above).

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5852[CORE-5852])_
-- The system trigger `RDB$TRIGGER9` checks that an object exists.
However, existence checks for generators and exceptions were not implemented for checking when granting the `USAGE` privilege on generator and exception objects.
As a result, it was possible to grant `USAGE` on a non-existent object.

_fixed by R. Simakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5847[CORE-5847])_
-- The error message returned from a primary key violation was returning "`Malformed string`" instead of the key value.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5846[CORE-5846])_
-- `CREATE VIEW` was issuing a faulty error "`Implementation of text subtype 512 not located`".

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5844[CORE-5844])_
-- Firebird was not cancelling events when the client disconnected.
See also CORE-5879 and CORE-5880, above.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5843[CORE-5843])_
-- Failures in a `TRANSACTION START` trigger were not being handled correctly.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5840[CORE-5840])_
-- A user was able to create a table that had a foreign key reference to another table to which he had no access privilege.

_fixed by R. Simakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5837[CORE-5837])_
-- Inconsistent results when working with `GLOBAL TEMPORARY TABLE ON COMMIT PRESERVE ROWS`.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5822[CORE-5822])_
-- The client would get the error SQLSTATE = 28000 ("user/password not defined") if `WireCrypt = Disabled` was used on the client side.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5819[CORE-5819])_
-- An attachment could persist after it was deleted from `MON$ATTACHMENTS`.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5804[CORE-5804])_
-- Fixed several legacy errors and anomalies in the implementation of the `REVOKE` operator.

_fixed by R. Simakov_

'''

_(CORE-5801, link not available)_
-- Unauthorized BLOB access vulnerability was fixed.

_fixed by D. Starodubov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5796[CORE-5796])_
-- The _gstat_ utility could produce  a faulty report concerning the presence of some non-encrypted pages in a database.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5793[CORE-5793])_
-- The error returned from `DbCryptPlugin::setKey()` ("`Missing correct crypt key`") was not helpful for diagnostics.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5791[CORE-5791])_
-- The ODS 12.0 for Windows and Linux-x64 builds differs from Linux-x86.
The fix results in a minor ODS change, from 12.0 to 12.2, for some but not all platforms.
This has certain implications for compatibility, so please read <<rnfb30-apiods-ods-12-2,these notes>>.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5790[CORE-5790])_
-- User with `DROP DATABASE` privilege could not drop the database.

_fixed by R. Simakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5788[CORE-5788])_
-- *Security Patch*: Replacement of use of SHA-1 in the SRP Client Proof with SHA-256.
See <<rnfb30-security-srp-patch304,V. 3.0.4 SRP Security Patch>> in the Security chapter of these notes.

_fixed by A. Whyman, A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5783[CORE-5783])_
-- `EXECUTE STATEMENT` was ignoring the text of the SQL query string after a comment of the double-hyphen form ('```--```').

The bug was solved by ensuring that the parser properly handled a newline symbol.

However, when `EXECUTE STATEMENT` gets the SQL query text from a binary BLOB variable, the engine uses a special blob filter (`filter_text`) to convert the binary blob to text.
For some reason, this blob filter treats \n (new-line) as a segment boundary and  _removes_ it from the output.
In a case where the line-endings in the binary BLOB were stored as \r\n, the SQL query text received by `EXECUTE STATEMENT` thus loses the newline directive, and the PSQL parser is left with no way to detect the end of the single-line comment.

The BLOB filter `filter_text` will not be changed to cater for the edge case of applying a binary BLOB to `EXECUTE STATEMENT`.
The solution is to avoid using a binary BLOB to store data that is to be used as text.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5780[CORE-5780])_
-- The server would hang when a client tried to send DB encryption keys that were too long to fit in the TCP buffer that FB allocates for sending/receiving messages, `TcpRemoteBufferSize`.
The fix is to drop the attachment as soon as the server detects a fragmented packet in the async receiver.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5776[CORE-5776])_
-- Error "`Input parameter mismatch`" could be thrown after altering a function to replace an external function with a PSQL function.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5773[CORE-5773])_
-- A PSQL (explicit) cursor could not see an inserted record, because cursor stability based on savepoints and the Undo log could not be applied to explicit cursors.
A different approach was taken to implement stability for explicit cursors.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5762[CORE-5762])_
-- Wrong transaction number in system table `RDB$PAGES` relation could cause infinite recursion in the engine and result in a segfault.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5757[CORE-5757])_
-- Deadlock with events.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5755[CORE-5755])_
-- Granting a privilege on a non-existent object produced no error or warning.

_fixed by R. Simakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5754[CORE-5754])_
-- Since Firebird does not have explicit privileges for triggers, `ALTER TRIGGER` would check the privileges for `ALTER DATABASE`, which was correct for database triggers but wrong for table-level triggers.

_fixed by R. Simakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5753[CORE-5753])_
-- The parser allowed the use of `WITH GRANT OPTION` when granting the `EXECUTE` privilege to functions and packages.
This was wrong.

_fixed by R. Simakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5747[CORE-5747])_
-- A user could grant `USAGE` privileges to self.

_fixed by R. Simakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5743[CORE-5743])_
-- A conversion error could be thrown when both `GROUP BY`/`ORDER BY` expressions and `WHERE` expressions contained literals.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5702[CORE-5702])_
-- Firebird on Windows was leaking handles.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4964[CORE-4964])_
-- Genuine errors during connection to the security database were hidden by the Srp user manager.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-405[CORE-405])_
-- An old pitfall: if an index contained garbage and automatic GC was disabled, it would not be possible to create unique indexes or `PRIMARY`, `UNIQUE` or `FOREIGN KEY` constraints. 

_fixed by V. Khorsun_

'''

[[bug-304-crashes]]
=== Server Crashes/Hang-ups

_(http://tracker.firebirdsql.org/browse/CORE-5863[CORE-5863])_
-- A Classic process could crash when the client had disconnected.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5830[CORE-5830])_
-- The encryption interface could crash the Firebird process when working on big database file.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5815[CORE-5815])_
-- The server could hang for 60/120 seconds if the client disconnected during the database encryption key transfer callback.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5756[CORE-5756])_
-- Server could crash when trying to recreate a table that is in use for a DML operation.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5436[CORE-5436])_
-- SuperClassic server would hang under load.

_fixed by V. Khorsun_

'''

[[bug-304-api]]
=== API/Remote Interface

[[bug-304-tag]]
_(http://tracker.firebirdsql.org/browse/CORE-5911[CORE-5911])_
-- Connection could hang if there was no activity for 60 seconds.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5772[CORE-5772])_
-- A client connection could hang when working with events under high load.

_fixed by A. Peshkov_

'''

[[bug-304-builds]]
=== Builds

_(http://tracker.firebirdsql.org/browse/CORE-5865[CORE-5865])_
-- An alignment error would occur on x86_64 when using clang to compile Firebird, due to an optimization in that environment.
It was known to affect builds for MacOSX and LibreOffice Base.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5824[CORE-5824])_
-- Segmentation fault during install on Linux.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5817[CORE-5817])_
-- Firebird would not compile with ICU 60 or higher.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5778[CORE-5778])_
-- `install.sh` would fail  if the `-path` argument contained 'firebird'.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5769[CORE-5769])_
-- Database crypt plug-in sample in Pascal was broken.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5765[CORE-5765])_
-- Missing directives in `Firebird.pas`.

_fixed by A. Whyman, A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5764[CORE-5764])_
-- Installation of Firebird 3.0.3 on SLES 12 SP3 would fail with "`Could not find acceptable ICU library`".

_fixed by A. Peshkov_

'''

[[bug-304-utilities]]
=== Utilities

[[bug-304-utilities-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-5899[CORE-5899])_
-- Using _gbak_ as a service could cause memory leakage.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5893[CORE-5893])_
-- _gbak_ could crash the database engine when mixing a database alias with the full database path.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5833[CORE-5833])_
-- Metadata triggers for some object types (views, exceptions, roles, indexes, domains) were lost in the backup-restore process.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5760[CORE-5760])_
-- The server process could crash while restoring a database.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5745[CORE-5745])_
-- SQL privileges error during database restore.

_fixed by A. Peshkov_

'''

[[bug-304-utilities-gfix]]
==== gfix

_(http://tracker.firebirdsql.org/browse/CORE-5872[CORE-5872])_
-- Database validation would report false errors "`Record XXX has bad transaction`" and\or "`Record XXX is wrong length`" when the record's transaction number exceeded 2^32^.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5869[CORE-5869])_
-- Sweep was failing to increment the OIT value past 2^32^, when Next Transaction value was already higher than 2^32^.

_fixed by V. Khorsun_

'''

[[bug-304-utilities-gsec]]
==== gsec

_(http://tracker.firebirdsql.org/browse/CORE-5829[CORE-5829])_
-- The _gsec_ utility was not releasing the user manager plug-in.

_fixed by A. Peshkov_

'''

[[bug-304-utilities-gstat]]
==== gstat

_(http://tracker.firebirdsql.org/browse/CORE-5831[CORE-5831])_
-- Output of _gstat_ from an encrypted database was not user-friendly.

_fixed by A. Peshkov_

'''

[[bug-304-utilities-isql]]
==== isql

_(http://tracker.firebirdsql.org/browse/CORE-5870[CORE-5870])_
-- The `SHOW DATABASE` command in _isql_ was returning zero for statistics with a value exceeding the range of 32-bit integer.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5742[CORE-5742])_
-- An incorrect error message was returned in _isql_ when trying to create a database when logged in with the wrong password.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5737[CORE-5737])_
-- Invalid parameters for gds transaction in _isql_ would cause it to hang when trying to show various system objects while another attachment had uncommitted changes to those objects.

_fixed by A. Peshkov_

'''

[[bug-304-utilities-nbackup]]
==== nBackup

_(http://tracker.firebirdsql.org/browse/CORE-5886[CORE-5886])_
-- _nbackup_ would stop working after 32K iterations of backups.

_fixed by A. Peshkov_

'''

[[bug-303]]
== Firebird 3.0.3 Release: Bug Fixes


The following bug fixes were reported prior to the version 3.0.3 official release:

[[bug-303-core]]
=== Core Engine

[[bug-303-core-crypt-vuln]]
_(http://tracker.firebirdsql.org/browse/CORE-5735[CORE-5735])_
-- An additional keyholder could open unauthorized connections to an encrypted database, creating a vulnerability.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5720[CORE-5720])_
-- Sweep in Classic mode could run too slowly when there was a big load on the server.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5713[CORE-5713])_
-- A field alias could disappear in a complex query

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5695[CORE-5695])_
-- The function `POSITION` did not consider the collation for BLOBs.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5694[CORE-5694])_
-- Duplicate values could occur in columns with the `UNIQUE` constraint.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5684[CORE-5684])_
-- Error "`no current record for fetch operation`" was raised while deleting a record from `MON$ATTACHMENTS` using `ORDER BY` clause

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5681[CORE-5681])_
-- An access violation could occur when an external statement was executed and the local transaction was rolled back.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5675[CORE-5675])_
-- `isc_vax_integer()` and `isc_portable_integer()` did not work properly with short negative numbers.

_fixed by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5673[CORE-5673])_
-- Unique constraint would not work in an encrypted database on first command.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5667[CORE-5667])_
-- Message "`CTE 'X' has cyclic dependencies`" would appear when '```X```' was the alias for a result set and there was a previous CTE part in the query with the same name '```X```'.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5659[CORE-5659])_
-- The optimizer was generating a bad plan under certain conditions.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5655[CORE-5655])_
-- `isc_info_sql_relation_alias` was reporting incorrect aliases for CTE or nested queries.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5645[CORE-5645])_
-- A wrong transaction could be passed to the external engine.

_fixed by A. dos Santos Fernades_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5643[CORE-5643])_
-- Message "`Operating system call munmap failed. Error code 12`" could appear in `firebird.log` under heavy load in Classic or Superclassic.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5638[CORE-5638])_
-- Wrong result with index on case-insensitive collation using `NUMERIC-SORT`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5618[CORE-5618])_
-- Some portions of the pages of second-level blobs were not released when dropping relations.

_fixed by D. Logashov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5605[CORE-5605])_
-- When running with a plug-in to access a version 2.5 database, the engine would incorrectly check for existing `MAP` if a pre-FB3 security database was used.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5600[CORE-5600])_
-- An invalid blob id would be reported when adding a new blob column of type text and updating another field in the same operation.

_fixed by V.Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5598[CORE-5598])_
-- Error "`Block size exceeds implementation restriction`" could occur while inner joining large datasets with a long key using the HASH JOIN plan.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5588[CORE-5588])_
-- `DbInfo` interface was not being passed to ancillary instances of a plug-in.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5580[CORE-5580])_
-- Signatures of packaged functions were not being checked for mismatch with the `[NOT] DETERMINISTIC` attribute.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5576[CORE-5576])_
-- Queries containing a `WITH LOCK` clause could trigger a bugcheck.

_fixed by R. Simakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5567[CORE-5567])_
-- Direct system table modifications were not completely prohibited.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5555[CORE-5555])_
-- Error handling for `SELECT WITH LOCK` broke compatibility with Firebird 2.5.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5553[CORE-5553])_
-- A database could not be encrypted if the `DatabaseAccess` was set to `None`.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5550[CORE-5550])_
-- A computed decimal field in a view could be stored with the wrong `RDB$FIELD_PRECISION` value.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5549[CORE-5549])_
-- Errors could occur when building or running Firebird on hardware that did not have SSE enabled.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5542[CORE-5542])_
-- Database-level triggers related to `TRANSACTION` events (start/commit/rollback) were not taking their `POSITION` index into account.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5535[CORE-5535])_
-- The value of `RDB$FIELD_SUB_TYPE` in `RDB$FUNCTION_ARGUMENTS` would be garbage after altering the function.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5528[CORE-5528])_
-- Internal Firebird consistency check (limbo impossible (184), file: vio.cpp line: 2379)

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5527[CORE-5527])_
-- External routines were not receiving default values for their output parameters.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5526[CORE-5526])_
-- External routines could receive parameters with incorrect length or data type.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5517[CORE-5517])_
-- Classic server could raise the error "`Global mapping memory overflow`" periodically and require restarting to accept new connections.

_fixed by A. Peshknov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5416[CORE-5416])_
-- Memory leak: Firebird did not release memory after load tests.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5415[CORE-5415])_
-- Found and fixed an elusive bug whereby an unexpected memory overwrite could cause the in-memory image of a random database page to be corrupted.

_fixed by V. Khorsun, with testing assistance from D. Kovalenko_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4492[CORE-4492])_
-- With `OR` or `IN` predicates for `RDB$DBKEY`, the optimizer failed to use an INDEX plan when it should have.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2853[CORE-2853])_
-- Bugcheck: page N, page type 5 lock conversion denied (215).

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2731[CORE-2731])_
-- Recursive `EXECUTE STATEMENT` was not working properly.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2502[CORE-2502])_
-- Cyclic dependency errors in CTE, involving aliases.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2284[CORE-2284])_
-- Records were left in `RDB$PAGES` after rollback of `CREATE TABLE` statement.

_fixed by R. Simakov & D. Yemanov_

'''

[[bug-303-crashes]]
=== Server Crashes/Hang-ups

_(http://tracker.firebirdsql.org/browse/CORE-5730[CORE-5730])_
-- The connection to the server could hang when working with encrypted databases over network protocol other than TCP.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5719[CORE-5719])_
-- Firebird 3 engine could crash when restoring from a backup made by Firebird 2.5.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5707[CORE-5707])_
-- Begin and end of physical backup in the same transaction could crash the engine.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5706[CORE-5706])_
-- Trace config with misplaced '```{```' could lead to an engine crash.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5591[CORE-5591])_
-- The engine could hang during transaction start, soon after certain errors.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5562[CORE-5562])_
-- Firebird could crash when a UDF was loaded and unloaded frequently.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5547[CORE-5547])_
-- The server could crash while compiling a stored procedure with nested references to query-based computed fields.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5533[CORE-5533])_
-- The engine could crash when a database contained a database-level trigger.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5516[CORE-5516])_
-- Firebird service could crash when stopping.

_fixed by V. Khorsun_

'''

[[bug-303-builds]]
=== Builds

_(http://tracker.firebirdsql.org/browse/CORE-5654[CORE-5654])_
-- Intermediate build files for plugins examples were mixed up.

_fixed by A. Peshkov_

'''

[[bug-303-api]]
=== API/Remote Interface

_(http://tracker.firebirdsql.org/browse/CORE-5721[CORE-5721])_
-- Information items `isc_info_length` and `fb_info_crypt_state` had the same code. 

[IMPORTANT]
====
Software using the `fb_info_crypt_state` constant should be recompiled to make it work with version 3.0.3 and later.
====

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5686[CORE-5686])_
-- Firebird 3.0.2 would allow any protocol version >= 10 to connect, including InterBase protocol 14

_fixed by M. Rotteveel_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5649[CORE-5649])_
-- `isc_add_user` / `isc_modify_user` could produce an unusable user record.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5521[CORE-5521])_
-- A race condition could arise between event notification and event registration.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5510[CORE-5510])_
-- The engine could send a status vector with more than 20 items to old clients and cause a disconnection.

_fixed by R. Simakov_

'''

[[bug-303-posixonly]]
=== POSIX Only

_(http://tracker.firebirdsql.org/browse/CORE-5650[CORE-5650])_
-- Dropping a procedure on the Classic server could cause a segmentation fault.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5624[CORE-5624])_
-- An old bug was fixed, whereby backslashes in path strings for use on POSIX file systems were not always converted to forward slashes.

_fixed by A. Peshkov_

'''

[[bug-303-utilities]]
=== Utilities

[[bug-303-utilities-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-5653[CORE-5653])_
-- _gbak_ restore with a large number of small blobs was very slow using Linux Classic.

_fixed by R. Simakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5630[CORE-5630])_
-- During restore, the shadow file could not be created.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5579[CORE-5579])_
-- A request synchronization error could occur in _gbak_ during a restore.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5566[CORE-5566])_
-- The server could crash while restoring from a backup if the shadow file already existed.

_fixed by D. Yemanov_

'''

[[bug-303-utilities-isql]]
==== isql

_(http://tracker.firebirdsql.org/browse/CORE-5569[CORE-5569])_
-- _isql_ would incorrectly pad `UNICODE_FSS`/`UTF8` columns when they used a collation.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5570[CORE-5570])_
-- Negative infinity (double) was being shown incorrectly without the sign in _isql_.

_fixed by A. dos Santos Fernandes_

'''

[[bug-303-utilities-nbackup]]
==== nBackup

_(http://tracker.firebirdsql.org/browse/CORE-5613[CORE-5613])_
-- Superserver could hang when changing physical backup state under high load

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5540[CORE-5540])_
-- Alternate executions of an _isql_ command from the command line in embedded mode would be 5 to 10 times slower, i.e. fast-slow-fast-slow...

_fixed by V. Khorsun_

'''

[[bug-303-utilities-users]]
==== User Management

_(http://tracker.firebirdsql.org/browse/CORE-5651[CORE-5651])_
-- Problem migrating users to version 3.0.

_fixed by A. Peshkov_

'''

[[bug-302]]
== Firebird 3.0.2 Release: Bug Fixes

The following bug fixes were reported prior to the version 3.0.2 official release:

[[bug-302-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-5501[CORE-5501])_
-- Diagnostics form _gstat_ were unclear when a damaged page in DB file appeared encrypted.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5498[CORE-5498])_
-- It was not possible to create a connection for events processing.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5496[CORE-5496])_
-- Creating SRP SYSDBA with explicit admin (`-admin yes` in gsec or `grant admin role` in `create user`) was creating two SYSDBA accounts.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5489[CORE-5489])_
-- Performance for ``NULL``s filtering inside a navigational index scan was poor.

_fixed by D. Yemanov_

'''

[[bug-vuln-5474]]
_(http://tracker.firebirdsql.org/browse/CORE-5474[CORE-5474])_
-- The setting "```Restrict UDF```" for configuration parameter `UdfAccess` was ineffective because of `fbudf.so` being dynamically linked against `libc`.

_fixed by A. Peshkov, A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5472[CORE-5472])_
-- Problems with dbcrypt key transfer.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5470[CORE-5470])_
-- Trace `INCLUDE_FILTER` with `\[[:WHITESPACE:]]+` would not work when a statement was issued that contained a newline character.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5464[CORE-5464])_
-- An access violation would occur in fbclient when reading a BLOB stored in incompatible encoding.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5457[CORE-5457])_
-- Bugcheck 167 (invalid SEND request).

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5456[CORE-5456])_
-- When attempting to migrate a database from Firebird 2.5.2 to 3.0.1, _gbak_ restore would always crash at the end.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5452[CORE-5452])_
-- A segmentation fault would occur when the engine's dynamic library was unloaded right after closing worker threads (GC and/or cache writer).

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5448[CORE-5448])_
-- Bugcheck oocurred when creating a view on a table that has a column with character set `NONE`, database default charset is `UTF8`, and the default collation is `UNICODE`.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5447[CORE-5447])_
-- `EXECUTE STATEMENT <e>` when `<e>` starts with '```--```' (comment) issues "`Unexpected end of command`" error with a wrong column number.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5432[CORE-5432])_
-- Classic Server suffered a performance regression: too much time was being spent during context switches.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5422[CORE-5422])_
-- The error "`Decompression overran buffer`" could occur after rollback.
It affected all platforms but would appear particularly on Windows Superserver, when `GCPolicy` was set to `Combined` or `Cooperative` and `CpuAffinityMask` was configured to more than a single core.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5421[CORE-5421])_
-- Performance degradation in FB 3.0.2 compared to FB 2.5.7.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5414[CORE-5414])_
-- Error restoring on FB 3.0 from FB 2.5 backup: bugcheck 221 (cannot remap).

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5410[CORE-5410])_
-- Dependencies were not stored when certain types of construction were used in subroutines.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5393[CORE-5393])_
-- Optimization was poor for some operations with views containing subqueries.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5392[CORE-5392])_
-- BUGCHECK 179 (decompression overran buffer) or an unexpected lock conflict could happen during back-out of record versions.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5390[CORE-5390])_
-- _isql_ would crash with corrupt memory when statement length exceeded 10 MB.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5384[CORE-5384])_
-- Plug-in manager was failing to provide the appropriate config information when the name of the configuration file was set in `plugins.conf`.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5383[CORE-5383])_
-- Dependencies in PSQL packages were not being recognised.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5382[CORE-5382])_
-- An SQL statement longer than 10MB could be processed (truncated) incorrectly.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5381[CORE-5381])_
-- Regression: A (select from view with nested view) query could not be executed.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5368[CORE-5368])_
-- Regression: a client application could hang or throw an access violation on selecting from multiple threads using one embedded connection.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5367[CORE-5367])_
-- Regression: A `BOOLEAN` state as a parameter for a search condition was incorrectly rejected as invalid.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5366[CORE-5366])_
-- Regression: A `CASE` expression with more than 255 conditions was being rejected.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5350[CORE-5350])_
-- An assertion was exhibited on Windows in `CachedMasterInterface::set`.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5314[CORE-5314])_
-- UDFs declared with large varchars were taking excessive time to execute.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3530[CORE-3530])_
-- `BETWEEN` operand/clause was not supported for `COMPUTED BY` columns -- "`feature is not supported`".
Now it is.

_fixed by D. Yemanov_

'''

[[bug-302-crashes]]
=== Server Crashes/Hang-ups

_(http://tracker.firebirdsql.org/browse/CORE-5428[CORE-5428])_
-- An old bug could occasionally cause a segmentation fault in Classic when the structure of a table with triggers was modified (DDL) while another attachment was preparing a request to work with that table.
In rare cases, pointers to the old triggers were cached by the request compiler, and the fault would occur the next time they were used.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5425[CORE-5425])_
-- A load test was hanging the server.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5417[CORE-5417])_
-- The engine could hang if an automatic sweep was starting during a database shutdown.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-1894[CORE-1894])_
--  (Old bug) Circular dependencies between computed fields would crash the engine.

_fixed by A. dos Santos Fernandes_

'''

[[bug-302-builds]]
=== Builds

_(http://tracker.firebirdsql.org/browse/CORE-5120[CORE-5120])_
-- Issues with the function `snprintf` (in `autoconfing_msvc.h`) and user-defined literals in VS 2015 (MSVC 14).

_fixed by V. Khorsun_

'''

[[bug-302-api]]
=== API

_(http://tracker.firebirdsql.org/browse/CORE-5359[CORE-5359])_
-- New API - ``MessageMetadata``'s `getScale()` was returning `INTEGER`, while MetadataBuilder's `setScale()` expected unsigned.

_fixed by A. Peshkov_

'''

[[bug-302-posixonly]]
=== POSIX Only

_(http://tracker.firebirdsql.org/browse/CORE-5503[CORE-5503])_
-- Classic Server was limited to 64 connections when using _systemd_ init scripts

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5484[CORE-5484])_
-- A database on an NFS share was unavailable when accessed using the mount point path.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5458[CORE-5458])_
-- Connections were failing due to dead NFS mount points.

_fixed by A. Peshkov_

'''

[[bug-302-winonly]]
=== Windows Only

_(http://tracker.firebirdsql.org/browse/CORE-5477[CORE-5477])_
-- Trace was duplicating `ascii_char(13)` in its output on Windows.

_fixed by V. Khorsun_

'''

[[bug-301]]
== Firebird 3.0.1 Release: Bug Fixes

The following bug fixes were reported prior to the version 3.0.1 official release:

[[bug-301-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-5355[CORE-5355])_
-- `XpbBuilder` was failing to create a new TPB.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5351[CORE-5351])_
-- `LEFT JOIN` would incorrectly push a UDF into the inner stream, causing wrong results.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5341[CORE-5341])_
-- A user-defined collation failed to work with BLOBs.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5339[CORE-5339])_
-- An assertion could occur in `createDatabase()` when doing the overwrite check.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5337[CORE-5337])_
-- A subquery in the insert list expression was ignoring changes made earlier in the same executable block.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5329[CORE-5329])_
-- A database could suffer partial corruption in the "`use all space`" (no-reserve) mode.

_fixed by V. Khorsun & D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5327[CORE-5327])_
-- BUGCHECK 165 (cannot find tip page)

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5322[CORE-5322])_
-- Cascade deletion in a self-referencing table could raise the error "`no current record for fetch operation`".

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5313[CORE-5313])_
-- A "`Data type unknown`" error was occurring with the `LIST` operation.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5307[CORE-5307])_
-- Random "`invalid transaction handle`" errors were being returned from the engine.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5305[CORE-5305])_
-- `ON UPDATE CASCADE` was failing for a self-referencing Foreign Key.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5302[CORE-5302])_
-- REGRESSION: Performance was degraded when bulk inserting into a table with indices.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5292[CORE-5292])_
-- Trying to encrypt a database in the absence of the appropriate key could corrupt it.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5289[CORE-5289])_
-- A small memory leak could occur when an empty result set was returned.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5279[CORE-5279])_
-- Granting of privileges to views was broken.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5277[CORE-5277])_
-- Parameters with multi-byte character sets were being allowed to exceed the length limit for `VARCHAR` fields.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5275[CORE-5275])_
-- Expression index could become inconsistent if `CREATE INDEX` was interrupted after b-tree creation but before committing.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5268[CORE-5268])_
-- Nested `OR` conditions could lead to incorrect results.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5248[CORE-5248])_
-- Consistency between roles and privileges in `GRANT` syntax needed improving in accordance with the SQL standard.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5244[CORE-5244])_
-- An attempt to execute a `SELECT` statement using `isc_dsql_execute_immediate()` would produce the wrong error message.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5241[CORE-5241])_
-- Affected rows were not being counted for some update operations with views.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5236[CORE-5236])_
-- `IN`/`ANY`/`ALL` predicates could cause sub-optimal execution (late filtering) of joins.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5233[CORE-5233])_
-- Unaligned memory access `in MET_format()` would cause segfault on big-endian machines.

_fixed by James Clarke_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5232[CORE-5232])_
-- 32-bit locks on big-endian systems would lead to deadlock.

_fixed by James Clarke_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5231[CORE-5231])_
-- `EXECUTE STATEMENT` would throw a BLR error if the number of output parameters exceeded 256.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5226[CORE-5226])_
-- An incorrect result set (missing records) could be returned by an ORDER plan query navigating on a descending index.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5225[CORE-5225])_
-- Authentication was ending with first plug-in that had the user but would fail there, instead of continuing with the next plug-in.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5222[CORE-5222])_
-- `SELECT WITH LOCK` could raise unexpected update conflict errors under concurrent load.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5213[CORE-5213])_
-- A database could get decrypted after changing a couple of bytes in the database header without 'agreement' from the crypt plug-in.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5210[CORE-5210])_
-- `POST_EVENT` was not working with the Fb 3.0 server and client.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5193[CORE-5193])_
-- The operator `IS` exhibited a precedence problem.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5183[CORE-5183])_
-- REGRESSION: line/column numbering in error messages were being garbled if `alias.name` syntax was used in the offending statement.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5142[CORE-5142])_
-- The error "`no current record to fetch`" was thrown if some record was to be deleted both by the statement itself and by some trigger fired during statement execution.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-1746[CORE-1746])_
-- An expression index could be created while inserts into the table were in progress.

_fixed by V. Khorsun_

'''

[[bug-301-crashes]]
=== Server Crashes

_(http://tracker.firebirdsql.org/browse/CORE-5234[CORE-5234])_
-- Access violation from certain UDFs would cause the server to crash.

_fixed by V. Khorsun_

'''

[[bug-301-api]]
=== API/Remote Interface

_(http://tracker.firebirdsql.org/browse/CORE-5347[CORE-5347])_
-- Race conditions could arise when initializing wire compression.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5296[CORE-5296])_
-- A network protocol error was exhibited when performing a callback to a client for the database crypt key.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5278[CORE-5278])_
-- Some SPB parameters were failing in FB 3.0.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5224[CORE-5224])_
-- Transaction id tags for the Services API did not support new 48-bit transaction ids.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5154[CORE-5154])_
-- The Services API would not work with non-ASCII database names.

_fixed by D. Sibiryakov_

'''

[[bug-301-utilities]]
=== Utilities

[[bug-301-utilities-svcmgr]]
==== fbsvcmgr

_(http://tracker.firebirdsql.org/browse/CORE-5270[CORE-5270])_
-- _fbsvcmgr_ was not producing any error when it attempted to shut down a database without a specified timeout (`prp_force_shutdown N`).

_fixed by A. Peshkov_

'''

[[bug-301-utilities-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-5228[CORE-5228])_
-- Restore could hang if the database contained more than 4 billion records.

_fixed by D. Yemanov_

'''

[[bug-301-utilities-gfix]]
==== gfix

_(http://tracker.firebirdsql.org/browse/CORE-5295[CORE-5295])_
-- Validation could read after the end-of-file when operating on a multi-file database.

_fixed by V. Khorsun_

'''

[[bug-301-utilities-isql]]
==== isql

_(http://tracker.firebirdsql.org/browse/CORE-5308[CORE-5308])_
-- The `BLOBVIEW` command was causing _isql_ to hang.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5294[CORE-5294])_
-- _isql_ would leak memory when `SHOW GRANTS` was used on a new, empty database.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5220[CORE-5220])_
-- `isql -[e]X[tract_metadata]` output was omitting double quotes for the `COLLATE <collation>` clause of a `CREATE DOMAIN` statement when `<collation>` was for any non-ascii character set.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5218[CORE-5218])_
-- `isql -[e]X[tract_metadata]` was not exporting explicitly defined names for `NOT NULL` constraints for Dialect 3 databases.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5217[CORE-5217])_
-- `isql -[e]X[tract_metadata]` could crash while exporting an exception with message text length longer than 127 bytes.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5207[CORE-5207])_
-- `isql -[e]X[tract_metadata]` could generate invalid `GRANT USAGE` statements for domains.

_fixed by D. Yemanov_

'''

[[bug-301-utilities-mon]]
==== Monitoring and Trace

_(http://tracker.firebirdsql.org/browse/CORE-5246[CORE-5246])_
-- A string truncation error would occur while selecting from the `MON$` tables if some user-defined context variable was longer than 255 bytes.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5203[CORE-5203])_
-- A trace session could fully utilize a single CPU core.

_fixed by A. Peshkov_

'''

[[bug-301-utilities-nbackup]]
==== nBackup

_(http://tracker.firebirdsql.org/browse/CORE-5264[CORE-5264])_
-- A database located on a raw device could not be unlocked from an __nBackup__-locked state.

_fixed by A. Peshkov_

'''

[[bug-301-builds]]
=== Builds

_(http://tracker.firebirdsql.org/browse/CORE-5348[CORE-5348])_
-- Databases created during the process of the Windows builds were owned by a Windows administrator, not SYSDBA.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5284[CORE-5284])_
-- Firebird failed to build with `USE_VALGRIND`

_fixed by A. Peshkov_

'''

[[bug-301-posx-specific]]
=== POSIX-Specific

_(http://tracker.firebirdsql.org/browse/CORE-5335[CORE-5335])_
-- A segfault could occur when `op_que_events` was used on a port that was not prepared for events processing.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5285[CORE-5285])_
-- A segfault could occur if an attachment was closed while requests were still open.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5249[CORE-5249])_
-- Incorrect use of the system call `readlink()`.

_fixed by A. Peshkov_

'''

[[bug-300final]]
== Firebird 3.0.0 Release: Bug Fixes

The following bug fixes were reported prior to the version 3.0.0 official release:

[[bug-300final-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-5184[CORE-5184])_
-- An assertion would occur in the `cloop` dispatcher when trying to save exception information in the status interface.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5182[CORE-5182])_
-- Failure to find a record on re-fetch would produce inconsistent effects on subsequent statement execution.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5166[CORE-5166])_
-- Unique key violation on a `BOOLEAN` column was returning an erroneous message.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5165[CORE-5165])_
-- `HAVING COUNT({asterisk}) NOT IN ( <Q> )` would erroneously exclude a record from the outer result set.
(`<Q>` represents a result set without nulls)

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5161[CORE-5161])_
-- It was possible to create a unique index on non-unique data.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5159[CORE-5159])_
-- Regression: the engine could throw transliteration errors when running from a non-ASCII system path.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5157[CORE-5157])_
-- The server could go into an infinite loop when data was being sent from a client to the server in small packets.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5149[CORE-5149])_
-- Regression: `LEFT JOIN` was incorrectly pushing `COALESCE` into the inner stream, causing wrong results.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5147[CORE-5147])_
-- `CREATE TRIGGER` was failing with the error "`Ambiguous field name between table B and table A`".

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5146[CORE-5146])_
-- Join order was sub-optimal if one table had a selective predicate and `MIN` was calculated for the other one.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5144[CORE-5144])_
-- Deadlock could occur when a database was being encrypted or decrypted under high parallel load.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5133[CORE-5133])_
-- `ALTER SEQUENCE RESTART WITH` was failing to change the initial value.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5130[CORE-5130])_
-- Minor regression: wrong error message was being returned on an attempt to compile a view with both a subquery and the `WITH CHECK OPTION` clause in its definition -- an illegal combination.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5122[CORE-5122])_
-- The optimizer could avoid using an expression index if the query was running in a different connection character set to the one that was in effect when the index was created.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4645[CORE-4645])_
-- Internal Firebird consistency check (cannot find tip page (165), file: tra.cpp line: 2375) would occur if too many transactions were created for one connection to a read-only database.
This was a very old bug, dating back to InterBase 6.

_fixed by V. Khorsun_

'''

[[bug-final-crashes]]
=== Server Crashes

_(http://tracker.firebirdsql.org/browse/CORE-5153[CORE-5153])_
-- Regression: The server would crash when aggregate functions were used together with the `NOT IN` predicate.

_fixed by A. dos Santos Fernandes_

'''

[[bug-final-utilities]]
=== Utilities

[[bug-final-utilities-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-5143[CORE-5143])_
-- _gbak_ restore could fail when there was some SQL function accessing a table while the switch `-O(NE_AT_A_TIME)` was in use.

_fixed by D. Yemanov_

'''

[[bug-final-utilities-gfix]]
==== gfix

_(http://tracker.firebirdsql.org/browse/CORE-5140[CORE-5140])_
-- An attempt to set the number of page buffers to a non-supported value would return the wrong error message.

_fixed by V. Khorsun_

'''

[[bug-final-utilities-isql]]
==== isql

_(http://tracker.firebirdsql.org/browse/CORE-5194[CORE-5194])_
-- An invalid `COMPUTED BY` definition was being generated by the 'extract metadata' operation.

_fixed by A. dos Santos Fernandes_

'''

[[bug-final-utilities-mon]]
==== Monitoring

_(http://tracker.firebirdsql.org/browse/CORE-5179[CORE-5179])_
-- Database-level statistics (`MON$STAT_GROUP` = 0) could contain multiple rows under concurrent load.

_fixed by D. Yemanov_

'''

[[bug-final-utilities-userman]]
==== User Management

_(http://tracker.firebirdsql.org/browse/CORE-5189[CORE-5189])_
-- The codes of operation for user management plug-ins were missing from the public API.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5162[CORE-5162])_
-- Users with the same name can co-exist in the security database if they are created by different plug-ins.
However, tags or attributes for a user created using one plug-in were being displayed in the `SEC$` virtual tables for the same-name user created by the other plug-in.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5155[CORE-5155])_
-- `[CREATE OR] ALTER USER` statement would fail if the `PASSWORD` parameter was present and was not specified immediately after the `USER` parameter.

_fixed by A. Peshkov_

'''

[[bug-final-builds]]
=== Builds

_(http://tracker.firebirdsql.org/browse/CORE-5181[CORE-5181])_
-- The build would fail if `HAVE_MMAP` was not defined.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5180[CORE-5180])_
-- Root rights were unnecessarily required to build a Linux package.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5134[CORE-5134])_
-- The samples of dbcrypt-related plug-ins contained references to internal files.

_fixed by A. Peshkov_

'''

[[bug-300rc2]]
== Firebird 3.0 Release Candidate 2: Bug Fixes and Minor Improvements

The following tweaks and bug fixes were reported prior to version 3.0.0 release candidate 2:

[float]
=== Minor Improvements

_(http://tracker.firebirdsql.org/browse/CORE-4996[CORE-4996])_
-- NEW: SECURITY2.FDB -> SECURITY3.FDB upgrade feature

_Implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-1538[CORE-1538])_
-- NEW: An option was added to the API function `isc_database_info()` to return the number of free pages in a database.

_Implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5112[CORE-5112])_
-- IMPROVEMENT: The error messages for a malformed SQDLA were improved.

_Implemented by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5100[CORE-5100])_
-- IMPROVEMENT: Improved control over database crypt keys, see <<rnfb30-security-encryption-tasks,Encryption Tasks>>.

_Implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5083[CORE-5083])_
-- IMPROVEMENT: A method was provided to set the correct offsets in user-implemented `IMessageMetadata`.

_Implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5077[CORE-5077])_
-- IMPROVEMENT: In _isql_, `SHOW DATABASE` includes the encryption status of the database, as does `gstat -h[eader]`.

_Implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5063[CORE-5063])_
-- IMPROVEMENT: In _isql_, `SHOW DATABASE` includes the numbers of used and free pages in the database.

_Implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5028[CORE-5028])_
-- IMPROVEMENT: The remote port number was added to the monitoring table `MON$ATTACHMENTS`.

_Implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4978[CORE-4978])_
-- IMPROVEMENT: Validation and repair of lost data pages have been improved.

_Implemented by R. Simakov, V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2493[CORE-2493])_
-- IMPROVEMENT: The IP address of the remote host is now appended to error messages in `firebird.log` for TCP connections.

_Implemented by V. Khorsun_

'''

[float]
=== Bugs

[[bug-300rc2-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-5110[CORE-5110])_
-- A false primary or foreign key violation could be reported when an attachment used the `isc_dpb_no_garbage_collect` flag.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5104[CORE-5104])_
-- ``SELECT``s from an external data source would become slow.

_fixed by V. Khorsun, A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5097[CORE-5097])_
-- `COMPUTED BY` expressions were not being converted to their data type inside the engine.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5093[CORE-5093])_
-- `ALTER COLUMN` was not changing the type of a computed column where it should.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5082[CORE-5082])_
-- The server was not validating the correctness of the user/password pair provided in the `EXECUTE STATEMENT` operation.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5078[CORE-5078])_
-- The "`Invalid BLOB ID`" error was being thrown unexpectedly after a large `VARCHAR` column was changed to text `BLOB`.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5075[CORE-5075])_
-- `ON DISCONNECT` trigger with `EXECUTE STATEMENT` was not working and would lead to a server crash when it was recreated.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5062[CORE-5062])_
-- Function `CHAR_TO_UUID` on an indexed column would throw the error "`expression evaluation not supported`".

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5060[CORE-5060])_
-- `CREATE VIEW` that selected from a system table would fail, despite all grants being available.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5056[CORE-5056])_
-- The write lock on the database file was being cleared when retrieving the database statistics via the Services API.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5049[CORE-5049])_
-- Byte-length for view columns was being calculated incorrectly.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5047[CORE-5047])_
-- `mapUser()` routine would establish a secondary attachment using the wrong provider.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5039[CORE-5039])_
-- Connecting to a service with an invalid service name would yield an incorrect error message.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5034[CORE-5034])_
-- A delay of at least 5 seconds could occur on disconnect if the disconnect followed closely on an Event Manager initialization.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5033[CORE-5033])_
-- The file `fb_user_mapping` could be left behind in the Firebird lock directory after a correct shutdown of all Firebird worker processes.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5032[CORE-5032])_
-- Connection to a database with its own security database was not possible in the absence of `security3.fdb`.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5026[CORE-5026])_
-- Firebird authentication would give up after failing to establish authentication via the first common plugin.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5020[CORE-5020])_
-- An `ORDER BY` clause on the key columns of a compound index could disable usage of other indices.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5018[CORE-5018])_
-- Non-indexed predicates might not have been applied immediately after retrieval when tables were being joined.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5017[CORE-5017])_
-- Interrupt of aux connection during TCP setup phase would cause a server exit due to an unhandled exception.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5014[CORE-5014])_
-- Interrupt of aux connection during TCP setup phase was producing unclear error messages in `firebird.log`.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4997[CORE-4997])_
-- Races would occur when two threads tried simultaneously to establish the first embedded connection to the engine.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4991[CORE-4991])_
-- The Keyholder plug-in was being loaded on connection to a database but not on creating a database.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4980[CORE-4980])_
-- The `REVOKE` operator could modify the privileges granted to system tables at database creation time.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4969[CORE-4969])_
-- The `SEC$USERS` table became unavailable when an error occurred in any configured UserManager plug-in.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4964[CORE-4964])_
-- Real errors during connection to a security database were being hidden by the Srp user manager.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4885[CORE-4885])_
-- Retrieving the current user name when using Windows trusted authentication and an OS user name containing non-ASCII characters would cause an error.

_fixed by A. Peshkov, D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4840[CORE-4840])_
-- Transactions with `isc_tpb_autocommit` could hang the server.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2923[CORE-2923])_
-- Dependencies with views were exhibiting a problem.

_fixed by A. dos Santos Fernandes_

'''

[[bug-300rc2-crashes]]
=== Server Crashes

_(http://tracker.firebirdsql.org/browse/CORE-5107[CORE-5107])_
-- `SET AUTODDL OFF` and sequence of `CREATE` + `ALTER` + `DROP VIEW` would lead to a server crash.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5087[CORE-5087])_
-- A database shutdown could cause a server crash if multiple attachments were running `EXECUTE STATEMENT`.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5016[CORE-5016])_
-- The server could crash during garbage collection when a `DELETE` is executed after adding a new referencing column.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5015[CORE-5015])_
-- The server could crash when an event was posted from an `ON DISCONNECT` trigger.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4982[CORE-4982])_
-- The server could crash during a select from a procedure if an exception was thrown while backing out the current savepoint.

_fixed by D. Yemanov_

'''

[[bug-300rc2-dbencryption]]
=== Database Encryption

_(http://tracker.firebirdsql.org/browse/CORE-5105[CORE-5105])_
-- Deadlocks could occur when a database was initially encrypted.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5044[CORE-5044])_
-- Pages were being encrypted for each shadow separately.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5041[CORE-5041])_
-- A database could be corrupted after `ALTER DATABASE ENCRYPT/DECRYPT` was issued multiple times per database open time.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4999[CORE-4999])_
-- Trying to access a database with an invalid crypt key would cause a deadlock.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4990[CORE-4990])_
-- Databases were not being decrypted completely.

_fixed by A. Peshkov_

'''

[[bug-300rc2-api]]
=== API/Remote Interface

_(http://tracker.firebirdsql.org/browse/CORE-5102[CORE-5102])_
-- `fbclient.dll` API calls were (wrongly) modifying the FPU control word.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5067[CORE-5067])_
-- New connections were being blocked as a consequence of sweeps of the security database taking too long.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5042[CORE-5042])_
-- The version 3 client could not create a database on a version 2.5 server.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5029[CORE-5029])_
-- A crash could occur in fbclient when a multi-threaded application was using the XNET protocol.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4998[CORE-4998])_
-- Neither client nor server could close the connection after failed authentication.

_fixed by V. Khorsun_

'''

[[bug-300rc2-utils]]
=== Utilities

[[bug-300rc2-utils-gbak]]
==== _gbak_

_(http://tracker.firebirdsql.org/browse/CORE-5101[CORE-5101])_
-- Restore was slow when the database contained many small tables with indices.

_fixed by V. Khorsun_

'''

[[bug-300rc2-utils-gstat]]
==== _gstat_

_(http://tracker.firebirdsql.org/browse/CORE-5088[CORE-5088])_
-- A segmentation fault could occur while `gstat -h` was closing.

_fixed by A. Peshkov_

'''

[[bug-300rc2-utils-isql]]
==== _isql_

_(http://tracker.firebirdsql.org/browse/CORE-5092[CORE-5092])_
-- The `EXTRACT` command would lose the data types of `COMPUTED BY` columns.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5089[CORE-5089])_
-- Metadata extraction (`isql -X`): A `CREATE PROCEDURE/FUNCTION` statement would retain the `TYPE OF` reference to a table column that no longer existed, if the procedure or function had a parameter of that type declared at the time it was created.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5061[CORE-5061])_
-- Plan output was being unexpectedly truncated after a query was simplified by shortening it.

_fixed by D. Yemanov_

'''

[[bug-300rc2-utils-mon]]
==== Monitoring

_(http://tracker.firebirdsql.org/browse/CORE-4708[CORE-4708])_
-- Content of `MON$EXPLAINED_PLAN` in `MON$STATEMENTS` was being truncated if it exceeded the 32KB limit.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4179[CORE-4179])_
-- The `MON$` tables became unavailable when there was intensive disk-bound load.

_fixed by D. Yemanov_

'''

[[bug-300rc2-installers]]
=== Builds and Installers

_(http://tracker.firebirdsql.org/browse/CORE-5053[CORE-5053])_
-- (POSIX): `changeServerMode.sh` could mess with configuration.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5002[CORE-5002])_
-- (WINDOWS): The Windows installer exhibited some character set confusion (ANSI vs. UTF8) in its GUI for non-English environments.

_fixed by P. Reeves_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4910[CORE-4910])_
-- (WINDOWS): The Windows build would fail if a path to source files contained spaces.

_fixed by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4862[CORE-4862])_
-- (WINDOWS): `ibase.h` from the x64 package included a nonexistent file.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4842[CORE-4842])_
-- (POSIX): the installer script would fail in some Linux environments.

_fixed by A. Peshkov, M. Masyk_

'''

[[bug-300rc1]]
== Firebird 3.0 Release Candidate 1: Bug Fixes and Minor Improvements

The following bug fixes and tweaks were reported prior to version 3.0.0 release candidate 1:

[float]
=== Minor Improvements

_(http://tracker.firebirdsql.org/browse/CORE-4911[CORE-4911])_
-- IMPROVEMENT: Most errors that occur in providers are fatal and it is pointless to try other providers in the hope another will succeed when that one failed.
As an example, if the remote redirector detects that the format of the database connection string matches a certain protocol, trying other providers will be futile if connection on that protocol failed.
Or, suppose the engine reports some internal database error (other than invalid ODS version), it will be no use trying to open the same database through the loopback provider.

A better option appeared to be to enumerate the codes for those errors after which it would make sense to try other providers -- primarily `isc_unavailable` and `isc_no_priv`.
Given the desirability of retaining the content of the status vector as-is, the solution was to add some more error codes.

_Implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4898[CORE-4898])_
-- IMPROVEMENT: Creation and loading of functions was slow when there were many functions in the database.
This process has been given a speed boost.

_Implemented by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4880[CORE-4880])_
-- IMPROVEMENT: Creating packages containing many functions was slow.
This process has been given a speed boost.

_Implemented by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4939[CORE-4939])_
-- IMPROVEMENT: I/O operations on the _nbackup_ backup file at are now aligned at the page size boundary

_Implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4936[CORE-4936])_
-- IMPROVEMENT: Internal contention in the background garbage collector has been reduced

_Implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4935[CORE-4935])_
-- IMPROVEMENT: Performance was improved on backing out a dead record version or undoing a newly created primary record version when the back-version chain gets too long

_Implemented by V. Khorsun_

'''

[float]
==== Bugs

[[bug-300rc1-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-4984[CORE-4984])_
-- Ordering by a compound index together with a range condition was giving wrong results

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4954[CORE-4954])_
-- Packaged procedure with a default input value would not be called if the default parameter was not specified

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4952[CORE-4952])_
-- SuperServer could hang on database shutdown

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4951[CORE-4951])_
-- The message "`Incorrect parameters provided to internal function INF_transaction_info Invalid token`" was reported when trying to commit a two-phase-commit transaction

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4950[CORE-4950])_
-- Statistics could not be recalculated or updated for any system index

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4947[CORE-4947])_
-- A compound `ALTER TABLE` statement that tried to `ADD` and `DROP` the same check constraint would fail

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4943[CORE-4943])_
-- Casting a Dialect 1 date to string would break when a domain with a check constraint was present

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4938[CORE-4938])_
-- Operations (get statistics, change forced wites, make backup) could not be completed on a database when working in embedded mode

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4929[CORE-4929])_
-- PSQL source with "```ELSE IF ( <expr> ) THEN```" block containing commands to manipulate an explicit cursor would not compile

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4921[CORE-4921])_
-- Predicate `IS [NOT] DISTINCT FROM` was not being pushed into unions/aggregates, resulting in sub-optimal plans

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4917[CORE-4917])_
-- `ALTER DOMAIN ... TO __new_name__` would allow the _new_name_ to be specified in the same pattern as domains generated by the system, i.e. matching to `'RDB$\[[:DIGIT:]]*'`

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4914[CORE-4914])_
-- Moving a database into the 'full shutdown' state could corrupt indexes on long-key text columns

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4909[CORE-4909])_
-- MERGE / HASH JOINs would produce incorrect results when `VARCHAR` join keys differed only by trailing spaces

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4906[CORE-4906])_
-- An access violation would occur if the server was shut down with active trace session(s)

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4904[CORE-4904])_
-- Index corruption could occur while inserting data into a long-key-indexed field

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4902[CORE-4902])_
-- Failure of assertion `(m_format->fmt_length == m_data.getCount())`

_fixed by D. Yemanov, V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4897[CORE-4897])_
-- The _fbsvcmgr_ could produce a broken log when restoring a database

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4890[CORE-4890])_
-- Placing a comment (single-lined or multi-lined) between the final `END` statement and the terminator character (e.g. `^`) in stored procedure code produced a compiling error if the utility tool used the legacy API

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4889[CORE-4889])_
-- Using _fbsvcmgr_ with `action_trace_start` under SuperSsrver would cause a livelock and prevent attachments using local protocol

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4887[CORE-4887])_
-- An `AFTER CREATE/ALTER PACKAGE` DDL trigger would run before inserts and updates of `RDB$PROCEDURES` and `RDB$FUNCTIONS`, whereas it should run after all changes to the system tables.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4884[CORE-4884])_
-- A script containing `EXECUTE BLOCK` with *multiple* nested `BEGIN...END` statements would cause a crash during parsing

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4872[CORE-4872])_
-- The version 3 fbclient could not work with servers older than version 2.5 via the remote protocol

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4861[CORE-4861])_
-- A segmentation fault could occur when working with a saved exception in a request

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4854[CORE-4854])_
-- The client library was handling non-UTF8 representation of international characters incorrectly in the SPB

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4848[CORE-4848])_
-- `MERGE ... WHEN NOT MATCHED ... RETURNING` was returning wrong (non-`NULL`) values when no insert was performed

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4846[CORE-4846])_
-- Altering a trigger to attempt to change the table to which it belongs did not succeed, but failed with bizarre results and an unhelpful error message

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4836[CORE-4836])_
-- `GRANT UPDATE(c) ON T TO U01 WITH GRANT OPTION`: user `U01` would be unable to revoke this privilege if some DML was executed before `REVOKE`

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4710[CORE-4710])_
-- "`Invalid request BLR at offset 361 context already in use (BLR error)`" was the wrong message for the error concerned, occurring only when the context count was near the 256 limit

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4680[CORE-4680])_
-- Deadlock could occur during attachment

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4585[CORE-4585])_
-- A column `CHECK` constraint could not be created if the column was based on a domain

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4497[CORE-4497])_
-- Regression: wrong handling in `FOR`-cursor when a "```NOT EXISTS( select from <`view`> )```" expression was used to check results obtained from a stored procedure

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4292[CORE-4292])_
-- The server would ignore asynchronous requests (monitoring or cancellation) while preparing a query with a lot of windowed functions

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4279[CORE-4279])_
-- Invalid error message: "`CHARACTER SET OCTETS is not defined`" when creating a database specifying `isc_dpb_lc_ctype = OCTETS`

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4277[CORE-4277])_
-- A database could be created with an invalid character set as its default

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4276[CORE-4276])_
-- `CREATE TABLE` would throw an error if a column was being defined with the character set DOS775

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4107[CORE-4107])_
-- (subquery + derived table + union) would produce a wrong result set

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3717[CORE-3717])_
-- Anomalies existed between the three  methods of user management, regarding valid user names and passwords

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3545[CORE-3545])_
-- Validation of domain constraints in PSQL was inconsistent

_fixed by A. dos Santos Fernandes_

'''

[[bug-300rc1-posx-specific]]
=== POSIX-Specific

_(http://tracker.firebirdsql.org/browse/CORE-4919[CORE-4919])_
-- On AIX and Solaris, all processes on a Classic server would hang after the death of one process

_fixed by A. Peshkov_

'''

[[bug-300rc1-win-specific]]
=== Windows-Specific

_(http://tracker.firebirdsql.org/browse/CORE-4859[CORE-4859])_
-- Embedded server could not work without the folder `C:\ProgramData\firebird`

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4860[CORE-4860])_
-- Online validation on Windows would fail if the `dbname` argument contained forward slash ('```/```') and a concurrent attachment existed that also used '```/```'

_fixed by V. Khorsun_

'''

[[bug-300rc1-servicesapi]]
=== Services API

_(http://tracker.firebirdsql.org/browse/CORE-4679[CORE-4879])_
-- When using the Services API to manage users (from _fbsvcmgr_ or by building a SPB in some program, for example) it was required -- but not documented -- to place the user name parameter immediately after the desired action (add/modify).
If any other parameter was placed before the user name, the Services Manager on the server would go crazy and build a wrong command line for the _gsec_ service.

_fixed by A. Peshkov_

'''

[[bug-300rc1-utils]]
=== Utilities

[[bug-300rc1-utils-fbsvcmgr]]
==== _fbsvcmgr_

_(http://tracker.firebirdsql.org/browse/CORE-4855[CORE-4855])_
-- Online validation during DML activity in another connection would lead to errors: "`Error while trying to read from file`" and "`Page in use during flush (210)`"

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4876[CORE-4876])_
-- A named trace session launched by _fbsvcmgr_ with a non-empty value for the parameter `trc_name` could not be stopped using its name

_fixed by V. Khorsun_

'''

[[bug-300rc1-utils-gbak]]
==== _gbak_

_(http://tracker.firebirdsql.org/browse/CORE-4928[CORE-4928])_
-- The connection information in an `ON CONNECT` trigger could not be saved if the connection was established by _gbak_

_fixed by A. dos Santos Fernandes_

'''

[[bug-300rc2-utils-gfix]]
==== _gfix_

_(http://tracker.firebirdsql.org/browse/CORE-4899[CORE-4899])_
-- Using `gfix -online` in Classic returned the message "`IProvider::attachDatabase failed when loading mapping cache`" if access was using a remote protocol

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4865[CORE-4865])_
-- Online validation could return a false report of double-allocated pages

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3548[CORE-3548])_
-- _gfix_ would return an error after correctly shutting down a database

_fixed by A. Peshkov_

'''

[[bug-300rc1-utils-isql]]
==== _isql_

_(http://tracker.firebirdsql.org/browse/CORE-4882[CORE-4882])_
-- The _isql_ `INPUT` command (or the  `-i` option at the command line) was reading large (> 64K) lines incorrectly

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4864[CORE-4864])_
-- `CREATE DATABASE` fails in _isql_

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4870[CORE-4870])_
-- In _isql_, `SET COUNT ON` reports the wrong number of affected rows when issuing `UPDATE` on a view which was created `WITH CHECK OPTION`

_fixed by A. dos Santos Fernandes_

'''

[[bug-300b2-beta02]]
== Firebird 3.0 Second Beta Release: Bug Fixes

The following bug fixes were reported prior to the version 3.0.0 Beta 2 release:

[[bug-300b2-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-4819[CORE-4819])_
-- failure of the engine to check the validity of `RETURNING_VALUES` for `EXECUTE PROCEDURE` and `INTO` for `EXECUTE STATEMENT` could lead to bugchecks.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4809[CORE-4809])_
-- HASH/MERGE JOIN was not used for more than two streams if they were joined via `USING`/`NATURAL` clauses and the join was based on DBKEY concatenations.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4806[CORE-4806])_
-- Regression: generators could be seen and modified by unprivileged users.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4798[CORE-4798])_
-- Regression: `MIN()` or `MAX()` with a join would ignore possible index navigation.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4789[CORE-4789])_
-- Timestamps that were out of valid range were not prevented from being cast to `VARCHAR` or `CHAR`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4786[CORE-4786])_
-- When an attempt was made to insert a duplicate value into a primary or unique key column, where the length of the key was 127 characters or more, the problematic key was not shown in the error message.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4781[CORE-4781])_
-- Maximum string length (32765 bytes) was not being validated by the parser.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4774[CORE-4774])_
-- Table aliasing was being required unnecessarily when doing `UPDATE ... RETURNING` with `RDB$` pseudo-columns.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4768[CORE-4768])_
-- `CREATE USER ... TAGS ( argument_1 = 'value1', ..., argument_N = 'valueN' )` would return wrong results from the statement when there were many arguments.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4767[CORE-4767])_
-- In `CREATE USER ... TAGS ( attr = 'prefix #suffix' )` the character "```#```" in the attribute value would cause the subsequent characters to be dropped from storage.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4760[CORE-4760])_
-- A user with non-ASCII (multi-byte) characters in the name could not be created.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4759[CORE-4759])_
-- A request synchronization error could occur when building an expression index.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4755[CORE-4755])_
-- A parameterized exception would produce wrong output when the number of arguments exceeded seven.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4754[CORE-4754])_
-- Manipulations with a GTT from several attachments (using `EXECUTE STATEMENT` with an `ON EXTERNAL` clause and different roles) could lead to the error "`Internal Firebird consistency check (invalid SEND request (167), file: JrdStatement.cpp line: 325)`".

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4753[CORE-4753])_
-- Firebird could hang in the embedded mode.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4752[CORE-4752])_
-- `EXECUTE STATEMENT` using BLOB parameters would result in an "`Invalid BLOB ID`" error.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4747[CORE-4747])_
-- The error "`Invalid BLOB ID`" could occur when retrieving `MON$STATEMENTS.MON$SQL_TEXT` using `EXECUTE STATEMENT` with an `ON EXTERNAL` clause with the `db_connect` argument unspecified.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4744[CORE-4744])_
-- The statement `ALTER DATABASE SET DEFAULT CHARACTER SET` exhibited two faults:
1) it would take effect only once for the current attachment;
2) it was not checking that the new character set existed until it was actually used.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4743[CORE-4743])_
-- A granted role would not work with a non-ASCII user name.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4740[CORE-4740])_
-- `SIMILAR TO` with quantifier `{n,}` in the pattern was failing in version 2.5 with the error "`Invalid pattern`" and was producing strange results in version 3.0.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4733[CORE-4733])_
-- The command `ALTER TABLE <T> ALTER TYPE <C> DOMAIN_WITH_NOT_NULL` was not verifying the data in column `<C>` and would make incorrect assignments in `<C>` to ZERO / JULIAN_DATE / ASCII(0) for types `INT`, `TIMESTAMP` and `VARCHAR`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4725[CORE-4725])_
-- Inconsistencies were exhibited with `ALTER DOMAIN` and `ALTER TABLE` involving `DROP NOT NULL` and ``PRIMARY KEY``s.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4719[CORE-4719])_
-- The message "`Statement failed, SQLSTATE = 00000 + unknown ISC error 0`" would appear when issuing `REVOKE ALL ON ALL FROM <existing_user>`.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4713[CORE-4713])_
-- A "`BLOB not found`" error would be thrown at rollback after inserting into a table with an expression index.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4712[CORE-4712])_
-- Messages stating "`Error in isc_release_request() ... when working with legacy security database`" were appearing in `firebird.log` for the Classic server when connecting with legacy authentication.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4702[CORE-4702])_
-- Join order was less optimal than in version 2.x.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4684[CORE-4684])_
-- An error was being thrown while preparing a complex query ("`Too many Contexts of Relation/Procedure/Views. Maximum allowed is 256`".)

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4675[CORE-4675])_
-- Conditions like `WHERE <field> = <cursor>.<field>` would not use an existing index.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4673[CORE-4673])_
-- A computed index based on a computed column would store `NULL` for all its keys.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4670[CORE-4670])_
-- Constraint violation errors could be swallowed in some cases.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4668[CORE-4668])_
-- `SELECT FROM MON$TABLE_STATS` did not work on Superclassic and Classic.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4665[CORE-4665])_
-- Search criteria would produce wrong results on `WHERE <field_C> STARTING WITH <:value> ORDER BY <field_N>` when `field_C` was the leading part of a compound index key consisting of `(field_C, field_N)`.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4659[CORE-4659])_
-- A bug was introduced when implementing support for multiple user managers, whereby the error "`Missing security context for .....\SECURITY3.FDB`" could appear when performing some operations where per-database security was configured.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4656[CORE-4656])_
-- The server could hang while chasing dead record versions.

_fixed by D. Starodubov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4655[CORE-4655])_
-- MSVC8 and MSVC9 builds of Beta 1 were failing.

_fixed by D. Starodubov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4648[CORE-4648])_
-- A user with the `RDB$ADMIN` role was denied the privilege for `CREATE DATABASE`.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4644[CORE-4644])_
-- Security context and open database errors could present under heavy concurrent load.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4634[CORE-4634])_
-- The error "`No current record for fetch operation`" could occur when the same indexed column was specified in both the `WHERE` and the `ORDER BY` clauses.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4631[CORE-4631])_
-- When the shared memory region backing the lock table could not be remapped, the status vector would return the error message "`Lock manager out of room`" without any low-level details (e.g. OS level error), thus hiding the real cause of the problem.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4624[CORE-4624])_
-- Firebird's handling of '```:```' characters in mount table entries was invalid.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4623[CORE-4623])_
-- PSQL variables based on "`Domain`" and "`Type Of`" referring to BLOB with sub_type < 0 were no longer working.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4622[CORE-4622])_
-- Triggers with the `UPDATE OR INSERT` statement and `IIF()` were not working as expected.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4618[CORE-4618])_
-- Rollback was failing to undo changes when a `MERGE` statement was updating the same target rows multiple times and the optimizer used PLAN MERGE.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4604[CORE-4604])_
-- `EXECUTE STATEMENT` was inflating the `CHAR_LENGTH()` size for ``VARCHAR``s.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4599[CORE-4599])_
-- The `REPLACE()` function was not working correctly with multi-byte character sets.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4583[CORE-4583])_
-- The embedded engine would try to load the ICU DLLs from `PATH` folders.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4582[CORE-4582])_
-- During the "`linger`" period, problems would occur when attempting to change some database properties.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4581[CORE-4581])_
-- The embedded server was trying to load UDFs from wrong place.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4572[CORE-4572])_
-- The incorrect error message was returned for PSQL functions when the number of actual arguments did not match the number of formal arguments.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4571[CORE-4571])_
-- Selecting from a table with ICU columns would fail where the database had been created on Linux with ICU 4.2.1 and then copied to Windows.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4561[CORE-4561])_
-- BUGCHECK(183) was thrown when using a cursor with `ORDER BY ID+0` and `FOR UPDATE WITH LOCK`.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4539[CORE-4539])_
-- The server would not accept the right plan.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4507[CORE-4507])_
-- Procedure source could not be deleted.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4472[CORE-4472])_
-- The message "`Modifying function <F> which is currently in use`" was displayed when `<F>` was called from an internal function declared in another unit.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4384[CORE-4384])_
-- Problems would occur when a table grew beyond 65535 pointer pages.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4383[CORE-4383])_
-- Index and BLOBs garbage collection was not working for in-place updates.

_fixed by D. Sibiryakov & D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4382[CORE-4382])_
-- User savepoints were not being released on `COMMIT`.

_fixed by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4369[CORE-4369])_
-- BUGCHECK(177) was being thrown for a `MERGE` involving multiple matches.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4280[CORE-4280])_
-- Stored PSQL functions would accept duplicate input arguments.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4161[CORE-4161])_
-- It was not possible to insert records into a table having a column `GENERATED BY DEFAULT AS IDENTITY` in its DDL.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3373[CORE-3373])_
-- It was possible to store a 31-character string in a `VARCHAR(25)` column.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2932[CORE-2932])_
-- Field position would be wrong after `ALTER POSITION`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2848[CORE-2848])_
-- Page-level "`lock conversion denied`" or "`lock denied`" errors could occur under high load when no deadlocks were apparent.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-214[CORE-214])_
-- `COUNT (DISTINCT ...)` was too slow.

_fixed by D. Yemanov_

'''

[[bug-300b2-crash]]
=== Server Crashes

_(http://tracker.firebirdsql.org/browse/CORE-4766[CORE-4766])_
-- An access violation would occur on an attempt to manage the users list using `EXECUTE STATEMENT` on behalf of a non-SYSDBA user having the `RDB$ADMIN` role.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4705[CORE-4705])_
-- Superclassic would crash at disconnect after running `EXECUTE STATEMENT` as non-current user.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4653[CORE-4653])_
-- Infinite mutual stored procedure calls were causing the server to crash instead of returning the appropriate error, "`Too many concurrent executions of the same request`".

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4075[CORE-4075])_
-- The server would bugcheck or crash on an exception in a calculated index.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3632[CORE-3632])_
-- The application would crash after calling `fork()` in a process using `libfbembed.so`.

_fixed by A. Peshkov_

'''

[[bug-300b2-api]]
=== API/Remote Interface

_(http://tracker.firebirdsql.org/browse/CORE-4795[CORE-4795])_
-- fbclient was executing the event callback function twice.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4794[CORE-4794])_
-- `isc_cancel_events()` was returning the error "`invalid events id (handle) (code: 335545021)`" if an event was no longer queued.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4788[CORE-4788])_
-- The Superclassic server could hang when receiving a network packet.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4785[CORE-4785])_
-- Bad `op_execute` packet would kill the server.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4756[CORE-4756])_
-- Events were broken in Firebird 3.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4646[CORE-4646])_
-- Attachment would fail when using `LegacyAuth` on the server and the default configuration on the client.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4639[CORE-4639])_
-- Linux servers could reject connections with a transliteration error.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4471[CORE-4471])_
-- The `Legacy_Auth` plugin would not connect from a FB3 to a FB2.5 server when tried after `Win_Sspi`.

_fixed by A. Peshkov_

'''

[[bug-300b2-utils]]
=== Utilities

[[bug300b2-utils-isql]]
==== isql

_(http://tracker.firebirdsql.org/browse/CORE-4782[CORE-4782])_
-- `SHOW TABLE` command in _isql_ would fail when the table contained a field with Unicode collation in its DDL.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4706[CORE-4706])_
-- _isql_ was padding BLOB columns wrongly when the column alias had more than 17 characters.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4578[CORE-4578])_
-- In _isql_, `INPUT` files were not being properly closed.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4503[CORE-4503])_
-- In _isql_, the command `SHOW USERS` would display only the current user.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4259[CORE-4259])_
-- The call to `setlocale(LC_CTYPE, "")` should not be made in _isql_ for Windows.

_fixed by F. Schlottmann-Goedde & D. Yemanov_

'''

[[bug300b2-utils-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-4715[CORE-4715])_
-- Restore of a shadowed database would fail if the `-k` ("`restore without shadow`") switch was used.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4704[CORE-4704])_
-- Permissions for generators and exceptions were being corrupted after backup/restore.

_fixed by D. Yemanov_

'''

[[bug300b2-utils-gsec]]
==== gsec

_(http://tracker.firebirdsql.org/browse/CORE-4698[CORE-4698])_
-- Typing `add -user SYSDBA -pw masterkey -admin yes` into _gsec_ would crash `firebird.exe`.

_fixed by V. Khorsun & A. Peshkov_

'''

[[bug-300b2-beta02-improv]]
== Firebird 3.0 Second Beta Release: Improvements

The following improvements were implemented prior to the version 3.0.0 Beta 2 release:

_(http://tracker.firebirdsql.org/browse/CORE-4791[CORE-4791])_
-- `INSERTING`, `UPDATING` and `DELETING` were made reserved words to fix ambiguity with Boolean expressions.

_implemented by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4735[CORE-4735])_
-- An expression "```where bool_field IS true | false```" can now use the same index as "```where bool_field = true | false```" if such an index exists.

_implemented by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4731[CORE-4731])_
-- Issuing DML or DDL statements on the `RDB${asterisk}` system tables is prohibited in Firebird 3.

_implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4729[CORE-4729])_
-- A flag was added to `MON$DATABASE` to assist in determining what type of security database is used -- default, self or other.

_implemented by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4696[CORE-4696])_
-- Flushing dirty pages to disk after creation of a temporary table index is now avoided.

_implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4685[CORE-4685])_
-- Resolved some risky issues on POSIX when aliases in `databases.conf` were pointing to symbolic or hard links, allowing invalid database accesses.

_implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4671[CORE-4671])_
-- Internal temporary blobs are released early, to free up some memory/disk space.

_implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4610[CORE-4610])_
-- Diagnostics will now report a tag name when transliteration errors occur in Parameter Block values.

_implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4607[CORE-4607])_
-- Support added for having multiple UserManagers in `firebird.conf` and for using them from SQL.

_implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4605[CORE-4605])_
-- The configuration parameter `CryptPlugin` was renamed to `WireCryptPlugin`.

_implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4590[CORE-4590])_
-- The data type of the result returned by the functions `CHAR_LENGTH()`, `BIT_LENGTH()` and `OCTET_LENGTH()` for BLOBs was changed to `BIGINT`.

_implemented by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4386[CORE-4386])_
-- "`Object in use`" errors now come with more details.

_implemented by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3526[CORE-3526])_
-- Support was added for `WHEN SQLSTATE` error handlers in PSQL.

_implemented by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3234[CORE-3234])_
-- Support was added for text BLOBs >= 32K as the first argument for the `TRIM()` function.

_implemented by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3226[CORE-3226])_
-- IPv6 support for the remote interface.

_implemented by M. Kubecek_

'''

_(http://tracker.firebirdsql.org/browse/CORE-733[CORE-733])_
-- Compression of data over the network.

_implemented by A. Peshkov_

'''

[[bug-300b1-beta01]]
== Firebird 3.0 First Beta Release

The following improvements and bug fixes were reported prior to the version 3.0.0 Beta 1 release:

[[bug-300b1-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-4576[CORE-4576])_
-- The Cache Writer thread could not start.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4574[CORE-4574])_
-- Regression: Incorrect result in subquery with aggregate.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4570[CORE-4570])_
-- `ALTER PACKAGE` was returning a wrong error.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4566[CORE-4566])_
-- Incorrect size of the output parameter or argument when `EXECUTE BLOCK`, procedure or function used a system field in the metadata character set.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4565[CORE-4565])_
-- GDSCODE could have value = 0 in `WHEN`-section under some concurrent environments.
This bug affected Superclassic and Classic models but not Superserver.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4555[CORE-4555])_
-- A DDL trigger was remaining active after being dropped.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4530[CORE-4530])_
-- A DB_KEY based join of two tables could be ineffective.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4522[CORE-4522])_
-- DDL permissions were not protecting against removal of BLOB filters.

_fixed by R. Simakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4515[CORE-4515])_
-- Regression: trace was reporting ``UPDATE``s in statistics when doing `INSERT into <some_table>`.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4505[CORE-4505])_
-- Use of a named cursor would fail if a statement was not executed.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4488[CORE-4488])_
-- A `FOR SELECT <L> FROM <T> AS CURSOR <C>` seems to return a wrong result if table `<T>` is modified inside the cursor's `BEGIN...END` block.
Cursor references, which are not variables, should represent the current state of the record.
If it was updated "`in place`" (via "```where current of```"), then cursor references should return the new values.
The first example reported in http://tracker.firebirdsql.org/browse/CORE-4488[CORE-4488] should return ``NULL``s.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4478[CORE-4478])_
-- Failure to load a provider or plugin was not reported anywhere.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4477[CORE-4477])_
-- The field `RDB$MAP_TO_TYPE` was missing from the system table `RDB$TYPES`.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4468[CORE-4468])_
-- `CREATE USER GRANT ADMIN ROLE` did not work.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4464[CORE-4464])_
-- Duplicate tags for `CREATE/ALTER USER` were not handled correctly.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4453[CORE-4453])_
-- Regression: The `NOT NULL` constraint, if declared in a domain, did not work.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4447[CORE-4447])_
-- A positioned `UPDATE` statement would preclude its index usage for the subsequent cursor field references.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4444[CORE-4444])_
-- Engine could hang and block all attachments in an out-of-disk-space condition during physical backup.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4433[CORE-4433])_
-- GlobalRWLock could not downgrade an EX lock to SH if readers were present.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4435[CORE-4435])_
-- After calling `release()` instead of `detach()` for an attachment to a database in embedded mode, the attachment would remain interminably active.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4430[CORE-4430])_
-- Properties of a user created in `Legacy_UserManager` were padded with spaces up to 10 characters.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4415[CORE-4415])_
-- Pointless extraction of generic DDL trigger.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4396[CORE-4396])_
-- A query executed via `EXECUTE STATEMENT` was returning the wrong result.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4395[CORE-4395])_
-- `EXECUTE STATEMENT ON EXTERNAL` was not finding a Firebird 2.5 database.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4394[CORE-4394])_
-- "`Cursor not found`" error when using the legacy API.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4388[CORE-4388])_
-- `SELECT WITH LOCK` could enter an infinite loop for a single record.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4381[CORE-4381])_
-- Run-time errors were returning incorrect line/column information.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4379[CORE-4379])_
-- Explicit cursors containing correlated subqueries in the select list were performing poorly.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4376[CORE-4376])_
-- Preparation of an erroneous DDL statement was not indicating that the main command failed.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4375[CORE-4375])_
-- A procedure would execute infinitely if it contained more than 32767 statements inside any `BEGIN...END` block.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4374[CORE-4374])_
-- Truncation error when using `EXECUTE STATEMENT` with a BLOB.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4373[CORE-4373])_
-- Package compilation was not checking for duplicate names.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4372[CORE-4372])_
-- Deadlock could occur when two data pages contained record fragments pointing to each other.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4371[CORE-4371])_
-- A `CREATE FUNCTION` or `CREATE PROCEDURE` statement that referred to a non-existent exception would return the error message "`Error while parsing function's BLR`" instead of "`exception not defined`".

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4366[CORE-4366])_
-- A `WHERE` predicate containing `NULL IS NOT DISTINCT FROM (select min(NULL) from ...)` was returning the wrong result.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4365[CORE-4365])_
-- Equality predicate distribution was not working for some complex queries.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4360[CORE-4360])_
-- `SELECT` from derived table which contains `GROUP BY` on a column with a literal value was returning wrong results.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4354[CORE-4354])_
-- Parsing of a recursive query would return the error "`Column does not belong to referenced table`" when the source table did have such a column.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4353[CORE-4353])_
-- Sorting records were larger than was really necessary.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4344[CORE-4344])_
-- Error "`no current record for fetch operation`" when table inner joins procedure inner joins table.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4334[CORE-4334])_
-- Resources (e.g. sort files) owned by a trigger could be left unreleased when the trigger was interrupted asynchronously.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4331[CORE-4331])_
-- `LAG`, `LEAD` and `NTH_VALUE` would raise an error when the second argument was `NULL`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4330[CORE-4330])_
-- The function `LAG` returned an incorrect result if the `OFFSET` value was assigned from a table.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4326[CORE-4326])_
-- The keyword `SET` was required in the `ALTER USER` statement when it should have been optional.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4318[CORE-4318])_
-- Regression: Predicates involving PSQL variables or parameters were not pushed inside the aggregation.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4313[CORE-4313])_
-- Error "`Attempt to reopen an open cursor`" could be raised if the query handle was reused in a different transaction.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4309[CORE-4309])_
-- The 'Cache Writer' record in `MON$ATTACHMENTS` would vanish when deleting, via delete from `MON$ATTACHMENTS`, another connection that was running a heavy update on a big table.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4307[CORE-4307])_
-- Any fields present only in the `WHERE` clause of a view `WITH CHECK OPTION` would cause an invalid CHECK CONSTRAINT violation.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4303[CORE-4303])_
-- Possible races during service destruction.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4301[CORE-4301])_
-- Non-ASCII data in `SEC$USERS` was not read correctly.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4286[CORE-4286])_
-- The error "`Statement already has a cursor assigned`" would be thrown when trying to execute another SQL statement using a different cursor name.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4118[CORE-4118])_
-- Expression index might be overlooked for derived fields or view fields.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3305[CORE-3305])_
-- A "`BLOB not found`" error would be returned after creating or altering an invalid trigger.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2350[CORE-2350])_
-- An over-long column name for a `SELECT` alias was not being rejected, as it should have been.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-1475[CORE-1475])_
-- A database which had active attachments could not be replaced from a backup file even after the database was shut down.

_fixed by D. Yemanov_

'''

[[bug-300b1-crash]]
=== Server Crashes

_(http://tracker.firebirdsql.org/browse/CORE-4575[CORE-4575])_
-- The server would crash in the garbage collector thread at disconnect of the last attachment.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4568[CORE-4568])_
-- The server could crash while disconnecting from the database under load.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4510[CORE-4510])_
-- A database validation bug could cause the server to crash.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4506[CORE-4506])_
-- The server would crash when executing almost any "```show ...```" commands after a reconnect.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4500[CORE-4500])_
-- Firebird would crash after an unsuccessful remapping of the lock table's shared memory.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4498[CORE-4498])_
-- The server would crash when getting an explained plan for a DBKEY-based retrieval.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4422[CORE-4422])_
-- The server would crash when using `ROW_NUMBER() OVER (PARTITION BY x)` in an `ORDER BY` clause.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4419[CORE-4419])_
-- The server could crash while sorting records longer than 128KB.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4322[CORE-4322])_
-- The engine would crash when aggregate or window functions were used in a recursive query.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4321[CORE-4321])_
-- Regression: _isql_ was not destroying the SQL statement.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4319[CORE-4319])_
-- The engine would crash when the Trace config contained the line "```connection_id=NN```" and an attempt was made to connect to a non-existent database or alias.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4304[CORE-4304])_
-- The engine would crash when an attempt to **re**create a table with a foreign key was made after a syntax error that preceded the `RECREATE` attempt.

_fixed by A. dos Santos Fernandes_

'''

[[bug-300b1-api]]
=== API/Remote Interface

_(http://tracker.firebirdsql.org/browse/CORE-4275[CORE-4275])_
-- `CREATE DATABASE` would fault if `fbclient.dll` was loaded from another directory (`Providers = Engine12`).

_fixed by V. Khorsun_

'''

[[bug-300b1-utils]]
=== Utilities

[[bug300b1-utils-isql]]
==== isql

_(http://tracker.firebirdsql.org/browse/CORE-4480[CORE-4480])_
-- _isql_ would issue the warning "`Bad debug info format`" when connecting to a database with stored functions after a restore.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4440[CORE-4440])_
-- _isql_ would crash without connecting when executing the command `SHOW VERSION`.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4380[CORE-4380])_
-- _isql_ would truncate a BLOB when reading an empty segment.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4320[CORE-4320])_
-- Regression: _isql_ would crash when receiving statistics from the execution of a SQL query.

_fixed by V. Khorsun_

'''

[[bug300b1-utils-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-4470[CORE-4470])_
-- _gbak_ restore would fail on a database containing dependency between views and packaged functions.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4425[CORE-4425])_
-- User collations based on `UNICODE` were not being upgraded to a newer ICU version on restore.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4417[CORE-4417])_
-- _gbak_ refused to commit the index for a primary key with characters accented with an umlaut.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4346[CORE-4346])_
-- Version 3 _gbak_ was unable to restore backups made on earlier server versions.

_fixed by D. Yemanov_

'''

[[bug300b1-utils-nbackup]]
==== nBackup

_(http://tracker.firebirdsql.org/browse/CORE-4461[CORE-4461])_
-- _nbackup_ was printing error messages to _stdout_ instead of _stderr_.

_fixed by A. Peshkov_

'''

[[bug300b1-utils-qli]]
==== qli

_(http://tracker.firebirdsql.org/browse/CORE-4327[CORE-4327])_
-- _qli_ was throwing an error when copying `NULL` blobs between databases.

_fixed by A. Peshkov_

'''

[[bug-300a2-alpha02]]
== Firebird 3.0 Second Alpha Release

The following improvements and bug fixes were reported as fixed prior to the version 3.0.0 release:

[[bug-300a2-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-4302[CORE-4302])_
-- Descending index could be very inefficient for some keys

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4289[CORE-4289])_
-- A `NOT NULL` field from a derived table could become `NULL` when referred to from outside the derived table

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4281[CORE-4281])_
-- `TYPE OF` arguments of stored functions could cause the server to hang if depending on a domain or column that had been changed

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4270[CORE-4270])_
-- A subquery involving a windowed function and a `where <field> IN(select ...)` condition could cause an error

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4265[CORE-4265])_
-- An unexpected lock conflict error could be raised while connecting to a heavily loaded database

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4262[CORE-4262])_
-- Context parsing errors could occur with derived tables and `CASE` functions

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4261[CORE-4261])_
-- `JOIN` result could be wrong when joined fields had been created via the `row_number()` function

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4258[CORE-4258])_
-- The boundary for the minimum value for `BIGINT`/`DECIMAL(18)` was wrong

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4251[CORE-4251])_
-- The Guardian service could write garbage after the end of a message in the Event Log

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4250[CORE-4250])_
-- Access violation could occur in Guardian at process shutdown

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4237[CORE-4237])_
-- Metadata being reported from system table queries for UDF return arguments was different to that returned in Firebird 2.5

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4234[CORE-4234])_
-- `IF (subfunc())` would throw an error when subfunc returned a `BOOLEAN`

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4229[CORE-4229])_
-- Bidirectional cursor was not being positioned by the first call of `FETCH LAST`

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4227[CORE-4227])_
-- A parser conflict was causing wrong evaluation of `BETWEEN` and Boolean expressions

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4216[CORE-4216])_
-- Memory leak with `TRIGGER ON TRANSACTION COMMIT`

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4211[CORE-4211])_
-- The embedded engine would hang for 5 seconds when closing, with errors about timeout in shutdown process and invalid mutex being written into `firebird.log`

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4201[CORE-4201])_
-- A computed field would return `NULL` inside a `BEFORE INSERT` trigger

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4198[CORE-4198])_
-- An incorrect "`token unknown`" error would occur when an SQL string ended with a hex number literal

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4177[CORE-4177])_
-- Some Boolean expressions were not being allowed

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4159[CORE-4159])_
-- Incorrect memory statistics were being reported

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4156[CORE-4156])_
-- `RDB$GET_CONTEXT`/`RDB$SET_CONTEXT` parameters were being described incorrectly as `CHAR NOT NULL` instead of  `VARCHAR NULLABLE`

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3989[CORE-3989])_
-- Bad performance and slow response were exhibited when many concurrent sorts were executed

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3921[CORE-3921])_
-- With `bugcheckabort=1` and sweep starting at gap ~21000, "`Bugcheck 186 (record disappeared)`" and 100% CPU load would occur

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2165[CORE-2165])_
-- Unnecessary index reads could occur when using a strict inequality condition

_fixed by V. Khorsun_

'''

[[bug-300a2-crash]]
=== Server Crashes

_(http://tracker.firebirdsql.org/browse/CORE-4293[CORE-4293])_
-- The server could crash on a `SELECT` with a long or complex list of compound ``AND``/``OR``'d predicates

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4271[CORE-4271])_
-- Recreation of an errant package body could cause the engine to crash

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4268[CORE-4268])_
-- Disconnecting from a database could cause a server crash

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4267[CORE-4267])_
-- Sweeping a database could cause a server crash

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4225[CORE-4225])_
-- The server could crash when trace activity was attempted on a database having a database-level trigger

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4185[CORE-4185])_
-- Server crashes could occur, reporting "`invalid lock id (NNNNN)`"

_fixed by A. Peshkov_

'''

[[bug-300a2-api]]
=== API/Remote Interface

_(http://tracker.firebirdsql.org/browse/CORE-4283[CORE-4283])_
-- "`Resource temporarily unavailable`" errors could occur while events were being registered simultaneously

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4236[CORE-4236])_
-- Database shutdown was being reported as successfully completed before all active connections had actually been interrupted

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4178[CORE-4178])_
-- The new API was still returning obscure historical definition artifacts of data fields, instead of proper metadata properties that would make the interface actually usable

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4162[CORE-4162])_
-- Warnings were not being returned from calls to `attachDatabase()`

_fixed by A. Peshkov_

'''

[[bug-300a2-security]]
=== Security/User Management

_(http://tracker.firebirdsql.org/browse/CORE-4241[CORE-4241])_
-- Log-in could succeed with an empty password

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4200[CORE-4200])_
-- An uncommitted `SELECT` from the pseudo table `SEC$USERS` would block new database connections

_fixed by A. Peshkov_

'''

[[bug-300a2-psql]]
=== Procedural Language

_(http://tracker.firebirdsql.org/browse/CORE-4247[CORE-4247])_
-- Positioned `DELETE ... WHERE CURRENT OF <CURSOR>` could fail for tables with newly added fields

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4244[CORE-4244])_
-- Creating a procedure could be a problem if it involved adding text in DOS864 character set

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4184[CORE-4184])_
-- An error would be raised while executing an empty `EXECUTE BLOCK` with `NOT NULL` output parameter

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4160[CORE-4160])_
-- A parameterized exception would mishandle non-ASCII characters passed as the parameter

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4145[CORE-4145])_
-- Preparing an `EXECUTE BLOCK` that used domains was causing a memory leak

_fixed by A. dos Santos Fernandes_

'''

[[bug-300a2-ddl]]
=== Data Definition Language

_(http://tracker.firebirdsql.org/browse/CORE-4214[CORE-4214])_
-- Global temporary tables were able to reference permanent relations, which they should not be able to do

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4212[CORE-4212])_
-- Dropping a foreign key on a Global temporary table would cause a server crash

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4203[CORE-4203])_
-- Packaged routines with `CHAR` or `VARCHAR` parameters could not be created

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4180[CORE-4180])_
-- `CREATE COLLATION` was not verifying the base collation character set

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4173[CORE-4173])_
-- Setting a generator value twice in a single transaction would set it to zero

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4155[CORE-4155])_
-- External routines DDL in packages was wrongly reporting termination with semi-colon as an error

_fixed by A. dos Santos Fernandes_

'''

[[bug-300a2-dml]]
=== Data Manipulation Language

_(http://tracker.firebirdsql.org/browse/CORE-4269[CORE-4269])_
-- Wrong output would be produced when a field with the result of a windowed function was used in a query with a useless `WHERE 0=0` and `GROUP BY` clause

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4255[CORE-4255])_
-- Parameterized queries using `RDB$DB_KEY` would not work

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4240[CORE-4240])_
-- Recursive query would return incorrect results if passage through more than one branch was requested

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4158[CORE-4158])_
-- `LIKE` with `ESCAPE` clause was not working

_fixed by A. dos Santos Fernandes_

'''

[[bug-300a2-utils]]
=== Utilities

[[bug300a2-utils-gfix]]
==== gfix

_(http://tracker.firebirdsql.org/browse/CORE-4297[CORE-4297])_
-- `gfix` would crash when the size of the description of a limbo transaction was larger than 1 KB

_fixed by V. Khorsun_

'''

[[bug300a2-utils-fbsvcmgr]]
==== fbsvcmgr

_(http://tracker.firebirdsql.org/browse/CORE-4298[CORE-4298])_
-- `fbsvcmgr` was not recognising `sts_record_versions` and other `sts` switches

_fixed by A. Peshkov_

'''

[[bug-300a2-utils-isql]]
==== isql

_(http://tracker.firebirdsql.org/browse/CORE-4259[CORE-4259])_
-- Bug in the `isql` command `setlocale(LC_CTYPE, "")` on Windows due to a reference to `editline`, which is not available on that platform

_fixed by F. Schlottmann-Goedde_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4205[CORE-4205])_
-- `ISQL -x` was failing to output the `START WITH` clause of generators/sequences

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4149[CORE-4149])_
-- New permission types were not being displayed by _isql_

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-362[CORE-362])_
-- It was impossible to enter certain characters in _isql_

_fixed by F. Schlottmann-Goedde_

'''

[[bug-300a2-utils-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-4202[CORE-4202])_
-- Backup/restore from an older version to version 3.0 would fail with a BLR error

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4168[CORE-4168])_
-- A backup containing procedures or triggers that selected from external tables could not be restored with `ExternalFileAccess = None`

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4164[CORE-4164])_
-- Owner name was missing for generators and exceptions restored from a backup

_fixed by D. Yemanov_

'''

[[bug-300a2-utils-nbackup]]
==== nbackup

_(http://tracker.firebirdsql.org/browse/CORE-2648[CORE-2648])_
-- __nbackup__'s delta file was ignoring the Forced Writes setting of the database

_fixed by V. Khorsun_

'''

[[bug-300a2-utils-mon]]
==== Database Monitoring (MON$)

_(http://tracker.firebirdsql.org/browse/CORE-4235[CORE-4235])_
-- Deadlock could occur while accessing the monitoring tables under concurrent load

_fixed by D. Yemanov & V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4176[CORE-4176])_
-- Monitoring tables were returning incomplete information in Classic and Superclassic configurations

_fixed by D. Yemanov_

'''

[[bug-300a2-utils-trace]]
==== Trace

_(http://tracker.firebirdsql.org/browse/CORE-4219[CORE-4219])_
-- Regular expressions with double-slash would fail in trace

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4163[CORE-4163])_
-- Configuration file `fbtrace.conf` contained syntax errors

_fixed by A. Peshkov_

'''

[[bug-300a2-intl]]
=== International Language Support

{nbsp}

[[bug-300a2-installs]]
=== Installation Issues

_(http://tracker.firebirdsql.org/browse/CORE-4153[CORE-4153])_
-- Attempting to use `Legacy_Auth` directly after install would not work without restarting the service

_fixed by P. Reeves_

'''

[[bug-300-alpha01]]
== Firebird 3.0 First Alpha Release

The following improvements and bug fixes were reported as fixed prior to the version 3.0.0 release:

[[bug-300-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-4135[CORE-4135])_
-- Sweep was blocking the establishment of concurrent attachments in Superserver.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4134[CORE-4134])_
-- A race condition could occur when auto-sweep was started.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4074[CORE-4074])_
-- `COMPUTED BY` columns and `POSITION` function could produce garbled results.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4027[CORE-4027])_
-- Creating a table with computed fields containing `SELECT FIRST` could produce a corrupted result.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3973[CORE-3973])_
-- The SQLDA for an aliased column in a grouped query was missing the original table name, column name and owner.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3947[CORE-3947])_
-- Wrong results were produced when a column in the `WHERE` clause used the collation option (`NUMERIC-SORT=1`).

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3941[CORE-3941])_
-- A unique expression index would exhibit a memory alignment problem.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3929[CORE-3929])_
-- The invalid error "`attempted update of read-only column`" would appear when selecting `MINVALUE` from a list of more than 255 elements.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3894[CORE-3894])_
-- When an attempt was made to reduce the size of a `CHAR` or `VARCHAR` column, the numbers delivered in the error message were incorrect.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3874[CORE-3874])_
-- A computed column would appear in non-existent rows output from a left join.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3820[CORE-3820])_
-- Some character sets were duplicated in the system table `RDB$TYPES`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3754[CORE-3754])_
-- `SIMILAR TO` was not working correctly.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3735[CORE-3735])_
-- An unprivileged user could delete from the system tables `RDB$DATABASE`, `RDB$COLLATIONS` and `RDB$CHARACTER_SETS`.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3694[CORE-3694])_
-- "`Internal consistency check`" would occur in a query with grouping by subquery+stored procedure+aggregate.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3672[CORE-3672])_
-- It was not possible to use the `SUBSTRING` function to create a computed index for large columns.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3638[CORE-3638])_
-- Some collation tweaking:
`FR_CA_CI_AI` collation was introduced;
`FR_FR` was changed to be identical to `FR_CA` and `FR_FR_CI_AI` was changed to be identical to the new `FR_CA_CI_AI`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3476[CORE-3476])_
-- The `LIST` function was concatenating binary blobs as though they were text.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3401[CORE-3401])_
-- Collation errors could occur with the use of `[type of] <domain>` and `type of <column>`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3373[CORE-3373])_
-- It was possible to store a string of length 31 characters into a `VARCHAR(25)` column.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3338[CORE-3338])_
-- _Regression:_ Code changes had disabled support for expression indexes with `COALESCE`, `CASE` and `DECODE`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3317[CORE-3317])_
-- Success of row deletion depended on the order of insertion of the rows.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3310[CORE-3310])_
-- A complex expression involving `RDB$GET_CONTEXT` and `BETWEEN` worked in DSQL but failed with a conversion error when selected in a view definition.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3260[CORE-3260])_
-- `interlock.h` was not portable.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3250[CORE-3250])_
-- The Firebird server could not be started under any user name other than "`root`", "`firebird`", "`interbas`" or "`interbase`".

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3239[CORE-3239])_
-- The collation `UTF8 UNICODE_CI` could not be used in a compound index.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3204[CORE-3204])_
-- A constraint violation error involving `CAST` was not being raised inside views.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3052[CORE-3052])_
-- Comparisons involving multiple index segments could produce wrong result sets.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2988[CORE-2988])_
-- The concurrent transaction number was not being reported when a lock timeout occurred.

_fixed by N. Samofatov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2957[CORE-2957])_
-- `COUNT({asterisk})` from a big table could return a negative result.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2952[CORE-2952])_
-- Character class names in `SIMILAR TO` expressions could be case-sensitive or case-insensitive, depending on the collation of the left part, whereas they should be unequivocally case-insensitive.

_fixed by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2932[CORE-2932])_
-- An `ALTER TABLE ... ALTER COLUMN ... ALTER POSITION` operation could result in wrong column positions.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2922[CORE-2922])_
-- The character set used in a constant was not being registered as a dependency.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2913[CORE-2913])_
-- `COLLATE` expressions were being applied incorrectly.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2798[CORE-2798])_
-- Plan output lacked the names of views when selecting from views that contained procedure calls.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2796[CORE-2796])_
-- DB_KEY was always zero for rows in external tables.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2678[CORE-2678])_
-- A full outer join could not use available indices, resulting in very slow execution sometimes.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2508[CORE-2508])_
-- Use of certain choices of character in double-quoted index names, for example a bracket character, could defeat the parsing logic when generating a human-readable plan.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2155[CORE-2155])_
-- A join of a stored procedure with a view or a table could fail with the error "`No current record for fetch operation`".

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-1712[CORE-1712])_
-- A buffer overrun error was being caught erroneously in a `DOUBLE PRECISION` to `VARCHAR` conversion in a Dialect 1 database.

_fixed by C. Valderrama C._

'''

_(http://tracker.firebirdsql.org/browse/CORE-1605[CORE-1605])_
-- An aggregated query was causing "`Bugcheck 232 (invalid operation)`".

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-1550[CORE-1550])_
-- An unnecessary index scan was executed when the same index is mapped to both `WHERE` and `ORDER BY` clauses.

_fixed by D. Yemanov_

'''

[[bug-300-api]]
=== API/Remote Interface

_(http://tracker.firebirdsql.org/browse/CORE-3718[CORE-3718])_
-- The client library could hang after an unsuccessful attempt to connect to the remote auxiliary (events) port.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3475[CORE-3475])_
-- Parameters inside the `CAST` function were being wrongly described in the SQLDA as non-nullable.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3269[CORE-3269])_
-- The client would perform _detach_ incorrectly when the server became unavailable.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2484[CORE-2484])_
-- An erroneous "`Success`" message would be returned in the error status vector when failing to connect to a trash database file.

_fixed by C. Valderrama C._

'''

_(http://tracker.firebirdsql.org/browse/CORE-2431[CORE-2431])_
-- String values in error messages were not converted to the connection character set.

_fixed by A. dos Santos Fernandes_

'''

[[bug-300-psql]]
=== Procedural Language

_(http://tracker.firebirdsql.org/browse/CORE-4018[CORE-4018])_
-- Use of a system domain in declarations of arguments or return values in a stored procedure could prevent the procedure from being modifiable.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3737[CORE-3737])_
-- `EXECUTE BLOCK` parameter definitions were not being respected and could cause wrong behavior with respect to character sets.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3545[CORE-3545])_
-- Validation of domain `CHECK` constraints when used in PSQL declarations was inconsistent: it was using the type of the expression, instead of the type of the variable.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3055[CORE-3055])_
-- The names of variables or arguments could be wrong or absent in error messages when more than 256 variables were used.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3047[CORE-3047])_
-- Resolution of `EXECUTE BLOCK` parameter collations was using wrong logic.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2204[CORE-2204])_
-- Constraints on stored procedure output parameters were checked even when the procedure returned no rows.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-1620[CORE-1620])_
-- Incorrect error message (an absurd column number) was returned if an empty SQL string was prepared for `EXECUTE STATEMENT`.

_fixed by D. Yemanov_

'''

[[bug-300-ddl]]
=== Data Definition Language

_(http://tracker.firebirdsql.org/browse/CORE-3114[CORE-3114])_
-- Attempting to drop a non-existent generator (sequence) would result in a serious exception.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3056[CORE-3056])_
-- Problems could occur if further DDL commands were issued in the same transaction following a `CREATE COLLATION` command.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2696[CORE-2696])_
-- The `ALTER TABLE` command allowed the addition of a column with a `NOT NULL` definition, allowing a non-savvy DBAdmin to wreck the table.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-1748[CORE-1748])_
-- Unrestorable backup: a problem which would occur if `ALTER TABLE ... ADD COLUMN` added a column with a `NOT NULL` constraint.
The fix for http://tracker.firebirdsql.org/browse/CORE-2696[CORE-2696] has now made it impossible to do this.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-1518[CORE-1518])_
-- Adding a non-nullable column to a populated table would render the table inconsistent.
The fix for http://tracker.firebirdsql.org/browse/CORE-2696[CORE-2696] has now made it impossible to do this.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-1355[CORE-1355])_
-- Client tools tended to be confused about how to interpret a `NULL` that is returned from a non-nullable column.
The fix for http://tracker.firebirdsql.org/browse/CORE-2696[CORE-2696] has now made it impossible to add a non-nullable column to a populated table.

It is not clear, though, whether this part of the fix makes it mandatory to specify a default value for a non-nullable column.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-634[CORE-634])_
-- Bad behaviour of `DELETE` when the `WHERE` clause was a subquery involving `FIRST`/`SKIP`: the operation would zap every row in the table.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-304[CORE-304])_
-- Any user could alter or drop generators and exceptions, a metadata security hole.

_fixed by D. Yemanov_

'''

[[bug-300-dml]]
=== Data Manipulation Language & DSQL

_(http://tracker.firebirdsql.org/browse/CORE-4144[CORE-4144])_
-- When when preparing a query with `UNION`, the error "`context already in use (BLR error)`" was wrongly being thrown.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4005[CORE-4005])_
-- Recursive CTEs were returning a wrong  error message.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3416[CORE-3416])_
-- Inserting a word containing the 8-bit character '``````' into a `CHARACTER SET ASCII` column would succeed instead of throwing a transliteration error.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3201[CORE-3201])_
-- The internal function `ATAN2` was returning an incorrect value with arguments `(0, 0)`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3174[CORE-3174])_
-- An expression index involving `TRIM` could lead to an incorrect indexed lookup.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2699[CORE-2699])_
-- A common table expression context could be used with parameters.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2606[CORE-2606])_
-- A multi-byte `CHAR` value requested as `VARCHAR` was returned with padded spaces.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2238[CORE-2238])_
-- With UTF8 and large varchar fields, `IS DISTINCT FROM` would cause the error "`Implementation limit exceeded`".

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-1188[CORE-1188])_
-- `STARTING WITH ?` (where the parameter value supplied is an empty string) would fail if the plan used a compound index.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-92[CORE-92])_
-- Infinite insertion cycle: `INSERT INTO THIS_TABLE SELECT ... FROM THIS_TABLE` would loop forever until resources were exhausted.

_fixed by V. Khorsun_

'''

[[bug-300-utils]]
=== Command-line Utilities

_(http://tracker.firebirdsql.org/browse/CORE-2547[CORE-2547])_
-- Utilities did not always honour the minimum number of characters required to recognise an option.

_fixed by C. Valderrama C._

'''

Other old bugs that were fixed in utilities:

[[bug-300-utils-fbguard]]
==== FbGuard

_(http://tracker.firebirdsql.org/browse/CORE-2784[CORE-2784])_
-- Guardian would keep creating more and more threads each time FBServer died.

_fixed by C. Valderrama C._

'''

_(http://tracker.firebirdsql.org/browse/CORE-1595[CORE-1595])_
-- Firebird Guardian's tray icon would disappear after a Windows Explorer crash.

_fixed by C. Valderrama C._

'''

[[bug-300-utils-isql]]
==== isql

_(http://tracker.firebirdsql.org/browse/CORE-4137[CORE-4137])_
-- _isql_ was generating metadata script output with syntax errors in the `CHARACTER SET` clause, e.g., `CHARACTER SETISO8859_1`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3431[CORE-3431])_
-- _isql_ was padding UTF-8 data incorrectly.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2788[CORE-2788])_
-- _isql_ would extract the array dimensions after the character set name.

_fixed by C. Valderrama C._

'''

[[bug-300-utils-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-3575[CORE-3575])_
-- _gbak_ did not support backup volumes of size greater than 4GB.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2740[CORE-2740])_
-- _gbak_ would restore invalid views without any warning to the user.

_fixed by C. Valderrama C._

'''

_(http://tracker.firebirdsql.org/browse/CORE-2545[CORE-2545])_
-- Several validations were lacking in _gbak_.

_fixed by C. Valderrama C._

'''

[[bug-300-utils-nbackup]]
==== nbackup

_(http://tracker.firebirdsql.org/browse/CORE-2543[CORE-2543])_
-- _nbackup_ could hide the real cause of a failure.

_fixed by C. Valderrama C._

'''

[[bug-300-intl]]
=== International Language Support

_(http://tracker.firebirdsql.org/browse/CORE-4136[CORE-4136])_
-- The "`Sharp-S`" character was being treated incorrectly in the `UNICODE_CI_AI` collation.

_fixed by A. dos Santos Fernandes_

'''
