[[rnfb30-fbconf]]
= Configuration Additions and Changes

The file `aliases.conf` has been renamed to `databases.conf`.
An old `aliases.conf` from a previous version can simply be renamed, and the new engine will just continue to use it as before.
However, `databases.conf` can now include some configuration information for individual databases.

[[rnfb30-configparams-scope]]
== Scope of Parameters

Some parameters are marked as configurable _per-database_ or _per-connection_.

* Per-database configuration is done in `databases.conf`.
* Per-connection configuration is primarily for client tool use and is done using the DPB parameter `isc_dpb_config` or, for Services, the SPB parameter `isc_spb_config`.
* In the case of Embedded, the DPB can be used to tune per-database entries on first attaching to a database.

[[rnfb30-configparams-macrosubs]]
== Macro Substitution

A number of predefined macros (syntax `$(name)`) is available for use in the configuration files to substitute for a directory name:

`$(root)`::
Root directory of Firebird instance

`$(install)`::
Directory where Firebird is installed.
`$(root)` and `$(install)` are initially the same.
`$(root)` can be overridden by setting or altering the environment variable `FIREBIRD`, in which case it becomes different from `$(install)`.

`$(this)`::
Directory where current configuration file is located

`$(dir_conf)`::
Directory where `firebird.conf` and `databases.conf` are located

`$(dir_secdb)`::
Directory where the default security database is located

`$(dir_plugins)`::
Directory where plugins are located

`$(dir_udf)`::
Directory where UDFs are located by default

`$(dir_sample)`::
Directory where samples are located

`$(dir_sampledb)`::
Directory where sample DB (employee.fdb) is located

`$(dir_intl)`::
Directory where international modules are located

`$(dir_msg)`::
Directory where the messages file (`firebird.msg`) is located.
`$(dir_msg)` usually should be the same as `$(root)` but can be overridden by the environment variable `FIREBIRD_MSG`.

[TIP]
====
You can observe the usage of some of these macros in `databases.conf.`
====

[NOTE]
====
In our pre-built binaries, `$(dir_conf)` and `$(dir_secdb)` would normally be the same as `$(root)` and `$(install)`.

`$(dir_plugins)`, `$(dir_udf)`, `$(dir_sample)`, `$(dir_sampledb)` and `$(dir_intl)` are predefined sub-directories inside `$(root)`.

The build conventions are not "`rules`" that could be expected to apply in every distribution of Firebird.
Distro-specific Linux packages, for example, each prefer to fit the Firebird components into standard layouts that comply with their own conventions.
As an illustration, user binaries, such as _isql_ might be located in `/usr/bin`, server binaries in `/usr/sbin`, configuration files in `/etc/firebird.d` and so on.
Obviously, `$(root)` would then make no sense, even if the `$(dir_something)` macros still pointed to actual directories.
====

[[rnfb30-fbconf-includes]]
== Includes

One configuration file can be included in another by using an "`include`" directive, e.g., 

[source]
----
include some_file.conf
----

A relative path is treated as relative to the enclosing configuration file.
So, if our example above is inside `/opt/config/master.conf` then our `include` refers to the file `/opt/config/some_file.conf`.

[[rnfb30-fbconf-includes-wildcard]]
=== Wildcards

The standard wildcards '```{asterisk}```' and '```?```' may be used in an `include` directive, to include all matching files in undefined order.
For example,

[source]
----
include $(dir_plugins)/config/*.conf
----

[[rnfb30-fbconf-expressions]]
== Expression of Parameter Values

Previously, byte values were specified by default as integer, representing the number of bytes.
However, now you can optionally specify them in _Kilobytes_, _Megabytes_ or _Gigabytes_, as appropriate, by adding '```K```', '```M```' or '```G```' (case-insensitive). For example, "```24M```" is read as 25165824 (24 * 1024 * 1024).

Boolean values are expressed as non-zero (true)|zero (false) by default, but you may now use the quoted strings `'y'`, `'yes'` or `'true'` instead of a non-zero digit.

[[rnfb3-fbconf-perdatabase]]
== "`Per-database`" Configuration

Custom configuration at database level is achieved with formal entries in `databases.conf`.

[[rnfb3-fbconf-perdatabase-format]]
=== Format of Configuration Entries

In `aliases.conf` the format for specifying a database alias was

[source]
----
aliasname = /absolute/path/to/database_file
----

If you are not adding any database-specific configuration directives for an alias, the format is just as it was before, e.g.,

[source,subs=+quotes]
----
emp = c:\Program Files\examples\empbuild\employee.fdb
 *or*
emp = /opt/firebird/examples/empbuild/employee.fdb
 *or*
emp = $(dir_sampleDb)/employee.fdb
----

A slightly more complex format is used for cases where certain non-global parameters are to be targeted at an individual database.
The entry for the database is defined by the alias declaration, as previously.
The database-specific directives are listed below it, within curly brackets.

[source]
----
#
# Directives for MYBIGDB
MYBIGDB = opt/databases/mybigdb.fdb
   {
      LockMemSize = 32M           # We know that MYBIGDB needs a lot of locks
      LockHashSlots = 19927       # and a hash table large enough for them
   }
----

[[rnfb3-fbconf-perdatabase-parameters]]
=== Parameters Available

The following parameters can be copy/pasted to `databases.conf` and used as overrides for specific databases.

.Parameters available in `databases.conf`
[cols="1m,1m,1m", stripes="none"]
|===
3+h|Engine-related

|DatabaseGrowthIncrement
|DeadlockTimeout
|DefaultDbCachePages

|EventMemSize
|FileSystemCacheThreshold
|ExternalFileAccess

|GCPolicy
|LockAcquireSpins
|LockHashSlots

|LockMemSize
|MaxUnflushedWrites
|MaxUnflushedWriteTime

|<<rnfb30-fbconf-securitydatabase,SecurityDatabase>>
|<<rnfb30-fbconf-usermanager,UserManager>>
|{nbsp}

|<<rnfb30-fbconf-wirecompression,
WireCompression>>
|<<rnfb30-fbconf-wirecrypt,WireCrypt>>
|<<rnfb30-fbconf-cryptplugin,WireCryptPlugin>>

h|Client-related
2+d|__Some parameters can be configured at the client connection via the DPB/SPB, as an alternative to configuring them in `databases.conf`.
 to <<rnfb30-configparams-scope,Scope of Parameters>> at the beginning of this chapter to understand these differences.__

|<<rnfb30-fbconf-auth,AuthClient>>
|<<rnfb30-engine-providers,Providers>>
|{nbsp}

3+d|_The following parameters can be configured *only* via the DPB/SPB_

|ConnectionTimeout
|DummyPacketInterval
|IpcName

|RemoteAuxPort
|RemotePipeName
|RemoteServiceName

|RemoteServicePort
|TCPNoNagle
|{nbsp}
|===

[[rnfb3-fbconf-newparams]]
== New Parameters

New parameters added to `firebird.conf` are:

[[rnfb30-fbconf-securitydatabase]]
=== SecurityDatabase

Defines the name and location of the security database that stores login user names and passwords used by the server to validate remote connections.
By default, in `firebird.conf`, it is `$(root)/security3.fdb`.
It can be overridden for a specific database by a configuration in `databases.conf`.

[[rnfb30-fbconf-auth]]
=== AuthServer and AuthClient

Two parameters that determine what authentication methods can be used by the network server and the client redirector.
The enabled methods are listed as string symbols separated by commas, semicolons or spaces.

* Secure remote passwords (`Srp`), using the plug-in is the default, using the OS-appropriate plug-in (`libSrp.s0`/`Srp.dll`/`Srp.dylib`)
* On Windows, the Security Support Provider Interface (`Win_Sspi`) is used when no login credentials are supplied
* Client applications can use legacy authentication (`Legacy_Auth`) to talk to old servers.

For `AuthServer`, `Srp` and `Win_Sspi` are listed;
for `AuthClient`, `Srp`, `Win_Sspi` and `Legacy_Auth`.

To disable a method, erase the comment marker ('```#```') and remove the unwanted method from the list.

Both parameters can be used in `databases.conf`.
They can both be used in the DPB or the SPB for a connection-specific configuration.

[[rnfb30-fbconf-wirecrypt]]
=== WireCrypt

Sets whether the network connection should be encrypted.
It has three possible values: `Required` | `Enabled` | `Disabled`.
The default is set such that encryption is `Required` for connections coming in to the server and `Enabled` for connections outgoing to a server.

To access a server using an older client library and, thus, no encryption, `WireCrypt` in the server configuration file should be set to `Enabled` or `Disabled` to avert the default `Required`.

The rules are simple: if one side has `WireCrypt = Required` and the other sets the parameter to `Disabled`, the side with `WireCrypt=Required` rejects the connection and it is not established.

A missing `WireCrypt` plug-in or encryption key in cases where the channel must be encrypted also thwarts a connection.

In all other cases, connection is established without encryption if at least one side has `WireCrypt = Disabled`.
In other cases, the encrypted connection is established.

[[rnfb30-fbconf-usermanager]]
=== UserManager

Sets the plug-in that will operate on the security database.
It can be a list with blanks, commas or semicolons as separators: the first plug-in from the list is used as the default.

The default plug-in is `Srp` (`libSrp.s0`/`Srp.dll`/`Srp.dylib`).

The UserManager parameter can be used in `databases.conf` for a database-specific override.

[[rnfb30-fbconf-traceplugin]]
=== TracePlugin

Specifies the plug-in used by Firebird's Trace facility to send trace data to the client app or audit data to the log file.

The default plug-in is `fbtrace` (`libfbtrace.s0`/`fbtrace.dll`/`fbtrace.dylib`).

[[rnfb30-fbconf-cryptplugin]]
=== WireCryptPlugin

A wire-crypt plug-in is used to encrypt and decrypt data transferred over the network.

The installation default `Arc4` implies use of an *Alleged RC4* plug-in.
The configured plug-in, which requires a key generated by the configured authentication plug-in, can be overridden in the API for a specific connection via the DPB or the SPB.

[TIP]
====
For information about configuring plug-ins, see <<rnfb30-config-plugins,Configuring Plug-ins>> in the <<rnfb30-engine,Engine>> chapter.
====

[[rnfb30-fbconf-keyholder]]
=== KeyHolderPlugin

This parameter would represent some form of temporary storage for database encryption keys.
Nothing is implemented as a default plug-in, but a sample Linux plug-in named `libCryptKeyHolder_example.so` can be found  in `/plugins/`.

[[rnfb30-fbconf-providers]]
=== Providers

List of allowed transports for accessing databases, discussed in <<rnfb30-engine-providers,the Engine chapter>>.

[[rnfb30-fbconf-shared]]
=== ServerMode

Determines the execution mode of the server ("`server model`").
Discussed in <<rnfb30-engine-modes,the Engine chapter>>.

[[rnfb30-fbconf-remoteaccess]]
=== RemoteAccess

Parameter in `firebird.conf` and `databases.conf` provides an efficient, configurable replacement for hard-coded rules limiting access to `security3.fdb`.
It can also be used to configure limited remote access to any other database, including non-default security databases.

By default `RemoteAccess` is enabled for all databases except the security database.
If you intend using more than one dedicated security database, then disabling remote access to it (or them) via `databases.conf` is recommended.

For stricter security, server-wide, you can set `RemoteAccess` to false in `firebird.conf` and use entries in `database.conf` to re-enable it for specific databases.

_RemoteAccess_ is a Boolean.
It can be expressed with either true/false, 1/0 or Yes/No.

[[rnfb30-fbconf-wirecompression]]
=== WireCompression
Alex Peshkov

Parameter in `firebird.conf` or `databases.conf`, enabling or disabling compression of data over the wire at global or individual database level.

The default setting is disabled (= False).
Settings and environment must be correct at both server and client for `WireCompression` to take effect:

* To enable it at the server side, in `firebird.conf` and/or `databases.conf`, change the setting to True
* To activate `Wirecompression` from the client side, pass the appropriate tag in the config item of the DPB or SPB call:
+
[source]
----
isc_dbp_config/isc_sbp_config <string-length> "WireCompression=true"
----
* Both server and client versions must be Firebird 3 or greater (protocol >=13)

See Tracker item http://tracker.firebirdsql.org/browse/CORE-733[CORE-733]. 

[[rnfb30-fbconf-ipv6only]]
=== IPv6V6Only
Michael Kubecek

Parameter in `firebird.conf` only.
(TCP ports are created before any connection is established.)

Firebird 3 supports IPv6 connections, on both client and server sides.

[[rnfb30-fbconf-ipv6only-server]]
==== Server

By default, the Firebird server listens on the zero IPv6 address (`::`) and accepts all incoming connections, whether IPv4 or IPv6, and `IPv6V6Only` is set to false (=0).
If it is set to true, the server, still listening implicitly or explicitly on the zero IPv6 address, will accept only IPv6 connections.

[NOTE]
====
A different listening address, either IPv4 or IPv6, can be set using the `RemoteBindAddress` parameter.
If an IPv4 address or a non-zero IPv6 address is used, the `IPv6V6Only` directive has no effect.

On POSIX platforms, in Classic mode, the parameters `RemoteBindAddress`, `RemoteServicePort` and `RemoteServiceName` are ignored by `fbserver`, since the listening socket is set up by `(x)inetd`.
The listening address and/or port need to be set in the `(x)inetd`.
====

_IPv6V6Only_ is a Boolean.
It can be expressed with either true/false, 1/0 or Yes/No.

[[rnfb30-fbconf-ipv6only-client]]
==== Client

The standard text form of an IPv6 address uses the colon character to separate groups of digits (upto 8 groups of digits).
In the connection string, the IPv6 address must be enclosed in square brackets, to resolve the ambiguity with the use of the colon as the separator between the host IP address and the database path.
For example:

[source]
----
connect '[2014:1234::5]:test';
connect '[2014:1234::5]/3049:/srv/firebird/test.fdb';
----

[NOTE]
====
For consistency, square brackets can be optionally used around an IPv4 address or a domain name.

If a domain name is used in connection string, all addresses (IPv4 and IPv6) are tried in the order returned by resolver until a connection is established.
If all attempts fail, the client fails to connect.
====

[[rnfb30-fbconf-changed-params]]
== Parameters Changed or Enhanced

The following parameters have been changed or enhanced:

[[rnfb30-fbconf-changed-extfileaccess]]
=== ExternalFileAccess

Entries in the "```Restrict```" list of the `ExternalFileAccess` parameter can be used to mangle file names with relative paths.

Entries in the "```Restrict```" list were already used to mangle file names with no path component.
For example, with 

[source]
----
ExternalFileAccess = /opt/extern
----

and the following sequence of commands:

[source]
----
SQL> create table qq external file 'zz' (x int);
SQL> insert into qq values(1);
SQL> commit;
----

the file /opt/extern/zz will be created.

However, if something like this is submitted,

[source]
----
create table qq external file 'dir/zz' (x int);
----

the result is an error about denied access to file /opt/firebird/bin/dir/zz.

The improvement avoids this gap by mangling the file name in accord with the value of the parameter and, if necessary, creating the missing path components, such as 'dir' in the example above.

[[rnfb30-fbconf-removed]]
== Parameters Removed or Deprecated

The following parameters have been removed or deprecated:

[[rnfb30-fbconf-removed-rootdir]]
=== RootDirectory

In older version, this parameter provided a superfluous option for recording the file system path to Firebird's "`root`" files (`firebird.conf`, the security database and so on).

[[rnfb30-fbconf-removed-leghash]]
=== LegacyHash

This parameter used to make it possible to use the old `security.fdb` from Firebird 1.X installations after it had been subjected to an upgrade script and thence to enable or disable use of the obsolete DES hash encrypting algorithm.
It is no longer supported.

[[rnfb30-fbconf-removed-oldset]]
=== OldSetClauseSemantics

This parameter enabled temporary support for an implementation fault in certain sequences of `SET` clauses in versions of Firebird prior to version 2.5.
It is no longer available.

[[rnfb30-fbconf-removed-oldcolnam]]
=== OldColumnNaming

This parameter temporarily enabled legacy code support for an old InterBase/Firebird 1.0 bug that generated unnamed columns for computed output which was not explicitly aliased in the `SELECT` specification.
It is no longer available.

[[rnfb30-fbconf-removed-lockorder]]
=== LockGrantOrder

This parameter used to allow the option to have Firebird's Lock Manager emulate InterBase v3.3 lock allocation behaviour, whereby locks would be granted in no particular order, as soon as they were available, rather than by the normal order (first-come, first-served).
The legacy option is no longer supported.

[[rnfb30-fbconf-removed-winprio]]
=== Obsolete Windows priority settings

`UsePriorityScheduler`, `PrioritySwitchDelay` and `PriorityBoost`, which were marginally relevant to obsolete processors on obsolete Windows versions, are no longer supported.
