[[rnfb30-ddl]]
= Data Definition Language (DDL)

[[rnfb30-ddl-links]]
== Quick Links

* <<rnfb30-ddl-boolean>>
* <<rnfb30-ddl-identity>>
* <<rnfb30-ddl-managenull>>
* <<rnfb30-ddl-altersequence>>
* <<rnfb30-ddl-alterdftcharset>>
* <<rnfb30-ddl-blobscomputed>>
* <<rnfb30-ddl-enhance-linger>>
* New option in `DROP SHADOW` to <<rnfb3-ddl-dropshadow,Preserve the Shadow File>>
* <<rnfb3-ddl-users-and-privs>>

[[rnfb30-ddl-enhance]]
== DDL Enhancements

The following enhancements have been added to the SQL data definition language lexicon:

[[rnfb30-ddl-enhance-datatype]]
=== New Data Types

A fully-fledged `BOOLEAN` type is introduced in this release, along with a surfaced emulation of the SQL standard "`identity`" column.

[[rnfb30-ddl-boolean]]
==== BOOLEAN Data Type
Adriano dos Santos Fernandes

The SQL:2008 compliant `BOOLEAN` data type (8 bits) comprises the distinct truth values `TRUE` and `FALSE`.
Unless prohibited by a `NOT NULL` constraint, the `BOOLEAN` data type also supports the truth value `UNKNOWN` as the null value.
The specification does not make a distinction between the `NULL` value of this data type and the truth value `UNKNOWN` that is the result of an SQL predicate, search condition, or Boolean value expression: they may be used interchangeably to mean exactly the same thing.

As with many programming languages, the SQL `BOOLEAN` values can be tested with implicit truth values.
For example, `field1 OR field2` and `NOT field1` are valid expressions.

[[rnfb30-ddl-boolean-is]]
===== The IS Operator

Predicates can use the operator `IS [NOT]` for matching.
For example, `field1 IS FALSE`, or `field1 IS NOT TRUE`.

[NOTE]
====
Equivalence operators ("```=```", "```!=```", "```<>```" and so on) are valid in all comparisons.
====

[[rnfb30-ddl-boolean-example]]
===== BOOLEAN Examples

[source]
----
CREATE TABLE TBOOL (ID INT, BVAL BOOLEAN);
COMMIT;

INSERT INTO TBOOL VALUES (1, TRUE);
INSERT INTO TBOOL VALUES (2, 2 = 4);
INSERT INTO TBOOL VALUES (3, NULL = 1);
COMMIT;

SELECT * FROM TBOOL
          ID    BVAL
============ =======
           1 <true>
           2 <false>
           3 <null>

-- Test for TRUE value
SELECT * FROM TBOOL WHERE BVAL
          ID    BVAL
============ =======
           1 <true>

-- Test for FALSE value
SELECT * FROM TBOOL WHERE BVAL IS FALSE
          ID    BVAL
============ =======
           2 <false>

-- Test for UNKNOWN value
SELECT * FROM TBOOL WHERE BVAL IS UNKNOWN
          ID    BVAL
============ =======
           3 <null>

-- Boolean values in SELECT list
SELECT ID, BVAL, BVAL AND ID < 2
  FROM TBOOL
          ID    BVAL
============ ======= =======
           1 <true>  <true>
           2 <false> <false>
           3 <null>  <false>

-- PSQL Declaration with start value
DECLARE VARIABLE VAR1 BOOLEAN = TRUE;

-- Valid syntax, but as with a comparison
-- with NULL, will never return any record
SELECT * FROM TBOOL WHERE BVAL = UNKNOWN
SELECT * FROM TBOOL WHERE BVAL <> UNKNOWN
----

[[rnfb30-ddl-boolean-othertypes]]
===== Use of Boolean against other data types

Although `BOOLEAN` is not inherently convertible to any other datatype, from version 3.0.1 the strings `'true'` and `'false'` (case-insensitive) will be implicitly cast to `BOOLEAN` in value expressions, e.g.

[source]
----
if (true > 'false') then ...
----

`'false'` is converted to `BOOLEAN`.
An attempt use the Boolean operators `AND`, `NOT`, `OR` and `IS` will fail.
`NOT 'False'`, for example, is invalid.

A `BOOLEAN` can be explicitly converted to and from string with `CAST`.
`UNKNOWN` is not available for any form of casting.

.Other Notes
[NOTE]
====
* Represented in the API with the `FB_BOOLEAN` type and `FB_TRUE` and `FB_FALSE` constants.
* The value `TRUE` is greater than the value `FALSE`.
====

[[rnfb30-ddl-booleansreserved]]
===== Keywords INSERTING, UPDATING and DELETING

To avoid ambiguities when used in Boolean expressions, the previously non-reserved keywords `INSERTING`, `UPDATING` and `DELETING`, which return True or False when tested in PSQL, have been made reserved words in all contexts.
If you have used any of these words as identifiers for database objects, columns, variables or parameters, it will be necessary to redefine them, either with new names or by enclosing these identifiers in double quotes.

[[rnfb30-ddl-identity]]
==== Identity Column Type
Adriano dos Santos Fernandes

An identity column is a column associated with an internal sequence generator.
Its value is set automatically when the column is omitted in an `INSERT` statement.

[float]
===== Syntax

[listing,subs=+quotes]
----
<column definition> ::=
  _name_ <type> GENERATED BY DEFAULT AS IDENTITY [ (START WITH _value_) ] <constraints>
----

When defining a column, the optional `START WITH` clause allows the generator to be initialised to a value other than zero.
See Tracker ticket http://tracker.firebirdsql.org/browse/CORE-4199[CORE-4199].

[listing,subs=+quotes]
----
<alter column definition> ::=
  _name_ RESTART [ WITH _value_ ]
----

A column definition can be altered to modify the starting value of the generator.
`RESTART` alone resets the generator to zero;
the optional `WITH _value_` clause allows the restarted generator to start at a value other than zero.
See Tracker ticket http://tracker.firebirdsql.org/browse/CORE-4206[CORE-4206].

[float]
===== Rules

* The data type of an identity column must be an exact number type with zero scale.
Allowed types are thus `SMALLINT`, `INTEGER`, `BIGINT`, `NUMERIC(x,0)` and `DECIMAL(x,0)`.
* An identity column cannot have `DEFAULT` or `COMPUTED` value.

[NOTE]
====
* An identity column cannot be altered to become a regular column.
The reverse is also true.
* Identity columns are implicitly `NOT NULL` (non-nullable).
* Uniqueness is not enforced automatically.
A `UNIQUE` or `PRIMARY KEY` constraint is required to guarantee uniqueness.
* The use of other methods of generating key values for `IDENTITY` columns, e.g. by trigger-generator code or by allowing users to change or add them, is discouraged to avoid unexpected key violations.
====

.Example
[source]
----
create table objects (
  id integer generated by default as identity primary key,
  name varchar(15)
);

insert into objects (name) values ('Table');
insert into objects (name) values ('Book');
insert into objects (id, name) values (10, 'Computer');

select * from objects;

          ID NAME
============ ===============
           1 Table
           2 Book
          10 Computer
----

[[rnfb30-ddl-identity-impl]]
===== Implementation Details

Two new columns have been inserted in `RDB$RELATION_FIELDS` to support identity columns: `RDB$GENERATOR_NAME` and `RDB$IDENTITY_TYPE`.

* `RDB$GENERATOR_NAME` stores the automatically created generator for the column.
In `RDB$GENERATORS`, the value of `RDB$SYSTEM_FLAG` of that generator will be 6.
* Currently, `RDB$IDENTITY_TYPE` will currently always store the value `1` (for `BY DEFAULT`) for identity columns and `NULL` for non-identity columns.
In the future this column will store the value `0`, too (for `ALWAYS`) when Firebird implements support for this type of identity column.

[[rnfb30-ddl-managenull]]
=== Manage Nullability in Domains and Columns
Adriano dos Santos Fernandes

`ALTER` syntax is now available to change the nullability of a table column or a domain

.Syntax
[listing,subs=+quotes]
----
ALTER TABLE _table-name_ ALTER _field-name_ { DROP | SET } [NOT] NULL

ALTER DOMAIN _domain-name_ { DROP | SET } [NOT] NULL
----

[NOTE]
====
The success of a change in a table column from `NULL` to `NOT NULL` is subject to a full data validation on the table, so ensure that the column has no nulls before attempting the change.

A change in a domain subjects all the tables using the domain to validation.

An explicit `NOT NULL` on a column that depends on a domain prevails over the domain.
In this situation, the changing of the domain to make it nullable does not propagate to the column.
====

[[rnfb30-ddl-altersequence]]
=== Modify Generators (Sequences)
Adriano dos Santos Fernandes; Dmitry Yemanov

More statement options have been added for modifying generators (sequences).
Where previously in SQL the only option was `ALTER SEQUENCE <sequence name> RESTART WITH <value>`, now a full lexicon is provided and `GENERATOR` and `SEQUENCE` are synonyms for the full range of commands.

`RESTART` can now be used on its own to restart the sequence at its previous start or restart value.
A new column `RDB$INITIAL_VALUE` is added to the system table `RDB$GENERATORS` to store that value.

A generator (sequence) can also be [re]created or altered to include an optional "`step`" clause to make the generator increment the series by two or more steps instead of the default 1.
The clause is implemented as `INCREMENT BY _number_` and is stored in `RDB$GENERATORS` in `RDB$GENERATOR_INCREMENT`.

.Syntax
[listing,subs=+quotes]
----
{ CREATE | RECREATE } { SEQUENCE | GENERATOR } _sequence-name_ [ START WITH _value_ ]
   [ INCREMENT BY _number_ ]

CREATE OR ALTER { SEQUENCE | GENERATOR } _sequence-name_ { RESTART | START WITH _value_ }
   [ INCREMENT BY _number_ ]

ALTER { SEQUENCE | GENERATOR } <sequence name> RESTART [ WITH _value_ ]
   [ INCREMENT BY _number_ ]
----

.Function GEN_ID()
[NOTE]
====
The legacy function `GEN_ID(generator_name, step_value))` still  works to set a one-time step value in its second argument.
If it is used, the stored `RDB$GENERATOR_INCREMENT` value is overridden.
====

[[rnfb30-ddl-alterdftcharset]]
=== Alter the Default Character Set
Adriano dos Santos Fernandes

[listing,subs=+quotes]
----
ALTER DATABASE
  ...
  SET DEFAULT CHARACTER SET <new_charset>
----

The alteration does not change any existing data.
The new default character set is used only in subsequent DDL commands and will assume the default collation of the new character set.

[[rnfb30-ddl-blobscomputed]]
=== BLOB Expressions in Computed Columns
Adriano dos Santos Fernandes

A substring from a `BLOB` column can now be used to define a computed column.

.Example
[source]
----
ALTER TABLE ATABLE
  ADD ABLOB
  COMPUTED BY (SUBSTRING(BLOB_FIELD FROM 1 FOR 20))
----

[[rnfb30-ddl-enhance-linger]]
=== "`Linger`" Database Closure for Superserver
Alex Peshkov

Sometimes it is desirable to have the Superserver engine keep the database open for a period after the last attachment is closed, i.e. to have it "`linger`" a while.
It can help to improve performance at low cost, under conditions where the database is opened and closed frequently, by keeping resources "`warm`" for next time it is reopened.

Firebird 3.0 introduces an enhancement to `ALTER DATABASE` to manage this optional `LINGER` capability for databases running under Superserver.

.Syntax
[listing,subs=+quotes]
----
ALTER DATABASE SET LINGER TO _seconds_;
ALTER DATABASE DROP LINGER;
----

[float]
==== Usage

To set linger for the database do:

[source]
----
ALTER DATABASE SET LINGER TO 30; -- sets linger interval to 30 seconds
----

Either of the following forms will clear the linger setting and return the database to the normal condition (no linger):

[source]
----
ALTER DATABASE DROP LINGER;
ALTER DATABASE SET LINGER TO 0;
----

[NOTE]
====
Dropping `LINGER` is not an ideal solution for the occasional need to turn it off for some once-only condition where the server needs a forced shutdown.
The _gfix_ utility now has the `-NoLinger` switch, which will close the specified database immediately after the last attachment is gone, regardless of the `LINGER` setting in the database.
The `LINGER` setting is retained and works normally the next time.

The same one-off override is also available through the Services API, using the tag `isc_spb_prp_nolinger`, e.g. (in one line):

[source]
----
fbsvcmgr host:service_mgr user sysdba password xxx
       action_properties dbname employee prp_nolinger
----
====

See also Tracker ticket http://tracker.firebirdsql.org/browse/CORE-4263[CORE-4263] for some discussion of the development of this feature.

[[rnfb3-ddl-dropshadow]]
=== Option to Preserve Shadow File
Alex Peshkov

The `DROP SHADOW` command has a new option to preserve the shadow file in the filesystem: 

[listing,subs=+quotes]
----
DROP SHADOW _shadow_num_
  [{DELETE | PRESERVE} FILE]
----

See Tracker ticket http://tracker.firebirdsql.org/browse/CORE-4955[CORE-4955].

[[rnfb3-ddl-users-and-privs]]
=== New SQL for Managing Users and Access Privileges

A number of new features and enhancements have been added to the DDL lexicon for managing users and their access to objects in databases.
They are <<rnfb30-access-sql,described in detail>> in Chapter 7, Security.

[[rnfb3-ddl-enhance-users]]
==== <<rnfb30-user-sql,SQL-driven User Management>>

The SQL set of DDL commands for managing user accounts has been enhanced in Firebird 3, thus improving the capability to manage (add, modify or delete) users in a security database from a regular database attachment.

._gsec_ is deprecated!
[IMPORTANT]
====
The command-line and shell utility _gsec_ is deprecated from this release forward.
It will continue to work with `security3.fdb`, but it will not work with alternative security databases.
====

[[rnfb3-ddl-setrole]]
==== <<rnfb3-security-setrole, SET ROLE>> and <<rnfb3-security-settrustedrole,SET TRUSTED ROLE>>

The SQL:2008-compliant operator `SET ROLE` allows the `CURRENT_ROLE` context variable to be set to one that has been granted to the `CURRENT_USER` or to a user assigned to the database attachment as trusted (`SET TRUSTED ROLE`).

[[rnfb3-ddl-grantedby]]
==== <<rnfb30-security-grantedby, GRANTED BY Clause for Privileges>>

Previously, the grantor or revoker of SQL privileges was always the current user.
The `GRANTED BY` clause makes it so that a different grantor or revoker can be specified in `GRANT` and `REVOKE` commands.

[[rnfb3-ddl-revoke-all]]
==== <<rnfb30-security-revokeall, REVOKE ALL ON ALL>>

When a user is removed from the security database or another authentication source, this new command is useful for revoking its access to all objects in the database.

[[rnfb3-ddl-metadataprivs]]
==== <<rnfb30-security-metadataprivs, GRANT/REVOKE Metadata Privileges>>

In Firebird 3, the system tables are read-only.
This SQL syntax provides the means to assign metadata write privileges to specified users or roles for specified objects.

[[rnfb3-ddl-execute-udf]]
==== <<rnfb30-security-udfperms, EXECUTE Privileges for UDFs>>

`EXECUTE` permission is now supported for UDFs (both legacy and PSQL based ones).

[[rnfb3-ddl-grantusage]]
==== <<rnfb30-security-otherprivs, GRANT/REVOKE USAGE>>

New SQL:2008-compliant `USAGE` permission is introduced to protect metadata objects other than tables, views, procedures and functions.
