[[rnfb30-dml]]
= Data Manipulation Language (DML)

In this chapter are the additions and improvements that have been added to the SQL data manipulation language subset in Firebird 3.0.

[[rnfb30-dml-quicklinks]]
== Quick Links

* <<rnfb30-dml-merge>>
* <<rnfb30-dml-windowfuncs>>
* <<rnfb30-dml-planoutput>>
* <<rnfb30-dml-substring>>
* <<rnfb30-dml-hyperbolic>>
* <<rnfb30-dml-statistical>>
* <<rnfb30-dml-functions-dateadd>>
* <<rnfb30-dml-trim>>
* <<rnfb30-dml-altquoting>>
* <<rnfb30-dml-offsetfetch>>
* <<rnfb30-dml-mixjoins>>
* <<rnfb30-dml-leftparam>>
* <<rnfb30-dml-returningalias>>
* <<rnfb30-dml-returningcursor>>
* <<rnfb30-dml-curstability>>
* <<rnfb30-dml-gtt>>
* <<rnfb30-dml-validate>>
* <<rnfb30-dml-countresult>>
* <<rnfb30-dml-similarto,SIMILAR TO Performance Improvement>>
* <<rnfb30-dml-orparam>>
* <<rnfb30-dml-dialect1,A Little Dialect 1 Accommodation>>
* <<rnfb30-dml-esql>>

[[rnfb30-dml-merge]]
== Supplemental SQL:2008 Features for MERGE
Adriano dos Santos Fernandes

In summary, support for `MERGE` was supplemented with the introduction of these features:

* Addition of the `DELETE` extension (http://tracker.firebirdsql.org/browse/CORE-2005[CORE-2005])
* Enabling the use of multiple `WHEN MATCHED` | `WHEN NOT MATCHED` clauses (http://tracker.firebirdsql.org/browse/CORE-3639[CORE-3639]) and ability to apply conditions to `WHEN MATCHED` | `WHEN NOT MATCHED`
* Addition of the `RETURNING ... INTO ...` clause (http://tracker.firebirdsql.org/browse/CORE-3020[CORE-3020])

The purpose of `MERGE` is to read data from the source and `INSERT` or `UPDATE` in the target table according to a condition.
It is available in DSQL and PSQL.

.Syntax
[listing,subs=+quotes]
----
<merge statement> ::=
  MERGE
    INTO _table-or-view_ [ [AS] _correlation-name_ ]
    USING <table or view or derived-table> [ [AS] _correlation-name_ ]
    ON <condition>
    <merge when>...
    <returning clause>

<merge when> ::=
  <merge when matched> |
  <merge when not matched>

<merge when matched> ::=
  WHEN MATCHED [ AND <condition> ] THEN
    { UPDATE SET <assignment list> | DELETE }

<merge when not matched> ::=
  WHEN NOT MATCHED [ AND <condition> ] THEN
    INSERT [ <left paren> <column list> <right paren> ]
      VALUES <left paren> <value list> <right paren>
----

[float]
=== Rules

At least one of `<merge when matched>` or `<merge when not matched>` should be specified.

[float]
=== Example

[source]
----
MERGE INTO customers c
  USING
    (SELECT * FROM customers_delta WHERE id > 10) cd
     ON (c.id = cd.id)
  WHEN MATCHED THEN
    UPDATE SET name = cd.name
  WHEN NOT MATCHED THEN
    INSERT (id, name)
    VALUES (cd.id, cd.name)
----

[NOTE]
====
A right join is made between the `INTO` (left-side) and `USING` tables using the condition.
`UPDATE` is called when a record exists in the left table (`INTO`), otherwise `INSERT` is called.

As soon as it is determined whether or not the source matches a record in the target, the set formed from the corresponding (`WHEN MATCHED` / `WHEN NOT MATCHED`) clauses is evaluated in the order specified, to check their optional conditions.
The first clause whose condition evaluates to true is the one which will be executed, and the subsequent ones will be ignored.

If no record is returned in the join, `INSERT` is not called.
====

[[rnfb30-dml-windowfuncs]]
== Window (Analytical) Functions
Adriano dos Santos Fernandes

According to the SQL specification, window functions (also known as analytical functions) are a kind of aggregation, but one that does not "`filter`" the result set of a query.
The rows of aggregated data are mixed with the query result set.

The window functions are used with the `OVER` clause.
They may appear only in the `SELECT` list or the `ORDER BY` clause of a query.

Besides the `OVER` clause, Firebird window functions may be _partitioned_ and _ordered_.

.Syntax
[listing,subs=+quotes]
----
<window function> ::= <window function name> ([<expr> [, <expr> ...]]) OVER (
  [PARTITION BY <expr> [, <expr> ...]]
  [ORDER BY <expr> 
    [<direction>] 
    [<nulls placement>] 
    [, <expr> [<direction>] [<nulls placement>] ...]
)

<direction> ::= {ASC | DESC}

<nulls placement> ::= NULLS {FIRST | LAST}
----

[[rnfb30-dml-windowfuncs-aggregates]]
=== Aggregate Functions Used as Window Functions

All aggregate functions may be used as window functions, adding the `OVER` clause.

Imagine a table `EMPLOYEE` with columns `ID`, `NAME` and `SALARY`, and the need to show each employee with his respective salary and the percentage of his salary over the payroll.

A normal query could achieve this, as follows:

[source]
----
select
    id,
    department,
    salary,
    salary / (select sum(salary) from employee) portion
  from employee
  order by id;
----

.Results
[source]
----
id  department  salary  portion
--  ----------  ------  ----------
1   R & D        10.00      0.2040
2   SALES        12.00      0.2448
3   SALES         8.00      0.1632
4   R & D         9.00      0.1836
5   R & D        10.00      0.2040
----

The query is repetitive and lengthy to run, especially if `EMPLOYEE` happens to be a complex view.

The same query could be specified in a much faster and more elegant way using a window function:

[source]
----
select
    id,
    department,
    salary,
    salary / sum(salary) OVER () portion
  from employee
  order by id;
----

Here, `sum(salary) over ()` is computed with the sum of all `SALARY` from the query (the `EMPLOYEE` table).

[[rnfb30-dml-windowfuncs-partition]]
=== Partitioning

Like aggregate functions, that may operate alone or in relation to a group, window functions may also operate on a group, which is called a "`partition`".

.Syntax
[listing,subs=+quotes]
----
<window function>(...) OVER (PARTITION BY <expr> [, <expr> ...])
----

Aggregation over a group could produce more than one row, so the result set generated by a partition is joined with the main query using the same expression list as the partition.

Continuing the `EMPLOYEE` example, instead of getting the portion of each employee's salary over the all-employees total, we would like to get the portion based on just the employees in the same department:

[source]
----
select
    id,
    department,
    salary,
    salary / sum(salary) OVER (PARTITION BY department) portion
  from employee
  order by id;
----

.Results
[source]
----
id  department  salary  portion
--  ----------  ------  ----------
1   R & D        10.00      0.3448
2   SALES        12.00      0.6000
3   SALES         8.00      0.4000
4   R & D         9.00      0.3103
5   R & D        10.00      0.3448
----

[[rnfb30-dml-windowfuncs-order-by]]
=== Ordering

The `ORDER BY` sub-clause can be used with or without partitions and, with the standard aggregate functions, make them return the partial aggregations as the records are being processed.

.Example
[source]
----
select
    id,
    salary,
    sum(salary) over (order by salary) cumul_salary
  from employee
  order by salary;
----

.Results
[source]
----
id  salary  cumul_salary
--  ------  ------------
3     8.00          8.00
4     9.00         17.00
1    10.00         37.00
5    10.00         37.00
2    12.00         49.00
----

Then `cumul_salary` returns the partial/accumulated (or running) aggregation (of the `SUM` function).
It may appear strange that 37.00 is repeated for the ids 1 and 5, but that is how it should work.
The `ORDER BY` keys are grouped together and the aggregation is computed once (but summing the two 10.00).
To avoid this, you can add the `ID` field to the end of the `ORDER BY` clause.

It's possible to use multiple windows with different orders, and `ORDER BY` parts like `ASC`/`DESC` and `NULLS FIRST/LAST`.

With a partition, `ORDER BY` works the same way, but at each partition boundary the aggregation is reset.

All aggregation functions, other than `LIST()`, are usable with `ORDER BY`.

[[rnfb30-dml-windowfuncs-exclusivefuncs]]
=== Exclusive window functions

Beyond aggregate functions are the exclusive window functions, currently divided into _ranking_ and _navigational_ categories.
Both sets can be used with or without partition and ordering, although the usage does not make much sense without ordering.

[[rnfb30-dml-windowfuncs-ranking]]
==== Ranking Functions

The ranking functions compute the ordinal rank of a row within the window partition.
In this category are the functions `DENSE_RANK`, `RANK` and `ROW_NUMBER`.

.Syntax
[listing]
----
<ranking window function> ::=
  DENSE_RANK() |
  RANK() |
  ROW_NUMBER()
----

The ranking functions can be used to create different type of incremental counters.
Consider `SUM(1) OVER (ORDER BY SALARY)` as an example of what they can do, each of them in a different way.
Following is an example query, also comparing with the `SUM` behavior.

[source]
----
select
    id,
    salary,
    dense_rank() over (order by salary),
    rank() over (order by salary),
    row_number() over (order by salary),
    sum(1) over (order by salary)
  from employee
  order by salary;
----

.Results
[source]
----
id  salary  dense_rank  rank  row_number  sum
--  ------  ----------  ----  ----------  ---
3     8.00           1     1           1    1
4     9.00           2     2           2    2
1    10.00           3     3           3    4
5    10.00           3     3           4    4
2    12.00           4     5           5    5
----

The difference between `DENSE_RANK` and `RANK` is that there is a gap related to duplicate rows (relative to the window ordering) only in `RANK`.
`DENSE_RANK` continues assigning sequential numbers after the duplicate salary.
On the other hand, `ROW_NUMBER` always assigns sequential numbers, even when there are duplicate values.

[[rnfb30-dml-windowfuncs-navigational]]
==== Navigational Functions

The navigational functions get the simple (non-aggregated) value of an expression from another row of the query, within the same partition.

.Syntax
[listing]
----
<navigational window function> ::=
  FIRST_VALUE(<expr>) |
  LAST_VALUE(<expr>) |
  NTH_VALUE(<expr>, <offset>) [FROM FIRST | FROM LAST] |
  LAG(<expr> [ [, <offset> [, <default> ] ] ) |
  LEAD(<expr> [ [, <offset> [, <default> ] ] )
----

.Important to Note
[IMPORTANT]
====
`FIRST_VALUE`, `LAST_VALUE` and `NTH_VALUE` also operate on a window frame.
Currently, Firebird always frames from the first to the current row of the partition, not to the last.
This is likely to produce strange results for `NTH_VALUE` and especially `LAST_VALUE`.
====

.Example
[source]
----
select
    id,
    salary,
    first_value(salary) over (order by salary),
    last_value(salary) over (order by salary),
    nth_value(salary, 2) over (order by salary),
    lag(salary) over (order by salary),
    lead(salary) over (order by salary)
  from employee
  order by salary;
----

.Results
[source]
----
id  salary  first_value  last_value  nth_value     lag    lead
--  ------  -----------  ----------  ---------  ------  ------
3     8.00         8.00        8.00     <null>  <null>    9.00
4     9.00         8.00        9.00       9.00    8.00   10.00
1    10.00         8.00       10.00       9.00    9.00   10.00
5    10.00         8.00       10.00       9.00   10.00   12.00
2    12.00         8.00       12.00       9.00   10.00  <null>
----

`FIRST_VALUE` and `LAST_VALUE` get, respectively, the first and last value of the ordered partition.

`NTH_VALUE` gets the _n_-th value, starting from the first (default) or the last record, from the ordered partition.
An offset of 1 from first would be equivalent to `FIRST_VALUE`;
an offset of 1 from last is equivalent to `LAST_VALUE`.

`LAG` looks for a preceding row, and `LEAD` for a following row.
`LAG` and `LEAD` get their values within a distance respective to the current row and the offset (which defaults to 1) passed.

In a case where the offset points outside the partition, the default parameter (which defaults to `NULL`) is returned.

[[rnfb30-dml-planoutput]]
== Advanced Plan Output
Dmitry Yemanov

PLAN output can now be output in a more structured and comprehensible form, e.g.

[listing]
----
SELECT statement
   -> First [10]
     -> Sort [SUM, O_ORDERDATE]
       -> Aggregate
         -> Sort [L_ORDERKEY, O_ORDERDATE, O_SHIPPRIORITY]
           -> Inner Loop Join
             -> Filter
               -> Table ≪ORDERS≫ Access By ID
                 -> Bitmap
                   -> Index ≪ORDERS_ORDERDATE≫ Range Scan
             -> Filter
               -> Table ≪CUSTOMER≫ Access By ID
                 -> Bitmap
                   -> Index ≪CUSTOMER_PK≫ Unique Scan
             -> Filter
               -> Table ≪LINEITEM≫ Access By ID
                 -> Bitmap
                   -> Index ≪LINEITEM_PK≫ Unique Scan
----

[[rnfb30-dml-planoutput-isql]]
=== Advanced PLAN Output in isql

New syntax `SET EXPLAIN [ON | OFF ]` has been added to the _isql_ utility to surface this option.
For details, refer to <<rnfb30-util-isql-setexplain,SET EXPLAIN Extensions for Viewing Detailed Plans>> in the <<rnfb30-util,Utilities>> chapter.

[[rnfb30-dml-internal-functions]]
== Internal Functions

Additions and enhancements to the internal functions set are:

[[rnfb30-dml-substring]]
=== SUBSTRING with Regular Expressions
Adriano dos Santos Fernandes

A substring search can now use a regular expression.

.Search Pattern
[listing]
----
SUBSTRING(<string> [NOT] SIMILAR TO <pattern> ESCAPE <char>)
----

Discussion: Tracker http://tracker.firebirdsql.org/browse/CORE-2006[CORE-2006]

For more information about the use of `SIMILAR TO` expressions, refer to `README.similar_to.txt` in the /doc/ subdirectory of your Firebird installation.

[TIP]
====
The regex used is the SQL one  -- the same one that is used for Firebird's `SIMILAR TO` searches.
A guide is available in the https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref25/firebird-25-language-reference.html#fblangref25-commons-predsiimilarto[Common Language Elements] chapter of the Firebird 2.5 Language Reference, and in the DML chapter of the version 2.5 release notes available at the https://www.firebirdsql.org/file/documentation/release_notes/html/en/2_5/rnfb25-dml.html#rnfb25-dml-regex[Firebird web site].
====

[[rnfb30-dml-hyperbolic]]
=== Inverse Hyperbolic Trigonometric Functions
Claudio Valderrama C.

The six inverse hyperbolic trigonometric functions have been implemented internally.
They are:

ACOSH::
Returns the hyperbolic arc cosine of a number (expressed in radians).
Format: `ACOSH( <number> )`

ASINH::
Returns the hyperbolic arc sine of a number (expressed in radians).
Format: `ASINH( <number> )`

ATANH::
Returns the hyperbolic arc tangent of a number (expressed in radians).
Format: `ATANH( <number> )`

COSH::
Returns the hyperbolic cosine of an angle (expressed in radians).
Format: `COSH( <number> )`

SINH::
Returns the hyperbolic sine of an angle (expressed in radians).
Format: `SINH( <number> )`

TANH::
Returns the hyperbolic tangent of an angle (expressed in radians).
Format: `TANH( <number> )`

[[rnfb30-dml-statistical]]
=== Statistical Functions
Hajime Nakagami; Adriano dos Santos Fernandes

A suite of SQL-standard-compliant statistical functions has been implemented.

[[rnfb30-dml-statistical-sd]]
==== Aggregate Statistical Functions

Functions comprise Sample Variance, Population Variance, Sample Standard Deviation, Population Standard Deviation, Sample Population, Population Covariance and Coefficient of Correlation.
See Tracker ticket http://tracker.firebirdsql.org/browse/CORE-4717[CORE-4717].

.Syntax
[listing]
----
<single param statistical function> ::= <single param statistical function name>(<expr>)
<single param statistical function name> := { VAR_POP | VAR_SAMP | STDDEV_POP | STDDEV_SAMP }

<dual param statistical function> ::= <dual param statistical function name>(<expr1>, <expr>>)
<dual param statistical function name> := { COVAR_POP | COVAR_SAMP | CORR }
----

.Semantics
[NOTE]
====
* `NULL` is returned from `VAR_SAMP`, `STDDEV_SAMP` or `COVAR_SAMP` if the result count is 0 or 1
* `NULL` is returned from `VAR_POP`, `STDDEV_POP`, `COVAR_POP` or `CORR` if the result count is 0
====

.Example
[source]
----
SELECT STDDEV_SAMP(salary) FROM employees;
----

.SD/Variance Function Descriptions
[[rnfb30-statistical01]]
[cols="2m,4m,6", options="header", stripes="none"]
|===
^| Function
^| Format
^| Description

|VAR_SAMP
|VAR_SAMP( <expr> )
|Returns the Sample Variance, equivalent to

3+|(SUM(<expr> ^ 2) - SUM(<expr>) ^ 2 / COUNT(<expr>)) / (COUNT(<expr>) - 1)

|VAR_POP
|VAR_POP( <expr> )
|Returns the the Population Variance, equivalent to

3+|(SUM(<expr> ^ 2) - SUM(<expr>) ^ 2 / COUNT(<expr>)) / COUNT(<expr>)

|STDDEV_SAMP
|STDDEV_SAMP( <expr> )
|Returns the Sample Standard Deviation, equivalent to

3+|SQRT(VAR_SAMP(<expr>))

|STDDEV_POP
|STDDEV_POP( <expr> )
|Returns the Population Standard Deviation, equivalent to

3+|SQRT(VAR_POP(<expr>))

|COVAR_SAMP
|COVAR_SAMP( <expr1>, <expr2> )
|Returns the Sample Population, equivalent to

3+|(SUM(<expr1> {asterisk} <expr2>) - SUM(<expr1>) {asterisk} SUM(<expr2>) / COUNT({asterisk})) / (COUNT({asterisk}) - 1)

|COVAR_POP
|COVAR_POP( <expr1>, <expr2> )
|Returns the Population Covariance, equivalent to

3+|(SUM(<expr1> {asterisk} <expr2>) - SUM(<expr1>) {asterisk} SUM(<expr2>) / COUNT({asterisk})) / COUNT({asterisk})

|CORR
|CORR( <expr1>, <expr2> )
|Returns the Coefficient of Correlation, equivalent to

3+|COVAR_POP(<expr1>, <expr2>) / (STDDEV_POP(<expr2>) {asterisk} STDDEV_POP(<expr1>))
|===

[[rnfb30-dml-statistical-regr]]
==== Linear Regression Functions

The suite of `REGR_{asterisk}` functions analyses the relationships between two sets of numeric data, considering only sets that are not `NULL` in either expression.
See Tracker ticket http://tracker.firebirdsql.org/browse/CORE-4722[CORE-4722].

.Syntax
[listing]
----
<regr function> ::= <function name>(<expr1>, <expr2>)
<function name> := { REGR_AVGX | REGR_AVGY | REGR_COUNT | REGR_INTERCEPT |
  REGR_R2 | REGR_SLOPE | REGR_SXX | REGR_SXY | REGR_SYY }
----

[float]
===== Formulae

The formulae use the following variables:

[listing]
----
Y: <expr1> (<expr1> IS NOT NULL AND <expr2> IS NOT NULL)
X: <expr2> (<expr1> IS NOT NULL AND <expr2> IS NOT NULL)
N: COUNT of recordset unless <expr1> IS NULL OR <expr2> IS NULL
----

[IMPORTANT]
====
`Y` and `X` are `DOUBLE PRECISION`.
`N` is `SMALLINT`, `INTEGER` or `BIGINT`.

All functions eliminate expression pairs where either expression in the pair is `NULL`.
If no rows remain, the functions (except `REGR_COUNT()`) return `NULL`.
====

.Linear Regression Function Descriptions
[[rnfb30-statistical02]]
[cols="2m,4m,6", options="header", stripes="none"]
|===
^| Function
^| Format
^| Description

|REGR_AVGX
|REGR_AVGX(Y, X)
|Returns the average of the independent expression (`Y`) in the expression pair.
The return value is of type `DOUBLE PRECISION`.

3+|REGR_AVGX(Y, X) = SUM(X) / N

|REGR_AVGY
|REGR_AVGY(Y, X)
|Returns the average of the dependent expression (`X`) in the expression pair.
The return value is of type `DOUBLE PRECISION`.

3+|REGR_AVGY(Y, X) = SUM(Y) / N

|REGR_COUNT
|REGR_COUNT(Y, X)
|Returns the number of expression pairs (`Y` and `X`).
The return value is of type `SMALLINT`, `INTEGER` or `BIGINT`.
If no rows remain after elimination of pairs where either expression is `NULL`, the function returns 0.

3+|REGR_COUNT(Y, X) = N

|REGR_INTERCEPT
|REGR_INTERCEPT(Y, X)
|Returns the y-intercept of the regression line determined by a set of expression pairs (`Y` and `X`).

3+|REGR_INTERCEPT(Y, X) = REGR_AVGY(Y, X) - REGR_SLOPE(Y, X) * REGR_AVGX(Y, X)

|REGR_R2
|REGR_R2(Y, X)
|Returns the square of the correlation coefficient of a set of expression pairs (`Y` and `X`).

3+|REGR_R2(Y, X) = POWER(CORR(Y, X),2)

|REGR_SLOPE
|REGR_SLOPE(Y, X)
|Returns the slope of the regression line, determined by a set of expression pairs (`Y` and `X`).

3+|REGR_SLOPE(Y, X) = COVAR_POP(Y, X) / VAR_POP(X)

|REGR_SXX
|REGR_SXX(Y, X)
|Returns the sum of squares of the independent expression (`Y`) in an expression pair (`Y` and `X`).

3+|REGR_SXX(Y, X) = N * VAR_POP(X)

|REGR_SXY
|REGR_SXY(Y, X)
|Returns the sum of products of the independent expression multiplied by the dependent expression in an expression pair (`Y` and `X`).

3+|REGR_SXY(Y, X) = N * COVAR_POP(Y, X)

|REGR_SYY
|REGR_SYY(Y, X)
|Returns the sum of squares of the dependent expression in an expression pair (`Y` and `X`).

3+|REGR_SYY(Y, X) = N * VAR_POP(Y)
|===

[[rnfb30-dml-trim]]
=== TRIM() BLOB Arguments Lose 32 KB limit
Adriano dos Santos Fernandes

In prior versions, `TRIM(substring FROM string)` allowed BLOBs for both arguments, but the first argument had to be smaller than 32 KB.
Now both arguments can take BLOBs of up to 4 GB.

[[rnfb30-dml-literalstring]]
=== String Literal Limit Adjustments
Adriano dos Santos Fernandes

The internal length of a string can, at some levels, be almost 64 KB.
Tests demonstrated that it is safe to accept a string literal of up to that size for writing to a text BLOB.
Accordingly, 

. The (32KB - 3) "`safety limit`" on literal string length for writing to text BLOBs has been raised to 65,533 bytes (64KB - 3);
. A limit, in characters, is calculated in run-time for strings that are in multi-byte character sets, to avoid overrunning the bytes limit.
For example, for a UTF8 string (max. 4 bytes/character) the run-time limit is likely to be about (floor (65533/4)) = 16383 _characters_.

See Tracker ticket http://tracker.firebirdsql.org/browse/CORE-4881[CORE-4881]. 

[[rnfb30-dml-functions-dateadd]]
=== Enhancements to DATEADD() Internal Function
Adriano dos Santos Fernandes

For the internal function `DATEADD()`

* The function now supports a fractional value for `MILLISECOND`.
See Tracker item http://tracker.firebirdsql.org/browse/CORE-4457[CORE-4457].
* the data type of input `<amount>` arguments has changed from `INTEGER` to `BIGINT`.
See Tracker item http://tracker.firebirdsql.org/browse/CORE-4310[CORE-4310].

[[rnfb30-dml-improve]]
== DML Improvements

A collection of useful DML improvements is released with Firebird 3.

[[rnfb30-dml-altquoting]]
=== Alternatives for Embedding Quotes in String Literals
Adriano dos Santos Fernandes

It is now possible to use a character, or character pair, other than the doubled (escaped) apostrophe, to embed a quoted string inside another string.
The keyword `q` or `Q` preceding a quoted string informs the parser that certain left-right pairs or pairs of identical characters within the string are the delimiters of the embedded string literal.

.Syntax
[listing]
----
<alternate string literal> ::=
    { q | Q } <quote> <alternate start char> [ { <char> }... ] <alternate end char> <quote>
----

.Rules
[NOTE]
====
When `<alternate start char>` is '```(```', '```{```', '```[```' or '```<```', `<alternate end char>` is paired up with its respective "`partner`", viz. '```)```', '```}```', '```]```' and '```>```'.
In other cases, `<alternate end char>` is the same as `<alternate start char>`.

Inside the string, i.e. `<char>` items, single (not escaped) quotes can be used.
Each quote will be part of the result string.
====

.Examples
[source]
----
select q'{abc{def}ghi}' from rdb$database;        -- result: abc{def}ghi
select q'!That's a string!' from rdb$database;    -- result: That's a string
----

[[rnfb30-dml-offsetfetch]]
=== SQL:2008-Compliant OFFSET and FETCH Clauses
Mark Rotteveel

New SQL:2008 compliant `OFFSET` and `FETCH` clauses provide a standard equivalent for `FIRST` and `SKIP`, and an alternative for `ROWS...TO`, when fetching sets from ordered output.

* The `OFFSET` clause specifies the number of rows to skip
* The `FETCH` clause specifies the number of rows to fetch.

As with `SKIP` and `FIRST`, `OFFSET` and `FETCH` clauses can be applied independently, in both top-level and nested query expressions.
They are available in PSQL and  DSQL.

.Syntax
[listing]
----
SELECT ... [ ORDER BY <expr_list> ]
  [ OFFSET <simple_value_expr> { ROW | ROWS } ]
  [ FETCH { FIRST | NEXT } [ <simple_value_expr> ] { ROW | ROWS } ONLY ]
----

`<simple_value_expr>` is a (numeric) literal, a DSQL parameter ('```?```') or a PSQL named parameter ("```:namedparameter```") that resolves to an integer data type.

.Examples
[source]
----
-- 1:
SELECT * FROM T1 ORDER BY COL1
  OFFSET 10 ROWS;
-- 2:
SELECT * FROM T1 ORDER BY COL1
  FETCH FIRST 10 ROWS ONLY;
-- 3:
SELECT * FROM (
    SELECT * FROM T1 ORDER BY COL1 DESC
    OFFSET 1 ROW
    FETCH NEXT 10 ROWS ONLY
  ) a
  ORDER BY a.COL1
  FETCH FIRST ROW ONLY;
----

[NOTE]
====
. The `FIRST`/`SKIP` and `ROWS` clauses are non-standard alternatives.
. The `OFFSET` and/or `FETCH` clauses cannot be mixed with clauses from the `FIRST`/`SKIP` or `ROWS` alternatives in the same query expression.
. Expressions and column references are not allowed within either the `OFFSET` or the `FETCH` clause.
. Unlike the `ROWS` clause, `OFFSET` and `FETCH` are available only in `SELECT` statements.
. The "`percentage FETCH`" defined in the SQL standard is not supported.
. "```FETCH ... WITH TIES```" defined in the SQL standard is not supported.
====

[[rnfb30-dml-mixjoins]]
=== Prohibit Edgy Mixing of Implicit/Explicit Joins
Dmitry Yemanov

While mixing of implicit and explict join syntax is not recommended at all, the parser would allows them, nevertheless.
Certain "`mixes`" actually cause the optimizer to produce unexpected results, including "`No record for fetch`" errors.
The same edgy styles are prohibited by other SQL engines and now they are prohibited in Firebird.

To visit some discussion on the subject, see the Tracker ticket http://tracker.firebirdsql.org/browse/CORE-2812[CORE-2812].

[[rnfb30-dml-leftparam]]
=== Support for Left-side Parameters in WHERE Clause
Adriano dos Santos Fernandes

The following style of subquery, with the parameter in the left side of a `WHERE...IN (SELECT...)` condition, would fail with the error "`The data type of the parameter is unknown`".

This style is now accepted.
For example:

[source]
----
SELECT <columns> FROM table_1 t1
  WHERE <conditions on table_1>
  AND (? IN (SELECT some_col FROM table_2 t2 WHERE t1.id = t2.ref_id))
----

[IMPORTANT]
====
Better SQL coding practice would be to use `EXISTS` in these cases;
however, developers were stumbling over this problem when using generated SQL from Hibernate, which used this undesirable style.
====

[[rnfb30-dml-returning]]
=== Enhancements to the RETURNING Clause
Adriano dos Santos Fernandes

Two enhancements were added to the `RETURNING` clause:

[[rnfb30-dml-returningalias]]
==== RETURNING Clause Value Can be Aliased

When using the `RETURNING` clause to return a value to the client, the value can now be passed under an alias.

.Example Without and With Aliases
[source]
----
UPDATE T1 SET F2 = F2 * 10
  RETURNING OLD.F2, NEW.F2; -- without aliases

UPDATE T1 SET F2 = F2 * 10
  RETURNING OLD.F2 OLD_F2, NEW.F2 AS NEW_F2; -- with aliases
----

[NOTE]
====
The keyword `AS` is optional.
====

[[rnfb30-dml-returningcursor]]
==== RETURNING Clause from Positioned Updates and Deletes

Support has been added for a `RETURNING` clause in positioned (`WHERE CURRENT OF`) `UPDATE` and `DELETE` statements.

.Example
[source]
----
UPDATE T1 SET F2 = F2 * 10 WHERE CURRENT OF C
  RETURNING NEW.F2;
----

[[rnfb30-dml-curstability]]
=== Cursor Stability
Vlad Khorsun

Until this release, Firebird suffered from an infamous bug whereby a data modification operation could loop infinitely and, depending on the operation, delete all the rows in a table, continue updating the same rows ad infinitum or insert rows until the host machine ran out of resources.
All DML statements were affected (`INSERT`, `UPDATE`, `DELETE`, `MERGE`).
It occurred because the engine used an implicit cursor for the operations.

To ensure stability, rows to be inserted, updated or deleted had to be marked in some way in order to avoid multiple visits.
Another workaround was to force the query to have a `SORT` in its plan, in order to materialize the cursor.

From Firebird 3, engine uses the Undo log to check whether a row was already inserted or modified by the current cursor.

[IMPORTANT]
====
This stabilisation does *not* work with `SUSPEND` loops in PSQL.
====

[[rnfb30-dml-gtt]]
=== An Improvement for Global Temporary Tables
Vlad Khorsun

Global temporary tables (GTTs) are now writable even in read-only transactions.
The effect is as follows:

Read-only transaction in read-write database::
Writable in both `ON COMMIT PRESERVE ROWS` and `ON COMMIT DELETE ROWS`

Read-only transaction in read-only database::
Writable in `ON COMMIT DELETE ROWS` only

Also

* Rollback for GTT `ON COMMIT DELETE ROWS` is faster
* Rows do not need to be backed out on rollback
* Garbage collection in GTT is not delayed by active transactions of other connections

[NOTE]
====
The same refinements were also backported to Firebird 2.5.1.
====

[[rnfb30-dml-validate]]
=== An Improvement for DML Strings
Adriano dos Santos Fernandes

Strings in DML queries are now transformed or validated to avoid passing malformed strings to the engine internals, for example, to the `MON$STATEMENTS.MON$SQL_TEXT` column.

The solution adopted depends on the character set of the attachment:

* `NONE` -- non-ASCII characters are transformed to question marks
* Others -- the string is checked for malformed characters

[[rnfb30-dml-countresult]]
=== COUNT() Now Returns BIGINT

The `COUNT()` aggregate function now returns its result as `BIGINT` instead of `INTEGER`.

[[rnfb30-dml-optimize]]
=== Optimizations

Optimizations made for this release included:

[[rnfb30-dml-similarto]]
==== SIMILAR TO
Adriano dos Santos Fernandes

The performance of SIMILAR TO was improved.

[[rnfb30-dml-orparam]]
==== OR'ed Parameter in WHERE Clause
Dmitry Yemanov

Performance for `(table.field = :param or :param = -1)` in the `WHERE` clause was enhanced.

[[rnfb30-dml-perf01]]
==== Better Choices for Navigation
Dmitry Yemanov

Previously, when an `ORDER` plan was in a `SELECT` structure, the optimizer would choose the first index candidate that matched the `ORDER BY` or `GROUP BY` clause.
This "`first come`" approach is not the best when multiple index choices are available.
The Firebird 3 engine surveys all of the available choices and picks the most suitable index.

See Tracker ticket http://tracker.firebirdsql.org/browse/CORE-4285[CORE-4285].

[[rnfb30-dml-perf02]]
==== Plainer Execution Path for UNION Queries
Dmitry Yemanov

Previously, the execution path for `UNION` queries was hierarchical, often causing redundant reads.
This optimization replaces the hierarchical execution path with a plainer one that improves performance.

See Tracker ticket http://tracker.firebirdsql.org/browse/CORE-4165[CORE-4165].

[[rnfb30-dml-perf03]]
==== Index Walk for Compound Index
Dmitry Yemanov

The optimizer now allows an index walk (`ORDER` plan) when a suitable compound index `(A, B)` is available for a query condition of the style `WHERE A = ? ORDER BY B`.

See Tracker ticket http://tracker.firebirdsql.org/browse/CORE-1846[CORE-1846].

[[rnfb30-dml-perf04]]
==== Performance Improvement for SET STATISTICS INDEX
Vlad Khorsun

`BTR_selectivity()` would walk the whole leaf level of given index b-tree to calculate index selectivity.
Throughout the process, the only rescheduling would happen at a disk I/O operation.
The effect was to impose long waits for AST requests from concurrent attachments, such as page lock requests, monitoring, cancellation, etc.
An improvement in Firebird 3 seems to solve that problem.

See Tracker ticket http://tracker.firebirdsql.org/browse/CORE-4215[CORE-4215].

[[rnfb30-dml-dialect1]]
=== Dialect 1 Interface
Adriano dos Santos Fernandes

Selection of `SQL_INT64`, `SQL_DATE` and `SQL_TIME` in dialect 1 was enabled.

See Tracker http://tracker.firebirdsql.org/browse/CORE-3972[CORE-3972]

[[rnfb30-dml-esql]]
=== Embedded SQL (ESQL) Enhancements
Dmitry Yemanov

Two enhancements were included in the Embedded SQL subset in this release:

Support for UPDATE OR INSERT statement::
See Tracker ticket  http://tracker.firebirdsql.org/browse/CORE-4438[CORE-4438]

Support for the RETURNING clause::
See Tracker ticket http://tracker.firebirdsql.org/browse/CORE-4437[CORE-4437]

[[rnfb30-dml-contextvars]]
=== Context Variables

Context variables added in version 3.0.4:

==== WIRE_COMPRESSED and WIRE_ENCRYPTED
Vlad Khorsun

*Firebird 3.0.4:* Context variables `WIRE_COMPRESSED` and `WIRE_ENCRYPTED` were added to the `SYSTEM` namespace to report compression and encryption status, respectively, of the current connection:

WIRE_COMPRESSED::
Compression status of the current connection.
If the connection is compressed, returns `TRUE`;
if it is not compressed, returns `FALSE`.
Returns `NULL` if the connection is embedded.

WIRE_ENCRYPTED::
Encryption status of the current connection.
If the connection is encrypted, returns `TRUE`;
if it is not encrypted, returns `FALSE`.
Returns `NULL` if the connection is embedded.

==== LOCALTIME and LOCALTIMESTAMP
Adriano dos Santos Fernandes

*Firebird 3.0.4:* Context variables `LOCALTIME` and `LOCALTIMESTAMP` were added as synonyms for `CURRENT_TIME` and `CURRENT_TIMESTAMP`, respectively, in anticipation of `CURRENT_TIME` and `CURRENT_TIMESTAMP` being redefined in Firebird 4 to represent the time and timestamp in UTC time, to comply with the SQL standards.

LOCALTIME::
Returns a timestamp carrying no date part.
The time part registers the time of day, to thousandths of a second, when execution of the current statement began.
If the statement results in multiple operations, the timestamp written to all records created or updated will be the same.

LOCALTIMESTAMP::
Returns a timestamp registering the date and the time of day, to thousandths of a second, when execution of the current statement began.
If the statement results in multiple operations, all records created or updated will have the same timestamp.
