[[rnfb30-general]]
= General Notes

Thank you for choosing Firebird 3.0.
We cordially invite you to test it hard against  your expectations and engage with us in identifying and fixing any bugs you might encounter.

If you are upgrading from a previous major release version, be sure to study Chapter 12, <<rnfb30-compat,[ref]_Compatibility Issues_>> before you attempt to do anything to your existing databases!

[[rnfb30-general-v306]]
== Sub-release V.3.0.6

Bugs reported and fixed prior to the version 3.0.6 release are listed <<bug-306,HERE>>.

.Note for Pascal developers
[IMPORTANT]
====
`VERSION` constants for Firebird API interfaces inside the distributed `Firebird.pas` file were re-generated to match numeration rules used for other languages.
====

[[rnfb30-general-improvements-v306]]
=== V.3.0.6 Improvements

_(http://tracker.firebirdsql.org/browse/CORE-6334[CORE-6334])_
-- Added missing relocation support to MacOS builds.

_Implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6274[CORE-6274])_
-- Increased parsing speed of long queries.

_Implemented by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6237[CORE-6237])_
-- Improved performance when using SRP plugin.

_Implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4933[CORE-4933])_
-- Added better transaction control to ISQL.

_Implemented by V. Khorsun_

'''

[[rnfb30-general-v305]]
== Sub-release V.3.0.5

Bugs reported and fixed prior to the version 3.0.5 release are listed <<bug-305,HERE>>.

[[rnfb30-general-improvements-v305]]
=== V.3.0.5 Improvements

_(http://tracker.firebirdsql.org/browse/CORE-6072[CORE-6072])_
-- Improved the engine providers compatibility across Firebird versions.

_Implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6004[CORE-6004])_
-- Added a configuration switch to disable the "TCP Loopback Fast Path" option (Windows only).

_Implemented by KarloX2_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5948[CORE-5948])_
-- Improved the WIN_SSPI plugin to produce keys for the WireCrypt plugin.

_Implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5928[CORE-5928])_
-- Made it possible for the AuthClient plugin to access the authentication block from DPB.

_Implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5724[CORE-5724])_
-- Added ability to use "```install.sh -path /opt/my_path```" without a need to install Firebird first in the default folder.

_Implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4462[CORE-4462])_
-- Implemented option to restore compressed `.nbk` files without explicitly decompressing them.

_Implemented by A. Peshkov, V. Khorsun_

'''

[[rnfb30-general-v304]]
== Sub-release V.3.0.4

Bugs reported and fixed prior to the version 3.0.4 release are listed <<bug-304,HERE>>.

.BLOB Vulnerability
[IMPORTANT]
====
Because of the way BLOBs are implemented in Firebird, it is possible for a knowledgeable user to gain unauthorised access to their contents by a brute force method without having the necessary privileges to access the table containing them.
Some work was done to ameliorate this risk in databases accessed by Firebird 3.0.4 or higher.
====

.Security Patch for Srp Client Proof
[IMPORTANT]
====
See <<rnfb30-security-srp-patch304,V. 3.0.4 SRP Security Patch>> in the Security chapter of these notes.
====

.Minor ODS Change for Some Platforms
[NOTE]
====
An incompatibility in the structure of the page storing generators was discovered between ODS 12.0 databases from Windows and Linux-x64 and some others, including MacOSX.
The fix resulted in a minor ODS change, from 12.0 to 12.2, for some but not all platforms.
This has certain implications for compatibility, so please read <<rnfb30-apiods-ods-12-2,these notes>>.
====

[[rnfb30-general-improvements-v304]]
=== V.3.0.4 Improvements

_(http://tracker.firebirdsql.org/browse/CORE-5913[CORE-5913])_
-- Context variables `WIRE_COMPRESSED` and `WIRE_ENCRYPTED` were added to the `SYSTEM` namespace to report compression and encryption status, respectively, of the current connection.
See <<rnfb30-dml-contextvars, Context Variables: v.3.0.4>> for details.

_Implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5908[CORE-5908])_
-- Enhanced reporting of errors when a dynamic library fails to load.
For more information, see <<rnfb3-engine-loaderrors,Better Reporting on Dynamic Library Loading Errors>>.

_Implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5876[CORE-5876])_
-- When an external function (UDF) causes an error of the type "`Arithmetic exception, numeric overflow, or string truncation`", the error message will now include the name of the function.

_Implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5860[CORE-5860])_
-- The API now supports passing the DPB/spb item `{asterisk}{asterisk}{asterisk}_auth_plugin_list` from an application to the client interface.
<<rnfb30-api-dpb-moreinfo-pluginlist,More details>>.

_Implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5853[CORE-5853])_
-- Two new context variables `LOCALTIME` and `LOCALTIMESTAMP` that are synonyms for `CURRENT_TIME` and `CURRENT_TIMESTAMP`, respectively.
They can be used in Firebird 3.0.4 and later, for forward-compatibility with Firebird 4.
See <<rnfb30-dml-contextvars,Context Variables: v.3.0.4>> for details.

_Implemented by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5746[CORE-5746])_
-- The read-only restriction for system tables was relaxed to permit `CREATE`, `ALTER` and `DROP` operations on their indexes.

_Implemented by R. Abzalov, V. Khorsun_

'''

[[rnfb30-general-v303]]
== Sub-release V.3.0.3

Bugs reported and fixed prior to the version 3.0.3 release are listed <<bug-303,HERE>>.

.Security Alert
[IMPORTANT]
====
If you are using the database encryption feature, or plan to do so, it is essential to upgrade to this sub-release.
Refer to <<bug-303-core-crypt-vuln,this report>> for details.
====

[[rnfb30-general-improvements-v303]]
=== V.3.0.3 Improvements

_(http://tracker.firebirdsql.org/browse/CORE-5727[CORE-5727])_
-- Engine response has been improved on cancel/shutdown signals when scanning a long list of pointer pages.

_Implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5712[CORE-5712])_
-- The name of the encryption key is not top secret information.
It can be read using the _gstat_ utility or service, for example.
However, for working with that name from a program it was desirable to access the key name using the API call `Attachment::getInfo()`.
Hence, this facility is now provided via the information item `fb_info_crypt_key`.

_Implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5704[CORE-5704])_
-- Some clauses of the `ALTER DATABASE` statement require updating of the single row in `RDB$DATABASE`: `SET DEFAULT CHARACTER SET`, `SET LINGER`, `DROP LINGER`.
Others, such as `BEGIN|END BACKUP`, `ENCRYPT`, `DECRYPT`, et al., do not need to touch that record.

In previous versions, to prevent concurrent instances of `ALTER DATABASE` running in parallel transactions, the engine would run an update on the `RDB$DATABASE` record regardless of the nature of clauses specified by the user.
Hence, any other transaction that read the `RDB$DATABASE` record in READ COMMITTED NO RECORD VERSION mode would be blocked briefly, even by a "`dummy update`" that in fact did not update the record.

In some cases, such as with an `ALTER DATABASE END BACKUP` the blockage could last 10 minutes or more.
A user would seem to be unable to connect to the database with  _isql_, for example, while `ALTER DATABASE END BACKUP` was running.
In fact, _isql_ would connect successfully, but it  would read `RDB$DATABASE` immediately after attaching, using a `READ COMMITTED NO RECORD VERSION WAIT` transaction and then just wait until the work of `ALTER DATABASE END BACKUP` was committed.

From this sub-release forward, the update of the `RDB$DATABASE` record is avoided when possible, and an implicit lock is placed to prevent concurrent runs of the `ALTER DATABASE` statement.

_Implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5676[CORE-5676])_
-- All queries that are semantically the same should have the same plan.
However, until now, the optimizer understood only an explicit reference inside an `ORDER BY` clause and would ignore sorts derived from equivalent expressions.
Now, it will consider equivalence classes for index navigation.
Refer to the Tracker ticket for an example.

_Implemented by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5674[CORE-5674])_
-- Common Table Expressions are now allowed to be left unused.

_implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5660[CORE-5660])_
-- Flushing a large number of dirty pages has been made faster.

_Implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5648[CORE-5648])_
-- Measures have been taken to avoid serialization of `isc_attach_database` calls issued by `EXECUTE STATEMENT`.

_Implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5629[CORE-5629])_
-- Output from _gstat_ now includes the date and time of analysis.

_implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5614[CORE-5614])_
-- The _merge_ stage of a physical backup stage could run too long, especially with huge page cache.
Changes have been made to reduce it.

_Implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5610[CORE-5610])_
-- Message "`Error during sweep: connection shutdown`" now provides information about the database that was being swept.

_Implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5602[CORE-5602])_
-- Improvement in performance of `ALTER DOMAIN` when the domain has many dependencies.

_Implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5601[CORE-5601])_
-- Compression details and encryption status of the connection (`fb_info_conn_flags`) have been added to the `getInfo()` API call.
For more information see <<rnfb30-api-dpb-moreinfo,notes in the API chapter>>.

_(http://tracker.firebirdsql.org/browse/CORE-5543[CORE-5543])_
-- Restoring a pre ODS 11.1 database now correctly populates `RDB$RELATION_TYPE` field in the metadata.

_implemented by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4913[CORE-4913])_
-- Speed of backup with _nBackup_ when directed to NAS over SMB protocol has been improved.

_Implemented by J. Hejda & V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3295[CORE-3295])_
-- The optimizer can now estimate the actual record compression ratio.

_Implemented by D. Yemanov_

'''

[[rnfb30-general-improvements-v302]]
== Sub-release V.3.0.2

Bugs reported and fixed prior to the version 3.0.2 release are listed <<bug-302,HERE>>.

One important bug fix addresses a <<bug-vuln-5474,serious security vulnerability>> present in all preceding Firebird releases and sub-releases.

[WARNING]
====
The exploit is available to authenticated users only, somewhat limiting the risks.
However, it is strongly recommended that any previous installation be upgraded to this one without delay.
====

=== New Feature

_(http://tracker.firebirdsql.org/browse/CORE-4563[CORE-4563])_
-- Support was added for fast/low-latency "`TCP Loopback Fast Path`" functionality introduced in Windows 8 and Server 2012.

This feature is said to improve the performance of the TCP stack for local loopback connections, by short-circuiting the TCP stack for local calls.
The details of the feature can be found in http://tinyurl.com/za6tvch[this Microsoft Technet blog].

_Implemented by V. Khorsun_

=== Improvements

The following improvements appear in this sub-release:

_(http://tracker.firebirdsql.org/browse/CORE-5475[CORE-5475])_
-- IMPROVEMENT: It is now possible to filter out info and warnings from the trace log.

_implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5442[CORE-5442])_
-- IMPROVEMENT: Enhanced control capability when sharing the database crypt key between Superserver attachments.

_implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5441[CORE-5441])_
-- IMPROVEMENT: The physical numbers of frequently used data pages are now cached to reduce the number of fetches of pointer pages.

_implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5434[CORE-5434])_
-- IMPROVEMENT: A read-only transaction will no longer force write the Header/TIP page content to disk immediately after a change.
This improvement gives a significant performance gain where there are numerous light read-only transactions.
At this stage, it affects only servers in SS mode.
For CS and SC it is more complex to implement and should appear in Firebird 4.0. 

_implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5374[CORE-5374])_
-- IMPROVEMENT: The database name was made available to an encryption plug-in.

_implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5332[CORE-5332])_
-- IMPROVEMENT: `libfbclient.so` was compiled for Android (x86/x86-64/arm64).

_implemented by M. A. Popa_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5257[CORE-5257])_
-- IMPROVEMENT: Nesting of keys in a plug-in configuration was enabled.

_implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5204[CORE-5204])_
-- IMPROVEMENT: The Linux code is now built with `--enable-binreloc` and an option was included in the installer script to install in locations other than `/opt/firebird`.

_implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4486[CORE-4486])_
-- IMPROVEMENT: For Trace, a filter has been provided to INCLUDE / EXCLUDE errors by their mnemonical names.

_implemented by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3885[CORE-3885])_
-- IMPROVEMENT: Android port (arm32).

_implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3637[CORE-3637])_
-- IMPROVEMENT: A port was done and tested for Linux on the ancient Motorola 680000 CPU platform to satisfy some requirement from Debian. 

_implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-1095[CORE-1095])_
-- IMPROVEMENT: Support has been added to enable `SELECT` expressions to be valid operands for the `BETWEEN` predicate.

_implemented by D. Yemanov_

'''

[[rnfb30-general-improvements-v301]]
== Sub-release V.3.0.1

Bugs reported and fixed prior to the version 3.0.1 release are listed <<bug-301,HERE>>.

The following improvements appear in this sub-release:

_(http://tracker.firebirdsql.org/browse/CORE-5266[CORE-5266])_
-- IMPROVEMENT: The statement `CREATE OR ALTER USER SYSDBA PASSWORD __password__` can now be used to initialize an empty `securityN.fdb` security database.

_implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5257[CORE-5257])_
-- IMPROVEMENT: Nesting of keys in a plug-in configuration was enabled.

_implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5229[CORE-5229])_
-- IMPROVEMENT: For <<rnfb30-apiods-api-winlocal,URL-like connection strings on Windows>>, restriction of lookup to IPv4 only was enabled.

_implemented by Michal Kubecek_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5216[CORE-5216])_
-- IMPROVEMENT: Line and column numbers (location context) are now provided for runtime errors raised inside `EXECUTE BLOCK`.

_implemented by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5205[CORE-5205])_
-- IMPROVEMENT: A switch was added to build POSIX binaries with a built-in `libtommath` library.

_implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5201[CORE-5201])_
-- IMPROVEMENT: _gbak_ now returns a non-zero result code when restore fails on creating and activating a deferred user index.

_implemented by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5167[CORE-5167])_
-- IMPROVEMENT: Implicit conversion between Boolean and string is now done automatically when a string for 'true' or 'false' is used as a value in an expression.
Case-insensitive.
Not valid when used with a Boolean operator -- `IS`, `NOT`,  `AND` or `OR`; not available for `UNKNOWN`.

_implemented by A. dos Santos Fernandes_

'''

[[rnfb30-general-bugreport]]
== Bug Reporting

Bugs fixed since the release of version 3.0.0 are listed and described in the chapter entitled <<rnfb30-bug,Bugs Fixed>>.

* If you think you have discovered a new bug in this release, please make a point of reading the instructions for bug reporting in the article https://www.firebirdsql.org/en/how-to-report-bugs/[How to Report Bugs Effectively], at the Firebird Project website.
* If you think a bug fix hasn't worked, or has caused a regression, please locate the original bug report in the Tracker, reopen it if necessary, and follow the instructions below.

Follow these guidelines as you attempt to analyse your bug:

. Write detailed bug reports, supplying the exact build number of your Firebird kit.
Also provide details of the OS platform.
Include reproducible test data in your report and post it to our http://tracker.firebirdsql.org[Tracker].
. You are warmly encouraged to make yourself known as a field-tester of this pre-release by subscribing to the mailto:firebird-test-request@lists.sourceforge.net?subject=subscribe[field-testers' list] and posting the best possible bug description you can.
. If you want to start a discussion thread about a bug or an implementation, please do so by subscribing to the mailto:firebird-devel-request@lists.sourceforge.net?subject=subscribe[firebird-devel list].
In that forum you might also see feedback about any tracker ticket you post regarding this Beta.

[[rnfb30-general-docs]]
== Documentation

You will find all of the README documents referred to in these notes -- as well as many others not referred to -- in the `doc` sub-directory of your Firebird 3.0 installation.

_--The Firebird Project_