[[rnfb30-new]]
= New In Firebird 3.0

The primary goals for Firebird 3 were to unify the server architecture and to improve support for SMP and multiple-core hardware platforms.
Parallel objectives were to improve threading of engine processes, and the options for sharing page cache across thread and connection boundaries.

Alongside these aims came new strategies to improve performance, query optimization, monitoring and scalability, and to address the demand for more security options.
A number of popular features were introduced into the SQL language, including the long-awaited support for the `BOOLEAN` data type and the associated logical predications.

[[rnfb30-new-subreleases]]
== Sub-Releases

Details of improvements and links to bug fixes in sub-releases can be found in the <<rnfb30-general,General Notes>> chapter.

[[rnfb30-new-sumry]]
== Summary of Features

The following list summarises the features and changes, with links to the chapters and topics where more detailed information can be found.

Unification of the Firebird executable is complete::
With the completion of true SMP support for Superserver, the Firebird core is now a unified library that supports a single ODS, loadable either as an embedded engine or by the "`network listener`" executable.
Choice of server model is determined by settings for a new configuration parameter `ServerMode`, defining the locking and cache modes.
It is specified at global level in `firebird.conf`.
+
By default, ServerMode = Super (alias __ThreadedDedicated__), i.e., SuperServer.
+
[NOTE]
====
The previous `aliases.conf` is replaced by `databases.conf`,  now including not just aliases for databases but also (optionally) configuration parameters to enable configuration of databases and/or alternative security databases individually.
====
+
The changes are described in more detail in the chapter <<rnfb30-engine,Changes in the Firebird Engine>>.

True SMP support for SuperServer::
In Superserver mode, the engine now makes use of multiple CPUs and cores when spawning connections.
+
Tracker: http://tracker.firebirdsql.org/browse/CORE-775[CORE-775]
+
Implemented by V. Khorsun

New, object-oriented C{plus}{plus} APIs::
Object-oriented C{plus}{plus} APIs enable external code routines to plug in and run safely inside Firebird engine space, including (but not limited to):
** Encryption schemes for data
** User authentication schemes, including secure key exchange
** Eventually, plug-in support for stored procedures, triggers and functions written in Java, C{plus}{plus}, ObjectPascal, etc.

"`Per-Database`" Configuration::
<<rnfb3-fbconf-perdatabase,Custom configuration at database level>> can now be achieved with formal entries in `databases.conf` (formerly `aliases.conf`).

Increased Limits in Several Areas::
Transaction IDs, attachment IDs, statement IDs all have increased maximum values.
+
Maximum number of page buffers in cache is increased for 64-bit servers.
+
Maximum database size is increased.
+
For details, see Chapter 4, <<rnfb30-apiods,[ref]_Changes to the API and ODS_>>.

Multiple Security Databases::
Firebird now supports user access control via more than one security database on the server.
Each database can be <<rnfb3-fbconf-perdatabase,configured>>, using the parameter `SecurityDatabase` in `databases.conf`, to use a specific database other than the default `security3.fdb`.
The user structures may even be defined within the user database itself.
+
[NOTE]
====
The flag `MON$SEC_DATABASE` was added to the monitoring table `MON$DATABASE` to assist in determining what type of security database is used -- `Default`, `Self` or `Other`.
====

Several New SQL Commands to Manage Users and Access::
Changes in architecture, stiffening of rules for security and data integrity, along with feature requests, have given rise to a raft of new <<rnfb30-access-sql,SQL commands for managing users and their access to objects>>.

International Characters in User Credentials::
Provided the new authentication provisions are used, the system can accept user names and passwords containing non-ASCII characters.
See <<rnfb30-login-international,International Character Sets for User Accounts>> in the <<rnfb30-security,Security>> chapter.

New Data Type Support::
`BOOLEAN`:::
A true `BOOLEAN` type (True/False/Unknown), complete with support for logical predicates, e.g.,
+
[source]
----
UPDATE ATABLE
  SET MYBOOL = (COLUMN1 IS DISTINCT FROM COLUMN2)
----
+
For details, see <<rnfb30-ddl-boolean,BOOLEAN Type>>.
+
`IDENTITY`:::
`IDENTITY` type, spawning unique identifiers for the defined column from an internal generator.
For details, see <<rnfb30-ddl-identity,IDENTITY-Style Column>>.

Manage NULL/NOT NULL Column/Domain Attribute::
The `NOT NULL` attribute on a column or domain can now be managed using the `ALTER TABLE` or `ALTER DOMAIN` syntax, respectively.
For details, see <<rnfb30-ddl-managenull,Manage Nullability in Domains and Columns>>.

Support for SQL Packages::
For details, refer to <<rnfb30-psql-packages,Packages>>.

DDL Triggers::
Now, triggers can be written to execute when database objects are modified or deleted.
A typical use is to block unauthorised users from performing these tasks.
+
For details, refer to <<rnfb30-psql-ddltriggers,DDL Triggers>>.

'Window' functions in DML::
A whole new series of analytical functions to work with multiple subsets in DML.
See <<rnfb30-dml-windowfuncs,Window (Analytical) Functions>>.

Statistical functions::
A suite of statistical functions returning values for a variety of variance, standard deviation and linear regression formulae.
See <<rnfb30-dml-statistical,Statistical Functions>>.

Scrollable Cursors::
The query engine now supports bi-directional ("`scrollable`") cursors, enabling both forward and backward navigation in PSQL and in DSQL with support from the API.
See <<rnfb30-psql-scrollcursors,Scrollable (Bi-directional) Cursor Support>>.

SQL:2008-Compliant OFFSET and FETCH Clauses::
Support implemented for SQL:2008-compliant `OFFSET` and `FETCH` clauses as an alternative for {`FIRST` and `SKIP`} or {`ROWS` and `TO`} clauses.
See <<rnfb30-dml-offsetfetch,SQL:2008-Compliant OFFSET and FETCH Clauses>>.

IPv6 Support::
Firebird 3 can use IPv6 connections on both client and server sides.
See the notes for the new configuration parameter <<rnfb30-fbconf-ipv6only,IPv6V6Only>>.

Validation Whilst Database is On-line::
On-line validation, first implemented in Firebird 2.5.4, has been ported forward to Firebird 3.0.
See <<rnfb30-apiods-api-onlinevalidation,Perform Some Validation Services On-line>>.

Run-time Statistics in gbak Verbose Output::
Verbose output from _gbak_ can now include <<rnfb30-util-gbakstats,run-time statistics>>, reporting times elapsed, page reads and page writes.
Also supported in the <<rnfb30-api-spb-gbakstats,Services API>>.

[[rnfb30-new-compat]]
== Compatibility with Older Versions

A series of notes about compatibility with older Firebird versions is collated in Chapter 12, "`<<rnfb30-compat,Compatibility Issues>>`".
Included there are instructions for <<rnfb30-compat-initsec,initializing the security database>>, if it was not done by your installer kit, and for configuring the server for the <<rnfb30-compat-legacyauth,legacy style of authentication>>.
