[[rnfb30-psql]]
= Procedural SQL (PSQL)

Advancements in procedural SQL (PSQL) include:

[[rnfb30-psql-links]]
== Quick Links

* <<rnfb30-psql-funcs>>
* <<rnfb30-psql-subroutines>>
* <<rnfb30-psql-packages>>
* <<rnfb30-psql-ddltriggers>>
* <<rnfb30-psql-exceptparams>>
* <<rnfb30-psql-continue>>
* <<rnfb30-psql-cursor-stablility>>
* <<rnfb30-psql-cursor-asvariable>>
* <<rnfb30-psql-whensqlstate>>
* <<rnfb30-psql-limitsoff,Some Size Limits Removed Using New API>>

[[rnfb30-psql-funcs]]
== PSQL Stored Functions
Dmitry Yemanov

It is now possible to write a scalar function in PSQL and call it just like an internal function.

.Syntax for the DDL
[listing,subs=+quotes]
----
{CREATE [OR ALTER] | ALTER | RECREATE} FUNCTION _name_
  [(<param1> [, ...])]
  RETURNS <type>
AS
BEGIN
  ...
END
----

[TIP]
====
The `CREATE` statement is the _declaration syntax_ for PSQL functions, parallel to `DECLARE` for legacy UDFs.
====

.Example
[source]
----
CREATE FUNCTION F(X INT) RETURNS INT
AS
BEGIN
  RETURN X+1;
END;
SELECT F(5) FROM RDB$DATABASE;
----

[[rnfb30-psql-subroutines]]
== PSQL Sub-routines
Adriano dos Santos Fernandes

The header of a PSQL module (stored procedure, stored function, trigger, executable block) can now accept sub-procedure and sub-function blocks in the header declarations for use within the body of the module.

.Syntax for Declaring a Sub-procedure
[listing,subs=+quotes]
----
DECLARE PROCEDURE _name_ [(<param1> [, ...])]
[RETURNS (<param1> [, ...])]
AS
...
----

.Syntax for declaring a Sub-function
[listing,subs=+quotes]
----
DECLARE FUNCTION _name_ [(<param1> [, ...])]
RETURNS <type>
AS
...
----

.Examples
[source]
----
SET TERM ^;
--
-- Sub-function in EXECUTE BLOCK
--
EXECUTE BLOCK RETURNS (N INT)
AS
  DECLARE FUNCTION F(X INT) RETURNS INT
  AS
  BEGIN
    RETURN X+1;
  END
BEGIN
  N = F(5);
  SUSPEND;
END ^
--
-- Sub-function inside a stored function
--
CREATE OR ALTER FUNCTION FUNC1 (n1 INTEGER, n2 INTEGER)
  RETURNS INTEGER
  AS
  DECLARE FUNCTION SUBFUNC (n1 INTEGER, n2 INTEGER)
    RETURNS INTEGER
    AS
    BEGIN
      RETURN n1 + n2;
    END
    BEGIN
      RETURN SUBFUNC(n1, n2);
    END ^
--
select func1(5, 6) from rdb$database ^
----

[[rnfb30-psql-packages]]
== Packages
Adriano dos Santos Fernandes

.Acknowledgement
[NOTE]
====
This feature was sponsored with donations gathered at the fifth Brazilian Firebird Developers' Day, 2008
====

A package is a group of procedures and functions managed as one entity.
The notion of "`packaging`" the code components of a database operation addresses several objectives:

Modularisation::
The idea is to separate blocks of interdependent code into logical modules, as programming languages do.
+
In programming, it is well recognised that grouping code in various ways, in namespaces, units or classes, for example, is a good thing.
With standard procedures and functions in the database this is not possible.
Although they can be grouped in different script files, two problems remain:
+
.. The grouping is not represented in the database metadata.
.. Scripted routines all participate in a flat namespace and are callable by everyone (we are not referring to security permissions here).

To facilitate dependency tracking::
We want a mechanism to facilitate dependency tracking between a collection of related internal routines, as well as between this collection and other routines, both packaged and unpackaged.
+
Firebird packages come in two parts: a _header_ (keyword `PACKAGE`), and a _body_ (keyword `PACKAGE BODY`).
This division is very similar to a Delphi unit, the header corresponding to the interface part, and the body corresponding to the implementation part.
+
The header is created first (`CREATE PACKAGE`), and the body (`CREATE PACKAGE BODY`) follows.
+
Whenever a packaged routine determines that it uses a certain database object, a dependency on that object is registered in Firebird system tables.
Thereafter, to drop, or maybe alter that object, you first need to remove what depends on it.
As it is a package body that depends on it, that package body can just be dropped, even if some other database object depends on this package.
When the body is dropped, the header remains, allowing you to recreate its body once the changes related to the removed object are done.

To facilitate permission management::
It is good practice in general to create routines to require privileged use and to use roles or users to enable the privileged use.
As Firebird runs routines with the caller privileges, it is necessary also to grant resource usage to each routine when these resources would not be directly accessible to the caller.
Usage of each routine needs to be granted to users and/or roles.
+
Packaged routines do not have individual privileges.
The privileges act on the package.
Privileges granted to packages are valid for all package body routines, including private ones, but are stored for the package header.
+
.For example
[source]
----
GRANT SELECT ON TABLE secret TO PACKAGE pk_secret;
GRANT EXECUTE ON PACKAGE pk_secret TO ROLE role_secret;
----

To enable "`private scope`"::
This objective was to introduce private scope to routines;
that is, to make them available only for internal usage within the defining package.
+
All programming languages have the notion of routine scope, which is not possible without some form of grouping.
Firebird packages also work like Delphi units in this regard.
If a routine is not declared in the package header (interface) and is implemented in the body (implementation), it becomes a private routine.
A private routine can only be called from inside its package.

[[rnfb30-psql-pkg-signatures]]
=== Signatures

For each routine that is assigned to a package, elements of a digital signature (the set of [routine name, parameters and return type]) are stored in the system tables.

The signature of a procedure or routine can be queried, as follows:

[source]
----
SELECT...
-- sample query to come
----

[[rnfb30-psql-pkg-syntax]]
=== Packaging Syntax

[listing,subs=+quotes]
----
<package_header> ::=
  { CREATE [OR ALTER] | ALTER | RECREATE } PACKAGE _name_
  AS
  BEGIN
      [ <package_item> ... ]
  END

<package_item> ::=
  <function_decl> ; |
  <procedure_decl> ;

<function_decl> ::=
  FUNCTION _name_ [( <parameters> )] RETURNS <type>

<procedure_decl> ::=
  PROCEDURE _name_ [( <parameters> ) [RETURNS ( <parameters> )]]

<package_body> ::=
  { CREATE | RECREATE } PACKAGE BODY _name_
  AS
  BEGIN
    [ <package_item> ... ]
    [ <package_body_item> ... ]
  END

<package_body_item> ::=
  <function_impl> |
  <procedure_impl>

<function_impl> ::=
  FUNCTION _name_ [( <parameters> )] RETURNS <type>
  AS
  BEGIN
     ...
  END
  |
  FUNCTION _name_  [( <parameters> )] RETURNS <type>
    EXTERNAL NAME '__name__' ENGINE _engine_

<procedure_impl> ::=
  PROCEDURE _name_ [( <parameters> ) [RETURNS ( <parameters> )]]
  AS
  BEGIN
     ...
  END
  |
  PROCEDURE _name_ [( <parameters> ) [RETURNS ( <parameters> )]]
    EXTERNAL NAME '_name_' ENGINE _engine_

<drop_package_header> ::=
  DROP PACKAGE _name_

<drop_package_body> ::=
  DROP PACKAGE BODY _name_
----

.Syntax rules
* All routines declared in the header and at the start of the body should be implemented in the body with the same <<rnfb30-psql-pkg-signatures,signature>>, i.e. you cannot declare the routine in different ways in the header and in the body.
* Default values for procedure parameters cannot be redefined in `<package_item>` and `<package_body_item>`.
They can be in `<package_body_item>` only for private procedures that are not declared.

[NOTE]
====
* `DROP PACKAGE` drops the package body before dropping its header.
* The source of package bodies is retained after `ALTER/RECREATE PACKAGE`.
The column `RDB$PACKAGES.RDB$VALID_BODY_FLAG` indicates the state of the package body.
See Tracker item http://tracker.firebirdsql.org/browse/CORE-4487[CORE-4487].
* UDF declarations (`DECLARE EXTERNAL FUNCTION`) are currently not supported inside packages.
* Syntax is available for a description (`COMMENT ON`) for package procedures and functions and their parameters.
See Tracker item http://tracker.firebirdsql.org/browse/CORE-4484[CORE-4484].
====

[[rnfb30-psql-pkg-example]]
=== Simple Packaging Example

[source]
----
SET TERM ^;
-- package header, declarations only
CREATE OR ALTER PACKAGE TEST
AS
BEGIN
  PROCEDURE P1(I INT) RETURNS (O INT); -- public procedure
END

-- package body, implementation
RECREATE PACKAGE BODY TEST
AS
BEGIN
  FUNCTION F1(I INT) RETURNS INT; -- private function
  PROCEDURE P1(I INT) RETURNS (O INT)
  AS
  BEGIN
  END
  FUNCTION F1(I INT) RETURNS INT
  AS
  BEGIN
    RETURN 0;
  END
END ^
----

[NOTE]
====
More examples can be found in the Firebird installation, in `examples/package/`.
====

[[rnfb30-psql-ddltriggers]]
== DDL triggers
Adriano dos Santos Fernandes

.Acknowledgement
[NOTE]
====
This feature was sponsored with donations gathered at the fifth Brazilian Firebird Developers' Day, 2008
====

The purpose of a "`DDL trigger`" is to enable restrictions to be placed on users who attempt to create, alter or drop a DDL object.

.Syntax
[listing,subs=+quotes]
----
<database-trigger> ::=
  {CREATE | RECREATE | CREATE OR ALTER}
    TRIGGER _name_
    [ACTIVE | INACTIVE]
    {BEFORE | AFTER} <ddl event>
    [POSITION _number_]
  AS
  BEGIN
  	...
  END

<ddl event> ::=
	ANY DDL STATEMENT
  | <ddl event item> [{OR <ddl event item>}...]

<ddl event item> ::=
    CREATE TABLE
  | ALTER TABLE
  | DROP TABLE
  | CREATE PROCEDURE
  | ALTER PROCEDURE
  | DROP PROCEDURE
  | CREATE FUNCTION
  | ALTER FUNCTION
  | DROP FUNCTION
  | CREATE TRIGGER
  | ALTER TRIGGER
  | DROP TRIGGER
  | CREATE EXCEPTION
  | ALTER EXCEPTION
  | DROP EXCEPTION
  | CREATE VIEW
  | ALTER VIEW
  | DROP VIEW
  | CREATE DOMAIN
  | ALTER DOMAIN
  | DROP DOMAIN
  | CREATE ROLE
  | ALTER ROLE
  | DROP ROLE
  | CREATE SEQUENCE
  | ALTER SEQUENCE
  | DROP SEQUENCE
  | CREATE USER
  | ALTER USER
  | DROP USER
  | CREATE INDEX
  | ALTER INDEX
  | DROP INDEX
  | CREATE COLLATION
  | DROP COLLATION
  | ALTER CHARACTER SET
  | CREATE PACKAGE
  | ALTER PACKAGE
  | DROP PACKAGE
  | CREATE PACKAGE BODY
  | DROP PACKAGE BODY
----

.Semantics
. `BEFORE` triggers are fired before changes to the system tables.
`AFTER` triggers are fired after system table changes.
+
.Important Rule
[IMPORTANT]
====
The event type `[BEFORE | AFTER]` of a DDL trigger cannot be changed.
====

. When a DDL statement fires a trigger that raises an exception (`BEFORE` or `AFTER`, intentionally or unintentionally) the statement will not be committed.
That is, exceptions can be used to ensure that a DDL operation will fail if the conditions are not precisely as intended.

. DDL trigger actions are executed only when _committing_ the transaction in which the affected DDL command runs.
Never overlook the fact that what is possible to do in an `AFTER` trigger is exactly what is possible to do after a DDL command without autocommit.
You cannot, for example, create a table in the trigger and use it there.

. With "```CREATE OR ALTER```" statements, a trigger is fired one time at the `CREATE` event or the `ALTER` event, according to the previous existence of the object.
With `RECREATE` statements, a trigger is fired for the `DROP` event if the object exists, and for the `CREATE` event.

. `ALTER` and `DROP` events are generally not fired when the object name does not exist.
For the exception, see point 6.

. The exception to rule 5 is that `BEFORE ALTER/DROP USER` triggers fire even when the user name does not exist.
This is because, underneath, these commands perform DML on the security database, and the verification is not done before the command on it is run.
This is likely to be different with embedded users, so do not write code that depends on this.
. If some exception is raised after the DDL command starts its execution and before `AFTER` triggers are fired, `AFTER` triggers will not be fired.

. Packaged procedures and triggers do not fire individual `{CREATE | ALTER | DROP} {PROCEDURE | FUNCTION}` triggers.

[[rnfb30-psql-ddltriggers-permission]]
=== Permissions

The following users can create, alter or drop DDL triggers and access the <<rnfb30-psql-utils-notriggers,trigger-related switches>> in the Firebird utilities:

* the database owner
* SYSDBA
* a user logged in under the `RDB$ADMIN` role
* a user having the `ALTER DATABASE` <<rnfb30-security-metadataprivs,metadata privilege>>

[[rnfb30-psql-utils-notriggers]]
=== Support in Utilities

A DDL trigger is a type of database trigger, so the parameters `-nodbtriggers` (_gbak_ and _isql_) and `-T` (_nbackup_) apply to them.
Remember that only users with the appropriate metadata privileges can use these switches.

[[rnfb30-psql-ddltriggers-context]]
=== DDL_TRIGGER Context Namespace

The introduction of DDL triggers brings with it the new `DDL_TRIGGER` namespace for use with `RDB$GET_CONTEXT`.
Its usage is valid only when a DDL trigger is running.
Its use is valid in stored procedures and functions called by DDL triggers.

The `DDL_TRIGGER` context works like a stack.
Before a DDL trigger is fired, the values relative to the executed command are pushed onto this stack.
After the trigger finishes, the values are popped.
So in the case of cascade DDL statements, when a user DDL command fires a DDL trigger and this trigger executes another DDL command with `EXECUTE STATEMENT`, the values of the `DDL_TRIGGER` namespace are the ones relative to the command that fired the last DDL trigger on the call stack.

[[rnfb30-psql-ddltriggers-context-elements]]
==== Elements of DDL_TRIGGER Context

[horizontal]
`EVENT_TYPE`:: event type (`CREATE`, `ALTER`, `DROP`)
`OBJECT_TYPE`:: object type (`TABLE`, `VIEW`, etc)
`DDL_EVENT`:: event name (`<ddl event item>`), where `<ddl_event_item>` is `EVENT_TYPE || ' ' || OBJECT_TYPE`
`OBJECT_NAME`:: metadata object name
`OLD_OBJECT_NAME`:: for tracking the renaming of a domain (see note)
`NEW_OBJECT_NAME`:: for tracking the renaming of a domain (see note)
`SQL_TEXT`:: sql statement text

[NOTE]
====
`ALTER DOMAIN __old-name__ TO __new-name__` sets `OLD_OBJECT_NAME` and `NEW_OBJECT_NAME` in both `BEFORE` and `AFTER` triggers.
For this command, `OBJECT_NAME` will have the old object name in `BEFORE` triggers, and the new object name in `AFTER` triggers.
====

[[rnfb30-psql-ddltriggers-examples]]
=== Examples Using DDL Triggers

Here is how you might use a DDL trigger to enforce a consistent naming scheme, in this case, stored procedure names should begin with the prefix "```SP_```":

[source]
----
set auto on;
create exception e_invalid_sp_name 'Invalid SP name (should start with SP_)';

set term !;

create trigger trig_ddl_sp before CREATE PROCEDURE
as
begin
  if (rdb$get_context('DDL_TRIGGER', 'OBJECT_NAME') not starting 'SP_') then
    exception e_invalid_sp_name;
end!

-- Test

create procedure sp_test
as
begin
end!

create procedure test
as
begin
end!

-- The last command raises this exception and procedure TEST is not created
-- Statement failed, SQLSTATE = 42000
-- exception 1
-- -E_INVALID_SP_NAME
-- -Invalid SP name (should start with SP_)
-- -At trigger 'TRIG_DDL_SP' line: 4, col: 5

set term ;!
----

Implement custom DDL security, in this case restricting the running of DDL commands to certain users:

[source]
----
create exception e_access_denied 'Access denied';

set term !;

create trigger trig_ddl before any ddl statement
as
begin
  if (current_user <> 'SUPER_USER') then
    exception e_access_denied;
end!

-- Test

create procedure sp_test
as
begin
end!

-- The last command raises this exception and procedure SP_TEST is not created
-- Statement failed, SQLSTATE = 42000
-- exception 1
-- -E_ACCESS_DENIED
-- -Access denied
-- -At trigger 'TRIG_DDL' line: 4, col: 5

set term ;!
----

Use a trigger to log DDL actions and attempts:

[source]
----
create sequence ddl_seq;

create table ddl_log (
  id bigint not null primary key,
  moment timestamp not null,
  user_name varchar(31) not null,
  event_type varchar(25) not null,
  object_type varchar(25) not null,
  ddl_event varchar(25) not null,
  object_name varchar(31) not null,
  sql_text blob sub_type text not null,
  ok char(1) not null
);

set term !;

create trigger trig_ddl_log_before before any ddl statement
as
  declare id type of column ddl_log.id;
begin
  -- We do the changes in an AUTONOMOUS TRANSACTION, so if an exception happens
  -- and the command didn't run, the log will survive.
  in autonomous transaction do
  begin
    insert into ddl_log (id, moment, user_name, event_type, object_type,
                         ddl_event, object_name, sql_text, ok)
      values (next value for ddl_seq, current_timestamp, current_user,
              rdb$get_context('DDL_TRIGGER', 'EVENT_TYPE'),
              rdb$get_context('DDL_TRIGGER', 'OBJECT_TYPE'),
              rdb$get_context('DDL_TRIGGER', 'DDL_EVENT'),
              rdb$get_context('DDL_TRIGGER', 'OBJECT_NAME'),
              rdb$get_context('DDL_TRIGGER', 'SQL_TEXT'),
              'N')
      returning id into id;
    rdb$set_context('USER_SESSION', 'trig_ddl_log_id', id);
  end
end!

-- Note: the above trigger will fire for this DDL command. It's good idea to
-- use -nodbtriggers when working with them!
create trigger trig_ddl_log_after after any ddl statement
as
begin
  -- Here we need an AUTONOMOUS TRANSACTION because the original transaction
  -- will not see the record inserted on the BEFORE trigger autonomous
  -- transaction if user transaction is not READ COMMITTED.
  in autonomous transaction do
     update ddl_log set ok = 'Y'
     where id = rdb$get_context('USER_SESSION', 'trig_ddl_log_id');
end!

commit!

set term ;!

-- Delete the record about trig_ddl_log_after creation.
delete from ddl_log;
commit;

-- Test

-- This will be logged one time 
-- (as T1 did not exist, RECREATE acts as CREATE) with OK = Y.
recreate table t1 (
  n1 integer,
  n2 integer
);

-- This will fail as T1 already exists, so OK will be N.
create table t1 (
  n1 integer,
  n2 integer
);

-- T2 does not exist. There will be no log.
drop table t2;

-- This will be logged twice 
-- (as T1 exists, RECREATE acts as DROP and CREATE) with OK = Y.
recreate table t1 (
  n integer
);

commit;
----

[source]
----
select id, ddl_event, object_name, sql_text, ok
  from ddl_log order by id;

 ID DDL_EVENT                 OBJECT_NAME                      SQL_TEXT OK
=== ========================= ======================= ================= ======
  2 CREATE TABLE              T1                                   80:3 Y
====================================================
SQL_TEXT:
recreate table t1 (
    n1 integer,
    n2 integer
)
====================================================
  3 CREATE TABLE              T1                                   80:2 N
====================================================
SQL_TEXT:
create table t1 (
    n1 integer,
    n2 integer
)
====================================================
  4 DROP TABLE                T1                                   80:6 Y
====================================================
SQL_TEXT:
recreate table t1 (
    n integer
)
====================================================
  5 CREATE TABLE              T1                                   80:9 Y
====================================================
SQL_TEXT:
recreate table t1 (
    n integer
)
====================================================
----

[[rnfb30-psql-scrollcursors]]
== Scrollable (Bi-directional) Cursor Support
Dmitry Yemanov

Instead of just fetching rows sequentially in a forward direction, "`scrollability`" allows flexible navigation through an open cursor set both backwards and forwards.
Rows next to, prior to and relative to the current cursor row can be targetted.
In PSQL, a scrollable cursor can be operated on directly.
API support is available to enable DSQL applications to fetch rows in a similar manner.

[[rnfb30-psql-cursorrules]]
=== Cursor Syntax for PSQL

To declare a cursor:

[listing,subs=+quotes]
----
DECLARE _cursor-name_ SCROLL CURSOR FOR ( <select expression> )
----

To fetch forward:

[listing,subs=+quotes]
----
FETCH _cursor-name_ [INTO _var-name_ [, _var-name_ ...]];
----

To fetch in any direction:

[listing,subs=+quotes]
----
FETCH {NEXT | PRIOR | FIRST | LAST | ABSOLUTE _n_ | RELATIVE _n_}
  FROM _cursor-name_ [INTO _var-name_ [, _var-name_ ...]];
----

See also <<rnfb30-dsql-scrollcursors,Scrollable Cursor Support for DSQL>> in the chapter entitled <<rnfb30-apiods,Changes to the Firebird API and ODS>>.
The section entitled <<rnfb30-dsql-cursoruse,Scrollable Cursor Usage>> explains a little more about the usage of the various `FETCH` options.

[NOTE]
====
. When a scrolling option is omitted, `NO SCROLL` is implied (i.e. the cursor is opened as forward-only).
This means that only `FETCH [NEXT FROM]` commands can be used.
Other commands will return an error.
. Scrollable cursors are internally materialized as a temporary record set, thus consuming memory/disk resources, so this feature should be used only when really necessary.
====

[[rnfb30-psql-exceptparams]]
== Exceptions with parameters
Adriano dos Santos Fernandes

An exception can now be defined with a message containing slots for parameters which are filled and passed when raising the exception, using the syntax pattern

[listing,subs=+quotes]
----
EXCEPTION _name_ USING ( <value list> )
----

[float]
=== Examples

[source]
----
create exception e_invalid_val 'Invalid value @1 for the field @2';
----

[source]
----
...
if (val < 1000) then
   thing = val;
else
   exception e_invalid_val using (val, 'thing');
end
----

[source]
----
CREATE EXCEPTION EX_BAD_SP_NAME
  'Name of procedures must start with ''@1'' : ''@2''';
----

[source]
----
CREATE TRIGGER TRG_SP_CREATE BEFORE CREATE PROCEDURE
AS
DECLARE SP_NAME VARCHAR(255);
BEGIN
  SP_NAME = RDB$GET_CONTEXT('DDL_TRIGGER', 'OBJECT_NAME');

  IF (SP_NAME NOT STARTING 'SP_')
  THEN EXCEPTION EX_BAD_SP_NAME USING ('SP_', SP_NAME);
END;
----

[NOTE]
====
The status vector is generated using this code combination: `isc_except, <exception{nbsp}number>, isc_formatted_exception, <formatted{nbsp}exception{nbsp}message>, <exception{nbsp}parameters>`

Since a new error code (`isc_formatted_exception`) is used, the client must be version 3.0, or at least use the `firebird.msg` file from version 3.0, in order to translate the status vector to a string.

Considering, in left-to-right order, each parameter passed in the exception-raising statement as "`the __N__th`", with _N_ starting at 1:

* If an __N__th parameter is not passed, the text is not substituted.
* If `NULL` is passed, it is replaced by the string `'++*** null ***++'`.
* If more parameters are passed than are defined in the exception message, the surplus ones are ignored.
* The total length of the message, including the values of the parameters, is still limited to 1053 bytes.
====

[[rnfb30-psql-continue]]
== CONTINUE in Looping Logic
Adriano dos Santos Fernandes

`CONTINUE` is a complementary command to `BREAK`/`LEAVE`, allowing flow of control to break (leave) and start of the next iteration of a `FOR`/`WHILE` loop.

.Syntax
[listing,subs=+quotes]
----
CONTINUE [_label_];
----

.Example
[source]
----
FOR SELECT A, D FROM ATABLE INTO :achar, :ddate
  DO BEGIN
    IF (ddate < current_data - 30) THEN
      CONTINUE;
    ELSE
      /* do stuff */
    ...
  END
----

[[rnfb30-psql-cursor-stablility]]
== PSQL Cursor Stabilization
Vlad Khorsun

PSQL cursors without `SUSPEND` inside are now stable:

[source]
----
FOR SELECT ID FROM T WHERE VAL IS NULL INTO :ID
  DO BEGIN
    UPDATE T SET VAL = 1
     WHERE ID = :ID;
  END
----

Previously, this block would loop interminably.
Now, the loop will not select the value if it was set within the loop.

[NOTE]
====
This could change the behaviour of legacy code.
====

If there is a `SUSPEND` inside the block, the old instability remains: this query, for example, still produces an infinite loop:

[source]
----
FOR SELECT ID FROM T INTO :ID
  DO BEGIN
    INSERT INTO T (ID) VALUES (:ID);
    SUSPEND;
  END
----

[[rnfb30-psql-colonusage]]
== Extension of Colon Prefix Usage
Adriano dos Santos Fernandes

Hitherto, the colon ('```:```') prefix has been used in PSQL to mark a reference to a variable in DML statements.
Its use has been extended in Firebird 3 for two unrelated purposes:

. to allow `OLD`/`NEW` fields in cursors to be read or assigned to and to assign them to variables.
. to make variable assignment in both DML and PSQL statements in modules and blocks more flexible and, where needed, to resolve ambiguity between field names and variable names


[[rnfb30-psql-cursor-asvariable]]
=== PSQL Cursors as Variables

Referencing cursors as record variables is now supported in PSQL.
Either explicit (`DECLARE AS CURSOR`) or implicit (`FOR SELECT`) PSQL cursors make their current record available via the cursor name, thus making the `INTO` clause optional.

In `FOR SELECT` loops, it requires the `AS CURSOR` clause to be specified.
For example:

[source]
----
execute block as
begin
  for
    select id, x from t1 as cursor c1
  do begin
    for select id, x from t2 where x = :c1.x as cursor c2 do
    begin
          /* . . . */
    end
  end
end
----

[NOTE]
====
Notice the extension of the use of a colon ('```:```') as a prefix to the referenced cursor field.
====

.Another example
[source]
----
for
  select rdb$relation_id as id, rdb$relation_name as name
  from rdb$relations
  where rdb$view_blr is null
  as cursor tables
do begin
  out_id = tables.id;
  out_name = tables.name;
  suspend;
end
----

To avoid ambiguity, the colon prefix could be used:

[source]
----
out_id = :tables.id;
out_name = :tables.name;
/* or */
:out_id = :tables.id;
:out_name = :tables.name;
----

"`tables`" here is a cursor name and acts similarly to `OLD`/`NEW` in triggers.

[[rnfb30-psql-assign-variable]]
=== Colon Prefix as a Variable Marker

It is now valid to apply the colon prefix to a variable on either side of an assignment statement in PSQL-only constructs.

Previously, these were valid assignments:

[source]
----
var1 = :var2;
/* or */
new.fld = :var;
----

whereas, these were invalid:

[source]
----
:var1 = :var2;
/* or */
:new.fld = :var;
----

The extension (http://tracker.firebirdsql.org/browse/CORE-4434[CORE-4434]) fixes this inconsistency.

This is now valid syntax:

[source]
----
create trigger t1 before insert on t1
as
  declare v integer;
begin
  :v = :old.n;
  :new.n = :v;
end
----

In fact, using this example, there is no difference between

[source]
----
:v = :old.n;
/* and */
v = :old.n;
----

Here, it is just "`syntactic sugar`" but, in other cases, it provides the means to resolve ambiguity between field name references and variable names.

.Example of possible ambiguity
[source]
----
for
  select rdb$relation_id as id, rdb$relation_name as name
  from rdb$relations
  where rdb$view_blr is null
  as cursor tables
do begin
  out_id = :table.id;
  select tables.name from tables where tables.id = :tables.id into :out_name;
  suspend;
end
----

Inside the nested `SELECT`, "`tables`" is both a table name and a cursor name here, so the colon is used to resolve the ambiguity.

[[rnfb30-psql-whensqlstate]]
== SQLSTATE in Exception Handlers
Dmitry Yemanov

An SQLSTATE code becomes a valid condition for trapping an exception with a `WHEN` statement.
In alignment with `SQLCODE` and `GDSCODE`, the `SQLSTATE` code can be used as in the following snippet:

[source]
----
...
WHEN SQLSTATE '22006' DO
BEGIN
  -- do something
END
...
----

[NOTE]
====
`SQLSTATE` codes are string literals.
====

[[rnfb30-psql-execute-block-errors]]
== EXECUTE BLOCK Run-time Errors

From version 3.0.1, line and column numbers (location context) are now provided for run-time errors raised inside `EXECUTE BLOCK`.

[[rnfb30-psql-limitsoff]]
== PSQL Body Size Limit Raised

If and only if the new API is being used, the size of the body of a stored procedure or a trigger can exceed the traditional limit of 32 KB.
Currently, as a security measure, a hard-coded limit of 10MB is imposed, although the theoretical limit is 4GB.
The traditional size of all input or output parameters no longer limited to the traditional size of (64KB minus overhead), either.

For details, see <<rnfb30-apiods-sqlsize,Some SQL Size Limits Removed Using New API>> in the API chapter.
