[#rnfb60-apiods]
= Changes to the Firebird API and ODS

*since Firebird 5.0 release*

[#rnfb60-apiods-ods]
== ODS (On-Disk Structure) Changes

[#rnfb60-apiods-ods-version]
=== New Major ODS Version

Firebird 6.0 creates databases with an ODS (On-Disk Structure) version of 14.0.

Upgrading to Firebird 6.0 requires a backup and restore using https://firebirdsql.org/file/documentation/html/en/firebirddocs/gbak/firebird-gbak.html[gbak].

[#rnfb60-apiods-min-page]
=== Minimum Page Size Raised to 8192
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/8406[#8406]

The minimum page size was raised from 4096 to 8192.
With the introduction of schemas, some indices of system tables are now too wide for page size 4096.

[#rnfb60-apiods-new-systabs]
=== New System Tables

System tables added in ODS 14.0:

* <<rnfb60-apiods-new-systabs-mon-ltt>>
* <<rnfb60-apiods-new-systabs-mon-ltt-col>>
* <<rnfb60-apiods-new-systabs-schema>>

[#rnfb60-apiods-new-systabs-mon-ltt]
==== `MON$LOCAL_TEMPORARY_TABLES`

Provides information about active Local Temporary Tables across all connections.

[%header,cols="m,m,"]
|===
|Column Name
|Data Type
|Description

|MON$ATTACHMENT_ID
|BIGINT
|Attachment ID

|MON$TABLE_ID
|INTEGER
|Internal table ID (unique within the connection)

|MON$TABLE_NAME
|CHAR(63)
|Table name

|MON$SCHEMA_NAME
|CHAR(63)
|Schema name

|MON$TABLE_TYPE
|VARCHAR(32)
|Table type (`PRESERVE ROWS` or `DELETE ROWS`)

|===

[#rnfb60-apiods-new-systabs-mon-ltt-col]
==== `MON$LOCAL_TEMPORARY_TABLE_COLUMNS`

Provides information about the columns of active Local Temporary Tables across all connections.

[%header,cols="m,m,"]
|===
|Column Name
|Data Type
|Description

|MON$ATTACHMENT_ID
|BIGINT
|Attachment ID

|MON$TABLE_ID
|INTEGER
|Internal table ID

|MON$TABLE_NAME
|CHAR(63)
|Table name

|MON$SCHEMA_NAME
|CHAR(63)
|Schema name

|MON$FIELD_NAME
|CHAR(63)
|Field name

|MON$FIELD_POSITION
|SMALLINT
|Field position

|MON$FIELD_TYPE
|SMALLINT
|Field type

|MON$NOT_NULL
|SMALLINT
a|Nullability flag

[horizontal.compact]
`0`:: nullable
`1`:: not nullable (`NOT NULL`)

|MON$CHARACTER_SET_ID
|SMALLINT
|Character set ID

|MON$COLLATION_ID
|SMALLINT
|Collation ID

|MON$FIELD_LENGTH
|SMALLINT
|Field length

|MON$FIELD_SCALE
|SMALLINT
|Field scale

|MON$FIELD_PRECISION
|SMALLINT
|Field precision

|MON$FIELD_SUB_TYPE
|SMALLINT
|Field sub-type

|MON$CHAR_LENGTH
|INTEGER
|Character length

|===

[#rnfb60-apiods-new-systabs-schema]
==== `RDB$SCHEMAS`

The `RDB$SCHEMAS` contains the definitions of schemas themselves.
It has the following columns (in order of definition):

[%autowidth.stretch,cols="m,a", options="header",stripes="none"]
|===
|Column
|Description

|RDB$SCHEMA_NAME
|Name of the schema

|RDB$OWNER_NAME
|Name of the owner (user)

|RDB$CHARACTER_SET_NAME
|Name of the schema default character set;
if `NULL`, the default is inherited from the database

|RDB$CHARACTER_SET_SCHEMA_NAME
|Schema of the schema default character set;
if `NULL`, the default is inherited from the database

|RDB$SQL_SECURITY
|Schema default SQL SECURITY

[horizontal.compact]
`NULL`:: Inherit default (from database)
`FALSE`:: `INVOKER`
`TRUE`:: `DEFINER`

|RDB$SECURITY_CLASS
|Security class defined in the table `RDB$SECURITY_CLASSES`, to apply access control limits to the schema

|RDB$SYSTEM_FLAG
|Flag

[horizontal.compact]
`0`:: User-defined
`1` or greater:: System-defined

|RDB$DESCRIPTION
|Description of the schema as set with `COMMENT ON`

|===

[#rnfb60-apiods-new-syscols]
=== New Columns in System Tables

[%autowidth.stretch,cols="m,m,a", options="header",stripes="none"]
|===
|Table
|Column
|Description

|MON$ATTACHMENTS
|MON$SEARCH_PATH
|Search path of the attachment

|MON$CALL_STACK
|MON$SCHEMA_NAME
|Schema of the routine (with `MON$PACKAGE_NAME` and `MON$OBJECT_NAME`)

|MON$COMPILED_STATEMENTS
|MON$SCHEMA_NAME
|Schema of the routine (with `MON$PACKAGE_NAME` and `MON$OBJECT_NAME`)

|MON$TABLE_STATS
|MON$SCHEMA_NAME
|Schema of the table (with `MON$TABLE_NAME`)

.2+|RDB$CHARACTER_SETS
|RDB$DEFAULT_COLLATE_SCHEMA_NAME
|Schema of the default collation (with `RDB$DEFAULT_COLLATE_NAME`)

|RDB$SCHEMA_NAME
|Schema of the character set (with `RDB$CHARACTER_SET_NAME`)

|RDB$CHECK_CONSTRAINTS
|RDB$SCHEMA_NAME
|Schema of the constraint (with `RDB$CONSTRAINT_NAME`) *and* the backing trigger (with `RDB$TRIGGER_NAME`)

|RDB$COLLATIONS
|RDB$SCHEMA_NAME
|Schema of the collation (with `RDB$COLLATION_NAME`)

|RDB$DATABASE
|RDB$CHARACTER_SET_SCHEMA_NAME
|Schema of the database default character set (with `RDB$CHARACTER_SET_NAME`)

|RDB$DEPENDENCIES
|RDB$DEPENDED_ON_SCHEMA_NAME
|Schema of the "`depended on`" object (with `RDB$DEPENDED_ON_NAME`);
can be `NULL` if the object is a schemaless object type

|RDB$DEPENDENCIES
|RDB$DEPENDENT_SCHEMA_NAME
|Schema of the "`dependent`" object (with -- optionally -- `RDB$PACKAGE_NAME`, and `RDB$DEPENDENT_NAME`)
can be `NULL` if the object is a schemaless object type

|RDB$EXCEPTIONS
|RDB$SCHEMA_NAME
|Schema of the exception (with `RDB$EXCEPTION_NAME`)

|RDB$FIELDS
|RDB$SCHEMA_NAME
|Schema of the domain (with `RDB$FIELD_NAME`)

|RDB$FIELD_DIMENSIONS
|RDB$SCHEMA_NAME
|Schema of the domain (with `RDB$FIELD_NAME`)

|RDB$FUNCTIONS
|RDB$SCHEMA_NAME
|Schema of the function (with `RDB$PACKAGE_NAME` and `RDB$FUNCTION_NAME`)

.3+|RDB$FUNCTION_ARGUMENTS
|RDB$FIELD_SOURCE_SCHEMA_NAME
|Schema of the domain (with `RDB$FIELD_SOURCE`)

|RDB$RELATION_SCHEMA_NAME
|Schema of the "`type of`" column (with `RDB$RELATION_NAME` and `RDB$FIELD_NAME`)

|RDB$SCHEMA_NAME
|Schema of the function (with `RDB$PACKAGE_NAME` and `RDB$FUNCTION_NAME`)

|RDB$GENERATORS
|RDB$SCHEMA_NAME
|Schema of the sequence (with `RDB$GENERATOR_NAME`)

|RDB$INDEX_SEGMENTS
|RDB$SCHEMA_NAME
|Schema of the index (with `RDB$INDEX_NAME`)

.2+|RDB$INDICES
|RDB$FOREIGN_KEY_SCHEMA_NAME
|Schema of the index of the primary or unique key referenced by the foreign key backed by this index (with `RDB$FOREIGN_KEY`)

|RDB$SCHEMA_NAME
|Schema of the index (with `RDB$INDEX_NAME`) *and* the relation (with `RDB$RELATION_NAME`)

|RDB$PACKAGES
|RDB$SCHEMA_NAME
|Schema of the package (with `RDB$PACKAGE_NAME`)

|RDB$PROCEDURES
|RDB$SCHEMA_NAME
|Schema of the procedure (with `RDB$PACKAGE_NAME` and `RDB$PROCEDURE_NAME`)

.3+|RDB$PROCEDURE_PARAMETERS
|RDB$FIELD_SOURCE_SCHEMA_NAME
|Schema of the domain (with `RDB$FIELD_SOURCE`)

|RDB$RELATION_SCHEMA_NAME
|Schema of the "`type of`" column (with `RDB$RELATION_NAME` and `RDB$FIELD_NAME`)

|RDB$SCHEMA_NAME
|Schema of the procedure (with `RDB$PACKAGE_NAME` and `RDB$PROCEDURE_NAME`)

|RDB$PUBLICATION_TABLES
|RDB$TABLE_SCHEMA_NAME
|Schema of the published table (with `RDB$TABLE_NAME`)

.2+|RDB$REF_CONSTRAINTS
|RDB$CONST_SCHEMA_NAME_UQ
|Schema of the primary or unique key constraint linked in the `REFERENCES` clause (with `RDB$CONST_NAME_UQ`)

|RDB$SCHEMA_NAME
|Schema of the constraint (with `RDB$CONSTRAINT_NAME`)

|RDB$RELATIONS
|RDB$SCHEMA_NAME
|Schema of the relation (with `RDB$RELATION_NAME`)

|RDB$RELATION_CONSTRAINTS
|RDB$SCHEMA_NAME
|Schema of the constraint (with `RDB$CONSTRAINT_NAME`), the table (with `RDB$RELATION_NAME`), *and* the backing index (with `RDB$INDEX_NAME`)

.2+|RDB$RELATION_FIELDS
|RDB$FIELD_SOURCE_SCHEMA_NAME
|Schema of the domain (with `RDB$FIELD_SOURCE`)

|RDB$SCHEMA_NAME
|Schema of the relation (with `RDB$RELATION_NAME`) *and* the internal sequence for identity values (with `RDB$GENERATOR_NAME`)

|RDB$TRIGGERS
|RDB$SCHEMA_NAME
|Schema of the trigger (with `RDB$TRIGGER_NAME`) *and* the relation (with `RDB$RELATION_NAME`)

|RDB$TRIGGER_MESSAGES
|RDB$SCHEMA_NAME
|Schema of the trigger (with `RDB$TRIGGER_NAME`)

|RDB$USER_PRIVILEGES
|RDB$RELATION_SCHEMA_NAME
|Schema of the object the privilege is granted `ON` (with `RDB$RELATION_NAME`);
can be `NULL` if the object is a schemaless object type

|RDB$USER_PRIVILEGES
|RDB$USER_SCHEMA_NAME
|Schema of the object the privilege is granted `TO` (with `RDB$USER`);
can be `NULL` if the object is a schemaless object type

.2+|RDB$VIEW_RELATIONS
|RDB$RELATION_SCHEMA_NAME
|Schema of the relation (with `RDB$RELATION_NAME`) *or* stored procedure (with `RDB$PACKAGE_NAME` and `RDB$RELATION_NAME`) referenced by the view

|RDB$SCHEMA_NAME
|Schema of the view (with `RDB$VIEW_NAME`)

|===

[#rnfb60-apiods-overflow-header]
=== Removal of Overflow Header Pages
Dmitry Yemanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/7975[#7975]

The support for overflow header pages has been removed.

Previous Firebird versions supported multiple header pages per database file.
Such overflow header pages are allocated if stored clumplets do not fit the available header page space.
However, this is practically impossible with the minimum page size of 8KB, even if we quadrupled the number of supported clumplet types.

In struct `header_page`, the field `ULONG hdr_next_page` has been renamed to `hdr_unused`.

[#rnfb60-apiods-multi]
=== Removal of Multi-file Database Support
Dmitry Yemanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8047[#8047]

Support for multi-file databases was removed.

This has the following effects:

* _gbak_ can no longer restore a database to multiple files.
That is, for restore, it no longer accepts a list of filenames and sizes, but only accepts a single database filename.
* `CREATE DATABASE` no longer accepts the `LENGTH` nor `FILE` clauses, including the `LENGTH` and `STARTING` sub-clauses of `FILE`.

[#rnfb60-apiods-blob-length]
=== Store Blob Length Longer Than 4 GiB in Blob Header
Dmitry Yemanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8428[#8428]

The size of blobs that are longer than 4 GiB is now stored in the blob header (struct `blh`).
The `blh` layout was modified to preserve the blob header size.
The field `blh_length` was changed to a 64-bit unsigned int, and field `blh_level` was moved to after `blh_charset`, and `blh_unused` was removed.

[#rnfb60-apiods-api]
== Application Programming Interfaces

The wire protocol version for the Firebird 6.0 API is 20.
Additions and changes are described in the sections below.

[#rnfb60-apiods-api-ext]
=== Main API Extensions

A number of new methods have been added to the following interfaces.

[#rnfb60-apiods-api-statement]
==== Statement

A new flag `IStatement::PREPARE_REQUIRE_SEMICOLON` was added to support ISQL's <<rnfb60-util-isql-autoterm,automatic end of statement detection>>.

[#rnfb60-apiods-api-util]
==== `UtilInterface`

The method `UtilInterface::getPerfCounters()` now reports attachment-level statistics for fetches, marks, reads, and writes.
In previous versions, this method reported database-wide statistics for these performance counters.
Under concurrent use, this could result in confusing statistics.

See also <<rnfb60-apiods-api-info-perf>>.

[#rnfb60-apiods-api-dpb]
==== New DPB Items

The following DPB (Database Parameter Buffer) items were added:

`isc_dpb_search_path`::
String parameter to set the initial <<rnfb60-engine-schema-path,search path>> of the session.

[#rnfb60-apiods-api-tpb]
==== New TPB Items

The following TPB (Transaction Parameter Buffer) items were added:

`isc_tpb_lock_table_schema`::
String parameter with the schema for table reservation.
+
This can be used with `isc_tpb_lock_read` and `isc_tpb_lock_write`, *after* the table name and
before `isc_tpb_shared`, `isc_tpb_protected` or `isc_tpb_exclusive`.
The format is a single-byte length followed by the schema name.

[#rnfb60-apiods-api-sdl]
==== New SDL Items

The following SDL (Slice Descriptor Language -- for arrays) items were added:

`isc_sdl_schema`::
String parameter with the schema.
+
Can be used to explicitly qualify the schema.
The format is the same as `isc_sdl_relation`.

[#rnfb60-apiods-api-info]
=== Extensions to various getInfo() Methods

[#rnfb60-apiods-api-info-perf]
==== New Scope Tags to Request Attachment or Database Performance Counters
Dmitry Yemanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8771[#8771]

In previous versions, database info requests for performance counters returned either database-wide performance counters for some request items, and attachment-level performance counters for others.

The `fb_info_counts_scope_att` and `fb_info_counts_scope_db` can be used to switch the current scope for all subsequent request items until a different scope tag is read.
This also makes it possible to request database-wide *and* attachment-level performance counters in a single info request.
If no scope tag was encountered before the affected request items, it will use their default (see below), which is a mix of scopes.
This default behaviour matches the behaviour in previous Firebird versions.

The scope tags specifically affect the values returned by the following information request items:

* Default database-wide
** `isc_info_reads`
** `isc_info_writes`
** `isc_info_fetches`
** `isc_info_marks`
** `isc_info_current_memory`
** `isc_info_max_memory`
* Default attachment-level
** `isc_info_read_seq_count`
** `isc_info_read_idx_count`
** `isc_info_update_count`
** `isc_info_insert_count`
** `isc_info_delete_count`
** `isc_info_backout_count`
** `isc_info_purge_count`
** `isc_info_expunge_count`

The scope tags are included as "`Single`" items in the returned information response buffer.

.Example
[listing]
----
// Request isc_info_reads (db-wide) and isc_info_read_seq_count (att-level)
// as in previous versions:
[isc_info_reads, isc_info_read_seq_count]

// Request db-wide and then att-level for same items
[fb_info_counts_scope_db, isc_info_reads, isc_info_read_seq_count,
 fb_info_counts_scope_att, isc_info_reads, isc_info_read_seq_count]
----

[#rnfb60-apiods-api-service-ext]
=== Services API Extensions

[#rnfb60-apiods-api-service-schema]
==== Schema Support

To support schemas, the following Service Request Buffer items were added:

[horizontal.compact]
`isc_spb_bkp_skip_schema_data`::
Equivalent of `gbak -skip_schema_data _sql-regex_` when backing up.

`isc_spb_bkp_include_schema_data`::
Equivalent of `gbak -include_schema_data _sql-regex_` when backing up.

`isc_spb_res_skip_schema_data`::
`gbak -skip_schema_data _sql-regex_` when restoring.

`isc_spb_res_include_schema_data`::
Equivalent of `gbak -include_schema_data _sql-regex_` when restoring.

`isc_spb_sts_schema`::
Equivalent of `gstat -schema _name_`.

`isc_spb_val_sch_incl`::
Equivalent of `isc_spb_val_tab_incl` for schema.

`isc_spb_val_sch_excl`::
Equivalent of `isc_spb_val_tab_excl` for schema.

[#rnfb60-apiods-api-trace-ext]
=== Trace API Extensions

[#rnfb60-apiods-api-paramdsc]
==== Replaced Internal `dsc` Struct With Public `paramdsc` Struct
Dmitry Yemanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8489[#8489]

Specifically in `TraceParams`, an internal struct of type `dsc` was exposed which prevented evolution of this struct for internal use.
It has been replaced with a struct `paramdsc` which is intended as public API.
It exposes the same information as `dsc` did.
