[#rnfb60-apiods]
= Changes to the Firebird API and ODS

*since Firebird 5.0 release*

[#rnfb60-apiods-ods]
== ODS (On-Disk Structure) Changes

[#rnfb60-apiods-ods-version]
=== New Major ODS Version

Firebird 6.0 creates databases with an ODS (On-Disk Structure) version of 14.0.

Upgrading to Firebird 6.0 requires a backup and restore using https://firebirdsql.org/file/documentation/html/en/firebirddocs/gbak/firebird-gbak.html[gbak].

[#rnfb60-apiods-min-page]
=== Minimum Page Size Raised to 8192
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/8406[#8406]

The minimum page size was raised from 4096 to 8192.
With the introduction of schemas, some indices of system tables are now too wide for page size 4096.

[#rnfb60-apiods-new-systabs]
=== New System Tables

System tables added in ODS 14.0:

//[horizontal]
//`<name>`:: <description>


[#rnfb60-apiods-new-syscols]
=== New Columns in System Tables

* ...

[#rnfb60-apiods-overflow-header]
=== Removal of Overflow Header Pages
Dmitry Yemanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/7975[#7975]

The support for overflow header pages has been removed.

Previous Firebird versions supported multiple header pages per database file.
Such overflow header pages are allocated if stored clumplets do not fit the available header page space.
However, this is practically impossible with the minimum page size of 8KB, even if we quadrupled the number of supported clumplet types.

In struct `header_page`, the field `ULONG hdr_next_page` has been renamed to `hdr_unused`.

[#rnfb60-apiods-multi]
=== Removal of Multi-file Database Support
Dmitry Yemanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8047[#8047]

Support for multi-file databases was removed.

This has the following effects:

* _gbak_ can no longer restore a database to multiple files.
That is, for restore, it no longer accepts a list of filenames and sizes, but only accepts a single database filename.
* `CREATE DATABASE` no longer accepts the `LENGTH` nor `FILE` clauses, including the `LENGTH` and `STARTING` sub-clauses of `FILE`.

[#rnfb60-apiods-blob-length]
=== Store Blob Length Longer Than 4 GiB in Blob Header
Dmitry Yemanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8428[#8428]

The size of blobs that are longer than 4 GiB is now stored in the blob header (struct `blh`).
The `blh` layout was modified to preserve the blob header size.
The field `blh_length` was changed to a 64-bit unsigned int, and field `blh_level` was moved to after `blh_charset`, and `blh_unused` was removed.

[#rnfb60-apiods-api]
== Application Programming Interfaces

The wire protocol version for the Firebird 6.0 API is 20.
Additions and changes are described in the sections below.

[#rnfb60-apiods-api-ext]
=== Main API Extensions

A number of new methods have been added to the following interfaces.

[#rnfb60-apiods-api-statement]
==== Statement

A new flag `IStatement::PREPARE_REQUIRE_SEMICOLON` was added to support ISQL's <<rnfb60-util-isql-autoterm,automatic end of statement detection>>.

[#rnfb60-apiods-api-info]
=== Extensions to various getInfo() Methods

// TODO Remove section if no additions

[#rnfb60-apiods-api-service-ext]
=== Services API Extensions

// TODO Remove section if no additions

[#rnfb60-apiods-api-trace-ext]
=== Trace API Extensions

[#rnfb60-apiods-api-paramdsc]
==== Replaced Internal `dsc` Struct With Public `paramdsc` Struct
Dmitry Yemanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8489[#8489]

Specifically in `TraceParams`, an internal struct of type `dsc` was exposed which prevented evolution of this struct for internal use.
It has been replaced with a struct `paramdsc` which is intended as public API.
It exposes the same information as `dsc` did.
