[#rnfb60-bug]
= Bugs Fixed

////
Individual issue template:

_https://github.com/FirebirdSQL/firebird/issues/nnnn[#nnnn]_
-- A description

_Fixed by Some Person_

'''

<end of issue template>

General outline (<version> ::= <major><minor><patch>[<pre>]):

[#bug-<version>]
== Firebird <major>.<minor>.<patch>[-<pre>] Release: Bug Fixes

[#bug-<version>-core]
=== Core Engine

[#bug-<version>-crashes]
=== Server Crashes/Hang-ups

[#bug-<version>-api]
=== API/Remote Interface

[#bug-<version>-install]
=== Installation Issues

[#bug-<version>-utils]
=== Utilities

[#bug-<version>-util-isql]
==== isql

[#bug-<version>-util-gbak]
==== gbak

[#bug-<version>-util-<tool>]
==== <tool>

[#bug-<version>-<abbreviated-subject>]
=== <subject>

////

[#bug-600a1]
== Firebird 6.0.0 Alpha 1 Release: Bug Fixes

[#bug-600a1-core]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/7476[#7476]_
-- Improvement on procedures/triggers to recognise changes in a domain used in `COALESCE`

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7568[#7568]_
-- Equivalence of Boolean condition in partial index

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7600[#7600]_
-- `CASE` statement different result compared to Firebird 2.5.9

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7715[#7715]_
-- Support multibyte (UTF8) start/end character in alternative string literal

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7924[#7924]_
-- `ALTER TABLE ALTER COLUMN <text_field>` can not be changed properly in some cases

_Fixed by Dimitry Sibiryakov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8452[#8452]_
-- Disallow creation of object names with only spaces

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/pull/8652[#8652]_
-- Prevent race condition when GlobalObject destruction routine unlocks global mutex

_Fixed by Artyom Ivanov_

'''

[#bug-600a1-util-isql]
==== isql

_https://github.com/FirebirdSQL/firebird/pull/187[#187]_
-- If stdin is `FILE_TYPE_PIPE` treat it as non-interactive

_Fixed by Artyom Smirnov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8090_
-- `isql -x` (extract metadata) generates DDL to create active indices for inactive indices

See also <<rnfb60-ddl-createidx-inactive>>.

_Fixed by Dimitry Sibiryakov_
