[#rnfb60-bug]
= Bugs Fixed

////
Individual issue template:

_https://github.com/FirebirdSQL/firebird/issues/nnnn[#nnnn]_
-- A description

_Fixed by Some Person_

'''

<end of issue template>

General outline (<version> ::= <major><minor><patch>[<pre>]):

[#bug-<version>]
== Firebird <major>.<minor>.<patch>[-<pre>] Release: Bug Fixes

[#bug-<version>-core]
=== Core Engine

[#bug-<version>-crashes]
=== Server Crashes/Hang-ups

[#bug-<version>-api]
=== API/Remote Interface

[#bug-<version>-install]
=== Installation Issues

[#bug-<version>-utils]
=== Utilities

[#bug-<version>-util-isql]
==== isql

[#bug-<version>-util-gbak]
==== gbak

[#bug-<version>-util-<tool>]
==== <tool>

[#bug-<version>-<abbreviated-subject>]
=== <subject>

////

[#bug-600a1]
== Firebird 6.0.0 Alpha 1 Release: Bug Fixes

[#bug-600a1-core]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/7476[#7476]_
-- Improvement on procedures/triggers to recognise changes in a domain used in `COALESCE`

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7568[#7568]_
-- Equivalence of Boolean condition in partial index

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7600[#7600]_
-- `CASE` statement different result compared to Firebird 2.5.9

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7715[#7715]_
-- Support multibyte (UTF8) start/end character in alternative string literal

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7924[#7924]_
-- `ALTER TABLE ALTER COLUMN <text_field>` can not be changed properly in some cases

_Fixed by Dimitry Sibiryakov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8435[#8435]_
-- Strange error with text blob concatenation with UTF8+WIN1250

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8452[#8452]_
-- Disallow creation of object names with only spaces

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/pull/8494[#8494]_
-- Fix issues with longish concatenated context aliases

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8639[#8639]_
-- Concurrency problem in remote profiler communication mechanism

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/pull/8652[#8652]_
-- Prevent race condition when GlobalObject destruction routine unlocks global mutex

_Fixed by Artyom Ivanov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8776[#8776]_
-- Prevent past-EOF access to uni-directional cursors

_Fixed by https://github.com/Ev3nt[Ev3nt^]_

'''

_https://github.com/FirebirdSQL/firebird/issues/8820[#8820]_
-- Missing a column name for Boolean expression

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8842[#8842]
-- GTT accept weird syntax and has unnecessary syntax conflicts

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8890[#8890]
-- `WITH TIME ZONE` types store non-zero garbage for padding instead of 0x00

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8902[#8902]_
-- `FULL OUTER JOIN` does not use indexes with a derived table

_Fixed by Dimitry Yemanov_

'''

https://github.com/FirebirdSQL/firebird/issues/8945[#8945]
-- `ALTER COLUMN <BOOL_COL> TYPE [VAR]CHAR` must be allowed

_Fixed by Adriano dos Santos Fernandes_

'''

[#bug-600a1-util]
=== Utilities

[#bug-600a1-util-isql]
==== isql

_https://github.com/FirebirdSQL/firebird/pull/187[#187]_
-- If stdin is `FILE_TYPE_PIPE` treat it as non-interactive

_Fixed by Artyom Smirnov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8090_
-- `isql -x` (extract metadata) generates DDL to create active indices for inactive indices

See also <<rnfb60-ddl-createidx-inactive>>.

_Fixed by Dimitry Sibiryakov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8933[#8933]_
-- `SHOW PROCEDURE/FUNCTION` doesn't show `NOT NULL` status for parameters

_Fixed by Adriano dos Santos Fernandes_

'''

[#bug-600a1-util-gbak]
==== gbak

_https://github.com/FirebirdSQL/firebird/pull/8793[#8793]_
-- Change gbak output of errors and warnings to stderr instead of stdout

_Fixed by Andrey Kravchenko_

'''
