[#rnfb60-fbconf]
= Configuration Additions and Changes

[#rnfb60-config-added]
== New Configuration Items

// TODO Specific sections needed

[#rnfb60-config-changes]
== Changed Configuration Items

// TODO Remove section if no additions

[#rnfb60-traceconf]
== Trace Configuration Additions and Changes

[#rnfb60-traceconf-database]
=== Option to Explicitly Use Database Name or Regex
Artyom Abakumov

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/8426[#8426]

The original `database` configuration item allows to match both names literally _and_ as SQL regular expressions.
These goals can conflict if the desired database name to match is not a valid SQL regular expression, and this could result in failures.

To address this, two alternative configuration items have been added:

[horizontal.compact]
`databaseName`:: Match by name only
`databaseRegex`:: Match by SQL regular expression only

The `database` configuration item continues working as before, but we recommend using these new configuration items to be explicit in the type of match you intend.

.Example configuration
[listing]
----
database
{
	enabled = false
}

databaseName = /var/primary-db.fdb
{
	enabled = true
	log_errors = true
}

databaseRegex = (%[\\/](e[[:DIGIT:]]{{2}}).fdb)
{
	enabled = true
}

database = employee
{
	enabled = true
}
----

[#rnfb60-replconf]
== Replication Configuration Additions and Changes

[#rnfb60-repl-inex-schema]
=== `include_schema_filter` and `exclude_schema_filter`

The configuration items `include_schema_filter` and `exclude_schema_filter` can be used in `replication.conf` to filter on schemas.
These new configuration items complement the existing `include_filter` and `exclude_filter` configuration items.
If `include_schema_filter` is not specified, all schemas are included by default.
Likewise, if `exclude_schema_filter` is not provided, no schemas are excluded.

[#rnfb60-repl-search-path]
=== `schema_search_path`

A primary database running on Firebird 5.0 or earlier can be asynchronously replicated to a slave database using Firebird 6.0 or higher.
Since the primary database has no schema awareness, the `schema_search_path` configuration item allows the replicator to search for database objects using the search path.

The `schema_search_path` can only be configured on the secondary side.
It has no effect if the primary is a Firebird 6.0 or higher database (as then the object names are fully qualified).

[#rnfb60-config-cleanup]
== Removed Configuration Items

`MaxIdentifierByteLength`::
Previously used for restricting maximum identifier length in bytes.
The maximum is now always 252 bytes.

`MaxIdentifierCharLength`::
Previously used for restricting maximum identifier length in characters.
The maximum is now always 63 characters.

`Redirection`::
Previously used for enabling _redirection_ (making the server act as a proxy to another Firebird server).
Redirection is now no longer possible, and was already broken for most cases since Firebird 3.0.

`RelaxedAliasChecking`::
Previously used to enable old Firebird 1.x relaxed alias rules to allow use of the table name in a column reference even if the table was aliased.
The strict alias rules are now always applied.

// TODO Other sections needed
