[#rnfb60-ddl]
= Data Definition Language (DDL)

[#rnfb60-ddl-links]
.Quick Links
* <<rnfb60-ddl-drop-if-exists>>
* <<rnfb60-ddl-alter-func-det>>
* <<rnfb60-ddl-alter-sql-sec>>
* <<rnfb60-ddl-createdb-owner>>

////
Generic template:

[#rnfb60-ddl-<abbreviated-subject>]
== <subject>
<implementer/author>

Tracker ticket: https://github.com/FirebirdSQL/firebird/[pull/]<issue>[#<issue>]

<short description>

.Syntax
[listing]
----
<syntax>
----

[<more details>]

.Examples
[listing]
----
<examples>
----

////

[#rnfb60-ddl-drop-if-exists]
== `DROP ... [IF EXISTS]`
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/4203[#4203]

Using subclause `IF EXISTS`, it's now possible to try to drop objects and not get errors when they did not exist.

.Supported statements
[listing,subs=+quotes]
----
DROP EXCEPTION [IF EXISTS] _exception_
DROP INDEX [IF EXISTS] _index-
DROP PROCEDURE [IF EXISTS] _procedure_
DROP TABLE [IF EXISTS] _table_
DROP TRIGGER [IF EXISTS] _trigger_
DROP VIEW [IF EXISTS] _view_
DROP FILTER [IF EXISTS] _filter_
DROP DOMAIN [IF EXISTS] _domain_
DROP [EXTERNAL] FUNCTION [IF EXISTS] _function_
DROP SHADOW [IF EXISTS] _shadow_
DROP ROLE [IF EXISTS] _role_
DROP GENERATOR [IF EXISTS] _generator_
DROP SEQUENCE [IF EXISTS] _sequence_
DROP COLLATION [IF EXISTS] _collation_
DROP USER [IF EXISTS] _user_ [USING PLUGIN _plugin_]
DROP PACKAGE [IF EXISTS] _package_
DROP PACKAGE BODY [IF EXISTS] _package_
DROP [GLOBAL] MAPPING [IF EXISTS] _mapping_
DROP SCHEMA [IF EXISTS] _schema_
ALTER TABLE _table_ DROP [COLUMN] [IF EXISTS] _column_
ALTER TABLE _table_ DROP CONSTRAINT [IF EXISTS] _constraint_
----

For `DROP` statements with `IF EXISTS`, DDL triggers are not fired when the object did not exist.

For `ALTER TABLE ... DROP` subclauses, DDL triggers are not fired if there are only `DROP ... IF EXISTS` subclauses and none of the columns and constraints existed.

[#rnfb60-ddl-create-if-not-exists]
== `CREATE ... [IF NOT EXISTS]`
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/8062[#8062]

Using subclause `IF NOT EXISTS`, it's now possible to try to create objects and not get errors when they already exist.

.Supported statements
[listing,subs=+quotes]
----
CREATE EXCEPTION [IF NOT EXISTS] ...
CREATE INDEX [IF NOT EXISTS] ...
CREATE PROCEDURE [IF NOT EXISTS] ...
CREATE [{GLOBAL | LOCAL} TEMPORARY] TABLE [IF NOT EXISTS] ...
CREATE TRIGGER [IF NOT EXISTS] ...
CREATE VIEW [IF NOT EXISTS] ...
CREATE FILTER [IF NOT EXISTS] ...
CREATE DOMAIN [IF NOT EXISTS] ...
CREATE FUNCTION [IF NOT EXISTS] ...
DECLARE EXTERNAL FUNCTION [IF NOT EXISTS] ...
CREATE SHADOW [IF NOT EXISTS] ...
CREATE ROLE [IF NOT EXISTS] ...
CREATE GENERATOR [IF NOT EXISTS] ...
CREATE SEQUENCE [IF NOT EXISTS] ...
CREATE COLLATION [IF NOT EXISTS] ...
CREATE USER [IF NOT EXISTS] ...
CREATE PACKAGE [IF NOT EXISTS] ...
CREATE PACKAGE BODY [IF NOT EXISTS] ...
CREATE [GLOBAL] MAPPING [IF NOT EXISTS] ...
CREATE SCHEMA [IF NOT EXISTS] ...
ALTER TABLE _table_ ADD [COLUMN] [IF NOT EXISTS] _column_ ...
ALTER TABLE _table_ ADD CONSTRAINT [IF NOT EXISTS] _constraint_ ...
----

For `CREATE` and `DECLARE` statements -- except `CREATE USER` -- where `IF NOT EXISTS` is part of the main statement, DDL triggers are not fired when the object already exists.

For the `ALTER TABLE ... ADD` subclause, DDL triggers are not fired if there are only `IF NOT EXISTS` subclauses and all columns and constraints already existed.

The engine only verifies if the name (object, column or constraint) already exists, and if so, it does nothing.
It does not try to match the definition of the existing object with the one being created.

Some objects share the same "`namespace`".
For example, there cannot be a table and a procedure -- in the same schema -- with the same name.
If there is a table `XYZ` and `CREATE PROCEDURE IF NOT EXISTS XYZ` is tried, the procedure will not be created and no error will be raised.

[#rnfb60-ddl-alter-func-det]
== Alter `DETERMINISTIC` State of Functions
Alexander Zhdanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/7427[#7427]

Added the ability to set or clear the deterministic state of a function without specifying the entire body.

.Syntax
[listing]
----
ALTER FUNCTION <name> <alter-function-option>...

<alter-function-option> ::=
    [NOT] DETERMINISTIC
  | <sql-security-option>
----

The SQL security options are covered in <<rnfb60-ddl-alter-sql-sec>>.

[#rnfb60-ddl-alter-sql-sec]
== Alter `SQL SECURITY` State of Functions, Procedures, and Packages
Alexander Zhdanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/7744[#7744]

Added the ability to alter the SQL security state of a function, procedure, or package without specifying the entire body.

.Syntax
[listing]
----
ALTER PROCEDURE <name> <sql-security-option>

ALTER PACKAGE <name> <sql-security-option>

ALTER FUNCTION <name> <alter-function-option>...

<sql-security-option> ::=
    SQL SECURITY {INVOKER | DEFINER}
  | DROP SQL SECURITY

<alter-function-option> ::=
    [NOT] DETERMINISTIC
  | <sql-security-option>
----

Dropping the SQL security state will apply the SQL security configuration of the schema.

Although the syntax of `ALTER FUNCTION` allows specifying multiple conflicting SQL security options, doing so will raise an error ("`__duplicate specification of SQL SECURITY - not supported__`").

The `[NOT] DETERMINISTIC` option for `ALTER FUNCTION` is covered in <<rnfb60-ddl-alter-func-det>>.

[#rnfb60-ddl-createdb-owner]
== Create Database With a Different Owner
Dimitry Sibiryakov

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/7719[#7719]

The `CREATE DATABASE` statement now accepts an `OWNER` clause to set a different user than the creator as the owner.
Only users with administrator privileges can use the `OWNER` clause.

.Syntax
[listing]
----
CREATE DATABASE <filespec>
  [ <db_initial_option>... ]
  [ <db_config_option>... ]

<db_initial_option> ::=
    !! existing options !!
  | OWNER _owner_
----

[#rnfb60-ddl-createidx-inactive]
== Support Creation of Inactive Indices
Dimitry Sibiryakov

Tracker tickets: https://github.com/FirebirdSQL/firebird/issues/6233[#6233], https://github.com/FirebirdSQL/firebird/issues/8090[#8090]

The `CREATE INDEX` syntax was extended to allow creation of an inactive index.
The syntax was extended with an optional `ACTIVE | INACTIVE` clause immediately after the index name.

.Syntax
[listing,subs=+quotes]
----
CREATE [UNIQUE] [ASC[ENDING] | DESC[ENDING]] INDEX
  [IF NOT EXISTS] [_idx-schema_ <period>] _indexname_
  [ACTIVE | INACTIVE]
  ON [_tbl-schema_ <period>] _tablename_
  { (_col_ [, _col_ ...])
  | COMPUTED BY (<expression>) }
  [WHERE <search_condition>]
----

[#rnfb60-ddl-create-db-multi]
== Removal of Multi-file Database Options from `CREATE DATABASE`
Dmitry Yemanov

Tracker ticker: https://github.com/FirebirdSQL/firebird/pull/8047[#8047]

The `LENGTH` and `FILE` clauses were removed from `CREATE DATABASE`, including the `LENGTH` and `STARTING` sub-clauses of `FILE`.

See also <<rnfb60-apiods-multi>>.
