[#rnfb60-dml]
= Data Manipulation Language (DML)

[#rnfb60-dml-links]
.Quick Links
* <<rnfb60-dml-cast-format>>
* <<rnfb60-dml-routine-call-default>>
* <<rnfb60-dml-named-args>>
* <<rnfb60-dml-call-stmt>>
* <<rnfb60-dml-context-system>>
* <<rnfb60-dml-built-in-functions>>
** <<rnfb60-dml-any-value>>
** <<rnfb60-dml-gen-uuid-v7>>
** <<rnfb60-dml-multi-trim>>

////
Generic template:

[#rnfb60-dml-<abbreviated-subject>]
== <subject>
<implementer/author>

Tracker ticket: https://github.com/FirebirdSQL/firebird/[pull/]<issue>[#<issue>]

<short description>

.Syntax
[listing]
----
<syntax>
----

[<more details>]

.Examples
[listing]
----
<examples>
----

////

[#rnfb60-dml-cast-format]
== Datetime `FORMAT` clause for `CAST`
Artyom Ivanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/2388[#2388]

The `CAST` function now has the SQL-standard `FORMAT` clause for casting between string types and datetime types.
This allows custom formatting of datetime values, and conversion from string values with a specific format to datetime values.

.Syntax
[listing]
----
<cast specification> ::=
  CAST ( <cast-operand> AS <cast-target>
         [ FORMAT <cast-template> ] )

<cast-template> ::=
  <character string literal>
----

.Syntax of cast-template
[listing]
----
<datetime-template> ::=
  { <datetime-template-part> }...

<datetime-template-part> ::=
    <datetime-template-field>
  | <datetime-template-delimiter>

<datetime-template-field> ::=
  !! See tables in following sections !!

<datetime-template-delimiter> ::=
  !! See tables in following sections !!
----

[#rnfb60-dml-cast-format-parse]
=== Formatting and Parsing Datetime Values

The `FORMAT` clause serves two purposes:

. Converting a datetime value to a string
. Parsing a string value to a datetime value

The _cast-template_ of the `FORMAT` clause specifies how the datetime should be converted to string, or how the string should be parsed to a datetime.
Conversion to string offers more options and flexibility than conversion to datetime.

The _cast-template_ must be a string literal, and has the following template fields:

.Cast Template Fields
[cols="<1m,<4", options="header",stripes="none"]
|===
|Format Pattern
|Description

|YEAR
|Year (1 - 9999)

|YYYY
|Last 4 digits of year (0001 - 9999)

|YYY
|Last 3 digits of year (000 - 999)

|YY
|Last 2 digits of year (00 - 99)

|Y
|Last digit of year (0 - 9)

|RR / RRRR
a|Round Year (further information <<rnfb60-dml-cast-format-rr,below>>) +
Only string to datetime

|Q
a|Quarter of the year (1 - 4) +
Only datetime to string

|MM
|Month (01 - 12)

|MON
|Short month name (e.g. `Apr`)

|MONTH
|Full month name (e.g. `APRIL`)

|RM
|Roman number of the month (`I` - `XII`)

|WW
a|Week of the year (`01` - `53`) +
Only datetime to string

Exercise caution when combining with year.
For example, 2023-01-01 is week 52 2022, but there is no week-based year template variable, and ``'WW YYYY'`` renders `52 2023`!

|W
a|Week of the month (`1` - `5`) +
Only datetime to string

Week 1 starts at day 1, week 2 at day 8, week 3 at day 15, week 4 for at day 22 and week 5 at day 29.

|D
a|Day of the week (`1` - `7`) +
Only datetime to string

`1` is Sunday, `7` is `Saturday`

|DAY
a|Full name of the day (e.g. `MONDAY`) +
Only datetime to string

|DY
|Short name of the day (e.g. `Mon`)

|DD
|Day of the month (`01` - `31`)

|DDD
a|Day of the Year (`001` - `366`) +
Only datetime to string

|J
|Julian Day (number of days since January 1, 4712 BC)

|HH / HH12
a|Hour of the day (`01` - `12`) without AM/PM period.

When converting from string to datetime, specifying template-field `A.M.` or `P.M.` is required.

|HH24
|Hour of the day (`00` - `23`)

|MI
|Minutes (`00` - `59`)

|SS
|Seconds (`00` - `59`)

|SSSSS
|Seconds since midnight (`0` - `86399`)

|FF1 - FF9
a|Fractional seconds with the specified accuracy. +
When converting from string to datetime, only `FF1` - `FF4` are supported.

For `FF5` - `FF9`, digits 5 - 9 are _always_ `0`.

|A.M. / P.M.
a|AM/PM period for 12 hours time. +
Either can be used, and will parse `A.M.` and `P.M.`, or render `A.M.` or `P.M.` depending on the actual time.

|TZH
|Time zone in hours (`-14` - `14`)

|TZM
|Time zone in minutes (`00` - `59`)

|TZR
|Time zone name or time zone displacement (same as `TZH:TZM`)

|===

Most of these template fields are defined by the SQL standard, but some are non-standard extensions.
The template fields are case-insensitive, so `YYYY-MM` is the same as `yyyy-mm`.

The template fields can be separated with the following delimiters:

.Cast Template Delimiters
[cols="<m", options="header",stripes="none"]
|===
|Delimiter

|-
|++.++
|/
|,
|;
|:
|<space>

|===

Contrary to the SQL standard, a single quote (apostrophe) is not supported as a delimiter.
// TODO Reopened https://github.com/FirebirdSQL/firebird/issues/2388 to report this, update above if needed

When converting from datetime to string, it is possible to insert raw text into a format string with double quotes: `... FORMAT '"Today is" DAY'` -> `Today is MONDAY`.
To render `"`, escape it with `\`, i.e. use `\"`, and to render `\`, use `\\`.

Example:

[listing]
----
SELECT CAST(CURRENT_TIMESTAMP AS VARCHAR(45)
  FORMAT 'DD.MM.YEAR HH24:MI:SS "is" J "Julian day"')
FROM RDB$DATABASE;
=========================
14.6.2023 15:41:29 is 2460110 Julian day
----

Patterns can be used without any separators:

[listing]
----
SELECT CAST(CURRENT_TIMESTAMP AS VARCHAR(50)
  FORMAT 'YEARMMDD HH24MISS')
FROM RDB$DATABASE;
=========================
20230719 161757
----

However, be careful with patterns with repeating characters, for example `DDDDD` will be interpreted as `DDD` + `DD`.

[#rnfb60-dml-cast-format-to-dt]
==== Converting from String to Datetime

When converting from string to datetime, additional rules and limitations apply:

* If the target type has a date component, and year, month or day are not set by the pattern, the missing parts will get their values from the current date
* If the target type has a time component, and hours, minutes, seconds, or fractions are not set by the pattern, the missing parts will be set to `0`
* [[rnfb60-dml-cast-format-rr]]Behaviour of `RR` (two-digit Round Year):
** If the specified two-digit year is 00 to 49, then
*** If the last two digits of the current year are 00 to 49, then the returned year has the same first two digits as the current year.
*** If the last two digits of the current year are 50 to 99, then the first 2 digits of the returned year are 1 greater than the first 2 digits of the current year.
** If the specified two-digit year is 50 to 99, then
*** If the last two digits of the current year are 00 to 49, then the first 2 digits of the returned year are 1 less than the first 2 digits of the current year.
*** If the last two digits of the current year are 50 to 99, then the returned year has the same first two digits as the current year.
* Behaviour of `RRRR` (4-digit Round Year): Accepts either 4-digit or 2-digit input.
If 2-digit, it provides the same result as `RR`.
If you do not want this functionality, then enter a 4-digit year.

Example:

[listing]
----
SELECT CAST('2000.12.08 12:35:30.5000' AS TIMESTAMP
  FORMAT 'YEAR.MM.DD HH24:MI:SS.FF4')
FROM RDB$DATABASE;
=====================
2000-12-08 12:35:30.5000
----


[#rnfb60-dml-routine-call-default]
== Allow `DEFAULT` Keyword in Argument List
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/7566[#7566]

The keyword `DEFAULT` can now be used in an argument list of a function or procedure call to explicitly use its default value (or that of its domain).
If the parameter or its domain has no default, the actual argument value is `NULL`.

.Example
[listing]
----
select function_name(1, DEFAULT, DEFAULT, 'Something')
from rdb$database;
----

[#rnfb60-dml-named-args]
== Named Arguments for Function and Procedure Calls
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/7586[#7586]

Named arguments allows you to specify function and procedure arguments by name, rather than by position.

This is especially useful when a routine has a lot of parameters, you want to specify arguments in a different order, or not specify those with default values.

.Syntax
[listing,subs=+quotes]
----
<function call> ::=
  [_schema_ .] [_package_ .] _function_ ( [<arguments>] )

<procedure selection> ::=
  [_schema_ .] [_package_ .]  _procedure_ [( <arguments> )]

<execute procedure> ::=
  EXECUTE PROCEDURE [_schema_ .] [_package_ .] _procedure_
    [ (<arguments>) | <arguments> ]
    [RETURNING_VALUES ...]

<arguments> ::=
    <positional arguments>
  | [ <positional arguments> , ] <named arguments>

<positional arguments> ::=
  <value> [ { , <value> }... ]

<named arguments> ::=
  <named argument> [ { , <named argument> }... ]

<named argument> ::=
  _argument-name_ => <value>
----

Like the positional syntax, all arguments without default values are required.

A call can use positional, named, or mixed arguments.
In mixed syntax, positional arguments must appear before named arguments.

.Examples
[listing]
----
select function_name(parameter2 => 'Two', parameter1 => 1)
from rdb$database;

select function_name(1, parameter2 => 'Two')
from rdb$database;

execute procedure insert_customer(
  last_name => 'SCHUMACHER',
  first_name => 'MICHAEL');

select *
from get_customers(city_id => 10, last_name => 'SCHUMACHER');
----

[#rnfb60-dml-call-stmt]
== `CALL` Statement for Executing Procedures
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/7587[#7587]

The `CALL` statement is similar to `EXECUTE PROCEDURE`, but allows the caller to only get specific output parameters, or none.

.Syntax
[listing,subs=+quotes]
----
CALL [ _schema_ . ] [ _package_ .] _procedure_ (<arguments>)

<arguments> ::=
    <positional arguments> |
    [ <positional arguments> , ] <named arguments>

<positional arguments> ::=
    <value or default> [ { , <value or default> }... ]

<named arguments> ::=
    <named argument> [ { , <named argument> }... ]

<named argument> ::=
    _argument-name_ => <value or default>

<value or default> ::= <value> | DEFAULT
----

When using positional arguments, output parameters follow after the input parameters.

In DSQL, output parameters are specified using `?`.
In PSQL, using the names of the target variables.

To exclude an output parameter as a positional argument, pass `NULL`, or only reference the desired output parameters using named argument syntax.

When used with selectable stored procedures, only the first row is returned, and the stored procedure exits after the first `SUSPEND`.
This is the same behaviour as with `EXECUTE PROCEDURE`.

.Examples
[source]
----
set term #;
create or alter procedure insert_customer (
  last_name varchar(30),
  first_name varchar(30))
returns (
  id integer,
  full_name varchar(62))
as
begin
  insert into customers (last_name, first_name)
    values (:last_name, :first_name)
    returning id, last_name || ', ' || first_name
    into :id, :full_name;
end#
set term ;#

-- Not all output parameters are necessary.
call insert_customer(
  'LECLERC',
  'CHARLES',
  ?);

-- Ignore first output parameter (using NULL) and get the second.
call insert_customer(
  'LECLERC',
  'CHARLES',
  null,
  ?);

-- Ignore ID output parameter.
call insert_customer(
  'LECLERC',
  'CHARLES',
  full_name => ?);

-- Pass inputs and get outputs using named arguments.
call insert_customer(
  last_name => 'LECLERC',
  first_name => 'CHARLES',
  last_name => ?,
  id => ?);

set term #;
create or alter procedure do_something_and_insert_customer returns (
  out_id integer,
  out_full_name varchar(62))
as
  declare last_name varchar(30);
  declare first_name varchar(30);
begin
  call insert_customer(
    last_name,
    first_name,
    out_id,
    full_name => out_full_name);
end#
set term ;#
----

[#rnfb60-dml-context-system]
== New `SYSTEM` Variables in `RDB$GET_CONTEXT()`

The following variables were added to the `SYSTEM` context of `RDB$GET_CONTEXT`:

`PAGES_ALLOCATED`::
Number of allocated database pages

`PAGES_FREE`::
Number of free (unused) database pages

`PAGES_USED`::
Number of used database pages

[#rnfb60-dml-built-in-functions]
== New Expressions and Built-in Functions

[#rnfb60-dml-any-value]
=== `ANY_VALUE` Aggregate Function
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/7617[#7617]

`ANY_VALUE` is a SQL:2023 non-deterministic aggregate function that returns the result of an expression applied to an arbitrary row in the group.

.Syntax
[listing]
----
ANY_VALUE ( <expr> )
----

This function only returns `NULL` if there is no row in the group where _expr_ produces a non-``NULL`` result.

.Example
[listing]
----
select
  DEPT_NO,
  any_value(FIRST_NAME || ' ' || LAST_NAME) "Example Employee"
from EMPLOYEE
group by DEPT_NO
----

[#rnfb60-dml-gen-uuid-v7]
=== Support UUID Version 7 Generation With `GEN_UUID`
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/7980[#7980]

Support for UUID version 7 generation was added to `GEN_UUID`.
The `GEN_UUID` function now accepts an optional parameter to specify the UUID version.

.Syntax
[listing,subs=+quotes]
----
GEN_UUID ( [_version_] )
----

The optional parameter _version_ accepts an integer expression, but results other than `4` or `7` raise an error.
If _version_ is not specified, it uses `4`, just like in previous Firebird versions.

.Supported versions
[horizontal.compact]
`4`::
UUID from truly random or pseudorandom numbers (except version and variant bits)
`7`::
UUID with the first 48 bits milliseconds since midnight 1 Jan 1970 UTC (Unix Epoch), and the remaining 74 bits -- except version and variant bits -- from truly random or pseudorandom numbers
+
Version 7 has the advantage that the UUID value is time-ordered (with millisecond precision).

Other UUID versions are not supported by `GEN_UUID`.

See also https://www.rfc-editor.org/rfc/rfc9562[RFC 9562 -- Universally Unique IDentifiers (UUIDs)^]

.Examples
----
-- Implicit version 4
select gen_uuid() from rdb$database;
-- Example: 701396BB8E814F9681BA88B6F4AEF3B7

-- Explicit version 4
select gen_uuid(4) from rdb$database;
-- Example: F6034BC70DE142C0BA2D81F40FDD7579

-- Explicit version 7
select gen_uuid(7) from rdb$database;
-- Example: 019C51802A227E9DB1F9E495396B9A9F
----

[#rnfb60-dml-multi-trim]
=== Multi-character Trim Functions: `BTRIM`, `LTRIM`, `RTRIM`
https://github.com/MrTeeett[MrTeeett^]

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8015[#8015]

The multi-character trim functions -- `BTRIM`, `LTRIM`, `RTRIM` -- return their first argument with leading, trailing, or both leading and trailing characters removed.
The second argument specifies the characters to be trimmed.
In contrast to the existing `TRIM` function, these functions will remove any of the specified trim characters, regardless of their ordering.

.What is Trimmed
[horizontal.compact]
`BTRIM`:: **B**oth leading and trailing characters
`LTRIM`:: Leading (**L**eft) characters
`RTRIM`:: Trailing (**R**ight) characters

These functions are specified in the SQL standard (SQL:2023).

.Syntax
[listing]
----
{ BTRIM | LTRIM | RTRIM } ( <value> [ , <trim-character> ] )
----

If _trim-character_ is not specified, _space_ is used as trim character.

.Example
[source]
----
select ltrim('baobab is a tree', 'aboe')
from RDB$DATABASE;
-- ' is a tree'
----
