[#rnfb60-dml]
= Data Manipulation Language (DML)

[#rnfb60-dml-links]
.Quick Links
* <<rnfb60-dml-schema>>
** <<rnfb60-dml-schema-current>>
* <<rnfb60-dml-cast>>
** <<rnfb60-dml-cast-format>>
** <<rnfb60-dml-cast-collate>>
* <<rnfb60-dml-routine-call-default>>
* <<rnfb60-dml-named-args>>
* <<rnfb60-dml-call-stmt>>
* <<rnfb60-dml-using>>
* <<rnfb60-dml-context-system>>
* <<rnfb60-dml-built-in-functions>>
** <<rnfb60-dml-any-value>>
** <<rnfb60-dml-gen-uuid-v7>>
** <<rnfb60-dml-multi-trim>>
** <<rnfb60-dml-greatest>>
** <<rnfb60-dml-least>>
** <<rnfb60-dml-within-group>>
** <<rnfb60-dml-listagg>>
** <<rnfb60-dml-inv-dist,Inverse Distribution Functions>>
*** <<rnfb60-dml-perc-cont>>
*** <<rnfb60-dml-perc-disc>>

////
Generic template:

[#rnfb60-dml-<abbreviated-subject>]
== <subject>
<implementer/author>

Tracker ticket: https://github.com/FirebirdSQL/firebird/[pull/]<issue>[#<issue>]

<short description>

.Syntax
[listing]
----
<syntax>
----

[<more details>]

.Examples
[listing]
----
<examples>
----

////

[#rnfb60-dml-schema]
== Changes to DML For Schema Support
Adriano dos Santos Fernandes

.See also
* <<rnfb60-engine-schema>> in chapter _Changes in the Firebird Engine_
* <<rnfb60-msql-search-path>>
* <<rnfb60-compat-schema>>

[#rnfb60-dml-schema-current]
=== New Context Variable `CURRENT_SCHEMA`

`CURRENT_SCHEMA` returns the name of the first valid schema (i.e. it exists) in the search path of the current session.
If no valid user schema exists, it returns `SYSTEM`.
In theory, it could return `NULL`, but as `SYSTEM` is always added to the search path, this should not happen in practice.

.Example
[source]
----
select CURRENT_SCHEMA from RDB$DATABASE;
----

[#rnfb60-dml-schema-context]
=== Additions to `RDB$GET_CONTEXT()`

Function `RDB$GET_CONTEXT()` received additional variables:

[horizontal.compact]
`DDL_TRIGGER`::
`SCHEMA_NAME`

`SYSTEM`::
`CURRENT_SCHEMA`, `SEARCH_PATH`

.See also
* <<rnfb60-dml-context-system>>
* <<rnfb60-dml-context-ddl-trigger>>

[#rnfb60-dml-schema-field]
=== Schema Qualification of Field Names

Field names can now be qualified with the schema, in addition to aliases or table names.
This includes cases where the schema is implicitly determined by the search path.
It is also possible to qualify the table name with the schema and refer to the field using just the table name.
For example:

[source]
----
create schema SCHEMA1;

create table SCHEMA1.TABLE1 (ID integer);

set search_path to SCHEMA1;

select TABLE1.ID from SCHEMA1.TABLE1;
select SCHEMA1.TABLE1.ID from TABLE1;
select SCHEMA1.TABLE1.ID from SCHEMA1.TABLE1;
----

If the same table name exists in multiple schemas, fields must be qualified with schema names or table aliases to avoid ambiguity.
For example:

[source]
----
create schema SCHEMA1;
create schema SCHEMA2;

create table SCHEMA1.TABLE1 (ID integer);
create table SCHEMA2.TABLE1 (ID integer);

select SCHEMA1.TABLE1.ID, SCHEMA2.TABLE1.ID
from SCHEMA1.TABLE1, SCHEMA2.TABLE1;

select S1.ID, S2.ID
from SCHEMA1.TABLE1 S1, SCHEMA2.TABLE1 S2;
----

[#rnfb60-dml-schema-name-res]
=== Name Resolution

With the introduction of schemas, the syntax `_identifier_._identifier_` -- used for tables, views, procedures, and functions (both standalone and packaged) -- introduces ambiguity when resolving object names using the schema search path.
The ambiguity arises between:

- `_schema_._object_` (a schema and its object)
- `_package_._object_` (a package and its object)

This section focuses on name resolution rules for tables, views, procedures, and functions within queries and code blocks.

[#rnfb60-dml-schema-name-res-scope]
==== Scope specifier (`%`)

To resolve these ambiguities, Firebird introduces a _scope specifier_, represented by the `%` symbol.
The scope specifier allows unambiguous referencing of objects.

.Syntax
[listing,subs=+quotes]
----
_identifier_ % { SCHEMA | PACKAGE } . _identifier_
----

.Examples
[source]
----
select *
from PLG$PROFILER%schema.PLG$PROF_SESSIONS;

execute procedure PLG$PROFILER%package.PAUSE_SESSION;

call PLG$PROFILER%package.PAUSE_SESSION();

select RDB$TIME_ZONE_UTIL%package.DATABASE_VERSION()
from SYSTEM%schema.RDB$DATABASE;

select *
from RDB$TIME_ZONE_UTIL%package.TRANSITIONS(
    'America/Sao_Paulo',
    timestamp '2017-01-01', timestamp '2019-01-01');
----

[#rnfb60-dml-schema-name-res-rule]
==== Detailed Name Resolution Rules

Firebird resolves object names following a structured sequence of rules.
Once an object is located, the resolution process halts, ensuring no ambiguity errors occur.

`NAME1.NAME2.NAME3`::
. Look for routine `NAME3` inside package `NAME2`, inside schema `NAME1`.

`NAME1%schema.NAME2`::
. Look for object `NAME2` inside schema `NAME1`.

`NAME1%package.NAME2`::
. Look for object `NAME2` inside a package `NAME1` using the schema search path.

`NAME1.NAME2`::
. If inside a package named `NAME1`, look for routine `NAME2` in the same package.
. Look in schema `NAME1` for object `NAME2`.
. Look for object `NAME2` inside a package `NAME1` using the schema search path.

`NAME`::
. If inside a routine, look for subroutine `NAME`.
. If inside a package, look for routine `NAME` in the same package.
. Look for object `NAME` using the schema search path.

[NOTE]
====
Object resolution also depends on the context in which they are used.
For example, in `select * from NAME1.NAME2`, `NAME2` could be a table, view, or procedure.
However, in `execute procedure NAME1.NAME2`, `NAME2` must be a procedure.
This distinction means that an `execute procedure` statement versus a `select` statement can resolve to different objects.
====

[#rnfb60-dml-schema-plan]
=== Plans

// TODO Does this belong in DML, or should it go to engine?

Plans -- both legacy and detailed -- now include schema names in their output, resulting in slight changes to their format.

For example, the query below:

[source]
----
with q1 as (
    select *
        from t1
),
q2 as (
    select *
        from q1
)
select *
    from q2 x;
----

Previously, this produced the following plans:

[source]
----
PLAN (X Q1 T1 NATURAL)

Select Expression
    -> Table "T1" as "X Q1 T1" Full Scan
----

Now, the plans explicitly include the schema, and each name is quoted separately:

[source]
----
PLAN ("X" "Q1" "PUBLIC"."T1" NATURAL)

Select Expression
    -> Table "PUBLIC"."T1" as "X" "Q1" "PUBLIC"."T1" Full Scan
----

[#rnfb60-dml-cast]
== Changes to `CAST` Function

[#rnfb60-dml-cast-format]
=== Datetime `FORMAT` Clause For `CAST`
Artyom Ivanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/2388[#2388]

The `CAST` function now has the SQL-standard `FORMAT` clause for casting between string types and datetime types.
This allows custom formatting of datetime values, and conversion from string values with a specific format to datetime values.

.Syntax
[listing]
----
<cast specification> ::=
  CAST ( <cast-operand> AS <cast-target>
         [ FORMAT <cast-template> ] )

<cast-template> ::=
  <character string literal>
----

.Syntax of cast-template
[listing]
----
<datetime-template> ::=
  { <datetime-template-part> }...

<datetime-template-part> ::=
    <datetime-template-field>
  | <datetime-template-delimiter>

<datetime-template-field> ::=
  !! See tables in following sections !!

<datetime-template-delimiter> ::=
  !! See tables in following sections !!
----

[#rnfb60-dml-cast-format-parse]
==== Formatting and Parsing Datetime Values

The `FORMAT` clause serves two purposes:

. Converting a datetime value to a string
. Parsing a string value to a datetime value

The _cast-template_ of the `FORMAT` clause specifies how the datetime should be converted to string, or how the string should be parsed to a datetime.
Conversion to string offers more options and flexibility than conversion to datetime.

The _cast-template_ must be a string literal, and has the following template fields:

.Cast Template Fields
[cols="<1m,<4", options="header",stripes="none"]
|===
|Format Pattern
|Description

|YEAR
|Year (1 - 9999)

|YYYY
|Last 4 digits of year (0001 - 9999)

|YYY
|Last 3 digits of year (000 - 999)

|YY
|Last 2 digits of year (00 - 99)

|Y
|Last digit of year (0 - 9)

|RR / RRRR
a|Round Year (further information <<rnfb60-dml-cast-format-rr,below>>) +
Only string to datetime

|Q
a|Quarter of the year (1 - 4) +
Only datetime to string

|MM
|Month (01 - 12)

|MON
|Short month name (e.g. `Apr`)

|MONTH
|Full month name (e.g. `APRIL`)

|RM
|Roman number of the month (`I` - `XII`)

|WW
a|Week of the year (`01` - `53`) +
Only datetime to string

Exercise caution when combining with year.
For example, 2023-01-01 is week 52 2022, but there is no week-based year template variable, and ``'WW YYYY'`` renders `52 2023`!

|W
a|Week of the month (`1` - `5`) +
Only datetime to string

Week 1 starts at day 1, week 2 at day 8, week 3 at day 15, week 4 for at day 22 and week 5 at day 29.

|D
a|Day of the week (`1` - `7`) +
Only datetime to string

`1` is Sunday, `7` is `Saturday`

|DAY
a|Full name of the day (e.g. `MONDAY`) +
Only datetime to string

|DY
|Short name of the day (e.g. `Mon`)

|DD
|Day of the month (`01` - `31`)

|DDD
a|Day of the Year (`001` - `366`) +
Only datetime to string

|J
|Julian Day (number of days since January 1, 4712 BC)

|HH / HH12
a|Hour of the day (`01` - `12`) without AM/PM period.

When converting from string to datetime, specifying template-field `A.M.` or `P.M.` is required.

|HH24
|Hour of the day (`00` - `23`)

|MI
|Minutes (`00` - `59`)

|SS
|Seconds (`00` - `59`)

|SSSSS
|Seconds since midnight (`0` - `86399`)

|FF1 - FF9
a|Fractional seconds with the specified accuracy. +
When converting from string to datetime, only `FF1` - `FF4` are supported.

For `FF5` - `FF9`, digits 5 - 9 are _always_ `0`.

|A.M. / P.M.
a|AM/PM period for 12 hours time. +
Either can be used, and will parse `A.M.` and `P.M.`, or render `A.M.` or `P.M.` depending on the actual time.

|TZH
|Time zone in hours (`-14` - `14`)

|TZM
|Time zone in minutes (`00` - `59`)

|TZR
|Time zone name or time zone displacement (same as `TZH:TZM`)

|===

Most of these template fields are defined by the SQL standard, but some are non-standard extensions.
The template fields are case-insensitive, so `YYYY-MM` is the same as `yyyy-mm`.

The template fields can be separated with the following delimiters:

.Cast Template Delimiters
[cols="<m", options="header",stripes="none"]
|===
|Delimiter

|-
|++.++
|/
|,
|;
|:
|<space>

|===

Contrary to the SQL standard, a single quote (apostrophe) is not supported as a delimiter.
// TODO Reopened https://github.com/FirebirdSQL/firebird/issues/2388 to report this, update above if needed

When converting from datetime to string, it is possible to insert raw text into a format string with double quotes: `... FORMAT '"Today is" DAY'` -> `Today is MONDAY`.
To render `"`, escape it with `\`, i.e. use `\"`, and to render `\`, use `\\`.

Example:

[listing]
----
SELECT CAST(CURRENT_TIMESTAMP AS VARCHAR(45)
  FORMAT 'DD.MM.YEAR HH24:MI:SS "is" J "Julian day"')
FROM RDB$DATABASE;
=========================
14.6.2023 15:41:29 is 2460110 Julian day
----

Patterns can be used without any separators:

[listing]
----
SELECT CAST(CURRENT_TIMESTAMP AS VARCHAR(50)
  FORMAT 'YEARMMDD HH24MISS')
FROM RDB$DATABASE;
=========================
20230719 161757
----

However, be careful with patterns with repeating characters, for example `DDDDD` will be interpreted as `DDD` + `DD`.

[#rnfb60-dml-cast-format-to-dt]
===== Converting from String to Datetime

When converting from string to datetime, additional rules and limitations apply:

* If the target type has a date component, and year, month or day are not set by the pattern, the missing parts will get their values from the current date
* If the target type has a time component, and hours, minutes, seconds, or fractions are not set by the pattern, the missing parts will be set to `0`
* [[rnfb60-dml-cast-format-rr]]Behaviour of `RR` (two-digit Round Year):
** If the specified two-digit year is 00 to 49, then
*** If the last two digits of the current year are 00 to 49, then the returned year has the same first two digits as the current year.
*** If the last two digits of the current year are 50 to 99, then the first 2 digits of the returned year are 1 greater than the first 2 digits of the current year.
** If the specified two-digit year is 50 to 99, then
*** If the last two digits of the current year are 00 to 49, then the first 2 digits of the returned year are 1 less than the first 2 digits of the current year.
*** If the last two digits of the current year are 50 to 99, then the returned year has the same first two digits as the current year.
* Behaviour of `RRRR` (4-digit Round Year): Accepts either 4-digit or 2-digit input.
If 2-digit, it provides the same result as `RR`.
If you do not want this functionality, then enter a 4-digit year.

Example:

[listing]
----
SELECT CAST('2000.12.08 12:35:30.5000' AS TIMESTAMP
  FORMAT 'YEAR.MM.DD HH24:MI:SS.FF4')
FROM RDB$DATABASE;
=====================
2000-12-08 12:35:30.5000
----

[#rnfb60-dml-cast-collate]
=== `COLLATE` Clause in Cast
Dimitry Sibiryakov

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/7748[#7748]

As a result of <<rnfb60-ddl-datatype-collate>>, `CAST` now accepts the `COLLATE` clause for character types.

[#rnfb60-dml-routine-call-default]
== Allow `DEFAULT` Keyword in Argument List
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/7566[#7566]

The keyword `DEFAULT` can now be used in an argument list of a function or procedure call to explicitly use its default value (or that of its domain).
If the parameter or its domain has no default, the actual argument value is `NULL`.

.Example
[listing]
----
select function_name(1, DEFAULT, DEFAULT, 'Something')
from rdb$database;
----

[#rnfb60-dml-named-args]
== Named Arguments for Function and Procedure Calls
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/7586[#7586]

Named arguments allows you to specify function and procedure arguments by name, rather than by position.

This is especially useful when a routine has a lot of parameters, you want to specify arguments in a different order, or not specify those with default values.

.Syntax
[listing,subs=+quotes]
----
<function call> ::=
  [_schema_ .] [_package_ .] _function_ ( [<arguments>] )

<procedure selection> ::=
  [_schema_ .] [_package_ .]  _procedure_ [( <arguments> )]

<execute procedure> ::=
  EXECUTE PROCEDURE [_schema_ .] [_package_ .] _procedure_
    [ (<arguments>) | <arguments> ]
    [RETURNING_VALUES ...]

<arguments> ::=
    <positional arguments>
  | [ <positional arguments> , ] <named arguments>

<positional arguments> ::=
  <value> [ { , <value> }... ]

<named arguments> ::=
  <named argument> [ { , <named argument> }... ]

<named argument> ::=
  _argument-name_ => <value>
----

Like the positional syntax, all arguments without default values are required.

A call can use positional, named, or mixed arguments.
In mixed syntax, positional arguments must appear before named arguments.

.Examples
[listing]
----
select function_name(parameter2 => 'Two', parameter1 => 1)
from rdb$database;

select function_name(1, parameter2 => 'Two')
from rdb$database;

execute procedure insert_customer(
  last_name => 'SCHUMACHER',
  first_name => 'MICHAEL');

select *
from get_customers(city_id => 10, last_name => 'SCHUMACHER');
----

[#rnfb60-dml-call-stmt]
== `CALL` Statement for Executing Procedures
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/7587[#7587]

The `CALL` statement is similar to `EXECUTE PROCEDURE`, but allows the caller to only get specific output parameters, or none.

.Syntax
[listing,subs=+quotes]
----
CALL [ _schema_ . ] [ _package_ .] _procedure_ (<arguments>)

<arguments> ::=
    <positional arguments> |
    [ <positional arguments> , ] <named arguments>

<positional arguments> ::=
    <value or default> [ { , <value or default> }... ]

<named arguments> ::=
    <named argument> [ { , <named argument> }... ]

<named argument> ::=
    _argument-name_ => <value or default>

<value or default> ::= <value> | DEFAULT
----

When using positional arguments, output parameters follow after the input parameters.

In DSQL, output parameters are specified using `?`.
In PSQL, using the names of the target variables.

To exclude an output parameter as a positional argument, pass `NULL`, or only reference the desired output parameters using named argument syntax.

When used with selectable stored procedures, only the first row is returned, and the stored procedure exits after the first `SUSPEND`.
This is the same behaviour as with `EXECUTE PROCEDURE`.

.Examples
[source]
----
set term #;
create or alter procedure insert_customer (
  last_name varchar(30),
  first_name varchar(30))
returns (
  id integer,
  full_name varchar(62))
as
begin
  insert into customers (last_name, first_name)
    values (:last_name, :first_name)
    returning id, last_name || ', ' || first_name
    into :id, :full_name;
end#
set term ;#

-- Not all output parameters are necessary.
call insert_customer(
  'LECLERC',
  'CHARLES',
  ?);

-- Ignore first output parameter (using NULL) and get the second.
call insert_customer(
  'LECLERC',
  'CHARLES',
  null,
  ?);

-- Ignore ID output parameter.
call insert_customer(
  'LECLERC',
  'CHARLES',
  full_name => ?);

-- Pass inputs and get outputs using named arguments.
call insert_customer(
  last_name => 'LECLERC',
  first_name => 'CHARLES',
  last_name => ?,
  id => ?);

set term #;
create or alter procedure do_something_and_insert_customer returns (
  out_id integer,
  out_full_name varchar(62))
as
  declare last_name varchar(30);
  declare first_name varchar(30);
begin
  call insert_customer(
    last_name,
    first_name,
    out_id,
    full_name => out_full_name);
end#
set term ;#
----

[#rnfb60-dml-using]
== The `USING` Statement
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/8869[#8869]

[#rnfb60-dml-using-overview]
=== Overview

The `USING` statement is a new DSQL extension designed to bridge the gap between standard DSQL statements and the powerful but verbose `EXECUTE BLOCK`.

When adapting a standard DSQL command to use `EXECUTE BLOCK` (for instance, to utilize sub-routines or reuse a single input parameter in multiple places), the developer is currently forced to explicitly declare all input parameters and, more tediously, all output fields.

The `USING` statement simplifies this workflow.
It provides the ability to declare parameters, sub-routines and variables while allowing the engine to infer outputs automatically from the contained SQL command.

[#rnfb60-dml-using-syntax]
=== Syntax

[listing]
----
USING [ ( <input_parameter_list> ) ]
    [ <local_declarations> ]
DO <sql_command>
----

At least one of `<input_parameter_list>` or `<local_declarations>` must be present.
A `USING DO ...` statement without parameters *and* without local declarations is invalid.

[#rnfb60-dml-using-syntax-comp]
==== Components

`<input_parameter_list>`::
A strictly typed list of parameters.
These can be bound to values using the `?` placeholder.
`<local_declarations>`::
Standard PSQL local declarations (variables, sub-functions and sub-procedures).
`<sql_command>`::
The DSQL statement to execute.
Supported statements include:
* `SELECT`
* `INSERT` (with or without `RETURNING`)
* `UPDATE` (with or without `RETURNING`)
* `UPDATE OR INSERT` (with or without `RETURNING`)
* `DELETE` (with or without `RETURNING`)
* `MERGE` (with or without `RETURNING`)
* `CALL`
* `EXECUTE PROCEDURE`

[#rnfb60-dml-using-feat]
=== Key Features

Inferred Outputs::
Unlike `EXECUTE BLOCK`, you do not need to explicitly declare a `RETURNS (...)` clause.
The output columns are automatically inferred from the `<sql_command>` in the `DO` clause.

Statement Type Transparency::
The API returns the statement type of the inner `<sql_command>` (e.g. if the inner command is a `SELECT`, the API reports it as a `SELECT` statement).

Parameter Reuse::
Input parameters declared in the `USING` clause can be used multiple times within the script using named references (e.g., `:p1`), while only requiring a single bind from the client application.

Mixed Parameter Binding::
You can mix declared parameters (bound via `?` in the declaration) and direct positional parameters (using `?` inside the `DO` command).

[#rnfb60-dml-using-ex]
=== Examples

[float]
==== Basic Parameter Reuse and Local Declarations

This example demonstrates declaring typed parameters, defining sub-routines, and using them in a query.

[source]
----
using (p1 integer = ?, p2 integer = ?)  <1>
  -- Declare a local function
  declare function subfunc (i1 integer)
    returns integer
  as
  begin
    return i1;
  end

  -- Declare a local procedure
  declare procedure subproc (i1 integer)
    returns (o1 integer)
  as
  begin
    o1 = i1;
    suspend;
  end
do
-- The main query
select subfunc(:p1) + o1                <3>
  from subproc(:p2 + ?)                 <2>
----
<1> The client binds values to `p1` and `p2`.
<2> The client binds a third value to the `?` inside the `DO` clause.
<3> The result set structure is inferred from the `SELECT` statement.

[float]
==== Simplifying Parameter Reuse

Without `USING`, inserting the same bind value into multiple columns requires sending the data twice.

.Standard DSQL
[listing]
----
insert into generic_table (col_a, col_b) values (?, ?);
-- Client must bind: [100, 100]
----

.With `USING`
[listing]
----
using (val integer = ?)
do insert into generic_table (col_a, col_b) values (:val, :val);
-- Client binds: [100]
----

[float]
==== `EXECUTE STATEMENT` with Named Parameters

[listing]
----
execute block returns (ri integer, rs varchar(20))
as
begin
  execute statement
    ('using(i int = ?, s varchar(20) = ?) '
     'do select :i, :s from rdb$database')
    (s := '2', i := 1) into ri, rs;
  suspend;
end
----

[float]
==== `EXECUTE STATEMENT` with Unnamed Parameters

[listing]
----
execute block returns (ri integer, rs varchar(20))
as
begin
  execute statement
    ('using(i int = ?, s varchar(20) = ?) '
     'do select :i, :s from rdb$database')
    (1, '2') into ri, rs;
  suspend;
end
----

[#rnfb60-dml-using-cmp]
=== Comparison

[%header,cols="h,1,1,1"]
|===
|Feature
|Standard DSQL
|`EXECUTE BLOCK`
|`USING`

|Local Declarations
|No
|Yes
|Yes

|Input Declarations
|Implicit (positional)
|Explicit
|Hybrid (implicit and explicit)

|Output Declarations
|Inferred
|Explicit (`RETURNS`)
|Inferred

|Verbosity
|Low
|High
|Medium

|Use Case
|Simple queries
|Complex logic, loops, explicit result set definition
|Reusing params, variables, sub-routines, standard queries

|===

[#rnfb60-dml-context-system]
== New `SYSTEM` Variables in `RDB$GET_CONTEXT()`

The following variables were added to the `SYSTEM` context of `RDB$GET_CONTEXT`:

`CURRENT_SCHEMA`::
Current schema (same as <<rnfb60-dml-schema-current,CURRENT_SCHEMA>>)

`PAGES_ALLOCATED`::
Number of allocated database pages

`PAGES_FREE`::
Number of free (unused) database pages

`PAGES_USED`::
Number of used database pages

`SEARCH_PATH`::
Search path of the current session (including invalid (nonexistent) schemas).
+
To get separate rows with schema names, you can use <<rnfb60-engine-sql-parse-unqualified-names>>:
+
[source]
----
select NAME
from SYSTEM.RDB$SQL.PARSE_UNQUALIFIED_NAMES(RDB$GET_CONTEXT('SYSTEM', 'SEARCH_PATH'))
----

[#rnfb60-dml-context-ddl-trigger]
== New `DDL_TRIGGER` Variables in `RDB$GET_CONTEXT()`

The following variables were added to the `DDL_TRIGGER` context of `RDB$GET_CONTEXT`:

`SCHEMA_NAME`::
Schema of the affected object within a DDL trigger.

[#rnfb60-dml-built-in-functions]
== New Expressions and Built-in Functions

[#rnfb60-dml-any-value]
=== `ANY_VALUE` Aggregate Function
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/7617[#7617]

`ANY_VALUE` is a SQL:2023 non-deterministic aggregate function that returns the result of an expression applied to an arbitrary row in the group.

.Syntax
[listing]
----
ANY_VALUE ( <expr> )
----

This function only returns `NULL` if there is no row in the group where _expr_ produces a non-``NULL`` result.

.Example
[listing]
----
select
  DEPT_NO,
  any_value(FIRST_NAME || ' ' || LAST_NAME) "Example Employee"
from EMPLOYEE
group by DEPT_NO
----

[#rnfb60-dml-gen-uuid-v7]
=== Support UUID Version 7 Generation With `GEN_UUID`
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/7980[#7980]

Support for UUID version 7 generation was added to `GEN_UUID`.
The `GEN_UUID` function now accepts an optional parameter to specify the UUID version.

.Syntax
[listing,subs=+quotes]
----
GEN_UUID ( [_version_] )
----

The optional parameter _version_ accepts an integer expression, but results other than `4` or `7` raise an error.
If _version_ is not specified, it uses `4`, just like in previous Firebird versions.

.Supported versions
[horizontal.compact]
`4`::
UUID from truly random or pseudorandom numbers (except version and variant bits)
`7`::
UUID with the first 48 bits milliseconds since midnight 1 Jan 1970 UTC (Unix Epoch), and the remaining 74 bits -- except version and variant bits -- from truly random or pseudorandom numbers
+
Version 7 has the advantage that the UUID value is time-ordered (with millisecond precision).

Other UUID versions are not supported by `GEN_UUID`.

See also https://www.rfc-editor.org/rfc/rfc9562[RFC 9562 -- Universally Unique IDentifiers (UUIDs)^]

.Examples
----
-- Implicit version 4
select gen_uuid() from rdb$database;
-- Example: 701396BB8E814F9681BA88B6F4AEF3B7

-- Explicit version 4
select gen_uuid(4) from rdb$database;
-- Example: F6034BC70DE142C0BA2D81F40FDD7579

-- Explicit version 7
select gen_uuid(7) from rdb$database;
-- Example: 019C51802A227E9DB1F9E495396B9A9F

-- Unsupported version
select gen_uuid(3) from RDB$DATABASE;
-- Statement failed, SQLSTATE = 42000
-- Invalid GEN_UUID version (3). Must be 4 or 7

----

[#rnfb60-dml-bit-agg]
=== Bitwise Aggregate Functions (`BIN_AND_AGG`, `BIN_OR_AGG`, and `BIN_XOR_AGG`)
Denis Simonov

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/8175[#8175]

The `BIN_AND_AGG`, `BIN_OR_AGG`, and `BIN_XOR_AGG` aggregate functions perform bit operations.

`NULLs` are ignored.
It's returned only if the group is empty, or if all evaluated records have a `NULL` value.

The input argument must be one of the integer types (`SMALLINT`, `INTEGER`, `BIGINT`, or `INT128`).
The output result is of the same type as the input argument.

.Syntax
[listing]
----
BIN_AND_AGG(<expression>)
BIN_OR_AGG(<expression>)
BIN_XOR_AGG([ALL | DISTINCT] <expression>)
----

The `BIN_AND_AGG` and `BIN_OR_AGG` functions do not support the `ALL` or `DISTINCT` keywords, since eliminating duplicates does not affect the result.
For `BIN_XOR_AGG`, you can specify `ALL` -- the default if not specified, or `DISTINCT` to exclude duplicates from processing, as there duplicates can affect the result.

.Example
[source]
----
SELECT
  name,
  BIN_AND_AGG(n) AS F_AND,
  BIN_OR_AGG(n) AS F_OR,
  BIN_XOR_AGG(n) AS F_XOR,
  BIN_XOR_AGG(ALL n) AS F_XOR_A,
  BIN_XOR_AGG(DISTINCT n) AS F_XOR_D
FROM acl_masks
GROUP BY name
----

[#rnfb60-dml-unlist]
=== Table-valued Function `UNLIST`
Alex Chudaykin

Tracker tickets:
https://github.com/FirebirdSQL/firebird/issues/8005[#8005]
https://github.com/FirebirdSQL/firebird/issues/8580[#8580]

The `UNLIST` function is a table-valued function which splits its input into multiple rows with a single column.
It does the opposite of aggregate functions `LIST`/`LISTAGG`.

.Syntax
[listing,subs=+quotes]
----
UNLIST ( _input_ [ , _separator_ ] [<unlist-type-conversion>] )
  [AS] <correlation-name> [ (_column-name_) ]

<type-conversion> ::= RETURNING <domain_or_non_array_type>

<domain_or_non_array_type> ::=
  !! See _Scalar Data Types Syntax_ in the Firebird Language Reference !!
----

.`UNLIST` Function Parameters
[cols="<1m,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|input
|Expression of a string or blob type;
input to be split.

|separator
a|Expression of a string or blob type;
separator (delimiter) of the input.
If not specified, `,` (comma) is used.

Length cannot exceed 32KiB.

|domain_or_non_array_type
|Datatype of the output column.
Behaves as if `CAST` is applied with the specified type.

If not specified, `CHAR(32)` is used with the same character set as _input_.
// TODO Might change, some discussions said it should be VARCHAR(60); double check after #8580 is done

|correlation-name
|Name of the derived table produced by `UNLIST` (required!)

|column-name
|Name of the column of the derived table.

Depending on the use of the derived table, specifying the column-name may be required.
If not specified, the column does not receive a name, but the column will have the alias `UNLIST` when used in a top-level `FROM` clause.

|===

.Table-valued Functions
[sidebar]
****
A table-valued function is a function that produces a (derived) table.
That is, the result returned has zero or more rows with one or more columns.

For comparison, Firebird's selectable stored procedures are a form of user-defined table-valued functions.
****

.Ambiguity With Stored Procedures Called `UNLIST`
[WARNING]
====
`UNLIST` is not a reserved word, and this can result in ambiguity if a stored procedure `UNLIST` exists on the search path.
Firebird will use the `UNLIST` built-in function for calls with one or two arguments *if* the correlation clause (`AS ...`) is present.
For three or more arguments, it will call the stored procedure `UNLIST`.

However, if you leave out the correlation clause, it will select from the procedure `UNLIST`, which might be unexpected.

If you need to select from a selectable stored procedure `UNLIST` with one or two arguments *and* have to provide a correlation, then you need to qualify the procedure with its schema (e.g. `PUBLIC.UNLIST`).
====

[discrete]
==== `IN UNLIST (...)`

With `IN`, a shorter form of `UNLIST` can be used:

.Syntax
[listing,subs=+quotes]
----
<in-predicate> ::= <value> [NOT] IN <in-source>

<in_source> ::=
    ( <select_stmt> ) !! Existing syntax !!
  | ( <value_list> )  !! Existing syntax !!
  | <unlist-short>

<unlist-short> ::=
  UNLIST ( _input_ [, _separator_] [<type-conversion>] )
----

It is not possible to specify an explicit correlation name and column name in the short form.

For example:

[source]
----
select *
from EMPLOYEE
where EMP_NO in unlist('2,4,5,7,11')
----

The equivalent with the regular form of `UNLIST` is:

[source]
----
select *
from EMPLOYEE
where EMP_NO in (
  select * from unlist('2,4,5,7,11') as A
)
----

[discrete]
==== Examples

[source]
----
select * from unlist('1,2,3,4,5') as U;

-- Produce INTEGERs instead of CHAR
select * from unlist('100:200:300:400:500', ':' RETURNING INT) AS U;

select U.* from unlist('text1,text2,text3') as U;

-- The second and third value produced start with a space
select C0 from unlist('text1, text2, text3') as U(C0);

select U.C0 from unlist('text1,text2,text3') as U(C0);

select EMP_NO from EMPLOYEE
where DEPT_NO in (select * from unlist('120,900') as depts);
-- This does the same as DEPT_NO in ('120', '900')

-- Short form of the previous
select EMP_NO from EMPLOYEE
where DEPT_NO in unlist('120,900');

-- Same as previous, but with a different separator
-- and explicit conversion to INTEGER:
select EMP_NO from EMPLOYEE
where DEPT_NO in unlist('120:900', ':' returning integer);

-- "Column unknown" error as no explict column-name is defined
-- -> default alias UNLIST only exists on output
select UNLIST from unlist('UNLIST,A,S,A') as A;

-- "Procedure unknown" error as no correlation-name is defined
select * from unlist('A,B,C')
----

[#rnfb60-dml-multi-trim]
=== Multi-character Trim Functions: `BTRIM`, `LTRIM`, `RTRIM`
https://github.com/MrTeeett[MrTeeett^]

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8015[#8015]

The multi-character trim functions -- `BTRIM`, `LTRIM`, `RTRIM` -- return their first argument with leading, trailing, or both leading and trailing characters removed.
The second argument specifies the characters to be trimmed.
In contrast to the existing `TRIM` function, these functions will remove any of the specified trim characters, regardless of their ordering.

.What is Trimmed
[horizontal.compact]
`BTRIM`:: **B**oth leading and trailing characters
`LTRIM`:: Leading (**L**eft) characters
`RTRIM`:: Trailing (**R**ight) characters

These functions are specified in the SQL standard (SQL:2023).

.Syntax
[listing]
----
{ BTRIM | LTRIM | RTRIM } ( <value> [ , <trim-character> ] )
----

If _trim-character_ is not specified, _space_ is used as trim character.

.Example
[source]
----
select ltrim('baobab is a tree', 'aboe')
from RDB$DATABASE;
-- ' is a tree'
----

[#rnfb60-dml-greatest]
=== Conditional Function `GREATEST`
Alexey Chudaykin

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8532[#8532]

The conditional function `GREATEST` returns the maximum (greatest) value of its arguments.
This function behaves the same as the existing `MAXVALUE` function, except this name is defined in the SQL standard.

.Syntax
[listing]
----
GREATEST (<expr> [{, <expr>}...])
----

If one or more expressions resolve to `NULL`, `GREATEST` returns `NULL`.

[#rnfb60-dml-least]
=== Conditional Function `LEAST`
Alexey Chudaykin

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8532[#8532]

The conditional function `LEAST` returns the minimum (least) value of its arguments.
This function behaves the same as the existing `MINVALUE` function, except this name is defined in the SQL standard.

.Syntax
[listing]
----
LEAST (<expr> [{, <expr>}...])
----

If one or more expressions resolve to `NULL`, `LEAST` returns `NULL`.

[#rnfb60-dml-within-group]
=== `WITHIN GROUP` Clause For Aggregate Functions
Alex Chudaykin

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8689[#8689]

The `WITHIN GROUP` clause is used for a subset of aggregate function to define an order within the group for their operation or processing.

.Syntax
[listing,subs=+macros]
----
<within-group-specification> ::=
  WITHIN GROUP '(' ORDER BY <sort-specification-list> ')'

<sort-specification-list> ::=
  <sort-specification> [, <sort-specification> ...]

<sort-specification> ::=
  <value-expression> [<ordering-specification>] [<null-ordering>]

<ordering-specification> ::=
    ASC  | ASCENDING
  | DESC | DESCENDING

<null-ordering> ::=
    NULLS FIRST
  | NULLS LAST
----

The <<rnfb60-dml-inv-dist,inverse distribution functions>> only accept a single _sort-specification_.

.Functions supporting the `WITHIN GROUP` clause:
* <<rnfb60-dml-listagg>>
* <<rnfb60-dml-inv-dist,Inverse Distribution Functions>>
** <<rnfb60-dml-perc-cont>>
** <<rnfb60-dml-perc-disc>>
// TODO not yet implemented (may not arrive in FB 6?)
// * Hypothetical set functions

[#rnfb60-dml-listagg]
=== `LISTAGG` Aggregate Function
Alex Chudaykin

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8689[#8689]

`LISTAGG` is a SQL standard (SQL:2016) aggregate function to concatenate values in a group, optionally with an order within that group.
In its basic form, it's equivalent to the Firebird-specific function `LIST` of previous versions.
For flexibility and backwards compatibility, `LIST` is now an alias for `LISTAGG`.

.Syntax
[listing,subs="+quotes,macros"]
----
<listagg-set-function> ::=
  { LISTAGG | LIST }
    <left-paren>
      [ ALL | DISTINCT ] <expr>
      [ <comma> _listagg-separator_ ]
      [ <listagg-overflow-clause> ]
    <right-paren>
    [ <within-group-specification> ]

<listagg-overflow-clause> ::=
  ON OVERFLOW <overflow-behavior>

<overflow-behavior> ::=
    ERROR
  | TRUNCATE [ _listagg-truncation-filler_ ] <listagg-count-indication>

<listagg-count-indication> ::=
  WITH COUNT | WITHOUT COUNT

<within-group-specification> ::=
  !! See <<rnfb60-dml-within-group>> !!
----

.`LISTAGG` Function Parameters
[cols="<1m,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Expression (e.g. column reference) to concatenate.

|listagg-separator
|String literal for the separator.
Defaults to '```,```'.

|listagg-truncation-filler
|Truncation filler on overflow.
Defaults to '```++...++```'.

|===

`LISTAGG` is defined by the SQL standard.
For backward compatibility with previous Firebird versions, `LIST` is now an alias for `LISTAGG`.
Compared to the SQL standard, some clauses and arguments are optional so `LISTAGG` and `LIST` can share the same definition.

* `ALL` (the default) results in all non-``NULL`` values being listed.
With `DISTINCT`, duplicates are removed, except if _expr_ is a `BLOB`.
* The optional _listagg-separator_ argument may be any expression convertible to string.
This makes it possible to specify e.g. `ascii_char(13)` as a separator.
* The _expr_ and _listagg-separator_ arguments support ``BLOB``s of any size and character set.
* Non-string arguments are implicitly converted to strings before concatenation.
* The result is a text `BLOB`, except when _expr_ is a `BLOB` of another subtype.
* The order of concatenation of _expr_ is only defined when the `WITHIN GROUP` clause is specified.
Otherwise, the order is undefined and depends on implementation details of the optimizer and the selected execution plan.
+
[TIP]
====
In Firebird 5.0 and older, ordering the concatenation performed by `LIST` was -- sometimes -- possible by using an ordered derived table.
We highly recommend replacing such brittle workarounds with the `WITHIN GROUP` clause.
====

.Deviations from the SQL standard definition of `LISTAGG`
* _expr_ and _listagg-separator_ can be expressions of any type convertible to string.
+
The SQL standard only accepts a string literal for _listagg-separator_.
* _listagg-separator_ is optional, defaulting to a comma ('```,```'), for backward compatibility with `LIST`.
* The `WITHIN GROUP` clause is optional, for backward compatibility with `LIST`.
* The `OVERFLOW` clause is ignored as the return type is always a `BLOB`, so it's considered never to overflow.
It's only provided for syntax compatibility with the SQL standard.

.Examples
[listing]
----
create table TEST_T (
  COL1 integer, COL2 varchar(2), COL3 varchar(2), COL4 varchar(2),
  COL5 boolean, COL6 varchar(2) character set WIN1251
);
commit;
insert into TEST_T values (1, 'A', 'A', 'J', false, 'Đź');
insert into TEST_T values (2, 'B', 'B', 'I', false, 'Đ”');
insert into TEST_T values (3, 'C', 'A', 'L', true,  'Đ–');
insert into TEST_T values (4, 'D', 'B', 'K', true,  'Đ™');
commit;

select listagg(COL4)
from TEST_T;
-- J,I,L,K

select
  listagg(distinct COL4, ':')
from TEST_T;
-- I:J:K:L

select
  listagg(distinct COL3, '||')
from TEST_T;
-- A||B

select
  listagg(distinct COL3, ':') within group (order by COL3)
from TEST_T;
-- A:B

select
  listagg(distinct COL3, ':') within group (order by COL3 desc)
from TEST_T;
-- B:A

select
  listagg(ALL COL3, ':') within group (order by COL3)
from TEST_T;
-- A:A:B:B

select
  listagg(COL6, ':') within group (order by COL2 desc)
from TEST_T;
-- Đ™:Đ–:Đ”:Đź

select
  listagg(COL4, ':' on overflow truncate '...' without count)
    within group (order by COL3 asc)
from TEST_T;
-- J:L:I:K

select
  listagg(COL4, ':' on overflow truncate '...' with count)
    within group (order by COL3 desc)
from TEST_T;
-- I:K:J:L

select
  listagg(COL3, ':' on overflow error) within group (order by COL6)
from TEST_T;
-- B:A:B:A

INSERT INTO TEST_T values(5, 'E', NULL, NULL, NULL, NULL);
INSERT INTO TEST_T values(6, 'F', 'C', 'N', true, 'Đš');

select
  listagg(COL2, ':') within group (order by COL3)
from TEST_T;
-- E:A:C:B:D:F

select
  listagg(COL2, ':') within group (order by COL3 nulls last)
from TEST_T;
-- A:C:B:D:F:E

select
  listagg(COL2, ':') within group (order by COL6 nulls first)
from TEST_T;
-- E:B:C:D:F:A
----

[#rnfb60-dml-inv-dist]
=== Inverse Distribution Functions `PERCENTILE_DISC` and `PERCENTILE_CONT`
Denis Simonov

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8946[#8946]

The `PERCENTILE_CONT` and `PERCENTILE_DISC` functions are known as inverse distribution functions.
These functions operate on an ordered set.
Like other aggregate functions, they can also be used as window functions.

[#rnfb60-dml-perc-cont]
==== `PERCENTILE_CONT`

`PERCENTILE_CONT` is an inverse distribution function that applies a continuous distribution.
It takes a percentile value and a sort specification and returns an element from the set defined by the sort specification.
``NULL``s are ignored in the calculation.

.Syntax
[listing,subs="+quotes,macros"]
----
PERCENTILE_CONT( _percent_ ) <within-group-specification>

<within-group-specification> ::=
  !! See <<rnfb60-dml-within-group>> !!
----

The argument _percent_ must be between 0 and 1, because it is a percentile value.
The expression of _percent_ must be constant within the group or -- as a window function -- partition.

The _within-group-specification_ can only have a single expression which must be of a numeric type to perform interpolation.

The `PERCENTILE_CONT` function returns a value of type `DOUBLE PRECISION` or `DECFLOAT(34)` depending on the type of the argument in the _within-group-specification_.
A value of type `DECFLOAT(34)` is returned if its `ORDER BY` contains an expression of type `INT128`, `NUMERIC(38, x)`, or `DECFLOAT(16 | 34)`, otherwise it returns `DOUBLE PRECISION`.

The result of `PERCENTILE_CONT` is computed by linear interpolation between values after ordering.
Using the percentile value _percent_ and the number of rows (_n_) in the group, you can compute the row number you are interested in after ordering the rows with respect to the sort specification.
This row number (`RN`) is computed according to the formula `RN = (1 + (percent * (n - 1))`.

The final result of the aggregate function is computed by linear interpolation between the values from rows at row numbers `CRN = ceiling(RN)` and `FRN = floor(RN)`.

.Pseudo-code
[listing]
----
function f(N) ::= value of expression from row at N

if (CRN = FRN = RN) then
  return f(RN)
else
  return (CRN - RN) * f(FRN) + (RN - FRN) * f(CRN)
----

[float]
===== Example

[source]
----
select
  DEPT_NO,
  SALARY,
  percent_rank() over (partition by DEPT_NO order by SALARY) as "PERCENT_RANK",
  percentile_cont(0.5) within group (order by SALARY)
    over (partition by DEPT_NO) as MEDIAN_CONT
from EMPLOYEE
where DEPT_NO < 600
order by 1, 2;
----

[listing]
----
DEPT_NO                SALARY            PERCENT_RANK             MEDIAN_CONT
======= ===================== ======================= =======================
000                  53793.00       0.000000000000000       133321.5000000000
000                 212850.00       1.000000000000000       133321.5000000000
100                  44000.00       0.000000000000000       77631.25000000000
100                 111262.50       1.000000000000000       77631.25000000000
110                  61637.81       0.000000000000000       65221.40500000000
110                  68805.00       1.000000000000000       65221.40500000000
115                6000000.00       0.000000000000000       6740000.000000000
115                7480000.00       1.000000000000000       6740000.000000000
120                  22935.00       0.000000000000000       33620.63000000000
120                  33620.63      0.5000000000000000       33620.63000000000
120                  39224.06      0.2500000000000000       33620.63000000000
121                 110000.00       0.000000000000000       110000.0000000000
123                  38500.00       0.000000000000000       38500.00000000000
125                  33000.00       0.000000000000000       33000.00000000000
130                  86292.94       0.000000000000000       94521.47000000000
130                 102750.00       1.000000000000000       94521.47000000000
140                 100914.00       0.000000000000000       100914.0000000000
180                  42742.50       0.000000000000000       53688.75000000000
180                  64635.00       1.000000000000000       53688.75000000000
----

[#rnfb60-dml-perc-disc]
==== `PERCENTILE_DISC`

`PERCENTILE_DISC` is an inverse distribution function that applies a discrete distribution.
It takes a percentile value and a sort specification and returns an element from the set defined by the sort specification.
``NULL``s are ignored in the calculation.

.Syntax
[listing,subs="+quotes,macros"]
----
PERCENTILE_DISC( _percent_ ) <within-group-specification>

<within-group-specification> ::=
  !! See <<rnfb60-dml-within-group>> !!
----

The argument _percent_ must be between 0 and 1, because it is a percentile value.
The expression of _percent_ must be constant within the group or -- as a window function -- partition.

The _within-group-specification_ can only have a single expression, of any type that can be sorted.
The function `PERCENTILE_DISC` returns a value of the same type as the expression in `ORDER BY` of the _within-group-specification_.

For a given percentile value _percent_, `PERCENTILE_DISC` sorts the values of the expression in the `ORDER BY` clause and returns the value with the smallest `CUME_DIST` value (with respect to the same sort specification) that is greater than or equal to _percent_.

[float]
===== Example

[source]
----
select
  DEPT_NO,
  SALARY,
  cume_dist() over (partition by DEPT_NO order by SALARY) as "CUME_DIST",
  percentile_disc(0.5) within group (order by SALARY)
    over (partition by DEPT_NO) as MEDIAN_DISC
from EMPLOYEE
where DEPT_NO < 600
order by 1, 2;
----

[listing]
----
DEPT_NO                SALARY               CUME_DIST           MEDIAN_DISC
======= ===================== ======================= =====================
000                  53793.00      0.5000000000000000              53793.00
000                 212850.00       1.000000000000000              53793.00
100                  44000.00      0.5000000000000000              44000.00
100                 111262.50       1.000000000000000              44000.00
110                  61637.81      0.5000000000000000              61637.81
110                  68805.00       1.000000000000000              61637.81
115                6000000.00      0.5000000000000000            6000000.00
115                7480000.00       1.000000000000000            6000000.00
120                  22935.00      0.3333333333333333              33620.63
120                  33620.63      0.6666666666666666              33620.63
120                  39224.06       1.000000000000000              33620.63
121                 110000.00       1.000000000000000             110000.00
123                  38500.00       1.000000000000000              38500.00
125                  33000.00       1.000000000000000              33000.00
130                  86292.94      0.5000000000000000              86292.94
130                 102750.00       1.000000000000000              86292.94
140                 100914.00       1.000000000000000             100914.00
180                  42742.50      0.5000000000000000              42742.50
180                  64635.00       1.000000000000000              42742.50
----

[#rnfb60-dml-inv-dist-ex]
==== An Example of Using `PERCENTILE_DISC` and `PERCENTILE_CONT`

[source]
----
select
  DEPT_NO,
  percentile_cont(0.5) within group (order by SALARY) as MEDIAN_CONT,
  percentile_disc(0.5) within group (order by SALARY) as MEDIAN_DISC
from EMPLOYEE
group by DEPT_NO;
----

[listing]
----
DEPT_NO             MEDIAN_CONT           MEDIAN_DISC
======= ======================= =====================
000           133321.5000000000              53793.00
100           77631.25000000000              44000.00
110           65221.40500000000              61637.81
115           6740000.000000000            6000000.00
120           33620.63000000000              33620.63
121           110000.0000000000             110000.00
123           38500.00000000000              38500.00
125           33000.00000000000              33000.00
130           94521.47000000000              86292.94
140           100914.0000000000             100914.00
180           53688.75000000000              42742.50
600           66450.00000000000              27000.00
621           71619.75000000000              62550.00
622           53167.50000000000              53167.50
623           60000.00000000000              60000.00
670           71268.75000000000              31275.00
671           81810.19000000000              81810.19
672           45647.50000000000              35000.00
900           92791.31500000000              69482.63
----
