[#rnfb60-engine]
= Changes in the Firebird Engine

[#rnfb60-engine-links]
.Quick Links
* <<rnfb60-engine-sql-pkg>>
* <<rnfb60-engine-optimizer>>

////
Generic template:

[#rnfb60-engine-<abbreviated-subject>]
== <subject>
<implementer/author>

Tracker ticket: https://github.com/FirebirdSQL/firebird/[pull/]<issue>[#<issue>]

<description>

////

[#rnfb60-engine-sql-pkg]
== `SYSTEM.RDB$SQL` Package
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/7675[#7675]

`SYSTEM.RDB$SQL` is a package with utility routines to work with dynamic SQL.

[#rnfb60-engine-sql-explain]
=== Procedure `EXPLAIN`

`SYSTEM.RDB$SQL.EXPLAIN` is a selectable procedure that returns tabular information of a query's plan, without executing the query.

.Input parameters
`SQL`::
type `BLOB SUB_TYPE TEXT CHARACTER SET UTF8` -- query statement

.Output parameters
`PLAN_LINE`::
type `INTEGER` -- plan's line order
`RECORD_SOURCE_ID`::
type `BIGINT` -- record source id
`PARENT_RECORD_SOURCE_ID`::
type `BIGINT` - parent record source id
`LEVEL`::
type `INTEGER` -- indentation level (may have gaps in relation to parent's level)
`SCHEMA_NAME`::
type `RDB$SCHEMA_NAME` -- schema name of object (table, procedure)
`PACKAGE_NAME`::
type `RDB$PACKAGE_NAME` -- package name of a stored procedure
`OBJECT_NAME`::
type `RDB$RELATION_NAME` -- object (table, procedure) name
`ALIAS`::
type `RDB$SHORT_DESCRIPTION` -- alias name
`RECORD_LENGTH`::
type `INTEGER` -- record length for the record source
`KEY_LENGTH`::
type `INTEGER` -- key length for the record source
`ACCESS_PATH`::
type `RDB$DESCRIPTION` -- friendly plan description

// TODO Add link to Q-literal docs in langref60
As SQL statements can contain quotes, it is recommended to use alternative string literals (Q-literals).
If your statement text also contains Q-literals, make sure to use another start and end pair.

.Example single line
[listing]
----
select *
from RDB$SQL.EXPLAIN('select * from EMPLOYEE where EMP_NO = ?');
----

.Example multi-line (with Q-literal)
[listing]
----
select *
from RDB$SQL.EXPLAIN(q'{
  select *
  from (
    select FULL_NAME NAME from EMPLOYEE
    union all
    select CUSTOMER NAME from CUSTOMER
  )
  where NAME = ?
}');
----

[#rnfb60-engine-sql-parse-unqualified-names]
=== Procedure `PARSE_UNQUALIFIED_NAMES`

`SYSTEM.RDB$SQL.PARSE_UNQUALIFIED_NAMES` is a selectable procedure that parses a list of unqualified SQL identifiers and returns a row for each identifier.
The input must follow syntax rules for names and the output of unquoted names are uppercased.

.Input parameters
`NAMES`::
type `VARCHAR(8191) CHARACTER SET UTF8` -- list of SQL identifiers

.Output parameters
`NAME`::
type `RDB$RELATION_NAME` -- a single SQL identifier, normalised to how identifiers are stored in the metadata tables

[listing]
----
select *
from RDB$SQL.PARSE_UNQUALIFIED_NAMES(
  'schema1, schema2, "schema3", "schema 4", "schema ""5"""');

-- SCHEMA1
-- SCHEMA2
-- schema3
-- schema 4
-- schema "5"
----

[#rnfb60-engine-optimizer]
== Optimiser Improvements

[#rnfb60-engine-opt-det-func-invariant]
=== Improve Invariant Handling of Deterministic Functions
Dmitry Yemanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/7865[#7865]

Previously, the return value of deterministic functions were considered invariant only if the function had no arguments.
A cache storing (_argument_values_, _return_value_) pairs is quite complex.
For now we use a simpler option: if the arguments of a deterministic function are invariants, such as literals or input parameters, then the return value of that function is also an invariant.

Function calls to deterministic functions with invariant arguments should now be evaluated only once in a statement, instead of -- for example -- for each row.

[#rnfb60-engine-opt-cost-order]
=== Cost-based Decision Between `ORDER` and `SORT` Plans
Dmitry Yemanov

Tracker ticket:
https://github.com/FirebirdSQL/firebird/pull/8316[#8316]
https://github.com/FirebirdSQL/firebird/issues/8484[#8484]

The optimiser now applies a cost calculation to decide between `ORDER` and `SORT` when ordering is required for a query.
The visible effects are:

* The `ORDER ... INDEX` plan is almost never used, as it's inferior to `SORT` in most cases, except some queries with the `OPTIMIZE FOR FIRST ROWS` hint, explicit or implicit (e.g. `SELECT FIRST`).
This is already proven in practice to work better.
* The `SORT` plan may be preferred to `ORDER` for the default `OPTIMIZE FOR ALL ROWS` scenario if it's estimated to be cheaper.
* Queries should not expect that the `ORDER` plan is always used if a suitable index exists.

The cost calculation will be adjusted once more statistics are available to the optimizer (e.g. clustering factor).

[#rnfb60-engine-opt-union-all-false]
=== `UNION ALL` Optimisation With Constant False Condition
Dmitry Yemanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/8113[#8113]

The optimiser may eliminate fetches from a side of a `UNION ALL` if all its rows are excluded by a constant _false_ expression.

[#rnfb60-engine-opt-idx-ignore-null-keys]
=== Ignore ``NULL``s (If Possible) While Scanning Keys During Index Navigation
Dmitry Yemanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8446[#8446]

While scanning keys during index navigation ``NULL``s are now skipped, if conditions in the query eliminate `NULL`.
