[#rnfb60-new]
= New In Firebird 6.0

[#rnfb60-new-summary]
== Summary of New Features

Firebird 6.0 introduces many improvements without any changes in architecture or operation, the most important are:

* ...

The following list summarises the features and changes, with links to the chapters and topics where more detailed information can be found.

////
Generic template (<version> ::= <major><minor>[<pre>]):

[#rnfb60-<version>-complete]
=== Complete In Firebird <major>.<minor> [<pre-release>]

Feature template:

<<rnfb60-section-id[,description>]>>::
https://github.com/FirebirdSQL/firebird/[pull/]<issue>[#<issue>]
_by <author>_

<end of feature template>

////

[#rnfb60-60alpha1-complete]
=== Complete In Firebird 6.0 Alpha 1

<<rnfb60-dml-cast-format>>::
https://github.com/FirebirdSQL/firebird/issues/2388[#2388]
_by Artyom Ivanov_

<<rnfb60-ddl-drop-if-exists>>::
https://github.com/FirebirdSQL/firebird/issues/4203[#4203]
_by Adriano dos Santos Fernandes_

<<rnfb60-ddl-create-if-not-exists>>
https://github.com/FirebirdSQL/firebird/issues/8062[#8062]
_by Adriano dos Santos Fernandes_

<<rnfb60-ddl-createidx-inactive>>::
https://github.com/FirebirdSQL/firebird/issues/6233[#6233], https://github.com/FirebirdSQL/firebird/issues/8090[#8090]
_by Dimitry Sibiryakov_

<<rnfb60-ddl-alter-func-det>>::
https://github.com/FirebirdSQL/firebird/7427[#7427]
_by Alexander Zhdanov_

<<rnfb60-dml-routine-call-default>>::
https://github.com/FirebirdSQL/firebird/issues/7566[#7566]
_by Adriano dos Santos Fernandes_

<<rnfb60-dml-named-args>>::
https://github.com/FirebirdSQL/firebird/issues/7586[#7586]
_by Adriano dos Santos Fernandes_

<<rnfb60-dml-call-stmt>>::
https://github.com/FirebirdSQL/firebird/issues/7587[#7587]
_by Adriano dos Santos Fernandes_

<<rnfb60-psql-decl-var-init,Allow any expression as default value in `DECLARE VARIABLE`>>::
https://github.com/FirebirdSQL/firebird/issues/7590[#7590]
_by Adriano dos Santos Fernandes_

<<rnfb60-dml-any-value,Aggregate function `ANY_VALUE`>>::
https://github.com/FirebirdSQL/firebird/pull/7617[#7617]
_by Adriano dos Santos Fernandes_

<<rnfb60-engine-sql-pkg,Package `SYSTEM.RDB$SQL` -- utility routines to work with dynamic SQL>>::
https://github.com/FirebirdSQL/firebird/issues/7675[#7675]
_by Adriano dos Santos Fernandes_

<<rnfb60-util-isql-explain,ISQL `EXPLAIN` statement>>::
https://github.com/FirebirdSQL/firebird/issues/7675[#7675]
_by Adriano dos Santos Fernandes_

<<rnfb60-ddl-createdb-owner>>::
https://github.com/FirebirdSQL/firebird/issues/7719[#7719]
_by Dimitry Sibiryakov_

<<rnfb60-ddl-alter-sql-sec>>::
https://github.com/FirebirdSQL/firebird/issues/7744[#7744]
_by Alexander Zhdanov_

<<rnfb60-util-isql-autoterm,ISQL automatic end of statement detection (`SET AUTOTERM`)>>::
https://github.com/FirebirdSQL/firebird/pull/7868[#7868]
_by Adriano dos Santos Fernandes_

Extend `SYSTEM` context of `RDB$GET_CONTEXT` with allocated, free and used pages::
https://github.com/FirebirdSQL/firebird/pull/7888[#7888]
_by https://github.com/Danuul3[Danuul3^]_
+
See also <<rnfb60-dml-context-system>>.

<<rnfb60-dml-gen-uuid-v7>>::
https://github.com/FirebirdSQL/firebird/issues/7980[#7980]
_by Adriano dos Santos Fernandes_

<<rnfb60-dml-multi-trim>>::
https://github.com/FirebirdSQL/firebird/pull/8015[#8015]
_by https://github.com/MrTeeett[MrTeeett^]_

<<rnfb60-apiods-multi>>::
https://github.com/FirebirdSQL/firebird/pull/8047[#8047]
_by Dmitry Yemanov_

<<rnfb60-engine-opt-union-all-false>>::
https://github.com/FirebirdSQL/firebird/issues/8113[#8113]
_by Dmitry Yemanov_

<<rnfb60-engine-opt-cost-order>>::
https://github.com/FirebirdSQL/firebird/pull/8316[#8316]
_by Dmitry Yemanov_
