[#rnfb60-new]
= New In Firebird 6.0

[#rnfb60-new-summary]
== Summary of New Features

Firebird 6.0 introduces many improvements without any changes in architecture or operation, the most important are:

* ...

The following list summarises the features and changes, with links to the chapters and topics where more detailed information can be found.

////
Generic template (<version> ::= <major><minor>[<pre>]):

[#rnfb60-<version>-complete]
=== Complete In Firebird <major>.<minor> [<pre-release>]

Feature template:

<<rnfb60-section-id[,description>]>>::
https://github.com/FirebirdSQL/firebird/[pull/]<issue>[#<issue>]
_by <author>_

<end of feature template>

////

[#rnfb60-60alpha1-complete]
=== Complete In Firebird 6.0 Alpha 1

<<rnfb60-engine-ltt>>::
https://github.com/FirebirdSQL/firebird/issues/1095[#1095]
_by Adriano dos Santos Fernandes_

<<rnfb60-engine-record-size>>::
https://github.com/FirebirdSQL/firebird/issues/1130[#1130]
_by Dimitry Yemanov_

<<rnfb60-dml-cast-format>>::
https://github.com/FirebirdSQL/firebird/issues/2388[#2388]
_by Artyom Ivanov_

<<rnfb60-ddl-drop-if-exists>>::
https://github.com/FirebirdSQL/firebird/issues/4203[#4203]
_by Adriano dos Santos Fernandes_

<<rnfb60-ddl-create-if-not-exists>>
https://github.com/FirebirdSQL/firebird/issues/8062[#8062]
_by Adriano dos Santos Fernandes_

<<rnfb60-ddl-createidx-inactive>>::
https://github.com/FirebirdSQL/firebird/issues/6233[#6233], https://github.com/FirebirdSQL/firebird/issues/8090[#8090]
_by Dimitry Sibiryakov_

<<rnfb60-ddl-alter-func-det>>::
https://github.com/FirebirdSQL/firebird/7427[#7427]
_by Alexander Zhdanov_

<<rnfb60-dml-routine-call-default>>::
https://github.com/FirebirdSQL/firebird/issues/7566[#7566]
_by Adriano dos Santos Fernandes_

<<rnfb60-dml-named-args>>::
https://github.com/FirebirdSQL/firebird/issues/7586[#7586]
_by Adriano dos Santos Fernandes_

<<rnfb60-dml-call-stmt>>::
https://github.com/FirebirdSQL/firebird/issues/7587[#7587]
_by Adriano dos Santos Fernandes_

<<rnfb60-psql-decl-var-init,Allow any expression as default value in `DECLARE VARIABLE`>>::
https://github.com/FirebirdSQL/firebird/issues/7590[#7590]
_by Adriano dos Santos Fernandes_

<<rnfb60-dml-any-value,Aggregate function `ANY_VALUE`>>::
https://github.com/FirebirdSQL/firebird/pull/7617[#7617]
_by Adriano dos Santos Fernandes_

<<rnfb60-engine-sql-pkg,Package `SYSTEM.RDB$SQL` -- utility routines to work with dynamic SQL>>::
https://github.com/FirebirdSQL/firebird/issues/7675[#7675]
_by Adriano dos Santos Fernandes_

<<rnfb60-util-isql-explain,ISQL `EXPLAIN` statement>>::
https://github.com/FirebirdSQL/firebird/issues/7675[#7675]
_by Adriano dos Santos Fernandes_

<<rnfb60-ddl-createdb-owner>>::
https://github.com/FirebirdSQL/firebird/issues/7719[#7719]
_by Dimitry Sibiryakov_

<<rnfb60-ddl-alter-sql-sec>>::
https://github.com/FirebirdSQL/firebird/issues/7744[#7744]
_by Alexander Zhdanov_

<<rnfb60-ddl-datatype-collate>>::
https://github.com/FirebirdSQL/firebird/pull/7748[#7748]
_by Dimitry Sibiryakov_
+
See also <<rnfb60-dml-cast-collate>> and <<rnfb60-ddl-alter-dom-collate>>.

<<rnfb60-engine-opt-det-func-invariant>>::
https://github.com/FirebirdSQL/firebird/issues/7865[#7865]
_by Dmitry Yemanov_

<<rnfb60-util-isql-autoterm,ISQL automatic end of statement detection (`SET AUTOTERM`)>>::
https://github.com/FirebirdSQL/firebird/pull/7868[#7868]
_by Adriano dos Santos Fernandes_

Extend `SYSTEM` context of `RDB$GET_CONTEXT` with allocated, free and used pages::
https://github.com/FirebirdSQL/firebird/pull/7888[#7888]
_by https://github.com/Danuul3[Danuul3^]_
+
See also <<rnfb60-dml-context-system>>.

<<rnfb60-dml-gen-uuid-v7>>::
https://github.com/FirebirdSQL/firebird/issues/7980[#7980]
_by Adriano dos Santos Fernandes_

<<rnfb60-dml-multi-trim>>::
https://github.com/FirebirdSQL/firebird/pull/8015[#8015]
_by https://github.com/MrTeeett[MrTeeett^]_

<<rnfb60-apiods-multi>>::
https://github.com/FirebirdSQL/firebird/pull/8047[#8047]
_by Dmitry Yemanov_

<<rnfb60-engine-opt-union-all-false>>::
https://github.com/FirebirdSQL/firebird/issues/8113[#8113]
_by Dmitry Yemanov_

<<#rnfb60-dml-bit-agg>>::
https://github.com/FirebirdSQL/firebird/issues/8175[#8175]
_by Denis Simonov_

Windows ARM64 Port Available::
https://github.com/FirebirdSQL/firebird/issues/8216[#8216]
_by Adriano dos Santos Fernandes_
// TODO Does this need an extra section?

<<rnfb60-ddl-alt-pkg-body>>::
https://github.com/FirebirdSQL/firebird/pull/8309[#8309]
_by Artyom Abakumov_

<<rnfb60-engine-opt-cost-order>>::
https://github.com/FirebirdSQL/firebird/pull/8316[#8316]
_by Dmitry Yemanov_

Trace: <<rnfb60-traceconf-database>>::
https://github.com/FirebirdSQL/firebird/issues/8426[#8426]
_by Artyom Abakumov_

<<rnfb60-engine-opt-idx-ignore-null-keys>>::
https://github.com/FirebirdSQL/firebird/pull/8446[#8446]
_by Dmitry Yemanov_

<<rnfb60-engine-valid-db>>::
https://github.com/FirebirdSQL/firebird/pull/8450[#8450]
_by Dimitry Yemanov_

<<rnfb60-psql-range-for>>::
https://github.com/FirebirdSQL/firebird/issues/8498
_by Adriano dos Santos Fernandes_

Conditional Functions <<rnfb60-dml-greatest,`GREATEST`>> and <<rnfb60-dml-least,`LEAST`>>::
https://github.com/FirebirdSQL/firebird/pull/8532[#8532]
_by Alexey Chudaykin_

<<rnfb60-dml-unlist>>::
https://github.com/FirebirdSQL/firebird/issues/8005[#8005]
https://github.com/FirebirdSQL/firebird/issues/8580[#8580]
_by Alex Chudaykin_

<<rnfb60-engine-blr-debug-sub>>::
https://github.com/FirebirdSQL/firebird/issues/8579[#8579]
_by Adriano dos Santos Fernandes_

<<rnfb60-engine-repl-cleanup>>::
https://github.com/FirebirdSQL/firebird/pull/8626[#8826]
_by Andrey Kravchenko_

<<rnfb60-dml-listagg>>::
https://github.com/FirebirdSQL/firebird/pull/8689[#8689]
_by Alex Chudaykin_

<<rnfb60-ddl-altertbl-column-opt>>::
https://github.com/FirebirdSQL/firebird/pull/8723[#8723]
_by Mark Rotteveel_

<<rnfb60-apiods-api-info-perf>>::
https://github.com/FirebirdSQL/firebird/pull/8771[#8771]
_by Dmitry Yemanov_

<<rnfb60-util-isql-stats>>::
https://github.com/FirebirdSQL/firebird/pull/8792[#8792]
_by https://github.com/Ev3nt[Ev3nt^]_

<<rnfb60-utils-gstat-fill-factor>>::
https://github.com/FirebirdSQL/firebird/pull/8816[#8816]
_by Dimitry Yemanov_

<<rnfb60-dml-using>>::
https://github.com/FirebirdSQL/firebird/issues/8869[#8869]
_by Adriano dos Santos Fernandes_

<<rnfb60-ddl-varchar-no-length>>::
https://github.com/FirebirdSQL/firebird/pull/8909[#8909]
_by Mark Rotteveel_

<<rnfb60-engine-opt-cardinal-pred>>::
https://github.com/FirebirdSQL/firebird/pull/8940[#8940]
_by Dimitry Yemanov_
