[#rnfb60-new]
= New In Firebird 6.0

[#rnfb60-new-summary]
== Summary of New Features

Firebird 6.0 introduces many improvements without any changes in architecture or operation, the most important are:

* ...

The following list summarises the features and changes, with links to the chapters and topics where more detailed information can be found.

////
Generic template (<version> ::= <major><minor>[<pre>]):

[#rnfb60-<version>-complete]
=== Complete In Firebird <major>.<minor> [<pre-release>]

Feature template:

<description>::
https://github.com/FirebirdSQL/firebird/[pull/]<issue>[#<issue>]
_by <author>_
+
For more details, see <<rnfb60-section-id>>.

<end of feature template>

////

[#rnfb60-60alpha1-complete]
=== Complete In Firebird 6.0 Alpha 1

<<rnfb60-ddl-drop-if-exists,`DROP ... [IF EXISTS]`>>::
https://github.com/FirebirdSQL/firebird/issues/4203[#4203]
_by Adriano dos Santos Fernandes_

<<rnfb60-ddl-create-if-not-exists,`CREATE ... [IF NOT EXISTS]`>>
https://github.com/FirebirdSQL/firebird/issues/8062[#8062]
_by Adriano dos Santos Fernandes_

<<rnfb60-ddl-alter-func-det,Alter `DETERMINISTIC` State of Functions>>::
https://github.com/FirebirdSQL/firebird/7427[#7427]
_by Alexander Zhdanov_

<<rnfb60-dml-routine-call-default,Allow `DEFAULT` Keyword in Argument List>>::
https://github.com/FirebirdSQL/firebird/issues/7566[#7566]
_by Adriano dos Santos Fernandes_

<<rnfb60-dml-named-args,Named Arguments for Function and Procedure Calls>>::
https://github.com/FirebirdSQL/firebird/issues/7586[#7586]
_by Adriano dos Santos Fernandes_

<<rnfb60-dml-call-stmt,`CALL` Statement for Executing Procedures>>::
https://github.com/FirebirdSQL/firebird/issues/7587[#7587]
_by Adriano dos Santos Fernandes_

<<rnfb60-psql-decl-var-init,Allow any expression as default value in `DECLARE VARIABLE`>>::
https://github.com/FirebirdSQL/firebird/issues/7590[#7590]
_by Adriano dos Santos Fernandes_

<<rnfb60-dml-any-value,Aggregate function `ANY_VALUE`>>::
https://github.com/FirebirdSQL/firebird/pull/7617[#7617]
_by Adriano dos Santos Fernandes_

<<rnfb60-engine-sql-pkg,Package `SYSTEM.RDB$SQL` -- utility routines to work with dynamic SQL>>::
https://github.com/FirebirdSQL/firebird/issues/7675[#7675]
_by Adriano dos Santos Fernandes_

<<rnfb60-util-isql-explain,ISQL `EXPLAIN` statement>>::
https://github.com/FirebirdSQL/firebird/issues/7675[#7675]
_by Adriano dos Santos Fernandes_

<<rnfb60-ddl-createdb-owner, Create Database With a Different Owner>>::
https://github.com/FirebirdSQL/firebird/issues/7719[#7719]
_by Dimitry Sibiryakov_

<<rnfb60-ddl-alter-sql-sec,Alter `SQL SECURITY` State of Functions, Procedures, and Packages>>::
https://github.com/FirebirdSQL/firebird/issues/7744[#7744]
_by Alexander Zhdanov_

<<rnfb60-util-isql-autoterm,ISQL automatic end of statement detetection (`SET AUTOTERM`)>>
https://github.com/FirebirdSQL/firebird/pull/7868[#7868]
_by Adriano dos Santos Fernandes_