[#rnfb60-security]
= Security

Security enhancements in Firebird 6 include:

* <<rnfb60-sec-schema-grant-revoke>>

// TODO ...

[#rnfb60-sec-schema-grant-revoke]
== Changes to `GRANT` And `REVOKE` For Schemas
Adriano dos Santos Fernandes

With the introduction of schemas, the `GRANT` and `REVOKE` statement syntax was changed to accommodate this new feature.

.See also
<<rnfb60-engine-schema-priv>>

[#rnfb60-sec-schema-priv]
=== Granting And Revoking Privileges On Schemas

To be able to access objects in a schema, a user must have the `USAGE` privilege on the schema, in addition to privileges on the specific object they want to access.

.Syntax fragment
[listing,subs=+quotes]
----
GRANT
  USAGE ON SCHEMA _name_
  !! ... rest of GRANT syntax unchanged !!

REVOKE [GRANT OPTION FOR]
  USAGE ON SCHEMA _name_
  !! ... rest of REVOKE syntax unchanged !!
----

[#rnfb60-sec-schema-qual]
=== Schema Qualification When Granting Or Revoking

When granting or revoking privileges, it is recommended to use the fully-qualified object name (that is, use `__schema-name__.__object-name__`, not just `__object-name__`).
If the object is not fully-qualified, the object is located on the search path.
This can result in scripts that may not be repeatable if executed with a different search path.

// TODO Verify example

.Examples
[source]
----
-- Use fully-qualified names:
grant insert on PUBLIC.EMPLOYEE_PROJECT
  to procedure PUBLIC.ADD_EMP_PROJ;

-- Instead of unqualified names:
grant insert on EMPLOYEE_PROJECT
  to procedure ADD_EMP_PROJ;
----

[#rnfb60-sec-schema-ddl-priv]
=== Granting And Revoking DDL Privileges

DDL privileges for <<rnfb60-engine-schema-bound-obj,schema-bound>> object types are now specific to a schema.
The schema can be specified with the optional `ON SCHEMA _name_` clause.
If this clause is absent, the _current schema_ is implicitly used.

.Syntax fragment
[listing,subs=+quotes]
----
GRANT
 { <ddl-privileges> <schema-object> [ON SCHEMA _name_]
 | <ddl-privileges> <schemaless-object> }
 !! ... rest of GRANT syntax unchanged !!

REVOKE [GRANT OPTION FOR]
 { <ddl-privileges> <schema-object> [ON SCHEMA _name_]
 | <ddl-privileges> <schemaless-object> }
 !! ... rest of REVOKE syntax unchanged !!

<ddl_privileges> ::=
  {ALL [PRIVILEGES] | <ddl_privilege_list>}

<ddl_privilege_list> ::=
  <ddl_privilege> [, <ddl_privilege> ...]

<ddl_privilege> ::= CREATE | ALTER ANY | DROP ANY

<schema-object> ::=
    TABLE     | VIEW          | PROCEDURE | FUNCTION
  | PACKAGE   | GENERATOR     | SEQUENCE  | DOMAIN
  | EXCEPTION | CHARACTER SET | COLLATION

<schemless-object> ::= ROLE | FILTER | SCHEMA
----
