[#rnfb60-util]
= Monitoring & Command-line Utilities

Improvements and additions to the Firebird utilities.

[#rnfb60-util-mon]
== Monitoring

// TODO Remove section if no additions

[#rnfb60-util-nbackup]
== _nbackup_

// TODO Remove section if no additions

[#rnfb60-util-isql]
== _isql_

[#rnfb60-util-isql-search-path]
=== Switch `-SE[ARCH_PATH]`

The `-SEARCH_PATH` option (short form `-SE`) enables ISQL to pass the search path argument as `isc_dpb_search_path` with every established attachment.

[listing]
----
isql -search_path x,y test.fdb
select RDB$GET_CONTEXT('SYSTEM', 'SEARCH_PATH') from system.rdb$database;
-- Result: "X", "Y"
set search_path to y;
select RDB$GET_CONTEXT('SYSTEM', 'SEARCH_PATH') from system.rdb$database;
-- Result: "Y"

connect 't2.fdb';
select RDB$GET_CONTEXT('SYSTEM', 'SEARCH_PATH') from system.rdb$database;
-- Result: "X", "Y"
----

[listing]
----
isql -search_path '"x", "y"' test.fdb
select RDB$GET_CONTEXT('SYSTEM', 'SEARCH_PATH') from system.rdb$database;
-- Result: "x", "y"
----

Special names with double quotes require different handling depending on the operating system and, specifically, the shell interpreter.
On Linux with Bash, double quotes must be escaped using the backslash (`\`) character.
On Windows with the Command Prompt (`cmd`), double quotes need to be duplicated.
The example below demonstrates how to use the same search path on both platforms.

// TODO Add example for PowerShell?

.Linux / Bash
[listing]
----
isql -search_path "x, \"y\", z, \"q a\", system" test.fdb

select rdb$get_context('SYSTEM', 'SEARCH_PATH') from system.rdb$database;
-- Result: "X", "y", "Z", "q a", "SYSTEM"
----

Windows / Command Prompt:
[listing]
----
isql -search_path "x, ""y"", z, ""q a"", system" test.fdb

select rdb$get_context('SYSTEM', 'SEARCH_PATH') from system.rdb$database;
-- Result: "X", "y", "Z", "q a", "SYSTEM"
----

[#rnfb60-util-isql-explain]
=== `EXPLAIN` Statement
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/7675[#7675]

`EXPLAIN` is an ISQL-only statement to show the query plan of a statement without executing it.

For similar functionality in DSQL, see <<rnfb60-engine-sql-explain,`SYSTEM.RDB$SQL.EXPLAIN`>>.

.Syntax
[listing]
----
EXPLAIN <statement>
----

.Examples:
[listing]
----
SQL> explain select * from employees where id = ?;

SQL> set term !;
SQL>
SQL> explain
CON> execute block
CON> as
CON>     declare id integer;
CON> begin
CON>     select id from employees where id = ? into id;
CON> end!
SQL>
SQL> set term ;!
----

[#rnfb60-util-isql-autoterm]
=== `SET AUTOTERM {ON|OFF}`
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/7868[#7868]

`SET AUTOTERM` configures automatic end of statement detection.
When set to `ON`, the terminator defined with `SET TERM` is reset to a semicolon, and ISQL will use new heuristics for end of statement detection, where the engine helps ISQL to detect valid usage of semicolons inside statements.

At each semicolon (outside quotes or comments), ISQL prepares the query buffer with flag `IStatement::PREPARE_REQUIRE_SEMICOLON`.

If the engine prepares the statement successfully, it's run and ISQL is put in new statement mode.

If the engine returns error `isc_command_end_err2`, then ISQL is put in statement continuation mode and asks for another line, repeating the process.
When this error happens together with `IStatement::PREPARE_REQUIRE_SEMICOLON`, the trace facility will not log the error.

If the engine returns a different error, the error is shown and ISQL is put in new statement mode.

.Notes
* This option can also be activated with commandline parameter `-autot[erm]`
* `SET AUTOTERM` can only be used with a Firebird 6 or later engine
* Executing `SET TERM` automatically disables `AUTOTERM`, i.e. sets it to `OFF`
* `SET AUTOTERM ON` automatically resets the terminator to semicolon
* While `AUTOTERM ON` can be used in non-interactive scripts, it may slow down big scripts with PSQL statements spanning many statements.
At each semicolon, ISQL will attempt to prepare the statement, which can be inefficient.
+
In other words, for scripts, use of `SET TERM` should be preferred over `SET AUTOTERM`.

.Examples
[listing]
----
SQL> SET AUTOTERM ON;

SQL> execute block returns (o1 integer)
CON> as
CON> begin
CON>     o1 = 1;
CON>     suspend;
CON> end;

          O1
============
1

SQL> select 1
CON>     from rdb$database
CON>     where true;

    CONSTANT
============
1
----

[#rnfb60-util-isql-stats]
=== `SET STATS` Now Reports Attachment-level Statistics
https://github.com/Ev3nt[Ev3nt^]

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8792[#8792]

In previous versions, _isql_ `SET STATS` reported database-wide statistics for reads, writes, and fetches.
Under concurrent use, this could result in confusing statistics.
This has been changed to report attachment-level statistics for reads, writes, and fetches.

The memory statistics are still database-wide.

See also <<rnfb60-apiods-api-info-perf>> and <<rnfb60-apiods-api-util>>.

[#rnfb60-utils-gbak]
== _gbak_

[#rnfb60-utils-gbak-schema]
=== Switches `-INCLUDE_SCHEMA_D[ATA]` and `SKIP_SCHEMA_D[ATA]`
Adriano dos Santos Fernandes

To support schemas, the switches `-INCLUDE_SCHEMA_DATA _sql-regex_` (short form `-INCLUDE_SCHEMA_D _sql-regex_`) and `-SKIP_SCHEMA_DATA _sql-regex_` (short form `-SKIP_SCHEMA_D _sql-regex_`) were add to `gbak`.
They complement the existing `-INCLUDE_DATA` and `-SKIP_DATA` options.
If `-INCLUDE_SCHEMA_DATA` is not specified, all schemas are included by default.
Likewise, if `-SKIP_SCHEMA_DATA` is not provided, no schemas are skipped.

.Example
[listing]
----
# Include data only from tables of schema S1
gbak -c -include_schema_data S1 database.fbk database.fdb

# Include data only from tables named T1 from any schema
gbak -c -include_data T1 database.fbk database.fdb

# Include data only from table T1 of schema S1
gbak -c -include_schema_data S1 -include_data T1 database.fbk database.fdb

# Include data from tables of all schemas except S1
gbak -c -skip_schema_data S1 database.fbk database.fdb
----

[#rnfb60-utils-gbak-multi-restore]
=== Multi-file Database Support Removed
Dmitry Yemanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8047[#8047]

_gbak_ can no longer restore a database to multiple files.
That is, for restore, it no longer accepts a list of filenames and sizes, but only accepts a single database filename.

See also <<rnfb60-apiods-multi>>.

[#rnfb60-utils-gfix]
== _gfix_

// TODO Remove section if no additions

[#rnfb60-utils-gstat]
== _gstat_

[#rnfb60-utils-gstat-schema]
=== Switch `-SCH[EMA]`
Adriano dos Santos Fernandes

The repeatable switch `-SCHEMA _name_` (short form `-SCH _name_`) can be used to specify schema(s) for analysis.
This switch complements the existing `-TABLE` switch.

When `-SCHEMA` is not specified, all schemas are analysed.
When both `-SCHEMA` and `-TABLE` are specified, only tables that match both are analysed.
That is, the schema of the table must match any of the listed schema names *and* its name must match any of the listed table names.

[#rnfb60-utils-gstat-fill-factor]
=== Improved Calculation Of The Average Page Fill Factor
Dimitry Yemanov

Tracker ticket: https://github.com/FirebirdSQL/firebird/pull/8816[#8816]

The calculation of the average page fill factor was improved and made more accurate.

* Empty pages are excluded,
* Alignment is included in the size occupied by a record.

[#rnfb60-utils-fbsvcmgr]
== _fbsvcmgr_

[#rnfb60-utils-fbsvcmgr-schema]
=== Schema Support

Options were added to `fbsvcmgr` for schema support.
They are the equivalent of the Service Request Items listed in <<rnfb60-apiods-api-service-schema>>, without the `isc_spb_` prefix.
