/*
 * This file is generated by jOOQ.
*/
package ru.ibase.fbjavaex.exampledb.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ru.ibase.fbjavaex.exampledb.tables.InvoiceLine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoiceLineRecord extends UpdatableRecordImpl<InvoiceLineRecord> implements Record5<Integer, Integer, Integer, Long, BigDecimal> {

    private static final long serialVersionUID = 1099965716;

    /**
     * Setter for <code>INVOICE_LINE.INVOICE_LINE_ID</code>.
     */
    public void setInvoiceLineId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>INVOICE_LINE.INVOICE_LINE_ID</code>.
     */
    public Integer getInvoiceLineId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>INVOICE_LINE.INVOICE_ID</code>.
     */
    public void setInvoiceId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>INVOICE_LINE.INVOICE_ID</code>.
     */
    public Integer getInvoiceId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>INVOICE_LINE.PRODUCT_ID</code>.
     */
    public void setProductId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>INVOICE_LINE.PRODUCT_ID</code>.
     */
    public Integer getProductId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>INVOICE_LINE.QUANTITY</code>.
     */
    public void setQuantity(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>INVOICE_LINE.QUANTITY</code>.
     */
    public Long getQuantity() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>INVOICE_LINE.SALE_PRICE</code>.
     */
    public void setSalePrice(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>INVOICE_LINE.SALE_PRICE</code>.
     */
    public BigDecimal getSalePrice() {
        return (BigDecimal) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Long, BigDecimal> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Long, BigDecimal> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return InvoiceLine.INVOICE_LINE.INVOICE_LINE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return InvoiceLine.INVOICE_LINE.INVOICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return InvoiceLine.INVOICE_LINE.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return InvoiceLine.INVOICE_LINE.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return InvoiceLine.INVOICE_LINE.SALE_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getInvoiceLineId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getInvoiceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getSalePrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceLineRecord value1(Integer value) {
        setInvoiceLineId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceLineRecord value2(Integer value) {
        setInvoiceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceLineRecord value3(Integer value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceLineRecord value4(Long value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceLineRecord value5(BigDecimal value) {
        setSalePrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceLineRecord values(Integer value1, Integer value2, Integer value3, Long value4, BigDecimal value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoiceLineRecord
     */
    public InvoiceLineRecord() {
        super(InvoiceLine.INVOICE_LINE);
    }

    /**
     * Create a detached, initialised InvoiceLineRecord
     */
    public InvoiceLineRecord(Integer invoiceLineId, Integer invoiceId, Integer productId, Long quantity, BigDecimal salePrice) {
        super(InvoiceLine.INVOICE_LINE);

        set(0, invoiceLineId);
        set(1, invoiceId);
        set(2, productId);
        set(3, quantity);
        set(4, salePrice);
    }
}
