/*
 * This file is generated by jOOQ.
*/
package ru.ibase.fbjavaex.exampledb.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.ibase.fbjavaex.exampledb.tables.Webrole;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WebroleRecord extends UpdatableRecordImpl<WebroleRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1935994181;

    /**
     * Setter for <code>WEBROLE.WEBROLE_ID</code>.
     */
    public void setWebroleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>WEBROLE.WEBROLE_ID</code>.
     */
    public Integer getWebroleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>WEBROLE.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>WEBROLE.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Webrole.WEBROLE.WEBROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Webrole.WEBROLE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getWebroleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebroleRecord value1(Integer value) {
        setWebroleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebroleRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebroleRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WebroleRecord
     */
    public WebroleRecord() {
        super(Webrole.WEBROLE);
    }

    /**
     * Create a detached, initialised WebroleRecord
     */
    public WebroleRecord(Integer webroleId, String name) {
        super(Webrole.WEBROLE);

        set(0, webroleId);
        set(1, name);
    }
}
