/*
 * This file is generated by jOOQ.
*/
package ru.ibase.fbjavaex.exampledb.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.ibase.fbjavaex.exampledb.DefaultSchema;
import ru.ibase.fbjavaex.exampledb.Keys;
import ru.ibase.fbjavaex.exampledb.tables.records.WebroleRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Webrole extends TableImpl<WebroleRecord> {

    private static final long serialVersionUID = 943650369;

    /**
     * The reference instance of <code>WEBROLE</code>
     */
    public static final Webrole WEBROLE = new Webrole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WebroleRecord> getRecordType() {
        return WebroleRecord.class;
    }

    /**
     * The column <code>WEBROLE.WEBROLE_ID</code>.
     */
    public final TableField<WebroleRecord, Integer> WEBROLE_ID = createField("WEBROLE_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>WEBROLE.NAME</code>.
     */
    public final TableField<WebroleRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(63).nullable(false), this, "");

    /**
     * Create a <code>WEBROLE</code> table reference
     */
    public Webrole() {
        this("WEBROLE", null);
    }

    /**
     * Create an aliased <code>WEBROLE</code> table reference
     */
    public Webrole(String alias) {
        this(alias, WEBROLE);
    }

    private Webrole(String alias, Table<WebroleRecord> aliased) {
        this(alias, aliased, null);
    }

    private Webrole(String alias, Table<WebroleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WebroleRecord> getPrimaryKey() {
        return Keys.PK_WEBROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WebroleRecord>> getKeys() {
        return Arrays.<UniqueKey<WebroleRecord>>asList(Keys.PK_WEBROLE, Keys.UNQ_WEBROLE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Webrole as(String alias) {
        return new Webrole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Webrole rename(String name) {
        return new Webrole(name, null);
    }
}
