/*
 * This file is generated by jOOQ.
*/
package ru.ibase.fbjavaex.exampledb.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import ru.ibase.fbjavaex.exampledb.DefaultSchema;
import ru.ibase.fbjavaex.exampledb.Keys;
import ru.ibase.fbjavaex.exampledb.tables.records.WebuserinroleRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Webuserinrole extends TableImpl<WebuserinroleRecord> {

    private static final long serialVersionUID = -2015775080;

    /**
     * The reference instance of <code>WEBUSERINROLE</code>
     */
    public static final Webuserinrole WEBUSERINROLE = new Webuserinrole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WebuserinroleRecord> getRecordType() {
        return WebuserinroleRecord.class;
    }

    /**
     * The column <code>WEBUSERINROLE.ID</code>.
     */
    public final TableField<WebuserinroleRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>WEBUSERINROLE.WEBUSER_ID</code>.
     */
    public final TableField<WebuserinroleRecord, Integer> WEBUSER_ID = createField("WEBUSER_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>WEBUSERINROLE.WEBROLE_ID</code>.
     */
    public final TableField<WebuserinroleRecord, Integer> WEBROLE_ID = createField("WEBROLE_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>WEBUSERINROLE</code> table reference
     */
    public Webuserinrole() {
        this("WEBUSERINROLE", null);
    }

    /**
     * Create an aliased <code>WEBUSERINROLE</code> table reference
     */
    public Webuserinrole(String alias) {
        this(alias, WEBUSERINROLE);
    }

    private Webuserinrole(String alias, Table<WebuserinroleRecord> aliased) {
        this(alias, aliased, null);
    }

    private Webuserinrole(String alias, Table<WebuserinroleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WebuserinroleRecord> getPrimaryKey() {
        return Keys.PK_WEBUSERINROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WebuserinroleRecord>> getKeys() {
        return Arrays.<UniqueKey<WebuserinroleRecord>>asList(Keys.PK_WEBUSERINROLE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<WebuserinroleRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<WebuserinroleRecord, ?>>asList(Keys.FK_WEBUSERINROLE_USER, Keys.FK_WEBUSERINROLE_ROLE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Webuserinrole as(String alias) {
        return new Webuserinrole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Webuserinrole rename(String name) {
        return new Webuserinrole(name, null);
    }
}
