[[fblangref40-intro-de]]
= Über die Firebird 4.0-Sprachreferenz

Diese Sprachreferenz beschreibt die von Firebird 4.0 unterstützte SQL-Sprache.

Diese Firebird SQL Sprachreferenz ist die dritte zusammenhängende Dokument, das alle Aspekte der Abfragesprache betrachtet, die von Entwicklern für die Kommunikation ihrer Anwendungen mit dem Firebird Relation Database Management System benötigt werden.

[[fblangref40-intro-subject-de]]
== Thema

Das Kernthema dieses Dokuments ist die vollständige Implementierung der SQL-Abfragesprache.
Firebird entspricht weitestgehend den internationalen Standards für SQL in Bezug auf Datentypen, Datenspeicherstrukturen, Mechanismen zur referentiellen Integrität sowie Fähigkeiten zur Datenmanipulation und Zugriffsrechte.
Firebird beinhaltet außerdem eine robuste Prozedursprache -- procedural SQL (PSQL) -- für gespeicherte Prozeduren und Funktionen, Trigger und dynamisch ausführbare Code Blöcke.
Dies sind die Themen, die in diesem Dokument behandelt werden. 

[[fblangref40-intro-authors-de]]
== Urheberschaft

Für die Firebird 4.0-Version wurde die _Firebird 3.0-Sprachreferenz_ als Grundlage genommen, und Firebird 4.0-Informationen wurden basierend auf den _Firebird 4.0-Versionshinweisen_ und der Funktionsdokumentation hinzugefügt.

[[fblangref40-intro-contributors-de]]
=== Mitwirkende

[float]
==== Direkter Inhalt

* Dmitry Filippov (Autor)
* Alexander Karpeykin (Autor)
* Alexey Kovyazin (Autor, Editor)
* Dmitry Kuzmenko (Autor, Editor)
* Denis Simonov (Autor, Editor)
* Paul Vinkenoog (Autor, Designer)
* Dmitry Yemanov (Autor)
* Mark Rotteveel (Autor, Editor)

[float]
==== Ressourcen Inhalt

* Adriano dos Santos Fernandes
* Alexander Peshkov
* Vladyslav Khorsun
* Claudio Valderrama
* Helen Borrie
* und andere

[float]
==== Übersetzungen

* Martin Köditz, it & synergy GmbH

[[fblangref40-intro-bugs-de]]
== Melden von Fehlern oder fehlenden Inhalten

Wenn Sie in diesem Dokument Fehler, fehlende Inhalte oder andere Probleme finden, melden Sie dies bitte in unserer https://github.com/FirebirdSQL/firebird-documentation/issues[issue tracker^] der https://github.com/FirebirdSQL /firebird-documentation[firebird-dokumentation GitHub-Repository].

Pull Requests mit Änderungen und Fixes werden ebenfalls sehr geschätzt.

[[fblangref40-acknowledgements-de]]
== Anmerkungen

[float]
[[sponsors-donors-de]]
==== Sponsoren und andere Spender

Siehe auch https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref25/firebird-25-language-reference.html#fblangref25-acknowledgements[Acknowledgements^] in der Firebird 2.5 Language Reference für die Sponsoren der ersten russischen Version und ihrer Übersetzung.

[float]
[[sponsors01-native-de]]
===== Sponsoren der russischen Sprachreferenz

* https://www.moex.com[Moscow Exchange] (Russland)
+
_Moscow Exchange ist die größte Börsenholding in Russland und Osteuropa, gegründet am 19. Dezember 2011 durch die Zusammenlegung der Börsengruppen MICEX (gegründet 1992) und RTS (gegründet 1995).
Die Moskauer Börse gehört nach dem Handel mit Anleihen und der Gesamtkapitalisierung der gehandelten Aktien zu den 20 größten Börsen der Welt sowie zu den 10 größten Börsenplattformen für den Handel mit Derivaten._

* https://www.ib-aid.com[IBSurgeon] (https://ibase.ru[ibase.ru]) (Russland)
+
_Technischer Support und Entwickler administrativer Tools für das Firebird DBMS._

[[fblangref40-contributing-de]]
== Beitragen

Es gibt mehrere Möglichkeiten, wie Sie zur Dokumentation von Firebird oder Firebird im Allgemeinen beitragen können:

* Nehmen Sie an den Mailinglisten teil (siehe https://www.firebirdsql.org/en/mailing-lists/)
* Fehler melden oder Pull Requests auf GitHub senden (https://github.com/FirebirdSQL/)
* Werden Sie Entwickler (für Dokumentation kontaktieren Sie uns auf firebird-docs, für Firebird in
allgemein, verwenden Sie die Firebird-devel-Mailingliste)
* Spenden Sie an die Firebird Foundation (siehe https://www.firebirdsql.org/en/donate/)
* Werden Sie zahlendes Mitglied oder Sponsor der Firebird Foundation (siehe
https://www.firebirdsql.org/en/firebird-foundation/)