:sectnums!:

[appendix]
[[fblangref40-license-de]]
= Lizenzhinweise

Die Inhalte dieser Dokumentation sind Gegenstand der Public Documentation License Version 1.0 (die "`Lizenz`");
Sie d端rfen diese Dokumentation nur verwenden, sofern Sie die Bedingungen dieser Lizenz akzeptieren.
Kopien der Lizenz sind verf端gbar unter https://www.firebirdsql.org/pdfmanual/pdl.pdf (PDF) und https://www.firebirdsql.org/manual/pdl.html (HTML).

Die originale Dokumentation wurde unter dem Titel [ref]_Firebird 4.0 Language Reference_ erfasst.
Dieses Dokument basiert auf der [ref]_Firebird 3.0 Language Reference_.

Die urspr端nglichen Schreiber der Originaldokumentation sind: Paul Vinkenoog, Dmitry Yemanov, Thomas Woinke und Mark Rotteveel.
Verfasser der urspr端nglichen Texte in russisch sind Denis Simonov, Dmitry Filippov, Alexander Karpeykin, Alexey Kovyazin und Dmitry Kuzmenko.

Copyright (C) 2008-2021.
Alle Rechte vorbehalten.
(Kontakt mit dem Verfasser: paul at vinkenoog dot nl.)

Verfasser und Bearbeiter des inkludierten PDL-lizenzierten Materials sind: J. Beesley, Helen Borrie, Arno Brinkman, Frank Ingermann, Vlad Khorsun, Alex Peshkov, Nickolay Samofatov, Adriano dos Santos Fernandes, Dmitry Yemanov.

Enthaltene Teile unterliegen dem Copyright (C) 2001-2021 ihrer jeweiligen Verfasser.
Alle Rechte vorbehalten.

Mitwirkende: Mark Rotteveel.

Inhalte, die durch Mark Rotteveel erstellt wurden, unterliegen dem Copyright (C) 2018-2021.
Alle Rechte vorbehalten.
(Kontakt mit dem Verfasser: mrotteveel at users dot sourceforge dot net).

:sectnums:
