/*
 * This file is generated by jOOQ.
*/
package ru.ibase.fbjavaex.exampledb.routines;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;

import ru.ibase.fbjavaex.exampledb.DefaultSchema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpAddInvoice extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -1555547396;

    /**
     * The parameter <code>SP_ADD_INVOICE.INVOICE_ID</code>.
     */
    public static final Parameter<Integer> INVOICE_ID = createParameter("INVOICE_ID", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>SP_ADD_INVOICE.CUSTOMER_ID</code>.
     */
    public static final Parameter<Integer> CUSTOMER_ID = createParameter("CUSTOMER_ID", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>SP_ADD_INVOICE.INVOICE_DATE</code>.
     */
    public static final Parameter<Timestamp> INVOICE_DATE = createParameter("INVOICE_DATE", org.jooq.impl.SQLDataType.TIMESTAMP, false, false);

    /**
     * Create a new routine call instance
     */
    public SpAddInvoice() {
        super("SP_ADD_INVOICE", DefaultSchema.DEFAULT_SCHEMA);

        addInParameter(INVOICE_ID);
        addInParameter(CUSTOMER_ID);
        addInParameter(INVOICE_DATE);
    }

    /**
     * Set the <code>INVOICE_ID</code> parameter IN value to the routine
     */
    public void setInvoiceId(Integer value) {
        setValue(INVOICE_ID, value);
    }

    /**
     * Set the <code>CUSTOMER_ID</code> parameter IN value to the routine
     */
    public void setCustomerId(Integer value) {
        setValue(CUSTOMER_ID, value);
    }

    /**
     * Set the <code>INVOICE_DATE</code> parameter IN value to the routine
     */
    public void setInvoiceDate(Timestamp value) {
        setValue(INVOICE_DATE, value);
    }
}
