[#fbconf-repl-exclude-filter]
= `exclude_filter`

Pattern for tables to exclude in replication.

.Replication type
Synchronous, asynchronous

.Availability
[horizontal.compact]
Added:: 4.0

.Syntax
[listing,subs="+quotes,+macros"]
----
exclude_filter = [ <sql-regular-expression> ]

<sql-regular-expression> ::=
  !! See https://firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref50/fblangref50-commons-predicates.html#fblangref50-commons-syntaxregex[Syntax: SQL Regular Expressions] !!
----

.Default
_empty_ (exclude nothing)

By default, all tables in the _publication set_ of the database are replicated.
The `exclude_filter` can be used to reduce this to a subset (exclude those matching the `exclude_filter` -- possibly already limited to those matching the <<fbconf-repl-include-filter>>).

The _publication set_ of the database can be configured with https://firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref50/fblangref50-ddl.html#fblangref50-ddl-db-alter[`ALTER DATABASE`], https://firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref50/fblangref50-ddl-table.html#fblangref50-ddl-tbl-create[`CREATE TABLE`] and https://firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref50/fblangref50-ddl-table.html#fblangref50-ddl-tbl-alter[`ALTER TABLE`].
This is not covered by this reference.
For further details, see https://firebirdsql.org/file/documentation/release_notes/html/en/4_0/rlsnotes40.html#rnfb40-replication-setup[Setting Up Replication] in the _Firebird 4.0 Release Notes_.

The `exclude_filter` uses the SQL regular expression syntax, described in https://firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref50/fblangref50-commons-predicates.html#fblangref50-commons-syntaxregex[Syntax: SQL Regular Expressions] of the _Firebird 5.0 Language Reference_.

.Example
[listing]
----
database /path/to/example.fdb
{
  # Do not replicate tables with prefix DAT_, and tables CUSTOMER and ORDER
  exclude_filter = DAT\_%|CUSTOMER|ORDER
}
----

.See also
<<fbconf-repl-include-filter>>
