[#fbconf-repl-journal-archive-directory]
= `journal_archive_directory`

Directory to store archived replication segments.

.Replication type
Asynchronous

.Availability
[horizontal.compact]
Added:: 4.0

.Syntax
[listing,subs=+quotes]
----
journal_archive_directory = _path_
----

The journal archive directory is used to store replication segments (journal files) that are ready to be consumed by a replica using asynchronous replication.

Firebird will automatically move replication segments to this directory, unless <<fbconf-repl-journal-archive-command>> is defined.

If you have a single replica, the journal archive directory can be used directly by the replica (in <<fbconf-repl-journal-source-directory>>).
This can -- for example -- be done by mounting or otherwise sharing the directory between both hosts.

If you have multiple replicas, each replica must have its own copy of the journal archive.
Replicas will delete journal files they no longer need, which can conflict with the needs of another replica.
Make sure that each journal file created by Firebird in this directory is copied to a location unique to a replica, or use the <<fbconf-repl-journal-archive-command>> instead.

The value of this configuration item also defines the `$(archpathname)` macro used in <<fbconf-repl-journal-archive-command>>.

This configuration item can be omitted when <<fbconf-repl-journal-archive-command>> is specified _without_ the `$(archpathname)` macro.

.See also
<<fbconf-repl-journal-archive-command>>, <<fbconf-repl-journal-source-directory>>
