[#fbconf-repl-journal-archive-command]
= `journal_archive_command`

Program (complete commandline with arguments) that is executed when a replication segment is full and needs archiving.

.Replication type
Asynchronous

.Availability
[horizontal.compact]
Added:: 4.0

.Syntax
[listing,subs=+quotes]
----
journal_archive_command = _string_
----

This program *must* return exit-code zero *only* if archiving has been performed successfully.
In particular, it *must* return a non-zero exit-code if the target archive already exists.

Special predefined macros are available:

`$(filename)`::
filename (without path) of the journal segment being archived
`$(pathname)`::
full path of the journal segment being archived;
same as <<fbconf-repl-journal-directory>> + `$(filename)`
`$(archivepathname)`::
suggested full path for the archived segment;
same as <<fbconf-repl-journal-archive-directory>> + `$(filename)`

If `journal_archive_command` is used _without_ the `$(archivepathname)` macro, the configuration item <<fbconf-repl-journal-archive-directory>> can be omitted.

.A simple example using standard OS commands for archiving
[listing]
----
# Linux
journal_archive_command = "test ! -f $(archivepathname) && cp $(pathname) $(archivepathname)"

# Windows
journal_archive_command = "copy $(pathname) $(archivepathname)"
----

.See also
<<fbconf-repl-journal-directory>>, <<fbconf-repl-journal-archive-directory>>
