[#fbconf-repl-sync-replica]
= `sync_replica`

Connection information to the replica database (for synchronous replication).

.Replication type
Synchronous

.Availability
[horizontal.compact]
Added:: 4.0

.Syntax
[listing,subs=+quotes]
----
sync_replica = <connection-specification>

<connection-specification> ::=
    [_username_[:__password__]]@<database-url>
  | <database-url>
    '{'
      [ <key> = <value> <new-line> ]...
    '}'

<database-url> ::=
  !! _Normal Firebird database URL formats_ !!
----

// TODO: Verify if all URL formats are indeed supported

Multiple entries are allowed (for different synchronous replicas).

The value of `sync_replica` is either:

. a simple value with the database URL, optionally prefixed with a username and an optional password, or
. a <<fbconf-syntax-scope,scoped value>> where the simple value is *only* a database URL, and configuration of username and password is done through key-value items within the scope.

To specify a username or password containing `:` or `@`, you must use a scoped value.

// TODO What, if any, are the credentials used when none are specified, or incomplete?

.`sync_replica` configuration items
[cols="<1m,<3", options="header",stripes="none"]
|===
^| Item
^| Value

|username
|Username for connecting to the replica

|password
|Password for connecting to the replica

|username_file
|Path of a file containing the username for connecting to the replica;
the first non-empty line is the username

|password_file
|Path of a file containing the password for connecting to the replica;
the first non-empty line is the password

|username_env
|Name of an environment variable containing the username for connecting to the replica

|password_env
|Name of an environment variable containing the password for connecting to the replica

|===

At most one `username{asterisk}` and one `password{asterisk}` key may be specified.

If `username_file` or `password_file` have a relative path, the path is resolved against the Firebird root directory.

// TODO Double check if that is actually the case, and not, for example against $(this)

.Example
[listing]
----
# As simple value
sync_replica = john:smith@server2:replica

# As scoped value
sync_replica = server2:replica
{
  username = john
  password = smith
}

# Password sourced from file
sync_replica = server2:replica
{
  username = john
  password_file = /path/to/password.txt
}

# Username and password sourced from environment
sync_replica = server2:replica
{
  username_env = REPLICA_USERNAME
  password_env = REPLICA_PASSWORD
}
----
