[[rnfb40-bug]]
= Bugs Fixed

////
_(https://github.com/FirebirdSQL/firebird/issues/nnnn[#nnnn])_
-- A description

_fixed by A. Person_

'''
////

[[bug-400]]
== Firebird 4.0 Release: Bug Fixes

The following bug-fixes since the Release Candidate 1 are noted:

[[bug-400-core]]
=== Core Engine

_(https://github.com/FirebirdSQL/firebird/issues/6816[#6816])_
-- Illegal output length in `BASE64/HEX` `ENCODE/DECODE` functions.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6812[#6812])_
-- `BASE64_ENCODE` and `HEX_ENCODE` can exceed the maximum length for `VARCHAR`.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6805[#6805])_
-- `RDB$TYPES` has incorrect entries for `RDB$TYPE` 28 and 29 in `RDB$TYPE_NAME` column.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6804[#6804])_
-- Assertion in tomcrypt when the key length for _RC4_ is too small.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6800[#6800])_
-- Client config setting _DefaultTimeZone_ is not passed to server when _isc_dpb_session_time_zone_ is not set.

_fixed by A. dos Santos Fernandes_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6797[#6797])_
-- Functions `DECRYPT` and `RSA_DECRYPT` return `VARCHAR CHARACTER SET NONE` instead of `VARBINARY (VARCHAR CHARACTER SET OCTETS)`.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6795[#6795])_
-- Replication gets stuck due to _"Blob xxx.xx is not found for table xxx"_ error.

_fixed by D. Yemanov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6790[#6790])_
-- `MON$ATTACHMENTS.MON$TIMESTAMP` is incorrect when _DefaultTimeZone_ is configured with time zone different from the server's default.

_fixed by A. dos Santos Fernandes_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6787[#6787])_
-- `MON$ATTACHMENTS.MON$TIMESTAMP` should use its session original time zone.

_fixed by A. dos Santos Fernandes_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6785[#6785])_
-- Problem when restoring the database on Firebird 4 RC1.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6782[#6782])_
-- Cannot get "records fetched" for selectable procedures in trace.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6778[#6778])_
-- Inconsistent cursor-driven deletion.

_fixed by D. Yemanov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6768[#6768])_
-- Cannot restore backup on a raw device (_error during "open O_CREAT" operation for file "/dev/sda1"_).

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6761[#6761])_
-- Hash join cannot match records using some `TIME ZONE` / `DECFLOAT` keys.

_fixed by D. Yemanov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6759[#6759])_
-- Results of concatenation with blob has no info about collation of source columns (which are declared with such info).

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6758[#6758])_
-- `COMPUTED BY` column looses charset and collate of source field <F> when <F> is either of type `BLOB` or `VARCHAR` casted to `BLOB`.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6756[#6756])_
-- Error _"no current record for fetch operation"_ when sorting by an international string.

_fixed by D. Yemanov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6750[#6750])_
-- `CAST` of Infinity values to `FLOAT` doesn't work.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6749[#6749])_
-- Error _"Invalid time zone (+08). Falling back to displacement"_ in firebird.log.

_fixed by A. dos Santos Fernandes_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6747[#6747])_
-- Wrong message when connecting to tiny trash database file.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6746[#6746])_
-- Regression: CREATE DATABASE fails with 'Token unknown' error when DB name is enclosed in double quotes and 'DEFAULT CHARACTER SET' is specified after DB name.

_fixed by A. dos Santos Fernandes_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6734[#6734])_
-- Provide same results for date arithmetics when date is changed by values near +/-max(bigint).

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6733[#6733])_
-- Attempt to create database with page_size >= 65536 makes DB with actual page size = _4KB_ or _8KB_, but not _32KB_ as it should.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6727[#6727])_
-- Synchronous replication to localhost hangs on disconnect.

_fixed by D. Yemanov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6724[#6724])_
-- Inconsistent translation _"string->timestamp->string->timestamp"_ in Dialect 1.

_fixed by A. dos Santos Fernandes_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6719[#6719])_
-- User without `ALTER ANY ROLE` privilege can use `COMMENT ON ROLE`.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6717[#6717])_
-- `FETCH ABSOLUTE` and `RELATIVE` beyond bounds of cursor should always position immediately before-first or after-last.

_fixed by D. Yemanov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6716[#6716])_
-- `FETCH RELATIVE` has an off by one error for the first row.

_fixed by D. Yemanov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6710[#6710])_
-- `COMMENT ON USER` can only apply comment on user defined by the default user manager plugin.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6700[#6700])_
-- Wire compression causes sporadic _"Error reading data from the connection"_ errors.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6698[#6698])_
-- Comments before the first line of code are removed.

_fixed by A. dos Santos Fernandes_

'''

_(https://github.com/FirebirdSQL/firebird/issues/3810[#3810])_
-- Wrong or missing `IS NULL` optimization.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/3106[#3106])_
-- Many indexed reads in a compound index with NULLs.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/2469[#2469])_
-- Stored procedure recursively called by calculated field fails after reconnect.

_fixed by V. Khorsun_

'''

[[bug-400-crashes]]
=== Server Crashes/Hang-ups

_(https://github.com/FirebirdSQL/firebird/issues/6808[#6808])_
-- Segfault in `ENCRYPT/DECRYPT` functions when their first argument is _NULL_.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6781[#6781])_
-- Crashing (due to UDF exception) process hangs.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6777[#6777])_
-- AV when the engine shuts down and cancels an attachment waiting in the lock manager.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6766[#6766])_
-- Replication plugin can crash the engine by returning _nullptr_ from _startTransaction()_ method.

_fixed by D. Yemanov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6754[#6754])_
-- Connect to database that contains broken pages can lead to a server crash.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6753[#6753])_
-- AV in the engine when _StatementTimeout_ is active for user statement and some internal DSQL statement was executed as part of overall execution process.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6752[#6752])_
-- Segfaults in _fbclient_ when receiving invalid / unexpected data from the server.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6751[#6751])_
-- Various segfaults in _fbclient_.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6738[#6738])_
-- Segfault when _GFIX_ requests for database page buffer more memory than available from OS.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6731[#6731])_
-- Segfault when shutting down database which got encrypted by another process.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6708[#6708])_
-- Rare race condition in Plugin Manager could lead to the server crash.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6265[#6265])_
-- Segfault when using expression index with complex expression.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/5784[#5784])_
-- When 32-bit and 64-bit Firebird 3 servers run on a single Windows machine concurrently, Firebird services freeze several minutes after first disconnect.

_fixed by V. Khorsun_

'''

[[bug-400-api]]
=== API/Remote Interface

_(https://github.com/FirebirdSQL/firebird/issues/6718[#6718])_
-- Event delivery could be missed when local (XNET) protocol is used.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6679[#6679])_
-- _CLOOP_ envelopes are wrong regarding IStatus.

_fixed by A. Peshkov_

'''

[[bug-400-builds]]
=== Build Issues

_(https://github.com/FirebirdSQL/firebird/issues/6780[#6780])_
-- firebird.msg is missing in Firebird Android builds.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6745[#6745])_
-- Protect included tomcrypt library from being overwritten by a system package.

_fixed by A. Peshkov_

'''

[[bug-400-utilities]]
=== Utilities

[[bug-400-utilities-isql]]
==== isql

_(https://github.com/FirebirdSQL/firebird/issues/6796[#6796])_
-- Buffer overflow when padding line with national characters causes _ISQL_ to crash.

_fixed by A. dos Santos Fernandes_

'''

[[bug-400-utilities-gbak]]
==== gbak

_(https://github.com/FirebirdSQL/firebird/issues/6709[#6709])_
-- _GBAK_ discards replica mode during backup/restore.

_fixed by D. Yemanov_

'''

[[bug-400-utilities-gstat]]
==== gstat

_(https://github.com/FirebirdSQL/firebird/issues/6729[#6729])_
-- Regression: _GSTAT_ with switch -t executed via services fails with _"found unknown switch"_ error.

_fixed by A. Peshkov_

'''

[[bug-400rc1]]
== Firebird 4.0 Release Candidate 1: Bug Fixes

The following bug-fixes since the Beta 2 release are noted:

[[bug-400rc1-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-6475[CORE-6475])_
-- Memory leak when running EXECUTE STATEMENT with named parameters.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6472[CORE-6472])_
-- Wrong byte order for UUIDs reported by _GSTAT_ and monitoring tables.

_fixed by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6460[CORE-6460])_
-- Incorrect query result when using named window.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6453[CORE-6453])_
-- `EXECUTE STATEMENT` fails on FB 4.x if containing time/timestamp with time zone parameters.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6447[CORE-6447])_
-- Unexpectedly different text of message for parameterized expression starting from second run.
Same fix was backported to Firebird 3.0.8.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6441[CORE-6441])_
-- Srp plugin keeps connection after database has been removed for ~10 seconds.
Same fix was backported to Firebird 3.0.8.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6440[CORE-6440])_
-- Expression indexes containing `COALESCE` inside cannot be matched by the optimizer after migration from v2.5 to v3.0.
Same fix was backported to Firebird 3.0.8.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6437[CORE-6437])_
-- GFIX cannot set big value for page buffers.
Same fix was backported to Firebird 3.0.8.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6427[CORE-6427])_
-- Whitespace as date separator causes conversion error.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6421[CORE-6421])_
-- Parameter in offset expression in `LAG, LEAD, NTH_VALUE` window functions requires explicit cast to `BIGINT` or `INTEGER`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6419[CORE-6419])_
-- Truncation of strings to put in MON$ tables do not work correctly.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6415[CORE-6415])_
-- Error "malformed string' is raised instead of "expected: N, actual: M" when UTF-8 charset is used and default value is longer than the column length.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6414[CORE-6414])_
-- Error "expected length N, actual M" contains wrong value of M when UTF-8 charset is used in the field declaration.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6408[CORE-6408])_
-- `RETURNING` clause in the `MERGE` statement cannot reference column in aliased target table using qualified reference (alias.column) if `DELETE` action present.
Same fix was backported to Firebird 3.0.8.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6403[CORE-6403])_
-- Some PSQL statements may lead to exceptions report wrong line/column.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6398[CORE-6398])_
-- Error converting string with hex representation of `INTEGER` to `SMALLINT`.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6397[CORE-6397])_
-- Message length error with `COALESCE` and `TIME / TIMESTAMP WITHOUT TIME ZONE` and `WITH TIME ZONE`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6389[CORE-6389])_
-- Using binary string literal to assign to user-defined blob sub-types yield conversion error.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6386[CORE-6386])_
-- `ALTER SEQUENCE RESTART WITH <n>` should not change the initial sequence `START` value.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6385[CORE-6385])_
-- Wrong line and column information after IF statement.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6379[CORE-6379])_
-- Bugcheck 179 (decompression overran buffer).

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6376[CORE-6376])_
-- `IDENTITY` column with explicit `START WITH` or `INCREMENT BY` starts with wrong value.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6357[CORE-6357])_
-- `LEAD()` and `LAG()` do not allow to specify 3rd argument of `INT128` datatype.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6356[CORE-6356])_
-- `ROUND()` does not allow second argument >=1 when its first argument is more than MAX_BIGINT / 10.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6355[CORE-6355])_
-- `TRUNC()` does not accept second argument = -128 (but shows it as required boundary in error message).

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6353[CORE-6353])_
-- `INT128` data type has problems with some PSQL objects.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6344[CORE-6344])_
-- Invalid return type for functions with `INT128 / NUMERIC(38)` argument.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6337[CORE-6337])_
-- Sub-type information is lost when calculating arithmetic expressions.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6336[CORE-6336])_
-- Error "Implementation of text subtype <NNNN> not located" on attempt to use some collations defined in fbintl.conf.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6335[CORE-6335])_
-- `INSERT ... RETURNING` does not require a SELECT privilege.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6328[CORE-6328])_
-- FB4 Beta 2 may still be using the current date for `TIME WITH TIME ZONE` and extended wire protocol.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6325[CORE-6325])_
-- `NTILE/RANK/PERCENT_RANK` may cause problems in big/complex statements.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6318[CORE-6318])_
-- `CAST('NOW' as TIME)` raises a conversion error.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6316[CORE-6316])_
-- Unable to specify new 32KB page size in `CREATE DATABASE` statement.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6303[CORE-6303])_
-- Error writing to `TIMESTAMP / TIME WITH TIME ZONE` array.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6302[CORE-6302])_
-- Error writing an array of `NUMERIC(24,6)` to the database.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6084[CORE-6084])_
-- `CREATE SEQUENCE START WITH` has wrong initial value.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6023[CORE-6023])_
-- FB4 is unable to overwrite older ODS database.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5838[CORE-5838])_
-- Rotated trace files are locked by the engine.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4985[CORE-4985])_
-- A non-privileged user could implicitly count records in a restricted table.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2274[CORE-2274])_
-- `MERGE` has a non-standard behaviour, accepts multiple matches.

_fixed by V. Khorsun_

'''

[[bug-400rc1-crashes]]
=== Server Crashes/Hang-ups

_(http://tracker.firebirdsql.org/browse/CORE-6450[CORE-6450])_
-- Races in the security databases cache could lead to the server crash.
Same fix was backported to Firebird 3.0.8.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6433[CORE-6433])_
-- Server could crash during a daily maintenance / set statistics index.
Same fix was backported to Firebird 3.0.8.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6412[CORE-6412])_
-- Firebird was freezing when trying to manage users via triggers.
Same fix was backported to Firebird 3.0.8.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6387[CORE-6387])_
-- Client process was aborting due to bugs inside the ChaCha plugin.

_fixed by A. Peshkov_

'''

[[bug-400rc1-api]]
=== API/Remote Interface

_(http://tracker.firebirdsql.org/browse/CORE-6432[CORE-6432])_
-- Possible buffer overflow in client library in `Attachment::getInfo()` call.
Same fix was backported to Firebird 3.0.8.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6426[CORE-6426])_
-- Assertion when the batch is executed without a BLOB field.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6425[CORE-6425])_
-- Exception in client library in `IAttachment::createBatch()`.

_fixed by A. Peshkov_

'''

[[bug-400rc1-builds]]
=== Build Issues

_(http://tracker.firebirdsql.org/browse/CORE-6305[CORE-6305])_
-- Android port build failure.

_fixed by A. Peshkov_

'''

[[bug-400rc1-utilities]]
=== Utilities

[[bug-400rc1-utilities-isql]]
==== isql

_(http://tracker.firebirdsql.org/browse/CORE-6438[CORE-6438])_
-- Bad headers when text columns has >= 80 characters.

_fixed by A. dos Santos Fernandes_

'''

[[bug-400rc1-utilities-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-6377[CORE-6377])_
-- Unable to restore database with tables using `GENERATED ALWAYS AS IDENTITY` columns.

_fixed by A. Peshkov_

'''

[[bug-400b2]]
== Firebird 4.0 Beta 2 Release: Bug Fixes

The following bug-fixes since the Beta 1 release are noted:

[[bug-400b2-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-6290[CORE-6290])_
-- Hex number used at the end of statement could read invalid memory and produce wrong values or exceptions.
Same fix was backported to Firebird 3.0.6.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6282[CORE-6282])_
-- Data type of `MON$ATTACHMENTS.MON$IDLE_TIMER` and `MON$STATEMENTS.MON$STATEMENT_TIMER` was defined as `TIMESTAMP WITHOUT TIME ZONE`, now it's changed to `TIMESTAMP WITH TIME ZONE`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6281[CORE-6281])_
-- Invalid timestamp errors could happen when working with the `RDB$TIME_ZONE_UTIL.TRANSITIONS` procedure.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6280[CORE-6280])_
-- MERGE statement could lose parameters in the "```WHEN [NOT] MATCHED```" clause that will never be matched.
This could also cause server crashes in some situations.
Same fix was backported to Firebird 3.0.6.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6272[CORE-6272])_
-- Failed attach to a database was not traced.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6266[CORE-6266])_
-- Deleting records from `MON$ATTACHMENTS` using the `ORDER BY` clause didn't close the corresponding attachments.
Same fix was backported to Firebird 3.0.6.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6251[CORE-6251])_
-- `UNIQUE CONSTRAINT` violation could be possible.
Same fix was backported to Firebird 3.0.6.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6250[CORE-6250])_
-- Signature mismatch error could be raised when creating package body on identical packaged procedure header.
Same fix was backported to Firebird 3.0.6.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6248[CORE-6248])_
-- A number of errors could happen when database name is longer than 255 characters.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6243[CORE-6243])_
-- v4 Beta 1 regression happened: the engine rejects `POSITION` element of the SQL:2003 `CREATE TRIGGER` syntax.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6241[CORE-6241])_
-- Values greater than number of days between 01.01.0001 and 31.12.9999 (=3652058) could be added or subtracted from `DATE`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6238[CORE-6238])_
-- `DECFLOAT`: subtraction ("```Num1 - Num2```") would lead to the "`Decimal float overflow`" error if `Num2` is specified in scientific notation and is less than max double (1.7976931348623157e308).

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6236[CORE-6236])_
-- `RDB$TIME_ZONE_UTIL` package had wrong privilege defined for `PUBLIC`.

_fixed by A. dos Santos Fernandes, D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6230[CORE-6230])_
-- It was impossible to connect to a database if `security.db` reference was removed from `databases.conf`.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6221[CORE-6221])_
-- Incorrect implementation of `allocFunc()` for zlib1: memory leak was possible.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6214[CORE-6214])_
-- tzdata database version was outdated and required an update.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6206[CORE-6206])_
-- `VARCHAR` of insufficient length was used for command `SET BIND OF DECFLOAT TO VARCHAR`.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6205[CORE-6205])_
-- Improper error was raised for `UNION DISTINCT` with more than 255 columns.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6186[CORE-6186])_
-- Original contents of the column used with `ENCRYPT()` looked as distorted after this call.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6181[CORE-6181])_
-- Usage of "```SET DECFLOAT BIND BIGINT,n```" with result of 11+ digits, would fail with the "`Decimal float invalid operation`" error.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6166[CORE-6166])_
-- Some problems could appear for long object names (> 255 bytes).

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6160[CORE-6160])_
-- `SUBSTRING` of non-text/-blob was described to return `NONE` character set in DSQL.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6159[CORE-6159])_
-- `SUBSTRING` SIMILAR was described with wrong data type in DSQL.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6110[CORE-6110])_
-- 64-bit transaction IDs were not stored properly inside the status vector.

_fixed by I. Eremin_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6080[CORE-6080])_
-- Attempt to drop an existing user could randomly fail with error "`336723990 : record not found for user`".

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6046[CORE-6046])_
-- Incorrect time zone parsing could read garbage in memory.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6034[CORE-6034])_
-- The original time zone was not set to the current time zone at the routine invocation.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6033[CORE-6033])_
-- `SUBSTRING(CURRENT_TIMESTAMP ...)` would fail with a "`string truncation`" error.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5957[CORE-5957])_
-- Adding a numeric quantifier as a bound for repetition of expression inside `SIMILAR TO` could lead to an empty resultset.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5931[CORE-5931])_
-- `SIMILAR TO` did not return the result when an invalid pattern was used.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5892[CORE-5892])_
-- SQL SECURITY _DEFINER_ context was not properly evaluated for monitoring tables.

_fixed by R. Simakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5697[CORE-5697])_
-- Conversion from numeric literals to `DECFLOAT` would add the precision that is not originally present.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5696[CORE-5696])_
-- Conversion from zero numeric literals to `DECFLOAT` would lead to the incorrect result.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5664[CORE-5664])_
-- `SIMILAR TO` was substantially (500-700x) slower than `LIKE` on trivial pattern matches with `VARCHAR` data.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4874[CORE-4874])_
-- Server could perform a `SIMILAR TO` matching infinitely.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4739[CORE-4739])_
-- Accent insensitive comparison: diacritical letters with diagonal crossing stroke failed for non-equality conditions with their non-accented forms.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3858[CORE-3858])_
-- Very poor performance of `SIMILAR TO` for some arguments.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3380[CORE-3380])_
-- It was possible to read from the newly created BLOB.
It's prohibited now.

_fixed by A. dos Santos Fernandes_

'''

[[bug-400b2-crashes]]
=== Server Crashes/Hang-ups

_(http://tracker.firebirdsql.org/browse/CORE-6254[CORE-6254])_
-- Server could crash when using `SET TRANSACTION` and `ON TRANSACTION START` trigger uses `EXECUTE STATEMENT` against current transaction.
Same fix was backported to Firebird 3.0.6.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6253[CORE-6253])_
-- Locked fb_lock file could cause a server crash.
Same fix was backported to Firebird 3.0.6.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6251[CORE-6251])_
-- Server would crash when built-in function `LEFT` or `RIGHT` is missing its 2nd argument.
Same fix was backported to Firebird 3.0.6.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6231[CORE-6231])_
-- Server would crash during shutdown of XNET connection to a local database when events have been registered.
Same fix was backported to Firebird 3.0.6.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6224[CORE-6224])_
-- Server could crash due to double destruction of the rem_port object.
Same fix was backported to Firebird 3.0.6.

_fixed by D. Kovalenko, A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6218[CORE-6218])_
-- `COUNT(DISTINCT DECFLOAT_FIELD)` could cause the server to crash when there are duplicate values in this field.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6217[CORE-6217])_
-- Dangerous (possibly leading to a crash) work with pointer: `delete ptr; ptr=new ;`.

_fixed by D. Kovalenko, A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5972[CORE-5972])_
-- External engine trigger would crash the server if the table has computed fields.
Same fix was backported to Firebird 3.0.6.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4893[CORE-4893])_
-- `SIMILAR TO` would cause a server crash when matching a blob with size >2GB to a string literal.

_fixed by A. dos Santos Fernandes_

'''

[[bug-400b2-api]]
=== API/Remote Interface

_(http://tracker.firebirdsql.org/browse/CORE-6283[CORE-6283])_
-- Result of `isNullable()` in message metadata, returned by metadata builder, did not match datatype set by `setType()` in metadata builder.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6227[CORE-6227])_
-- `isc_info_svc_user_dbpath` was always returning an alias of the main security database.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6212[CORE-6212])_
-- Authentication plugin on the server could read garbage data from the client instead of the empty packet.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6207[CORE-6207])_
-- It was impossible to compile Firebird.pas with FPC.

_fixed by A. Peshkov_

'''

[[bug-400b2-builds]]
=== Build Issues

_(http://tracker.firebirdsql.org/browse/CORE-6174[CORE-6174])_
-- `ibase.h` was missing from the nightly builds.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6170[CORE-6170])_
-- Installation on CentOS 8 failed because of the mismatched version of LibTomMath and LibNCurses libraries.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6061[CORE-6061])_
-- It was impossible to build the server with the `--with-builtin-tommath` option.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6056[CORE-6056])_
-- Overflow warnings appeared when building some collations.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6019[CORE-6019])_
-- Wire compression did not work without the MSVC 2010 runtime package installed.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5691[CORE-5691])_
-- File description of the Firebird executables was not specific.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5445[CORE-5445])_
-- Installation failed on Debian Stretch/Testing due to incorrect version of the LibTomMath library.

_fixed by A. Peshkov_

'''

[[bug-400b2-utilities]]
=== Utilities

[[bug-400b2-utilities-isql]]
==== isql

_(http://tracker.firebirdsql.org/browse/CORE-6262[CORE-6262])_
-- `SHOW DOMAIN/TABLE` did not display the character set of system objects.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6260[CORE-6260])_
-- Warnings were not always displayed in ISQL.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6211[CORE-6211])_
-- Command "```isql -X```" could not extract the `ROLE` name when using a multi-byte charset for the connection.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6116[CORE-6116])_
-- Metadata script extracted with ISQL from a database restored from a v2.5 backup was invalid if some table has `COMPUTED BY` fields.
Same fix was backported to Firebird 3.0.6.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6044[CORE-6044])_
-- Some issues were noticed due to the increased SQL identifier length.

_fixed by A. dos Santos Fernandes_

'''

[[bug-400b2-utilities-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-6265[CORE-6265])_
-- Existing mapping rules were removed by the backup/restore cycle.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6233[CORE-6233])_
-- Wrong dependencies of stored function on view were created after backup/restore.
Same fix was backported to Firebird 3.0.6.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6208[CORE-6208])_
-- `CREATE DATABASE` permission would disappear from security database after the backup/restore cycle.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6130[CORE-6130])_
-- Creating backup to `STDOUT` using the service manager was broken.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6071[CORE-6071])_
-- Restoring an encrypted backup of a SQL dialect 1 database would fail.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5976[CORE-5976])_
-- GBAK multi-database file restore used wrong minimum number of pages for the first database file.

_fixed by M. Rotteveel_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2251[CORE-2251])_
-- GBAK doesn't return the error code in some cases.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

[[bug-400b2-utilities-gfix]]
==== gfix

_(http://tracker.firebirdsql.org/browse/CORE-5364[CORE-5364])_
-- `gfix -online normal` did not raise an error when there was another SYSDBA-owned session open.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

[[bug-400b1]]
== Firebird 4.0 Beta 1 Release: Bug Fixes

The following bug-fixes since the Alpha release are noted:

[[bug-400b1-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-5986[CORE-5986])_
-- Evaluation of `NULL IS [NOT] FALSE | TRUE` was incorrect.
Same fix was backported to Firebird 3.0.5.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5985[CORE-5985])_
-- Regression: `ROLE` was not being passed to ES/EDS: specifying it in the statement was ignored.
Same fix was backported to Firebird 3.0.5.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5982[CORE-5982])_
-- An error involving read permission for a BLOB field was being thrown when the BLOB was an input or output parameter for a procedure.
Same fix was backported to Firebird 3.0.5.

_fixed by D. Starodubov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5974[CORE-5974])_
-- `SELECT DISTINCT` with a decfloat/timezone/collated column was producing wrong results.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5973[CORE-5973])_
-- Improvement: Fixed-point overflow in a `DOUBLE PRECISION` value converted from `DECFLOAT` is now handled properly.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5965[CORE-5965])_
-- The optimizer was choosing a less efficient plan in FB4 and FB3 than the FB2.5 optimizer.
Same fix was backported to Firebird 3.0.5.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5959[CORE-5959])_
-- Firebird would return the wrong time after a change of time zone.
Same fix was backported to Firebird 3.0.5.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5950[CORE-5950])_
-- Deadlock could occur when attaching to a bugchecked database.
Same fix was backported to Firebird 3.0.5.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5949[CORE-5949])_
-- Bugcheck could happen when a read-only  database with non-zero linger was set to read-write mode.
Same fix was backported to  Firebird 3.0.5.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5935[CORE-5935])_
-- Bugcheck 165 (cannot find TIP page). Same fix was backported to Firebird 3.0.5.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5930[CORE-5930])_
-- Bugcheck with message "`incorrect snapshot deallocation - too few slots`".

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5918[CORE-5918])_
-- Memory pool statistics were inaccurate.
Same fix was backported to Firebird 3.0.5.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5896[CORE-5896])_
-- A `NOT NULL` constraint was not being synchronized after the column was renamed.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5785[CORE-5785])_
-- An `ORDER BY` clause on a compound index could disable usage of other indices.
Same fix was backported to Firebird 3.0.5.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5871[CORE-5871])_
-- Incorrect caching of the result of a subquery result in a procedure call from a `SELECT` query.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5862[CORE-5862])_
-- `RDB$CHARACTER_LENGTH` in `RDB$FIELDS` was not being populated when the column was a computed `VARCHAR` without an explicit type.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5750[CORE-5750])_
-- Date-time parsing needed strengthening.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5728[CORE-5728])_
-- The field subtype of DEC_FIXED columns was not returned by `isc_info_sql_sub_type`.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5726[CORE-5726])_
-- The error message when inserting a value exceeding the maximum value of DEC_FIXED decimal was unclear.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5717[CORE-5717])_
-- The literal date/time prefix syntax (`DATE`, `TIME` or `TIMESTAMP` prefix before the quoted value) used together with the implicit date/time literal expressions (`'NOW'`, `'TODAY'`, etc.) was known to evaluate those expressions in ways that would produce unexpected results, often undetected.
This behaviour was considered undesirable -- the Firebird 4.0 engine and above will now reject them everywhere.

For details, see <<rnfb40-compat-sql-prefixed-literals,Prefixed Implicit Date/Time Literals Now Rejected>> in the Compatibility chapter.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5710[CORE-5710])_
-- Data type declaration `DECFLOAT` without precision should be using a default precision.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5700[CORE-5700])_
-- `DECFLOAT` underflow should yield zero instead of an error.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5699[CORE-5699])_
-- `DECFLOAT` should not throw exceptions when +/-NaN,  +/-sNaN and +/-Infinity is used in comparisons.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5646[CORE-5646])_
-- A parse error when compiling a statement would cause a memory leak until the attachment was disconnected.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5612[CORE-5612])_
-- View operations (create, recreate or drop) were exhibiting gradual slow-down.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5611[CORE-5611])_
-- Memory consumption for prepared statements was higher.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5593[CORE-5593], http://tracker.firebirdsql.org/browse/CORE-5518[CORE-5518])_
-- The system function `RDB$ROLE_IN_USE` could not take long role names.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5480[CORE-5480])_
-- A `SUBSTRING` start position smaller than 1 should be allowed.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-1592[CORE-1592])_
-- Altering procedure parameters could lead to an unrestorable database.

_fixed by A. dos Santos Fernandes_

'''

[[bug-400b1-crashes]]
=== Server Crashes/Hang-ups

_(http://tracker.firebirdsql.org/browse/CORE-5980[CORE-5980])_
-- Firebird would crash due to concurrent operations with expression indices.
Same fix was backported to Firebird 3.0.5.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5972[CORE-5972])_
-- External engine trigger could crash the server if the table had a computed field.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5943[CORE-5943])_
-- The server could crash while preparing a query with both `DISTINCT`/`ORDER BY` and a non-field expression in the select list.
Same fix was  backported to Firebird 3.0.5.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5936[CORE-5936])_
-- The server could segfault at the end of a database backup.

_fixed by V. Khorsun_

'''

[[bug-400b1-security]]
=== Security

_(http://tracker.firebirdsql.org/browse/CORE-5927[CORE-5927])_
-- With some non-standard authentication plugins, traffic would remain unencrypted despite providing the correct crypt key.
Same fix was backported to Firebird 3.0.5.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5926[CORE-5926])_
-- An attempt to create a mapping with a non-ASCII user name that was encoded in a *single-byte* codepage (e.g. `WIN1251`) would lead to a "`Malformed string`" error.
Same fix was backported to Firebird 3.0.5.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5861[CORE-5861])_
-- New objects and some old objects in a database could not be granted the `GRANT OPTION` via role privileges.

_fixed by R. Simakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5657[CORE-5657])_
-- Attended to various UDF-related security vulnerabilities, resulting in aggressive deprecation of support for the use of UDFs as external functions.
See also <<rnfb40-engine-deprecated-udfs,External Functions (UDFs) Feature Deprecated>> in the the chapter <<rnfb40-engine,Changes to the Firebird Engine>> and <<rnfb40-compat-udfs,Deprecation of External Functions (UDFs)>> in the <<rnfb40-compat,Compatibility>> chapter.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5639[CORE-5639])_
-- Mapping rule using WIN_SSPI plugin: Windows user group conversion to Firebird role was not working.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5518[CORE-5518])_
-- Firebird UDF `string2blob()` could allow remote code execution.

_fixed by A. Peshkov_

'''

[[bug-400b1-utilities]]
=== Utilities

[[bug-400b1-utilities-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-5855[CORE-5855])_
-- A database with generators containing space characters in their names could not be backed up.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5800[CORE-5800])_
-- After backup/restore, expression indexes on computed fields would not work properly.
Same fix was backported to Firebird 3.0.5.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5637[CORE-5637])_
-- A string right truncation error was occurring on restore of the security database.

_fixed by A. Peshkov_

'''

[[bug-400b1-utilities-gpre]]
==== gpre

_(http://tracker.firebirdsql.org/browse/CORE-5934[CORE-5834])_
-- `gpre_boot` was failing to link using `cmake`, giving undefined reference 'dladdr' and 'dlerror'.
Same fix was backported to Firebird 3.0.5.

_fixed by A. Peshkov_

'''

[[bug-400b1-utilities-trace]]
==== trace

_(http://tracker.firebirdsql.org/browse/CORE-5907[CORE-5907])_
-- Regression: Trace could not be launched if its 'database' section contained a regular expression pattern with curvy brackets to enclose a quantifier.
Same fix was backported to Firebird 3.0.5.

_fixed by A. Peshkov_

'''

[[bug-400b1-builds]]
=== Build Issues

_(http://tracker.firebirdsql.org/browse/CORE-5989[CORE-5989])_
-- Some build issues involving iconv / libiconv 1.15 vs libc / libiconv_open | common/isc_file.cpp.
Same fix was backported to Firebird 3.0.5.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5955[CORE-5955])_
-- Static linking problem with ld >= 2.31.
Same fix was backported to Firebird 3.0.5.

_fixed by R. Simakov_

'''

[[bug-400a1]]
== Firebird 4.0 Alpha 1 Release: Bug Fixes

The following fixes to pre-existent bugs are noted:

[[fb4a1-trigger-fix]]
_(http://tracker.firebirdsql.org/browse/CORE-5545[CORE-5545])_
-- Using the `POSITION` parameter with the `[RE]CREATE TRIGGER` syntax would cause an "`unknown token`" error if `POSITION` was written in the logically correct place, i.e. after the main clauses of the statement.
For example, the following should work because `POSITION` comes after the other specifications:

[source]
----
RECREATE TRIGGER T1
BEFORE INSERT
ON tbl
POSITION 1 AS
BEGIN
  --
END
----

However, it would exhibit the error, while the following would succeed:

[source]
----
RECREATE TRIGGER T1
BEFORE INSERT
POSITION 1
ON tbl
AS
BEGIN
  --
END
----

The fix makes the first example correct, and the second should throw the error.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5454[CORE-5454])_
-- Inserting into an updatable view without an explicit column list would fail.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5408[CORE-5408])_
-- The result of a Boolean expression could not be concatenated with a string literal.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5404[CORE-5404])_
-- Inconsistent column and line references were being returned in error messages for faulty PSQL definitions.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5237[CORE-5237])_
-- Processing of the `include` clause in configuration files was mishandling dot ('```.```') and asterisk ('```{asterisk}```') characters in the file name and path of the included file.

_fixed by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5223[CORE-5223])_
-- Double dots in file names for databases were prohibited if the `DatabaseAccess` configuration parameter was set to restrict access to a list of directories.

_fixed by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5141[CORE-5141])_
-- Field definition would allow multiple `NOT NULL` clauses.
For example, 

[source]
----
create table t (a integer not null not null not null)
----

The fix makes the behaviour consistent with `CREATE DOMAIN` behaviour, and the example will return the error "`Duplicate specification of NOT NULL - not supported`".

_fixed by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4701[CORE-4701])_
-- Garbage collection for indexes and BLOBs was not taking data in the Undo log into account.

_fixed by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4483[CORE-4483])_
-- In PSQL, data changed by executing a procedure was not visible to the `WHEN` handler if the exception occurred in the called procedure.

_fixed by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4424[CORE-4424])_
-- In PSQL, execution flow would roll back to the wrong savepoint if multiple exception handlers were executed at the same level.

_fixed by D. Sibiryakov_

'''
