[[rnfb40-bug]]
= Bugs Fixed

////
_https://github.com/FirebirdSQL/firebird/issues/nnnn[#nnnn (CORE-mmmm)]_
-- A description

_fixed by A. Person_

'''
////

[[bug-406]]
== Firebird 4.0.6 Release: Bug Fixes

[[bug-406-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/8554[#8554]_
-- Vulnerability GHSA-7qp6-hqxj-pjjp / ZDI-CAN-26486  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8520[#8520]_
-- Error in `iTransaction.getInfo()` on embedded connection  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8509[#8509]_
-- "Error creating private namespace" message in _firebird.log_  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8477[#8477]_
-- Inheritance of `WINDOW` does not work  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8449[#8449]_
-- Races when server is closed during forced database shutdown  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8440[#8440]_
-- Wrong result for `MINVALUE/MAXVALUE` with string arguments  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8431[#8431]_
-- Make sure only one error will be sent to not-started service  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8430[#8430]_
-- Unstable error messages in services with trace enabled  

_Implemented by Artyom Abakumov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8417[#8417]_
-- Negative statement ID in trace output  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8389[#8389]_
-- Unnecessary reload of the encryption plugin in the _SuperServer_ architecture  

_Implemented by Alexey Mochalov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8350[#8350]_
-- Missing records inside a replicated database  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8336[#8336]_
-- Error: "Invalid clumplet buffer structure: buffer end before end of clumplet - clumplet too long (77779)" when using trusted auth  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/pull/8324[#8324]_
-- Make asynchronous replica re-initialization reliable  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8304[#8304]_
-- Wrong results using `MINVALUE/MAXVALUE` in join condition  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8283[#8283]_
-- Assert in `~thread_db()` due to not released page buffer  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/pull/8268[#8268]_
-- Fix refetch header data from delta when database in backup lock  

_Implemented by Andrey Kravchenko_

'''

_https://github.com/FirebirdSQL/firebird/pull/8255[#8255]_
-- Catch possible stack overflow when preparing and compiling user statements  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8253[#8253]_
-- Incorrect handling of non-ASCII object names in `CREATE MAPPING` statement  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/pull/8243[#8243]_
-- Fix a bug where the shutdown handler could be called again  

_Implemented by Alexander Zhdanov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8238[#8238]_
-- Fix using macro with regex in path parameter in fbtrace.conf  

_Implemented by Alexander Peshkov, Artyom Ivanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8237[#8237]_
-- Database access error when nbackup is starting  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8236[#8236]_
-- Avoid "hangs" in clock_gettime() in tomcrypt's PRNG  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8222[#8222]_
-- Fix a case of deleted memory modification  

_Implemented by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/8219[#8219]_
-- Database creation in 3.0.12, 4.0.5 and 5.0.1 is slower than in previous releases  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/pull/8069[#8069]_
-- Add missing synchronization to cached vectors of known pages  

_Implemented by Dmitry Yemanov, Vlad Khorsun_

'''

[[bug-406-crashes]]
=== Server Crashes/Hang-ups

_https://github.com/FirebirdSQL/firebird/issues/8485[#8485]_
-- Segfault on incorrect _databases.conf_ starting with sub-config (without line `alias=database_path`)  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8437[#8437]_
-- Segfault when running query with `PARTITION BY` and subquery  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8429[#8429]_
-- Segfault when already destroyed callback interface is used  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8403[#8403]_
-- Fix potential deadlock when starting the encryption thread  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8221[#8221]_
-- Crash when `MAKE_DBKEY()` is called with 0 or 1 arguments  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8215[#8215]_
-- Rare sporadic segfaults in test for core-6142 on Windows  

_Implemented by Alexander Peshkov_

'''


[[bug-405]]
== Firebird 4.0.5 Release: Bug Fixes

[[bug-405-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/8189[#8189]_
-- Slow connection times with a lot of simultaneous connections and active trace session present  

_Implemented by Alexander Peshkov, Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8180[#8180]_
-- Sometimes a system trace session is terminated spontaneously  

_Implemented by Artyom Abakumov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8178[#8178]_
-- Fix boolean conversion to string inside `DataTypeUtil::makeFromList()`  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8171[#8171]_
-- Trace plugin unloaded if called method is not implemented  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8156[#8156]_
-- Can not specify concrete IPv6 address in ES/EDS connection string  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8150[#8150]_
-- Process could attach to the deleted instance of shared memory  

_Implemented by Alexander Peshkov, Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8138[#8138]_
-- Bugcheck when replicator state is changed concurrently  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8120[#8120]_
-- `CAST` dies with numeric value is out of range error

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8108[#8108]_
-- ICU 63.1 suppresses conversion errors  

_Implemented by Dmitry Kovalenko_

'''

_https://github.com/FirebirdSQL/firebird/issues/8085[#8085]_
-- Memory leak when executing a lot of different queries and `StatementTimeout > 0`  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8077[#8077]_
-- Error "Too many recursion levels" does not stop execution of code that uses `ON DISCONNECT` trigger  

_Implemented by Alexander Peshkov, Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8058[#8058]_
-- Replicated DDL changes do not set the correct grantor  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8056[#8056]_
-- Error "Too many temporary blobs" with `BLOB_APPEND` when selecting a stored procedure with rows-clause

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8040[#8040]_
-- Bugcheck 183 (wrong record length) could happen on replica database after UK violation on insert   

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8027[#8027]_
-- Broken _gbak_ statistics  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8011[#8011]_
-- `DECFLOAT` error working with `INT128` in UDR

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8006[#8006]_
-- `INT128` datatype not supported in `FB_MESSAGE` macro   

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7997[#7997]_
-- Unexpected results when comparing integer with string containing value out of range of that integer datatype  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7993[#7993]_
-- Unexpected results when using `CASE WHEN` with `RIGHT JOIN`  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7969[#7969]_
-- Characters are garbled when replicating fields with type `BLOB SUB_TYPE TEXT` if the character set of the connection and the field are different  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7950[#7950]_
-- Unable to restore database when .fbk was created on host with other _ICU_  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7927[#7927]_
-- Some default values are set incorrectly for SC/CS architectures

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7899[#7899]_
-- Inconsistent state of master-detail occurs after reconnect + 'SET AUTODDL OFF' + 'drop <FK>' which is rolled back

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7896[#7896]_
-- _replication.log_ remains empty (and without any error in firebird.log) until concurrent FB instance is running under different account and generates segments on its master. Significant delay required after stopping concurrent FB to allow first one to write in its replication log.

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7885[#7885]_
-- Unstable error messages in services due to races related with service status vector  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7873[#7873]_
-- Wrong memory buffer alignment and I/O buffer size when working in direct I/O mode  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7867[#7867]_
-- Error "wrong page type" during garbage collection on v4.0.4  

_Implemented by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/7839[#7839]_
-- Potential bug in `BETWEEN` operator  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7831[#7831]_
-- Incorrect type of UDF-argument with array  

_Implemented by Dmitry Kovalenko_

'''

_https://github.com/FirebirdSQL/firebird/issues/7827[#7827]_
-- Problem using Python _firebird-driver_ with either Intel or M1 Mac builds with version 4.0.3 or 5.0+  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7461[#7461]_
-- Differences in field metadata descriptions between Firebird 2.5 and Firebird 4  

_Implemented by Dmitry Yemanov_

'''

[[bug-405-crashes]]
=== Server Crashes/Hang-ups

_https://github.com/FirebirdSQL/firebird/issues/8151[#8151]_
-- Deadlock happens when running 'List Trace Sessions' service and there are many active trace sessions

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8149[#8149]_
-- A hang or crash could happen when connection fires _TRACE_EVENT_DETACH_ event and a new trace session is created concurrently

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8114[#8114]_
-- Segfault in connection pool during server shutdown

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8110[#8110]_
-- Firebird 5 crash on Android API level 34

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8101[#8101]_
-- Firebird crashes if a plugin factory returns nullptr and no error in status  

_Implemented by Vlad Khorsun, Dimitry Sibiryakov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8089[#8089]_
-- AV when attaching database while low on free memory

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8083[#8083]_
-- AV when writing to internal trace log

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8079[#8079]_
-- Engine could crash when executing some trigger(s) while another attachment modifies them  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8039[#8039]_
-- Segfault when opening damaged (last TIP is missing in `RDB$PAGES`, user's FW was OFF) database  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7985[#7985]_
-- Hang in case of error when sweep thread is attaching to database (_Classic Server_)

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7979[#7979]_
-- Hang when database with disconnect trigger using `MON$` tables is shutting down  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7917[#7917]_
-- Hang in case of error when sweep thread is attaching to database  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7905[#7905]_
-- Segfault during TPC initialization  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7860[#7860]_
-- Crash potentially caused by `BETWEEN` operator  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7851[#7851]_
-- The skip of `att_functionarg_field_precision` does not check `RESTORE_format`  

_Implemented by Dmitry Kovalenko_

'''

_https://github.com/FirebirdSQL/firebird/issues/7809[#7809]_
-- Crash "Fatal lock manager error: Process disappeared in LockManager::acquire_shmem"  

_Implemented by Alexander Peshkov_

'''

[[bug-405-utilities]]
=== Utilities

[[bug-405-utilities-gbak]]
==== gbak

_https://github.com/FirebirdSQL/firebird/issues/8003[#8003]_
-- _gbak_ v4 can't backup database in _ODS < 13_  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7869[#7869]_
-- _gbak_ can write uninitialized data into `RDB$RETURN_ARGUMENT` and `RDB$ARGUMENT_POSITION` fields  

_Implemented by Dmitry Kovalenko_

'''

_https://github.com/FirebirdSQL/firebird/issues/7846[#7846]_
-- FB4 can't backup/restore `INT128`-array  

_Implemented by Dmitry Kovalenko_

'''

_https://github.com/FirebirdSQL/firebird/issues/7800[#7800]_
-- Default publication status is not preserved after backup/restore  

_Implemented by Dmitry Yemanov_

'''

[[bug-405-utilities-isql]]
==== isql

_https://github.com/FirebirdSQL/firebird/issues/7844[#7844]_
-- Removing first column with `SET WIDTH` crashes _isql_  

_Implemented by Adriano dos Santos Fernandes_

'''


[[bug-404]]
== Firebird 4.0.4 Release: Bug Fixes

[[bug-404-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/7817[#7817]_
-- Memory leak is possible for UDF array arguments  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7812[#7812]_
-- Service backup does not work in multiple engines configuration  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7772[#7772]_
-- Blob corruption in FB4.0.3 (embedded)  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7759[#7759]_
-- Routine calling overhead increased by factor 6 vs Firebird 4.0.0  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/pull/7747[#7747]_
-- Fix an issue where the garbage collection in indexes and blobs is not performed in _VIO_backout_  

_Implemented by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/7745[#7745]_
-- Error restoring database which has system domains in user table with BLOBs using embedded connection  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/pull/7737[#7737]_
-- Fix cases where the precedence relationship between a record page and a blob page is not set  

_Implemented by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/7731[#7731]_
-- Display length of timestamp with timezone is wrong in dialect 1  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7730[#7730]_
-- Server ignores the size of `VARCHAR` when performing `SET BIND ... TO VARCHAR(N)`  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7729[#7729]_
-- `SET BIND OF TS WITH TZ TO VARCHAR(128)` uses the date format of dialect 1  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7727[#7727]_
-- Index for integer column cannot be used when `INT128`/`DECFLOAT` value is being searched

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7713[#7713]_
-- `FOR SELECT` statement can not see any changes made inside the `DO` block  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7691[#7691]_
-- `WITH CALLER PRIVILEGES` has no effect in triggers   

_Implemented by Alexander Peshkov_

'''

[[bug-404-crashes]]
=== Server Crashes/Hang-ups

_https://github.com/FirebirdSQL/firebird/issues/7779[#7779]_
-- Firebird 4.0.3 is constantly crashing with the same symptoms (fbclient.dll)  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7762[#7762]_
-- Crash on "Operating system call pthread_mutex_destroy failed. Error code 16" in log  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7738[#7738]_
-- Crash on multiple connections/disconnections  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7480[#7480]_
-- Firebird server stops accepting new connections after some time  

_Implemented by Alexander Peshkov_

'''

[[bug-404-api]]
=== API/Remote Interface

_https://github.com/FirebirdSQL/firebird/issues/7723[#7723]_
-- Wrong error message on login if the user doesn't exist and _WireCrypt_ is disabled  

_Implemented by Alexander Peshkov_

'''

[[bug-404-installs]]
=== Installation Issues

_https://github.com/FirebirdSQL/firebird/issues/7766[#7766]_
-- Firebird 4 Windows Installer omits DLLs during custom installation mode

_Implemented by Paul Reeves_

'''

[[bug-404-utilities]]
=== Utilities

[[bug-404-utilities-gbak]]
==== gbak

_https://github.com/FirebirdSQL/firebird/issues/7770[#7770]_
-- Restore takes 25% more time vs 4.0.0  

_Implemented by Vlad Khorsun_

'''

[[bug-404-utilities-isql]]
==== isql

_https://github.com/FirebirdSQL/firebird/issues/7761[#7761]_
-- Regression when displaying line number of errors in _ISQL_ scripts  

_Implemented by Adriano dos Santos Fernandes_

'''


[[bug-403]]
== Firebird 4.0.3 Release: Bug Fixes

[[bug-403-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/7683[#7683]_
-- `rdb$time_zone_util.transitions` returns an infinite result set  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7670[#7670]_
-- Cursor name can duplicate parameter and variable names in procedures and functions  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7665[#7665]_
-- Wrong result ordering in `LEFT JOIN` query  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7664[#7664]_
-- `DROP TABLE` executed for a table with big records may lead to "wrong page type" or "end of file" error  

_Implemented by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/pull/7662[#7662]_
-- Peformance issues in prepare_update()  

_Implemented by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/7661[#7661]_
-- FB3 CS rejects new connections  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7651[#7651]_
-- Unable to find savepoint in insert with nested query and returning clause in FB4  

_Implemented by Dmitry Yemanov_

'''


_https://github.com/FirebirdSQL/firebird/issues/7638[#7638]_
-- `OVERRIDING USER VALUE` should be allowed for `GENERATED ALWAYS AS IDENTITY`  

_Implemented by Adriano dos Santos Fernandes_

'''


_https://github.com/FirebirdSQL/firebird/issues/7627[#7627]_
-- The size of the database with big records becomes bigger after backup/restore  

_Implemented by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/7605[#7605]_
-- Disallow replication of `RDB$BACKUP_HISTORY`  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7604[#7604]_
-- PSQL functions do not convert the output BLOB to the connection character set  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7603[#7603]_
-- `BIN_SHR` on `INT128` does not apply sign extension  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7599[#7599]_
-- Conversion of text with '\0' to `DECFLOAT` without errors  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7591[#7591]_
-- `RELEASE SAVEPOINT ONLY` works incorrectly  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7579[#7579]_
-- Cannot _nbackup_ a Firebird 3.0 database in Firebird 4.0 service with _engine12_ setup in _Providers_  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7555[#7555]_
-- Invalid configuration for random fresh created database may be used after drop of another one with alias in _databases.conf_  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7548[#7548]_
-- `SET BIND OF TIMESTAMP WITH TIME ZONE TO CHAR` is not working with UTF8 connection charset  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7537[#7537]_
-- Wrong name in error message when unknown namespace is passed into `RDB$SET_CONTEXT`  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7535[#7535]_
-- High CPU usage connect to Firebird 3 database using Firebird 4 Classic and SuperClassic service  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7517[#7517]_
-- Successful compiling of procedure with wrong PLAN(s) used by some of its statement(s)  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7501[#7501]_
-- Precision of a standalone unit may differ from a packaged one in SQL dialect 1  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7499[#7499]_
-- Problem with restore (error: index cannot be used in the specified plan)  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7488[#7488]_
-- Invalid real to string cast  

_Implemented by Artyom Abakumov, Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7484[#7484]_
-- External engine `SYSTEM` not found  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7482[#7482]_
-- Result of `blob_append(null, null) (literal '<null>')` is not shown  

_Implemented by Vlad Khorsun, Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7456[#7456]_
-- Impossible drop function in package with name of PSQL-function  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7415[#7415]_
-- _DbCrypt/KeyHolder_ plugins key changing issues on running server  

_Implemented by Alexey Mochalov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7398[#7398]_
-- Worst plan sort created to execute an indexed tables  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7387[#7387]_
-- Unreliable replication behaviour in Linux Classic  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7380[#7380]_
-- Aliased blob variable with less restrictions makes text blob accept malformed string through `BLOB_APPEND`  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7379[#7379]_
-- `BLOB_APPEND` with existing blob accepts malformed string  

_Implemented by Vlad Khorsun, Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7371[#7371]_
-- Various errors (fatal lock manager error, pthread_mutex_destroy failed) caused by races when opening/closing database  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7361[#7361]_
-- Broken compacting of trace config storage  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7359[#7359]_
-- Querying to list the running trace sessions can fail if two service API calls was done before it for a short time (Linux specifics)  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7357[#7357]_
-- Lock manager error when connect a Firebird 3.0 database more than once using SuperClassic Firebird 4.0 service  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7349[#7349]_
-- Contradictory licensing/distribution statements in several charset-support files  

_Implemented by Mark Rotteveel_

'''

_https://github.com/FirebirdSQL/firebird/issues/7298[#7298]_
-- Unreliable info result parsing  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7256[#7256]_
-- Inconsistent conversion of non-TEXT blobs in `BLOB_APPEND`  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7255[#7255]_
-- `READ COMMITTED READ CONSISTENCY` mode is broken in Classic / SuperClassic on Linux  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/pull/7233[#7233]_
-- Slow database restore when Classic server mode is used  

_Implemented by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/6941[#6941]_
-- Dummy (always true) conditions may change the join order  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/4729[#4729]_
-- `GRANT` and `REVOKE UPDATE` (field)  

_Implemented by Alex Peshkoff_

'''

[[bug-403-crashes]]
=== Server Crashes/Hang-ups

_https://github.com/FirebirdSQL/firebird/issues/7626[#7626]_
-- Segfault when new attachment is done to shutting down database  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7556[#7556]_
-- FB Classic can hang attempting to attach DB while it is starting to encrypt/decrypt  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7514[#7514]_
-- Segfault when detaching after deleting shadow on Classic  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7510[#7510]_
-- Firebird regularly crashes soon after unload of _udr_engine_ plugin  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7472[#7472]_
-- Window functions may lead to crash interacting with others exceptions  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7467[#7467]_
-- Simple SQL crashes Firebird: `select cast(rdb$db_key as integer) from rdb$database`  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7446[#7446]_
-- Attempt to use data in destroyed transaction pool  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7402[#7402]_
-- Server crashes on startup error  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7393[#7393]_
-- Access violation after double fault in _attachDatabase()_  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7370[#7370]_
-- Segfault under OOM conditions  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7314[#7314]_
-- Multitreaded activating indices restarts server process  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7276[#7276]_
-- Firebird 4 literal with `CONTAINING` crashes server  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7271[#7271]_
-- Sporadic server crash  

_Implemented by Vlad Khorsun_

'''

[[bug-403-api]]
=== API/Remote Interface

_https://github.com/FirebirdSQL/firebird/issues/7473[#7473]_
-- Client application crash when processing callback requests from server during _attachDatabase_  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7444[#7444]_
-- _isql_ crashes while executing test from QA suite  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7365[#7365]_
-- Client side aliases do not work in _databases.conf_  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7296[#7296]_
-- During shutdown _op_disconnect_ may be sent to invalid handle  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7262[#7262]_
-- Repeated _op_batch_create_ leaks the batch  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7239[#7239]_
-- Connect using XNET protocol shows different exception (comparing to INET) if database is in the shutdown state  

_Implemented by Vlad Khorsun_

'''

[[bug-403-builds]]
=== Build Issues

_https://github.com/FirebirdSQL/firebird/issues/7582[#7582]_
-- Missing _isc_info_end_ in _Firebird.pas_  

_Implemented by Alex Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7369[#7369]_
-- Build fails against _re2_ 20220601  

_Implemented by Adriano dos Santos Fernandes_

'''

[[bug-403-installs]]
=== Installation Issues

_https://github.com/FirebirdSQL/firebird/issues/7283[#7283]_
-- Suspicious error message during install  

_Implemented by Alex Peshkoff_

'''

[[bug-403-maconly]]
=== MacOS Only

_https://github.com/FirebirdSQL/firebird/issues/7241[#7241]_
-- MacOS installer - firebird user is not created correctly if group already exists  

_Implemented by Jonathan Frutos_

'''

[[bug-403-utilities]]
=== Utilities

[[bug-403-utilities-gbak]]
==== gbak

_https://github.com/FirebirdSQL/firebird/issues/7611[#7611]_
-- Can't backup/restore database from v3 to v4 with `SEC$USER_NAME` field longer than 10 characters  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7610[#7610]_
-- Uninitialized/random value assigned to `RDB$ROLES.RDB$SYSTEM PRIVILEGES` when restoring from FB3 backup  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7465[#7465]_
-- Restore success illegally reported when _gbak_ was unable to activate all indices  

_Implemented by Alex Peshkoff_

'''

[[bug-403-utilities-fbtracemgr]]
==== fbtracemgr

_https://github.com/FirebirdSQL/firebird/issues/7295[#7295]_
-- Unexpected message 'Error reading data from the connection' when _fbtracemgr_ is closed using Ctrl-C  

_Implemented by Alex Peshkoff_

'''


[[bug-402]]
== Firebird 4.0.2 Release: Bug Fixes

[[bug-402-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/7243[#7243]_
-- Some _UNICODE_ characters can lead to wrong `CONTAINING` evaluation when lower/upper uses different number of bytes in its encoding.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7229[#7229]_
-- `ALTER COLUMN DROP IDENTITY` does not reset generator name in metadata cache.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7222[#7222]_
-- Dependencies of packaged functions are not tracked.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/pull/7217[#7217]_
-- It's not allowed to execute DROP PACKAGE BODY for a package with a procedure even if a user has DROP ANY PACKAGE privilege.  

_Implemented by I. Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/7179[#7179]_
-- Wrong error message - "string right truncation. expected length 30, actual 30."  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7178[#7178]_
-- DEFAULTed grants to PUBLIC must act as DEFAULTed to every user.  

_Implemented by R. Simakov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7176[#7176]_
-- Incorrect error "Invalid token. Malformed string." with UNION + blob + non-UTF8 varchar.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7167[#7167]_
-- Incorrect transliteration of field names in constraint violation errors.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7160[#7160]_
-- Missing checkout in the trace manager when performing user mapping may cause server hang.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7150[#7150]_
-- Replication not restarting after network failure.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7147[#7147]_
-- Problems with use of big timeout (or no timeout at all) in the trace service.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7141[#7141]_
-- Services manager breaks long lines into 1023 bytes portions when using _isc_info_svc_line_ in _Service::query()_.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7140[#7140]_
-- Wrong select result in case of special sort character.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7139[#7139]_
-- With multiple trace sessions user may receive trace events related to engine's requests.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7138[#7138]_
-- Problems accessing FB4 database, copied from another host.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7135[#7135]_
-- Firebird engine randomly fails when delivering mapping clear signal to other processes.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7134[#7134]_
-- Database page errors directly after _GBAK_, dissappearing after some calls of _GFIX_.  

_Implemented by V. Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7129[#7129]_
-- Cannot alter SQL SECURITY on package.  

_Implemented by A. Mochalov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7124[#7124]_
-- Inconsistent _RDB$USER_PRIVILEGES_ after dropping identity.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7122[#7122]_
-- Invalid state of mapping cache after replacement of database.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7121[#7121]_
-- Mapping error when server tries to use mapping rules from database in full shutdown mode.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7119[#7119]_
-- Database statistics service could not find existing table(s).  

_Implemented by V. Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7118[#7118]_
-- Chained `JOIN .. USING` across the same column names may be optimized badly.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7108[#7108]_
-- Firebird does not find an record when adding a foreign key.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7106[#7106]_
-- Wrong detection of must-be-delimited user names.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7094[#7094]_
-- Incorrect indexed lookup of strings when the last keys characters are part of collated contractions and there is multi-segment insensitive descending index.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7090[#7090]_
-- Performance degradation with `CURRENT_DATE`, `LOCALTIME` and `LOCALTIMESTAMP`.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7084[#7084]_
-- Creating unique constraints on MacOS fails on larger tables.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/4085[#4085]_
-- _RDB$INDICES_ information stored inconsistently after a `CREATE INDEX`.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/3357[#3357]_
-- Bad execution plan if some stream depends on multiple streams via a function.  

_Implemented by D. Yemanov_

'''

[[bug-402-crashes]]
=== Server Crashes/Hang-ups

_https://github.com/FirebirdSQL/firebird/issues/7200[#7200]_
-- `DROP DATABASE` leads to hang if it is issued while database encrypting/decrypting is in progress.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7199[#7199]_
-- Various errors (strange messages in firebird.log, segfaults) with high rate of attach/detach database operations.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7103[#7103]_
-- FB service hangs after several `DELETE FROM MON$STATEMENTS` being issued in order to stop ES/EDS which waits record for updating.  

_Implemented by V. Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7080[#7080]_
-- Executing batch crashes the server.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/6947[#6947]_
-- Query to MON$ tables does not return data when database encryption/decryption is in progress.  

_Implemented by A. Peshkoff_

'''

[[bug-402-api]]
=== API/Remote Interface

_https://github.com/FirebirdSQL/firebird/issues/7188[#7188]_
-- Memory leak in _fbclient_ when a multi-database transaction is used.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7128[#7128]_
-- Incorrect error message with _isc_sql_interprete()_.  

_Implemented by V. Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7099[#7099]_
-- Incomplete _op_batch_cs_ response with _TAG_MULTIERROR_.  

_Implemented by A. Peshkoff_

'''

[[bug-402-winonly]]
=== Windows Only

_https://github.com/FirebirdSQL/firebird/issues/7202[#7202]_
-- _ISQL -ch utf8_ (Windows only): either silently quits to OS or issues non-expected 'malformed string' when non-ASCII character occurs in the typed command.  

_Implemented by A. dos Santos Fernandes_

'''

[[bug-402-linonly]]
=== Linux Only

_https://github.com/FirebirdSQL/firebird/issues/7197[#7197]_
-- Segfault in Linux CS after successful detach from database.  

_Implemented by A. Peshkoff_

'''

[[bug-402-maconly]]
=== MacOS Only

_https://github.com/FirebirdSQL/firebird/issues/7112[#7112]_
-- Avoid unload of plugins in MacOS due to problematic reload of them.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/pull/7088[#7088]_
-- MacOS UDR and Legacy_UserManager plugins not working due to not exported entry point.  

_Implemented by A. dos Santos Fernandes_

'''

[[bug-402-utilities]]
=== Utilities

[[bug-402-utilities-gbak]]
==== gbak

_https://github.com/FirebirdSQL/firebird/issues/7204[#7204]_
-- Segfault in _GBAK_ when restoring a broken backup file over the wire.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7184[#7184]_
-- _GBAK_ output is not being flushed to disk.  

_Implemented by A. Peshkoff_

'''

[[bug-402-utilities-gstat]]
==== gstat

_https://github.com/FirebirdSQL/firebird/issues/7194[#7194]_
-- _GSTAT_ fails but returns 0 as error code if incorrect _databases.conf_ is used.  

_Implemented by A. Mochalov_

'''

[[bug-402-utilities-isql]]
==== isql

_https://github.com/FirebirdSQL/firebird/issues/7123[#7123]_
-- ISQL does not extract `INCREMENT BY` for IDENTITY column.  

_Implemented by A. dos Santos Fernandes_

'''

[[bug-402-installs]]
=== Installation Issues

_https://github.com/FirebirdSQL/firebird/issues/7113[#7113]_
-- Wrong path in Object Pascal's readme.md.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7096[#7096]_
-- Client install on Windows is missing some files  

_Implemented by P. Reeves_

'''

[[bug-401]]
== Firebird 4.0.1 Release: Bug Fixes

[[bug-401-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/7070[#7070]_
-- Error _"BLOB is not found"_ while replication converts `INSERT` into `UPDATE` for a conflicting record.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7064[#7064]_
-- Linear regression functions aren't implemented correctly.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7062[#7062]_
-- Creation of expression index does not release its statement correctly.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7057[#7057]_
-- Client-side positioned updates work wrongly with scrollable cursors.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7056[#7056]_
-- Fetching from a scrollable cursor may overwrite user-specified buffer and corrupt memory.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7052[#7052]_
-- Races between transactions on the primary side may cause update conflicts while applying journals to the replica.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7048[#7048]_
-- Incorrect releasing of user savepoint (older savepoints become inaccessible).  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7043[#7043]_
-- Wrong message when user has no access to _/tmp/firebird_.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7033[#7033]_
-- Replicator is missing sanity checks for user-supplied blocks.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6998[#6998]_
-- Problems with access to `RDB$CONFIG` table for non-privileged user when he has grant on execution of stored procedure which has necessary access rights (created by `SYSDBA` with `SQL DEFINER` clause).  

_Implemented by R. Simakov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6995[#6995]_
-- _"String truncation error"_ is raised while restoring the database from a v2.5 backup.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6989[#6989]_
-- Invalid message in _replication.log_ (and possibly crash in the case of synchronous replication) when the target DB has no "replica" flag set.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6976[#6976]_
-- Lack of proper clean up after failure to initialize shared memory.  

_Implemented by V. Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/6963[#6963]_
-- The `REFERENCES` permission does not work.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/6955[#6955]_
-- `fb_info_creation_timestamp_tz` returns a corrupted buffer.  

_Implemented by V. Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/6935[#6935]_
-- `SQL SECURITY DEFINER` has inconsistent behaviour if the object owner is non-privileged.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6935[#6935]_
-- `SQL SECURITY DEFINER` does not affect the ownership of created DDL objects.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6907[#6907]_
-- Failed DDL commands can be replicated.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6900[#6900]_
-- _IBatch::add()_ method fails silently when a memory limit is exceeded.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/6893[#6893]_
-- Problem with replication of BLOB segments longer than 32KB.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6887[#6887]_
-- Invalid `SIMILAR TO` patterns may lead memory read beyond string limits.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6886[#6886]_
-- Differerent interfaces behaviour depending upon source of interface.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/6887[#6887]_
-- Significant performance regression of `SIMILAR TO` and `SUBSTRING(SIMILAR)` when pattern is taken from a variable.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6874[#6874]_
-- Literal 65536 (interpreted as int) cannot be multiplied by itself without cast if result is more than 2^63-1.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/6860[#6860]_
-- Create user statement fails with _SQLSTATE = HY000_ when using _DataTypeCompatibility_ setting.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/6856[#6856]_
-- Permission error after replication of DDL commands.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6853[#6853]_
-- Asynchronous replication leaks file handles.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6850[#6850]_
-- Database-level and DDL triggers are executed at the replica side.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6849[#6849]_
-- Conflicting `INSERT propagated` into a read-write replica may cause duplicate records to appear (and PK/UK violation to happen).  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6848[#6848]_
-- Generator values may not replicate after commit.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6845[#6845]_
-- Result type of `AVG` over `BIGINT` column results in type `INT128`.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/6838[#6838]_
-- Deleting multiple rows from a view with triggers may cause triggers to fire just once.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6801[#6801]_
-- Error recompiling a package with some combination of nested functions.  

_Implemented by A. dos Santos Fernandes_

'''

[[bug-401-crashes]]
=== Server Crashes/Hang-ups

_https://github.com/FirebirdSQL/firebird/issues/7067[#7067]_
-- Deadlock when using not initialized security database.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7060[#7060]_
-- Deadlock when execute test for _CORE-4337_.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7034[#7034]_
-- Server crashes while fetching from a scrollable cursor in PSQL.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7018[#7018]_
-- Crashes or incorrect results for some windows frames.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7015[#7015]_
-- Replication applier code may crash if the specified block contains no savepoint operations.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6985[#6985]_
-- Application could hang when using new Batch API with blobs over XNET.  

_Implemented by V. Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/6975[#6975]_
-- Crash or hang while shutting down the replica database if segments are being applied.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6945[#6945]_
-- Segfault in the batch interface when _gbak_ restores a database with many blobs over the wire.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/6930[#6930]_
-- Segfault when calling cryptographic functions.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/6913[#6913]_
-- Buffer overflows in _getInfo()_ APIs.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6909[#6909]_
-- Some updates may crash Firebird server on the replica side.  

_Implemented by D. Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6832[#6832]_
-- Segfault when using `COMMIT RETAINING` with Global Temporary Tables.  

_Implemented by A. Peshkoff_

'''

[[bug-401-api]]
=== API/Remote Interface

_https://github.com/FirebirdSQL/firebird/issues/7068[#7068]_
-- Errors in the _ChaCha_ plugin are displayed incorrectly.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7066[#7066]_
-- Server may send incorrect specific data to client when establishing encrypted connection.  

_Implemented by A. Peshkoff_

'''

_https://github.com/FirebirdSQL/firebird/issues/7065[#7065]_
-- Connection hangs after delivery of 256GB of data.  

_Implemented by A. Peshkoff_

'''

[[bug-401-winonly]]
=== Windows Only

_https://github.com/FirebirdSQL/firebird/issues/6968[#6968]_
-- On Windows, engine may hang when works with corrupted database and read after the end of file.  

_Implemented by V. Khorsun_

'''

[[bug-401-linonly]]
=== Linux Only

_https://github.com/FirebirdSQL/firebird/issues/6966[#6966]_
-- Status vector for ES(<EMPTY_STRING>) is unstable if another execute block with correct statement was executed before. Affects only Linux builds in Classic mode.  

_Implemented by A. Peshkoff_

'''

[[bug-401-builds]]
=== Builds

_https://github.com/FirebirdSQL/firebird/issues/7037[#7037]_
-- Build problem when using both _--with-builtin-tommath_ and _--with-builtin-tomcrypt_.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6978[#6978]_
-- Firebird 4 fails to build on big-endian platforms.  

_Implemented by A. Peshkoff_

'''

[[bug-401-installs]]
=== Installation Issues

_https://github.com/FirebirdSQL/firebird/issues/6979[#6979]_
-- Windows x64 server installer installs an incomplete x86 client. 

_Implemented by P. Reeves_

'''

_https://github.com/FirebirdSQL/firebird/issues/6943[#6943]_
-- Windows client install is missing some DLLs. 

_Implemented by P. Reeves_

'''

_https://github.com/FirebirdSQL/firebird/issues/6917[#6917]_
-- Firebird 4 installer asks for SYSDBA password when doing client installation.  

_Implemented by P. Reeves_

'''

[[bug-400]]
== Firebird 4.0 Release: Bug Fixes

The following bug-fixes since the Release Candidate 1 are noted:

[[bug-400-core]]
=== Core Engine

_(https://github.com/FirebirdSQL/firebird/issues/6816[#6816])_
-- Illegal output length in `BASE64/HEX` `ENCODE/DECODE` functions.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6812[#6812])_
-- `BASE64_ENCODE` and `HEX_ENCODE` can exceed the maximum length for `VARCHAR`.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6805[#6805])_
-- `RDB$TYPES` has incorrect entries for `RDB$TYPE` 28 and 29 in `RDB$TYPE_NAME` column.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6804[#6804])_
-- Assertion in tomcrypt when the key length for _RC4_ is too small.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6800[#6800])_
-- Client config setting _DefaultTimeZone_ is not passed to server when _isc_dpb_session_time_zone_ is not set.

_fixed by A. dos Santos Fernandes_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6797[#6797])_
-- Functions `DECRYPT` and `RSA_DECRYPT` return `VARCHAR CHARACTER SET NONE` instead of `VARBINARY (VARCHAR CHARACTER SET OCTETS)`.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6795[#6795])_
-- Replication gets stuck due to _"Blob xxx.xx is not found for table xxx"_ error.

_fixed by D. Yemanov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6790[#6790])_
-- `MON$ATTACHMENTS.MON$TIMESTAMP` is incorrect when _DefaultTimeZone_ is configured with time zone different from the server's default.

_fixed by A. dos Santos Fernandes_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6787[#6787])_
-- `MON$ATTACHMENTS.MON$TIMESTAMP` should use its session original time zone.

_fixed by A. dos Santos Fernandes_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6785[#6785])_
-- Problem when restoring the database on Firebird 4 RC1.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6782[#6782])_
-- Cannot get "records fetched" for selectable procedures in trace.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6778[#6778])_
-- Inconsistent cursor-driven deletion.

_fixed by D. Yemanov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6768[#6768])_
-- Cannot restore backup on a raw device (_error during "open O_CREAT" operation for file "/dev/sda1"_).

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6761[#6761])_
-- Hash join cannot match records using some `TIME ZONE` / `DECFLOAT` keys.

_fixed by D. Yemanov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6759[#6759])_
-- Results of concatenation with blob has no info about collation of source columns (which are declared with such info).

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6758[#6758])_
-- `COMPUTED BY` column looses charset and collate of source field <F> when <F> is either of type `BLOB` or `VARCHAR` casted to `BLOB`.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6756[#6756])_
-- Error _"no current record for fetch operation"_ when sorting by an international string.

_fixed by D. Yemanov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6750[#6750])_
-- `CAST` of Infinity values to `FLOAT` doesn't work.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6749[#6749])_
-- Error _"Invalid time zone (+08). Falling back to displacement"_ in firebird.log.

_fixed by A. dos Santos Fernandes_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6747[#6747])_
-- Wrong message when connecting to tiny trash database file.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6746[#6746])_
-- Regression: CREATE DATABASE fails with 'Token unknown' error when DB name is enclosed in double quotes and 'DEFAULT CHARACTER SET' is specified after DB name.

_fixed by A. dos Santos Fernandes_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6734[#6734])_
-- Provide same results for date arithmetics when date is changed by values near +/-max(bigint).

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6733[#6733])_
-- Attempt to create database with page_size >= 65536 makes DB with actual page size = _4KB_ or _8KB_, but not _32KB_ as it should.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6727[#6727])_
-- Synchronous replication to localhost hangs on disconnect.

_fixed by D. Yemanov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6724[#6724])_
-- Inconsistent translation _"string->timestamp->string->timestamp"_ in Dialect 1.

_fixed by A. dos Santos Fernandes_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6719[#6719])_
-- User without `ALTER ANY ROLE` privilege can use `COMMENT ON ROLE`.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6717[#6717])_
-- `FETCH ABSOLUTE` and `RELATIVE` beyond bounds of cursor should always position immediately before-first or after-last.

_fixed by D. Yemanov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6716[#6716])_
-- `FETCH RELATIVE` has an off by one error for the first row.

_fixed by D. Yemanov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6710[#6710])_
-- `COMMENT ON USER` can only apply comment on user defined by the default user manager plugin.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6700[#6700])_
-- Wire compression causes sporadic _"Error reading data from the connection"_ errors.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6698[#6698])_
-- Comments before the first line of code are removed.

_fixed by A. dos Santos Fernandes_

'''

_(https://github.com/FirebirdSQL/firebird/issues/3810[#3810])_
-- Wrong or missing `IS NULL` optimization.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/3106[#3106])_
-- Many indexed reads in a compound index with NULLs.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/2469[#2469])_
-- Stored procedure recursively called by calculated field fails after reconnect.

_fixed by V. Khorsun_

'''

[[bug-400-crashes]]
=== Server Crashes/Hang-ups

_(https://github.com/FirebirdSQL/firebird/issues/6808[#6808])_
-- Segfault in `ENCRYPT/DECRYPT` functions when their first argument is _NULL_.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6781[#6781])_
-- Crashing (due to UDF exception) process hangs.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6777[#6777])_
-- AV when the engine shuts down and cancels an attachment waiting in the lock manager.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6766[#6766])_
-- Replication plugin can crash the engine by returning _nullptr_ from _startTransaction()_ method.

_fixed by D. Yemanov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6754[#6754])_
-- Connect to database that contains broken pages can lead to a server crash.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6753[#6753])_
-- AV in the engine when _StatementTimeout_ is active for user statement and some internal DSQL statement was executed as part of overall execution process.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6752[#6752])_
-- Segfaults in _fbclient_ when receiving invalid / unexpected data from the server.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6751[#6751])_
-- Various segfaults in _fbclient_.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6738[#6738])_
-- Segfault when _GFIX_ requests for database page buffer more memory than available from OS.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6731[#6731])_
-- Segfault when shutting down database which got encrypted by another process.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6708[#6708])_
-- Rare race condition in Plugin Manager could lead to the server crash.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6265[#6265])_
-- Segfault when using expression index with complex expression.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/5784[#5784])_
-- When 32-bit and 64-bit Firebird 3 servers run on a single Windows machine concurrently, Firebird services freeze several minutes after first disconnect.

_fixed by V. Khorsun_

'''

[[bug-400-api]]
=== API/Remote Interface

_(https://github.com/FirebirdSQL/firebird/issues/6718[#6718])_
-- Event delivery could be missed when local (XNET) protocol is used.

_fixed by V. Khorsun_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6679[#6679])_
-- _CLOOP_ envelopes are wrong regarding IStatus.

_fixed by A. Peshkov_

'''

[[bug-400-builds]]
=== Build Issues

_(https://github.com/FirebirdSQL/firebird/issues/6780[#6780])_
-- firebird.msg is missing in Firebird Android builds.

_fixed by A. Peshkov_

'''

_(https://github.com/FirebirdSQL/firebird/issues/6745[#6745])_
-- Protect included tomcrypt library from being overwritten by a system package.

_fixed by A. Peshkov_

'''

[[bug-400-utilities]]
=== Utilities

[[bug-400-utilities-isql]]
==== isql

_(https://github.com/FirebirdSQL/firebird/issues/6796[#6796])_
-- Buffer overflow when padding line with national characters causes _ISQL_ to crash.

_fixed by A. dos Santos Fernandes_

'''

[[bug-400-utilities-gbak]]
==== gbak

_(https://github.com/FirebirdSQL/firebird/issues/6709[#6709])_
-- _GBAK_ discards replica mode during backup/restore.

_fixed by D. Yemanov_

'''

[[bug-400-utilities-gstat]]
==== gstat

_(https://github.com/FirebirdSQL/firebird/issues/6729[#6729])_
-- Regression: _GSTAT_ with switch -t executed via services fails with _"found unknown switch"_ error.

_fixed by A. Peshkov_

'''

[[bug-400rc1]]
== Firebird 4.0 Release Candidate 1: Bug Fixes

The following bug-fixes since the Beta 2 release are noted:

[[bug-400rc1-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-6475[CORE-6475])_
-- Memory leak when running EXECUTE STATEMENT with named parameters.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6472[CORE-6472])_
-- Wrong byte order for UUIDs reported by _GSTAT_ and monitoring tables.

_fixed by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6460[CORE-6460])_
-- Incorrect query result when using named window.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6453[CORE-6453])_
-- `EXECUTE STATEMENT` fails on FB 4.x if containing time/timestamp with time zone parameters.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6447[CORE-6447])_
-- Unexpectedly different text of message for parameterized expression starting from second run.
Same fix was backported to Firebird 3.0.8.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6441[CORE-6441])_
-- Srp plugin keeps connection after database has been removed for ~10 seconds.
Same fix was backported to Firebird 3.0.8.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6440[CORE-6440])_
-- Expression indexes containing `COALESCE` inside cannot be matched by the optimizer after migration from v2.5 to v3.0.
Same fix was backported to Firebird 3.0.8.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6437[CORE-6437])_
-- GFIX cannot set big value for page buffers.
Same fix was backported to Firebird 3.0.8.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6427[CORE-6427])_
-- Whitespace as date separator causes conversion error.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6421[CORE-6421])_
-- Parameter in offset expression in `LAG, LEAD, NTH_VALUE` window functions requires explicit cast to `BIGINT` or `INTEGER`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6419[CORE-6419])_
-- Truncation of strings to put in MON$ tables do not work correctly.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6415[CORE-6415])_
-- Error "malformed string' is raised instead of "expected: N, actual: M" when UTF-8 charset is used and default value is longer than the column length.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6414[CORE-6414])_
-- Error "expected length N, actual M" contains wrong value of M when UTF-8 charset is used in the field declaration.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6408[CORE-6408])_
-- `RETURNING` clause in the `MERGE` statement cannot reference column in aliased target table using qualified reference (alias.column) if `DELETE` action present.
Same fix was backported to Firebird 3.0.8.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6403[CORE-6403])_
-- Some PSQL statements may lead to exceptions report wrong line/column.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6398[CORE-6398])_
-- Error converting string with hex representation of `INTEGER` to `SMALLINT`.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6397[CORE-6397])_
-- Message length error with `COALESCE` and `TIME / TIMESTAMP WITHOUT TIME ZONE` and `WITH TIME ZONE`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6389[CORE-6389])_
-- Using binary string literal to assign to user-defined blob sub-types yield conversion error.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6386[CORE-6386])_
-- `ALTER SEQUENCE RESTART WITH <n>` should not change the initial sequence `START` value.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6385[CORE-6385])_
-- Wrong line and column information after IF statement.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6379[CORE-6379])_
-- Bugcheck 179 (decompression overran buffer).

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6376[CORE-6376])_
-- `IDENTITY` column with explicit `START WITH` or `INCREMENT BY` starts with wrong value.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6357[CORE-6357])_
-- `LEAD()` and `LAG()` do not allow to specify 3rd argument of `INT128` datatype.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6356[CORE-6356])_
-- `ROUND()` does not allow second argument >=1 when its first argument is more than MAX_BIGINT / 10.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6355[CORE-6355])_
-- `TRUNC()` does not accept second argument = -128 (but shows it as required boundary in error message).

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6353[CORE-6353])_
-- `INT128` data type has problems with some PSQL objects.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6344[CORE-6344])_
-- Invalid return type for functions with `INT128 / NUMERIC(38)` argument.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6337[CORE-6337])_
-- Sub-type information is lost when calculating arithmetic expressions.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6336[CORE-6336])_
-- Error "Implementation of text subtype <NNNN> not located" on attempt to use some collations defined in fbintl.conf.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6335[CORE-6335])_
-- `INSERT ... RETURNING` does not require a SELECT privilege.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6328[CORE-6328])_
-- FB4 Beta 2 may still be using the current date for `TIME WITH TIME ZONE` and extended wire protocol.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6325[CORE-6325])_
-- `NTILE/RANK/PERCENT_RANK` may cause problems in big/complex statements.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6318[CORE-6318])_
-- `CAST('NOW' as TIME)` raises a conversion error.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6316[CORE-6316])_
-- Unable to specify new 32KB page size in `CREATE DATABASE` statement.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6303[CORE-6303])_
-- Error writing to `TIMESTAMP / TIME WITH TIME ZONE` array.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6302[CORE-6302])_
-- Error writing an array of `NUMERIC(24,6)` to the database.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6084[CORE-6084])_
-- `CREATE SEQUENCE START WITH` has wrong initial value.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6023[CORE-6023])_
-- FB4 is unable to overwrite older ODS database.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5838[CORE-5838])_
-- Rotated trace files are locked by the engine.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4985[CORE-4985])_
-- A non-privileged user could implicitly count records in a restricted table.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2274[CORE-2274])_
-- `MERGE` has a non-standard behaviour, accepts multiple matches.
See also <<rnfb40-compat-merge>>.

_fixed by V. Khorsun_

'''

[[bug-400rc1-crashes]]
=== Server Crashes/Hang-ups

_(http://tracker.firebirdsql.org/browse/CORE-6450[CORE-6450])_
-- Races in the security databases cache could lead to the server crash.
Same fix was backported to Firebird 3.0.8.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6433[CORE-6433])_
-- Server could crash during a daily maintenance / set statistics index.
Same fix was backported to Firebird 3.0.8.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6412[CORE-6412])_
-- Firebird was freezing when trying to manage users via triggers.
Same fix was backported to Firebird 3.0.8.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6387[CORE-6387])_
-- Client process was aborting due to bugs inside the ChaCha plugin.

_fixed by A. Peshkov_

'''

[[bug-400rc1-api]]
=== API/Remote Interface

_(http://tracker.firebirdsql.org/browse/CORE-6432[CORE-6432])_
-- Possible buffer overflow in client library in `Attachment::getInfo()` call.
Same fix was backported to Firebird 3.0.8.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6426[CORE-6426])_
-- Assertion when the batch is executed without a BLOB field.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6425[CORE-6425])_
-- Exception in client library in `IAttachment::createBatch()`.

_fixed by A. Peshkov_

'''

[[bug-400rc1-builds]]
=== Build Issues

_(http://tracker.firebirdsql.org/browse/CORE-6305[CORE-6305])_
-- Android port build failure.

_fixed by A. Peshkov_

'''

[[bug-400rc1-utilities]]
=== Utilities

[[bug-400rc1-utilities-isql]]
==== isql

_(http://tracker.firebirdsql.org/browse/CORE-6438[CORE-6438])_
-- Bad headers when text columns has >= 80 characters.

_fixed by A. dos Santos Fernandes_

'''

[[bug-400rc1-utilities-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-6377[CORE-6377])_
-- Unable to restore database with tables using `GENERATED ALWAYS AS IDENTITY` columns.

_fixed by A. Peshkov_

'''

[[bug-400b2]]
== Firebird 4.0 Beta 2 Release: Bug Fixes

The following bug-fixes since the Beta 1 release are noted:

[[bug-400b2-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-6290[CORE-6290])_
-- Hex number used at the end of statement could read invalid memory and produce wrong values or exceptions.
Same fix was backported to Firebird 3.0.6.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6282[CORE-6282])_
-- Data type of `MON$ATTACHMENTS.MON$IDLE_TIMER` and `MON$STATEMENTS.MON$STATEMENT_TIMER` was defined as `TIMESTAMP WITHOUT TIME ZONE`, now it's changed to `TIMESTAMP WITH TIME ZONE`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6281[CORE-6281])_
-- Invalid timestamp errors could happen when working with the `RDB$TIME_ZONE_UTIL.TRANSITIONS` procedure.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6280[CORE-6280])_
-- MERGE statement could lose parameters in the "```WHEN [NOT] MATCHED```" clause that will never be matched.
This could also cause server crashes in some situations.
Same fix was backported to Firebird 3.0.6.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6272[CORE-6272])_
-- Failed attach to a database was not traced.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6266[CORE-6266])_
-- Deleting records from `MON$ATTACHMENTS` using the `ORDER BY` clause didn't close the corresponding attachments.
Same fix was backported to Firebird 3.0.6.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6251[CORE-6251])_
-- `UNIQUE CONSTRAINT` violation could be possible.
Same fix was backported to Firebird 3.0.6.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6250[CORE-6250])_
-- Signature mismatch error could be raised when creating package body on identical packaged procedure header.
Same fix was backported to Firebird 3.0.6.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6248[CORE-6248])_
-- A number of errors could happen when database name is longer than 255 characters.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6243[CORE-6243])_
-- v4 Beta 1 regression happened: the engine rejects `POSITION` element of the SQL:2003 `CREATE TRIGGER` syntax.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6241[CORE-6241])_
-- Values greater than number of days between 01.01.0001 and 31.12.9999 (=3652058) could be added or subtracted from `DATE`.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6238[CORE-6238])_
-- `DECFLOAT`: subtraction ("```Num1 - Num2```") would lead to the "`Decimal float overflow`" error if `Num2` is specified in scientific notation and is less than max double (1.7976931348623157e308).

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6236[CORE-6236])_
-- `RDB$TIME_ZONE_UTIL` package had wrong privilege defined for `PUBLIC`.

_fixed by A. dos Santos Fernandes, D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6230[CORE-6230])_
-- It was impossible to connect to a database if `security.db` reference was removed from `databases.conf`.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6221[CORE-6221])_
-- Incorrect implementation of `allocFunc()` for zlib1: memory leak was possible.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6214[CORE-6214])_
-- tzdata database version was outdated and required an update.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6206[CORE-6206])_
-- `VARCHAR` of insufficient length was used for command `SET BIND OF DECFLOAT TO VARCHAR`.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6205[CORE-6205])_
-- Improper error was raised for `UNION DISTINCT` with more than 255 columns.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6186[CORE-6186])_
-- Original contents of the column used with `ENCRYPT()` looked as distorted after this call.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6181[CORE-6181])_
-- Usage of "```SET DECFLOAT BIND BIGINT,n```" with result of 11+ digits, would fail with the "`Decimal float invalid operation`" error.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6166[CORE-6166])_
-- Some problems could appear for long object names (> 255 bytes).

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6160[CORE-6160])_
-- `SUBSTRING` of non-text/-blob was described to return `NONE` character set in DSQL.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6159[CORE-6159])_
-- `SUBSTRING` SIMILAR was described with wrong data type in DSQL.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6110[CORE-6110])_
-- 64-bit transaction IDs were not stored properly inside the status vector.

_fixed by I. Eremin_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6080[CORE-6080])_
-- Attempt to drop an existing user could randomly fail with error "`336723990 : record not found for user`".

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6046[CORE-6046])_
-- Incorrect time zone parsing could read garbage in memory.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6034[CORE-6034])_
-- The original time zone was not set to the current time zone at the routine invocation.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6033[CORE-6033])_
-- `SUBSTRING(CURRENT_TIMESTAMP ...)` would fail with a "`string truncation`" error.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5957[CORE-5957])_
-- Adding a numeric quantifier as a bound for repetition of expression inside `SIMILAR TO` could lead to an empty resultset.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5931[CORE-5931])_
-- `SIMILAR TO` did not return the result when an invalid pattern was used.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5892[CORE-5892])_
-- SQL SECURITY _DEFINER_ context was not properly evaluated for monitoring tables.

_fixed by R. Simakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5697[CORE-5697])_
-- Conversion from numeric literals to `DECFLOAT` would add the precision that is not originally present.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5696[CORE-5696])_
-- Conversion from zero numeric literals to `DECFLOAT` would lead to the incorrect result.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5664[CORE-5664])_
-- `SIMILAR TO` was substantially (500-700x) slower than `LIKE` on trivial pattern matches with `VARCHAR` data.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4874[CORE-4874])_
-- Server could perform a `SIMILAR TO` matching infinitely.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4739[CORE-4739])_
-- Accent insensitive comparison: diacritical letters with diagonal crossing stroke failed for non-equality conditions with their non-accented forms.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3858[CORE-3858])_
-- Very poor performance of `SIMILAR TO` for some arguments.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-3380[CORE-3380])_
-- It was possible to read from the newly created BLOB.
It's prohibited now.

_fixed by A. dos Santos Fernandes_

'''

[[bug-400b2-crashes]]
=== Server Crashes/Hang-ups

_(http://tracker.firebirdsql.org/browse/CORE-6254[CORE-6254])_
-- Server could crash when using `SET TRANSACTION` and `ON TRANSACTION START` trigger uses `EXECUTE STATEMENT` against current transaction.
Same fix was backported to Firebird 3.0.6.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6253[CORE-6253])_
-- Locked fb_lock file could cause a server crash.
Same fix was backported to Firebird 3.0.6.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6251[CORE-6251])_
-- Server would crash when built-in function `LEFT` or `RIGHT` is missing its 2nd argument.
Same fix was backported to Firebird 3.0.6.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6231[CORE-6231])_
-- Server would crash during shutdown of XNET connection to a local database when events have been registered.
Same fix was backported to Firebird 3.0.6.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6224[CORE-6224])_
-- Server could crash due to double destruction of the rem_port object.
Same fix was backported to Firebird 3.0.6.

_fixed by D. Kovalenko, A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6218[CORE-6218])_
-- `COUNT(DISTINCT DECFLOAT_FIELD)` could cause the server to crash when there are duplicate values in this field.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6217[CORE-6217])_
-- Dangerous (possibly leading to a crash) work with pointer: `delete ptr; ptr=new ;`.

_fixed by D. Kovalenko, A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5972[CORE-5972])_
-- External engine trigger would crash the server if the table has computed fields.
Same fix was backported to Firebird 3.0.6.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4893[CORE-4893])_
-- `SIMILAR TO` would cause a server crash when matching a blob with size >2GB to a string literal.

_fixed by A. dos Santos Fernandes_

'''

[[bug-400b2-api]]
=== API/Remote Interface

_(http://tracker.firebirdsql.org/browse/CORE-6283[CORE-6283])_
-- Result of `isNullable()` in message metadata, returned by metadata builder, did not match datatype set by `setType()` in metadata builder.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6227[CORE-6227])_
-- `isc_info_svc_user_dbpath` was always returning an alias of the main security database.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6212[CORE-6212])_
-- Authentication plugin on the server could read garbage data from the client instead of the empty packet.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6207[CORE-6207])_
-- It was impossible to compile Firebird.pas with FPC.

_fixed by A. Peshkov_

'''

[[bug-400b2-builds]]
=== Build Issues

_(http://tracker.firebirdsql.org/browse/CORE-6174[CORE-6174])_
-- `ibase.h` was missing from the nightly builds.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6170[CORE-6170])_
-- Installation on CentOS 8 failed because of the mismatched version of LibTomMath and LibNCurses libraries.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6061[CORE-6061])_
-- It was impossible to build the server with the `--with-builtin-tommath` option.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6056[CORE-6056])_
-- Overflow warnings appeared when building some collations.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6019[CORE-6019])_
-- Wire compression did not work without the MSVC 2010 runtime package installed.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5691[CORE-5691])_
-- File description of the Firebird executables was not specific.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5445[CORE-5445])_
-- Installation failed on Debian Stretch/Testing due to incorrect version of the LibTomMath library.

_fixed by A. Peshkov_

'''

[[bug-400b2-utilities]]
=== Utilities

[[bug-400b2-utilities-isql]]
==== isql

_(http://tracker.firebirdsql.org/browse/CORE-6262[CORE-6262])_
-- `SHOW DOMAIN/TABLE` did not display the character set of system objects.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6260[CORE-6260])_
-- Warnings were not always displayed in ISQL.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6211[CORE-6211])_
-- Command "```isql -X```" could not extract the `ROLE` name when using a multi-byte charset for the connection.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6116[CORE-6116])_
-- Metadata script extracted with ISQL from a database restored from a v2.5 backup was invalid if some table has `COMPUTED BY` fields.
Same fix was backported to Firebird 3.0.6.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6044[CORE-6044])_
-- Some issues were noticed due to the increased SQL identifier length.

_fixed by A. dos Santos Fernandes_

'''

[[bug-400b2-utilities-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-6265[CORE-6265])_
-- Existing mapping rules were removed by the backup/restore cycle.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6233[CORE-6233])_
-- Wrong dependencies of stored function on view were created after backup/restore.
Same fix was backported to Firebird 3.0.6.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6208[CORE-6208])_
-- `CREATE DATABASE` permission would disappear from security database after the backup/restore cycle.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6130[CORE-6130])_
-- Creating backup to `STDOUT` using the service manager was broken.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-6071[CORE-6071])_
-- Restoring an encrypted backup of a SQL dialect 1 database would fail.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5976[CORE-5976])_
-- GBAK multi-database file restore used wrong minimum number of pages for the first database file.

_fixed by M. Rotteveel_

'''

_(http://tracker.firebirdsql.org/browse/CORE-2251[CORE-2251])_
-- GBAK doesn't return the error code in some cases.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

[[bug-400b2-utilities-gfix]]
==== gfix

_(http://tracker.firebirdsql.org/browse/CORE-5364[CORE-5364])_
-- `gfix -online normal` did not raise an error when there was another SYSDBA-owned session open.
Same fix was backported to Firebird 3.0.6.

_fixed by A. Peshkov_

'''

[[bug-400b1]]
== Firebird 4.0 Beta 1 Release: Bug Fixes

The following bug-fixes since the Alpha release are noted:

[[bug-400b1-core]]
=== Core Engine

_(http://tracker.firebirdsql.org/browse/CORE-5986[CORE-5986])_
-- Evaluation of `NULL IS [NOT] FALSE | TRUE` was incorrect.
Same fix was backported to Firebird 3.0.5.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5985[CORE-5985])_
-- Regression: `ROLE` was not being passed to ES/EDS: specifying it in the statement was ignored.
Same fix was backported to Firebird 3.0.5.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5982[CORE-5982])_
-- An error involving read permission for a BLOB field was being thrown when the BLOB was an input or output parameter for a procedure.
Same fix was backported to Firebird 3.0.5.

_fixed by D. Starodubov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5974[CORE-5974])_
-- `SELECT DISTINCT` with a decfloat/timezone/collated column was producing wrong results.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5973[CORE-5973])_
-- Improvement: Fixed-point overflow in a `DOUBLE PRECISION` value converted from `DECFLOAT` is now handled properly.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5965[CORE-5965])_
-- The optimizer was choosing a less efficient plan in FB4 and FB3 than the FB2.5 optimizer.
Same fix was backported to Firebird 3.0.5.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5959[CORE-5959])_
-- Firebird would return the wrong time after a change of time zone.
Same fix was backported to Firebird 3.0.5.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5950[CORE-5950])_
-- Deadlock could occur when attaching to a bugchecked database.
Same fix was backported to Firebird 3.0.5.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5949[CORE-5949])_
-- Bugcheck could happen when a read-only  database with non-zero linger was set to read-write mode.
Same fix was backported to  Firebird 3.0.5.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5935[CORE-5935])_
-- Bugcheck 165 (cannot find TIP page). Same fix was backported to Firebird 3.0.5.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5930[CORE-5930])_
-- Bugcheck with message "`incorrect snapshot deallocation - too few slots`".

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5918[CORE-5918])_
-- Memory pool statistics were inaccurate.
Same fix was backported to Firebird 3.0.5.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5896[CORE-5896])_
-- A `NOT NULL` constraint was not being synchronized after the column was renamed.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5785[CORE-5785])_
-- An `ORDER BY` clause on a compound index could disable usage of other indices.
Same fix was backported to Firebird 3.0.5.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5871[CORE-5871])_
-- Incorrect caching of the result of a subquery result in a procedure call from a `SELECT` query.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5862[CORE-5862])_
-- `RDB$CHARACTER_LENGTH` in `RDB$FIELDS` was not being populated when the column was a computed `VARCHAR` without an explicit type.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5750[CORE-5750])_
-- Date-time parsing needed strengthening.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5728[CORE-5728])_
-- The field subtype of DEC_FIXED columns was not returned by `isc_info_sql_sub_type`.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5726[CORE-5726])_
-- The error message when inserting a value exceeding the maximum value of DEC_FIXED decimal was unclear.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5717[CORE-5717])_
-- The literal date/time prefix syntax (`DATE`, `TIME` or `TIMESTAMP` prefix before the quoted value) used together with the implicit date/time literal expressions (`'NOW'`, `'TODAY'`, etc.) was known to evaluate those expressions in ways that would produce unexpected results, often undetected.
This behaviour was considered undesirable -- the Firebird 4.0 engine and above will now reject them everywhere.

For details, see <<rnfb40-compat-sql-prefixed-literals,Prefixed Implicit Date/Time Literals Now Rejected>> in the Compatibility chapter.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5710[CORE-5710])_
-- Data type declaration `DECFLOAT` without precision should be using a default precision.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5700[CORE-5700])_
-- `DECFLOAT` underflow should yield zero instead of an error.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5699[CORE-5699])_
-- `DECFLOAT` should not throw exceptions when +/-NaN,  +/-sNaN and +/-Infinity is used in comparisons.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5646[CORE-5646])_
-- A parse error when compiling a statement would cause a memory leak until the attachment was disconnected.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5612[CORE-5612])_
-- View operations (create, recreate or drop) were exhibiting gradual slow-down.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5611[CORE-5611])_
-- Memory consumption for prepared statements was higher.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5593[CORE-5593], http://tracker.firebirdsql.org/browse/CORE-5518[CORE-5518])_
-- The system function `RDB$ROLE_IN_USE` could not take long role names.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5480[CORE-5480])_
-- A `SUBSTRING` start position smaller than 1 should be allowed.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-1592[CORE-1592])_
-- Altering procedure parameters could lead to an unrestorable database.

_fixed by A. dos Santos Fernandes_

'''

[[bug-400b1-crashes]]
=== Server Crashes/Hang-ups

_(http://tracker.firebirdsql.org/browse/CORE-5980[CORE-5980])_
-- Firebird would crash due to concurrent operations with expression indices.
Same fix was backported to Firebird 3.0.5.

_fixed by V. Khorsun_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5972[CORE-5972])_
-- External engine trigger could crash the server if the table had a computed field.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5943[CORE-5943])_
-- The server could crash while preparing a query with both `DISTINCT`/`ORDER BY` and a non-field expression in the select list.
Same fix was  backported to Firebird 3.0.5.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5936[CORE-5936])_
-- The server could segfault at the end of a database backup.

_fixed by V. Khorsun_

'''

[[bug-400b1-security]]
=== Security

_(http://tracker.firebirdsql.org/browse/CORE-5927[CORE-5927])_
-- With some non-standard authentication plugins, traffic would remain unencrypted despite providing the correct crypt key.
Same fix was backported to Firebird 3.0.5.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5926[CORE-5926])_
-- An attempt to create a mapping with a non-ASCII user name that was encoded in a *single-byte* codepage (e.g. `WIN1251`) would lead to a "`Malformed string`" error.
Same fix was backported to Firebird 3.0.5.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5861[CORE-5861])_
-- New objects and some old objects in a database could not be granted the `GRANT OPTION` via role privileges.

_fixed by R. Simakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5657[CORE-5657])_
-- Attended to various UDF-related security vulnerabilities, resulting in aggressive deprecation of support for the use of UDFs as external functions.
See also <<rnfb40-engine-deprecated-udfs,External Functions (UDFs) Feature Deprecated>> in the the chapter <<rnfb40-engine,Changes to the Firebird Engine>> and <<rnfb40-compat-udfs,Deprecation of External Functions (UDFs)>> in the <<rnfb40-compat,Compatibility>> chapter.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5639[CORE-5639])_
-- Mapping rule using WIN_SSPI plugin: Windows user group conversion to Firebird role was not working.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5518[CORE-5518])_
-- Firebird UDF `string2blob()` could allow remote code execution.

_fixed by A. Peshkov_

'''

[[bug-400b1-utilities]]
=== Utilities

[[bug-400b1-utilities-gbak]]
==== gbak

_(http://tracker.firebirdsql.org/browse/CORE-5855[CORE-5855])_
-- A database with generators containing space characters in their names could not be backed up.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5800[CORE-5800])_
-- After backup/restore, expression indexes on computed fields would not work properly.
Same fix was backported to Firebird 3.0.5.

_fixed by D. Yemanov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5637[CORE-5637])_
-- A string right truncation error was occurring on restore of the security database.

_fixed by A. Peshkov_

'''

[[bug-400b1-utilities-gpre]]
==== gpre

_(http://tracker.firebirdsql.org/browse/CORE-5934[CORE-5834])_
-- `gpre_boot` was failing to link using `cmake`, giving undefined reference 'dladdr' and 'dlerror'.
Same fix was backported to Firebird 3.0.5.

_fixed by A. Peshkov_

'''

[[bug-400b1-utilities-trace]]
==== trace

_(http://tracker.firebirdsql.org/browse/CORE-5907[CORE-5907])_
-- Regression: Trace could not be launched if its 'database' section contained a regular expression pattern with curvy brackets to enclose a quantifier.
Same fix was backported to Firebird 3.0.5.

_fixed by A. Peshkov_

'''

[[bug-400b1-builds]]
=== Build Issues

_(http://tracker.firebirdsql.org/browse/CORE-5989[CORE-5989])_
-- Some build issues involving iconv / libiconv 1.15 vs libc / libiconv_open | common/isc_file.cpp.
Same fix was backported to Firebird 3.0.5.

_fixed by A. Peshkov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5955[CORE-5955])_
-- Static linking problem with ld >= 2.31.
Same fix was backported to Firebird 3.0.5.

_fixed by R. Simakov_

'''

[[bug-400a1]]
== Firebird 4.0 Alpha 1 Release: Bug Fixes

The following fixes to pre-existent bugs are noted:

[[fb4a1-trigger-fix]]
_(http://tracker.firebirdsql.org/browse/CORE-5545[CORE-5545])_
-- Using the `POSITION` parameter with the `[RE]CREATE TRIGGER` syntax would cause an "`unknown token`" error if `POSITION` was written in the logically correct place, i.e. after the main clauses of the statement.
For example, the following should work because `POSITION` comes after the other specifications:

[source]
----
RECREATE TRIGGER T1
BEFORE INSERT
ON tbl
POSITION 1 AS
BEGIN
  --
END
----

However, it would exhibit the error, while the following would succeed:

[source]
----
RECREATE TRIGGER T1
BEFORE INSERT
POSITION 1
ON tbl
AS
BEGIN
  --
END
----

The fix makes the first example correct, and the second should throw the error.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5454[CORE-5454])_
-- Inserting into an updatable view without an explicit column list would fail.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5408[CORE-5408])_
-- The result of a Boolean expression could not be concatenated with a string literal.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5404[CORE-5404])_
-- Inconsistent column and line references were being returned in error messages for faulty PSQL definitions.

_fixed by A. dos Santos Fernandes_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5237[CORE-5237])_
-- Processing of the `include` clause in configuration files was mishandling dot ('```.```') and asterisk ('```{asterisk}```') characters in the file name and path of the included file.

_fixed by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5223[CORE-5223])_
-- Double dots in file names for databases were prohibited if the `DatabaseAccess` configuration parameter was set to restrict access to a list of directories.

_fixed by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-5141[CORE-5141])_
-- Field definition would allow multiple `NOT NULL` clauses.
For example, 

[source]
----
create table t (a integer not null not null not null)
----

The fix makes the behaviour consistent with `CREATE DOMAIN` behaviour, and the example will return the error "`Duplicate specification of NOT NULL - not supported`".

_fixed by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4701[CORE-4701])_
-- Garbage collection for indexes and BLOBs was not taking data in the Undo log into account.

_fixed by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4483[CORE-4483])_
-- In PSQL, data changed by executing a procedure was not visible to the `WHEN` handler if the exception occurred in the called procedure.

_fixed by D. Sibiryakov_

'''

_(http://tracker.firebirdsql.org/browse/CORE-4424[CORE-4424])_
-- In PSQL, execution flow would roll back to the wrong savepoint if multiple exception handlers were executed at the same level.

_fixed by D. Sibiryakov_

'''
