[[rnfb40-general]]
= General Notes

Thank you for choosing Firebird 4.0.
We cordially invite you to test it hard against your expectations and engage with us in identifying and fixing any bugs you might encounter.

ODS 13 is introduced and it's a major ODS upgrade, so older databases cannot be opened with a Firebird 4 server.
The engine library is named `engine13.dll` (Windows) and `libEngine13.so` (POSIX).
The security database is named `security4.fdb`.
Binaries layout and configuration are unchanged from Firebird 3.

[NOTE]
====
That said, you can copy the Firebird engine library from the Firebird 3.0 distribution package (named `engine12.dll` (Windows) and `libEngine12.so` (POSIX), and located inside the `/plugins` sub-directory) to continue working with databases in ODS12 without needing a backup/restore.
However, new features introduced with Firebird 4.0 will not be accessible.
====

Known incompatibilities are detailed in the <<rnfb40-compat,Compatibility Issues>> chapter.

[[rnfb40-general-v402]]
== Sub-release V.4.0.2

Bugs reported and fixed prior to the version 4.0.2 release are listed <<bug-402,HERE>>.

[[rnfb40-general-improvements-v402]]
=== V.4.0.2 Improvements

_https://github.com/FirebirdSQL/firebird/pull/6983[#6983]_
-- New built-in function _<<rnfb40-dml-new-blob-append, BLOB_APPEND>>_  

_Implemented by V. Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7208[#7208]_
-- Trace: provide performance statistics for DDL statement.  

_Implemented by V. Khorsun_

'''
  
_https://github.com/FirebirdSQL/firebird/issues/7194[#7194]_
-- Make it possible to avoid _fbclient_ dependency in Pascal programs using _firebird.pas_.  

_Implemented by A. Peshkov_

'''
  
_https://github.com/FirebirdSQL/firebird/issues/7168[#7168]_
-- Ignore missing UDR libraries during restore.  

_Implemented by A. dos Santos Fernandes_

'''
  
_https://github.com/FirebirdSQL/firebird/issues/7161[#7161]_
-- Update _zlib_ to version 1.2.12.  

_Implemented by V. Khorsun_

'''
  
_https://github.com/FirebirdSQL/firebird/issues/7093[#7093]_
-- Improve indexed lookup speed of strings when the last keys characters are part of collated contractions.  

_Implemented by A. dos Santos Fernandes_

'''
  
_https://github.com/FirebirdSQL/firebird/issues/7092[#7092]_
-- Improve performance of `CURRENT_TIME`.  

_Implemented by A. dos Santos Fernandes_

'''
  
_https://github.com/FirebirdSQL/firebird/issues/7042[#7042]_
-- `ON DISCONNECT` triggers are not executed during forced attachment shutdown.  

_Implemented by I. Eremin_

'''
  
_https://github.com/FirebirdSQL/firebird/issues/7041[#7041]_
-- Firebird port for Apple M1 architecture.  

_Implemented by J. Frutos, A. Peshkoff, A. dos Santos Fernandes_

'''
  
_https://github.com/FirebirdSQL/firebird/issues/7038[#7038]_
-- Improve performance of `STARTING WITH` with insensitive collations.  

_Implemented by A. dos Santos Fernandes_

'''
  
_https://github.com/FirebirdSQL/firebird/issues/6730[#6730]_
-- Trace: provide ability to see `STATEMENT RESTART` events (or their count).  
  
_Implemented by V. Khorsun_

'''

[[rnfb40-general-v401]]
== Sub-release V.4.0.1

Bugs reported and fixed prior to the version 4.0.1 release are listed <<bug-401,HERE>>.

[[rnfb40-general-improvements-v401]]
=== V.4.0.1 Improvements

_https://github.com/FirebirdSQL/firebird/issues/6910[#6910]_
-- Add way to retrieve statement BLR with _Statement::getInfo()_ and ISQL's `SET EXEC_PATH_DISPLAY BLR`.  


_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6959[#6959]_
-- Add _getInfo()_ method to the _Batch_ interface in the API.  

_Implemented by A. Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6954[#6954]_
-- Add `fb_info_protocol_version` information request to _Attachment::getInfo()_.  

_Implemented by A. Peshkov_

'''


_https://github.com/FirebirdSQL/firebird/issues/6929[#6929]_
-- Add support of PKCS v.1.5 padding to RSA functions, needed for backward compatibility with old systems.  

_Implemented by A. Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6915[#6915]_
-- Allow attribute `DISABLE-COMPRESSIONS` in UNICODE collations.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6903[#6903]_
-- Make it possible to create ICU-based collations with locales keywords.  

_Implemented by tkeinz, A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6872[#6872]_
-- Faster indexed `STARTING WITH` execution with UNICODE collations.  

_Implemented by A. dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6810[#6810]_
-- Use precise limit of salt length when signing messages and verifying the sign.  

_Implemented by A. Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6809[#6809]_
-- Integer hex-literal support for `INT128`.  

_Implemented by A. Peshkov_

'''

[[rnfb40-general-bugreport]]
== Bug Reporting

Bugs fixed since the release of version 4.0.0 are listed and described in the chapter entitled <<rnfb40-bug,Bugs Fixed>>.

* If you think you have discovered a new bug in this release, please make a point of reading the instructions for bug reporting in the article https://www.firebirdsql.org/en/how-to-report-bugs/[How to Report Bugs Effectively], at the Firebird Project website.
* If you think a bug fix has not worked, or has caused a regression, please locate the original bug report in the Tracker, reopen it if necessary, and follow the instructions below.

Follow these guidelines as you attempt to analyse your bug:

. Write detailed bug reports, supplying the exact build number of your Firebird kit.
Also provide details of the OS platform.
Include reproducible test data in your report and post it to our https://github.com/FirebirdSQL/firebird/issues[Tracker].
. You are warmly encouraged to make yourself known as a field-tester of this beta by subscribing to the mailto:firebird-test-request@lists.sourceforge.net?subject=subscribe[field-testers' list] and posting the best possible bug description you can.
. If you want to start a discussion thread about a bug or an implementation, please do so by subscribing to the mailto:firebird-devel+subscribe@googlegroups.com[firebird-devel list].

[[rnfb40-general-docs]]
== Documentation

You will find all of the README documents referred to in these notes -- as well as many others not referred to -- in the doc sub-directory of your Firebird 4.0 installation.

__ -- The Firebird Project__