[[rnfb40-general]]
= General Notes

Thank you for reviewing this Firebird 4.0 Beta release.
We cordially invite you to test it hard against your expectations and engage with us in identifying and fixing any bugs you might encounter.

ODS13 is introduced and it's a major ODS upgrade, so older databases cannot be opened with a Firebird 4 server.
At this point in development, nothing more than a backup/restore is needed if you want to upgrade an existing database for your beta testing.
The engine library is named `engine13.dll` (Windows) and `libEngine13.so` (POSIX).
The security database is named `security4.fdb`.
Binaries layout and configuration are unchanged from Firebird 3.

[NOTE]
====
That said, you can copy the Firebird engine library from the Firebird 3.0 distribution package (named `engine12.dll` (Windows) and `libEngine12.so` (POSIX), and located inside the `/plugins` sub-directory) to continue working with databases in ODS12 without needing a backup/restore.
However, new features introduced with Firebird 4.0 will not be accessible.
====

Known incompatibilities are detailed in the <<rnfb40-compat,Compatibility Issues>> chapter.

[[rnfb40-general-bugreport]]
== Bug Reporting

Bugs fixed since Firebird 3.0.5 and Firebird 4.0 Beta 1 release are listed and described in the <<rnfb40-bug,Bugs Fixed>> chapter.

* If you think you have discovered a new bug in this release, please make a point of reading the instructions for bug reporting in the article http://www.firebirdsql.org/en/how-to-report-bugs/[How to Report Bugs Effectively], at the Firebird Project website.
* If you think a bug fix has not worked, or has caused a regression, please locate the original bug report in the Tracker, reopen it if necessary, and follow the instructions below.

Follow these guidelines as you attempt to analyse your bug:

. Write detailed bug reports, supplying the exact build number of your Firebird kit.
Also provide details of the OS platform.
Include reproducible test data in your report and post it to our http://tracker.firebirdsql.org[Tracker].
. You are warmly encouraged to make yourself known as a field-tester of this beta by subscribing to the link:mailto:firebird-test-request@lists.sourceforge.net?subject=subscribe[field-testers' list] and posting the best possible bug description you can.
. If you want to start a discussion thread about a bug or an implementation, please do so by subscribing to the link:mailto:firebird-devel-request@lists.sourceforge.net?subject=subscribe[firebird-devel list].
In that forum you might also see feedback about any tracker ticket you post regarding this Beta.

[[rnfb30-general-docs]]
== Documentation

You will find all of the README documents referred to in these notes -- as well as many others not referred to -- in the doc sub-directory of your Firebird 4.0 installation.

__ -- The Firebird Project__