:sectnums!:

[appendix]
[[rnfb40-licence]]
= Licence Notice

The contents of this Documentation are subject to the Public Documentation License Version 1.0 (the "`License`");
you may only use this Documentation if you comply with the terms of this Licence.
Copies of the Licence are available at https://www.firebirdsql.org/pdfmanual/pdl.pdf (PDF) and https://www.firebirdsql.org/manual/pdl.html (HTML).

The Original Documentation is entitled [ref]_Firebird 4.0 Release Notes_.

The Initial Writer of the Original Documentation is: Helen Borrie.
Persons named in attributions are Contributors.

Copyright (C) 2004-2020.
All Rights Reserved.
Initial Writer contact: helebor at users dot sourceforge dot net.

Contributor(s): Dmitry Yemanov, Mark Rotteveel.

Portions created by Dmitry Yemanov are Copyright (C) 2004-2024.
All Rights Reserved.
(Contributor contact(s): dimitr at users dot sourceforge dot net).

Portions created by Mark Rotteveel are Copyright (C) 2020-2024.
All Rights Reserved.
(Contributor contact(s): mrotteveel at users dot sourceforge dot net).

:sectnums: