[[rnfb40-new]]
= New In Firebird 4.0

[[rnfb40-new-sumry]]
== Summary of New Features

The following list summarises the features and changes, with links to the chapters and topics where more detailed information can be found.

[[rnfb40-new-complete]]
=== Complete In Firebird 4.0 Final Release

Renamed functions RSA_SIGN and RSA_VERIFY::
Functions priorly introduced as `RSA_SIGN` and `RSA_VERIFY` have been renamed to `RSA_SIGN_HASH` and `RSA_VERIFY_HASH` respectively.
+
Tracker ticket https://github.com/FirebirdSQL/firebird/issues/6806[#6806]

Session time zone is available via the system context::
The `SYSTEM` namespace of the built-in function `RDB$GET_CONTEXT` has been extended with the `SESSION_TIMEZONE` parameter that returns the time zone of the current session.
+
Tracker ticket https://github.com/FirebirdSQL/firebird/issues/6786[#6786]

More efficient implementation of SUBSTRING for UTF-8 character set::
Built-in function `SUBSTRING` has been improved to provide better performance when called with _UTF-8_ input strings.
+
Tracker ticket https://github.com/FirebirdSQL/firebird/issues/6769[#6769]

Allow replication plugins to refuse the current attachment::
The replication plugin API has been extended to allow the plugin to validate the attachment and return an error if it refuses to replicate its changes.
+
Tracker ticket https://github.com/FirebirdSQL/firebird/issues/6767[#6767]

Immediate execution of DSQL_drop and DSQL_unprepare commands::
Delayed execution of _DSQL_drop_ and _DSQL_unprepare_ options of the _dsql_free_statement()_ operation has been replaced with an immediate execution in order to release resource locks faster.
+
Tracker ticket https://github.com/FirebirdSQL/firebird/issues/6748[#6748]

Provide time zone ID constants in public headers::
Time zone IDs used by the Firebird engine have been made available in the header files of the public API.
+
Tracker ticket https://github.com/FirebirdSQL/firebird/issues/6715[#6715]

Make RDB$GET_TRANSACTION_CN working the same way in Super and Classic::
Built-in function `GET_TRANSACTION_CN` has been fixed to return the same result (proper commit number) for the given transaction number in all architectures. Priorly it might return _NULL_ in Classic Server.
+
Tracker ticket https://github.com/FirebirdSQL/firebird/issues/6253[#6253]

[[rnfb40-new-complete-in-rc1]]
=== Complete In Release Candidate 1

ALTER SESSION RESET statement::
New command to reset user session environment to its initial (default) state has been added.
+
For full details, see <<rnfb40-msql-alter-session-reset,ALTER SESSION RESET Statement>> in the <<rnfb40-msql,Management Statements>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-5832[CORE-5832]

New virtual table RDB$CONFIG::
This table exposes configuration settings actual for the current database.
+
For full details, see <<rnfb40-config-table,Virtual table RDB$CONFIG>> in the <<rnfb40-msql,Engine>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-3708[CORE-3708]

Report replica mode through isc_database_info, MON$DATABASE and SYSTEM context::
The replica state of the database (_none_ / _read-only_ / _read-write_) is now surfaced via the `MON$DATABASE` table and `Attachment::getInfo()` API call. It can also be read using the  context variable `REPLICA_MODE` of the `SYSTEM` namespace.
+
For full details, see <<rnfb40-util-mon,Monitoring>> in the <<rnfb40-util,Monitoring & Command-line Utilities>> chapter and <<rnfb40-apiods-api-info,Extensions to various getInfo() Methods>> in the <<rnfb40-apiods,Changes to the Firebird API and ODS>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6474[CORE-6474]

Tracing of session management statements::
The trace manager has been extended to report also the new category of session management statements, e.g. `ALTER SESSION RESET`.
+
[NOTE]
Trace plugin developers should be prepared to accept the NULL transaction inside the _ITracePlugin::trace_dsql_execute()_ method, similarly to how it should have been handled for the _trace_dsql_prepare()_ method of the same interface.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6469[CORE-6469]

Ability to retrieve next attachment ID and next statement ID::
Counters representing next attachment ID and next statement ID are now surfaced via the `MON$DATABASE` table and `Attachment::getInfo()` API call.
+
For full details, see <<rnfb40-util-mon,Monitoring>> in the <<rnfb40-util,Monitoring & Command-line Utilities>> chapter and <<rnfb40-apiods-api-info,Extensions to various getInfo() Methods>> in the <<rnfb40-apiods,Changes to the Firebird API and ODS>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6300[CORE-6300]

SQL standard syntax for timezone offsets::
Timezone offset in timestamp/time literal, `CAST`, `SET TIME ZONE` and `AT TIME ZONE` now follows SQL standard syntax only.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6429[CORE-6429]

No -pidfile option anymore::
PIDFile/-pidfile directive/option has been removed from Firebird Super(Server/Classic) systemd unit.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6413[CORE-6413]

Time zone displacement in configuration::
Usage of time zone displacement is now allowed in configuration setting `DefaultTimeZone`.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6395[CORE-6395]

Better dependency tracking when installing Firebird on Linux::
Presence of tomcrypt & curses libraries is now checked before installing Firebird.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6366[CORE-6366]

INT128 as a dedicated data type::
`INT128` data type has been added as explicit basic type for high precision numerics.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6342[CORE-6342]

API cleanup::
`Util` methods that return interface pointers by legacy handle are replaced with plain C functions.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6320[CORE-6320]

Ability to update the supported time zones::
Now it's possible to update list of time zones (names and ids) without source code recompilation.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6308[CORE-6308]

Support for nbackup -fixup via Services API::
Allow to fixup (nbackup) a database using Services API
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-5085[CORE-5085]

Better error reporting for user management commands::
Explicit message about missing password is now raised for `CREATE [OR ALTER] USER` statements.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-4841[CORE-4841]

Improved sorting performance::
Sorting performance has been improved for cases when long VARCHARs are involved.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-2650[CORE-2650]


[[rnfb40-new-complete-in-beta2]]
=== Complete In Beta 2

SET BIND OF "type1" TO "type2" statement::
New session-management statement `SET BIND` defines data type coercion rules between server-side and client-side data types.
+
For full details, see <<rnfb40-msql-set-bind,SET BIND Statement>> in the <<rnfb40-msql,Management Statements>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6287[CORE-6287].

SQL-level replication management::
`ALTER DATABASE` and `CREATE/ALTER TABLE` statements are extended to allow SQL-level management for the replicated table set and current replication state.
For details, see <<rnfb40-ddl-replication,Replication Management>> in the <<rnfb40-ddl,Data Definition Language>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6285[CORE-6285].

FLOAT datatype is now SQL standard compliant::
`FLOAT(p)` definition is changed to represent precision in binary digits (as defined by the SQL specification) rather than in decimal digits as before.
For details, see <<rnfb40-ddl-float,Standard Compliance for Data Type FLOAT>> in the <<rnfb40-ddl,Data Definition Language>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6109[CORE-6109].

Starting multiple transactions using the same initial transaction snapshot::
`SET TRANSACTION` statement makes it possible to share the same transaction snapshot among multiple transactions (possibly started by different attachments).
For details, see <<rnfb40-dml-set-tran-snapshot,Sharing Transaction Snapshots>> in the <<rnfb40-dml,Data Manipulation Language>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6018[CORE-6018].

Better transaction control in ISQL::
ISQL can now (optionally) remember the transaction parameters of the last started transaction and reuse them for subsequent transactions.
For details, see <<rnfb40-util-isql-keeptranparams,Keeping Transaction Parameters>> in the <<rnfb40-util,Utilities>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-4933[CORE-4933].

Lateral derived tables::
Support for SQL:2011 compliant lateral derived tables.
For details, see <<rnfb40-dml-lateral,Lateral Derived Tables>> in the <<rnfb40-dml,Data Manipulation Language>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-3435[CORE-3435].

Convenient usage of TIMESTAMP/TIME WITH TIME ZONE when appropriate ICU library is not installed on the client side::
In order to work with time zone names introduced with the new data types `TIME WITH TIME ZONE` and `TIMESTAMP WITH TIME ZONE`, the Firebird client library provides API extensions that internally use the ICU library. If the ICU library is missing (or has an incorrect version), the time value would be represented in GMT which may be inconvinient.
+
To provide a better workaround to this issue, the so called _EXTENDED_ format of the time zone information has been introduced. It includes both time zone name and its corresponding GMT offset. The GMT offset will be used as a fallback in the case of missing or mismatched ICU library.
For details see <<rnfb40-msql-set-bind,SET BIND Statement>> in the <<rnfb40-msql,Management Statements>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6286[CORE-6286].

Options in user management statements can be specified in arbitrary order::
DDL statements `CREATE USER`, `RECREATE USER`, `ALTER USER`, `ALTER CURRENT USER` and `CREATE OR ALTER USER` now allow their options (`PASSWORD`, `FIRSTNAME`, `TAGS`, etc) to be specified in arbitrary order.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6279[CORE-6279].

Efficient table scans for DBKEY-based range conditions::
Range conditions (less-than and more-than) applied to a `RDB$DB_KEY` pseudo-column are now executed using a range table scan instead of a full table scan, thus providing better performance of such queries.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6278[CORE-6278].

Increased parsing speed of long queries::
Stack growth increment inside the SQL parser has been increased to allow less memory reallocations/copies and thus improve the parsing performance for long queries.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6274[CORE-6274].

API methods to set various names (field, relation, etc.) in the metadata builder::
Methods `setField()`, `setRelation()`, `setOwner()`, `setAlias()` have been added to the `IMetadataBuilder` interface of the Firebird API to set up the corresponding values for the given API message.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6268[CORE-6268].

SUSPEND is prohibited in procedures and EXECUTE BLOCK without RETURNS::
If a stored procedure or an `EXECUTE BLOCK` statement misses the `RETURNS` declaration (i.e.
it has no output paratemers), then the `SUSPEND` statement inside its body is prohibited and error `isc_suspend_without_returns` is raised.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6239[CORE-6239].

Improve performance when using SRP plugin for authentication::
Connections cache has been implemented inside the SRP authentication plugin to improve the performance.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6237[CORE-6237].

Delivery of key known to the client to any database connection::
It makes it possible to run standard utilities (like _gfix_) or service tasks against an encrypted database on remote server in the cases when the database key is known to the client.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6220[CORE-6220].

Support for specials (inf/nan) when sorting DECFLOAT values::
Special values (like __INF__/__NaN__) have been taken into account when sorting `DECFLOAT` values, the output order is now consistent with their comparison rules.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6219[CORE-6219].

Extend trace record for COMMIT/ROLLBACK RETAINING to show old/new transaction IDs::
`COMMIT/ROLLBACK RETAINING` statement preserves the current transaction context but generates a new transaction ID.
The trace output has been extended to show this new transaction ID in the `COMMIT_RETAINING` and `ROLLBACK_RETANING` trace events and also show both initial and new transaction IDs in every transaction identifier in the trace records.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6095[CORE-6095].

Show OS-specific error when entrypoint is not found in dynamic library::
When the dynamic library loaded by the Firebird engine misses the required entrypoint, the reported error now includes the OS-specific information.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6069[CORE-6069].

Change behavior of skipped and repeated wall times within time zones::
Within time zones, some wall times do not exist (DST starting) or repeat twice (DST ending).
Firebird has been modified to handle these situations accordingly to the ECMAScript standard.
For example: 
+
** 1:30 AM on November 5, 2017 in America/New_York is repeated twice (fall backward), but it must be interpreted as 1:30 AM UTC-04 instead of 1:30 AM UTC-05.
** 2:30 AM on March 12, 2017 in America/New_York does not exist, but it must be interpreted as 2:30 AM UTC-05 (equivalent to 3:30 AM UTC-04).

+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6058[CORE-6058].

Built-in functions converting binary string to hexadecimal representation and vice versa::
Functions `HEX_ENCODE` and `HEX_DECODE` have been added to convert between binary strings and their hexadecimal representations.
See <<rnfb4-dml-new-builtin-hex,HEX_ENCODE() and HEX_DECODE()>> for their description.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6049[CORE-6049].

Ability to see the current state of database encryption::
Column `MON$CRYPT_STATE` has been added to the table `MON$DATABASE`.
It has four possible states:
+
* 0 - not encrypted
* 1 - encrypted
* 2 - decryption is in progress
* 3 - encryption is in progress

+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6048[CORE-6048].

DPB properties for DECFLOAT configuration::
New DPB items have been added to the API that can be used to set up the `DECFLOAT` properties for the current attachment.
See also <<rnfb40-dml-lateral,Setting DECFLOAT Properties>> in the <<rnfb40-msql,Management Statements>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6032[CORE-6032].

Transaction info item fb_info_tra_snapshot_number in the API::
New TPB item `fb_info_tra_snapshot_number` has been added to the API that returns the snapshot number of the current transaction.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-6017[CORE-6017].

EXECUTE STATEMENT with excess parameters::
Input parameters of `EXECUTE STATEMENT` command may be declared using the `EXCESS` prefix to indicate that they can be missing in the query text.
See <<rnfb40-ddl-execstmt-excess,Excess parameters in EXECUTE STATEMENT>> in the <<rnfb40-ddl,Data Definition Language>> chapter for details.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-5658[CORE-5658].

Ability to backup/restore only tables defined via a command line argument (pattern)::
New command-line switch `-INCLUDE_DATA` has been added to _gbak_, see <<rnfb40-util-gbak-include-data,Ability to Backup/Restore Only Specified Tables>> in the <<rnfb40-util,Utilities>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-5538[CORE-5538].

RECREATE USER statement::
New DDL statement `RECREATE USER` has been added to drop and re-create the specified user in a single step.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-4726[CORE-4726].

Authenticate user in "EXECUTE STATEMENT ON EXTERNAL DATA SOURCE" by hash of the current password::
New sample plugin named `ExtAuth` has been added to the Firebird distribution package.
It allows to omit user name and password when calling `EXECUTE STATEMENT` against a trusted group of servers sharing the same `ExtAuth` plugin and the key specific for that group.
See `/firebird/examples/extauth/INSTALL` for more details.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-3983[CORE-3983].

Extended precision for numerics::
Fixed point numerics with precision up to 38 digits are now supported, along with improved intermediate calculations for shorter numerics.
For details, see <<rnfb40-ddl-longer-numerics,Increased Precision for NUMERIC and DECIMAL Types>> in the <<rnfb40-ddl,Data Definition Language>> chapter.

[[rnfb40-new-complete-in-beta1]]
=== Complete In Beta 1

Support for international time zones::
International time zone support from Firebird 4.0 onward comprises data types, functions and internal algorithms to manage date/time detection, storage and calculations involving international time zones based on UTC (Adriano dos Santos Fernandes).
+
For full details, see <<rnfb40-timezone,Support for International Time Zones>> in the <<rnfb40-engine,Engine>> chapter.
+
Tracker tickets http://tracker.firebirdsql.org/browse/CORE-694[CORE-694] and http://tracker.firebirdsql.org/browse/CORE-909[CORE-909]

Built-in replication::
Built-in logical (row level) replication, both synchronous and asynchronous (Dmitry Yemanov & Roman Simakov)
+
For details, see <<rnfb40-replication,Firebird Replication>> in the <<rnfb40-engine,Engine>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-2021[CORE-2021]

New way to capture the database snapshot::
Introducing a new methodology for the Firebird engine to capture the snapshots for retaining the consistency of a transaction's view of database state.
The new approach enables read consistency to be maintained for the life of a statement in READ COMMITTED transactions and also allows more optimal garbage collection.
+
The changes are described in more detail in the topic <<rnfb40-engine-trans-commit-order,Commit Order for Capturing the Database Snapshot>> in the chapter <<rnfb40-engine,Changes in the Firebird Engine>>.

Pooling of external connections::
The external data source (EDS) subsystem has been augmented by a pool of external connections.
The pool retains unused external connections for a period to reduce unnecessary overhead from frequent connections and disconnections by clients using the same connection strings (Vlad Khorsun).
+
For details, see <<rnfb40-connection-pool,Pooling of External Connections>> in the <<rnfb40-engine,Engine>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-5990[CORE-5990]

Physical standby solution::
Physical standby solution (incremental restore via nbackup).
+
The changes are described in more detail in the Utilities chapter in the topic <<rnfb40-util-nbackup-inplace, __nBackup__: GUID-based Backup and In-Place Merge>>.

Extended length of metadata identifiers::
Metadata names longer than 31 bytes: new maximum length of object names is 63 characters.
+
The changes are described in more detail in the topic <<rnfb40-ddl-objectnames,Extended Length for Object Names>> in the chapter <<rnfb40-ddl,Data Definition Language>>.

Configurable time-outs::
Timeout periods configurable for statements, transactions and connections.
+
The changes for statements and connections are described in more detail in the topic <<rnfb40-engine-timeouts,Timeouts at Two levels>> in the chapter <<rnfb40-engine,Changes in the Firebird Engine>> (Vlad Khorsun).
+
Tracker tickets http://tracker.firebirdsql.org/browse/CORE-658[CORE-658] and http://tracker.firebirdsql.org/browse/CORE-985[CORE-985]

New DECFLOAT data type::
The SQL:2016 standard-compliant high-precision numeric type `DECFLOAT` is introduced, along with related operational functions.
It is described in detail in the topic <<rnfb40-ddl-decfloat,Data type DECFLOAT>> in the chapter <<rnfb40-ddl,Data Definition Language>>.

Enhanced system privileges::
Predefined system roles, administrative permissions.
+
The changes are described in more detail in the topic <<rnfb4-enhancedprivs,Enhanced System Privileges>> in the <<rnfb40-security,Security>> chapter.
+
See also the <<rnfb40-msql,Management Statements>> chapter for some background about what the new system privileges are intended for.

GRANT ROLE TO ROLE::
Granting roles to other roles, described in detail in the topic <<rnfb4-grant-role-to-role,Granting a Role to Another Role>> in the <<rnfb40-security,Security>> chapter.

User groups::
User groups and cumulative permissions are described in detail in the topic <<rnfb4-grant-role-to-role,Granting a Role to Another Role>> in the <<rnfb40-security,Security>> chapter.

Batch operations in the API::
Batch API operations, bulk load optimizations, support for passing BLOBs in-line.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-820[CORE-820]
+
For details, see <<rnfb40-apiods-api-batchops,Support for Batch Insert and Update Operations in the API>>.

Window functions extensions::
Extensions to window functions are described in detail in the <<rnfb40-dml,Data Manipulation Language>> chapter in the topics <<rnfb40-dml-framed-windows,Frames for Window Functions>>, <<rnfb40-dml-named-windows,Named Windows>> and <<rnfb40-dml-windows-newfunctions,More Window Functions>>.

FILTER Clause for Aggregate Functions::
`FILTER` clause implemented for aggregate functions, see <<rnfb40-dml-filter-clause,FILTER Clause for Aggregate Functions>> in the <<rnfb40-dml,Data Manipulation Language>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-5768[CORE-5768]

Enhanced RETURNING clause in DML to enable returning all current field values::
Introduces the `RETURNING {asterisk}` syntax, and variants, to return a complete set of field values after committing a row that has been inserted, updated or deleted (Adriano dos Santos Fernandes).
For details, see <<rnfb40-engine-dml-improvement-03,RETURNING {asterisk} Now Supported>> in the <<rnfb40-dml,Data Manipulation Language>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-3808[CORE-3808]

Built-in functions FIRST_DAY and LAST_DAY::
New date/time functions `FIRST_DAY` and `LAST_DAY`, see <<rnfb40-dml-new-timefuncs,Two New Date/Time Functions>> in the <<rnfb40-dml,Data Manipulation Language>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-5620[CORE-5620]

Built-in Cryptographic functions::
New security-related functions, including eight cryptographic ones, see <<rnfb4-builtin-crypto-functions,Built-in Cryptographic Functions>> in the <<rnfb40-security,Security>> chapter.
+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-5970[CORE-5970]

Monitoring Compression and Encryption Status of Attachments::
Compression and encryption status of a connection are now available in the monitoring table `MON$ATTACHMENTS`:
+
** `MON$WIRE_COMPRESSED` (wire compression enabled = 1, disabled = 0)
** `MON$WIRE_ENCRYPTED` (wire encryption enabled = 1, disabled = 0)

+
Tracker ticket http://tracker.firebirdsql.org/browse/CORE-5536[CORE-5536]

Improve performance of _gbak restore_::
The new Batch API was used to improve the performance of _gbak restore_, including parallel operations.
+
Tracker tickets http://tracker.firebirdsql.org/browse/CORE-2992[CORE-2992] and http://tracker.firebirdsql.org/browse/CORE-5952[CORE-5952]

Backup and Restore with Encryption::
Support for backing up and restoring encrypted databases using the crypt and keyholder plug-ins -- see <<rnfb40-util-gbak-crypt,Backup and Restore with Encryption>> in the <<rnfb40-util,Utilities>> chapter.
+
Also available is compression and decompression of both encrypted and non-encrypted backups.

[[rnfb40-new-compat]]
=== Compatibility with Older Versions

Notes about compatibility with older Firebird versions are collated in the "`<<rnfb40-compat,Compatibility Issues>>`" chapter.
