[[fblangref40-security-role]]
= `ROLE`

A _role_ is a database object that packages a set of <<fblangref40-security-privs,privileges>>.
Roles implement the concept of access control at a group level.
Multiple privileges are granted to the role and then that role can be granted to or revoked from one or many users.

A user that is granted a role must supply that role in their login credentials in order to exercise the associated privileges.
Any other privileges granted to the user directly are not affected by their login with the role.
Logging in with multiple roles simultaneously is not supported.

In this section the tasks of creating and dropping roles are discussed.

[[fblangref40-security-role-create]]
== `CREATE ROLE`

.Used for
Creating a new `ROLE` object

.Available in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
CREATE ROLE _rolename_
----

[[fblangref40-security-tbl-createrole]]
.`CREATE ROLE` Statement Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|rolename
|Role name.
The maximum length is 31 characters
|===

The statement `CREATE ROLE` creates a new role object, to which one or more privileges can be granted subsequently.
The name of a role must be unique among the names of roles in the current database.

[WARNING]
====
It is advisable to make the name of a role unique among usernames as well.
The system will not prevent the creation of a role whose name clashes with an existing username but, if it happens, the user will be unable to connect to the database.
====

[[fblangref40-security-role-createpriv]]
=== Who Can Create a Role

The `CREATE ROLE` statement can be executed by:

* <<fblangref40-security-administrators,Administrators>>
* Users with the `CREATE ROLE` privilege

The user executing the `CREATE ROLE` statement becomes the owner of the role.

[[fblangref40-security-role-create-exmpl]]
=== `CREATE ROLE` Example

.Creating a role named `SELLERS`
[source]
----
CREATE ROLE SELLERS;
----

.See also
<<fblangref40-security-role-drop>>, <<fblangref40-security-grant,`GRANT`>>, <<fblangref40-security-revoke,`REVOKE`>>

[[fblangref40-security-alterrole]]
== `ALTER ROLE`

.Used for
Altering a role (enabling or disabling auto-admin mapping)

.Available in
DSQL

.Syntax
[listing,subs=+quotes]
----
ALTER ROLE _rolename_
  {SET | DROP} AUTO ADMIN MAPPING
----

[[fblangref40-security-tbl-alterrole]]
.`ALTER ROLE` Statement Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|rolename
|Role name;
specifying anything other than `RDB$ADMIN` will fail
|===

`ALTER ROLE` has no place in the create-alter-drop paradigm for database objects since a role has no attributes that can be modified.
Its actual effect is to alter an attribute of the database: Firebird uses it to enable and disable the capability for Windows Administrators to assume <<fblangref40-security-administrators,administrator privileges>> automatically when logging in.

This capability can affect only one role: the system-generated role `RDB$ADMIN` that exists in every database of ODS 11.2 or higher.
Several factors are involved in enabling this feature.

For details, see <<fblangref40-security-autoadminmapping,`AUTO ADMIN MAPPING`>>.

[[fblangref40-security-role-alterpriv]]
=== Who Can Alter a Role

The `ALTER ROLE` statement can be executed by:

* <<fblangref40-security-administrators,Administrators>>

[NOTE]
====
Although an `ALTER ANY ROLE` DDL privilege exists, it does not apply because creating or dropping mappings requires administrator privileges.
====

[[fblangref40-security-role-drop]]
== `DROP ROLE`

.Used for
Deleting a role

.Available in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
DROP ROLE _rolename_
----

The statement `DROP ROLE` deletes an existing role.
It takes just a single argument, the name of the role.
Once the role is deleted, the entire set of privileges is revoked from all users and objects that were  granted the role.

[[fblangref40-security-role-droppriv]]
=== Who Can Drop a Role

The `DROP ROLE` statement can be executed by:

* <<fblangref40-security-administrators,Administrators>>
* The owner of the role
* Users with the `DROP ANY ROLE` privilege

[[fblangref40-security-role-drop-exmpl]]
=== `DROP ROLE` Examples

.Deleting the role SELLERS
[source]
----
DROP ROLE SELLERS;
----

.See also
<<fblangref40-security-role-create>>, <<fblangref40-security-grant,`GRANT`>>, <<fblangref40-security-revoke,`REVOKE`>>
