[[fblangref30-security-granting]]
= Statements for Granting Privileges

A `GRANT` statement is used for granting privileges -- including roles -- to users and other database objects.

[[fblangref30-security-grant]]
== `GRANT`

.Used for
Granting privileges and assigning roles

.Available in
DSQL, ESQL

[[fblangref30-security-grant-privsyntax]]
.Syntax (granting privileges)
[listing,subs=+quotes]
----
GRANT <privileges>
  TO <grantee_list>
  [WITH GRANT OPTION]
  [{GRANTED BY | AS} [USER] _grantor_]

<privileges> ::=
    <table_privileges> | <execute_privilege>
  | <usage_privilege>  | <ddl_privileges>
  | <db_ddl_privilege>

<table_privileges> ::=
  {ALL [PRIVILEGES] | <table_privilege_list> }
    ON [TABLE] {_table_name_ | _view_name_}

<table_privilege_list> ::=
  <table_privilege> [, <tableprivilege> ...]

<table_privilege> ::=
    SELECT | DELETE | INSERT
  | UPDATE [(_col_ [, _col_ ...])]
  | REFERENCES [(_col_ [, _col_ ...)]

<execute_privilege> ::= EXECUTE ON
  { PROCEDURE _proc_name_ | FUNCTION _func_name_
  | PACKAGE _package_name_ }

<usage_privilege> ::= USAGE ON
  { EXCEPTION _exception_name_
  | {GENERATOR | SEQUENCE} _sequence_name_ }

<ddl_privileges> ::=
  {ALL [PRIVILEGES] | <ddl_privilege_list>} <object_type>

<ddl_privilege_list> ::=
  <ddl_privilege> [, <ddl_privilege> ...]

<ddl_privilege> ::= CREATE | ALTER ANY | DROP ANY

<object_type> ::=
    CHARACTER SET | COLLATION | DOMAIN | EXCEPTION
  | FILTER | FUNCTION | GENERATOR | PACKAGE
  | PROCEDURE | ROLE | SEQUENCE | TABLE | VIEW

<db_ddl_privileges> ::=
  {ALL [PRIVILEGES] | <db_ddl_privilege_list>} {DATABASE | SCHEMA}

<db_ddl_privilege_list> ::=
  <db_ddl_privilege> [, <db_ddl_privilege> ...]

<db_ddl_privilege> ::= CREATE | ALTER | DROP

<grantee_list> ::= <grantee> [, <grantee> ...]

<grantee> ::=
    PROCEDURE _proc_name_  | FUNCTION _func_name_
  | PACKAGE _package_name_ | TRIGGER _trig_name_
  | VIEW _view_name_       | ROLE _role_name_
  | [USER] _username_      | GROUP _Unix_group_
----

[[fblangref30-security-grant-rolesyntax]]
.Syntax (granting roles)
[listing,subs=+quotes]
----
GRANT <role_granted>
  TO <role_grantee_list>
  [WITH ADMIN OPTION]
  [{GRANTED BY | AS} [USER] _grantor_]

<role_granted> ::= _role_name_ [, _role_name_ ...]

<role_grantee_list> ::=
  <role_grantee> [, <role_grantee> ...]

<role_grantee> ::= [USER] _username_
----

[[fblangref30-security-tbl-grant]]
.`GRANT` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|grantor
|The user granting the privilege(s)

|table_name
|The name of a table

|view_name
|The name of a view

|col
|The name of table column

|proc_name
|The name of a stored procedure

|func_name
|The name of a stored function (or UDF)

|package_name
|The name of a package

|exception_name
|The name of an exception

|sequence_name
|The name of a sequence (generator)

|object_type
|The type of metadata object

|trig_name
|The name of a trigger

|role_name
|Role name

|username
|The username to which the privileges are granted to or to which the role is assigned.
If the `USER` keyword is absent, it can also be a role.

|Unix_group
|The name of a user group in a POSIX operating system
|===

The `GRANT` statement grants one or more privileges on database objects to users, roles, or other database objects.

A regular, authenticated user has no privileges on any database object until they are explicitly granted, either to that individual user or to all users bundled as the user `PUBLIC`.
When an object is created, only its creator (the owner) and <<fblangref30-security-administrators,administrators>> have privileges to it, and can grant privileges to other users, roles, or objects.

Different sets of privileges apply to different types of metadata objects.
The different types of privileges will be described separately later in this section.

[NOTE]
====
`SCHEMA` is currently a synonym for `DATABASE`;
this may change in a future version, so we recommend to always use `DATABASE`
====

[[fblangref30-security-grant-to]]
=== The `TO` Clause

The `TO` clause specifies the users, roles, and other database objects that are to be granted the privileges enumerated in _privileges_.
The clause is mandatory.

The optional `USER` keyword in the `TO` clause allow you to specify exactly who or what is granted the privilege.
If a `USER` (or `ROLE`) keyword is not specified, the server first checks for a role with this name and, if there is no such role, the privileges are granted to the user with that name without further checking.

[TIP]
====
It is recommended to always explicitly specify `USER` and `ROLE` to avoid ambiguity.
Future versions of Firebird may make `USER` mandatory.
====

[IMPORTANT]
====
* When a `GRANT` statement is executed, the security database is not checked for the existence of the grantee user.
This is not a bug: SQL permissions are concerned with controlling data access for authenticated users, both native and trusted, and trusted operating system users are not stored in the security database.
* When granting a privilege to a database object other than user or role, such as a procedure, trigger or view, you must specify the object type.
* Although the `USER` keyword is optional, it is advisable to use it, in order to avoid ambiguity with roles.
====

[[fblangref30-security-privs-role]]
==== Packaging Privileges in a `ROLE` Object

A role is a "`container`" object that can be used to package a collection of privileges.
Use of the role is then granted to each user that requires those privileges.
A role can also be granted to a list of users.

The role must exist before privileges can be granted to it.
See <<fblangref30-security-role-create,`CREATE ROLE`>> for the syntax and rules.
The role is maintained by granting privileges to it and, when required, revoking privileges from it.
When a role is dropped (see <<fblangref30-security-role-drop,`DROP ROLE`>>), all users lose the privileges acquired through the role.
Any privileges that were granted additionally to an affected user by way of a different grant statement are retained.

A user that is granted a role must supply that role with his login credentials in order to exercise the associated privileges.
Any other privileges granted to the user are not affected by logging in with a role.

More than one role can be granted to the same user but logging in with multiple roles simultaneously is not supported.

A role can be granted only to a user.

[[fblangref30-security-grant-public]]
==== The User `PUBLIC`

Firebird has a predefined user named `PUBLIC`, that represents all users.
Privileges for operations on a particular object that are granted to the user `PUBLIC` can be exercised by any authenticated user.

[IMPORTANT]
====
If privileges are granted to the user `PUBLIC`, they should be revoked from the user `PUBLIC` as well.
====

[[fblangref30-security-grant-withgrantoption]]
=== The `WITH GRANT OPTION` Clause

The optional `WITH GRANT OPTION` clause allows the users specified in the user list to grant the privileges specified in the privilege list to other users.

[CAUTION]
====
It is possible to assign this option to the user `PUBLIC`.
Do not do this!
====

[[fblangref30-security-grant-grantedby]]
=== The `GRANTED BY` Clause

By default, when privileges are granted in a database, the current user is recorded as the grantor.
The `GRANTED BY` clause enables the current user to grant those privileges as another user.

When using the `REVOKE` statement, it will fail if the current user is not the user that was named in the `GRANTED BY` clause.

The `GRANTED BY` (and `AS`) clause can be used only by the database owner and other <<fblangref30-security-administrators,administrators>>.
The object owner cannot use `GRANTED BY` unless they also have administrator privileges.

[[fblangref30-security-grant-grant-as]]
==== Alternative Syntax Using `AS __username__`

The non-standard `AS` clause is supported as a synonym of the `GRANTED BY` clause to simplify migration from other database systems.

[[fblangref30-security-grant-table]]
=== Privileges on Tables and Views

For tables and views, unlike other metadata objects, it is possible to grant several privileges at once.

[[fblangref30-security-tbl-tableprivs]]
.List of Privileges on Tables
`SELECT`::
Permits the user or object to `SELECT` data from the table or view

`INSERT`::
Permits the user or object to `INSERT` rows into the table or view

`DELETE`::
Permits the user or object to `DELETE` rows from the table or view

`UPDATE`::
Permits the user or object to `UPDATE` rows in the table or view, optionally restricted to specific columns

`REFERENCES`::
Permits the user or object to reference the table via a foreign key, optionally restricted to the specified columns.
If the primary or unique key referenced by the foreign key of the other table is composite then all columns of the key must be specified.

`ALL [PRIVILEGES]`::
Combines `SELECT`, `INSERT`, `UPDATE`, `DELETE` and `REFERENCES` privileges in a single package

[[fblangref30-security-grant-table-exmpl]]
==== Examples of `GRANT <privilege>` on Tables

. `SELECT` and `INSERT` privileges to the user `ALEX`:
+
[source]
----
GRANT SELECT, INSERT ON TABLE SALES
  TO USER ALEX;
----
. The `SELECT` privilege to the `MANAGER`, `ENGINEER` roles and to the user `IVAN`:
+
[source]
----
GRANT SELECT ON TABLE CUSTOMER
  TO ROLE MANAGER, ROLE ENGINEER, USER IVAN;
----
. All privileges to the `ADMINISTRATOR` role, together with the authority to grant the same privileges to others:
+
[source]
----
GRANT ALL ON TABLE CUSTOMER
  TO ROLE ADMINISTRATOR
  WITH GRANT OPTION;
----
. The `SELECT` and `REFERENCES` privileges on the `NAME` column to all users and objects:
+
[source]
----
GRANT SELECT, REFERENCES (NAME) ON TABLE COUNTRY
TO PUBLIC;
----
. The `SELECT` privilege being granted to the user `IVAN` by the user `ALEX`:
+
[source]
----
GRANT SELECT ON TABLE EMPLOYEE
  TO USER IVAN
  GRANTED BY ALEX;
----
. Granting the `UPDATE` privilege on the `FIRST_NAME`, `LAST_NAME` columns:
+
[source]
----
GRANT UPDATE (FIRST_NAME, LAST_NAME) ON TABLE EMPLOYEE
  TO USER IVAN;
----
. Granting the `INSERT` privilege to the stored procedure `ADD_EMP_PROJ`:
+
[source]
----
GRANT INSERT ON EMPLOYEE_PROJECT
  TO PROCEDURE ADD_EMP_PROJ;
----

[[fblangref30-security-grant-execute]]
=== The `EXECUTE` Privilege

The `EXECUTE` privilege applies to stored procedures, stored functions (including UDFs), and packages.
It allows the grantee to execute the specified object, and, if applicable, to retrieve its output.

In the case of selectable stored procedures, it acts somewhat like a `SELECT` privilege, insofar as this style of stored procedure is executed in response to a `SELECT` statement.

[NOTE]
====
For packages, the `EXECUTE` privilege can only be granted for the package as a whole, ot for individual subroutines.
====

[[fblangref30-security-grant-execute-exmpl]]
==== Examples of Granting the `EXECUTE` Privilege

. Granting the `EXECUTE` privilege on a stored procedure to a role:
+
[source]
----
GRANT EXECUTE ON PROCEDURE ADD_EMP_PROJ
  TO ROLE MANAGER;
----
. Granting the `EXECUTE` privilege on a stored function to a role:
+
[source]
----
GRANT EXECUTE ON FUNCTION GET_BEGIN_DATE
  TO ROLE MANAGER;
----
. Granting the `EXECUTE` privilege on a package to user `PUBLIC`:
+
[source]
----
GRANT EXECUTE ON PACKAGE APP_VAR
  TO USER PUBLIC;
----
. Granting the `EXECUTE` privilege on a function to a package:
+
[source]
----
GRANT EXECUTE ON FUNCTION GET_BEGIN_DATE
  TO PACKAGE APP_VAR;
----

[[fblangref30-security-grant-usage]]
=== The `USAGE` Privilege

To be able to use metadata objects other than tables, views, stored procedures or functions, triggers and packages, it is necessary to grant the user (or database object like trigger, procedure or function) the `USAGE` privilege on these objects.

Since Firebird executes stored procedures and functions, triggers, and package routines with the privileges of the caller, it is necessary that either the user or otherwise the routine itself has been granted the `USAGE` privilege.

[NOTE]
====
In Firebird 3.0, the `USAGE` privilege is only available for exceptions and sequences (in `gen_id(__gen_name__, __n__) or `next value for __gen_name__`).
Support for the `USAGE` privilege for other metadata objects may be added in future releases.
====

[NOTE]
====
For sequences (generators), the `USAGE` privilege only grants the right to increment the sequence using the `GEN_ID` function or `NEXT VALUE FOR`.
The `SET GENERATOR` statement is a synonym for `ALTER SEQUENCE ... RESTART WITH ...`, and is considered a DDL statement.
By default, only the owner of the sequence and administrators have the rights to such operations.
The right to set the initial value of any sequence can be granted with `GRANT ALTER ANY SEQUENCE`, which is not recommend for general users.
====

[[fblangref30-security-grant-usage-exmpl]]
==== Examples of Granting the `USAGE` Privilege

. Granting the `USAGE` privilege on a sequence to a role:
+
[source]
----
GRANT USAGE ON SEQUENCE GEN_AGE
  TO ROLE MANAGER;
----
. Granting the `USAGE` privilege on a sequence to a trigger:
+
[source]
----
GRANT USAGE ON SEQUENCE GEN_AGE
  TO TRIGGER TR_AGE_BI;
----
. Granting the `USAGE` privilege on an exception to a package:
+
[source]
----
GRANT USAGE ON EXCEPTION
  TO PACKAGE PKG_BILL;
----

[[fblangref30-security-grant-ddl]]
=== DDL Privileges

By default, only <<fblangref30-security-administrators,administrators>> can create new metadata objects;
altering or dropping these objects is restricted to the owner of the object (its creator) and administrators.
DDL privileges can be used to grant privileges for these operations to other users.

.Available DDL Privileges
`CREATE`::
Allows creation of an object of the specified type

`ALTER ANY`::
Allows modification of any object of the specified type

`DROP ANY`::
Allows deletion of any object of the specified type

`ALL [PRIVILEGES]`::
Combines the `CREATE`, `ALTER ANY` and `DROP ANY` privileges for the specified type

[NOTE]
====
There are no separate DDL privileges for triggers and indexes.
The necessary privileges are inherited from the table or view.
Creating, altering or dropping a trigger or index requires the `ALTER ANY TABLE` or `ALTER ANY VIEW` privilege.
====

[[fblangref30-security-grant-ddl-exmpl]]
==== Examples of Granting DDL Privileges

. Allow user `JOE` to create tables
+
[source]
----
GRANT CREATE TABLE
  TO USER Joe;
----
. Allow user `JOE` to alter any procedure
+
[source]
----
GRANT ALTER ANY PROCEDURE
  TO USER Joe;
----

[[fblangref30-security-grant-db-ddl]]
=== Database DDL Privileges

The syntax for granting privileges to create, alter or drop a database deviates from the normal syntax of granting DDL privileges for other object types.

.Available Database DDL Privileges
`CREATE`::
Allows creation of a database

`ALTER`::
Allows modification of the current database

`DROP`::
Allows deletion of the current database

`ALL [PRIVILEGES]`::
Combines the `ALTER` and `DROP` privileges.
`ALL` does not include the `CREATE` privilege.

The `ALTER DATABASE` and `DROP DATABASE` privileges apply only to the current database, whereas DDL privileges `ALTER ANY` and `DROP ANY` on other object types apply to all objects of the specified type in the current database.
The privilege to alter or drop the current database can only be granted by <<fblangref30-security-administrators,administrators>>.

The `CREATE DATABASE` privilege is a special kind of privilege as it is saved in the security database.
A list of users with the `CREATE DATABASE` privilege is available from the virtual table `SEC$DB_CREATORS`.
Only <<fblangref30-security-administrators,administrators>> in the security database can grant the privilege to create a new database.

[NOTE]
====
`SCHEMA` is currently a synonym for `DATABASE`;
this may change in a future version, so we recommend to always use `DATABASE`
====

[[fblangref30-security-grant-db-ddl-exmpl]]
=== Examples of Granting Database DDL Privileges

. Granting `SUPERUSER` the privilege to create databases:
+
[source]
----
GRANT CREATE DATABASE
  TO USER Superuser;
----
. Granting `JOE` the privilege to execute `ALTER DATABASE` for the current database:
+
[source]
----
GRANT ALTER DATABASE
  TO USER Joe;
----
. Granting `FEDOR` the privilege to drop the current database:
+
[source]
----
GRANT DROP DATABASE
  TO USER Fedor;
----

[[fblangref30-security-grant-assignroles]]
=== Assigning Roles

Assigning a role is similar to granting a privilege.
One or more roles can be assigned to one or more users, including the <<fblangref30-security-grant-public,user `PUBLIC`>>, using one `GRANT` statement.

[[fblangref30-security-grant-withadminoption]]
==== The `WITH ADMIN OPTION` Clause

The optional `WITH ADMIN OPTION` clause allows the users specified in the user list to grant the role(s) specified to other users.

[CAUTION]
====
It is possible to assign this option to `PUBLIC`.
Do not do this!
====

[[fblangref30-security-grant-assignroles-exmpl]]
==== Examples of Role Assignment

. Assigning the `DIRECTOR` and `MANAGER` roles to the user `IVAN`:
+
[source]
----
GRANT DIRECTOR, MANAGER
  TO USER IVAN;
----
. Assigning the `MANAGER` role to the user `ALEX` with the authority to assign this role to other users:
+
[source]
----
GRANT MANAGER
  TO USER ALEX WITH ADMIN OPTION;
----

.See also
<<fblangref30-security-revoke,`REVOKE`>>
