[#langref-ddl-exception]
= `EXCEPTION`

This section describes how to create, modify and delete _custom exceptions_ for use in PSQL modules.

[#langref-ddl-exception-create]
== `CREATE EXCEPTION`

Creates a custom exception for use in PSQL modules

.Available in
DSQL, ESQL

[#langref-ddl-exception-create-syntax]
.Syntax
[listing,subs=+quotes]
----
CREATE EXCEPTION [_exc-schema_ <period>] _exception_name_
  '<message>'

<message> ::= <message-part> [<message-part> ...]

<message-part> ::=
    <text>
  | @<slot>

<slot> ::= _one of 1..9_
----

[#langref-ddl-tbl-crtexcep]
.`CREATE EXCEPTION` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|exc-schema
|Schema of the exception.
If not specified, the exception will be created in the current schema;
for `ALTER`, etc., the exception will be located on the search path.

|exception_name
|Exception name.
The maximum length is 63 characters.

|message
|Default error message.
The maximum length is 1,021 characters.

|text
|Text of any character

|slot
|Slot number of a parameter.
Numbering starts at 1.
Maximum slot number is 9.
|===

The statement `CREATE EXCEPTION` creates a new exception for use in PSQL modules.
If an exception with the same name and schema exists, the statement will raise an error.

The exception name is an identifier, see <<langref-structure-identifiers,Identifiers>> for more information.

The default message is stored in character set `NONE`, i.e. in characters of any single-byte character set.
The text can be overridden in the PSQL code when the exception is thrown.

The error message may contain "`parameter slots`" that can be filled when raising the exception.

[WARNING]
====
A parameter slot number is a single digit!
A second and subsequent digits are treated as literal text.
For example, `@10` will be interpreted as slot 1 followed by a literal '```0```'.
====

Custom exceptions are stored in the system table <<fblangref-appx04-exceptions,`RDB$EXCEPTIONS`>>.

[#langref-ddl-exception-createpriv]
=== Who Can Create an Exception

The `CREATE EXCEPTION` statement can be executed by:

* <<langref-security-administrators,Administrators>>
* Users with the `CREATE EXCEPTION` privilege

The user executing the `CREATE EXCEPTION` statement becomes the owner of the exception.

[#langref-ddl-exception-exmpl]
=== `CREATE EXCEPTION` Examples

.Creating an exception named `E_LARGE_VALUE`
[source]
----
CREATE EXCEPTION E_LARGE_VALUE
  'The value is out of range';
----

.Creating a parameterized exception `E_INVALID_VALUE`
[source]
----
CREATE EXCEPTION E_INVALID_VALUE
  'Invalid value @1 for field @2';
----

.See also
<<langref-ddl-exception-alter>>, <<langref-ddl-exception-crtalter>>, <<langref-ddl-exception-drop>>, <<langref-ddl-exception-recreate>>

[#langref-ddl-exception-alter]
== `ALTER EXCEPTION`

Alters the default message of a custom exception

.Available in
DSQL, ESQL

.Syntax
[listing,subs="+quotes,macros"]
----
ALTER EXCEPTION [_exc-schema_ <period>] _exception_name_
  '<message>'

!! See syntax of <<langref-ddl-exception-create-syntax,`CREATE EXCEPTION`>> for further rules !!
----

[#langref-ddl-exception-alterpriv]
=== Who Can Alter an Exception

The `ALTER EXCEPTION` statement can be executed by:

* <<langref-security-administrators,Administrators>>
* The owner of the exception
* Users with the `ALTER ANY EXCEPTION` privilege

[#langref-ddl-exception-alter-exmpl]
=== `ALTER EXCEPTION` Examples

.Changing the default message for the exception `E_LARGE_VALUE`
[source]
----
ALTER EXCEPTION E_LARGE_VALUE
  'The value exceeds the prescribed limit of 32,765 bytes';
----

.See also
<<langref-ddl-exception-create>>, <<langref-ddl-exception-crtalter>>, <<langref-ddl-exception-drop>>, <<langref-ddl-exception-recreate>>

[#langref-ddl-exception-crtalter]
== `CREATE OR ALTER EXCEPTION`

Creates a custom exception if it doesn't exist, or alters a custom exception

.Available in
DSQL

.Syntax
[listing,subs="+quotes,macros"]
----
CREATE OR ALTER EXCEPTION [_exc-schema_ <period>] _exception_name_
  '<message>'

!! See syntax of <<langref-ddl-exception-create-syntax,`CREATE EXCEPTION`>> for further rules !!
----

The statement `CREATE OR ALTER EXCEPTION` is used to create the specified exception if it does not exist, or to modify the text of the error message returned from it if it exists already.
If an existing exception is altered by this statement, any existing dependencies will remain intact.

[#langref-ddl-exception-crtalter-exmpl]
=== `CREATE OR ALTER EXCEPTION` Example

.Changing the message for the exception `E_LARGE_VALUE`
[source]
----
CREATE OR ALTER EXCEPTION E_LARGE_VALUE
  'The value is higher than the permitted range 0 to 32,765';
----

.See also
<<langref-ddl-exception-create>>, <<langref-ddl-exception-alter>>, <<langref-ddl-exception-recreate>>

[#langref-ddl-exception-drop]
== `DROP EXCEPTION`

Drops a custom exception

.Available in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
DROP EXCEPTION [_exc-schema_ <period>] _exception_name_
----

The statement `DROP EXCEPTION` is used to delete an exception.
Any dependencies on the exception will cause the statement to fail, and the exception will not be deleted.

[#langref-ddl-exception-droppriv]
=== Who Can Drop an Exception

The `DROP EXCEPTION` statement can be executed by:

* <<langref-security-administrators,Administrators>>
* The owner of the exception
* Users with the `DROP ANY EXCEPTION` privilege

[#langref-ddl-exception-drop-exmpl]
=== `DROP EXCEPTION` Examples

.Dropping exception `E_LARGE_VALUE`
[source]
----
DROP EXCEPTION E_LARGE_VALUE;
----

.See also
<<langref-ddl-exception-create>>, <<langref-ddl-exception-recreate>>

[#langref-ddl-exception-recreate]
== `RECREATE EXCEPTION`

Drops a custom exception if it exists, and creates a custom exception

.Available in
DSQL

.Syntax
[listing,subs="+quotes,macros"]
----
RECREATE EXCEPTION [_exc-schema_ <period>] _exception_name_
  '<message>'

!! See syntax of <<langref-ddl-exception-create-syntax,`CREATE EXCEPTION`>> for further rules !!
----

The statement `RECREATE EXCEPTION` creates a new exception for use in PSQL modules.
If an exception with the same name exists already, the `RECREATE EXCEPTION` statement will try to drop it and create a new one.
If there are any dependencies on the existing exception, the attempted deletion fails and `RECREATE EXCEPTION` is not executed.

[#langref-ddl-exception-recreate-exmpl]
=== `RECREATE EXCEPTION` Example

.Recreating the `E_LARGE_VALUE` exception
[source]
----
RECREATE EXCEPTION E_LARGE_VALUE
  'The value exceeds its limit';
----

.See also
<<langref-ddl-exception-create>>, <<langref-ddl-exception-drop>>, <<langref-ddl-exception-crtalter>>
