[#langref-ddl-comment]
= Comments

Database objects and a database itself may be annotated with comments.
It is a convenient mechanism for documenting the development and maintenance of a database.
Comments created with `COMMENT ON` will survive a _gbak_ backup and restore.

[#langref-ddl-comment-create]
== `COMMENT ON`

Adds a comment to a metadata object

.Available in
DSQL

.Syntax
[listing,subs="+quotes, attributes"]
----
COMMENT ON <object> IS {'_sometext_' | NULL}

<object> ::=
    DATABASE
  | <schemaless-type> _objectname_
  | <schema-bound-type> [_object-schema_ <period>] _objectname_
  | USER _username_ [USING PLUGIN _pluginname_]
  | COLUMN [_rel-schema_ <period>] _relationname_ <period> _fieldname_
  | [{PROCEDURE | FUNCTION}] PARAMETER
      [<routine-location> <period>] _routinename_ <period> _paramname_
  | {PROCEDURE | [EXTERNAL] FUNCTION}
      [<routine-location> <period>] _routinename_
  | [GLOBAL] MAPPING _mappingname_

<schema-less-type> ::= FILTER | ROLE | SCHEMA

<schema-bound-type> ::=
    CHARACTER SET | COLLATION | DOMAIN
  | EXCEPTION     | GENERATOR | INDEX
  | PACKAGE       | SEQUENCE  | TABLE
  | TRIGGER       | VIEW

<routine-location> ::=
    _routine-schema_
  | [ _package-schema_ <period> ] _package-name_
  | _package-name_ '%' PACKAGE
  | _routine-schema_ '%' SCHEMA
----

[#langref-ddl-tbl-commenton]
.`COMMENT ON` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|sometext
|Comment text

|schemaless-type
|A schemaless metadata object type

|schema-bound-type
|A schema-bound metadata object type

|object-schema
|Schema of the object.
If not specified, the object will be located on the search path.

|objectname
|Metadata object name

|username
|Username

|pluginname
|User manager plugin name

|rel-schema
|Schema of the relation.
If not specified, the relation will be located on the search path.

|relationname
|Name of table or view

|fieldname
|Name of the column

|routinename
|Name of stored procedure or function

|paramname
|Name of a stored procedure or function parameter

|routine-schema
|Schema containing the routine directly

|package-schema
|Schema containing the package

|package_name
|Name of the package containing the routine

|mappingname
|Name of a mapping
|===

The `COMMENT ON` statement adds comments for database objects (metadata).
Comments are saved to the `RDB$DESCRIPTION` column of the corresponding system tables.
Client applications can view comments from these fields.

[NOTE]
====
. If you add an empty comment ("```''```"), it will be saved as `NULL` in the database.
. By default, the `COMMENT ON USER` statement will create comments on users managed by the default user manager (the first plugin listed in the `UserManager` config option).
The `USING PLUGIN` can be used to comment on a user managed by a different user manager.
. Comments on users are not stored for the `Legacy_UserManager`.
. Comments on users are stored in the security database.
. Comments on global mappings are stored in the security database.
====

[WARNING]
====
Comments on users are visible to that user through the <<langref-appx06-users,`SEC$USERS`>> virtual table.
====

[#langref-ddl-comment-createpriv]
=== Who Can Add a Comment

The `COMMENT ON` statement can be executed by:

* <<langref-security-administrators,Administrators>>
* The owner of the object that is commented on
* Users with the `ALTER ANY __object_type__` privilege, where _object_type_ is the type of object commented on (e.g. `PROCEDURE`)

[#langref-ddl-comment-create-exmpl]
=== Examples using `COMMENT ON`

. Adding a comment for the current database
+
[source]
----
COMMENT ON DATABASE IS 'It is a test (''my.fdb'') database';
----
. Adding a comment for the `METALS` table
+
[source]
----
COMMENT ON TABLE METALS IS 'Metal directory';
----
. Adding a comment for the `ISALLOY` field in the `METALS` table
+
[source]
----
COMMENT ON COLUMN METALS.ISALLOY IS '0 = fine metal, 1 = alloy';
----
. Adding a comment for a parameter
+
[source]
----
COMMENT ON PARAMETER ADD_EMP_PROJ.EMP_NO IS 'Employee ID';
----
. Adding a comment for a package, its procedures and functions, and their parameters
+
[source]
----
COMMENT ON PACKAGE APP_VAR IS 'Application Variables';

COMMENT ON FUNCTION APP_VAR.GET_DATEBEGIN
IS 'Returns the start date of the period';

COMMENT ON PROCEDURE APP_VAR.SET_DATERANGE
IS 'Set date range';

COMMENT ON
PROCEDURE PARAMETER APP_VAR.SET_DATERANGE.ADATEBEGIN
IS 'Start Date';
----
