[#langref-ddl-schema]
= `SCHEMA`

// TODO: Maybe some of this needs to be described in #langref-commons instead of here

Introduced in Firebird 6.0, schemas (schemata) allow you to group related database objects like tables, functions, procedures, etc. into a namespace (the schema).
Within a schema, object names must be unique.
Between schemas, object can have duplicate names.

This grouping has several purposes

* logical organisation (keeping related things together, separate unrelated things)
* avoid naming conflicts for applications sharing a database (by putting the application-specific objects in separate schemas)
* data-isolation.
For example, in a multi-tenant database, each schema can have the same objects, but differing data.

The following object types are always contained in a schema (or, schema-bound):

* Tables
* Views
* Triggers
* Procedures
* Exceptions
* Domains
* Indexes
* Character sets
* Sequences / Generators
* Functions
* Collations
* Packages

The following object types are not contained in a schema (or, schema-less):

* Users
* Roles
* Blob filters
* Schemas
* Mappings and global mappings

Initially, a Firebird database has two schemas:

[horizontal]
`PUBLIC`:: schema for user objects
`SYSTEM`:: schema for system objects (the `RDB${asterisk}`, `MON${asterisk}`, and other system provided tables, views and packages)

The `PUBLIC` schema can be dropped.

[#langref-ddl-schema-create]
== `CREATE SCHEMA`

Creates a schema.

.Available in
DSQL

.Syntax
[listing,subs=+quotes]
----
CREATE [IF NOT EXISTS] SCHEMA _schema_name_
    [DEFAULT CHARACTER SET _default_charset_]
    [DEFAULT SQL SECURITY {DEFINER | INVOKER}]
----

[#langref-ddl-schema-tbl-createparam]
.`CREATE SCHEMA` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|schema_name
|Schema name.
The maximum length is 63 characters.

|default_charset
|Specifies the default character set for string data types created inside this schema.
If not specified, it inherits the default database character set.
|===

The `CREATE SCHEMA` statement creates a new schema.

Newly created schemas grant `USAGE` permission only to their owners.

[#langref-ddl-schema-createopts]
=== Optional Clauses for `CREATE SCHEMA`

`IF NOT EXISTS`::
If the schema already exists, no changes will be performed.

`DEFAULT CHARACTER SET`::
The default character set for creating data structures of string data types.
Character sets are used for `CHAR`, `VARCHAR` and `BLOB SUB_TYPE TEXT` data types.
The default character set of the database is used by default.
//TODO Also valid for schema? :: It is also possible to specify the default `COLLATION` for the default character set, making that collation the default for the default character set.
The default will be used for objects created in the schema except where an alternative character set, with or without a specified collation, is used explicitly for a field, domain, variable, cast expression, etc.

`SET DEFAULT SQL SECURITY`::
Specifies the default `SQL SECURITY` option to apply at runtime for objects in the schema without the SQL Security property set.
By default, the `SQL SECURITY` option of the database is inherited.
See also <<langref-security-sql-security,__SQL Security__>> in chapter _Security_.

[#langref-ddl-schema-create-who]
=== Who Can Create a Schema

The `CREATE SCHEMA` statement can be executed by:

* <<langref-security-administrators,Administrators>>
* Users with the `CREATE SCHEMA` privilege

.See also
<<langref-ddl-schema-alter>>, <<langref-ddl-schema-drop>>, <<langref-ddl-schema-crtoralt>>, <<langref-ddl-schema-recreate>>

[#langref-ddl-schema-alter]
== `ALTER SCHEMA`

Alters a schema.

.Available in
DSQL

.Syntax
[listing,subs=+quotes]
----
ALTER SCHEMA _schema_name_
    <alter_schema_option>...

<alter_schema_option> ::=
    SET DEFAULT CHARACTER SET _default_charset_
  | SET DEFAULT SQL SECURITY {DEFINER | INVOKER}
  | DROP DEFAULT CHARACTER SET
  | DROP DEFAULT SQL SECURITY
----

[#langref-ddl-schema-tbl-altparam]
.`ALTER SCHEMA` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|schema_name
|Schema name.
The maximum length is 63 characters.

|default_charset
|Specifies the default character set for string data types created inside this schema.
|===

The `ALTER SCHEMA` statement changes the configuration of a schema.

[#langref-ddl-schema-altopts]
=== Optional Clauses of `ALTER SCHEMA`

An `ALTER SCHEMA` statement needs one or more of these clauses

`SET DEFAULT CHARACTER SET`::
Alters the default character set for creating data structures of string data types.

`DROP DEFAULT CHARACTER SET`::
Drops the default character set of the schema, inheriting the default character set of the database.

`SET DEFAULT SQL SECURITY`::
Alters the default `SQL SECURITY` option.
See also <<langref-security-sql-security,__SQL Security__>> in chapter _Security_.

`DROP DEFAULT SQL SECURITY`::
Drops the default `SQL SECURITY` option of the schema, inheriting the default `SQL SECURITY` option of the database.

[#langref-ddl-schema-alter-who]
=== Who Can Alter a Schema

The `ALTER SCHEMA` statement can be executed by:

* <<langref-security-administrators,Administrators>>
* The schema owner
* Users with the `ALTER ANY SCHEMA` privilege

.See also
<<langref-ddl-schema-create>>, <<langref-ddl-schema-crtoralt>>

[#langref-ddl-schema-drop]
== `DROP SCHEMA`

Drops a schema.

.Available in
DSQL

.Syntax
[listing,subs=+quotes]
----
DROP [IF EXISTS] SCHEMA _schema_name_
----

[#langref-ddl-schema-tbl-dropparam]
.`DROP SCHEMA` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|schema_name
|Schema name.
The maximum length is 63 characters.
|===

Drops the schema.
Currently, only empty schemas can be dropped.
In the future, a `CASCADE` sub-clause will be introduced, allowing schemas to be dropped along with all their contained objects.

[#langref-ddl-schema-dropopts]
=== Optional Clauses for `DROP SCHEMA`

`IF EXISTS`::
If the schema does not exist, no changes will be performed.
If this clause is not specified, an error is raised if the schema does not exist.

[#langref-ddl-schema-drop-who]
=== Who Can Alter a Schema

The `DROP SCHEMA` statement can be executed by:

* <<langref-security-administrators,Administrators>>
* The schema owner
* Users with the `DROP ANY SCHEMA` privilege

.See also
<<langref-ddl-schema-create>>, <<langref-ddl-schema-recreate>>

[#langref-ddl-schema-crtoralt]
== `CREATE OR ALTER SCHEMA`

Creates or alters a schema.

.Available in
DSQL

.Syntax
[listing,subs=+quotes]
----
CREATE OR ALTER SCHEMA _schema_name_
    [DEFAULT CHARACTER SET _default_charset_]
    [DEFAULT SQL SECURITY {DEFINER | INVOKER}]
----

If the schema does not exist, creates it as if executing the equivalent <<langref-ddl-schema-create>>.
Otherwise, alters the schema as if executing <<langref-ddl-schema-alter>> with equivalent `SET` options.

For further details, see <<langref-ddl-schema-create>>.

.See also
<<langref-ddl-schema-alter>>, <<langref-ddl-schema-create>>, <<langref-ddl-schema-recreate>>

[#langref-ddl-schema-recreate]
== `RECREATE SCHEMA`

Drops and creates a schema.

.Available in
DSQL

.Syntax
[listing,subs=+quotes]
----
RECREATE SCHEMA _schema_name_
    [DEFAULT CHARACTER SET _default_charset_]
    [DEFAULT SQL SECURITY {DEFINER | INVOKER}]
----

If the schema already exists, drops it as if executing <<langref-ddl-schema-drop>>.
Next, it will create the schema as if executing <<langref-ddl-schema-create>>.

For further details, see <<langref-ddl-schema-create>> and <<langref-ddl-schema-drop>>.

.See also
<<langref-ddl-schema-create>>, <<langref-ddl-schema-drop>>