[#langref-ddl-shadow]
= `SHADOW`

A _shadow_ is an exact, page-by-page copy of a database.
Once a shadow is created, all changes made in the database are immediately reflected in the shadow.
If the primary database file becomes unavailable for some reason, the DBMS will switch to the shadow.

This section describes how to create and delete shadow files.

[#langref-ddl-createshadow]
== `CREATE SHADOW`

Creates a shadow file for the current database

.Available in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
CREATE SHADOW <sh_num> [{AUTO | MANUAL}] [CONDITIONAL]
  '_filepath_'
----

[#langref-ddl-tbl-createshadow]
.`CREATE SHADOW` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|sh_num
|Shadow number -- a positive number identifying the shadow set

|filepath
|The name of the shadow file and the path to it, in accord with the rules of the operating system

|===

The `CREATE SHADOW` statement creates a new shadow.
The shadow starts duplicating the database right at the moment it is created.
It is not possible for a user to connect to a shadow.

The page size for shadow files is set to be equal to the database page size and cannot be changed.

If a calamity occurs involving the original database, the system converts the shadow to a copy of the database and switches to it.
The shadow is then _unavailable_.
What happens next depends on the `MODE` option.

[#langref-ddl-createshadowmode]
=== `AUTO | MANUAL` Modes

When a shadow is converted to a database, it becomes unavailable.
A shadow might alternatively become unavailable because someone accidentally deletes its file, or the disk space where the shadow files are stored is exhausted or is itself damaged.

* If the AUTO mode is selected (the default value), shadowing ceases automatically, all references to it are deleted from the database header, and the database continues functioning normally.
+
If the `CONDITIONAL` option is set, the system will attempt to create a new shadow to replace the lost one.
It does not always succeed, however, and a new one may need to be created manually.
* If the MANUAL mode attribute is set when the shadow becomes unavailable, all attempts to connect to the database and to query it will produce error messages.
The database will remain inaccessible until either the shadow again becomes available, or the database administrator deletes it using the `DROP SHADOW` statement.
`MANUAL` should be selected if continuous shadowing is more important than uninterrupted operation of the database.

[TIP]
====
You can verify the location of the shadow file(s) by connecting to the database using _isql_ and running the command `SHOW DATABASE;`
====

[#langref-ddl-createshadow-who]
=== Who Can Create a Shadow

The `CREATE SHADOW` statement can be executed by:

* <<langref-security-administrators,Administrators>>
* Users with the `ALTER DATABASE` privilege

[#langref-ddl-createshadow-example]
=== Examples Using `CREATE SHADOW`

. Creating a shadow for the current database as "`shadow number 1`":
+
[source]
----
CREATE SHADOW 1 'g:\data\test.shd';
----

.See also
<<langref-ddl-db-create>>, <<langref-ddl-dropshadow>>

[#langref-ddl-dropshadow]
== `DROP SHADOW`

Drops (deletes) a shadow file from the current database

.Available in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
DROP SHADOW _sh_num_
  [{DELETE | PRESERVE} FILE]
----

[#langref-ddl-tbl-dropshadow]
.`DROP SHADOW` Statement Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|sh_num
|Shadow number -- a positive number identifying the shadow set
|===

The `DROP SHADOW` statement deletes the specified shadow for the current database.
When a shadow is dropped, all files related to it are deleted and shadowing to the specified _sh_num_ ceases.
The optional `DELETE FILE` clause makes this behaviour explicit.
On the contrary, the `PRESERVE FILE` clause will remove the shadow from the database, but the file itself will not be deleted.

[#langref-ddl-dropshadow-who]
=== Who Can Drop a Shadow

The `DROP SHADOW` statement can be executed by:

* <<langref-security-administrators,Administrators>>
* Users with the `ALTER DATABASE` privilege

[#langref-ddl-dropshadow-example]
=== Example of `DROP SHADOW`

.Deleting "`shadow number 1`".
[source]
----
DROP SHADOW 1;
----

.See also
<<langref-ddl-createshadow>>
