[#langref-ddl-charset]
= `CHARACTER SET`

[#langref-ddl-charset-alter]
== `ALTER CHARACTER SET`

Sets the default collation of a character set

.Available in
DSQL

.Syntax
[listing,subs=+quotes]
----
ALTER CHARACTER SET _charset_
  SET DEFAULT COLLATION _collation_
----

[#langref-ddl-tbl-charsetalter]
.`ALTER CHARACTER SET` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|charset
|Character set identifier

|collation
|The name of the collation
|===

This will affect the future usage of the character set, except for cases where the `COLLATE` clause is explicitly overridden.
In that case, the collation of existing domains, columns and PSQL variables will remain intact after the change to the default collation of the underlying character set.

[NOTE]
====
If you change the default collation for the database character set (the one defined when the database was created), it will change the default collation for the database.

If you change the default collation for the character set that was specified during the connection, string constants will be interpreted according to the new collation value, except in those cases where the character set and/or the collation have been overridden.
====

[#langref-ddl-charset-alterpriv]
=== Who Can Alter a Character Set

The `ALTER CHARACTER SET` statement can be executed by:

* <<langref-security-administrators,Administrators>>
* Users with the `ALTER ANY CHARACTER SET` privilege

[#langref-ddl-charset-alter-exmpl]
=== `ALTER CHARACTER SET` Example

.Setting the default `UNICODE_CI_AI` collation for the `UTF8` encoding
[source]
----
ALTER CHARACTER SET UTF8
  SET DEFAULT COLLATION UNICODE_CI_AI;
----
