:sectnums!:

[appendix]
[[fblangref30-appx05-montables-de]]
= Monitoringtabellen

Die Firebird-Engine kann Aktivitäten in einer Datenbank überwachen und über die Monitoring-Tabellen für Benutzerabfragen zur Verfügung stellen.
Die Definitionen dieser Tabellen sind immer in der Datenbank vorhanden, alle mit dem Präfix `MON$` benannt.
Die Tabellen sind virtuell: Sie werden nur in dem Moment mit Daten gefüllt, wenn der Benutzer sie abfragt.
Das ist auch ein guter Grund, warum es sinnlos ist, Trigger für sie zu erstellen!

Der Schlüsselbegriff zum Verständnis der Überwachungsfunktion ist ein _Aktivitäts-Snapshot_.
Die Aktivitätsmomentaufnahme stellt den aktuellen Zustand der Datenbank zu Beginn der Transaktion dar, in der die Überwachungstabellenabfrage ausgeführt wird.
Es liefert viele Informationen über die Datenbank selbst, aktive Verbindungen, Benutzer, vorbereitete Transaktionen, laufende Abfragen und mehr.

Der Snapshot wird erstellt, wenn eine Überwachungstabelle zum ersten Mal abgefragt wird.
Sie wird bis zum Ende der aktuellen Transaktion beibehalten, um eine stabile, konsistente Ansicht für Abfragen über mehrere Tabellen hinweg aufrechtzuerhalten, z. B. eine Master-Detail-Abfrage.
Mit anderen Worten, Monitoring-Tabellen verhalten sich immer so, als ob sie sich in der Isolation `SNAPSHOT TABLE STABILITY` ("`consistency`") befinden, selbst wenn die aktuelle Transaktion mit einer niedrigeren Isolationsstufe gestartet wird.

Um den Snapshot zu aktualisieren, muss die aktuelle Transaktion abgeschlossen und die Überwachungstabellen in einem neuen Transaktionskontext erneut abgefragt werden.

.Zugriffssicherheit
* SYSDBA und der Datenbankbesitzer haben vollen Zugriff auf alle Informationen, die in den Überwachungstabellen verfügbar sind
* Normale Benutzer können Informationen über ihre eigenen Verbindungen sehen;
andere Verbindungen sind für sie nicht sichtbar

[WARNING]
====
In stark belasteten Umgebungen kann das Sammeln von Informationen über die Monitoringtabellen einen negativen Einfluss auf die Systemleistung haben.
====

[[fblangref30-appx05-tbl-montables-de]]
.Liste der Monitoringtabellen
<<fblangref-appx05-monattach-de>>::
Informationen über aktive Datenbankattachments

<<fblangref-appx05-moncallstk-de>>::
Aufrufe des Stack durch aktive Abfragen gespeicherter Prozeduren und Trigger

<<fblangref-appx05-contxtvars-de>>::
Informationen zu benutzerdefinierten Kontextvariablen

<<fblangref-appx05-mondb-de>>::
Informationen über die Datenbank, an die die `CURRENT_CONNECTION` angehängt ist

<<fblangref-appx05-iostats-de>>::
Eingabe-/Ausgabestatistiken

<<fblangref-appx05-memusage-de>>::
Statistiken zur Speichernutzung

<<fblangref-appx05-recstats-de>>::
Recordlevelstatistiken

<<fblangref-appx05-statements-de>>::
Zur Ausführung vorbereitete Anweisungen

<<fblangref-appx05-tablestats-de>>::
Statistiken auf Tabellenebene

<<fblangref-appx05-transacs-de>>::
Gestartete Transaktionen

[[fblangref-appx05-monattach-de]]
== `MON$ATTACHMENTS`

`MON$ATTACHMENTS` zeigt Informationen über aktive Attachments der Datenbank an.

[[fblangref30-appx05-tbl-monattach-de]]
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Spaltenname
^| Datentyp
^| Beschreibung

|MON$ATTACHMENT_ID
|BIGINT
|Verbindungs-Kennung

|MON$SERVER_PID
|INTEGER
|Serverprozess-Kennung

|MON$STATE
|SMALLINT
|Verbindungsstatus:

`0` - Leerlauf (idle) +
`1` - Aktiv (active)

|MON$ATTACHMENT_NAME
|VARCHAR(255)
|Connection String -- der Dateiname und volle Pfad zur primären Datenbankdatei

|MON$USER
|CHAR(31)
|Der Name des Benutzers, der mit diese Verbindung nutzt

|MON$ROLE
|CHAR(31)
|Der angegebene Rollenname zum Zeitpunkt des Verbindungsaufbaus.
Wurde beim Aufbau der Verbindung keine Rolle angegeben, enthält das Feld den Text `NONE`

|MON$REMOTE_PROTOCOL
|VARCHAR(10)
|Name des Remote-Protokolls

|MON$REMOTE_ADDRESS
|VARCHAR(255)
|Remote-Adresse (Adresse und Servername)

|MON$REMOTE_PID
|INTEGER
|Kennung des Client-Prozesses

|MON$CHARACTER_SET_ID
|SMALLINT
|Kennung des Zeichensatzes (vgl. `RDB$CHARACTER_SET` in der Systemtabelle `RDB$TYPES`)

|MON$TIMESTAMP
|TIMESTAMP
|Datum und Zeit zum Zeitpunkt des Verbindungsaufbaus.

|MON$GARBAGE_COLLECTION
|SMALLINT
|Kennzeichen für Garbage Collection (wie in der Attachment DPB definiert): 1=erlaubt (allowed), 0=nicht erlaubt (not allowed)

|MON$REMOTE_PROCESS
|VARCHAR(255)
|Der volle Dateiname und Pfad zu der ausführbaren Datei, die diese Verbindung aufgebaut hat

|MON$STAT_ID
|INTEGER
|Statistik-Kennung

|MON$CLIENT_VERSION
|VARCHAR(255)
|Version der Clientbibliothek

|MON$REMOTE_VERSION
|VARCHAR(255)
|Remote-Protokollversion

|MON$REMOTE_HOST
|VARCHAR(255)
|Name des entfernten Hosts

|MON$REMOTE_OS_USER
|VARCHAR(255)
|Name des entfernten Benutzers

|MON$AUTH_METHOD
|VARCHAR(255)
|Name des Authentifizierungs-Plugins, mit dem die Verbindung hergestellt wurde

|MON$SYSTEM_FLAG
|SMALLINT
|Kennzeichen, das den Verbindungstyp angibt:

`0` - normale Verbindung +
`1` - Systemverbindung
|===

.Abrufen von Informationen zu Clientanwendungen
[source]
----
SELECT MON$USER, MON$REMOTE_ADDRESS, MON$REMOTE_PID, MON$TIMESTAMP
FROM MON$ATTACHMENTS
WHERE MON$ATTACHMENT_ID <> CURRENT_CONNECTION
----

[[fblangref-appx05-monattach-kill-de]]
=== Verwendung von `MON$ATTACHMENTS` um eine Verbindung zu beenden

Monitoringtabellen sind nur-lesend.
Jedoch hat der Server einen eingebauten Mechanismus, um Datensätze zu löschen (und nur zum Löschen) in der Tabelle MON$ATTACHMENTS, wodurch es möglich wird, Datenbankverbindungen zu beenden. 

.Hinweise
[NOTE]
====
* Sämtliche Aktivitäten der beendeten Verbindung werden augenblicklich gestoppt und alle aktiven Transaktionen werden zurückgerollt
* Die beendete Verbindung gibt einen Fehler mit dem Code `isc_att_shutdown` zurück
* Versuche diese Verbindung weiterzuverwenden, wird ebenfalls Fehler zurückgeben.
* Das Beenden von Systemverbindungen (`MON$SYSTEM_FLAG = 1`) ist nicht möglich.
Der Server überspringt Systemverbindungen in einem `DELETE FROM MON$ATTACHMENTS`.
====

Alle Verbindungen außer der eigenen (current) beenden:
[source]
----
DELETE FROM MON$ATTACHMENTS
WHERE MON$ATTACHMENT_ID <> CURRENT_CONNECTION
----

[[fblangref-appx05-moncallstk-de]]
== `MON$CALL_STACK`

`MON $ CALL_STACK` zeigt Aufrufe des Stacks von Abfragen an, die in gespeicherten Prozeduren und Triggern ausgeführt werden.

[[fblangref30-appx05-tbl-moncallstk-de]]
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Spaltenname
^| Datentyp
^| Beschreibung

|MON$CALL_ID
|BIGINT
|Aufruf-Kennung

|MON$STATEMENT_ID
|BIGINT
|Der Bezeichner der SQL-Anweisung der obersten Ebene, die die Aufrufkette initiiert hat.
Verwenden Sie diesen Bezeichner, um die Datensätze zur aktiven Anweisung in der Tabelle `MON$STATEMENTS` zu finden

|MON$CALLER_ID
|INTEGER
|Die Kennung der aufrufenden Stored Procedure oder des aufrufenden Triggers

|MON$OBJECT_NAME
|CHAR(31)
|PSQL-Objekt-Name (Module)

|MON$OBJECT_TYPE
|SMALLINT
|PSQL-Objekt-Typ (Trigger oder Stored Procedure):

`2` - Trigger +
`5` - Stored Procedure
`15` - Stored Function

|MON$TIMESTAMP
|TIMESTAMP
|Datum und Zeitpunkt des Aufrufs

|MON$SOURCE_LINE
|INTEGER
|Die Zeilennummer im SQL-Statement, welches zum Zeitpunkt des Snapshots gestartet wurde

|MON$SOURCE_COLUMN
|INTEGER
|Die Spaltennummer im SQL-Statement, welches zum Zeitpunkt des Snapshots gestartet wurde

|MON$STAT_ID
|INTEGER
|Statistik-Kennung

|MON$PACKAGE_NAME
|CHAR(31)
|Paketname für gespeicherte Prozeduren oder Funktionen in einem Paket
|===

[NOTE]
====
Informationen über Aufrufe während der Ausführung der `EXECUTE STATEMENT`-Anweisung gelangen nicht in die Aufrufliste.
====

.Rufen Sie die Aufrufliste für alle Verbindungen außer Ihren eigenen ab
[source]
----
WITH RECURSIVE
  HEAD AS (
    SELECT
      CALL.MON$STATEMENT_ID, CALL.MON$CALL_ID,
      CALL.MON$OBJECT_NAME, CALL.MON$OBJECT_TYPE
    FROM MON$CALL_STACK CALL
    WHERE CALL.MON$CALLER_ID IS NULL
    UNION ALL
    SELECT
      CALL.MON$STATEMENT_ID, CALL.MON$CALL_ID,
      CALL.MON$OBJECT_NAME, CALL.MON$OBJECT_TYPE
    FROM MON$CALL_STACK CALL
      JOIN HEAD ON CALL.MON$CALLER_ID = HEAD.MON$CALL_ID
  )
SELECT MON$ATTACHMENT_ID, MON$OBJECT_NAME, MON$OBJECT_TYPE
FROM HEAD
  JOIN MON$STATEMENTS STMT ON STMT.MON$STATEMENT_ID = HEAD.MON$STATEMENT_ID
WHERE STMT.MON$ATTACHMENT_ID <> CURRENT_CONNECTION
----

[[fblangref-appx05-contxtvars-de]]
== `MON$CONTEXT_VARIABLES`

`MON$CONTEXT_VARIABLES` zeigt Infos über benutzerdefinierte Kontextvariablen an.

[[fblangref30-appx05-tbl-contxtvars-de]]
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Spaltenname
^| Datentyp
^| Beschreibung

|MON$ATTACHMENT_ID
|INTEGER
|Verbindungskennung.
Gültiger Wert nur für Variablen auf Verbindungsebene.
Für Transaktionsebenen ist der Variablenwert `NULL`.

|MON$TRANSACTION_ID
|BIGINT
|Transaktionskennung.
Gültiger Wert nur auf Transaktionsebene.
Für Verbindungsebenen ist der Variablenwert `NULL`.

|MON$VARIABLE_NAME
|VARCHAR(80)
|Name der Kontextvariable

|MON$VARIABLE_VALUE
|VARCHAR(255)
|Wert der Kontextvariable
|===

.Abrufen aller Sitzungskontextvariablen für die aktuelle Verbindung
[source]
----
SELECT
  VAR.MON$VARIABLE_NAME,
  VAR.MON$VARIABLE_VALUE
FROM MON$CONTEXT_VARIABLES VAR
WHERE VAR.MON$ATTACHMENT_ID = CURRENT_CONNECTION
----

[[fblangref-appx05-mondb-de]]
== MON$DATABASE

`MON$DATABASE` zeigt Header-Daten der Datenbank an, mit der der aktuelle Benutzer verbunden ist.

[[fblangref30-appx05-tbl-mondb-de]]
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Spaltenname
^| Datentyp
^| Beschreibung

|MON$DATABASE_NAME
|VARCHAR(255)
|Name und voller Pfad der primären Datenbankdatei oder der Datenbank-Alias.

|MON$PAGE_SIZE
|SMALLINT
|Datenbank Seitengröße in Bytes.

|MON$ODS_MAJOR
|SMALLINT
|Haupt-ODS-Version, z.B. 11

|MON$ODS_MINOR
|SMALLINT
|Unter-ODS-Version, z.B. 2

|MON$OLDEST_TRANSACTION
|INTEGER
|Nummer der ältesten (relevanten) Transaktion (oldest [interesting] transaction (OIT))

|MON$OLDEST_ACTIVE
|INTEGER
|Nummer der ältesten aktiven Transaktion (oldest active transaction (OAT))

|MON$OLDEST_SNAPSHOT
|INTEGER
|Nummer der Transaktion, die zum Zeitpunkt der OAT aktiv war - älteste Snapshot Transaktion (oldest snapshot transaction (OST))

|MON$NEXT_TRANSACTION
|INTEGER
|Nummer der nächsten Transaktion zum Zeitpunkt als der Monitoring-Snapshot erstellt wurde

|MON$PAGE_BUFFERS
|INTEGER
|Die Anzahl der Seiten, die im Speicher für den Datenbank Seiten-Cache (page cache) zugewiesen wurden

|MON$SQL_DIALECT
|SMALLINT
|SQL-Dialekt der Datenbank: 1 oder 3

|MON$SHUTDOWN_MODE
|SMALLINT
|Der derzeitige Shutdown-Status der Datenbank:

`0` - Die Datenbank ist online +
`1` - Multi-User Shutdown +
`2` - Single-User Shutdown +
`3` - Kompletter Shutdown

|MON$SWEEP_INTERVAL
|INTEGER
|Sweep-Intervall

|MON$READ_ONLY
|SMALLINT
|Dieses Kennzeichen gibt an, ob die Datenbank im Modus read-only (Wert 1) oder read-write (Wert 0) arbeitet.

|MON$FORCED_WRITES
|SMALLINT
|Gibt an, ob der Schreibmodus der Datenbank auf synchrones Schreiben (forced writes ON, Wert ist 1) oder asynchrones Schreiben (forced writes OFF, Wert ist 0) gestellt ist

|MON$RESERVE_SPACE
|SMALLINT
|Gibt an, ob reserve_space (Wert 1) oder use_all_space (Wert 0) zum Füllen der Datenbankseiten verwendet wird.

|MON$CREATION_DATE
|TIMESTAMP
|Datum und Zeit zu der die Datenbank erstellt oder wiederhergestellt wurde.

|MON$PAGES
|BIGINT
|Anzahl der zugewiesenen Seiten der Datenbank auf einem externen Gerät

|MON$STAT_ID
|INTEGER
|Statistik-Kennung

|MON$BACKUP_STATE
|SMALLINT
|Derzeitiger physikalischer Backup-Status (nBackup):

`0` - normal +
`1` - stalled +
`2` - merge

|MON$CRYPT_PAGE
|BIGINT
|Anzahl verschlüsselter Seiten

|MON$OWNER
|CHAR(31)
|Benutzername des Datenbankbesitzers

|MON$SEC_DATABASE
|CHAR(7)
|Zeigt an, welcher Typ von Sicherheitsdatenbank verwendet wird:

`Default` - Standard-Sicherheitsdatenbank, d. h. security3.fdb +
`Self` - aktuelle Datenbank wird als Sicherheitsdatenbank verwendet +
`Sonstige` - eine andere Datenbank wird als Sicherheitsdatenbank verwendet (nicht sie selbst oder security3.fdb)
|===

[[fblangref-appx05-iostats-de]]
== `MON$IO_STATS`

`MON$IO_STATS` zeigt Input/Output-Statistiken an.
Die Zähler arbeiten kumulativ, gruppiert für jede Statistikgruppe.

[[fblangref30-appx05-tbl-iostats-de]]
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Spaltenname
^| Datentyp
^| Beschreibung

|MON$STAT_ID
|INTEGER
|Statistik-Kennung

|MON$STAT_GROUP
|SMALLINT
|Statistik-Gruppe:

`0` - Datenbank +
`1` - Verbindung +
`2` - Transaktion +
`3` - Statement +
`4` - Aufruf (Call)

|MON$PAGE_READS
|BIGINT
|Anzahl der gelesenen Datenbankseiten

|MON$PAGE_WRITES
|BIGINT
|Anzahl der geschriebenen Datenbankseiten

|MON$PAGE_FETCHES
|BIGINT
|Anzahl der geholten (fetched) Datenbankseiten

|MON$PAGE_MARKS
|BIGINT
|Anzahl der markierten Datenbankseiten
|===

[[fblangref-appx05-memusage-de]]
== `MON$MEMORY_USAGE`

`MON$MEMORY_USAGE` zeigt Statistiken zu Speichernutzung an.

[[fblangref30-appx05-tbl-memusage-de]]
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Spaltenname
^| Datentyp
^| Beschreibung

|MON$STAT_ID
|INTEGER
|Statistik-Kennung

|MON$STAT_GROUP
|SMALLINT
|Statistik-Gruppen:

`0` - Datenbank +
`1` - Verbindung +
`2` - Transaktion +
`3` - Statement +
`4` - Aufruf (Call)

|MON$MEMORY_USED
|BIGINT
|Die Größe des genutzten Speichers in Bytes.
Diese Daten beziehen sich auf die höchste Speicherzuteilung, die vom Server abgerufen wird.
Dies ist nützlich, um Speicherlecks und exzessiven Speicherverbrauch in Verbindungen, Prozeduren, etc. zu ermitteln.

|MON$MEMORY_ALLOCATED
|BIGINT
|Die vom Betriebssystem zugewiesene Speichermenge in Byte.
Diese Daten beziehen sich auf die Low-Level-Speicherzuweisung, die vom Firebird-Speichermanager durchgeführt wird - die vom Betriebssystem zugewiesene Speichermenge -, mit der Sie die physische Speichernutzung steuern können.

|MON$MAX_MEMORY_USED
|BIGINT
|Der größte Speicherverbrauch für dieses Objekt in Bytes.

|MON$MAX_MEMORY_ALLOCATED
|BIGINT
|Die größte Speicherreservierung für dieses Objekt durch das Betriebssystem in Bytes.
|===

[NOTE]
====
Zähler, die den Datensätzen auf Datenbankebene `MON$DATABASE` (`MON$STAT_GROUP = 0`) zugeordnet sind, zeigen die Speicherzuweisung für alle Verbindungen an.
In Classic und SuperClassic zeigen Nullwerte der Zähler an, dass diese Architekturen keinen gemeinsamen Cache haben.

Kleinere Speicherzuweisungen werden hier nicht gesammelt, sondern stattdessen dem Datenbankspeicherpool hinzugefügt.
====

.Erhalten von 10 Anfragen, die den meisten Speicher verbrauchen
[source]
----
SELECT
  STMT.MON$ATTACHMENT_ID,
  STMT.MON$SQL_TEXT,
  MEM.MON$MEMORY_USED
FROM MON$MEMORY_USAGE MEM
NATURAL JOIN MON$STATEMENTS STMT
ORDER BY MEM.MON$MEMORY_USED DESC
FETCH FIRST 10 ROWS ONLY
----

[[fblangref-appx05-recstats-de]]
== `MON$RECORD_STATS`

`MON$RECORD_STATS` zeigt Statistiken auf Datensatzebene an.
Die Zähler sind kumulativ nach Gruppe für jede Statistikgruppe.

[[fblangref30-appx05-tbl-recstats-de]]
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Spaltenname
^| Datentyp
^| Beschreibung

|MON$STAT_ID
|INTEGER
|Statistik-Kennung

|MON$STAT_GROUP
|SMALLINT
|Statistik-Gruppen:

`0` - Datenbank +
`1` - Verbindung +
`2` - Transaktion +
`3` - Statement +
`4` - Aufruf (Call)

|MON$RECORD_SEQ_READS
|BIGINT
|Anzahl der sequenziell gelesenen Datensätze

|MON$RECORD_IDX_READS
|BIGINT
|Anzahl der mittels Index gelesenen Datensätze

|MON$RECORD_INSERTS
|BIGINT
|Anzahl der eingefügten Datensätze

|MON$RECORD_UPDATES
|BIGINT
|Anzahl der aktualisierten Datensätze

|MON$RECORD_DELETES
|BIGINT
|Anzahl der gelöschten Datensätze

|MON$RECORD_BACKOUTS
|BIGINT
|Anzahl der Datensätze für die eine neue primäre Datensatzversion während eines Rollbacks oder Savepoint-Undo erstellt wurde.

|MON$RECORD_PURGES
|BIGINT
|Anzahl der Datensätze für die die Versionskette nicht länger von der OAT (oldest active transaction) oder jüngeren Transaktionen benötigt wird.

|MON$RECORD_EXPUNGES
|BIGINT
|Anzahl der Datensätze, in denen die Versionskette aufgrund von Löschungen innerhalb von Transaktionen gelöscht wird, die älter als die OAT (oldest active transaction) sind

|MON$RECORD_LOCKS
|BIGINT
|Anzahl gesperrter Datensätze records

|MON$RECORD_WAITS
|BIGINT
|Anzahl der Aktualisierungs-, Lösch- oder Sperrversuche für Datensätze, die anderen aktiven Transaktionen gehören.
Die Transaktion befindet sich im `WAIT`-Modus.

|MON$RECORD_CONFLICTS
|BIGINT
|Anzahl der erfolglosen Aktualisierungs-, Lösch- oder Sperrversuche für Datensätze, die anderen aktiven Transaktionen gehören.
Diese werden als Aktualisierungskonflikte gemeldet.

|MON$BACKVERSION_READS
|BIGINT
|Anzahl der gelesenen Back-Versionen, um sichtbare Datensätze zu finden

|MON$FRAGMENT_READS
|BIGINT
|Anzahl der gelesenen fragmentierten Datensätze

|MON$RECORD_RPT_READS
|BIGINT
|Anzahl der wiederholten Lesevorgänge von Datensätzen
|===

[[fblangref-appx05-statements-de]]
== `MON$STATEMENTS`

`MON$STATEMENTS` zeigt Anweisungen an, die zur Ausführung vorbereitet sind.

[[fblangref30-appx05-tbl-statements-de]]
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Spaltenname
^| Datentyp
^| Beschreibung

|MON$STATEMENT_ID
|INTEGER
|Statement-Kennung

|MON$ATTACHMENT_ID
|INTEGER
|Verbindungs-Kennung

|MON$TRANSACTION_ID
|INTEGER
|Transaktions-Kennung

|MON$STATE
|SMALLINT
|Statement-Status:

`0` - Leerlauf (idle) +
`1` - Aktiv +
`2` - verzögert (stalled)

|MON$TIMESTAMP
|TIMESTAMP
|Der Zeitpunkt an dem das Statement vorbereitet wurde.

|MON$SQL_TEXT
|BLOB TEXT
|Statement-Text in SQL

|MON$STAT_ID
|INTEGER
|Statistik-Kennung

|MON$EXPLAINED_PLAN
|BLOB TEXT
|Erklärter Ausführungsplan
|===

Der Status STALLED zeigt an, dass die Anweisung zum Zeitpunkt des Snapshots einen geöffneten Cursor hatte und darauf wartete, dass der Client den Abruf von Zeilen wieder aufnimmt.

.Aktive Abfragen anzeigen, ausgenommen diejenigen, die in Ihrer Verbindung ausgeführt werden
[source]
----
SELECT
  ATT.MON$USER,
  ATT.MON$REMOTE_ADDRESS,
  STMT.MON$SQL_TEXT,
  STMT.MON$TIMESTAMP
FROM MON$ATTACHMENTS ATT
JOIN MON$STATEMENTS STMT ON ATT.MON$ATTACHMENT_ID = STMT.MON$ATTACHMENT_ID
WHERE ATT.MON$ATTACHMENT_ID <> CURRENT_CONNECTION
AND STMT.MON$STATE = 1
----

[[fblangref-appx05-statements01-de]]
=== Verwenden von `MON$STATEMENTS` zum Abbrechen einer Abfrage

Überwachungstabellen sind schreibgeschützt.
Der Server verfügt jedoch über einen eingebauten Mechanismus zum Löschen (und nur zum Löschen) von Datensätzen in der Tabelle `MON$STATEMENTS`, der es ermöglicht, eine laufende Abfrage abzubrechen.

.Anmerkungen
[NOTE]
====
* Wenn derzeit keine Anweisungen in der Verbindung ausgeführt werden, wird jeder Versuch, Abfragen abzubrechen, nicht fortgesetzt
* Nachdem eine Abfrage abgebrochen wurde, wird beim Aufrufen von API-Funktionen zum Ausführen/Abrufen ein Fehler mit dem Code `isc_cancelled` zurückgegeben
* Nachfolgende Abfragen von dieser Verbindung werden wie gewohnt fortgesetzt
* Der Abbruch der Anweisung erfolgt nicht synchron, sondern markiert nur die Anforderung der Stornierung, und die Stornierung selbst erfolgt asynchron durch den Server
====

.Beispiel
Alle aktiven Abfragen für die angegebene Verbindung abbrechen:

[source]
----
DELETE FROM MON$STATEMENTS
  WHERE MON$ATTACHMENT_ID = 32
----

[[fblangref-appx05-tablestats-de]]
== `MON$TABLE_STATS`

`MON$TABLE_STATS` gibt Statistiken auf Tabellenebene aus.

[[fblangref30-appx05-tbl-tablestats-de]]
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Spaltenname
^| Datentyp
^| Beschreibung

|MON$STAT_ID
|INTEGER
|Statistikkennung

|MON$STAT_GROUP
|SMALLINT
|Statistikgruppe:

`0` - Datenbank +
`1` - Verbindung +
`2` - Transaktion +
`3` - Anweisung (Statement) +
`4` - Aufruf (Call)

|MON$TABLE_NAME
|CHAR(31)
|Tabellenname

|MON$RECORD_STAT_ID
|INTEGER
|Link zu `MON$RECORD_STATS`
|===

.Statistiken auf Datensatzebene für jede Tabelle für die aktuelle Verbindung abrufen
[source]
----
SELECT
  t.mon$table_name,
  r.mon$record_inserts,
  r.mon$record_updates,
  r.mon$record_deletes,
  r.mon$record_backouts,
  r.mon$record_purges,
  r.mon$record_expunges,
  ------------------------
  r.mon$record_seq_reads,
  r.mon$record_idx_reads,
  r.mon$record_rpt_reads,
  r.mon$backversion_reads,
  r.mon$fragment_reads,
  ------------------------
  r.mon$record_locks,
  r.mon$record_waits,
  r.mon$record_conflicts,
  ------------------------
  a.mon$stat_id
FROM mon$record_stats r
JOIN mon$table_stats t ON r.mon$stat_id = t.mon$record_stat_id
JOIN mon$attachments a ON t.mon$stat_id = a.mon$stat_id
WHERE a.mon$attachment_id = CURRENT_CONNECTION
----

[[fblangref-appx05-transacs-de]]
== `MON$TRANSACTIONS`

`MON$TRANSACTIONS` meldet gestartete Transaktionen.

[[fblangref30-appx05-tbl-transacs-de]]
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Spaltenname
^| Datentyp
^| Beschreibung

|MON$TRANSACTION_ID
|INTEGER
|Transaktionskennung

|MON$ATTACHMENT_ID
|INTEGER
|Verbindungskennung

|MON$STATE
|SMALLINT
|Transaktionsstatus:

`0` - Leerlauf (idle) +
`1` - Aktiv

|MON$TIMESTAMP
|TIMESTAMP
|Zeitpunkt an dem die Transaktion gestartet wurde

|MON$TOP_TRANSACTION
|INTEGER
|Top-Level-Transaktionsnummer (Kennung)

|MON$OLDEST_TRANSACTION
|INTEGER
|Kennung der ältesten relevanten Transaktion (oldest [interesting] transaction (OIT))

|MON$OLDEST_ACTIVE
|INTEGER
|Kennung der ältesten aktiven Transaktion (oldest active transaction (OAT))

|MON$ISOLATION_MODE
|SMALLINT
|Isolationsmodus (Level):

`0` - Konsistenz (Snapshot für Tabellenstabilität) +
`1` - Konkurrierend (Snapshot) +
`2` - Read Committed mit Datensatzversion +
`3` - Read Committed ohne Datensatzversion

|MON$LOCK_TIMEOUT
|SMALLINT
|Lock-Timeout:

`-1` - warten (ewig) +
`0` - nicht warten +
`1` oder größer - Lock-Timeout in Sekunden

|MON$READ_ONLY
|SMALLINT
|Gibt an, ob die Transaktion nur-lesend (Wert 1) oder lesend-schreibend (Wert 0) läuft

|MON$AUTO_COMMIT
|SMALLINT
|Gibt an, ob automatisches Commit für die Transaktion verwendet wird (Wert 1) oder nicht (Wert 0)

|MON$AUTO_UNDO
|SMALLINT
|Gibt an, ob der Logging-Mechanismus _automatiches Undo_ für die Transaktion verwendet wird (Wert 1) oder nicht (Wert 0)

|MON$STAT_ID
|INTEGER
|Statistikkennung
|===

.Alle Verbindungen abrufen, die Read Write-Transaktionen mit Isolationsstufe über Read Committed starten
[source]
----
SELECT DISTINCT a. *
FROM mon$attachments a
JOIN mon$transactions t ON a.mon$attachment_id = t.mon$attachment_id
WHERE NOT (t.mon$read_only = 1 AND t.mon$isolation_mode >= 2)
----

:sectnums:
