[[fblangref30-intro-de]]
= Über die Firebird 3.0-Sprachreferenz

Diese Sprachreferenz beschreibt die von Firebird 3.0 unterstützte SQL-Sprache.

Diese Firebird SQL Sprachreferenz ist das zweite zusammenhängende Dokument, das alle Aspekte der Abfragesprache betrachtet, die von Entwicklern für die Kommunikation ihrer Anwendungen mit dem Firebird Relation Database Management System benötigt werden.

[[fblangref30-intro-subject-de]]
== Thema

Das Kernthema dieses Dokuments ist die vollständige Implementierung der SQL-Abfragesprache.
Firebird entspricht weitestgehend den internationalen Standards für SQL in Bezug auf Datentypen, Datenspeicherstrukturen, Mechanismen zur referentiellen Integrität sowie Fähigkeiten zur Datenmanipulation und Zugriffsrechte.
Firebird beinhaltet außerdem eine robuste Prozedursprache -- procedural SQL (PSQL) -- für gespeicherte Prozeduren, Trigger und dynamisch ausführbare Code Blöcke.
Dies sind die Themen, die in diesem Dokument behandelt werden. 

[[fblangref30-intro-authors-de]]
== Urheberschaft

Für die Firebird 3.0-Version wurde die _Firebird 2.5-Sprachreferenz_ als Basis verwendet, und Firebird 3.0-Informationen wurden basierend auf den Firebird 3.0-Versionshinweisen, der Funktionsdokumentation und der russischen Firebird 3.0-Sprachreferenz hinzugefügt.
Dieses Dokument ist jedoch keine direkte Übersetzung der russischen Firebird 3.0-Sprachreferenz.

[[fblangref30-intro-contributors-de]]
=== Mitwirkende

[float]
==== Direkter Inhalt

* Dmitry Filippov (Autor)
* Alexander Karpeykin (Autor)
* Alexey Kovyazin (Autor, Editor)
* Dmitry Kuzmenko (Autor, Editor)
* Denis Simonov (Autor, Editor)
* Paul Vinkenoog (Autor, Designer)
* Dmitry Yemanov (Autor)
* Mark Rotteveel (Autor)

[float]
==== Ressourcen Inhalt

* Adriano dos Santos Fernandes
* Alexander Peshkov
* Vladyslav Khorsun
* Claudio Valderrama
* Helen Borrie
* und andere

[float]
==== Übersetzungen

* Martin Köditz, it & synergy GmbH

[[fblangref30-acknowledgements-de]]
== Anmerkungen


[float]
[[sponsors-donors-de]]
==== Sponsoren und andere Spender

[float]
[[sponsors01-native-de]]
===== Sponsoren der russischen Sprachreferenz

* https://www.moex.com[Moscow Exchange] (Russland)
+
_Moscow Exchange ist die größte Börse in Russland sowie Osteuropa, gegründet am 19. Dezember 2011, durch den Zusammenschluss der Börsengruppen MICEX (gegründet 1992) und RTS (gegründet 1995).
Moscow Exchange zählt zu den 20 weltweit führenden Börsen im Handel von Anleihen und Aktien,
als zu den 10 größten Börsenplattformen für Handelsderivate._

* https://www.ib-aid.com[IBSurgeon] (https://ibase.ru[ibase.ru]) (Russland)
+
_Technischer Support und Entwickler administrativer Tools für das Firebird DBMS._

[[fblangref30-contributing-de]]
== Beitragen

Es gibt verschiedene Möglichkeiten, wie Sie zur Dokumentation von Firebird oder Firebird im Allgemeinen beitragen können:

* Nehmen Sie an den Mailinglisten teil (siehe https://www.firebirdsql.org/en/mailing-lists/)
* Melden Sie Fehler oder senden Sie Pull-Anfragen auf GitHub (https://github.com/FirebirdSQL/)
* Werden Sie Entwickler (für Dokumentationen kontaktieren Sie uns unter firebird-docs, für Firebird im Allgemeinen verwenden Sie die Firebird-Entwickler-Mailingliste)
* Spenden Sie an die Firebird Foundation (siehe https://www.firebirdsql.org/en/donate/)
* Werden Sie zahlendes Mitglied oder Sponsor der Firebird Foundation (siehe
https://www.firebirdsql.org/en/firebird-foundation/)