:!sectnums:

[appendix]
[[fblangref30-appx06-sectables-de]]
= Sicherheitstabellen

Die Namen der Sicherheitstabellen haben `SEC$` als Präfix.
Sie zeigen Daten aus der aktuellen Sicherheitsdatenbank an.
Diese Tabellen sind virtuell in dem Sinne, dass vor dem Zugriff durch den Benutzer keine Daten in ihnen aufgezeichnet werden.
Sie werden zum Zeitpunkt der Benutzeranfrage mit Daten gefüllt.
Die Beschreibungen dieser Tabellen sind jedoch ständig in der Datenbank vorhanden.
In diesem Sinne sind diese virtuellen Tabellen wie Tabellen der `MON$`-Familie, die zur Überwachung des Servers verwendet werden.

.Sicherheit
* SYSDBA, Benutzer mit der Rolle `RDB$ADMIN` in der Sicherheitsdatenbank und der aktuellen Datenbank sowie der Besitzer der Sicherheitsdatenbank haben vollen Zugriff auf alle von den Sicherheitstabellen bereitgestellten Informationen.
* Reguläre Benutzer können nur Informationen über sich selbst sehen, andere Benutzer sind nicht sichtbar.

[IMPORTANT]
====
Diese Funktionen sind stark vom Benutzerverwaltungs-Plugin abhängig.
Beachten Sie, dass einige Optionen ignoriert werden, wenn Benutzer eines Legacy-Steuerelement-Plugins verwenden.
====

[[fblangref30-appx06-tbl-sectables-de]]
.Liste der Sicherheitstabellen
<<fblangref30-appx06-dbcreators-de>>::
Listet Benutzer und Rollen auf, denen das Privileg `CREATE DATABASE` gewährt wurde

<<fblangref30-appx06-authmapping-de>>::
Informationen zu globalen Authentifizierungszuordnungen

<<fblangref30-appx06-users-de>>::
Listet Benutzer in der aktuellen Sicherheitsdatenbank auf

`SEC$USER_ATTRIBUTES`::
Zusätzliche Attribute von Benutzern

[[fblangref30-appx06-dbcreators-de]]
== `SEC$DB_CREATORS`

Listet Benutzer und Rollen auf, denen die Berechtigung `CREATE DATABASE` zugewiesen wurde.

[[fblangref30-appx06-tbl-dbcreators-de]]
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Spaltenname
^| Datentyp
^| Beschreibung

|SEC$USER
|CHAR(31)
|Name des Benutzers oder der Rolle

|SEC$USER_TYPE
|SMALLINT
|Benutzerart

`8` - Benutzer +
`13` - Rolle
|===

[[fblangref30-appx06-authmapping-de]]
== `SEC$GLOBAL_AUTH_MAPPING`

Listet Benutzer und Rollen auf, denen die Berechtigung `CREATE DATABASE` zugewiesen wurde.

// Synchronisieren Sie die Spaltenbeschreibung mit fblangref30-appx04-tbl-authmapping

[[fblangref30-appx06-tbl-authmapping-de]]
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Spaltenname
^| Datentyp
^| Beschreibung

|SEC$MAP_NAME
|CHAR(31)
|Name der Zuweisung

|SEC$MAP_USING
|CHAR(1)
|Verwendete Definitionen

`P` - Plugin (spezifisch oder beliebig) +
`S` - jedes Plugin serverweit +
`M` - Zuordnung (Mapping) +
`{asterisk}` - jede Methode

|SEC$MAP_PLUGIN
|CHAR(31)
|Die Zuordnung gilt für Authentifizierungsinformationen von diesem bestimmten Plugin

|SEC$MAP_DB
|CHAR(31)
|Die Zuordnung gilt für Authentifizierungsinformationen aus dieser speziellen Datenbank

|SEC$MAP_FROM_TYPE
|CHAR(31)
|Der Typ des Authentifizierungsobjekts (definiert durch das Plugin), von dem die Zuordnung erfolgen soll, oder `{asterisk}` für jeden Typ

|SEC$MAP_FROM
|CHAR(255)
|Der Name des Authentifizierungsobjekts, von dem eine Zuordnung vorgenommen werden soll

|SEC$MAP_TO_TYPE
|SMALLINT Nullable
|Der Typ, dem zugeordnet werden soll

`0` - `Benutzer` +
`1` - `Rolle`

|SEC$MAP_TO
|CHAR(31)
|Der Name, dem zugeordnet werden soll
|===

[[fblangref30-appx06-users-de]]
== `SEC$USERS`

Listet Benutzer in der aktuellen Sicherheitsdatenbank auf.

[[fblangref30-appx06-tbl-users-de]]
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Column Name
^| Data Type
^| Beschreibung

|SEC$USER_NAME
|CHAR(31)
|Benutzername

|SEC$FIRST_NAME
|VARCHAR(32)
|Vorname

|SEC$MIDDLE_NAME
|VARCHAR(32)
|Zusatzname

|SEC$LAST_NAME
|VARCHAR(32)
|Nachname

|SEC$ACTIVE
|BOOLEAN
|`true` - aktiv, `false` - inaktiv

|SEC$ADMIN
|BOOLEAN
|`true` - Benutzer hat eine Administratorrolle in der Sicherheitsdatenbank, andernfalls `false`

|SEC$DESCRIPTION
|BLOB TEXT
|Beschreibung (Kommentar) zum Benutzer

|SEC$PLUGIN
|CHAR(31)
|Name des Authentifizierungs-Plugins, das diesen Benutzer verwaltet
|===

[IMPORTANT]
====
Es können mehrere Benutzer mit demselben Benutzernamen existieren, die jeweils von einem anderen Authentifizierungs-Plugin verwaltet werden.
====

[[fblangref30-appx06-userattr-de]]
== `SEC$USER_ATTRIBUTES`

Zusätzliche Benutzerattribute

[[fblangref30-appx06-tbl-userattr-de]]
[cols="<4m,<3m,<5", frame="all", options="header",stripes="none"]
|===
^| Spaltenname
^| Datentyp
^| Beschreibung

|SEC$USER_NAME
|CHAR(31)
|Benutzername

|SEC$KEY
|VARCHAR(31)
|Attributname

|SEC$VALUE
|VARCHAR(255)
|Attributwert

|SEC$PLUGIN
|CHAR(31)
|Name des Authentifizierungs-Plugins, das diesen Benutzer verwaltet
|===

.Anzeigen einer Liste von Benutzern und ihren Attributen
[source]
----
SELECT
  U.SEC$USER_NAME AS LOGIN,
  A.SEC$KEY AS TAG,
  A.SEC$VALUE AS "VALUE",
  U.SEC$PLUGIN AS "PLUGIN"
FROM SEC$USERS U
LEFT JOIN SEC$USER_ATTRIBUTES A
  ON U.SEC$USER_NAME = A.SEC$USER_NAME
    AND U.SEC$PLUGIN = A.SEC$PLUGIN;

LOGIN    TAG     VALUE   PLUGIN
======== ======= ======= ===================
SYSDBA   <null>  <null>  Srp
ALEX     B       x       Srp
ALEX     C       sample  Srp
SYSDBA   <null>  <null>  Legacy_UserManager
----
