:sectnums!:

[appendix]
[[fblangref30-appx01-supplement-de]]
= Zusatzinformationen

In diesem Anhang finden Sie Themen, auf die sich Entwickler beziehen können, um das Verständnis für Funktionen oder Änderungen zu verbessern.

[[fblangref30-appx01-supp-rdb-validblr-de]]
== Das Feld `RDB$VALID_BLR`

Das Feld `RDB$VALID_BLR` wurde zu den Systemtabellen `RDB$PROCEDURES` und `RDB$TRIGGERS` in Firebird 2.1 hinzugefügt.
Sein Zweck ist, eine mögliche Ungültigkeit eines PSQL-Moduls nach einer Änderung einer Domäne oder Tabellenspalte, von der das Modul abhängt, zu signalisieren.
`RDB$VALID_BLR` wird auf 0 gesetzt, sobald der Code einer Prozedur oder eines Triggers ungültig durch eine solche Änderung wird.

=== Funktionsweise der Invalidierung

Bei Triggern und Prozeduren ergeben sich Abhängigkeiten durch die Definitionen der Tabellenspalten, auf die zugegriffen wird, und auch über alle Parameter oder Variablen, die im Modul mit der ``TYPE OF``-Klausel definiert wurden.

Nachdem die Engine jede Domain, einschließlich der impliziten Domains, die intern hinter den Spaltendefinitionen und den Ausgabeparametern erstellt wurden, geändert hat, werden alle ihre Abhängigkeiten intern neu kompiliert.

[NOTE]
====
In V.2.x beinhaltet dies Prozeduren und Trigger, jedoch keine Blöcke, die in DML-Anweisungen für die Laufzeitausführung mit `EXECUTE BLOCK` codiert sind.
Firebird 3 umfasst weitere Modultypen (gespeicherte Funktionen, Pakete).
====

Jedes Modul, das aufgrund einer Inkompatibilität aufgrund einer Domänenänderung nicht neu kompiliert werden kann, wird als ungültig markiert ("`invalidated`" durch Setzen von `RDB$VALID_BLR` in seinem System Record (in `RDB$PROCEDURES` oder ``RDB$TRIGGERS ``, wie zutreffend) auf Null.

Eine erneute Validierung (Einstellung von `RDB$VALID_BLR` auf 1) erfolgt, wenn

. die Domäne wird erneut geändert und die neue Definition ist mit der zuvor ungültig gemachten Moduldefinition kompatibel; ODER
. das zuvor ungültig gemachte Modul wird geändert, um der neuen Domänendefinition zu entsprechen

Die folgende Abfrage findet die Module, die von einer bestimmten Domäne abhängen und meldet den Status ihrer `RDB$VALID_BLR`-Felder:

[source]
----
SELECT * FROM (
  SELECT
    'Procedure',
    rdb$procedure_name,
    rdb$valid_blr
  FROM rdb$procedures
  UNION ALL
  SELECT
    'Trigger',
    rdb$trigger_name,
    rdb$valid_blr
  FROM rdb$triggers
) (type, name, valid)
WHERE EXISTS
  (SELECT * from rdb$dependencies
   WHERE rdb$dependent_name = name
     AND rdb$depended_on_name = 'MYDOMAIN')

/* Replace MYDOMAIN with the actual domain name.
   Use all-caps if the domain was created
   case-insensitively. Otherwise, use the exact
   capitalisation. */
----

Die folgende Abfrage zeigt alle Module an, die von einer bestimmten Tabellenspalte abhängig sind, und gibt deren ``RDB$VALID_BLR``-Status aus:

[source]
----
SELECT * FROM (
  SELECT
    'Procedure',
    rdb$procedure_name,
    rdb$valid_blr
  FROM rdb$procedures
  UNION ALL
  SELECT
    'Trigger',
    rdb$trigger_name,
    rdb$valid_blr
  FROM rdb$triggers) (type, name, valid)
WHERE EXISTS
  (SELECT *
   FROM rdb$dependencies
   WHERE rdb$dependent_name = name
     AND rdb$depended_on_name = 'MYTABLE'
     AND rdb$field_name = 'MYCOLUMN')
----

[IMPORTANT]
====
Alle durch Domänen-/Spaltenänderungen verursachten PSQL-Ungültigkeiten werden im Feld `RDB$VALID_BLR` wiedergegeben.
Andere Arten von Änderungen, wie die Anzahl der Eingabe- oder Ausgabeparameter, aufgerufene Routinen usw., wirken sich jedoch nicht auf das Validierungsfeld aus, obwohl sie das Modul möglicherweise ungültig machen.
Ein typisches solches Szenario könnte eines der folgenden sein:

. Es wird eine Prozedur (B) definiert, die eine andere Prozedur (A) aufruft und daraus Ausgabeparameter liest.
In diesem Fall wird eine Abhängigkeit in ``RDB$DEPENDENCIES`` registriert.
Anschließend wird die aufgerufene Prozedur (A) geändert, um einen oder mehrere dieser Ausgabeparameter zu ändern oder zu entfernen.
Die Anweisung `ALTER PROCEDURE A` schlägt mit einem Fehler fehl, wenn ein Commit versucht wird.
. Eine Prozedur (B) ruft Prozedur A auf und liefert Werte für ihre Eingabeparameter.
In ``RDB$DEPENDENCIES`` ist keine Abhängigkeit registriert.
Eine nachträgliche Änderung der Eingabeparameter in Prozedur A ist zulässig.
Ein Fehler tritt zur Laufzeit auf, wenn B A mit dem nicht übereinstimmenden Eingabeparametersatz aufruft.
====

.Weitere Hinweise
[NOTE]
====
* Für PSQL-Module aus früheren Firebird-Versionen (gilt für einige Systemtrigger, sogar wenn die Datenbank unter Firebird 2.1. oder höher erstellt wurde), ist `RDB$VALID_BLR` NULL.
Dies heißt nicht, dass ihre BLR ungültig ist.
* Die _isql_-Befehle `SHOW PROCEDURES` und `SHOW TRIGGERS` zeigen ein Sternchen in der ``RDB$VALID_BLR``-Spalte für alle Module, deren Wert 0 ist (ungültig).
Für `SHOW PROCEDURE <procname>` und `SHOW TRIGGER <trigname>`, welche einzelne PSQL-Module sind, werden gar keien ungültigen BLR signalisiert.
====

[[fblangref30-appx01-note-on-equality-de]]
== Ein Hinweis zur Gleichheit

[IMPORTANT]
====
Diese Anmerkung über Gleichheits- und Ungleichheits-Operatoren gilt überall  in der Firebird SQL-Sprache.
====

Der "```=```"-Operator, welcher ausdrücklich in vielen Bedingungen verwendet wird, prüft nur Werte gegen Werte.
Entsprechend dem SQL-Standard, ist [constant]``NULL`` kein Wert und somit sind zwei [constant]``NULLs`` weder gleich noch ungleich zueinander.
Wenn Sie [constant]``NULLs`` in Bedingungen vergleichen müssen, nutzen Sie den Operator `IS NOT DISTINCT FROM`.
Dieser gibt wahr zurück, falls die Operanden den gleichen Wert besitzen _oder_ beide `NULL` sind.

[source]
----
select *
  from A join B
  on A.id is not distinct from B.code
----

In Fällen in denen Sie gegen [constant]``NULL`` innerhalb einer  __ungleich__-Bedingung testen wollen, nutzen Sie ``IS DISTINCT FROM``, nicht "```<>```".
Möchten Sie [constant]``NULL`` unterschiedlich zu anderen Werten und zwei [constant]``NULLs`` als gleich betrachten:

[source]
----
select *
  from A join B
  on A.id is distinct from B.code
----

:sectnums:
