[[fblangref30-contextvars]]
= Kontextvariablen

[[fblangref30-contextvars-current-connection-de]]
== `CURRENT_CONNECTION`

.Verfügbar in
DSQL, PSQL

.Typ
`INTEGER`

.Syntax
[listing]
----
CURRENT_CONNECTION
----

`CURRENT_CONNECTION` enthält den eindeutigen Bezeichner der aktuellen Verbindung.

Sein Wert wird von einem Zähler auf der Kopfseite der Datenbank abgeleitet, der bei jeder neuen Verbindung inkrementiert wird.
Wenn eine Datenbank wiederhergestellt wird, wird dieser Zähler auf Null zurückgesetzt.

.Beispiele
[source]
----
select current_connection from rdb$database

execute procedure P_Login(current_connection)
----

[[fblangref30-contextvars-current-date-de]]
== `CURRENT_DATE`

.Verfügbar in
DSQL, PSQL, ESQL

.Typ
`DATE`

.Syntax
[listing]
----
CURRENT_DATE
----

`CURRENT_DATE` gibt das aktuelle Serverdatum zurück.

[NOTE]
====
Innerhalb eines PSQL-Moduls (Prozedur, Trigger oder ausführbarer Block) bleibt der Wert von `CURRENT_DATE` bei jedem Lesen konstant.
Wenn mehrere Module sich gegenseitig aufrufen oder auslösen, bleibt der Wert während der Dauer des äußersten Moduls konstant.
Wenn Sie einen fortlaufenden Wert in PSQL benötigen (z. B. um Zeitintervalle zu messen), verwenden Sie <<fblangref30-contextvars-today>>.
====

.Beispiele
[source]
----
select current_date from rdb$database
-- Ergebnis z.B. 2011-10-03
----

[[fblangref30-contextvars-current-role-de]]
== `CURRENT_ROLE`

.Verfügbar in
DSQL, PSQL

.Typ
`VARCHAR(31)`

.Syntax
[listing]
----
CURRENT_ROLE
----

`CURRENT_ROLE` ist eine Kontextvariable, die die Rolle des aktuell verbundenen Benutzers enthält.
Wenn keine aktive Rolle vorhanden ist, ist `CURRENT_ROLE` `'NONE'`.

`CURRENT_ROLE` repräsentiert immer eine gültige Rolle oder `'NONE'`.
Wenn sich ein Benutzer mit einer nicht vorhandenen Rolle verbindet, setzt die Engine sie stillschweigend auf "NONE" zurück, ohne einen Fehler zurückzugeben.

.Beispiel
[source]
----
if (current_role <> 'MANAGER')
  then exception only_managers_may_delete;
else
  delete from Customers where custno = :custno;
----

[[fblangref30-contextvars-current-time-de]]
== `CURRENT_TIME`

.Verfügbar in
DSQL, PSQL, ESQL

.Typ
`TIME`

.Syntax
[listing]
----
CURRENT_TIME [ (<precision>) ]

<precision> ::= 0 | 1 | 2 | 3
----

Das optionale Argument _precision_ wird in ESQL nicht unterstützt.

[[fblangref30-funcs-tbl-current_time-de]]
.CURRENT_TIME Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|precision
|Präzision. 
Der Standardwert ist 0.
In ESQL nicht unterstützt.
|===

`CURRENT_TIME` gibt die aktuelle Serverzeit zurück.
Der Standardwert ist 0 Dezimalstellen, d. h. Sekundengenauigkeit.

[NOTE]
====
* `CURRENT_TIME` hat eine Standardgenauigkeit von 0 Dezimalstellen, wobei `CURRENT_TIMESTAMP` eine Standardgenauigkeit von 3 Dezimalstellen hat.
Daher ist `CURRENT_TIMESTAMP` nicht die genaue Summe von `CURRENT_DATE` und `CURRENT_TIME`, es sei denn, Sie geben explizit eine Genauigkeit an (d. h. `CURRENT_TIME(3)` oder `CURRENT_TIMESTAMP(0)`).
* Innerhalb eines PSQL-Moduls (Prozedur, Trigger oder ausführbarer Block) bleibt der Wert von `CURRENT_TIME` bei jedem Lesen konstant.
Wenn mehrere Module sich gegenseitig aufrufen oder auslösen, bleibt der Wert während der Dauer des äußersten Moduls konstant.
Wenn Sie einen fortlaufenden Wert in PSQL benötigen (z. B. um Zeitintervalle zu messen), verwenden Sie <<fblangref30-contextvars-now-de>>.
====

.`CURRENT_TIME` und Firebird 4 Zeitzonenunterstützung
[WARNING]
====
Firebird 4 unterstützt Zeitzonen.
Als Teil dieser Unterstützung wird es eine Inkompatibilität mit dem `CURRENT_TIME`-Ausdruck geben.

In Firebird 4 gibt `CURRENT_TIME` den neuen Typ `TIME WITH TIME ZONE` zurück.
Damit Ihre Abfragen mit dem Datenbankcode zukünftiger Firebird-Versionen kompatibel sind, hat Firebird 3.0.4 den `LOCALTIME`-Ausdruck eingeführt.
In Firebird 3.0 ist `LOCALTIME` ein Synonym für `CURRENT_TIME`.

In Firebird 4 funktioniert `LOCALTIME` weiterhin wie bisher (und gibt `TIME [WITHOUT TIME ZONE]` zurück), während `CURRENT_TIME` einen anderen Datentyp zurückgibt, `TIME WITH TIME ZONE`.

Sofern Sie nicht in der Lage sein müssen, Ihre Datenbank auf Firebird 3.0.3 oder früher herunterzustufen, empfehlen wir, `LOCALTIME` statt `CURRENT_TIME` zu verwenden.
====

.Beispiele
[source]
----
select current_time from rdb$database
-- Ergebnis z.B. 14:20:19.0000

select current_time(2) from rdb$database
-- Ergebnis z.B. 14:20:23.1200
----

.Siehe auch
<<fblangref30-contextvars-current-timestamp-de>>, <<fblangref30-contextvars-localtime-de>>, <<fblangref30-contextvars-localtimestamp-de>>

[[fblangref30-contextvars-current-timestamp-de]]
== `CURRENT_TIMESTAMP`

.Verfügbar in
DSQL, PSQL, ESQL

.Typ
`TIMESTAMP`

.Syntax
[listing]
----
CURRENT_TIMESTAMP [ (<precision>) ]

<precision> ::= 0 | 1 | 2 | 3
----

Das optionale Argument _precision_ wird in ESQL nicht unterstützt.

[[fblangref30-funcs-tbl-current-timestamp-de]]
.CURRENT_TIMESTAMP Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|precision
|Präzision.
Der Standardwert ist 0.
In ESQL nicht unterstützt.
|===

`CURRENT_TIMESTAMP` gibt das aktuelle Serverdatum und die aktuelle Uhrzeit zurück.
Der Standardwert ist 3 Dezimalstellen, d. h. Millisekunden-Genauigkeit.

[NOTE]
====
* Die Standardgenauigkeit von `CURRENT_TIME` beträgt 0 Dezimalstellen, also ist `CURRENT_TIMESTAMP` nicht die genaue Summe von `CURRENT_DATE` und `CURRENT_TIME`, es sei denn, Sie geben explizit eine Genauigkeit an (zB `CURRENT_TIME(3)` oder `CURRENT_TIMESTAMP(0) `).
* Innerhalb eines PSQL-Moduls (Prozedur, Trigger oder ausführbarer Block) bleibt der Wert von `CURRENT_TIMESTAMP` bei jedem Lesen konstant.
Wenn mehrere Module sich gegenseitig aufrufen oder auslösen, bleibt der Wert während der Dauer des äußersten Moduls konstant.
Wenn Sie einen fortlaufenden Wert in PSQL benötigen (z. B. um Zeitintervalle zu messen), verwenden Sie <<fblangref30-contextvars-now-de>>.
====

.`CURRENT_TIMESTAMP` und Firebird 4 Zeitzonenunterstützung
[WARNING]
====
Firebird 4 unterstützt Zeitzonen.
Als Teil dieser Unterstützung wird es eine Inkompatibilität mit dem `CURRENT_TIMESTAMP`-Ausdruck geben.

In Firebird 4 gibt "CURRENT_TIMESTAMP" den neuen Typ "TIMESTAMP WITH TIME ZONE" zurück.
Damit Ihre Abfragen mit dem Datenbankcode zukünftiger Firebird-Versionen kompatibel sind, hat Firebird 3.0.4 den `LOCALTIMESTAMP`-Ausdruck eingeführt.
In Firebird 3.0 ist `LOCALTIMESTAMP` ein Synonym für `CURRENT_TIMESTAMP`.

In Firebird 4 funktioniert `LOCALTIMESTAMP` weiterhin wie bisher (gibt `TIMESTAMP [WITHOUT TIME ZONE]` zurück), während `CURRENT_TIMESTAMP` einen anderen Datentyp zurückgibt, `TIMESTAMP WITH TIME ZONE`.

Sofern Sie nicht in der Lage sein müssen, Ihre Datenbank auf Firebird 3.0.3 oder früher herunterzustufen, empfehlen wir, `LOCALTIMESTAMP` statt `CURRENT_TIMESTAMP` zu verwenden.
====

.Beispiele
[source]
----
select current_timestamp from rdb$database
-- Ergebnis z.B. 2008-08-13 14:20:19.6170

select current_timestamp(2) from rdb$database
-- Ergebnis z.B. 2008-08-13 14:20:23.1200
----

.Siehe auch
<<fblangref30-contextvars-current-time-de>>, <<fblangref30-contextvars-localtime-de>>, <<fblangref30-contextvars-localtimestamp-de>>

[[fblangref30-contextvars-current-transaction-de]]
== `CURRENT_TRANSACTION`

.Verfügbar in
DSQL, PSQL

.Typ
`BIGINT`

.Syntax
[listing]
----
CURRENT_TRANSACTION
----

`CURRENT_TRANSACTION` enthält die eindeutige Kennung der aktuellen Transaktion.

Sein Wert wird von einem Zähler auf der Kopfseite der Datenbank abgeleitet, der bei jeder neuen Transaktion inkrementiert wird.
Wenn eine Datenbank wiederhergestellt wird, wird dieser Zähler auf Null zurückgesetzt.

.Beispiele
[source]
----
select current_transaction from rdb$database

New.Txn_ID = current_transaction;
----

[[fblangref30-contextvars-current-user-de]]
== `CURRENT_USER`

.Verfügbar in
DSQL, PSQL

.Typ
`VARCHAR(31)`

.Syntax
[listing]
----
CURRENT_USER
----

`CURRENT_USER` ist eine Kontextvariable, die den Namen des aktuell verbundenen Benutzers enthält.
Es ist völlig äquivalent zu <<fblangref30-contextvars-user-de>>.

.Beispiel
[source]
----
create trigger bi_customers for customers before insert as
begin
    New.added_by  = CURRENT_USER;
    New.purchases = 0;
end
----

[[fblangref30-contextvars-deleting-de]]
== `DELETING`

.Verfügbar in
PSQL

.Typ
`BOOLEAN`

.Syntax
[listing]
----
DELETING
----

Nur in Triggern verfügbar, `DELETING` zeigt an, ob der Trigger für eine `DELETE`-Operation ausgelöst wurde.
Vorgesehen für die Verwendung in <<fblangref30-ddl-trgr-relntrigger-rowevent,multi-action triggers-de>>.

.Beispiel
[source]
----
if (deleting) then
begin
  insert into Removed_Cars (id, make, model, removed)
    values (old.id, old.make, old.model, current_timestamp);
end
----

[[fblangref30-contextvars-gdscode-de]]
== `GDSCODE`

.Verfügbar in
PSQL

.Typ
`INTEGER`

.Syntax
[listing]
----
GDSCODE
----

In einem "```WHEN ... DO```"-Fehlerbehandlungsblock enthält die Kontextvariable `GDSCODE` die numerische Darstellung des aktuellen Firebird-Fehlercodes.
Vor Firebird 2.0 wurde `GDSCODE` nur in `WHEN GDSCODE`-Handlern gesetzt.
Jetzt kann es auch in den Blöcken `WHEN ANY`, `WHEN SQLCODE`, `WHEN SQLSTATE` und `WHEN EXCEPTION` ungleich Null sein, vorausgesetzt, die den Fehler auslösende Bedingung entspricht einem Firebird-Fehlercode.
Außerhalb von Fehlerhandlern ist `GDSCODE` immer 0.
Außerhalb von PSQL existiert es überhaupt nicht.

[NOTE]
====
Nach `WHEN GDSCODE` müssen Sie symbolische Namen wie `grant_obj_notfound` usw. verwenden.
Aber die Kontextvariable `GDSCODE` ist ein `INTEGER`.
Wenn Sie es mit einem bestimmten Fehler vergleichen möchten, muss der Zahlenwert verwendet werden, z.
`335544551` für `grant_obj_notfound`.
====

.Beispiel
[source]
----
when gdscode grant_obj_notfound, gdscode grant_fld_notfound,
   gdscode grant_nopriv, gdscode grant_nopriv_on_base
do
begin
  execute procedure log_grant_error(gdscode);
  exit;
end
----

[[fblangref30-contextvars-inserting-de]]
== `INSERTING`

.Verfügbar in
PSQL

.Typ
`BOOLEAN`

.Syntax
[listing]
----
INSERTING
----

Nur in Triggern verfügbar, zeigt `INSERTING` an, ob der Trigger aufgrund einer `INSERT`-Operation ausgelöst wurde.
Vorgesehen für die Verwendung in <<fblangref30-ddl-trgr-relntrigger-rowevent-de,Multi-Action-Trigger>>.
.Beispiel
[source]
----
if (inserting or updating) then
begin
  if (new.serial_num is null) then
    new.serial_num = gen_id(gen_serials, 1);
end
----

[[fblangref30-contextvars-localtime-de]]
== `LOCALTIME`

.Verfügbar in
DSQL, PSQL, ESQL

.Typ
`TIME`

.Syntax
[listing]
----
LOCALTIME [ (<precision>) ]

<precision> ::= 0 | 1 | 2 | 3
----

Das optionale Argument _precision_ wird in ESQL nicht unterstützt.

[[fblangref30-funcs-tbl-localtime-de]]
.`LOCALTIME`-Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|precision
|Präzision.
Der Standardwert ist 0.
In ESQL nicht unterstützt
|===

`LOCALTIME` gibt die aktuelle Serverzeit zurück.
Der Standardwert ist 0 Dezimalstellen, d. h. Sekundengenauigkeit.

[NOTE]
====
* `LOCALTIME` wurde in Firebird 3.0.4 als Alias ​​von `CURRENT_TIME` eingeführt.
In Firebird 4 gibt `CURRENT_TIME` eine `TIME WITH TIME ZONE` anstelle einer `TIME [Without TIME ZONE]` zurück, während `LOCALTIME` weiterhin `TIME [Without TIME ZONE]` zurückgibt.
Es wird empfohlen, von `CURRENT_TIME` auf `LOCALTIME` zu wechseln, um die Vorwärtskompatibilität mit Firebird 4 zu gewährleisten.
* `LOCALTIME` hat eine Standardgenauigkeit von 0 Dezimalstellen, wobei `LOCALTIMESTAMP` eine Standardgenauigkeit von 3 Dezimalstellen hat.
Daher ist `LOCALTIMESTAMP` nicht die genaue Summe von `CURRENT_DATE` und `LOCALTIME`, es sei denn, Sie geben explizit eine Genauigkeit an (d. h. `LOCALTIME(3)` oder `LOCALTIMESTAMP(0)`).
* Innerhalb eines PSQL-Moduls (Prozedur, Trigger oder ausführbarer Block) bleibt der Wert von `LOCALTIME` bei jedem Lesen konstant.
Wenn sich mehrere Module gegenseitig aufrufen oder auslösen, bleibt der Wert während der Dauer des äußersten Moduls konstant.
Wenn Sie in PSQL einen fortlaufenden Wert benötigen (z. B. um Zeitintervalle zu messen), verwenden Sie <<fblangref30-contextvars-now-de>>.====
====

.Beispiele
[source]
----
select localtime from rdb$database
-- Ergebnis z.B. 14:20:19.0000

select localtime(2) from rdb$database
-- Ergebnis z.B. 14:20:23.1200
----

.Siehe auch
<<fblangref30-contextvars-current-time-de>>, <<fblangref30-contextvars-localtimestamp-de>>

[[fblangref30-contextvars-localtimestamp-de]]
== `LOCALTIMESTAMP`

.Verfügbar in
DSQL, PSQL, ESQL

.Typ
`TIMESTAMP`

.Syntax
[listing]
----
LOCALTIMESTAMP [ (<precision>) ]

<precision> ::= 0 | 1 | 2 | 3
----

Das optionale Argument _precision_ wird in ESQL nicht unterstützt.

[[fblangref30-funcs-tbl-localtimestamp-de]]
.`LOCALTIMESTAMP` Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|precision
|Präzision.
Der Standardwert ist 3.
In ESQL nicht unterstützt
|===

`LOCALTIMESTAMP` gibt das aktuelle Serverdatum und die aktuelle Uhrzeit zurück.
Der Standardwert ist 3 Dezimalstellen, d. h. Millisekunden-Genauigkeit.

[NOTE]
====
* `LOCALTIMESTAMP` wurde in Firebird 3.0.4 als Synonym von `CURRENT_TIMESTAMP` eingeführt.
In Firebird 4 gibt `CURRENT_TIMESTAMP` einen `TIMESTAMP WITH TIME ZONE` anstelle eines `TIMESTAMP [Without TIME ZONE]` zurück, während `LOCALTIMESTAMP` weiterhin `TIMESTAMP [OHNE TIME ZONE]` zurückgibt.
Es wird empfohlen, von `CURRENT_TIMESTAMP` zu `LOCALTIMESTAMP` zu wechseln, um die Vorwärtskompatibilität mit Firebird 4 zu gewährleisten.
* Die Standardgenauigkeit von `LOCALTIME` beträgt 0 Dezimalstellen, also ist `LOCALTIMESTAMP` nicht die genaue Summe von `CURRENT_DATE` und `LOCALTIME`, es sei denn, Sie geben explizit eine Genauigkeit an (zB `LOCATIME(3)` oder `LOCALTIMESTAMP(0) `).
* Innerhalb eines PSQL-Moduls (Prozedur, Trigger oder ausführbarer Block) bleibt der Wert von `LOCALTIMESTAMP` bei jedem Lesen konstant.
Wenn sich mehrere Module gegenseitig aufrufen oder auslösen, bleibt der Wert während der Dauer des äußersten Moduls konstant.
Wenn Sie in PSQL einen fortlaufenden Wert benötigen (z. B. um Zeitintervalle zu messen), verwenden Sie <<fblangref30-contextvars-now-de>>.
====

.Beispiele
[source]
----
select localtimestamp from rdb$database
-- Ergebnis z.B. 2008-08-13 14:20:19.6170

select localtimestamp(2) from rdb$database
-- Ergebnis z.B. 2008-08-13 14:20:23.1200
----

.Siehe auch
<<fblangref30-contextvars-current-timestamp-de>>, <<fblangref30-contextvars-localtime-de>>

[[fblangref30-contextvars-new-de]]
== `NEW`

.Verfügbar in
PSQL, nur Trigger

.Typ
Datensatz

.Syntax
[listing,subs=+quotes]
----
NEW.__column_name__
----

[[fblangref30-funcs-tbl-new-de]]
.`NEW`-Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|column_name
|Spaltenname für den Zugriff
|===

`NEU` enthält die neue Version eines Datenbankeintrags, der gerade eingefügt oder aktualisiert wurde.
Ab Firebird 2.0 ist es in 'AFTER'-Triggern schreibgeschützt.

[NOTE]
====
Bei Multi-Action-Triggern -- eingeführt in Firebird 1.5 -- ist `NEU` immer verfügbar.
Wird der Trigger jedoch durch ein `DELETE` ausgelöst, gibt es keine neue Version des Datensatzes.
In dieser Situation wird beim Lesen von `NEW` immer `NULL` zurückgegeben;
das Schreiben in sie führt zu einer Laufzeitausnahme.
====

[[fblangref30-contextvars-now-de]]
== `'NOW'`

.Verfügbar in
DSQL, PSQL, ESQL

.Typ
`CHAR(3)`

`'NOW'` ist keine Variable, sondern ein String-Literal.
Es ist jedoch in dem Sinne besonders, dass Sie, wenn Sie es in einen Datums-/Uhrzeittyp `CAST()` geben, das aktuelle Datum und/oder die aktuelle Uhrzeit erhalten.
Seit Firebird 2.0 beträgt die Genauigkeit 3 Dezimalstellen, also Millisekunden. Bei `'NOW'` wird die Groß-/Kleinschreibung nicht beachtet und die Engine ignoriert führende oder nachfolgende Leerzeichen beim Casting.

[WARNING]
====
Bitte beachten Sie, dass die Abkürzungsausdrücke sofort beim Parsen ausgewertet werden und gleich bleiben, solange die Anweisung vorbereitet ist.
Somit bleibt auch bei mehrfacher Ausführung einer Abfrage der Wert für z.B. "```timestamp 'now'```" ändert sich nicht, egal wie viel Zeit vergeht.
Wenn Sie den Wert benötigen, um fortzufahren (d. h. bei jedem Anruf ausgewertet werden), verwenden Sie eine vollständige Besetzung.
====

[NOTE]
====
* `'NOW'` gibt immer das aktuelle Datum/die aktuelle Uhrzeit zurück, auch in PSQL-Modulen, wo <<fblangref30-contextvars-current-date-de>>, <<fblangref30-contextvars-current-time-de>> und << fblangref30-contextvars-current-timestamp-de>> gibt während der gesamten Dauer der äußersten Routine den gleichen Wert zurück.
Dies macht `'NOW'` zum Messen von Zeitintervallen in Triggern, Prozeduren und ausführbaren Blöcken nützlich.
* Außer in der oben genannten Situation, Lesen von <<fblangref30-contextvars-current-date-de>>, <<fblangref30-contextvars-current-time-de>> und <<fblangref30-contextvars-current-timestamp-de>> ist im Allgemeinen der Übertragung von `'JETZT'` vorzuziehen.
Beachten Sie jedoch, dass `CURRENT_TIME` standardmäßig auf Sekunden genau eingestellt ist; Um eine Genauigkeit in Millisekunden zu erhalten, verwenden Sie `CURRENT_TIME(3)`.
====

.Beispiele
[source]
----
select 'Now' from rdb$database
-- Ergebnis 'Now'

select cast('Now' as date) from rdb$database
-- Ergebnis z.B. 2008-08-13

select cast('now' as time) from rdb$database
-- Ergebnis z.B. 14:20:19.6170

select cast('NOW' as timestamp) from rdb$database
-- Ergebnis z.B. 2008-08-13 14:20:19.6170
----

<<fblangref30-datatypes-convert-shortcasts-de,Kurzformumwandlungen für Datums- und Uhrzeitdatentypen>> für die letzten drei Aussagen:

[source]
----
select date 'Now' from rdb$database
select time 'now' from rdb$database
select timestamp 'NOW' from rdb$database
----

[[fblangref30-contextvars-old-de]]
== `OLD`

.Verfügbar in
PSQL, nur Trigger

.Typ
Datensatz

.Syntax
[listing,subs=+quotes]
----
OLD.__column_name__
----

[[fblangref30-funcs-tbl-old-de]]
.`OLD` Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|column_name
|Spaltenname für den Zugriff
|===

`OLD` enthält die vorhandene Version eines Datenbankeintrags kurz vor einer Löschung oder Aktualisierung.
Ab Firebird 2.0 ist es schreibgeschützt.

[NOTE]
====
Bei Multi-Action-Triggern -- eingeführt in Firebird 1.5 -- ist 'OLD' immer verfügbar.
Wenn der Trigger jedoch durch ein 'INSERT' ausgelöst wird, gibt es offensichtlich keine bereits vorhandene Version des Datensatzes.
In dieser Situation wird beim Lesen von `OLD` immer `NULL` zurückgegeben;
das Schreiben in sie führt zu einer Laufzeitausnahme.
====

[[fblangref30-contextvars-row-count-de]]
== `ROW_COUNT`

.Verfügbar in
PSQL

.Typ
`INTEGER`

.Syntax
[listing]
----
ROW_COUNT
----

Die Kontextvariable `ROW_COUNT` enthält die Anzahl der Zeilen, die von der letzten DML-Anweisung (`INSERT`, `UPDATE`, `DELETE`, `SELECT` oder `FETCH`) im aktuellen Trigger, in der gespeicherten Prozedur oder im ausführbaren Block betroffen sind.

.Verhalten bei `SELECT` und `FETCH`
* Nach einem Singleton `SELECT` ist `ROW_COUNT` 1, wenn eine Datenzeile abgerufen wurde, andernfalls 0.
* In einer `FOR SELECT` Schleife wird `ROW_COUNT` bei jeder Iteration inkrementiert (beginnend bei 0 vor der ersten).
* Nach einem `FETCH` von einem Cursor ist `ROW_COUNT` 1, wenn eine Datenzeile abgerufen wurde, andernfalls 0.
Wenn mehr Datensätze vom gleichen Cursor abgerufen werden, wird `ROW_COUNT` _nicht_ über 1 hinaus erhöht.
* In Firebird 1.5.x ist `ROW_COUNT` 0 nach jeder Art von `SELECT`-Anweisung.

[NOTE]
====
`ROW_COUNT` kann nicht verwendet werden, um die Anzahl der Zeilen zu bestimmen, die von einem `EXECUTE STATEMENT`- oder `EXECUTE PROCEDURE`-Befehl betroffen sind.
====

.Beispiel
[source]
----
update Figures set Number = 0 where id = :id;
if (row_count = 0) then
  insert into Figures (id, Number) values (:id, 0);
----

[[fblangref30-contextvars-sqlcode-de]]
== `SQLCODE`

.Verfügbar in
PSQL

.Eingestellt in
2.5.1

.Typ
`INTEGER`

.Syntax
[listing]
----
SQLCODE
----

In einem "```WHEN ... DO```"-Fehlerbehandlungsblock enthält die Kontextvariable `SQLCODE` den aktuellen SQL-Fehlercode.
Vor Firebird 2.0 wurde `SQLCODE` nur in den `WHEN SQLCODE`- und `WHEN ANY`-Handlern gesetzt.
Sie darf jetzt auch in den Blöcken `WHEN GDSCODE`, `WHEN SQLSTATE` und `WHEN EXCEPTION` ungleich Null sein, sofern die fehlerauslösende Bedingung einem SQL-Fehlercode entspricht.
Außerhalb von Fehlerhandlern ist `SQLCODE` immer 0.
Außerhalb von PSQL existiert es überhaupt nicht.

[WARNING]
====
`SQLCODE` wird nun zugunsten des SQL-2003-kompatiblen Statuscodes <<fblangref30-contextvars-sqlstate-de>> veraltet.
Die Unterstützung für `SQLCODE` und `WHEN SQLCODE` wird in einer zukünftigen Version von Firebird eingestellt.
====

.Beispiel
[source]
----
when any
do
begin
  if (sqlcode <> 0) then
    Msg = 'An SQL error occurred!';
  else
    Msg = 'Something bad happened!';
  exception ex_custom Msg;
end
----

[[fblangref30-contextvars-sqlstate-de]]
== `SQLSTATE`

.Verfügbar in
PSQL

.Aufgenommen in
2.5.1

.Typ
`CHAR(5)`

.Syntax
[listing]
----
SQLSTATE
----

In einer "```WHEN ... DO```"-Fehlerbehandlung enthält die Kontextvariable `SQLSTATE` den 5-stelligen, SQL-2003-konformen Statuscode, der sich aus der Anweisung ergibt, die den Fehler ausgelöst hat.
Außerhalb von Fehlerhandlern ist `SQLSTATE` immer `'00000'`.
Außerhalb von PSQL ist es überhaupt nicht verfügbar.

[NOTE]
====
* `SQLSTATE` soll `SQLCODE` ersetzen.
Letzteres ist jetzt in Firebird veraltet und wird in einer zukünftigen Version verschwinden.
* Firebird unterstützt (noch) nicht die Syntax "```WHEN SQLSTATE ... DO```".
Sie müssen `WHEN ANY` verwenden und die Variable `SQLSTATE` innerhalb des Handlers testen.
* Jeder `SQLSTATE`-Code ist die Verkettung einer 2-Zeichen-Klasse und einer 3-Zeichen-Unterklasse.
Die Klassen _00_ (erfolgreicher Abschluss), _01_ (Warnung) und _02_ (keine Daten) repräsentieren [term]_Abschlussbedingungen_.
Jeder Statuscode außerhalb dieser Klassen ist ein [term]_Exception_.
Da die Klassen _00_, _01_ und _02_ keinen Fehler auslösen, werden sie niemals in der Variablen `SQLSTATE` angezeigt.
* Eine vollständige Liste der `SQLSTATE`-Codes finden Sie im Abschnitt <<fblangref30-appx02-tbl-sqlstates-de,SQLSTATE-Codes und Nachrichtentexte>> in [ref]_Anhang B: Ausnahmebehandlung, Codes und Nachrichten_.
====

.Beispiel
[source]
----
when any
do
begin
  Msg = case sqlstate
          when '22003' then 'Numeric value out of range.'
          when '22012' then 'Division by zero.'
          when '23000' then 'Integrity constraint violation.'
          else 'Something bad happened! SQLSTATE = ' || sqlstate
        end;
  exception ex_custom Msg;
end
----

[[fblangref30-contextvars-today-de]]
== `'TODAY'`

.Verfügbar in
DSQL, PSQL, ESQL

.Typ
`CHAR(5)`

`'TODAY'` ist keine Variable, sondern ein String-Literal.
Es ist jedoch in dem Sinne besonders, dass Sie, wenn Sie es in einen Datums-/Uhrzeittyp `CAST()` geben, das aktuelle Datum erhalten.
Bei `'TODAY'` wird die Groß-/Kleinschreibung nicht beachtet und die Engine ignoriert führende oder nachfolgende Leerzeichen beim Casting.

[NOTE]
====
* `'TODAY'` Ergebnis immer das aktuelle Datum, auch in PSQL-Modulen, wo <<fblangref30-contextvars-current-date-de>>, <<fblangref30-contextvars-current-time-de>> und <<fblangref30-contextvars-current-timestamp-de>> gibt während der gesamten Dauer der äußersten Routine denselben Wert zurück.
Dies macht `'TODAY'` nützlich, um Zeitintervalle in Triggern, Prozeduren und ausführbaren Blöcken zu messen (zumindest wenn Ihre Prozeduren tagelang laufen).
* Außer in der oben erwähnten Situation ist das Lesen von `CURRENT_DATE` im Allgemeinen vorzuziehen, `'NOW'` zu gießen.
====

.Beispiele
[source]
----
select 'Today' from rdb$database
-- Ergebnis 'Today'

select cast('Today' as date) from rdb$database
-- Ergebnis z.B. 2011-10-03

select cast('TODAY' as timestamp) from rdb$database
-- Ergebnis z.B. 2011-10-03 00:00:00.0000
----

<<fblangref30-datatypes-convert-shortcasts-de,Kurzschreibweise>> für die letzten beiden Anweisungen:

[source]
----
select date 'Today' from rdb$database;
select timestamp 'TODAY' from rdb$database;
----

[[fblangref30-contextvars-tomorrow-de]]
== `'TOMORROW'`

.Verfügbar in
DSQL, PSQL, ESQL

.Typ
`CHAR(8)`

`'TOMORROW'` ist keine Variable, sondern ein String-Literal.
Es ist jedoch in dem Sinne besonders, dass Sie, wenn Sie es in einen Datums-/Uhrzeittyp `CAST()` geben, das Datum des nächsten Tages erhalten.
Siehe auch <<fblangref30-contextvars-today-de>>.

.Beispiele
[source]
----
select 'Tomorrow' from rdb$database
-- Ergebnis 'Tomorrow'

select cast('Tomorrow' as date) from rdb$database
-- Ergebnis z.B. 2011-10-04

select cast('TOMORROW' as timestamp) from rdb$database
-- Ergebnis z.B. 2011-10-04 00:00:00.0000
----

<<fblangref30-datatypes-convert-shortcasts-de,Kurzschreibweise>> für die letzten beiden Anweisungen:

[source]
----
select date 'Tomorrow' from rdb$database;
select timestamp 'TOMORROW' from rdb$database;
----

[[fblangref30-contextvars-updating-de]]
== `UPDATING`

.Verfügbar in
PSQL

.Typ
`BOOLEAN`

.Syntax
[listing]
----
UPDATING
----

Nur in Triggern verfügbar, 'UPDATING' zeigt an, ob der Trigger aufgrund einer 'UPDATE'-Operation ausgelöst wurde.
Vorgesehen für die Verwendung in <<fblangref30-ddl-trgr-relntrigger-rowevent-de,Multi-Action-Trigger>>.

.Beispiel
[source]
----
if (inserting or updating) then
begin
  if (new.serial_num is null) then
    new.serial_num = gen_id(gen_serials, 1);
end
----

[[fblangref30-contextvars-yesterday-de]]
== `'YESTERDAY'`

.Verfügbar in
DSQL, PSQL, ESQL

.Typ
`CHAR(9)`

`'YESTERDAY'` ist keine Variable, sondern ein String-Literal.
Es ist jedoch in dem Sinne besonders, dass Sie, wenn Sie es in einen Datums-/Uhrzeittyp `CAST()` geben, das Datum des Vortages erhalten.
Siehe auch <<fblangref30-contextvars-today-de>>.

.Beispiele
[source]
----
select 'Yesterday' from rdb$database
-- Ergebnis 'Yesterday'

select cast('Yesterday as date) from rdb$database
-- Ergebnis z.B. 2011-10-02

select cast('YESTERDAY' as timestamp) from rdb$database
-- Ergebnis z.B. 2011-10-02 00:00:00.0000
----

<<fblangref30-datatypes-convert-shortcasts-de,Kurzschreibweise>> für die letzten beiden Anweisungen:

[source]
----
select date 'Yesterday' from rdb$database;
select timestamp 'YESTERDAY' from rdb$database;
----

[[fblangref30-contextvars-user-de]]
== `USER`

.Verfügbar in
DSQL, PSQL

.Typ
`VARCHAR(31)`

.Syntax
[listing]
----
USER
----

`USER` ist eine Kontextvariable, die den Namen des aktuell verbundenen Benutzers enthält.
Es entspricht vollständig <<fblangref30-contextvars-current-user-de>>.

.Beispiel
[source]
----
create trigger bi_customers for customers before insert as
begin
  New.added_by  = USER;
  New.purchases = 0;
end
----
