[[fblangref30-management-de]]
= Managementanweisungen

Seit Firebird 3.0 ist eine neue Klasse von DSQL-Anweisungen in Firebirds SQL-Lexikon entstanden, normalerweise für die Verwaltung von Aspekten der Client/Server-Umgebung.
Typischerweise beginnen solche Anweisungen mit dem Verb `SET`.

[NOTE]
====
Das _isql_-Tool hat auch eine Sammlung von `SET`-Befehlen.
Diese Befehle sind nicht Teil des SQL-Lexikons von Firebird.
Informationen zu __isql__s `SET`-Befehlen finden Sie unter https://www.firebirdsql.org/file/documentation/html/en/firebirddocs/isql/firebird-isql.html#isql-set[_Isql_ Set Commands] in _Firebird Interactive SQL Utility_.
====

Die meisten Verwaltungsanweisungen betreffen nur die aktuelle Verbindung (Anhang oder "Sitzung") und erfordern keine Autorisierung über die Anmeldeberechtigungen des aktuellen Benutzers ohne erhöhte Berechtigungen hinaus.

[[fblangref30-management-role-de]]
== Ändern der aktuellen Rolle

[[fblangref30-management-role-set-de]]
=== `SET ROLE`

.Benutzt für
Ändern der Rolle der aktuellen Sitzung

.Verfügbar in
DSQL

.Syntax
[listing,subs=+quotes]
----
SET ROLE {_role_name_ | NONE}
----

.`SET ROLE`-Anweisungsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|role_name
|Der Name der anzuwendenden Rolle role
|===

Die `SET ROLE`-Anweisung ermöglicht es einem Benutzer, eine andere Rolle anzunehmen;
es setzt die Kontextvariable `CURRENT_ROLE` auf _role_name_, wenn diese Rolle dem `CURRENT_USER` gewährt wurde.
Für diese Sitzung erhält der Benutzer die von dieser Rolle gewährten Berechtigungen.
Alle Rechte, die der vorherigen Rolle gewährt wurden, werden aus der Sitzung entfernt.
Verwenden Sie `NONE` anstelle von _role_name_, um die `CURRENT_ROLE` zu löschen.

Wenn die angegebene Rolle nicht existiert oder dem Benutzer nicht explizit zugewiesen wurde, wird der Fehler "`__Role *role_name* is invalid or unavailable__`" ausgegeben.

[[fblangref30-management-role-set-exmpl-de]]
==== `SET ROLE`-Beispiele

. Ändern Sie die aktuelle Rolle in `MANAGER`
+
[source]
----
SET ROLE manager;
select current_role from rdb$database;

ROLE
=======================
MANAGER
----
. Löschen Sie die aktuelle Rolle
+
[source]
----
SET ROLE NONE;
select current_role from rdb$database;

ROLE
=======================
NONE
----

.Siehe auch
<<fblangref30-management-role-set-trusted-de>>, <<fblangref30-security-grant-de,`GRANT`>>

[[fblangref30-management-role-set-trusted-de]]
=== `SET TRUSTED ROLE`

.Verwendet für
Ändert die Rolle der aktuellen Sitzung in die vertrauenswürdige Rolle

.Verfügbar in
DSQL

.Syntax
[listing]
----
SET TRUSTED ROLE
----

Die Anweisung `SET TRUSTED ROLE` ermöglicht es, die dem Benutzer durch eine Mapping-Regel zugewiesene Rolle einzunehmen (siehe <<fblangref30-security-mapping-de,Mapping von Benutzern auf Objekte>>).
Die durch eine Zuordnungsregel zugewiesene Rolle wird beim Verbinden automatisch übernommen, wenn der Benutzer keine explizite Rolle angegeben hat.
Die Anweisung `SET TRUSTED ROLE` ermöglicht es, die zugeordnete (oder `trusted``) Rolle zu einem späteren Zeitpunkt oder nach Änderung der aktuellen Rolle mit `SET ROLE` wieder einzunehmen.

Eine vertrauenswürdige Rolle ist kein bestimmter Rollentyp, sondern kann eine beliebige Rolle sein, die mit `CREATE ROLE` erstellt wurde, oder eine vordefinierte Systemrolle wie `RDB$ADMIN`.
Ein Anhang (Sitzung) hat eine vertrauenswürdige Rolle, wenn das <<fblangref30-security-mapping-de,Sicherheitsobjekt-Mapping-Subsystem>> eine Übereinstimmung zwischen dem vom Plugin übergebenen Authentifizierungsergebnis und einer lokalen oder globalen Zuordnung zu einer Rolle für die aktuelle Datenbank findet.
Die Rolle kann diesem Benutzer nicht explizit zugewiesen werden.

Wenn eine Sitzung keine vertrauenswürdige Rolle hat, wird die Ausführung von `SET TRUSTED ROLE` den Fehler „`__Your attachment has no trusted role__`“ auslösen.

[NOTE]
====
Während die `CURRENT_ROLE` mit `SET ROLE` geändert werden kann, ist es nicht immer möglich, mit demselben Befehl zu einer vertrauenswürdigen Rolle zurückzukehren, da `SET ROLE` prüft, ob die Rolle dem Benutzer zugewiesen wurde.
Mit `SET TRUSTED ROLE` kann die Trusted Rolle auch dann wieder übernommen werden, wenn `SET ROLE` fehlschlägt.
====

[[fblangref30-management-role-set-trusted-exmpl-de]]
==== `SET TRUSTED ROLE`-Beispiele

. Angenommen, eine Zuordnungsregel weist einem Benutzer "ALEX" die Rolle "ROLE1" zu:
+
[source]
-----
CONNECT 'employee' USER ALEX PASSWORD 'password';
SELECT CURRENT_ROLE FROM RDB$DATABASE;

ROLE
===============================
ROLE1

SET ROLE ROLE2;
SELECT CURRENT_ROLE FROM RDB$DATABASE;

ROLE
===============================
ROLE2

SET TRUSTED ROLE;
SELECT CURRENT_ROLE FROM RDB$DATABASE;

ROLE
===============================
ROLE1
-----

.Siehe auch
<<fblangref30-management-role-set-de>>, <<fblangref30-security-mapping-de,Zuordnung von Benutzern zu Objekten>>
