[[fblangref30-aggfuncs-de]]
= Aggregatfunktionen

Aggregatfunktionen arbeiten mit Gruppen von Datensätzen und nicht mit einzelnen Datensätzen oder Variablen.
Sie werden oft in Kombination mit einer `GROUP BY`-Klausel verwendet.

Die Aggregatfunktionen können mit der `OVER()`-Klausel auch als Fensterfunktionen verwendet werden.
Weitere Informationen finden Sie unter <<fblangref30-windowfuncs-de,Window (Analytical) Functions>>.

[[fblangref30-aggfuncs-general-de]]
== Allgemeine Aggregatfunktionen

[[fblangref30-aggfuncs-avg-de]]
=== `AVG()`

.Verfügbar in
DSQL, ESQL, PSQL

.Rückgabetyp
Ein numerischer Datentyp, der dem Datentyp des Arguments entspricht.

.Syntax
[listing]
----
AVG ([ALL | DISTINCT] <expr>)
----

[[fblangref30-aggfuncs-tbl-avg-de]]
.`AVG`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|expr
|Ausdruck.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten, die einen numerischen Datentyp zurückgibt.
Aggregatfunktionen sind als Ausdrücke nicht zulässig
|===

`AVG` gibt den durchschnittlichen Argumentwert in der Gruppe zurück.
`NULL` wird ignoriert.

* Parameter `ALL` (Standard) wendet die Aggregatfunktion auf alle Werte an.
* Der Parameter `DISTINCT` weist die `AVG`-Funktion an, nur eine Instanz jedes eindeutigen Werts zu berücksichtigen, egal wie oft dieser Wert auftritt.
* Wenn die Menge der abgerufenen Datensätze leer ist oder nur `NULL` enthält, ist das Ergebnis `NULL`. 

[[fblangref30-aggfuncs-avg-exmpl-de]]
==== `AVG`-Beispiele

[source]
----
SELECT
  dept_no,
  AVG(salary)
FROM employee
GROUP BY dept_no
----

.Siehe auch
<<fblangref30-dml-select-de,`SELECT`>>

[[fblangref30-aggfuncs-count-de]]
=== `COUNT()`

.Verfügbar in
DSQL, ESQL, PSQL

.Rückgabetyp
`BIGINT`

.Syntax
[listing]
----
COUNT ([ALL | DISTINCT] <expr> | *)
----

[[fblangref30-aggfuncs-tbl-count-de]]
.`COUNT`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|expr
|Ausdruck.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten, die einen numerischen Datentyp zurückgibt.
Aggregatfunktionen sind als Ausdrücke nicht zulässig
|===

`COUNT` gibt die Anzahl der Nicht-Null-Werte in einer Gruppe zurück.

* `ALL` ist die Vorgabe: es zählt einfach alle Werte in der Menge, die nicht `NULL` sind.
* Wenn `DISTINCT` angegeben ist, werden Duplikate aus der gezählten Menge ausgeschlossen.
* Wenn `COUNT ({asterisk})` anstelle des Ausdrucks _expr_ angegeben wird, werden alle Zeilen gezählt.
`ZAHL ({asterisk})` --
** akzeptiert keine Parameter
** kann nicht mit dem Schlüsselwort `DISTINCT` verwendet werden
** nimmt kein _expr_-Argument an, da sein Kontext per Definition spaltenunspezifisch ist
** zählt jede Zeile separat und gibt die Anzahl der Zeilen in der angegebenen Tabelle oder Gruppe zurück, ohne doppelte Zeilen auszulassen
** zählt Zeilen mit `NULL`
* Wenn die Ergebnismenge leer ist oder nur `NULL` in der/den angegebenen Spalte(n) enthält, ist der zurückgegebene Zähler null.

[[fblangref30-aggfuncs-count-exmpl-de]]
==== `COUNT`-Beispiele

[source]
----
SELECT
  dept_no,
  COUNT(*) AS cnt,
  COUNT(DISTINCT name) AS cnt_name
FROM employee
GROUP BY dept_no
----

.Siehe auch
<<fblangref30-dml-select-de,`SELECT`>>.

[[fblangref30-aggfuncs-list-de]]
=== `LIST()`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`BLOB`

.Syntax
[listing,subs=+quotes]
----
LIST ([ALL | DISTINCT] <expr> [, _separator_ ])
----

[[fblangref30-aggfuncs-tbl-list-de]]
.`LIST`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|expr
|Ausdruck.
Es kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten, die den String-Datentyp oder ein 'BLOB' zurückgibt.
Felder des numerischen Typs und des Datums-/Uhrzeittyps werden in Zeichenfolgen umgewandelt.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.

|separator
|Optionales alternatives Trennzeichen, ein Zeichenfolgenausdruck.
Komma ist das Standardtrennzeichen
|===

`LIST` gibt einen String zurück, der aus den Nicht-``NULL``-Argumentwerten in der Gruppe besteht, getrennt entweder durch ein Komma oder durch ein vom Benutzer angegebenes Trennzeichen.
Wenn keine Nicht-``NULL``-Werte vorhanden sind (dies schließt den Fall ein, in dem die Gruppe leer ist), wird ``NULL`` zurückgegeben.

* `ALL` (Standard) führt dazu, dass alle Nicht-``NULL``-Werte aufgelistet werden.
Mit `DISTINCT` werden Duplikate entfernt, außer wenn _expr_ ein `BLOB` ist.
* In Firebird 2.5 und höher kann das optionale Argument _separator_ ein beliebiger String-Ausdruck sein.
Dadurch ist es möglich, z.B. `ascii_char(13)` als Trennzeichen.
(Diese Verbesserung wurde auch auf 2.1.4 zurückportiert.)
* Die Argumente _expr_ und _separator_ unterstützen ``BLOB``s jeder Größe und jedes Zeichensatzes.
* Datum/Uhrzeit und numerische Argumente werden vor der Verkettung implizit in Zeichenfolgen umgewandelt.
* Das Ergebnis ist ein Text `BLOB`, außer wenn _expr_ ein `BLOB` eines anderen Untertyps ist.
* Die Reihenfolge der Listenwerte ist undefiniert -- die Reihenfolge, in der die Strings verkettet werden, wird durch die Lesereihenfolge aus dem Quellsatz bestimmt, die in Tabellen nicht allgemein definiert ist.
Wenn die Sortierung wichtig ist, können die Quelldaten mithilfe einer abgeleiteten Tabelle oder ähnlichem vorsortiert werden.

[[fblangref30-aggfuncs-list-exmpl-de]]
==== `LIST`-Beispiele

.Abrufen der Liste, Sortierung undefiniert:
+
[source]
----
SELECT LIST (display_name, '; ') FROM GR_WORK;
----
. Abrufen der Liste in alphabetischer Reihenfolge mithilfe einer abgeleiteten Tabelle:
+
[source]
----
SELECT LIST (display_name, '; ')
FROM (SELECT display_name
      FROM GR_WORK
      ORDER BY display_name);
----

.Siehe auch
<<fblangref30-dml-select-de,`SELECT`>>

[[fblangref30-aggfuncs-max-de]]
=== `MAX()`

.Verfügbar in
DSQL, ESQL, PSQL

.Rückgabetyp
Gibt ein Ergebnis des gleichen Datentyps wie der Eingabeausdruck zurück.

.Syntax
[listing]
----
MAX ([ALL | DISTINCT] <expr>)
----

[[fblangref30-aggfuncs-tbl-max-de]]
.`MAX`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|expr
|Ausdruck.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

`MAX` gibt das maximale Nicht-``NULL``-Element in der Ergebnismenge zurück.

* Wenn die Gruppe leer ist oder nur ``NULL``s enthält, ist das Ergebnis `NULL`.
* Wenn das Eingabeargument ein String ist, gibt die Funktion den Wert zurück, der zuletzt sortiert wird, wenn `COLLATE` verwendet wird.
* Diese Funktion unterstützt vollständig Text-``BLOB``s jeder Größe und jedes Zeichensatzes.

[NOTE]
====
Der Parameter `DISTINCT` macht bei Verwendung mit `MAX()` keinen Sinn und wird nur zur Einhaltung des Standards implementiert.
====

[[fblangref30-aggfuncs-max-exmpl-de]]
==== `MAX`-Beispiele

[source]
----
SELECT
  dept_no,
  MAX(salary)
FROM employee
GROUP BY dept_no
----

.Siehe auch
<<fblangref30-aggfuncs-min-de>>, <<fblangref30-dml-select-de,`SELECT`>>

[[fblangref30-aggfuncs-min-de]]
=== `MIN()`

.Verfügbar in
DSQL, ESQL, PSQL

.Rückgabetyp
Gibt ein Ergebnis des gleichen Datentyps wie der Eingabeausdruck zurück.

.Syntax
[listing]
----
MIN ([ALL | DISTINCT] <expr>)
----

[[fblangref30-aggfuncs-tbl-min]]
.`MIN`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|expr
|Ausdruck.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

`MIN` gibt das minimale Nicht-``NULL``-Element in der Ergebnismenge zurück.

* Wenn die Gruppe leer ist oder nur ``NULL``s enthält, ist das Ergebnis `NULL`.
* Wenn das Eingabeargument ein String ist, gibt die Funktion den Wert zurück, der zuerst sortiert wird, wenn `COLLATE` verwendet wird.
* Diese Funktion unterstützt vollständig Text-``BLOB``s jeder Größe und jedes Zeichensatzes.

[NOTE]
====
Der Parameter `DISTINCT` macht bei Verwendung mit `MIN()` keinen Sinn und wird nur zur Einhaltung des Standards implementiert.
====

[[fblangref30-aggfuncs-min-exmpl-de]]
==== `MIN`-Beispiele

[source]
----
SELECT
  dept_no,
  MIN(salary)
FROM employee
GROUP BY dept_no
----

.Siehe auch
<<fblangref30-aggfuncs-max-de>>, <<fblangref30-dml-select-de,`SELECT`>>

[[fblangref30-aggfuncs-sum-de]]
=== `SUM()`

.Verfügbar in
DSQL, ESQL, PSQL

.Rückgabetyp
Gibt ein Ergebnis des gleichen Datentyps wie der Eingabeausdruck zurück.

.Syntax
[listing]
----
SUM ([ALL | DISTINCT] <expr>)
----

[[fblangref30-aggfuncs-tbl-sum-de]]
.`SUM`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|expr
|Numerischer Ausdruck.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

`SUM` berechnet die Summe der Nicht-Null-Werte in der Gruppe und gibt sie zurück.

* Wenn die Gruppe leer ist oder nur ``NULL``s enthält, ist das Ergebnis `NULL`.
* ALL ist die Standardoption -- alle Werte in der Menge, die nicht `NULL` sind, werden verarbeitet.
Bei Angabe von `DISTINCT` werden Duplikate aus dem Set entfernt und anschließend die `SUM`-Auswertung durchgeführt.

[[fblangref30-aggfuncs-sum-exmpl-de]]
==== `SUM`-Beispiele

[source]
----
SELECT
  dept_no,
  SUM (salary),
FROM employee
GROUP BY dept_no
----

.Siehe auch
<<fblangref30-dml-select-de,`SELECT`>>

[[fblangref30-aggfuncs-stats-de]]
== Statistische Aggregatfunktionen

[[fblangref30-aggfuncs-corr-de]]
=== `CORR`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`DOUBLE PRECISION`

.Syntax
[listing]
----
CORR ( <expr1>, <expr2> )
----

[[fblangref30-aggfuncs-tbl-corr-de]]
.`CORR`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|expr__N__
|Numerischer Ausdruck.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

Die Funktion `CORR` gibt den Korrelationskoeffizienten für ein Paar numerischer Ausdrücke zurück.

Die Funktion `CORR(<expr1>, <expr2>)` ist äquivalent zu

[listing]
----
COVAR_POP(<expr1>, <expr2>) / (STDDEV_POP(<expr2>) * STDDEV_POP(<expr1>))
----

Dies wird auch als Korrelationskoeffizient nach Pearson bezeichnet.

Im statistischen Sinne ist Korrelation der Grad, mit dem ein Variablenpaar linear verbunden ist.
Eine lineare Beziehung zwischen Variablen bedeutet, dass der Wert einer Variablen bis zu einem gewissen Grad den Wert der anderen vorhersagen kann.
Der Korrelationskoeffizient stellt den Korrelationsgrad als Zahl von -1 (hohe inverse Korrelation) bis 1 (hohe Korrelation) dar.
Ein Wert von 0 entspricht keiner Korrelation.

Wenn die Gruppe oder das Fenster leer ist oder nur `NULL`-Werte enthält, ist das Ergebnis `NULL`.

[[fblangref30-aggfuncs-corr-exmpl-de]]
==== `CORR`-Beispiele

[source]
----
select
  corr(alength, aheight) AS c_corr
from measure
----

.Siehe auch
<<fblangref30-aggfuncs-covar-pop-de>>, <<fblangref30-aggfuncs-stddev-pop-de>>

[[fblangref30-aggfuncs-covar-pop-de]]
=== `COVAR_POP`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`DOUBLE PRECISION`

.Syntax
[listing]
----
COVAR_POP ( <expr1>, <expr2> )
----

[[fblangref30-aggfuncs-tbl-covar-pop-de]]
.`COVAR_POP`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|expr__N__
|Numerischer Ausdruck.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

Die Funktion `COVAR_POP` gibt die Populationskovarianz für ein Paar numerischer Ausdrücke zurück.

Die Funktion `COVAR_POP(<expr1>, <expr2>)` ist äquivalent zu

[listing]
----
(SUM(<expr1> * <expr2>) - SUM(<expr1>) * SUM(<expr2>) / COUNT(*)) / COUNT(*)
----

Wenn die Gruppe oder das Fenster leer ist oder nur `NULL`-Werte enthält, ist das Ergebnis `NULL`.

[[fblangref30-aggfuncs-covar-pop-exmpl-de]]
==== `COVAR_POP`-Beispiele

[source]
----
select
  covar_pop(alength, aheight) AS c_covar_pop
from measure
----

.Siehe auch
<<fblangref30-aggfuncs-covar-samp-de>>, <<fblangref30-aggfuncs-sum-de>>, <<fblangref30-aggfuncs-count-de>>

[[fblangref30-aggfuncs-covar-samp-de]]
=== `COVAR_SAMP`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`DOUBLE PRECISION`

.Syntax
[listing]
----
COVAR_SAMP ( <expr1>, <expr2> )
----

[[fblangref30-aggfuncs-tbl-covar-samp-de]]
.`COVAR_SAMP`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|expr__N__
|Numerischer Ausdruck.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

Die Funktion `COVAR_SAMP` gibt die Stichprobenkovarianz für ein Paar numerischer Ausdrücke zurück.

Die Funktion `COVAR_SAMP(<expr1>, <expr2>)` ist äquivalent zu

[listing]
----
(SUM(<expr1> * <expr2>) - SUM(<expr1>) * SUM(<expr2>) / COUNT(*)) / (COUNT(*) - 1)
----

Wenn die Gruppe oder das Fenster leer ist, nur 1 Zeile enthält oder nur `NULL`-Werte enthält, ist das Ergebnis `NULL`.

[[fblangref30-aggfuncs-covar-samp-exmpl-de]]
==== `COVAR_SAMP`-Beispiele

[source]
----
select
  covar_samp(alength, aheight) AS c_covar_samp
from measure
----

.Siehe auch
<<fblangref30-aggfuncs-covar-pop-de>>, <<fblangref30-aggfuncs-sum-de>>, <<fblangref30-aggfuncs-count-de>>

[[fblangref30-aggfuncs-stddev-pop-de]]
=== `STDDEV_POP`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`DOUBLE PRECISION` oder `NUMERIC` je nach Typ von _expr_

.Syntax
[listing]
----
STDDEV_POP ( <expr> )
----

[[fblangref30-aggfuncs-tbl-stddev-pop-de]]
.`STDDEV_POP`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|expr
|Numerischer Ausdruck.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

Die Funktion `STDDEV_POP` gibt die Populationsstandardabweichung für eine Gruppe oder ein Fenster zurück.
`NULL`-Werte werden übersprungen.

Die Funktion `STDDEV_POP(<expr>)` ist äquivalent zu

[listing]
----
SQRT(VAR_POP(<expr>))
----

Wenn die Gruppe oder das Fenster leer ist oder nur `NULL`-Werte enthält, ist das Ergebnis `NULL`.

[[fblangref30-aggfuncs-stddev-pop-exmpl-de]]
==== `STDDEV_POP`-Beispiele

[source]
----
select
  dept_no
  stddev_pop(salary)
from employee
group by dept_no
----

.Siehe auch
<<fblangref30-aggfuncs-stddev-samp-de>>, <<fblangref30-aggfuncs-var-pop-de>>, <<fblangref30-scalarfuncs-sqrt-de,`SQRT`>>

[[fblangref30-aggfuncs-stddev-samp-de]]
=== `STDDEV_SAMP`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`DOUBLE PRECISION` oder `NUMERIC` je nach Typ von _expr_

.Syntax
[listing]
----
STDDEV_POP ( <expr> )
----

[[fblangref30-aggfuncs-tbl-stddev-samp-de]]
.`STDDEV_SAMP`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|expr
|Numerischer Ausdruck.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

Die Funktion `STDDEV_SAMP` gibt die Standardabweichung der Stichprobe für eine Gruppe oder ein Fenster zurück.
`NULL`-Werte werden übersprungen.

Die Funktion `STDDEV_SAMP(<expr>)` ist äquivalent zu

[listing]
----
SQRT(VAR_SAMP(<expr>))
----

Wenn die Gruppe oder das Fenster leer ist, nur 1 Zeile enthält oder nur `NULL`-Werte enthält, ist das Ergebnis `NULL`.

[[fblangref30-aggfuncs-stddev-samp-exmpl-de]]
==== `STDDEV_SAMP`-Beispiele

[source]
----
select
  dept_no
  stddev_samp(salary)
from employee
group by dept_no
----

.Siehe auch
<<fblangref30-aggfuncs-stddev-pop-de>>, <<fblangref30-aggfuncs-var-samp-de>>, <<fblangref30-scalarfuncs-sqrt-de,`SQRT`>>

[[fblangref30-aggfuncs-var-pop-de]]
=== `VAR_POP`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`DOUBLE PRECISION` oder `NUMERIC` je nach Typ von _expr_

.Syntax
[listing]
----
VAR_POP ( <expr> )
----

[[fblangref30-aggfuncs-tbl-var-pop-de]]
.`VAR_POP`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|expr
|Numerischer Ausdruck.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

Die Funktion `VAR_POP` gibt die Populationsvarianz für eine Gruppe oder ein Fenster zurück.
`NULL`-Werte werden übersprungen.

Die Funktion `VAR_POP(<expr>)` ist äquivalent zu

[listing]
----
(SUM(<expr> * <expr>) - SUM (<expr>) * SUM (<expr>) / COUNT(<expr>))
  / COUNT (<expr>)
----

Wenn die Gruppe oder das Fenster leer ist oder nur `NULL`-Werte enthält, ist das Ergebnis `NULL`.

[[fblangref30-aggfuncs-var-pop-exmpl-de]]
==== `VAR_POP`-Beispiele

[source]
----
select
  dept_no
  var_pop(salary)
from employee
group by dept_no
----

.Siehe auch
<<fblangref30-aggfuncs-var-samp-de>>, <<fblangref30-aggfuncs-sum-de>>, <<fblangref30-aggfuncs-count-de>>

[[fblangref30-aggfuncs-var-samp-de]]
=== `VAR_SAMP`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`DOUBLE PRECISION` oder `NUMERIC` je nach Typ von _expr_

.Syntax
[listing]
----
VAR_SAMP ( <expr> )
----

[[fblangref30-aggfuncs-tbl-var-samp-de]]
.`VAR_SAMP`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|expr
|Numerischer Ausdruck.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

Die Funktion `VAR_POP` gibt die Stichprobenvarianz für eine Gruppe oder ein Fenster zurück.
`NULL`-Werte werden übersprungen.

Die Funktion `VAR_SAMP(<expr>)` ist äquivalent zu

[listing]
----
(SUM(<expr> * <expr>) - SUM(<expr>) * SUM (<expr>) / COUNT (<expr>))
  / (COUNT(<expr>) - 1)
----

Wenn die Gruppe oder das Fenster leer ist, nur 1 Zeile enthält oder nur `NULL`-Werte enthält, ist das Ergebnis `NULL`.

[[fblangref30-aggfuncs-var-samp-exmpl-de]]
==== `VAR_SAMP`-Beispiele

[source]
----
select
  dept_no
  var_samp(salary)
from employee
group by dept_no
----

.Siehe auch
<<fblangref30-aggfuncs-var-pop-de>>, <<fblangref30-aggfuncs-sum-de>>, <<fblangref30-aggfuncs-count-de>>

[[fblangref30-aggfuncs-regr]]
== Aggregatfunktionen der linearen Regression

Lineare Regressionsfunktionen sind nützlich für die Fortsetzung von Trendlinien.
Die Trend- oder Regressionslinie ist normalerweise ein Muster, dem eine Reihe von Werten folgt.
Die lineare Regression ist nützlich, um zukünftige Werte vorherzusagen.
Um die Regressionsgerade fortzusetzen, müssen Sie die Steigung und den Schnittpunkt mit der y-Achse kennen.
Zur Berechnung dieser Werte kann ein Satz linearer Funktionen verwendet werden.

In der Funktionssyntax wird _y_ als _x_-abhängige Variable interpretiert.

Die Aggregatfunktionen der linearen Regression verwenden ein Argumentpaar, den abhängigen Variablenausdruck (_y_) und den unabhängigen Variablenausdruck (_x_), die beide numerische Wertausdrücke sind.
Jede Zeile, in der eines der Argumente als `NULL` ausgewertet wird, wird aus den qualifizierenden Zeilen entfernt.
Wenn keine qualifizierenden Zeilen vorhanden sind, ist das Ergebnis von `REGR_COUNT` `0` (Null), und die anderen Aggregatfunktionen der linearen Regression ergeben `NULL`.

[[fblangref30-aggfuncs-regr-avgx-de]]
=== `REGR_AVGX`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_AVGX ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-avgx-de]]
.`REGR_AVGX`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|y
|Abhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.

|x
|Unabhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

Die Funktion `REGR_AVGX` berechnet den Durchschnitt der unabhängigen Variablen (_x_) der Regressionsgerade.

Die Funktion `REGR_AVGX(<y>, <x>)` ist äquivalent zu

[listing]
----
SUM(<exprX>) / REGR_COUNT(<y>, <x>)

<exprX> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN <x> END
----

.Siehe auch
<<fblangref30-aggfuncs-regr-avgy-de>>, <<fblangref30-aggfuncs-regr-count-de>>, <<fblangref30-aggfuncs-sum-de>>

[[fblangref30-aggfuncs-regr-avgy-de]]
=== `REGR_AVGY`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_AVGY ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-avgy-de]]
.`REGR_AVGY`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|y
|Abhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.

|x
|Unabhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

Die Funktion `REGR_AVGY` berechnet den Durchschnitt der abhängigen Variablen (_y_) der Regressionsgerade.

Die Funktion `REGR_AVGY(<y>, <x>)` ist äquivalent zu

[listing]
----
SUM(<exprY>) / REGR_COUNT(<y>, <x>)

<exprY> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN <y> END
----

.Siehe auch
<<fblangref30-aggfuncs-regr-avgx-de>>, <<fblangref30-aggfuncs-regr-count-de>>, <<fblangref30-aggfuncs-sum-de>>

[[fblangref30-aggfuncs-regr-count-de]]
=== `REGR_COUNT`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_COUNT ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-count-de]]
.`REGR_COUNT`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|y
|Abhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.

|x
|Unabhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

Die Funktion `REGR_COUNT` zählt die Anzahl der nicht leeren Paare der Regressionsgerade.

Die Funktion `REGR_COUNT(<y>, <x>)` ist äquivalent zu

[listing]
----
SUM(<exprXY>) / REGR_COUNT(<y>, <x>)

<exprXY> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN 1 END
----

.Siehe auch
<<fblangref30-aggfuncs-sum-de>>

[[fblangref30-aggfuncs-regr-intercept-de]]
=== `REGR_INTERCEPT`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_INTERCEPT ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-intercept-de]]
.`REGR_INTERCEPT`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|y
|Abhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.

|x
|Unabhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

Die Funktion `REGR_INTERCEPT` berechnet den Schnittpunkt der Regressionsgerade mit der y-Achse.

Die Funktion `REGR_INTERCEPT(<y>, <x>)` ist äquivalent zu

[listing]
----
REGR_AVGY(<y>, <x>) - REGR_SLOPE(<y>, <x>) * REGR_AVGX(<y>, <x>)
----

[[fblangref30-aggfuncs-regr-intercept-exmpl-de]]
==== `REGR_INTERCEPT`-Beispiele

Prognose des Verkaufsvolumens

[source]
----
with recursive years (byyear) as (
  select 1991
  from rdb$database
  union all
  select byyear + 1
  from years
  where byyear < 2020
),
s as (
  select
    extract(year from order_date) as byyear,
    sum(total_value) as total_value
  from sales
  group by 1
),
regr as (
  select
    regr_intercept(total_value, byyear) as intercept,
    regr_slope(total_value, byyear) as slope
  from s
)
select
  years.byyear as byyear,
  intercept + (slope * years.byyear) as total_value
from years
cross join regr
----

[listing]
----
BYYEAR TOTAL_VALUE
------ ------------
  1991    118377.35
  1992    414557.62
  1993    710737.89
  1994   1006918.16
  1995   1303098.43
  1996   1599278.69
  1997   1895458.96
  1998   2191639.23
  1999   2487819.50
  2000   2783999.77
...
----

.Siehe auch
<<fblangref30-aggfuncs-regr-avgx-de>>, <<fblangref30-aggfuncs-regr-avgy-de>>, <<fblangref30-aggfuncs-regr-slope-de>>

[[fblangref30-aggfuncs-regr-r2-de]]
=== `REGR_R2`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_R2 ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-r2-de]]
.`REGR_R2`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|y
|Abhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.

|x
|Unabhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

Die Funktion REGR_R2 berechnet das Bestimmtheitsmaß oder das R-Quadrat der Regressionsgerade.

Die Funktion `REGR_R2(<y>, <x>)` ist äquivalent zu

[listing]
----
POWER(CORR(<y>, <x>), 2)
----

.Siehe auch
<<fblangref30-aggfuncs-corr-de>>, <<fblangref30-scalarfuncs-power-de,`POWER`>>

[[fblangref30-aggfuncs-regr-slope-de]]
=== `REGR_SLOPE`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_SLOPE ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-slope-de]]
.`REGR_SLOPE`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|y
|Abhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.

|x
|Unabhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

Die Funktion `REGR_SLOPE` berechnet die Steigung der Regressionsgerade.

Die Funktion `REGR_SLOPE(<y>, <x>)` ist äquivalent zu

[listing]
----
COVAR_POP(<y>, <x>) / VAR_POP(<exprX>)

<exprX> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN <x> END
----

.Siehe auch
<<fblangref30-aggfuncs-covar-pop-de>>, <<fblangref30-aggfuncs-var-pop-de>>

[[fblangref30-aggfuncs-regr-sxx-de]]
=== `REGR_SXX`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_SXX ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-sxx-de]]
.`REGR_SXX`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|y
|Abhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.

|x
|Unabhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

Die Funktion `REGR_SXX` berechnet die Quadratsumme der unabhängigen Ausdrucksvariablen (_x_).

Die Funktion `REGR_SXX(<y>, <x>)` ist äquivalent zu

[listing]
----
REGR_COUNT(<y>, <x>) * VAR_POP(<exprX>)

<exprX> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN <x> END
----

.Siehe auch
<<fblangref30-aggfuncs-regr-count-de>>, <<fblangref30-aggfuncs-var-pop-de>>

[[fblangref30-aggfuncs-regr-sxy-de]]
=== `REGR_SXY`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_SXY ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-sxy-de]]
.`REGR_SXY`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|y
|Abhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.

|x
|Unabhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

Die Funktion `REGR_SXY` berechnet die Summe der Produkte des unabhängigen Variablenausdrucks (_x_) mal des abhängigen Variablenausdrucks (_y_).

Die Funktion `REGR_SXY(<y>, <x>)` ist äquivalent zu

[listing]
----
REGR_COUNT(<y>, <x>) * COVAR_POP(<y>, <x>)
----

.Siehe auch
<<fblangref30-aggfuncs-covar-pop-de>>, <<fblangref30-aggfuncs-regr-count-de>>

[[fblangref30-aggfuncs-regr-syy-de]]
=== `REGR_SYY`

.Verfügbar in
DSQL, PSQL

.Rückgabetyp
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_SYY ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-syy-de]]
.`REGR_SYY`-Funktionsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|y
|Abhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.

|x
|Unabhängige Variable der Regressionsgerade.
Sie kann eine Tabellenspalte, eine Konstante, eine Variable, einen Ausdruck, eine Nicht-Aggregatfunktion oder eine UDF enthalten.
Aggregatfunktionen sind als Ausdrücke nicht zulässig.
|===

Die Funktion `REGR_SYY` berechnet die Quadratsumme der abhängigen Variablen (_y_).

Die Funktion `REGR_SYY(<y>, <x>)` ist äquivalent zu

[listing]
----
REGR_COUNT(<y>, <x>) * VAR_POP(<exprY>)

<exprY> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN <y> END
----

.Siehe auch
<<fblangref30-aggfuncs-regr-count-de>>, <<fblangref30-aggfuncs-var-pop-de>>
