[[fblangref40-ddl-comment-de]]
= COMMENT

Datenbankobjekte und eine Datenbank selbst können mit Kommentaren versehen werden.
Es ist ein bequemer Mechanismus, um die Entwicklung und Wartung einer Datenbank zu dokumentieren.
Kommentare, die mit `COMMENT ON` erstellt wurden, überleben eine _gbak_-Sicherung und -Wiederherstellung.

[[fblangref40-ddl-comment-create-de]]
== `COMMENT ON`

.Verwendet für
Metadaten dokumentieren

.Verfügbar in
DSQL

.Syntax
[listing,subs=+quotes]
----
COMMENT ON <object> IS {'_sometext_' | NULL}

<object> ::=
    {DATABASE | SCHEMA}
  | <basic-type> _objectname_
  | USER _username_ [USING PLUGIN _pluginname_]
  | COLUMN _relationname_._fieldname_
  | [{PROCEDURE | FUNCTION}] PARAMETER
      \[__packagename__.]_routinename_._paramname_
  | {PROCEDURE | [EXTERNAL] FUNCTION}
      \[__package_name__.]_routinename_

<basic-type> ::=
    CHARACTER SET | COLLATION | DOMAIN
  | EXCEPTION     | FILTER    | GENERATOR
  | INDEX         | PACKAGE   | ROLE
  | SEQUENCE      | TABLE     | TRIGGER
  | VIEW
----

[[fblangref40-ddl-tbl-commenton-de]]
.`COMMENT ON`-Anweisungsparameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Beschreibung

|sometext
|Kommentartext

|basic-type
|Metadaten-Objekttyp

|objectname
|Name des Metadatenobjekts

|username
|Benutzername

|pluginname
|Name des User-Manager-Plugins

|relationname
|Name der Tabelle oder Ansicht

|fieldname
|Name der Spalte

|package_name
|Name des Pakets

|routinename
|Name der gespeicherten Prozedur oder Funktion

|paramname
|Name einer gespeicherten Prozedur oder eines Funktionsparameters
|===

Die Anweisung `COMMENT ON` fügt Kommentare für Datenbankobjekte (Metadaten) hinzu.
Kommentare werden in der Spalte `RDB$DESCRIPTION` der entsprechenden Systemtabellen gespeichert.
Clientanwendungen können Kommentare aus diesen Feldern anzeigen.

[NOTE]
====
. Wenn Sie einen leeren Kommentar hinzufügen ("```''```"), wird dieser als `NULL` in der Datenbank gespeichert.
. Standardmäßig erstellt die `COMMENT ON USER`-Anweisung Kommentare zu Benutzern, die vom Standardbenutzermanager verwaltet werden (das erste Plugin, das in der Konfigurationsoption `UserManager` aufgeführt ist).
Das `USING PLUGIN` kann verwendet werden, um einen Benutzer zu kommentieren, der von einem anderen Benutzermanager verwaltet wird.
. Kommentare zu Benutzern werden für den `Legacy_UserManager` nicht gespeichert.
. Kommentare zu Benutzern werden in der Sicherheitsdatenbank gespeichert.
. `SCHEMA` ist derzeit ein Synonym für `DATABASE`;
dies kann sich in einer zukünftigen Version ändern, daher empfehlen wir immer `DATABASE` zu verwenden
====

[WARNING]
====
Kommentare zu Benutzern sind für diesen Benutzer über die virtuelle Tabelle <<fblangref40-appx06-users-de,`SEC$USERS`>> sichtbar.
====

[[fblangref40-ddl-comment-createpriv-de]]
=== Wer kann einen Kommentar hinzufügen

Die `COMMENT ON`-Anweisung kann ausgeführt werden durch:

* <<fblangref40-security-administrators-de,Administratoren>>
* Der Besitzer des Objekts, das kommentiert wird
* Benutzer mit der Berechtigung `ALTER ANY __object_type__`, wobei _object_type_ der Typ des kommentierten Objekts ist (z. B. `PROCEDURE`)

[[fblangref40-ddl-comment-create-exmpl-de]]
=== Beispiele mit `COMMENT ON`

. Kommentar zur aktuellen Datenbank hinzufügen
+
[source]
----
COMMENT ON DATABASE IS 'It is a test (''my.fdb'') database';
----
. Kommentar für die Tabelle `METALS` hinzufügen
+
[source]
----
COMMENT ON TABLE METALS IS 'Metal directory';
----
. Hinzufügen eines Kommentars für das Feld `ISALLOY` in der Tabelle `METALS`
+
[source]
----
COMMENT ON COLUMN METALS.ISALLOY IS '0 = fine metal, 1 = alloy';
----
. Kommentar zu einem Parameter hinzufügen
+
[source]
----
COMMENT ON PARAMETER ADD_EMP_PROJ.EMP_NO IS 'Employee ID';
----
. Hinzufügen eines Kommentars für ein Paket, seine Prozeduren und Funktionen sowie deren Parameter
+
[source]
----
COMMENT ON PACKAGE APP_VAR IS 'Application Variables';

COMMENT ON FUNCTION APP_VAR.GET_DATEBEGIN
IS 'Returns the start date of the period';

COMMENT ON PROCEDURE APP_VAR.SET_DATERANGE
IS 'Set date range';

COMMENT ON
PROCEDURE PARAMETER APP_VAR.SET_DATERANGE.ADATEBEGIN
IS 'Start Date';
----
