[#fbconf-trace-include-filter]
= `include_filter`

Pattern for inclusion of trace events in a trace.

.Trace type
`database`, `services`

.Syntax
[listing,subs="+quotes,+macros"]
----
include_filter = [ <sql-regular-expression> ]

<sql-regular-expression> ::=
  !! See https://firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref50/fblangref50-commons-predicates.html#fblangref50-commons-syntaxregex[Syntax: SQL Regular Expressions] !!
----

What is matched depends on the trace type:

[horizontal.compact]
`database`::
Statement text of a query-related event.
`services`::
Service name of a service-operation-related event.
+
.Supported service names
[#fbconf-trace-service-names]
* Backup Database
* Restore Database
* Repair Database
* Add User
* Delete User
* Modify User
* Display User
* Database Properties
* Database Stats
* Get Log File
* Incremental Backup Database
* Incremental Restore Database
* Fixup Database after FS Copy
* Start Trace Session
* Stop Trace Session
* Suspend Trace Session
* Resume Trace Session
* List Trace Sessions
* Set Domain Admins Mapping to RDB$ADMIN
* Drop Domain Admins Mapping to RDB$ADMIN
* Display User with Admin Info
* Validate Database

Other event types are not subject to inclusion or exclusion.

.See also
<<fbconf-trace-exclude-filter>>
