[#fbconf-trace-log-filename]
= `log_filename`

Path of trace log file (system trace only).

.Trace type
`database`, `services`

.Syntax
[listing,subs=+quotes]
----
log_filename = _path_
----

_path_ is the absolute or relative path of the log file.
This configuration item is only available for system trace configuration.

A backslash must be escaped as `\\`, or -- on Windows -- you can also use `/` as the path separator.

For `database` sections, regular expression references (__sed__-like) for substitutions based on the matched pattern (simple value of the section) are supported.
`\0` -- whole matched string, `\1` ... `\9` -- regular expression groups (parenthesized subexpressions).

// TODO Does Firebird create intermediate directories, or must the directory already exist?
// TODO fbtrace.conf mentions that values with spaces must be enclosed in quotes; verify that, this doesn't seem to be the case since the syntax change in Firebird 3.0 (looking at config_file.cpp)
// TODO fbtrace.conf mentions that values can be enclosed in any quotes; verify that, this doesn't seem to be the case since the syntax change in Firebird 3.0 (looking at config_file.cpp)
// TODO Add some examples, especially with substitution references

.See also
<<fbconf-trace-max-log-size>>
