[#langref-intro]
= About the Firebird 6.0 Language Reference

This Language Reference describes the SQL language supported by Firebird 6.0.

[CAUTION]
====
Firebird 6.0 is not yet released, and this documentation is a work-in-progress to get it up-to-date to Firebird 6.0.

Some new features may not have been documented yet, may have been documented incorrectly or may not yet be complete, or the implementation of a feature may have been changed after it was documented.

If you notice anything missing, errors, or incomplete documentation, please report it on https://github.com/FirebirdSQL/firebird-documentation/issues or on https://groups.google.com/g/firebird-devel[firebird-devel^].
====

This Firebird 6.0 Language Reference is the fifth comprehensive manual to cover all aspects of the query language used by developers to communicate, through their applications, with the Firebird relational database management system.

[#langref-intro-subject]
== Subject

The subject of this volume is Firebird's implementation of the SQL ("`Structured Query Language`") relational database language.
Firebird conforms closely with international standards for SQL, from data type support, data storage structures, referential integrity mechanisms, to data manipulation capabilities and access privileges.
Firebird also implements a robust procedural language -- procedural SQL (PSQL) -- for stored procedures, stored functions, triggers, and dynamically-executable code blocks.
These areas are addressed in this volume.

This document does not cover configuration of Firebird, Firebird command-line tools, nor its programming APIs.
See https://firebirdsql.org/en/firebird-rdbms/[Firebird RDBMS], and specifically https://firebirdsql.org/en/reference-manuals/[Reference Manuals] for more Firebird documentation.

[#langref-intro-authors]
== Authorship

For the Firebird 6.0 version, the _Firebird 5.0 Language Reference_ was taken as the base, and Firebird 6.0 information was added based on the _Firebird 6.0 Release Notes_, feature documentation, Firebird issues, and commit history.

[#langref-intro-contributors]
=== Contributors

[float]
==== Direct Content

* Dmitry Filippov (writer)
* Alexander Karpeykin (writer)
* Alexey Kovyazin (writer, editor)
* Dmitry Kuzmenko (writer, editor)
* Denis Simonov (writer, editor)
* Paul Vinkenoog (writer, designer)
* Dmitry Yemanov (writer)
* Mark Rotteveel (writer, editor)

[float]
==== Resource Content

* Adriano dos Santos Fernandes
* Alexander Peshkov
* Vladyslav Khorsun
* Claudio Valderrama
* Helen Borrie
* ... and others

[#langref-intro-bugs]
== Reporting Errors or Missing Content

If you find errors, missing content or other problems in this document, please report this in our https://github.com/FirebirdSQL/firebird-documentation/issues[issue tracker^] of the https://github.com/FirebirdSQL/firebird-documentation[firebird-documentation GitHub repository^].

Pull requests with changes and fixes are also much appreciated.

[#langref-acknowledgements]
== Acknowledgments

[float]
[[sponsors-donors]]
=== Sponsors and Other Donors

See also the https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref25/firebird-25-language-reference.html#fblangref25-acknowledgements[Acknowledgements^] in the Firebird 2.5 Language Reference for the sponsors of the initial Russian version and its translation.

[#langref-contributing]
== Contributing

There are several ways you can contribute to the documentation of Firebird, or Firebird in general:

* Participate on the https://firebirdsql.org/en/mailing-lists/[mailing lists]
* Report bugs or submit pull requests on the https://github.com/FirebirdSQL/[FirebirdSQL GitHub Project^]
* Become a developer (contact us on https://groups.google.com/g/firebird-devel[firebird-devel^])
* https://www.firebirdsql.org/en/donate/[Donate] to the Firebird Foundation
* Become a paying member or sponsor of the https://firebirdsql.org/en/firebird-foundation/[Firebird Foundation]
