= Asciidoc Migration
Mark Rotteveel
:doctype: article

This document is a collection of notes on the migration of the Firebird documentation from docbook XML to asciidoc.
It is not well-organized, and is intended to record experiments, and tips and tricks for migration.

== Migration tooling

We're using https://github.com/asciidoctor/docbookrx/[docbookrx].
Specifically, we're using the suserx branch from https://github.com/mrotteveel/docbookrx (which is copied from https://github.com/openSUSE/docbookrx/).
This branch contains some additional bugfixes.

See the README.adoc for information on running the tool.

The `bin/docbook` file must be modified to set `idprefix` to `''` and `idseparator` to `'_'`.

== Unsupported docbook features

The docbookrx tool doesn't support the following docbook features, which will require manual fixup.
Make sure to check the output of docbookrx for messages like _"No visitor defined for <segmentedlist>! Skipping."_.

In general the entire content of an unsupported feature does not get included in the target document.

* `<segmentedlist>`
+
Needs to be manually converted to a table (given level of use - 7 times -, not interesting to try and fix in docbookrx).
* `<revhistory>`
+
Needs to be manually converted (TODO: Decide how, or maybe automate)

== Other transformation issues

* Linebreaks and whitespace inside inline-tags are preserved
* Spurious linebreaks + whitespace added after closing inline-tags
* In some situations, the period closing a sentence may appear on its own line as `\$$.$$`
+
Fix: put at end of sentence.

== Other manual fixes to apply:

* Remove `:idprefix:` and `:idseparator:` lines from header
* TODO: check validity of default `:imagesdir:` value
* TODO: `ifdef::showremarks[]` / `endif::showremarks[]` may need to be removed (or the `showremarks` property needs to be added in header)