= Asciidoc Migration
Mark Rotteveel
:doctype: article

This document is a collection of notes on the migration of the Firebird documentation from docbook XML to asciidoc.
It is not well-organized, and is intended to record experiments, and tips and tricks for migration.

== Migration tooling

We're using https://github.com/asciidoctor/docbookrx/[docbookrx].
Specifically, we're using the firebird-modifications branch from https://github.com/mrotteveel/docbookrx (which is copied from https://github.com/openSUSE/docbookrx/).
This branch contains some additional bugfixes.

See the README.adoc for information on running the tool.

The `bin/docbook` file must be modified to set `idprefix` to `''` and `idseparator` to `'_'`.

It is worthwhile to perform an alternative migration using https://www.pandoc.org/[pandoc] and compare the output.
This can hint at missing features or text.

== Unsupported docbook features

The docbookrx tool doesn't support the following docbook features, which will require manual fixup.
Make sure to check the output of docbookrx for messages like _"No visitor defined for <segmentedlist>! Skipping."_.

In general the entire content of an unsupported feature does not get included in the target document.

* Multi-row headers in a table
+
The `options="header"` needs to be removed, and the header needs to be manually constructed (eg using `h`, `.2+`, and other cell prefixes).

=== Fixed issues

The firebird-modifications branch of docbookrx contains fixes for

* `<segmentedlist>`
+
This will always convert to a table.
* `<revhistory>`
+
Will be converted to a four-column table
* `<title>` with index terms spread out over multiple lines, breaking rendering in multiple ways (missing title)
* Tables with a multi-row header will print out a warning

== Other transformation issues

* Linebreaks and whitespace inside inline-tags are preserved
* Spurious linebreaks + whitespace added after closing inline-tags
* In some situations, the period closing a sentence may appear on its own line as `\$$.$$`
+
Fix: put at end of sentence.

== Other manual fixes to apply:

* Remove `:idprefix:` and `:idseparator:` lines from header
* TODO: check validity of default `:imagesdir:` value
* TODO: `ifdef::showremarks[]` / `endif::showremarks[]` may need to be removed (or the `showremarks` property needs to be added in header)