= Asciidoc Migration
Mark Rotteveel
:doctype: article
:sectnums:
:sectanchors:
:toc: left
:icons: font
:experimental:
:imagesdir: ../images

This document is a collection of notes on the migration of the Firebird documentation from docbook XML to asciidoc.
It is not well-organized, and is intended to record experiments, and tips and tricks for migration.

== Migration tooling

We're using https://github.com/asciidoctor/docbookrx/[docbookrx].
Specifically, we're using the firebird-modifications branch from https://github.com/mrotteveel/docbookrx (which is copied from https://github.com/openSUSE/docbookrx/).
This branch contains some additional bugfixes.

See the README.adoc for information on running the tool.

The `bin/docbook` file must be modified to set `idprefix` to `''` and `idseparator` to `'_'`.

It is worthwhile to perform an alternative migration using https://www.pandoc.org/[pandoc] and compare the output.
This can hint at missing features or text.

== Unsupported docbook features

The docbookrx tool doesn't support the following docbook features, which will require manual fixup.
Make sure to check the output of docbookrx for messages like _"No visitor defined for <segmentedlist>! Skipping."_.

In general the entire content of an unsupported feature does not get included in the target document.

* Multi-row headers in a table
+
The `options="header"` needs to be removed, and the header needs to be manually constructed (eg using `h`, `.2+`, and other cell prefixes).
* Relative widths expressed through colspec are ignored, this needs to be fixed manually
* `<sectioninfo>` is not supported (partially fixed)
* `<chapterinfo>` is not supported (partially fixed)
* `<simplelist>` with type other than `horiz` (or `inline`) will be converted to a normal list
+
The modified docbookrx will log a warning
+
Suggested replacement, table with `[cols="3*",frame=none,grid=none,stripes=none]` (where `cols` value has the number of columns)
* HTML-style `<table>` is not supported.
* Spanned rows are (not always) handled

=== Fixed issues

The firebird-modifications branch of docbookrx contains fixes for

* `<segmentedlist>`
+
This will always convert to a table.
* `<revhistory>`
+
Will be converted to a four-column table
* `<title>` with index terms spread out over multiple lines, breaking rendering in multiple ways (missing title)
* Tables with a multi-row header will print out a warning
* Tables without `thead` would produce an error and crash conversion
* Support for `superscript` and `subscript`
* Support for inline type `errorcode`
* Minimal support for `<sectioninfo>` and `<chapterinfo>` to extract authors.
+
A warning _Possibly incomplete handling of ..._ with title and - if available - id is written to the console.
* code-literals within quotes may render incorrectly (eg `<quote><literal>=</literal></quote>`)
* Missing id on admonitions and sidebars
* Subtitle of book or article is missing
* If a book has an abstract, this is put before the document attributes, causing those attributes to not be applied.
* `<sgmltag>` is handled as an anonymous literal, the `class` attribute is not preserved.
For `class="starttag"`, `class="endtag"`, `class="emptytag"`, `class="genentity"` additional fixes must be applied.

== Open questions

* Currently all files generated by docbookrx are top-level files, meaning they will be rendered individually and when they are included.
The asciidoc conventions for partials like this is to start the filename with an underscore.
The alternative is too explicitly define which top-level files to build.
Using the underscore prefix conventions is probably the least intrusive option.

== Other transformation issues

* Linebreaks and whitespace inside inline-tags are preserved (partially fixed)
* Spurious linebreaks + whitespace added after opening or closing inline-tags (partially fixed)
* In some situations, the period closing a sentence may appear on its own line as `\$$.$$`
+
Fix: put at end of sentence.
* The sources contain HTML entities which in plain XML are just (undefined) entity refs.
The tool will convert these to asciidoc attribute refs, from - for example - `\&mdash;` to `{mdash}`.
+
Given the next item, it is probably best to replace these entities with character entities (eg `\&#8212;`).
* Our docbook sources do not always conform to the docbook schema, and during conversion this can cause problems like missing content.
Examples include listitems with bare content, instead of - for example - `para` elements.
These are issues that need to be addressed before conversion.
* Nested lists with attributes may have additional linebreaks before them.
The nested list is then rendered as a new list
* Lists with literals are on a single line, breaking the list (eg Reserved words in fblangref25)
+
Fixed by a different change to docbookrx
* asciidoctor-pdf doesn't support level 7 headers, restructure the document to reduce nesting of sections.

== Other manual fixes to apply:

* Add ':sectanchors:' to header
* Add copyright information to preamble or the preface (above the abstract)
+
Look for other attributions that may need to be added to this preface.
* Add `toc::[]` macro after the preamble to ensure correct placement of the TOC in PDF
* Replace `:imagesdir:` with correct value (that is point - relative - to the `src/docs/asciidoc/<language>/images` directory)
* TODO: `ifdef::showremarks[]` / `endif::showremarks[]` may need to be removed (or the `showremarks` property needs to be added in header)
* Update values of `<sgmltag>` with `class="starttag"`, `class="endtag"` or `class="emptytag"` by enclosing values with `<...>`, `</...>` or `<.../>`.
* Update values of `<sgmltag>` with `class="genentity"` by enclosing values with `&...;`