= Conventions for Firebird asciidoc
:doctype: article
:sectnums:
:sectanchors:
:toc: left
:icons: font
:experimental:
:imagesdir: ../images

This article documents the conventions used (or even required) for Firebird asciidoc documentation.

== Style

Line breaking convention: a single sentence per line, no line breaks within a sentence.
If a line becomes too long, take that as a hint to rewrite (if possible).

Converted documentation may not always adhere to this style due to limitations of the converter.
These style inconsistencies should only be addressed when touching a paragraph for other reasons.

== Documentation structure

Group documents per language in `src/asciidoc/<language>`.
Inside the language directory, group documents by _base_, that is _firebirddocs_, _papers_, _refdocs_ and _rlsnotes_.
Inside the _base_, use a directory per book or article.

In other words, the directory for a document is `src/asciidoc/<language>/<base>/<document-name>`.

A book or article can consist of a single asciidoctor file (extension `.adoc`), or multiple `.adoc` files.
When a book or article has multiple files, there should be a single root file, with the same name as its parent directory.
The root file will link to one or more asciidoctor fragment files.
These fragment files should be prefixed with `_`.
The use of `_` as a prefix is a convention established by the asciidoctor tools, and will prevent files to be processed both individually and as part of a larger document.

For example, the Firebird 2.5 Language Reference, English should be located in `src/asciidoc/en/refdocs/fblangref25`

It has the following files (not all files listed):

`fblangref25.adoc`:: root file
`_fblangref25-intro.adoc`:: fragment with the introduction chapter
`_fblangref25-appx01-supplement.adoc`:: fragment with an appendix with supplementary information
`...`:: etcetera

== Images

Store images per language in `src/asciidoc/<language>/images`.
Put images shared by multiple documents in the root of this directory, images shared only in a specific _base_ in `src/asciidoc/<language>/images/<base>`, and images for a specific document in `src/asciidoc/<language>/images/<base>/<document-name>`.

A document has to explicitly define the `imagesdir` location.
Given the documentation structure, its value should normally be `../../images`.
Explicitly defining this in each document allows for deviation from the defined structure if necessary.

== Standard attributes for a document

The header of a document should normally include the following attributes:

// TODO: Could need further refinement

----
:doctype: book           <1>
:sectnums:               <2>
:sectanchors:            <3>
:toc: left               <4>
:toclevels: 3            <5>
:icons: font             <6>
:experimental:           <7>
:imagesdir: ../../images <8>
----
<1> Defines the document type (normally `book` or `article`)
<2> Enables section numbering
<3> Adds _section anchors_ in HTML output to easily get a link to a section
<4> Add a TOC (Table Of Contents), in HTML output the TOC will be added left
<5> Generate TOC three levels deep (NOTE: TOC in HTML has been customized and ignores this setting)
<6> Use admonition icons
<7> Enable experimental features
<8> Relative path to the directory with images
