[#fbconf-plugins]
= `plugins.conf`

The file `plugins.conf` contains the configuration for various plugins to Firebird.

The file has two types of configuration items with <<fbconf-syntax-scope,scoped values>>:

[horizontal.compact]
<<fbconf-plugins-item-plugin>>::
Registration of a plugin
<<fbconf-plugins-item-config>>::
Configuration of a plugin

[#fbconf-plugins-item-plugin]
== `Plugin`

The `Plugin` item contains the registration information of a plugin.

.Syntax
[listings,subs=+quotes]
----
Plugin = _plugin-name_
{
  [ Module = _module-name_ ]
  [ RegisterName = _register-name_ ]
  [ Config = _config-name_ ]
  [ ConfigFile = _config-filename_ ]
}
----

.Plugin configuration parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|plugin-name
|Name of the plugin used by Firebird to look up -- or, load -- the plugin.

|module-name
|Name of the dynamic library containing the plugin.
If not specified, _plugin-name_ is used.

|register-name
|Name of the plugin in the dynamic library.
If not specified, _plugin-name_ is used.

|config-name
|Name of the <<fbconf-plugins-item-config>> item in this `plugins.conf` containing the plugin-specific configuration.

|config-filename
|Name of the configuration file with the plugin-specific configuration.
The file should use simple <<fbconf-syntax-kv,key-value syntax>> as used by `firebird.conf`.

|===

If both `Config` and `ConfigFile` are specified, `Config` will be used.

If neither `Config` nor `ConfigFile` are specified, the configuration will be resolved as follows:

. If a file `__module-name__.conf` exists, that will be used as `ConfigFile`
. Otherwise, `Config` is set to _plugin-name_.

These rules also apply to implicitly loaded plugins.

.Registration in `plugins.conf` is optional
[NOTE]
====
For simple cases, the presence of the plugin library in the `plugins` folder is sufficient for a plugin to work.
Those plugins are defined _implicitly_.

Registration in `plugins.conf` is only necessary when:

* The plugin has a different name than the module/library name.
+
This can be used if you want to use a different name than the original name, or the module contains multiple plugins with different names.
+
For example, in the default `plugins.conf` this is used for the `ChaCha64` plugin, which is part of the `ChaCha` module.
* The plugin requires additional configuration.
+
For example, in the default `plugins.conf` this is used to configure the `path` configuration item of the `UDR` plugin.
* You have multiple plugins with the same name;
you need to give them different names so Firebird can distinguish between them.
====

[#fbconf-plugins-item-config]
== `Config`

The `Config` item contains the configuration of a specific plugin.

.Syntax
[listings,subs=+quotes]
----
Config = _config-name_
{
  { _key-name_ = _value_ <new-line> }...
}
----

.Config configuration parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|config-name
|Configuration name, as referenced from a <<fbconf-plugins-item-plugin>> item.

|key-name
|Configuration key;
plugin-specific

|value
|Value for configuration key _key-name_;
plugin-specific

|===

Each key-value pair must be on a line of its own.

Supported values of _key-name_ and _value_ are plugin-specific.
