[#fbconf-replication]
= `replication.conf`

[NOTE]
====
The author has little experience with Firebird replication, so it's possible that the descriptions here are lacking in detail or practicality.

Feedback, additions, or corrections are highly appreciated.
Do not hesitate to contact us on https://groups.google.com/g/firebird-devel[firebird-devel^] or through the https://github.com/FirebirdSQL/firebird-documentation/issues[firebird-documentation issue tracker^], or submit a pull request to the https://github.com/FirebirdSQL/firebird-documentation[firebird-documentation] repository.
====

The `replication.conf` file configures replication between databases.

This section serves as a reference for the configuration items in `replication.conf`;
it does not cover -- nor is it intended to cover -- all aspects of Firebird replication.
At time of writing, only the https://firebirdsql.org/file/documentation/release_notes/html/en/4_0/rlsnotes40.html#rnfb40-replication[_Firebird 4.0 Release Notes_] and https://github.com/FirebirdSQL/firebird/blob/master/doc/README.replication.md[`doc/README.replication.md`]footnote:[This link is to the master branch of the Firebird repository, so it may document unreleased features or changes] in a Firebird installation document replication.

[#fbconf-repl-syntax]
== Replication syntax

The syntax of `replication.conf` has two types of configuration:

. server level (applies to all databases)
+
[listing,subs=+quotes]
----
database
'{'
  { _key-name_ = _simple-value_ <new-line> }...
'}'
----
+
This is essentially a <<fbconf-syntax-scope,scoped value>> _without_ an equals ('```=```') and simple value
. database level (applies to a specific database)
+
[listing,subs=+quotes]
----
database = _database-path_
'{'
  { _key-name_ = _simple-value_ <new-line> }...
'}'
----
+
This is a <<fbconf-syntax-scope,scoped value>>.
+
The _database-path_ must be a valid absolute or relative path;
aliases or wildcards cannot be used.

The database-level settings override those set on server-level.

[#fbconf-repl-cfg]
== Configuration items

The following sections list the configuration items supported in the scoped values of `replication.conf`.

// TODO Consider grouping the items by subject
// Initially, we list them in the order of replication.conf
The configuration items are listed in order of appearance in the default `replication.conf` file.

[discrete#fbconf-repl-cfg-primary]
=== Primary side

The following configuration items only affect the primary side (a.k.a. master) of replication.

include::replicationconf/_plugin.adoc[leveloffset=+2]

include::replicationconf/_include-filter.adoc[leveloffset=+2]

include::replicationconf/_exclude-filter.adoc[leveloffset=+2]

include::replicationconf/_log-errors.adoc[leveloffset=+2]

include::replicationconf/_report-errors.adoc[leveloffset=+2]

include::replicationconf/_disable-on-error.adoc[leveloffset=+2]

[discrete#fbconf-repl-cfg-primary-default]
=== Primary configuration items of built-in replication

The following configuration items are specific to configure the primary side of the built-in (default) replication.
If you use a third-party replication plugin, consult the documentation of your replication plugin for its configuration items.

include::replicationconf/_buffer-size.adoc[leveloffset=+2]

include::replicationconf/_journal-directory.adoc[leveloffset=+2]

include::replicationconf/_journal-file-prefix.adoc[leveloffset=+2]

include::replicationconf/_journal-segment-size.adoc[leveloffset=+2]

include::replicationconf/_journal-segment-count.adoc[leveloffset=+2]

include::replicationconf/_journal-group-flush-delay.adoc[leveloffset=+2]

include::replicationconf/_journal-archive-directory.adoc[leveloffset=+2]

include::replicationconf/_journal-archive-command.adoc[leveloffset=+2]

include::replicationconf/_journal-archive-timeout.adoc[leveloffset=+2]

include::replicationconf/_sync-replica.adoc[leveloffset=+2]

[discrete#fbconf-repl-cfg-replica]
=== Replica side

The following settings only affect the replica side (a.k.a. secondary or slave) of replication.

// TODO Does a configuration need to be present if the replica is a target of synchronous replication?

include::replicationconf/_cascade-replication.adoc[leveloffset=+2]

// Phrasing in replication.conf suggest the replica is also pluggable, and the following settings only apply to the built-in replication, but it is not pluggable, so this distinction is (currently?) not relevant.
//[discrete#fbconf-repl-cfg-replica-default]
//=== Replica configuration items of built-in replication

include::replicationconf/_journal-source-directory.adoc[leveloffset=+2]

include::replicationconf/_source-guid.adoc[leveloffset=+2]

include::replicationconf/_verbose-logging.adoc[leveloffset=+2]

include::replicationconf/_apply-idle-timeout.adoc[leveloffset=+2]

include::replicationconf/_apply-error-timeout.adoc[leveloffset=+2]
