[#fbconf-overview]
= An overview of Firebird configuration

The configuration of Firebird is distributed over a number of files and other configuration methods.
In broad strokes, the configuration is split over:

<<fbconf-firebird>>::
Global configuration of Firebird server and/or the client library

<<fbconf-databases>>::
Database aliases, and per-database configuration of Firebird server and/or client library

<<fbconf-plugins>>::
Plugin configuration

`replication.conf`::
Global and per-database replication configuration

Trace configuration::
Global and per-database trace configuration (system configuration by default in `fbtrace.conf`, users may start traces using the services API using the same syntax)

Environment variables::
Configuration of file locations for the server process

Database file::
Some per-database configuration is stored in the database header or in system tables of a specific database

//`plugins/udr_engine.conf`::
//UDR engine configuration

The following chapters will cover each file in detail.

[#fbconf-syntax]
== Shared syntax of configuration files

The configuration files (`{asterisk}.conf`) share a common syntax, though not all files use all available syntax options.

// TODO Verify if I am not assuming too much commonality here

[#fbconf-syntax-kv]
=== Key-value

In its most basic form, configuration is expressed as a list of key-value pairs:

.Syntax
[listing,subs=+quotes]
----
_key-name_ = _value_
----

.Example
[listing]
----
DatabaseAccess = None
----

Allowed _values_ depend on the specific key, but broadly has the following types:

integer::
Integer values, or integers followed by `K` (kilo: 1024), `M` (mega: 1024^2^ or 1,048,576) or `G` (giga: 1024^3^ or 1,073,741,824).
Boolean::
Truth values, where `0` is false and `1` (and any other non-zero integer value) is true.
Strings `true`, `y` and `yes` are also interpreted as true, everything else as `false`.
+
We recommend only using `0`/`1` _or_ `true`/`false` for Boolean values.
+
Currently, a non-numeric suffix of an integer prefix is ignored, so `123text` is interpreted as 123 -> true, not false.
This is an implementation artefact that may change in the future.
string::
String values;
individual properties may require a specific syntax in their string values, or a limited set of values, etc.
list::
List of values;
a list is a string value with values separated by a space ('``` ```'), comma ('```,```'), or semicolon ('```;```').
The order is usually significant.
Some lists may use only a subset of separators;
this will be mentioned explicitly if relevant.
scoped values::
Some configuration files (e.g. `databases.conf`, `plugins.conf`) allow keys with a string value followed by additional key-value pairs enclosed in braces.
+
See <<fbconf-syntax-scope>> for more information.

A (non-scoped) value can optionally be enclosed in double quotes.
The entire value must be quoted, and anything other than a comment or whitespace after the closing double quote is considered an error.
This can -- for example -- be used if the value contains a '```++#++```' (e.g. `++Key = "some#value"++`).
Unquoted, the '```++#++```' is interpreted as the start of a <<fbconf-syntax-comment,comment>>.

// TODO Case-sensitivity of keys and values

[#fbconf-syntax-scope]
=== Scope

Some configuration files use scopes.
Scopes are key-value pairs or keyword-value pairs enclosed in braces ('```++{++```' and '```++}++```').
Their exact usage and syntax depend on the specific configuration file.

In general, the syntax is:

.Key or keyword + scoped value syntax
[listing]
----
<key-or-keyword> = <simple-value>
{
  [<key> = <simple-value>]...
}
----

We call the part after the `=` (equals) a __scoped value__footnote:scoped[The term _scoped value_ is specific to this documentation, other Firebird documentation do not use this name (yet)].

For example, `databases.conf` has key-value pairs, where the value is either a string (simple-value), or a scoped value (string + scope):

.Scoped value in `databases.conf`
[listing]
----
# key employee with simple value
employee = $(dir_sampleDb)/employee.fdb

# key security.db with scoped value
security.db = $(dir_secDb)/security4.fdb
{
	RemoteAccess = false
	DefaultDbCachePages = 256
}
----

In this example, `security.db` is the _key_, and the string `$(dir_secDb)/security4.fdb` *and* the key-value pairs between braces are the value of `security.db`.
The configuration options `RemoteAccess` and `DefaultDbCachePages` are applied specifically to the security database (alias `security.db`).

As another example, _trace configuration_, `plugins.conf` and `replication.conf` have keyword-value pairs, where the value is (always) a scoped value

.Scoped value in `replication.conf`:
[listing]
----
database = /your/db.fdb
{
  journal_source_directory = /your/db/source
}
----

Here `database = /your/db.fdb` identifies this as replication configuration specific to the database `/your/db.fdb`, with the actual configuration listed within the braces.

[#fbconf-syntax-comment]
=== Comments

A '```++#++```' starts a comment, until the end of that line.
Comments are ignored by the configuration parser.

Comments are used in the default configuration files for documentation, and to show default values without explicitly configuring those values.

For your own use, you can use comments to temporarily disable a configuration item or revert to the default.
You can also use comments to record why a specific configuration value was chosen (e.g. by specifying a rationale, or a link to an external document, etc.).

If you need to specify a <<fbconf-syntax-kv,value>> that contains the '```++#++```' symbol, enclose the value in double quotes (e.g. `++Key = "some#value"++`).

[#fbconf-syntax-macro]
=== Macro substitution

Firebird provides a number of predefined macros which can be used in configuration values to substitute directory locations.

The syntax to use these macros is `$(_macro-name_)` (e.g. `$(dir_plugins)`).

It is not possible to define or specify your own custom macros.

.Available configuration macros
[horizontal.compact]
`root`::
root of the Firebird instance
`install`::
directory where Firebird is installed
`this`::
directory containing the current configuration file
`dir_conf`::
directory containing `firebird.conf` and `databases.conf`
`dir_secDb`::
directory containing the default security database
`dir_plugins`::
directory containing the plugins
`dir_udf`::
default directory containing UDFs
// TODO Does this macro still exist now Firebird 5 no longer includes UDFs?
`dir_sample`::
example directory
`dir_sampleDb`::
directory containing the example DB (`employee.fdb`)
`dir_intl`::
directory containing international modules
`dir_msg`::
directory containing the messages file (`firebird.msg`)

The macro names are case-insensitive.

[#fbconf-syntax-include]
=== Include

The `include` statement allows you to include the content of another file when the configuration file is read.

.Syntax
[listing,subs=+quotes]
----
include _path-expression_
----

Where _path-expression_ is a string identifying the file or files to include.
The _path-expression_ supports:

* Relative paths (resolved against the current configuration file)
* Absolute paths
* <<fbconf-syntax-macro>>
* Wildcards (`{asterisk}` for zero or more characters, and `?` for one character)

.Examples
----
# Relative path
include some_file.conf

# Which is equivalent to
include $(this)/some_file.conf

# Absolute path (Windows)
include C:\Firebird\default.conf

# Absolute path (Linux)
include /opt/firebird/default.conf

# Path with macro substitution
include $(dir_plugins)/some_file.conf

# Wildcard to include multiple files
include databases/*.conf
----

[TIP]
====
On Windows you can use either `\` or `/` as the path separator.
On Linux you can only use `/`.
====
