[#fbconf-firebird]
= `firebird.conf`

The `firebird.conf` configuration file serves three purposes:

. Configuring the Firebird server process
. Configuring client connections made by the Firebird server
+
For example, for connections made with https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-psql-execstmt-onexternal[`EXECUTE STATEMENT ... ON EXTERNAL`]
. Configuring client connections made by other processes.
+
This is basically the general case of the second item.

The third item does have a big caveat.
The `firebird.conf` in the Firebird installation directory will not configure *all* client connections, only those client connections which

. use `fbclient.dll`/`libfbclient.so`, and
. where the _fbclient_ library actually reads that `firebird.conf` file.

If your application uses its own `fbclient.dll`, it will read and use the client configuration in the `firebird.conf` in the same directory as that DLL, _if it exists_, not the `firebird.conf` in a Firebird installation directory.

The configuration used by a client can also be overridden using the `isc_dpb_config` information item.
Its content are key-value pairs as used in `firebird.conf`, and their values will take precedence over the client configuration in the `firebird.conf`.

Some server-side configuration items in `firebird.conf` can also be configured per database in <<fbconf-databases,`databases.conf`>>.
The value in `databases.conf` takes precedence over the value in `firebird.conf`, which takes precedence over the default value.
If a value is user-configurable (e.g. through the DPB or a `SET` statement), that value will generally take precedence for the current connection, though in some cases the server configuration may establish an upper limit (e.g. for timeouts).

Since Firebird 4.0, it is possible to query configuration settings of the current database for the current connection from the https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref-appx04-config[`RDB$CONFIG`] virtual table:

[source,sql]
----
select * from RDB$CONFIG
----

[#fbconf-cfg]
== Configuration items

The following sections list the configuration items supported in `firebird.conf`.
If a configuration item is also valid in `databases.conf`, this will be mentioned explicitly.

Unless mentioned explicitly, configuration items are server-side only.

Where applicable, we'll report the version that a configuration item was added, deprecated, or removed;
see also <<fbconf-intro-conventions>>.

// TODO Consider grouping the items by subject
// Initially, we list them in the order of firebird.conf

include::firebirdconf/_database-access.adoc[leveloffset=+2]

include::firebirdconf/_remote-access.adoc[leveloffset=+2]

include::firebirdconf/_external-file-access.adoc[leveloffset=+2]

include::firebirdconf/_udf-access.adoc[leveloffset=+2]

include::firebirdconf/_temp-directories.adoc[leveloffset=+2]

include::firebirdconf/_temp-table-directory.adoc[leveloffset=+2]

include::firebirdconf/_audit-trace-config-file.adoc[leveloffset=+2]

include::firebirdconf/_max-user-trace-log-size.adoc[leveloffset=+2]

include::firebirdconf/_default-db-cache-pages.adoc[leveloffset=+2]

include::firebirdconf/_database-growth-increment.adoc[leveloffset=+2]

include::firebirdconf/_use-file-system-cache.adoc[leveloffset=+2]

include::firebirdconf/_file-system-cache-threshold.adoc[leveloffset=+2]

include::firebirdconf/_file-system-cache-size.adoc[leveloffset=+2]

include::firebirdconf/_remote-file-open-ability.adoc[leveloffset=+2]

include::firebirdconf/_temp-block-size.adoc[leveloffset=+2]

include::firebirdconf/_temp-cache-limit.adoc[leveloffset=+2]

include::firebirdconf/_max-identifier-byte-length.adoc[leveloffset=+2]

include::firebirdconf/_max-identifier-char-length.adoc[leveloffset=+2]

include::firebirdconf/_inline-sort-threshold.adoc[leveloffset=+2]

include::firebirdconf/_auth-server.adoc[leveloffset=+2]

include::firebirdconf/_auth-client.adoc[leveloffset=+2]

include::firebirdconf/_user-manager.adoc[leveloffset=+2]

include::firebirdconf/_trace-plugin.adoc[leveloffset=+2]

include::firebirdconf/_wire-crypt-plugin.adoc[leveloffset=+2]

include::firebirdconf/_key-holder-plugin.adoc[leveloffset=+2]

include::firebirdconf/_allow-encrypted-security-database.adoc[leveloffset=+2]

include::firebirdconf/_providers.adoc[leveloffset=+2]

include::firebirdconf/_deadlock-timeout.adoc[leveloffset=+2]

include::firebirdconf/_statement-timeout.adoc[leveloffset=+2]

include::firebirdconf/_connection-idle-timeout.adoc[leveloffset=+2]

include::firebirdconf/_on-disconnect-trigger-timeout.adoc[leveloffset=+2]

include::firebirdconf/_max-unflushed-writes.adoc[leveloffset=+2]

include::firebirdconf/_max-unflushed-write-time.adoc[leveloffset=+2]

include::firebirdconf/_bugcheck-abort.adoc[leveloffset=+2]

include::firebirdconf/_clear-gtt-at-retaining.adoc[leveloffset=+2]

include::firebirdconf/_relaxed-alias-checking.adoc[leveloffset=+2]

include::firebirdconf/_read-consistency.adoc[leveloffset=+2]

include::firebirdconf/_data-type-compatibility.adoc[leveloffset=+2]

include::firebirdconf/_connection-timeout.adoc[leveloffset=+2]
