[#fbconf-environment-variables]
= Environment variables

Firebird supports a number of environment variables to configure Firebird server and/or _fbclient_.

[#fbconf-env-std]
== Standard environment variables

The following are the environment variables Firebird supports in normal builds.
This documentation does not cover environment variables for debug builds.

// In alphabetical order

include::env/_editor.adoc[leveloffset=+2]

include::env/_fb-expected-db.adoc[leveloffset=+2]

include::env/_firebird.adoc[leveloffset=+2]

include::env/_firebird-lock.adoc[leveloffset=+2]

include::env/_firebird-msg.adoc[leveloffset=+2]

include::env/_firebird-tmp.adoc[leveloffset=+2]

include::env/_icu-timezone-files-dir.adoc[leveloffset=+2]

include::env/_isc-inet-server-home.adoc[leveloffset=+2]

include::env/_isc-msgs.adoc[leveloffset=+2]

include::env/_isc-password.adoc[leveloffset=+2]

include::env/_isc-path.adoc[leveloffset=+2]

include::env/_isc-user.adoc[leveloffset=+2]

include::env/_visual.adoc[leveloffset=+2]

////
Other environment variables found in Firebird sources (master - December 2025; Firebird 7):

YYDEBUG (debug build only; dsql/parse.cpp)
INET_force_error (debug build only; remote/inet.cpp)
LC_CTYPE (common/isc_file.cpp) -- leave out for now, seems "standard" use of LC_CTYPE OS environment var
MISSING_ICU_EMULATION (debug build only; common/TimeZoneUtil.cpp)
FIREBIRD_BOOT_BUILD (common/utils.cpp) -- treat as debug, even if not formally debug)
LC_MESSAGES (yvalve/gds.cpp) -- leave out, covered in description of ISC_MSGS
FIREBIRD_DEV (debug build only variant of FIREBIRD; yvalve/config/os/config_root.h)
ISC_DEBUG_AUTH (debug build only; auth/AuthDbg.cpp)
////
