[#fbconf-intro]
= About this manual

Firebird is a relational database management system.
In simple use-cases, you can install it and use its default configuration.
For more advanced use-cases, or when you want to tune Firebird to get more performance, you will need to dig into its configuration options.

This manual is a reference for all configuration options that Firebird exposes in its configuration files, as environment variables, and -- for a limited subset -- options configured through command line tools like _gfix_ and SQL statements like `CREATE DATABASE` or `ALTER DATABASE`.

.Work in progress
[WARNING]
====
This manual is still in its infancy, so at this time, it is far from complete.
If you're missing anything or want to make suggestions for improvements, do not hesitate to contact us on https://groups.google.com/g/firebird-devel[firebird-devel^] or through the https://github.com/FirebirdSQL/firebird-documentation/issues[firebird-documentation issue tracker^].
====

[#fbconf-intro-versions]
== Firebird versions

This document covers Firebird 4.0 and Firebird 5.0.
Our intent is to keep it up-to-date with new, deprecated or removed configuration options as versions are released.

We do not document configuration options for Firebird 3.0 or older if they no longer exist in Firebird 4.0.

[#fbconf-intro-conventions]
== Conventions

This manual covers multiple versions.
New Firebird versions may add new configuration options, deprecate configuration options (i.e. use is discouraged but still supported), and even remove configuration options entirely.

For each configuration option, we document the version that added, deprecated or removed an option.

For example, say an option is added in Firebird 4.0, deprecated in 5.0, and removed in 6.0, that would be shown as:

[horizontal.compact]
Added:: 4.0
Deprecated:: 5.0
Removed:: 6.0

If an option is added/deprecated/removed in a point release, the point-release version (e.g. 4.0.3) will be used.

For an option which is added in Firebird 5.0, and not deprecated and removed, it just shows:

[horizontal.compact]
Added:: 5.0

If an option already existed in Firebird 3.0 or older, we do not show an _Added_ item.
However, if an option was deprecated in an older version, and still exists in Firebird 4.0, it is listed with the version that deprecated it.

For example:

[horizontal.compact]
Deprecated:: 2.0

Options which were removed with or before Firebird 4.0.0 are not documented.

// TODO Document how we handle changes between versions (e.g. new config values or changes in behaviour)

[#fbconf-intro-other]
== Where to get more information

For news and information on Firebird, visit https://firebirdsql.org/[].

For more Firebird documentation, go to:

* https://firebirdsql.org/en/firebird-rdbms/[Firebird RDBMS Documentation]
** https://firebirdsql.org/en/release-notes/[Release Notes]
** https://firebirdsql.org/en/reference-manuals/[Reference Manuals]
*** https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref50/firebird-50-language-reference.html[Firebird 5.0 Language Reference]
*** https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html[Firebird 4.0 Language Reference]
*** ...see full list on https://firebirdsql.org/en/reference-manuals/[Reference Manuals]...
** ...see more options on https://firebirdsql.org/en/firebird-rdbms/[Firebird RDBMS Documentation]...

If you're looking for help on Firebird, subscribe to https://groups.google.com/g/firebird-support[firebird-support^]. +
Other mailing lists and groups can be found on https://firebirdsql.org/en/mailing-lists/[Mailing Lists].

[#fbconf-intro-bugs]
== Reporting errors or missing content

If you find errors, missing content or other problems in this document, please report this in our https://github.com/FirebirdSQL/firebird-documentation/issues[issue tracker^] of the https://github.com/FirebirdSQL/firebird-documentation[firebird-documentation GitHub repository^].

Pull requests with changes and fixes are also much appreciated.

[#fbconf-intro-contrib]
== Contributing

There are several ways you can contribute to the documentation of Firebird, or Firebird in general:

* Participate on the https://firebirdsql.org/en/mailing-lists/[mailing lists]
* Report bugs or submit pull requests on the https://github.com/FirebirdSQL/[FirebirdSQL GitHub Project^]
* Become a developer (contact us on https://groups.google.com/g/firebird-devel[firebird-devel^])
* https://firebirdsql.org/en/donate/[Donate] to the Firebird Foundation
* Become a paying member or sponsor of the https://firebirdsql.org/en/firebird-foundation/[Firebird Foundation]
