[#fbconf-trace]
= Trace configuration

The trace facility of Firebird can be used to trace (record) various types of actions (e.g. connect, prepare, execute, commit) for databases and services.
See also https://firebirdsql.org/file/documentation/release_notes/html/en/2_5/rnfb25-trace.html[_Trace and Audit Services_] in the _Firebird 2.5 Release Notes_.
Beware, the configuration syntax changed between Firebird 2.5 and Firebird 3.0.

Server administrators can use the _system trace_ to trace actions for services, all databases, or a subset of databases.
The system trace can be configured in a configuration file, whose path is set in configuration item <<fbconf-audit-trace-config-file>> in `firebird.conf`.
A default Firebird installation contains a file `fbtrace.conf` that shows the layout and configuration items for a system trace;
this file is *not* used by default (the default value of `AuditTraceConfigFile` is empty, meaning no system trace).

Any user can start and manage a _user trace_ using the services API.
An ordinary user -- not an administrator, and without the `TRACE_ANY_ATTACHMENT` https://firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref50/fblangref50-security.html#fblangref50-security-sys-privs[system privilege] -- can request a trace only on their own connections, and cannot manage trace sessions started by other users.
Administrators can manage any user trace session.

The configuration of a user trace is sent as a string to the services manager, with the same syntax as the system trace configuration file.

The actual trace output is handled by a plugin, configured in <<fbconf-trace-plugin>> in `firebird.conf`.
This documentation assumes the default trace plugin included with Firebird, `fbtrace`.

[#fbconf-trace-syntax]
== Trace configuration syntax

The trace configuration has two main keywords.

`services`::
The `services` keyword only has a <<fbconf-syntax-scope>>;
that is, it does not have `= _simple-value_`.
This default section contains the entire trace configuration for all services.

`database`::
The `database` keyword is a <<fbconf-syntax-scope,scoped value>>.
It is used to configure tracing databases.
+
The `database` keyword can occur without `= _simple-value_` and only a scope -- the default section.
The default section contains the trace configuration items for all databases, and establishes defaults that can be overridden by a later occurrence of a `database` section with a simple value.

The simple value of a non-default database section is either a database filename without path or a https://firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref50/fblangref50-commons-predicates.html#fblangref50-commons-syntaxregex[SQL regular expression] pattern which is matched against the absolute path of the database file.

[NOTE]
====
Firebird 2.5 used a different syntax for trace configuration.
This reference does not cover that syntax.

The order of evaluation and description of configuration items (but *not* their syntax) are generally the same -- assuming the configuration item existed in that version.
====

[#fbconf-trace-syntax-order]
=== Order of evaluation

A trace configuration has the following order of evaluation rules to match a database or service

* the configuration is processed from top to bottom
// TODO Verify if this means that defaults are not applied if a non-default section occurs before the default section
* configuration items of a default section are applied for all databases or services
** only one default section of each type is allowed
** for a service, search ends
** for a database, search continues
* if a database name matches the pattern of a non-default section
** its configuration items are applied
** search ends

In other words, there can only be one (default) `services` section, and one default `database` section.
At most one other `database` section (with value) is used for a database, the first one to match.
// TODO May need stricter phrasing depending on how order of evaluation actually applies

[#fbconf-trace-cfg]
== Trace configuration items

The following are the configuration items available for trace configuration.
Some configuration items apply to both trace types (`database` and `services`), others are specific to a type.
The applicable types are listed under _Trace type_ in each configuration item section.

// TODO Consider grouping the items by subject
// Initially, we list them in the order of fbtrace.conf (based on Firebird 5.0)
The configuration items are listed in order of first appearance in the example `fbtrace.conf`.

include::trace/_enabled.adoc[leveloffset=+2]

include::trace/_log-filename.adoc[leveloffset=+2]

include::trace/_max-log-size.adoc[leveloffset=+2]

include::trace/_include-filter.adoc[leveloffset=+2]

include::trace/_exclude-filter.adoc[leveloffset=+2]

include::trace/_log-connections.adoc[leveloffset=+2]

include::trace/_connection-id.adoc[leveloffset=+2]

include::trace/_log-transactions.adoc[leveloffset=+2]

include::trace/_log-statement-prepare.adoc[leveloffset=+2]

include::trace/_log-statement-free.adoc[leveloffset=+2]

include::trace/_log-statement-start.adoc[leveloffset=+2]

include::trace/_log-statement-finish.adoc[leveloffset=+2]

include::trace/_log-procedure-compile.adoc[leveloffset=+2]

include::trace/_log-procedure-start.adoc[leveloffset=+2]

include::trace/_log-procedure-finish.adoc[leveloffset=+2]

include::trace/_log-function-compile.adoc[leveloffset=+2]

include::trace/_log-function-start.adoc[leveloffset=+2]

include::trace/_log-function-finish.adoc[leveloffset=+2]

include::trace/_log-trigger-compile.adoc[leveloffset=+2]

include::trace/_log-trigger-start.adoc[leveloffset=+2]

include::trace/_log-trigger-finish.adoc[leveloffset=+2]

include::trace/_log-context.adoc[leveloffset=+2]

include::trace/_log-errors.adoc[leveloffset=+2]

include::trace/_log-warnings.adoc[leveloffset=+2]

include::trace/_include-gds-codes.adoc[leveloffset=+2]

include::trace/_exclude-gds-codes.adoc[leveloffset=+2]

include::trace/_log-initfini.adoc[leveloffset=+2]

include::trace/_log-sweep.adoc[leveloffset=+2]

include::trace/_print-plan.adoc[leveloffset=+2]

include::trace/_explain-plan.adoc[leveloffset=+2]

include::trace/_print-perf.adoc[leveloffset=+2]

include::trace/_log-blr-requests.adoc[leveloffset=+2]

include::trace/_print-blr.adoc[leveloffset=+2]

include::trace/_log-dyn-requests.adoc[leveloffset=+2]

include::trace/_print-dyn.adoc[leveloffset=+2]

include::trace/_time-threshold.adoc[leveloffset=+2]

include::trace/_max-sql-length.adoc[leveloffset=+2]

include::trace/_max-blr-length.adoc[leveloffset=+2]

include::trace/_max-dyn-length.adoc[leveloffset=+2]

include::trace/_max-arg-length.adoc[leveloffset=+2]

include::trace/_max-arg-count.adoc[leveloffset=+2]

include::trace/_log-services.adoc[leveloffset=+2]

include::trace/_log-service_query.adoc[leveloffset=+2]
