[#fbconf-databases]
= `databases.conf`

The file `databases.conf` defines aliases for databases, and -- optionally -- database-specific configuration.
It can be used both server-side, and client-side.

[#fbconf-databases-syntax]
== databases.conf syntax

In its simplest form, a configuration item in `databases.conf` only defines an alias:

.Syntax of a simple alias
[listing,subs=+quotes]
----
_alias_ = _database-path_
----

This is a <<fbconf-syntax-kv,key-value pair>> with only a simple value.

As an example -- from the default `databases.conf` -- this defines the aliases `employee` and `employee.fdb` for the example database included in default Firebird installations:

.Examples of simples aliases
[listing]
----
#
# Example Database:
#
employee.fdb = $(dir_sampleDb)/employee.fdb
employee = $(dir_sampleDb)/employee.fdb
----

When the value is a <<fbconf-syntax-scope,scoped value>>, it also defines server-side _or_ client-side configuration.

.Syntax of an alias with a scoped value
[listing,subs=+quotes]
----
_alias_ = _database-path_
'{'
  { _key-name_ = _simple-value_ <new-line> }...
'}'
----

As an example -- from the default `databases.conf` -- this defines the alias `security.db` with database-specific configuration in the scoped value:

.Example of an alias with a scoped value
[listing]
----
security.db = $(dir_secDb)/security5.fdb
{
	RemoteAccess = false
	DefaultDbCachePages = 256
}
----

You can define multiple aliases for a single database, but only one of those aliases can be a <<fbconf-syntax-scope,scoped value>>.

[#fbconf-databases-server]
== Server-side usage

When used server-side, the file defines aliases that the server redirects to a specific database file, and -- if specified -- database-specific configuration used by the server for the database file.

The configuration specified in the scoped value applies for all connections to that database, not just connections using that specific alias.

Only _per-database_ configuration items are supported, other configurations items are ignored.

[#fbconf-databases-client]
== Client-side usage

When used client-side, the file defines aliases that the client can use as alternative connection strings, and the configuration the client uses for the connection if the connection string matches that alias, or the value of that alias, _exactly_.

The value of the alias can only be a filename, or a legacy connection string.
At this time, modern URL connection strings are not supported.
See also https://github.com/FirebirdSQL/firebird/issues/8302[firebird#8302].

Only _per-database_ *and* __client-side__ configuration items are supported, other configurations items are ignored.

[NOTE]
====
It is possible some connection properties are only _per-database_ server-side, and global client-side, or vice versa.
If you find such a case, please report it on the https://github.com/FirebirdSQL/firebird-documentation/issues[firebird-documentation repository] so we can update the documentation.
====

[#fbconf-databases-cfg]
== Configuration items

The details of the configuration items allowed in `databases.conf` are documented in chapter <<fbconf-firebird>>.
The following configurations items are supported:

// TODO Consider reordering (alphabetically, or per subject?), currently uses order in default firebird.conf

* <<fbconf-remote-access>>
* <<fbconf-external-file-access>>
* <<fbconf-temp-table-directory>>
* <<fbconf-default-db-cache-pages>>
* <<fbconf-database-growth-increment>>
* <<fbconf-use-file-system-cache>>
* <<fbconf-temp-cache-limit>>
* <<fbconf-max-identifier-byte-length>>
* <<fbconf-max-identifier-char-length>>
* <<fbconf-inline-sort-threshold>>
* <<fbconf-optimize-for-first-rows>>
* <<fbconf-outer-join-conversion>>
* <<fbconf-sub-query-conversion>>
* <<fbconf-auth-server>>
* <<fbconf-auth-client>>
* <<fbconf-user-manager>>
* <<fbconf-default-profiler-plugin>>
* <<fbconf-wire-crypt-plugin>>
* <<fbconf-key-holder-plugin>>
* <<fbconf-providers>>
* <<fbconf-deadlock-timeout>>
* <<fbconf-statement-timeout>>
* <<fbconf-connection-idle-timeout>>
* <<fbconf-on-disconnect-trigger-timeout>>
* <<fbconf-max-unflushed-writes>>
* <<fbconf-max-unflushed-write-time>>
* <<fbconf-clear-gtt-at-retaining>>
* <<fbconf-data-type-compatibility>>
* <<fbconf-wire-crypt>>
// TODO: Unclear if it actually works as per-database (asked question on firebird-devel, waiting on response)
* <<fbconf-dummy-packet-interval>>
* <<fbconf-remote-aux-port>>
* <<fbconf-lock-mem-size>>
* <<fbconf-lock-acquire-spins>>
* <<fbconf-lock-hash-slots>>
* <<fbconf-event-mem-size>>
* <<fbconf-snapshots-mem-size>>
* <<fbconf-tip-cache-block-size>>
* <<fbconf-gc-policy>>
* <<fbconf-max-statement-cache-size>>
* <<fbconf-security-database>>
