[[rnfb50-apiods]]
= Changes to the Firebird API and ODS

*since Firebird 4.0 release*

[[rnfb50-apiods-ods]]
== ODS (On-Disk Structure) Changes

[[rnfb50-apiods-ods-number]]
=== New Minor ODS Number

Firebird 5.0 creates databases with an ODS (On-Disk Structure) version of 13.1.
It can also work with databases created in ODS 13.0 (by Firebird 4.0), but some new features will be unavailable.

[[rnfb50-apiods-new-systabs]]
=== New System Tables

System tables added in ODS 13.1: 

[horizontal]
`RDB$KEYWORDS`:: Virtual table that enumerates keywords used by the SQL parser
`MON$COMPILED_STATEMENTS`:: Virtual table that reports compiled statements

[[rnfb50-apiods-new-syscols]]
=== New Columns in System Tables

Columns `RDB$CONDITION_SOURCE` and `RDB$CONDITION_BLR` were added to the system table `RDB$INDICES`, they belong to the partial indices feature.

Virtual table `MON$ATTACHMENTS` was extended with the new `MON$SESSION_TIMEZONE` column.
Also, column `MON$COMPILED_STATEMENT_ID` was added to the system tables `MON$STATEMENTS` and `MON$CALL_STACK`.
Virtual table `SEC$GLOBAL_AUTH_MAPPING` now has the new column `SEC$DESCRIPTION`.

[[rnfb50-apiods-api]]
== Application Programming Interfaces

The wire protocol version for the Firebird 5.0 API is 18.
Additions and changes are described in the sections below.

[[rnfb50-apiods-api-ext]]
=== Main API Extensions

A number of new methods have been added to the following interfaces.

==== `ResultSet`

[source]
----
void getInfo(Status status,
             uint itemsLength, const uchar* items,
             uint bufferLength, uchar* buffer);
----

Allows to query the cursor information.
Currently, only one information request is supported, `INF_RECORD_COUNT`.
`INF_RECORD_COUNT` returns the number of records cached by the scrollable cursor, or -1 for a uni-directional (forward-only) cursor.


[[rnfb50-apiods-api-info]]
=== Extensions to various getInfo() Methods

==== `Statement::getInfo()`

The following actions were added:

[horizontal]
`isc_info_sql_exec_path_blr_bytes`:: Execution path as BLR (binary format)
`isc_info_sql_exec_path_blr_text`:: Execution path as BLR (textual format)


[[rnfb50-apiods-api-service-ext]]
=== Services API Extensions

==== Support for parallel operations

Added support for parallel operations.

The following options were added:
[horizontal]
isc_spb_bkp_parallel_workers:: number of parallel workers for backup
isc_spb_res_parallel_workers:: number of parallel workers for restore
isc_spb_rpr_par_workers:: number of parallel workers for sweep

Examples of use of new parameters in _fbsvcmgr_ utility (login and password were left out for brevity):

[source]
----
fbsvcmgr -action_backup -bkp_parallel_workers 4 <dbname> <backupname>
fbsvcmgr -action_restore -res_parallel_workers 4 <backupname> <dbname>
fbsvcmgr -action_repair -rpr_sweep_db -rpr_par_workers 4 <dbname>
----

==== Support for gfix -upgrade

Added support for minor ODS upgrade.

The following option was added:
[horizontal]
isc_spb_rpr_upgrade_db:: upgrade database

Example of use of new parameter in _fbsvcmgr_ utility (login and password were left out for brevity):

[source]
----
fbsvcmgr -action_repair -rpr_upgrade_db <dbname>
----
