[[rnfb50-bug]]
= Bugs Fixed

////
_https://github.com/FirebirdSQL/firebird/issues/nnnn[#nnnn]_
-- A description

_Fixed by Some Person_

'''
////

[[bug-500rc2]]
== Firebird 5.0 Release Candidate 2: Bug Fixes

[[bug-500rc2-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/7904[#7904]_
-- FB5 bad plan for query  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7903[#7903]_
-- Unexpected Results when Using CASE-WHEN with LEFT JOIN  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7885[#7885]_
-- Unstable error messages in services due to races related with service status vector  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7879[#7879]_
-- Unexpected Results when Using Natural Right Join  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7867[#7867]_
-- Error "wrong page type" during garbage collection on v4.0.4  

_Implemented by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/7853[#7853]_
-- Do not consider non-deterministic expressions as invariants in pre-filters  

_Implemented by Dmitry Yemanov_

'''
  
_https://github.com/FirebirdSQL/firebird/issues/7839[#7839]_
-- Potential bug in BETWEEN Operator  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7831[#7831]_
-- Incorrect type of UDF-argument with array  

_Implemented by Dmitry Kovalenko_

'''

_https://github.com/FirebirdSQL/firebird/issues/7827[#7827]_
-- Problem using python firebird-driver with either intel or m1 Mac builds with version 4.0.3 or 5.0+  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7817[#7817]_
-- Memory leak is possible for UDF array arguments  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7795[#7795]_
-- NOT IN <list> returns incorrect result if NULLs are present inside the value list  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7772[#7772]_
-- Blob corruption in FB4.0.3 (embedded)  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7767[#7767]_
-- Slow drop trigger command execution under FB5.0  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7760[#7760]_
-- Parameters inside the IN list may cause a string truncation error  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7759[#7759]_
-- Routine calling overhead increased by factor 6 vs Firebird 4.0.0  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7461[#7461]_
-- Differencies in field metadata descriptions between Firebird 2.5 and Firebird 4  

_Implemented by Dmitry Yemanov_

'''

[[bug-500rc2-crashes]]
=== Server Crashes/Hangups

_https://github.com/FirebirdSQL/firebird/issues/7917[#7917]_
-- Hang in a case of error when the sweep thread is attaching the database  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7905[#7905]_
-- Segfault during TIP cache initialization  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7860[#7860]_
-- Crash potentially caused by BETWEEN Operator  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7832[#7832]_
-- Firebird 5 and 6 crash on "... RETURNING * " without INTO in PSQL  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7779[#7779]_
-- Firebird 4.0.3 is constantly crashing with the same symptoms (fbclient.dll) (incl. DMP File Analysis)  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7762[#7762]_
-- Crash on "Operating system call pthread_mutex_destroy failed. Error code 16" in log  

_Implemented by Alexander Peshkov_

'''

[[bug-500rc2-utilities]]
=== Utilities

[[bug-500rc2-utilities-isql]]
==== isql

_https://github.com/FirebirdSQL/firebird/issues/7844[#7844]_
-- Removing first column with SET WIDTH crashes ISQL  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7761[#7761]_
-- Regression when displaying line number of errors in ISQL scripts  

_Implemented by Adriano dos Santos Fernandes_

'''

[[bug-500rc2-utilities-gbak]]
==== gbak

_https://github.com/FirebirdSQL/firebird/issues/7851[#7851]_
-- [FB1+, GBAK, Restore] The skip of att_functionarg_field_precision does not check RESTORE_format  

_Implemented by Dmitry Kovalenko_

'''

_https://github.com/FirebirdSQL/firebird/issues/7846[#7846]_
-- FB4 can't backup/restore int128-array  

_Implemented by Dmitry Kovalenko_

'''

_https://github.com/FirebirdSQL/firebird/issues/7812[#7812]_
-- Service backup does not work in multiple engines configuration  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7800[#7800]_
-- Default publication status is not preserved after backup/restore  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7770[#7770]_
-- Restore takes 25% more time vs 4.0.0  

_Implemented by Vlad Khorsun_

'''



[[bug-500rc1]]
== Firebird 5.0 Release Candidate 1: Bug Fixes

[[bug-500rc1-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/pull/7747[#7747]_
-- Fix an issue where the garbage collection in indexes and blobs is not performed in `VIO_backout`

_Fixed by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/pull/7737[#7737]_
-- Fix cases where the precedence relationship between a record page and a blob page is not set  

_Fixed by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/7731[#7731]_
-- Display length of `TIMESTAMP WITH TIMEZONE` is wrong in Dialect 1  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7730[#7730]_
-- Server ignores the size of `VARCHAR` when performing `SET BIND ... TO VARCHAR(N)`  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7729[#7729]_
-- `SET BIND OF TIMESTAMP WITH TIMEZONE TO VARCHAR(128)` uses the date format of Dialect 1  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7727[#7727]_
-- Index for integer column cannot be used when `INT128`/`DECFLOAT` value is being searched

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7723[#7723]_
-- Wrong error message on login if the user doesn't exist and _WireCrypt_ is disabled

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7713[#7713]_
-- `FOR SELECT` statement can not see any changes made in `DO` block  

_Fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7710[#7710]_
-- Expression index -- more than one null value cause attempt to store duplicate value error

_Fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7703[#7703]_
-- Requests leak in _AutoCacheRequest_  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7696[#7696]_
-- `SELECT` from external procedure validates output parameters even when fetch method returns false  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/pull/7694[#7694]_
-- Fix false positives of "`__missing entries for record X__`" error during index validation when a deleted record version is committed and has a backversion

_Fixed by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/7691[#7691]_
-- `WITH CALLER PRIVILEGE` has no effect in triggers   

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7683[#7683]_
-- `RDB$TIME_ZONE_UTIL.TRANSITIONS` returns an infinite result set

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7676[#7676]_
-- Error "`__attempt to evaluate index expression recursively__`"

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7670[#7670]_
-- Cursor name can duplicate parameter and variable names in procedures and functions  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7665[#7665]_
-- Wrong result ordering in `LEFT JOIN` query  

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7664[#7664]_
-- `DROP TABLE` executed for a table with big records may lead to "`__wrong page type__`" or "`__end of file__`" error

_Fixed by Vlad Khorsun, Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/pull/7662[#7662]_
-- Fix performance issues in `prepare_update()`

_Fixed by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/pull/7661[#7661]_
-- Classic Server rejects new connections  

_Fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7649[#7649]_
-- Switch Linux performance counter timer to CLOCK_MONOTONIC_RAW  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/pull/7641[#7641]_
-- Fix wrong profiler measurements due to overflow  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7638[#7638]_
-- `OVERRIDING USER VALUE` should be allowed for `GENERATED ALWAYS AS IDENTITY`  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7627[#7627]_
-- The size of a database with big records becomes bigger after backup/restore

_Fixed by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/7626[#7626]_
-- Segfault when new attachment is done to shutting down database  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7611[#7611]_
-- Can't backup/restore database from v3 to v4 with `SEC$USER_NAME` field longer than 10 characters  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7610[#7610]_
-- Uninitialized/random value assigned to `RDB$ROLES` -> `RDB$SYSTEM PRIVILEGES` when restoring from FB3 backup  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7604[#7604]_
-- PSQL functions do not convert the output BLOB to the connection character set  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7603[#7603]_
-- `BIN_SHR` on `INT128` does not apply sign extension  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7599[#7599]_
-- Conversion of text with '\0' to `DECFLOAT` without errors  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7598[#7598]_
-- DDL statements hang when the compiled statements cache is enabled  

_Fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7582[#7582]_
-- Missing `isc_info_end` in _Firebird.pas_

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7574[#7574]_
-- Derived table syntax allows dangling `AS`  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7569[#7569]_
-- Multi-level order by and offset/fetch ignored on parenthesized query expressions  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7562[#7562]_
-- Profiler elapsed times are incorrect in Windows  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7556[#7556]_
-- FB Classic can hang when attempts to attach DB while it is starting to encrypt/decrypt  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7555[#7555]_
-- Invalid configuration for random fresh created database may be used after drop of another one with alias in _databases.conf_  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7553[#7553]_
-- Firebird 5 profiler error with subselects  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7548[#7548]_
-- `SET BIND OF TIMESTAMP WITH TIME ZONE TO CHAR` is not working with UTF8 connection charset  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7537[#7537]_
-- Wrong name in error message when unknown namespace is passed into `RDB$SET_CONTEXT()`  

_Fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7535[#7535]_
-- High CPU usage connect to Firebird 3 database using Firebird 4 Classic and SuperClassic service

_Fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7499[#7499]_
-- Error during restore: "`__Index cannot be used in the specified plan__`"

_Fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7488[#7488]_
-- Invalid real to string cast   

_Fixed by Alexander Peshkov, Artyom Abakumov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7486[#7486]_
-- No initialization of rpb's runtime flags causes problems with `SKIP LOCKED` when config _ReadConsistency = 0_ and SuperServer  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7484[#7484]_
-- External engine `SYSTEM` not found  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7480[#7480]_
-- Firebird server stops accepting new connections after some time  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7456[#7456]_
-- Impossible to drop function in package with name of PSQL-function

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7387[#7387]_
-- Unreliable replication behaviour in Linux Classic  

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/pull/7233[#7233]_
-- Postfix for #5385 (CORE-5101): Fix slow database restore when Classic server mode is used  

_Fixed by Ilya Eremin_

'''

[[bug-500rc1-crashes]]
=== Server Crashes/Hangups

_https://github.com/FirebirdSQL/firebird/issues/7738[#7738]_
-- Crash on multiple connections/disconnections  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7658[#7658]_
-- Segfault when closing database in valgrind-enabled build  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7554[#7554]_
-- Firebird 5 partial index creation causes server hang up  

_Fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7514[#7514]_
-- Segfault when detaching after deleting shadow on Classic  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7504[#7504]_
-- Segfault when closing SQL statement in remote provider during shutdown  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7472[#7472]_
-- Window functions may lead to crash interacting with others exceptions  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7464[#7464]_
-- Crash on repeating update in 5.0  

_Fixed by Adriano dos Santos Fernandes_

'''

[[bug-500rc1-utilities]]
=== Utilities

[[bug-500rc1-utilities-gbak]]
==== gbak

[[bug-500rc1-utilities-nbackup]]
==== nbackup

_https://github.com/FirebirdSQL/firebird/issues/7579[#7579]_
-- Cannot _nbackup_ a Firebird 3.0 database in Firebird 4.0 service with _engine12_ setup in _Providers_  

_Fixed by Alexander Peshkov_

'''


[[bug-500b1]]
== Firebird 5.0 Beta 1 Release: Bug Fixes

[NOTE]
====
This sections enumerates only bugfixes not already fixed in maintenance releases of earlier Firebird versions.
====

[[bug-500b1-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/7422[#7422]_
-- Seek in temporary blob level 0 makes read return wrong data

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7388[#7388]_
-- Different invariants optimization between views and CTEs

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7304[#7304]_
-- Events in system attachments (like garbage collector) are not traced

_Fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7227[#7227]_
-- Dependencies of subroutines are not preserved after backup restore

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7220[#7220]_
-- `TYPE OF COLUMN` dependency not tracked in package header and external routines

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7183[#7183]_
-- Regression when derived table has column evaluated as result of subquery with `IN`, `ANY` or `ALL` predicate: "`__invalid BLR at offset ... / context already in use__`"

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7164[#7164]_
-- Multi-way hash/merge joins are impossible for expression-based keys

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7133[#7133]_
-- `ORDER BY` for big (>34 digits) _int128_ values is broken when index on that field is used

_Fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7077[#7077]_
-- `EXECUTE BLOCK` (without `RETURNS`) do not work with batches

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7009[#7009]_
-- `IReplicatedTransaction` receives wrong savepoint event

_Fixed by Dimitry Sibiryakov, Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6942[#6942]_
-- Incorrect singleton error with `MERGE` and `RETURNING`

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6869[#6869]_
-- Domain CHECK-expression can be ignored when we `DROP` objects that are involved in it

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6807[#6807]_
-- Regression: error "`__Unexpected end of command__`" with incorrect line/column info

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/5749[#5749]_
-- "`__Token unknown__`" error on formfeed in query

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/3812[#3812]_
-- Query with a stored procedure doesn't accept explicit plan

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/3218[#3218]_
-- Optimizer fails applying stream-local predicates before merging

_Fixed by Dmitry Yemanov_

'''

[[bug-500b1-crashes]]
=== Server Crashes/Hangups

_https://github.com/FirebirdSQL/firebird/pull/7195[#7195]_
-- Crash when accessing already cleared memory in the sorting module

_Fixed by Andrey Kravchenko_

'''

[[bug-500b1-utilities]]
=== Utilities

[[bug-500b1-utilities-gbak]]
==== gbak

_https://github.com/FirebirdSQL/firebird/issues/7436[#7436]_
-- Backup error for wide table

_Fixed by Alex Peshkov_

'''
