[[rnfb50-bug]]
= Bugs Fixed

////
_https://github.com/FirebirdSQL/firebird/issues/nnnn[#nnnn]_
-- A description

_Fixed by Some Person_

'''
////

[[bug-500b1]]
== Firebird 5.0 Beta 1 Release: Bug Fixes

[NOTE]
====
This sections enumerates only bugfixes not already fixed in priorly released Firebird versions.
====

[[bug-500b1-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/7422[#7422]_
-- Seek in temporary blob level 0 makes read return wrong data

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7388[#7388]_
-- Different invariants optimization between views and CTEs

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7304[#7304]_
-- Events in system attachments (like garbage collector) are not traced

_Fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7227[#7227]_
-- Dependencies of subroutines are not preserved after backup restore

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7220[#7220]_
-- `TYPE OF COLUMN` dependency not tracked in package header and external routines

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7183[#7183]_
-- Regression when derived table has column evaluated as result of subquery with `IN`, `ANY` or `ALL` predicate: _"invalid BLR at offset ... / context already in use"_

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7164[#7164]_
-- Multi-way hash/merge joins are impossible for expression-based keys

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7133[#7133]_
-- `ORDER BY` for big (>34 digits) _int128_ values is broken when index on that field is used

_Fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7077[#7077]_
-- `EXECUTE BLOCK` (without `RETURNS`) do not work with batches

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7009[#7009]_
-- `IReplicatedTransaction` receives wrong savepoint event

_Fixed by Dimitry Sibiryakov, Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6942[#6942]_
-- Incorrect singleton error with `MERGE` and `RETURNING`

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6869[#6869]_
-- Domain CHECK-expression can be ignored when we `DROP` objects that are involved in it

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6807[#6807]_
-- Regression: error _"Unexpected end of command"_ with incorrect line/column info

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/5749[#5749]_
-- _"Token unknown"_ error on formfeed in query

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/3812[#3812]_
-- Query with a stored procedure doesn't accept explicit plan

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/3218[#3218]_
-- Optimizer fails applying stream-local predicates before merging

_Fixed by Dmitry Yemanov_

'''

[[bug-500b1-crashes]]
=== Server Crashes/Hangups

_https://github.com/FirebirdSQL/firebird/pull/7195[#7195]_
-- Crash when accessing already cleared memory in the sorting module

_Fixed by Andrey Kravchenko_

'''

[[bug-500b1-utilities]]
=== Utilities

[[bug-500b1-utilities-gbak]]
==== gbak

_https://github.com/FirebirdSQL/firebird/issues/7436[#7436]_
-- Backup error for wide table

_Fixed by Alex Peshkov_

'''
