[[rnfb50-bug]]
= Bugs Fixed

////
_https://github.com/FirebirdSQL/firebird/issues/nnnn[#nnnn]_
-- A description

_Fixed by Some Person_

'''
////

[[bug-503]]
== Firebird 5.0.3 Release: Bug Fixes

[[bug-503-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/8592[#8592]_
-- Presence of 'ROWS <n_limit>' causes garbage in error message when string conversion problem raises  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8590[#8590]_
-- Line "BLR to Source mapping:" may look broken when `procedures.rdb$debug_info` is queried using remote protocol  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8589[#8589]_
-- `PERCENT_RANK` may return _NaN_ instead of 0  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8554[#8554]_
-- Vulnerability GHSA-7qp6-hqxj-pjjp / ZDI-CAN-26486  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8520[#8520]_
-- Error in `iTransaction.getInfo()` on embedded connection  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8509[#8509]_
-- "Error creating private namespace" message in _firebird.log_  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8508[#8508]_
-- Conversion error with `old.field` inside `UPDATE OR INSERT`  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8488[#8488]_
-- `MIN/MAX` aggregates may badly affect the join order in queries with mixed INNER/LEFT joins  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8487[#8487]_
-- Unexpected _SetFilePointer_ error when remapping the shared memory  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8485[#8485]_
-- Segfault/AV on incorrect _databases.conf_ starting with subconfig (without line `alias=database_path`)  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8477[#8477]_
-- Inheritance of `WINDOW` does not work  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8449[#8449]_
-- Races when server is closed during forced database shutdown  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8440[#8440]_
-- Firebird 5.0.2 - wrong result for `MINVALUE/MAXVALUE` with string arguments  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8437[#8437]_
-- Segmentation fault when running query with `PARTITION BY` and subquery  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/pull/8432[#8432]_
-- Fix server hang when trying to stop a server with active connections with event notifications  

_Implemented by TreeHunter_

'''

_https://github.com/FirebirdSQL/firebird/pull/8431[#8431]_
-- Make sure only one error will be sent to not-started Service  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8430[#8430]_
-- Unstable error messages in services with trace enabled  

_Implemented by Artyom Abakumov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8320[#8320]_
-- Do not allow run concurrent sweep instances  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8296[#8296]_
-- Crash in `TipCache::findStates`  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8194[#8194]_
-- Internal consistency check (page in use during flush) with small number of _DefaultDbCachePages_  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8182[#8182]_
-- `IN` predicate incorrectly handles single parenthesized subquery as IN-list, instead of table subquery  

_Implemented by Mark Rotteveel_

'''

_https://github.com/FirebirdSQL/firebird/issues/8139[#8139]_
-- Conflict resolution code uses constraint name instead of index name  

_Implemented by Andrey Kravchenko, Vlad Khorsun_

'''

[[bug-503-utilities]]
=== Utilities

_https://github.com/FirebirdSQL/firebird/issues/8588[#8588]_
-- Error doing _nbackup_ when database file name has extended ASCII chars  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8524[#8524]_
-- _ISQL_ truncates lines longer than 255 characters when pasting  

_Implemented by Vlad Khorsun_

'''



[[bug-502]]
== Firebird 5.0.2 Release: Bug Fixes

[[bug-502-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/8429[#8429]_
-- Segfault when already destroyed callback interface is used  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8417[#8417]_
-- Negative statement ID in trace output  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8413[#8413]_
-- Fix incorrect maximum size when reading database parameter values in `SHOW DATABASE`  

_Implemented by Artyom Ivanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8408[#8408]_
-- Add option to disable install of _MSVCRT_ runtime libraries via a scripted install  

_Implemented by Paul Reeves_

'''

_https://github.com/FirebirdSQL/firebird/issues/8407[#8407]_
-- _InnoSetup_ based installer deletes _msiexec_ log of runtime libraries install  

_Implemented by Paul Reeves_

'''

_https://github.com/FirebirdSQL/firebird/pull/8403[#8403]_
-- Fix potential deadlock when starting the encryption thread  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8390[#8390]_
-- Deadlock might happen when database is shutting down with internal worker attachments  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8389[#8389]_
-- Unnecessary reload of the encryption plugin in the _SuperServer_ architecture  

_Implemented by Alexey Mochalov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8386[#8386]_
-- Crash when creating index on table that uses UDR and `ParallelWorkers > 1`  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/pull/8380[#8380]_
-- Fix race condition in `shutdownThread` start that can cause server to be unable to stop  

_Implemented by Artyom Ivanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8379[#8379]_
-- Incorrect cardinality estimation for retrievals with multiple compound indices having common set of fields  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8350[#8350]_
-- Missing records in the replicated database  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/pull/8341[#8341]_
-- Cleanup batches inside the engine if they were not released explicity before disconnection  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8336[#8336]_
-- Error: "Invalid clumplet buffer structure: buffer end before end of clumplet - clumplet too long" when using trusted authentication  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8334[#8334]_
-- MacOS ARM version requires Rosetta  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/pull/8327[#8327]_
-- Fix use :@ characters and add sub-section to configure username and password for `sync_replica`  

_Implemented by Andrey Kravchenko_

'''

_https://github.com/FirebirdSQL/firebird/pull/8324[#8324]_
-- Make asynchronous replica re-initialization reliable  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8319[#8319]_
-- Use a 64-bit counter for records written during backup  

_Implemented by Dmitry Starodubov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8315[#8315]_
-- Crash at database restore due to failed system call  

_Implemented by Vlad Khorsun, Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/8304[#8304]_
-- Wrong results using `MINVALUE/MAXVALUE` in join condition  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8292[#8292]_
-- run_all PDB fails with "Error calling COPY_XTRA"  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8290[#8290]_
-- "Unique scan" is incorrectly reported in the explained plan for unique index and `IS NULL` predicate  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8288[#8288]_
-- _GPRE_ generated code is incompatible with _GCC 14.2_  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8283[#8283]_
-- Assertion in `~thread_db()` due to not released page buffer  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/pull/8268[#8268]_
-- Fix refetch header data from delta when database is in the backup lock state  

_Implemented by Andrey Kravchenko_

'''

_https://github.com/FirebirdSQL/firebird/issues/8265[#8265]_
-- Nested `IN/EXISTS` subqueries should not be converted into semi-joins if the outer context is a sub-query which wasn't unnested  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8263[#8263]_
-- _gbak_ on _Classic_ with `ParallelWorkers > 1` doesn't restore indices, giving a cryptic error message  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/pull/8255[#8255]_
-- Catch possible stack overflow when preparing and compiling user statements  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8253[#8253]_
-- Incorrect handling of non-ASCII object names in `CREATE MAPPING` statement  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8252[#8252]_
-- Incorrect subquery unnesting with complex dependencies (`SubQueryConversion = true`)  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8250[#8250]_
-- Bad performance on simple two joins query on tables with a composite index  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8243[#8243]_
-- Fix a bug where the CS shutdown handler could be called again  

_Implemented by Alexander Zhdanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8241[#8241]_
-- _gbak_ may lose NULLs in restore  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/pull/8238[#8238]_
-- Fix using macro with regex in path parameter in _fbtrace.conf_  

_Implemented by Artyom Ivanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8237[#8237]_
-- Database access error when _nbackup_ is starting  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8236[#8236]_
-- Avoid "hangs" in `clock_gettime()` in _tomcrypt_'s PRNG  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8233[#8233]_
-- `SubQueryConversion = true` -- error "multiple rows in singleton select"  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8224[#8224]_
-- `SubQueryConversion = true` -- wrong resultset with `FIRST/SKIP` clauses inside the outer query  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8223[#8223]_
-- `SubQueryConversion = true` -- error "no current record for fetch operation" with complex joins  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8222[#8222]_
-- Fix a case of deleted memory modification  

_Implemented by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/8221[#8221]_
-- Crash when function `MAKE_DBKEY` is called with 0 or 1 arguments  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8219[#8219]_
-- Database creation in 3.0.12, 4.0.5 and 5.0.1 slower than in previous releases  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8215[#8215]_
-- Rare sporadic segfaults in test for _core-6142_ on Windows  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8214[#8214]_
-- Incorrect result of index list scan for a composite index, the second segment of which is a text field with `COLLATE UNICODE_CI`  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8213[#8213]_
-- `WHEN NOT MATCHED BY SOURCE` - does not work with a direct table as source  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8211[#8211]_
-- `DATEADD` truncates milliseconds for month and year deltas  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8203[#8203]_
-- Function `MAKE_DBKEY` may produce random errors if used with a relation name  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8109[#8109]_
-- Plan/performance regression when using special construct for `IN`  

_Implemented by Vlad Khorsun, Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8069[#8069]_
-- Add missing synchronization to cached vectors of known pages  

_Implemented by Dmitry Yemanov, Vlad Khorsun_

'''

[[bug-501]]
== Firebird 5.0.1 Release: Bug Fixes

[[bug-501-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/8189[#8189]_
-- Slow connection times with a lot of simultaneous connections and active trace session present  

_Implemented by Alexander Peshkov, Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/pull/8186[#8186]_
-- Fixed a few issues with IPC used by remote profiler  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8180[#8180]_
-- Sometimes a trace session is terminated spontaneously  

_Implemented by Artyom Abakumov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8178[#8178]_
-- Fix boolean conversion to string inside `DataTypeUtil::makeFromList()`  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8171[#8171]_
-- Trace plugin unloaded if called method is not implemented  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8168[#8168]_
-- `MAKE_DBKEY` bug after backup/restore  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8156[#8156]_
-- Can not specify concrete IPv6 address in ES/EDS connection string  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8150[#8150]_
-- Process could attach to the deleted instance of shared memory  

_Implemented by Alexander Peshkov, Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8138[#8138]_
-- Bugcheck when replicator state is changed concurrently  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8123[#8123]_
-- Procedure manipulation can lead to wrong dependencies removal  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8120[#8120]_
-- `CAST` dies with numeric value is out of range error  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8115[#8115]_
-- FB 5.0.0.1306 - unexpected results using `LEFT JOIN` with `WHEN`  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8112[#8112]_
-- Error _isc_read_only_trans (335544361)_ should report _SQLSTATE 25006_  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8108[#8108]_
-- ICU 63.1 suppresses conversion errors  

_Implemented by Dmitry Kovalenko_

'''

_https://github.com/FirebirdSQL/firebird/issues/8100[#8100]_
-- The `isc_array_lookup_bounds` function returns invalid values for low and high array bounds  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8094[#8094]_
-- Index creation error when restoring with parallels workers

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8086[#8086]_
-- `IN` predicate with string-type elements is evaluated wrongly against a numeric field  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8085[#8085]_
-- Memory leak when executing a lot of different queries and `StatementTimeout > 0`  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8084[#8084]_
-- Partial index uniqueness violation  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8078[#8078]_
-- `SIMILAR TO` with constant pattern using ‘|’, ‘*’, ‘?’ or ‘{0,N}’ doesn't work as expected  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8077[#8077]_
-- Error "Too many recursion levels" does not stop execution of code that uses `ON DISCONNECT` trigger (FB 4.x+)  

_Implemented by Alexander Peshkov, Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8063[#8063]_
-- (var)char variables/parameters assignments fail in stored procedures with subroutines

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8058[#8058]_
-- Replicated DDL changes do not set the correct grantor  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8056[#8056]_
-- Error "Too many temporary blobs" with `BLOB_APPEND` when selecting a stored procedure with rows-clause

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8040[#8040]_
-- Bugcheck 183 (wrong record length) could happen on replica database after UK violation on insert   

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8033[#8033]_
-- Invalid result when string compared with indexed `NUMERIC(x,y)` field where x > 18 and y != 0  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8027[#8027]_
-- Broken _gbak_ statistics  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8011[#8011]_
-- `DECFLOAT` error working with `INT128` in UDR

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8006[#8006]_
-- `INT128` datatype not supported in `FB_MESSAGE` macro   

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7997[#7997]_
-- Unexpected results when comparing integer with string containing value out of range of that integer datatype  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7995[#7995]_
-- Unexpected results after creating partial index  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7993[#7993]_
-- Unexpected results when using `CASE WHEN` with `RIGHT JOIN`  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7976[#7976]_
-- False validation error for short unpacked records  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7969[#7969]_
-- Characters are garbled when replicating fields with type `BLOB SUB_TYPE TEXT` if the character set of the connection and the field are different  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7942[#7942]_
-- Database file appears corrupted after restore from backup

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7937[#7937]_
-- Inner join raises error "no current record for fetch operation" if a stored procedure depends on some table via input parameter and also has an indexed relationship with another table  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7927[#7927]_
-- Some default values are set incorrectly for SC/CS architectures

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7921[#7921]_
-- Firebird 5 uses PK for ordered plan even if matching index with fewer fields exists

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7899[#7899]_
-- Inconsistent state of master-detail occurs after reconnect + 'SET AUTODDL OFF' + 'drop <FK>' which is rolled back

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7896[#7896]_
-- _replication.log_ remains empty (and without any error in firebird.log) until concurrent FB instance is running under different account and generates segments on its master. Significant delay required after stopping concurrent FB to allow first one to write in its replication log.

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7873[#7873]_
-- Wrong memory buffer alignment and I/O buffer size when working in direct I/O mode  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7863[#7863]_
-- Non-correlated sub-query is evaluated multiple times if it is based on a view rather than on an equivalent derived table

_Implemented by Dmitry Yemanov_

'''

[[bug-501-crashes]]
=== Server Crashes/Hangups

_https://github.com/FirebirdSQL/firebird/issues/8185[#8185]_
-- SIGSEGV in Firebird 5.0.0.1306 embedded during update on cursor  

_Implemented by Adriano dos Santos Fernandes, Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8176[#8176]_
-- Firebird 5 hangs after starting remote profiling session  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8151[#8151]_
-- Deadlock happens when running 'List Trace Sessions' service and there are many active trace sessions

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8149[#8149]_
-- A hang or crash could happen when connection fires _TRACE_EVENT_DETACH_ event and a new trace session is created concurrently

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8136[#8136]_
-- Server crashes with `IN (dbkey1, dbkey2, ...)` condition  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8114[#8114]_
-- Segfault in connection pool during server shutdown

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8110[#8110]_
-- Firebird 5 crash on Android API level 34  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8101[#8101]_
-- Firebird crashes if a plugin factory returns _nullptr_ and no error in the status  

_Implemented by Vlad Khorsun, Dimitry Sibiryakov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8089[#8089]_
-- AV when attaching database while low on free memory

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8087[#8087]_
-- AV when preparing a query with `IN <list>` that contains both literals and sub-query  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8083[#8083]_
-- AV when writing to internal trace log

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8079[#8079]_
-- Engine could crash when executing some trigger(s) while another attachment modifies them  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8039[#8039]_
-- Segfault when opening damaged (last TIP is missing in _RDB$PAGES_, user's FW was OFF) database  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8026[#8026]_
-- Crash LI-V5.0.0.1306 in _libEngine13.so_  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7998[#7998]_
-- Сrash during partial index checking if the condition raises a conversion error  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7985[#7985]_
-- Hang in case of error when sweep thread is attaching to database (_Classic Server_)  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7979[#7979]_
-- Hang when database with disconnect trigger using `MON$` tables is shutting down  

_Implemented by Alexander Peshkov_

'''

[[bug-501-utilities]]
=== Utilities

[[bug-501-utilities-isql]]
==== isql

_https://github.com/FirebirdSQL/firebird/pull/8016[#8016]_
-- Free memory issued for _isql_ command list but has never been freed on output file write  

_Implemented by Alexey Mochalov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7962[#7962]_
-- System procedure/function inconsistency between _isql_ `SHOW FUNCTIONS` and `SHOW PROCEDURES`  

_Implemented by Artyom Ivanov_

'''

[[bug-501-utilities-gbak]]
==== gbak

_https://github.com/FirebirdSQL/firebird/issues/8003[#8003]_
-- _gbak_ v4 can't backup database in ODS < 13  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7996[#7996]_
-- _gbak_ terminates/crashes when a read error occurs during restore  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7992[#7992]_
-- Assertion (space > 0) failure during restore  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7974[#7974]_
-- Restore of wide table can fail with "adjusting an invalid decompression length from <N> to <M>"  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7950[#7950]_
-- Unable to restore database when .fbk was created on host with other ICU  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7869[#7869]_
-- GBAK can write uninitialized data into RDB$RETURN_ARGUMENT and RDB$ARGUMENT_POSITION fields  

_Implemented by Dmitry Kovalenko_

'''

[[bug-501-builds]]
==== Builds/Packaging


_https://github.com/FirebirdSQL/firebird/issues/8172[#8172]_
-- File `include/firebird/impl/iberror_c.h` is missing in the Linux x64 tar archive  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8037[#8037]_
-- Remove directory entries from debug symbols tarbal  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8034[#8034]_
-- (Re)set owner/group in tarbal of non-root builds  

_Implemented by Alexander Peshkov_

'''

[[bug-500rc2]]
== Firebird 5.0 Release Candidate 2: Bug Fixes

[[bug-500rc2-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/7904[#7904]_
-- FB5 bad plan for query  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7903[#7903]_
-- Unexpected results when using CASE-WHEN with LEFT JOIN

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7885[#7885]_
-- Unstable error messages in services due to races related with service status vector  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7879[#7879]_
-- Unexpected results when using natural right join

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7867[#7867]_
-- Error "wrong page type" during garbage collection on v4.0.4  

_Implemented by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/7853[#7853]_
-- Do not consider non-deterministic expressions as invariants in pre-filters  

_Implemented by Dmitry Yemanov_

'''
  
_https://github.com/FirebirdSQL/firebird/issues/7839[#7839]_
-- Potential bug in BETWEEN operator

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7831[#7831]_
-- Incorrect type of UDF-argument with array  

_Implemented by Dmitry Kovalenko_

'''

_https://github.com/FirebirdSQL/firebird/issues/7827[#7827]_
-- Problem using Python firebird-driver with either Intel or M1 Mac builds with version 4.0.3 or 5.0+

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7817[#7817]_
-- Memory leak is possible for UDF array arguments  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7795[#7795]_
-- NOT IN <list> returns incorrect result if NULLs are present inside the value list  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7772[#7772]_
-- Blob corruption in FB4.0.3 (embedded)  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7767[#7767]_
-- Slow drop trigger command execution under FB5.0

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7760[#7760]_
-- Parameters inside IN list may cause a string truncation error

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7759[#7759]_
-- Routine calling overhead increased by factor 6 vs Firebird 4.0.0  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7461[#7461]_
-- Differences in field metadata descriptions between Firebird 2.5 and Firebird 4

_Implemented by Dmitry Yemanov_

'''

[[bug-500rc2-crashes]]
=== Server Crashes/Hangups

_https://github.com/FirebirdSQL/firebird/issues/7917[#7917]_
-- Hang in case of error when the sweep thread is attaching the database

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7905[#7905]_
-- Segfault during TIP cache initialization  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7860[#7860]_
-- Crash potentially caused by BETWEEN operator

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7832[#7832]_
-- Firebird 5 and 6 crash on "... RETURNING * " without INTO in PSQL  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7779[#7779]_
-- Firebird 4.0.3 is constantly crashing with the same symptoms (fbclient.dll) (incl. DMP File Analysis)  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7762[#7762]_
-- Crash on "Operating system call pthread_mutex_destroy failed. Error code 16" in log  

_Implemented by Alexander Peshkov_

'''

[[bug-500rc2-utilities]]
=== Utilities

[[bug-500rc2-utilities-isql]]
==== isql

_https://github.com/FirebirdSQL/firebird/issues/7844[#7844]_
-- Removing first column with SET WIDTH crashes ISQL  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7761[#7761]_
-- Regression when displaying line number of errors in ISQL scripts  

_Implemented by Adriano dos Santos Fernandes_

'''

[[bug-500rc2-utilities-gbak]]
==== gbak

_https://github.com/FirebirdSQL/firebird/issues/7851[#7851]_
-- [FB1+, GBAK, Restore] The skip of att_functionarg_field_precision does not check RESTORE_format  

_Implemented by Dmitry Kovalenko_

'''

_https://github.com/FirebirdSQL/firebird/issues/7846[#7846]_
-- FB4 can't backup/restore int128-array  

_Implemented by Dmitry Kovalenko_

'''

_https://github.com/FirebirdSQL/firebird/issues/7812[#7812]_
-- Service backup does not work in multiple engines configuration  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7800[#7800]_
-- Default publication status is not preserved after backup/restore  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7770[#7770]_
-- Restore takes 25% more time vs 4.0.0  

_Implemented by Vlad Khorsun_

'''

[[bug-500rc1]]
== Firebird 5.0 Release Candidate 1: Bug Fixes

[[bug-500rc1-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/pull/7747[#7747]_
-- Fix an issue where the garbage collection in indexes and blobs is not performed in `VIO_backout`

_Fixed by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/pull/7737[#7737]_
-- Fix cases where the precedence relationship between a record page and a blob page is not set  

_Fixed by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/7731[#7731]_
-- Display length of `TIMESTAMP WITH TIMEZONE` is wrong in Dialect 1  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7730[#7730]_
-- Server ignores the size of `VARCHAR` when performing `SET BIND ... TO VARCHAR(N)`  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7729[#7729]_
-- `SET BIND OF TIMESTAMP WITH TIMEZONE TO VARCHAR(128)` uses the date format of Dialect 1  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7727[#7727]_
-- Index for integer column cannot be used when `INT128`/`DECFLOAT` value is being searched

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7723[#7723]_
-- Wrong error message on login if the user doesn't exist and _WireCrypt_ is disabled

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7713[#7713]_
-- `FOR SELECT` statement can not see any changes made in `DO` block  

_Fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7710[#7710]_
-- Expression index -- more than one null value cause attempt to store duplicate value error

_Fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7703[#7703]_
-- Requests leak in _AutoCacheRequest_  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7696[#7696]_
-- `SELECT` from external procedure validates output parameters even when fetch method returns false  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/pull/7694[#7694]_
-- Fix false positives of "`__missing entries for record X__`" error during index validation when a deleted record version is committed and has a backversion

_Fixed by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/7691[#7691]_
-- `WITH CALLER PRIVILEGE` has no effect in triggers   

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7683[#7683]_
-- `RDB$TIME_ZONE_UTIL.TRANSITIONS` returns an infinite result set

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7676[#7676]_
-- Error "`__attempt to evaluate index expression recursively__`"

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7670[#7670]_
-- Cursor name can duplicate parameter and variable names in procedures and functions  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7665[#7665]_
-- Wrong result ordering in `LEFT JOIN` query  

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7664[#7664]_
-- `DROP TABLE` executed for a table with big records may lead to "`__wrong page type__`" or "`__end of file__`" error

_Fixed by Vlad Khorsun, Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/pull/7662[#7662]_
-- Fix performance issues in `prepare_update()`

_Fixed by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/pull/7661[#7661]_
-- Classic Server rejects new connections  

_Fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7649[#7649]_
-- Switch Linux performance counter timer to CLOCK_MONOTONIC_RAW  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/pull/7641[#7641]_
-- Fix wrong profiler measurements due to overflow  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7638[#7638]_
-- `OVERRIDING USER VALUE` should be allowed for `GENERATED ALWAYS AS IDENTITY`  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7627[#7627]_
-- The size of a database with big records becomes bigger after backup/restore

_Fixed by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/issues/7626[#7626]_
-- Segfault when new attachment is done to shutting down database  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7611[#7611]_
-- Can't backup/restore database from v3 to v4 with `SEC$USER_NAME` field longer than 10 characters  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7610[#7610]_
-- Uninitialized/random value assigned to `RDB$ROLES` -> `RDB$SYSTEM PRIVILEGES` when restoring from FB3 backup  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7604[#7604]_
-- PSQL functions do not convert the output BLOB to the connection character set  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7603[#7603]_
-- `BIN_SHR` on `INT128` does not apply sign extension  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7599[#7599]_
-- Conversion of text with '\0' to `DECFLOAT` without errors  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7598[#7598]_
-- DDL statements hang when the compiled statements cache is enabled  

_Fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7582[#7582]_
-- Missing `isc_info_end` in _Firebird.pas_

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7574[#7574]_
-- Derived table syntax allows dangling `AS`  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7569[#7569]_
-- Multi-level order by and offset/fetch ignored on parenthesized query expressions  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7562[#7562]_
-- Profiler elapsed times are incorrect in Windows  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7556[#7556]_
-- FB Classic can hang when attempts to attach DB while it is starting to encrypt/decrypt  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7555[#7555]_
-- Invalid configuration for random fresh created database may be used after drop of another one with alias in _databases.conf_  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7553[#7553]_
-- Firebird 5 profiler error with subselects  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7548[#7548]_
-- `SET BIND OF TIMESTAMP WITH TIME ZONE TO CHAR` is not working with UTF8 connection charset  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7537[#7537]_
-- Wrong name in error message when unknown namespace is passed into `RDB$SET_CONTEXT()`  

_Fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7535[#7535]_
-- High CPU usage connect to Firebird 3 database using Firebird 4 Classic and SuperClassic service

_Fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7499[#7499]_
-- Error during restore: "`__Index cannot be used in the specified plan__`"

_Fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7488[#7488]_
-- Invalid real to string cast   

_Fixed by Alexander Peshkov, Artyom Abakumov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7486[#7486]_
-- No initialization of rpb's runtime flags causes problems with `SKIP LOCKED` when config _ReadConsistency = 0_ and SuperServer  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7484[#7484]_
-- External engine `SYSTEM` not found  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7480[#7480]_
-- Firebird server stops accepting new connections after some time  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7456[#7456]_
-- Impossible to drop function in package with name of PSQL-function

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7387[#7387]_
-- Unreliable replication behaviour in Linux Classic  

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/pull/7233[#7233]_
-- Postfix for #5385 (CORE-5101): Fix slow database restore when Classic server mode is used  

_Fixed by Ilya Eremin_

'''

[[bug-500rc1-crashes]]
=== Server Crashes/Hangups

_https://github.com/FirebirdSQL/firebird/issues/7738[#7738]_
-- Crash on multiple connections/disconnections  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7658[#7658]_
-- Segfault when closing database in valgrind-enabled build  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7554[#7554]_
-- Firebird 5 partial index creation causes server hang up  

_Fixed by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7514[#7514]_
-- Segfault when detaching after deleting shadow on Classic  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7504[#7504]_
-- Segfault when closing SQL statement in remote provider during shutdown  

_Fixed by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7472[#7472]_
-- Window functions may lead to crash interacting with others exceptions  

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7464[#7464]_
-- Crash on repeating update in 5.0  

_Fixed by Adriano dos Santos Fernandes_

'''

[[bug-500rc1-utilities]]
=== Utilities

[[bug-500rc1-utilities-gbak]]
==== gbak

[[bug-500rc1-utilities-nbackup]]
==== nbackup

_https://github.com/FirebirdSQL/firebird/issues/7579[#7579]_
-- Cannot _nbackup_ a Firebird 3.0 database in Firebird 4.0 service with _engine12_ setup in _Providers_  

_Fixed by Alexander Peshkov_

'''


[[bug-500b1]]
== Firebird 5.0 Beta 1 Release: Bug Fixes

[NOTE]
====
This sections enumerates only bugfixes not already fixed in maintenance releases of earlier Firebird versions.
====

[[bug-500b1-core]]
=== Core Engine

_https://github.com/FirebirdSQL/firebird/issues/7422[#7422]_
-- Seek in temporary blob level 0 makes read return wrong data

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7388[#7388]_
-- Different invariants optimization between views and CTEs

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7304[#7304]_
-- Events in system attachments (like garbage collector) are not traced

_Fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7227[#7227]_
-- Dependencies of subroutines are not preserved after backup restore

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7220[#7220]_
-- `TYPE OF COLUMN` dependency not tracked in package header and external routines

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7183[#7183]_
-- Regression when derived table has column evaluated as result of subquery with `IN`, `ANY` or `ALL` predicate: "`__invalid BLR at offset ... / context already in use__`"

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7164[#7164]_
-- Multi-way hash/merge joins are impossible for expression-based keys

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7133[#7133]_
-- `ORDER BY` for big (>34 digits) _int128_ values is broken when index on that field is used

_Fixed by Alex Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/7077[#7077]_
-- `EXECUTE BLOCK` (without `RETURNS`) do not work with batches

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/7009[#7009]_
-- `IReplicatedTransaction` receives wrong savepoint event

_Fixed by Dimitry Sibiryakov, Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6942[#6942]_
-- Incorrect singleton error with `MERGE` and `RETURNING`

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6869[#6869]_
-- Domain CHECK-expression can be ignored when we `DROP` objects that are involved in it

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/6807[#6807]_
-- Regression: error "`__Unexpected end of command__`" with incorrect line/column info

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/5749[#5749]_
-- "`__Token unknown__`" error on formfeed in query

_Fixed by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/3812[#3812]_
-- Query with a stored procedure doesn't accept explicit plan

_Fixed by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/3218[#3218]_
-- Optimizer fails applying stream-local predicates before merging

_Fixed by Dmitry Yemanov_

'''

[[bug-500b1-crashes]]
=== Server Crashes/Hangups

_https://github.com/FirebirdSQL/firebird/pull/7195[#7195]_
-- Crash when accessing already cleared memory in the sorting module

_Fixed by Andrey Kravchenko_

'''

[[bug-500b1-utilities]]
=== Utilities

[[bug-500b1-utilities-gbak]]
==== gbak

_https://github.com/FirebirdSQL/firebird/issues/7436[#7436]_
-- Backup error for wide table

_Fixed by Alex Peshkov_

'''
