[[rnfb50-compat]]
= Compatibility Issues

In this section are features and modifications that might affect the way you have installed and used Firebird in earlier releases.

[[rnfb50-compat-sql]]
== SQL

Changes that may affect existing SQL code:

[[rnfb50-compat-returning]]
=== Multi-row RETURNING clause

User-specified `UPDATE`/ `DELETE` / `MERGE` queries containing the `RETURNING` clause may now return multiple records instead of raising error "multiple rows in singleton select" as it happened before.

[[rnfb50-compat-wnet]]
== Removal of WNET protocol

Network protocol _WNET_ (aka Named Pipes, aka NetBEIU) priorly supported on Windows platform is removed in Firebird 5.0. Those Windows users who operated with any _WNET_ connection string (_\\server\dbname_ or _wnet://server/dbname_) should switch to _INET_ (TCP) protocol instead (connection string _server:dbname_ or _inet://server/dbname_).

[[rnfb50-compat-qli]]
== Removal of QLI

Command-line utility _QLI_ is removed in Firebird 5.0, in accordance with its deprecation announcement published in the Firebird 4.0 release notes.
