[[rnfb50-compat]]
= Compatibility Issues

This section lists features and modifications that might affect the way you have installed and used Firebird in earlier releases.

[[rnfb50-compat-sql]]
== SQL

Changes that may affect existing SQL code:

[[rnfb50-compat-returning]]
=== Multi-row RETURNING behaviour

Client-side `INSERT ... SELECT`, `UPDATE`, `DELETE`, `MERGE` and `UPDATE OR INSERT`  queries containing the `RETURNING` clause may now return multiple records instead of raising error "`multiple rows in singleton select`" as it happened before.

These queries are now described as _isc_info_sql_stmt_select_ during preparation, while in previous versions they were described as _isc_info_sql_stmt_exec_procedure_.

Singleton `INSERT ... VALUES` statements, as well as positioned `UPDATE` and `DELETE` statements (i.e. the ones containing the `WHERE CURRENT OF` clause) preserve the existing behaviour, being described as _isc_info_sql_stmt_exec_procedure_.
They also preserve the ability of being executed within a single protocol roundtrip to the server.

However, all these queries, if used in PSQL and the `RETURNING` clause is applied, are still treated as singleton.

[[rnfb50-compat-wnet]]
== Removal of WNET protocol

Network protocol _WNET_ (a.k.a. Named Pipes, a.k.a. NetBEIU) previously supported on Windows platform is removed in Firebird 5.0.
Those Windows users who operated with any _WNET_ connection string (`\\server\dbname` or `wnet://server/dbname`) should switch to _INET_ (TCP) protocol instead (connection string `server:dbname`, `server/port:dbname`,  `inet://server/dbname`, or `inet://server:port/dbname`).

[[rnfb50-compat-qli]]
== Removal of QLI

Command-line utility _QLI_ is removed in Firebird 5.0, in accordance with its deprecation announcement published in the Firebird 4.0 release notes.
