[[rnfb50-fbconf]]
= Configuration Additions and Changes

New configuration parameters:

[[rnfb50-config-parallel]]
== Parameters for Parallel Operations

[[rnfb50-config-max-parallel-workers]]
=== MaxParallelWorkers

Limits the total number of parallel workers that can be created within a single Firebird process for each attached database.
Integer values in the range between 1 (no parallelism) and 64 are allowed.
All other values are silently ignored and the default value of 1 is used.

[NOTE]
====
Workers are accounted for each attached database independently.
====

[[rnfb50-config-parallel-workers]]
=== ParallelWorkers

Specifies the default number of parallel workers for a single task.
Integer values in the range between 1 (no parallelism) and _MaxParallelWorkers_ (see above) are allowed.
All other values are silently ignored and the default value of 1 is used.

[[rnfb50-config-other]]

== Other Parameters

=== MaxStatementCacheSize

Defines the maximum amount of memory used to cache unused DSQL compiled statements.
Value of zero means no statement caching is used.
Default value is 2 megabytes.

=== OnDisconnectTriggerTimeout

Configures a timeout (in seconds) that is applied to the `ON DISCONNECT` trigger execution.
The trigger will be automatically cancelled by the engine after the specified time is passed.
Value of zero ('```0```') means no timeout is set.
Default value is 180 seconds.

=== DefaultProfilerPlugin

Specifies the default profiler plugin used to profile connections using the `RDB$PROFILER` package.

[[rnfb50-config-changes]]

Changed configuration parameters:

=== WireCryptPlugin

A new variant (using 64-bit internal counter rather than 32-bit) of the ChaCha#20 plugin was added.
The new default value of this parameter is now `ChaCha64, ChaCha, Arc4`.

[[rnfb50-config-cleanup]]

Removed configuration parameters:

=== RemotePipeName

This parameter was removed along with the removal of WNET (aka named pipes) protocol support for Windows.

=== TcpLoopbackFastPath

This parameter was removed because Microsoft discourages using the SIO_LOOPBACK_FAST_PATH socket option.

[[rnfb50-replconf]]
== Replication Configuration Additions and Changes

=== cascade_replication

New parameter that specifies whether changes applied to the replica database will be also subject of further replication (if any configured).
Default value is false (cascading is disabled).

