[[rnfb50-fbconf]]
= Configuration Additions and Changes

New configuration parameters:

[[rnfb50-config-parallel]]
== Parameters for Parallel Operations

[[rnfb50-config-max-parallel-workers]]
=== MaxParallelWorkers

Limits the total number of parallel workers that can be created within a single Firebird process for each attached database.
Integer values in the range between 1 (no parallelism) and 64 are allowed.
All other values are silently ignored and the default value of 1 is used.

[NOTE]
====
Workers are accounted for each attached database independently.
====

[[rnfb50-config-parallel-workers]]
=== ParallelWorkers

Specifies the default number of parallel workers for a single task.
Integer values in the range between 1 (no parallelism) and _MaxParallelWorkers_ (see above) are allowed.
All other values are silently ignored and the default value of 1 is used.

[[rnfb50-config-other]]
== Other Parameters

[[rnfb50-config-max-stmt-cache]]
=== MaxStatementCacheSize

Defines the maximum amount of memory used to cache unused DSQL compiled statements.
A value of zero ('```0```') means no statement caching is used.
Default value is 2 megabytes.

[[rnfb50-config-disconnect-trg-timeout]]
=== OnDisconnectTriggerTimeout

Configures a timeout (in seconds) that is applied to the `ON DISCONNECT` trigger execution.
The trigger will be automatically cancelled by the engine after the specified time has passed.
A value of zero ('```0```') means no timeout is set.
Default value is 180 seconds.

[[rnfb50-config-default-profiler]]
=== DefaultProfilerPlugin

Specifies the default profiler plugin used to profile connections using the `RDB$PROFILER` package.

[[rnfb50-config-optimize-mode]]
=== OptimizeForFirstRows

Defines whether queries should be optimized to retrieve the first records as soon as possible rather than returning the whole dataset as soon as possible.
By default, retrieval of all rows is implied by the optimizer.

See also <<rnfb50-dml-select-optimize>> and <<rnfb50-msql-optimize-set>>.

[[rnfb50-config-changes]]
== Changed configuration parameters

=== WireCryptPlugin

A new variant of the ChaCha#20 plugin was added.
It uses a 64-bit internal counter rather than 32-bit.
The new default value of this parameter is now `ChaCha64, ChaCha, Arc4`.

[[rnfb50-replconf]]
== Replication Configuration Additions and Changes

[[rnfb50-replconf-cascade]]
=== cascade_replication

Specifies whether changes applied to the replica database will be also subject of further replication (if any configured).
Default value is false (cascading is disabled).

[[rnfb50-replconf-macros]]
=== Allow macros in replication.conf

Configuration file macros are now also supported in replication.conf.

[[rnfb50-config-cleanup]]
== Removed configuration parameters

[[rnfb50-config-cleanup-wnet]]
=== RemotePipeName

This parameter was removed along with the removal of WNET (aka named pipes) protocol support for Windows.

[[rnfb50-config-cleanup-fast-path]]
=== TcpLoopbackFastPath

This parameter was removed because Microsoft discourages using the SIO_LOOPBACK_FAST_PATH socket option.

