[[rnfb50-general]]
= General Notes

Thank you for choosing Firebird 5.0.
We cordially invite you to test it hard against your expectations and engage with us in identifying and fixing any bugs you might encounter.

ODS (On-Disk Structure) 13.1 is introduced.
It's a minor ODS upgrade, so databases in ODS 13.0 (created by Firebird 4.0) may still be opened with a Firebird 5.0 server (with some new features being unavailable), but databases in older ODS cannot be opened.

[NOTE]
====
Databases created in pre-Beta builds of Firebird 5.0 may be inaccessible in the Release Candidate 1 release and have to be recreated.
ODS was changed a few times during the development cycle and the Firebird Project generally does not guarantee ODS being stable before the Beta stage.

RC1 has an ODS change affecting the profiler, specifically with nullability and default values of its procedures and functions.
If you intend to use (or have already used) the profiler, it is advisable to recreate the database.

Also, if you used the profiler in a pre-RC1 build, and don't intend to recreate the database, you will need to drop the tables and views prefixed with `PLG$PROF` due to changes in these tables (which are not considered part of the ODS).
The next use of the profiler will recreate these tables and views.
====

The engine library is still named `engine13.dll` (Windows) and `libEngine13.so` (POSIX).
The security database is named `security5.fdb`.
Binaries layout and configuration are unchanged from Firebird 4.

[NOTE]
====
That said, you can copy the Firebird engine library from the Firebird 3.0 distribution package (named `engine12.dll` (Windows) and `libEngine12.so` (POSIX), and located inside the `/plugins` sub-directory) to continue working with databases in ODS 12 without needing a backup/restore.
However, new features introduced with Firebird 4.0 and Firebird 5.0 will not be accessible.
====

[[rnfb50-general-compat]]
== Compatibility with Older Versions

Known incompatibilities are detailed in the <<rnfb50-compat,Compatibility Issues>> chapter.

[[rnfb50-general-v501]]
== Sub-release V.5.0.1

Bugs reported and fixed prior to the version 5.0.1 release are listed <<bug-501,HERE>>.

[[rnfb50-general-improvements-v501]]
=== V.5.0.1 Improvements

_https://github.com/FirebirdSQL/firebird/pull/8181[#8181]_
-- Ensure the standalone CS listener on Linux uses the _SO_REUSEADDR_ socket option  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8165[#8165]_
-- Added shutdown handler for _Classic Server_  

_Implemented by Alexander Peshkov, Alexander_

'''

_https://github.com/FirebirdSQL/firebird/issues/8104[#8104]_
-- More efficient evaluation of expressions like `RDB$DB_KEY \<= ?` after mass delete   

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8066[#8066]_
-- Make protocol schemes case-insensitive  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/pull/8061[#8061]_
-- Unnest `IN/ANY/EXISTS` sub-queries and optimize them using semi-join algorithm  

See also the configuration parameter <<rnfb50-config-sub-query-conversion, SubQueryConversion>>.

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8042[#8042]_
-- Improve conflict resolution on replica when table have both primary and unique keys  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8030[#8030]_
-- Better cardinality estimation because when empty data pages exist  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8010[#8010]_
-- Remove `gfix -cache` option  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7978[#7978]_
-- Update Windows distributions with _zlib_ version 1.3.1  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7928[#7928]_
--  Make _TempCacheLimit_ setting to be per-database (not per-attachment) for _SuperClassic_  

_Implemented by Vlad Khorsun_

'''

[[rnfb50-general-bugreport]]
== Bug Reporting

Bugs fixed in this release are listed and described in the chapter entitled <<rnfb50-bug,Bugs Fixed>>.

* If you think you have discovered a new bug in this release, please make a point of reading the instructions for bug reporting in the article https://www.firebirdsql.org/en/how-to-report-bugs/[How to Report Bugs Effectively], at the Firebird Project website.
* If you think a bug fix has not worked, or has caused a regression, please locate the original bug report in the Tracker, reopen it if necessary, and follow the instructions below.

Follow these guidelines as you attempt to analyse your bug:

. Write detailed bug reports, supplying the exact build number of your Firebird kit.
Also provide details of the OS platform.
. Include reproducible test data in your report and post it to our https://github.com/FirebirdSQL/firebird/issues[Tracker].

[[rnfb50-general-docs]]
== Documentation

You will find all the README documents referred to in these notes -- as well as many others not referred to -- in the doc subdirectory of your Firebird 5.0 installation.

__ -- The Firebird Project__
