[[rnfb50-general]]
= General Notes

Thank you for choosing Firebird 5.0.
We cordially invite you to test it hard against your expectations and engage with us in identifying and fixing any bugs you might encounter.

ODS (On-Disk Structure) 13.1 is introduced.
It's a minor ODS upgrade, so databases in ODS 13.0 (created by Firebird 4.0) may still be opened with a Firebird 5.0 server (with some new features being unavailable), but databases in older ODS cannot be opened.

[NOTE]
====
Databases created in pre-Beta builds of Firebird 5.0 may be inaccessible in the Release Candidate 1 release and have to be recreated.
ODS was changed a few times during the development cycle and the Firebird Project generally does not guarantee ODS being stable before the Beta stage.

If you used the profiler in a pre-RC1 build, you will need to drop the tables prefixed with `PLG$PROF` due to changes in these tables (which are not considered part of the ODS).
====

The engine library is still named `engine13.dll` (Windows) and `libEngine13.so` (POSIX).
The security database is named `security5.fdb`.
Binaries layout and configuration are unchanged from Firebird 4.

[NOTE]
====
That said, you can copy the Firebird engine library from the Firebird 3.0 distribution package (named `engine12.dll` (Windows) and `libEngine12.so` (POSIX), and located inside the `/plugins` sub-directory) to continue working with databases in ODS 12 without needing a backup/restore.
However, new features introduced with Firebird 4.0 and Firebird 5.0 will not be accessible.
====

[[rnfb50-general-compat]]
== Compatibility with Older Versions

Known incompatibilities are detailed in the <<rnfb50-compat,Compatibility Issues>> chapter.

[[rnfb50-general-bugreport]]
== Bug Reporting

Bugs fixed in this release are listed and described in the chapter entitled <<rnfb50-bug,Bugs Fixed>>.

* If you think you have discovered a new bug in this release, please make a point of reading the instructions for bug reporting in the article https://www.firebirdsql.org/en/how-to-report-bugs/[How to Report Bugs Effectively], at the Firebird Project website.
* If you think a bug fix has not worked, or has caused a regression, please locate the original bug report in the Tracker, reopen it if necessary, and follow the instructions below.

Follow these guidelines as you attempt to analyse your bug:

. Write detailed bug reports, supplying the exact build number of your Firebird kit.
Also provide details of the OS platform.
. Include reproducible test data in your report and post it to our https://github.com/FirebirdSQL/firebird/issues[Tracker].

[[rnfb50-general-docs]]
== Documentation

You will find all the README documents referred to in these notes -- as well as many others not referred to -- in the doc subdirectory of your Firebird 5.0 installation.

__ -- The Firebird Project__
