[[rnfb50-general]]
= General Notes

Thank you for choosing Firebird 5.0.
We cordially invite you to test it hard against your expectations and engage with us in identifying and fixing any bugs you might encounter.

ODS (On-Disk Structure) 13.1 is introduced.
It's a minor ODS upgrade, so databases in ODS 13.0 (created by Firebird 4.0) may still be opened with a Firebird 5.0 server (with some new features being unavailable), but databases in older ODS cannot be opened.

[NOTE]
====
Databases created in pre-release builds of Firebird 5.0 may be inaccessible in the 5.0.0 final release and higher and have to be recreated.
The ODS was changed a few times during the development cycle and the Firebird Project generally does not guarantee ODS being stable before the Beta stage.

In addition, 5.0.0 RC1 had an ODS change affecting the profiler, specifically with nullability and default values of its procedures and functions.
If you intend to use (or have already used) the profiler, it is advisable to recreate the database.

Also, if you used the profiler in a pre-RC1 build, and don't intend to recreate the database, you will need to drop the tables and views prefixed with `PLG$PROF` due to changes in these tables (which are not considered part of the ODS).
The next use of the profiler will recreate these tables and views.
====

The engine library is still named `engine13.dll` (Windows) and `libEngine13.so` (POSIX).
The security database is named `security5.fdb`.
Binaries layout and configuration are unchanged from Firebird 4.

[NOTE]
====
That said, you can copy the Firebird engine library from the Firebird 3.0 distribution package (named `engine12.dll` (Windows) and `libEngine12.so` (POSIX), and located inside the `/plugins` sub-directory) to continue working with databases in ODS 12 without needing a backup/restore.
However, new features introduced with Firebird 4.0 and Firebird 5.0 will not be accessible.
====

[[rnfb50-general-compat]]
== Compatibility with Older Versions

Known incompatibilities are detailed in the <<rnfb50-compat,Compatibility Issues>> chapter.

[[rnfb50-general-v503]]
== Sub-release V.5.0.3

Bugs reported and fixed prior to the version 5.0.3 release are listed <<bug-503,HERE>>.

[[rnfb50-general-improvements-v503]]
=== V.5.0.3 Improvements

_https://github.com/FirebirdSQL/firebird/issues/8598[#8598]_
-- Don't fire referential integrity triggers if primary or unique keys haven't changed  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8523[#8523]_
-- Exception in _fbclient_ during first `isc_attach_database`  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8522[#8522]_
-- Exception in _fbclient_ during `isc_detach_database`  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/pull/8513[#8513]_
-- Makes `MON$COMPILED_STATEMENTS` and `MON$STATEMENTS` share blobs with text and plan content of the same statement  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/pull/8447[#8447]_
-- Avoid index scan for lower/upper bounds containing NULL keys  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8433[#8433]_
-- Improve code of class `BePlusTree`   

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/pull/8421[#8421]_
-- Add pointers tree to `TempSpace` class   

_Implemented by Andrey Kravchenko, Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/pull/8318[#8318]_
-- Send small blobs inline  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8278[#8278]_
-- Avoid index lookup for a NULL key if the condition is known to always be `FALSE` in this case  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/6413[#6413]_
-- Data pages of newly _gbak_ restored databases should marked as "swept" [CORE6164]  

_Implemented by Vlad Khorsun_

'''


[[rnfb50-general-v502]]
== Sub-release V.5.0.2

Bugs reported and fixed prior to the version 5.0.2 release are listed <<bug-502,HERE>>.

[[rnfb50-general-improvements-v502]]
=== V.5.0.2 Improvements

_https://github.com/FirebirdSQL/firebird/issues/8356[#8356]_
-- Make _trace_ use HEX representation for parameter values ​​of types `[VAR]CHAR CHARACTER SET OCTETS` and `[VAR]BINARY`  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8353[#8353]_
-- Report unique usernames for `isc_info_user_names`  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/pull/8323[#8323]_
-- Add `AUTO RELEASE TEMP BLOBID` transaction option  

_Implemented by Ilya Eremin_

'''

_https://github.com/FirebirdSQL/firebird/pull/8310[#8310]_
-- Collect network statistics and make it available for user applications  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/pull/8307[#8307]_
-- Wire protocol improvement: prefetch blob info and some data when opening a blob  

_Implemented by Vlad Khorsun_

[TIP]
====
This enhancement was sponsored by the donations collected in the 21 Firebird Developers Day, many thanks to everyone involved!
====

'''

_https://github.com/FirebirdSQL/firebird/issues/8291[#8291]_
-- NULLs should be skipped during index navigation when there's no lower bound and matched conditions are known to ignore NULLs  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8273[#8273]_
-- Reorganize public headers  

_Implemented by Adriano dos Santos Fernandes_

'''

_https://github.com/FirebirdSQL/firebird/issues/8256[#8256]_
-- _Win_SSPI_ plugin should try _Negotiate_ before _NTLM_  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8197[#8197]_
-- Add generated files for OO API for C language to distribution  

_Implemented by Alexander Peshkov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8161[#8161]_
-- Cardinality estimation should use primary record versions only  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7269[#7269]_
-- Database restore must make every effort on activating deferred indexes  

_Implemented by Vlad Khorsun, Dima_

'''

[[rnfb50-general-v501]]
== Sub-release V.5.0.1

Bugs reported and fixed prior to the version 5.0.1 release are listed <<bug-501,HERE>>.

[[rnfb50-general-improvements-v501]]
=== V.5.0.1 Improvements

_https://github.com/FirebirdSQL/firebird/pull/8181[#8181]_
-- Ensure the standalone CS listener on Linux uses the _SO_REUSEADDR_ socket option  

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/pull/8165[#8165]_
-- Added shutdown handler for _Classic Server_  

_Implemented by Alexander Peshkov, Alexander Zhdanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8104[#8104]_
-- More efficient evaluation of expressions like `++RDB$DB_KEY <= ?++` after mass delete

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8066[#8066]_
-- Make protocol schemes case-insensitive  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/pull/8061[#8061]_
-- Unnest `IN/ANY/EXISTS` sub-queries and optimize them using semi-join algorithm  

See also the configuration parameter <<rnfb50-config-sub-query-conversion, SubQueryConversion>>.

_Implemented by Dmitry Yemanov_

'''

_https://github.com/FirebirdSQL/firebird/issues/8042[#8042]_
-- Improve conflict resolution on replica when table has both primary and unique keys

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8030[#8030]_
-- Better cardinality estimation when empty data pages exist

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/8010[#8010]_
-- Remove `gfix -cache` option  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7978[#7978]_
-- Update Windows distributions with _zlib_ version 1.3.1  

_Implemented by Vlad Khorsun_

'''

_https://github.com/FirebirdSQL/firebird/issues/7928[#7928]_
--  Make _TempCacheLimit_ setting to be per-database (not per-attachment) for _SuperClassic_  

_Implemented by Vlad Khorsun_

'''

[[rnfb50-general-bugreport]]
== Bug Reporting

Bugs fixed in this release are listed and described in the chapter entitled <<rnfb50-bug,Bugs Fixed>>.

* If you think you have discovered a new bug in this release, please make a point of reading the instructions for bug reporting in the article https://www.firebirdsql.org/en/how-to-report-bugs/[How to Report Bugs Effectively], at the Firebird Project website.
* If you think a bug fix has not worked, or has caused a regression, please locate the original bug report in the Tracker, reopen it if necessary, and follow the instructions below.

Follow these guidelines as you attempt to analyse your bug:

. Write detailed bug reports, supplying the exact build number of your Firebird kit.
Also provide details of the OS platform.
. Include reproducible test data in your report and post it to our https://github.com/FirebirdSQL/firebird/issues[Tracker].

[[rnfb50-general-docs]]
== Documentation

You will find all the README documents referred to in these notes -- as well as many others not referred to -- in the doc subdirectory of your Firebird 5.0 installation.

__ -- The Firebird Project__
