[[rnfb50-new]]
= New In Firebird 5.0

[[rnfb50-new-summary]]
== Summary of New Features

Firebird 5.0 introduces many improvements without any changes in architecture or operation, the most important are:

- Parallel (multi-threaded) operation for backup/restore, sweep and index creation;
- Partial indices;
- `SKIP LOCKED` clause for `SELECT WITH LOCK`, `UPDATE` and `DELETE` statements;
- Inline minor ODS upgrade;
- Compiled statement cache;
- PSQL and SQL profiler;
- Support for `WHEN NOT MATCHED BY SOURCE` for `MERGE` statement;
- Support multiple rows for DML `RETURNING`;
- New built-in functions and packages;
- Denser record-level compression;
- Network support for scrollable cursors;

The following list summarises the features and changes, with links to the chapters and topics where more detailed information can be found.

[[rnfb50-new-complete]]
=== Complete In Firebird 5.0 Release Candidate 1

Avoid truncation of the access path information inside the `PLG$PROF_RECORD_SOURCES` table to 255 characters::
https://github.com/FirebirdSQL/firebird/pull/7752[#7752]
_by Adriano dos Santos Fernandes_

MacOS: build _libicu_ and static _libc{plus}{plus}_ using _vcpkg_::
https://github.com/FirebirdSQL/firebird/pull/7720[#7720]
_by Adriano dos Santos Fernandes_

Better processing and optimization of `IN <list>` predicates::
https://github.com/FirebirdSQL/firebird/pull/7707[#7707]
_by Dmitry Yemanov_
+
Processing of `IN <list>` predicates is now linear rather than recursive, thus no runtime stack limitations.
The existing limit of 1500 items has been raised to 65535 items.
+
Lists that are known to be constant are pre-evaluated as invariants and cached as a binary search tree, thus making comparisons faster if condition need to be checked for many rows or if the value list is long enough.
+
If the list is very long or if the `IN` predicate is not selective, the index scan supports searching groups using the sibling pointer (i.e. horizontally) rather than searching every group from root (i.e. vertically), thus utilizing just a single index scan for the whole `IN` list.

Make trace config parser resolve symlinks in database file path in trace configuration::
https://github.com/FirebirdSQL/firebird/issues/7692[#7692]
_by Vlad Khorsun_
+
Allow tracing database events even if the trace/audit is configured using a symbolic link instead of a real database file path.

Profiler should not miss query's top-level access paths nodes::
https://github.com/FirebirdSQL/firebird/issues/7688[#7688]
_by Adriano dos Santos Fernandes_

Add `LEVEL` column to `PLG$PROF_RECORD_SOURCES` and `PLG$PROF_RECORD_SOURCE_STATS_VIEW`::
https://github.com/FirebirdSQL/firebird/issues/7687[#7687]
_by Adriano dos Santos Fernandes_
+
Column `LEVEL` is added to the profiler record source tables/views.
It returns the actual indentation level that allows proper reconstruction of multi-line access path nodes.

Add overload `FbVarChar::set` function for non null-terminated string::
https://github.com/FirebirdSQL/firebird/issues/7685[#7685]
_by Adriano dos Santos Fernandes_

Use _ParallelWorkers_ setting from _firebird.conf_ as default for all parallelized operations::
https://github.com/FirebirdSQL/firebird/issues/7682[#7682]
_by Vlad Khorsun_
+
This allows utilities started via the Service Manager to use the server-side _ParallelWorkers_ setting without a need to specify the number of workers explicitly.

Make boot build on Windows a bit more user-friendly::
https://github.com/FirebirdSQL/firebird/pull/7680[#7680]
_by Vlad Khorsun_

Make the profiler store aggregated requests by default, with an option for the detailed store::
https://github.com/FirebirdSQL/firebird/issues/7652[#7652]
_by Adriano dos Santos Fernandes_
+
Make the profiler data aggregated at the statement level by default (with `REQUEST_ID = 0`), thus making the flushing faster.
A detailed (non-aggregated) data may be requested explicitly by specifying the 'DETAILED_REQUESTS' value in the `PLUGIN_OPTIONS` parameter of the `RDB$PROFILER.START_SESSION` function.

Getting the current `DECFLOAT ROUND/TRAPS` settings::
https://github.com/FirebirdSQL/firebird/issues/7642[#7642]
_by Alexander Peshkov_
+
New context variables `DECFLOAT_ROUND` and `DECFLOAT_TRAPS` are added to the `SYSTEM` namespace of the `RDB$GET_CONTEXT` function.
They return the current settings of the corresponding session options.

Run as application not specifying switch `-a`::
https://github.com/FirebirdSQL/firebird/issues/7637[#7637]
_by Vlad Khorsun_
+
Command-line switch `-a` is no longer required on Windows to start the Firebird server as an application.

Include Performance Cores only in default affinity mask::
https://github.com/FirebirdSQL/firebird/issues/7634[#7634]
_by Vlad Khorsun_
+
Some modern CPUs may contain two sets of cores - Efficient (E) and Performance (P).
By default Firebird runs on all available cores and that may cause performance degradation in CPU-bound tasks.
Now, E-cores are excluded from the default affinity mask.
If the _AffinityMask_ configuration setting is used explicitly, please pay attention which types of cores are specified to be enabled.

Allow nested parenthesized joined table::
https://github.com/FirebirdSQL/firebird/issues/7576[#7576]
_by Mark Rotteveel_

Optimize creation of expression and partial indices::
https://github.com/FirebirdSQL/firebird/pull/7559[#7559]
_by Dmitry Yemanov_

Add support for `-parallel` in combination with `gfix -icu`::
https://github.com/FirebirdSQL/firebird/issues/7550[#7550]
_by Vlad Khorsun_
+
`gfix -icu` rebuilds indexes and thus can benefit from parallelization.
Now it's allowed to use the `-icu` and `-parallel` switches together, to override the _ParallelWorkers_ setting used by default.

Compiler warnings raise when build cloop-generated _Firebird.pas_ in RAD Studio 11.3::
https://github.com/FirebirdSQL/firebird/issues/7542[#7542]
_by Vlad Khorsun_

`RDB$GET/SET_CONTEXT()`: enclosing in apostrophes or double quotes of a missed namespace/variable will make output more readable::
https://github.com/FirebirdSQL/firebird/issues/7539[#7539]
_by Vlad Khorsun_

Add ability to query current value of parallel workers for an attachment::
https://github.com/FirebirdSQL/firebird/issues/7536[#7536]
_by Vlad Khorsun_
+
* New column `MON$PARALLEL_WORKERS INTEGER` was added into `MON$ATTACHMENTS` table.
* New variable `PARALLEL_WORKERS` is now available in the `SYSTEM` context of the `RDB$GET_CONTEXT` function.
* New tag _fb_info_parallel_workers_ (value 149) is available in `IAttachment::getInfo()` and `isc_database_info()` API calls.

Reduce output of the `SHOW GRANTS` command::
https://github.com/FirebirdSQL/firebird/pull/7506[#7506]
_by Artyom Ivanov_

Firebird performance issue -- unnecessary index reads::
https://github.com/FirebirdSQL/firebird/issues/7494[#7494]
_by Vlad Khorsun_
+
Index scan algorithm has been improved to avoid unnecessary record reads for partial lookups in compound indices.

`SHOW SYSTEM` command: provide list of functions belonging to system packages::
https://github.com/FirebirdSQL/firebird/issues/7475[#7475]
_by Alexander Peshkov_

Make Android port (client/embedded) work inside apps::
https://github.com/FirebirdSQL/firebird/pull/7469[#7469]
_by Adriano dos Santos Fernandes_

Add COMPILE trace events for procedures/functions/triggers::
https://github.com/FirebirdSQL/firebird/pull/7466[#7466]
_by Dmitry Yemanov_
+
Allows to trace parse/compile events for the stored modules, corresponding elapsed time and also plans for queries inside those PSQL modules.

Add REPLICA MODE to the output of the _isql_ `SHOW DATABASE` command::
https://github.com/FirebirdSQL/firebird/issues/7425[#7425]
_by Dmitry Yemanov_

Surface internal optimization modes (all rows vs first rows) at the SQL and configuration levels::
https://github.com/FirebirdSQL/firebird/pull/7405[#7405]
_by Dmitry Yemanov_
+
This feature allows the optimizer to consider another (hopefully better) plan if only a subset or rows is fetched initially by the user application (with the remaining rows being fetched on demand), thus improving the response time.
It can be specified in the SQL query using the `OPTIMIZE FOR {FIRST | ALL} ROWS` clause, at the session level using the `SET OPTIMIZE FOR {FIRST | ALL} ROWS` management statement.
The default behaviour may be specified globally using the _OptimizeForFirstRows_ setting in the configuration file.

Use Windows private namespace for kernel objects used in server-to-server IPC::
https://github.com/FirebirdSQL/firebird/pull/7213[#7213]
_by Vlad Khorsun_
+
This improvement allows to synchronize Firebird processes across different Windows sessions.

Make ability to add comment to mapping (`COMMENT ON MAPPING ... IS ...`)::
https://github.com/FirebirdSQL/firebird/issues/7046[#7046]
_by Alexander Peshkov_

_ISQL_ showing publication status::
https://github.com/FirebirdSQL/firebird/issues/7001[#7001]
_by Dmitry Yemanov_

Add support for `QUARTER` to `EXTRACT`, `FIRST_DAY` and `LAST_DAY` functions::
https://github.com/FirebirdSQL/firebird/issues/5959[#5959]
_by Adriano dos Santos Fernandes_

=== Complete In Firebird 5.0 Beta 1

Parallel (multi-threaded) operations::
https://github.com/FirebirdSQL/firebird/issues/1783[#1783], https://github.com/FirebirdSQL/firebird/issues/3374[#3374], https://github.com/FirebirdSQL/firebird/issues/7447[#7447]
_by Vlad Khorsun_
+
Such operations as logical backup/restore, sweeping and `CREATE INDEX` statement execution can be executed in parallel by multiple threads, thus decreasing the total operation time.
+
See chapters <<rnfb50-engine-parallel>>, <<rnfb50-utils-gbak-parallel>> and <<rnfb50-utils-gfix-parallel>> for more details.

Support for partial indices::
https://github.com/FirebirdSQL/firebird/pull/7257[#7257]
_by Dmitry Yemanov_
+
The `CREATE INDEX` DDL statement has been extended to support <<rnfb50-ddl-partial-indices, partial indices>>, i.e. an index may now declare a condition that defines the subset of records to be indexed.

`SKIP LOCKED` clause::
https://github.com/FirebirdSQL/firebird/pull/7350[#7350]
_by Adriano dos Santos Fernandes_
+
New clause <<rnfb50-dml-skip-locked, `SKIP LOCKED`>> was introduced for statements `SELECT WITH LOCK`, `UPDATE` and `DELETE`.
It allows to skip the already locked records while reading the table.

Inline minor ODS upgrade::
https://github.com/FirebirdSQL/firebird/pull/7397[#7397]
_by Dmitry Yemanov_
+
An ability to <<rnfb50-engine-inline-upgrade, upgrade the database>> to the latest minor ODS version has been introduced, it does not require a backup/restore cycle.

Compiled statement cache::
https://github.com/FirebirdSQL/firebird/pull/7144[#7144]
_by Adriano dos Santos Fernandes_
+
A per-attachment <<rnfb50-engine-stmt-cache, cache of compiled SQL statements>> has been implemented.

PSQL and SQL profiler::
https://github.com/FirebirdSQL/firebird/pull/7086[#7086]
_by Adriano dos Santos Fernandes_
+
A built-in ability to <<rnfb50-engine-profiler, profile SQL and PSQL statements>> has been added, thus making it possible to measure execution time at different levels.

Support for `WHEN NOT MATCHED BY SOURCE` in the `MERGE` statement::
https://github.com/FirebirdSQL/firebird/issues/6681[#6681]
_by Adriano dos Santos Fernandes_
+
The `MERGE` statement has been extended to support the <<rnfb50-dml-matched-by-source, `WHEN NOT MATCHED BY SOURCE` clause>>.

Built-in functions `UNICODE_CHAR` and `UNICODE_VAL`::
https://github.com/FirebirdSQL/firebird/issues/6798[#6798]
_by Adriano dos Santos Fernandes_
+
New <<rnfb50-dml-unicode-funcs, built-in functions `UNICODE_CHAR` and `UNICODE_VAL`>> have been added to allow conversion between Unicode code point and character.

`RDB$BLOB_UTIL` new system package::
https://github.com/FirebirdSQL/firebird/pull/281[#281]
_by Adriano dos Santos Fernandes_
+
New <<rnfb50-engine-blob-util, system package `RDB$BLOB_UTIL`>> has been added to allow various operations with BLOBs in the PSQL modules.

Support multiple rows being returned by DML with the `RETURNING` clause::
https://github.com/FirebirdSQL/firebird/issues/6815[#6815]
_by Adriano dos Santos Fernandes_
+
The `RETURNING` clause, if used in DSQL queries, now <<rnfb50-compat-returning, allows multiple rows to be returned>>.

Optimize the record-level RLE algorithm for a denser compression of shorter-than-declared strings and sets of subsequent NULLs::
https://github.com/FirebirdSQL/firebird/issues/4723[#4723]
_by Dmitry Yemanov_
+
The built-in <<rnfb50-engine-rle, compression algorithm has been improved>> to allow denser compression of records.

More cursor-related details in the plan output::
https://github.com/FirebirdSQL/firebird/pull/7441[#7441]
_by Dmitry Yemanov_
+
Execution plan now contains <<rnfb50-engine-cursor-info, more information about cursors>>.

Other improvements are briefly listed below, please follow the tracker references for more information.

Unify display of system procedures & packages with other system objects::
https://github.com/FirebirdSQL/firebird/issues/7411[#7411]
_by Alexander Peshkov_
+
System procedures and packages are now shown by <<rnfb50-utils-show-system-proc,`SHOW SYSTEM`>>.

Simplify client library build::
https://github.com/FirebirdSQL/firebird/pull/7399[#7399]
_by Adriano dos Santos Fernandes_

Performance improvement for BLOB copying::
https://github.com/FirebirdSQL/firebird/issues/7382[#7382]
_by Adriano dos Santos Fernandes_

Cost-based choice between nested loop join and hash join::
https://github.com/FirebirdSQL/firebird/issues/7331[#7331]
_by Dmitry Yemanov_

Create Android packages with all necessary files in all architectures (_x86_, _x64_, _arm32_, _arm64_)::
https://github.com/FirebirdSQL/firebird/pull/7293[#7293]
_by Adriano dos Santos Fernandes_

Unify release filenames::
https://github.com/FirebirdSQL/firebird/pull/7284[#7284]
_by Adriano dos Santos Fernandes_

Improve ICU version mismatch diagnostics::
https://github.com/FirebirdSQL/firebird/issues/7169[#7169]
_by Adriano dos Santos Fernandes_

Provide ability to see in the trace log events related to missing security context::
https://github.com/FirebirdSQL/firebird/issues/7165[#7165]
_by Alexander Peshkov_
+
For more details, see <<rnfb50-security-trace-ctx>>.

`ResultSet.getInfo()` new API method::
https://github.com/FirebirdSQL/firebird/pull/7083[#7083]
_by Dmitry Yemanov_

Network support for scrollable cursors::
https://github.com/FirebirdSQL/firebird/issues/7051[#7051]
_by Dmitry Yemanov_

Add table `MON$COMPILED_STATEMENTS` and also column `MON$COMPILED_STATEMENT_ID` to both `MON$STATEMENTS` and `MON$CALL_STACK` tables::
https://github.com/FirebirdSQL/firebird/pull/7050[#7050]
_by Adriano dos Santos Fernandes_

Make ability to add comment to mapping ('`COMMENT ON MAPPING ... IS ...`')::
https://github.com/FirebirdSQL/firebird/issues/7046[#7046]
_by Alexander Peshkov_
+
For more details, see <<rnfb50-ddl-comment-mapping>>.

Results of negation must be the same for each datatype (`SMALLINT` / `INT` / `BIGINT` / `INT128`) when argument is minimum value for this type::
https://github.com/FirebirdSQL/firebird/issues/7025[#7025]
_by Alexander Peshkov_

Transform OUTER joins into INNER ones if the WHERE condition violates the outer join rules::
https://github.com/FirebirdSQL/firebird/issues/6992[#6992]
_by Dmitry Yemanov_

Add way to retrieve statement BLR with `Statement.getInfo()` and _ISQL_'s `SET EXEC_PATH_DISPLAY BLR`::
https://github.com/FirebirdSQL/firebird/issues/6910[#6910]
_by Adriano dos Santos Fernandes_
+
For _isql_, see <<rnfb50-utils-exec-path-blr>>.

`SIMILAR TO` should use index when pattern starts with non-wildcard character (as `LIKE` does)::
https://github.com/FirebirdSQL/firebird/issues/6873[#6873]
_by Adriano dos Santos Fernandes_

Add column `MON$SESSION_TIMEZONE` to the table `MON$ATTACHMENTS`::
https://github.com/FirebirdSQL/firebird/pull/6794[#6794]
_by Adriano dos Santos Fernandes_

Allow parenthesized query expression for standard-compliance::
https://github.com/FirebirdSQL/firebird/issues/6740[#6740]
_by Adriano dos Santos Fernandes_
+
For more details, see <<rnfb50-dml-parens-query>>.

System table with keywords::
https://github.com/FirebirdSQL/firebird/issues/6713[#6713]
_by Adriano dos Santos Fernandes_

Support full SQL standard character string literal syntax::
https://github.com/FirebirdSQL/firebird/issues/5589[#5589]
_by Adriano dos Santos Fernandes_
+
For more details, see <<rnfb50-dml-literals-char>>.

Support full SQL standard binary string literal syntax::
https://github.com/FirebirdSQL/firebird/issues/5588[#5588]
_by Adriano dos Santos Fernandes_
+
For more details, see <<rnfb50-dml-literals-binary>>.

Allow subroutines to access variables/parameters defined at the outer/parent level::
https://github.com/FirebirdSQL/firebird/issues/4769[#4769]
_by Adriano dos Santos Fernandes_
+
For more details, see <<rnfb50-psql-subroutine-param-access>>.

Avoid data retrieval if the `WHERE` clause always evaluates to `FALSE`::
https://github.com/FirebirdSQL/firebird/issues/1708[#1708]
_by Dmitry Yemanov_
