[[rnfb50-new]]
= New In Firebird 5.0

[[rnfb50-new-summary]]
== Summary of New Features

Firebird 5.0 introduces many improvements without any changes in architecture or operation, the most important are:

- Parallel (multi-threaded) operation for backup/restore, sweep and index creation;
- Partial indices;
- `SKIP LOCKED` clause for `SELECT WITH LOCK`, `UPDATE` and `DELETE` statements;
- Inline minor ODS upgrade;
- Compiled statement cache;
- PSQL and SQL profiler;
- Support for `WHEN NOT MATCHED BY SOURCE` for `MERGE` statement;
- Support multiple rows for DML `RETURNING`;
- New built-in functions and packages;
- Denser record-level compression;
- Network support for scrollable cursors;

The following list summarises the features and changes, with links to the chapters and topics where more detailed information can be found.

[[rnfb50-new-complete]]
=== Complete In Firebird 5.0 Beta 1

Parallel (multi-threaded) operations::
Such operations as logical backup/restore, sweeping and `CREATE INDEX` statement execution can be executed in parallel by multiple threads, thus decreasing the total operation time.
+
Tracker references: https://github.com/FirebirdSQL/firebird/issues/1783[#1783], https://github.com/FirebirdSQL/firebird/issues/3374[#3374], https://github.com/FirebirdSQL/firebird/issues/7447[#7447]
+
See chapters <<rnfb50-engine-parallel>>, <<rnfb50-utils-gbak-parallel>> and <<rnfb50-utils-gfix-parallel>> for more details.

Support for partial indices::
The `CREATE INDEX` DDL statement has been extended to support <<rnfb50-ddl-partial-indices, partial indices>>, i.e. an index may now declare a condition that defines the subset of records to be indexed.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/pull/7257[#7257]

`SKIP LOCKED` clause::
New clause <<rnfb50-dml-skip-locked, `SKIP LOCKED`>> was introduced for statements `SELECT WITH LOCK`, `UPDATE` and `DELETE`.
It allows to skip the already locked records while reading the table.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/pull/7350[#7350]

Inline minor ODS upgrade::
An ability to <<rnfb50-engine-inline-upgrade, upgrade the database>> to the latest minor ODS version has been introduced, it does not require a backup/restore cycle.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/pull/7397[#7397]

Compiled statement cache::
Per-attachment <<rnfb50-engine-stmt-cache, cache of compiled SQL statements>> has been implemented.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/pull/7144[#7144]

PSQL and SQL profiler::
A built-in ability to <<rnfb50-engine-profiler, profile SQL and PSQL statements>> has been added, thus making possible to measure execution time at different levels.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/pull/7086[#7086]

Support for `WHEN NOT MATCHED BY SOURCE` in the `MERGE` statement::
The `MERGE` statement has been extended to support the <<rnfb50-dml-matched-by-source, `WHEN NOT MATCHED BY SOURCE` clause>>.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/6681[#6681]

Built-in functions `UNICODE_CHAR` and `UNICODE_VAL`::
New <<rnfb50-dml-unicode-funcs, built-in functions `UNICODE_CHAR` and `UNICODE_VAL`>> have been added to allow conversion between Unicode code point and character.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/6798[#6798]

`RDB$BLOB_UTIL` new system package::
New <<rnfb50-engine-blob-util, system package `RDB$BLOB_UTIL`>> has been added to allow various operations with BLOBs in the PSQL modules.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/pull/281[#281]

Support multiple rows being returned by DML with the `RETURNING` clause::
The `RETURNING` clause, if used in DSQL queries, now <<rnfb50-compat-returning, allows multiple rows to be returned>>.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/6815[#6815]

Optimize the record-level RLE algorithm for a denser compression of shorter-than-declared strings and sets of subsequent NULLs::
The built-in <<rnfb50-engine-rle, compression algorithm has been improved>> to allow denser compression of records.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/4723[#4723]

More cursor-related details in the plan output::
Execution plan now contains <<rnfb50-engine-cursor-info, more information about cursors>>.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/pull/7441[#7441]

Other improvements are briefly listed below, please follow the tracker references for more information.

Unify display of system procedures & packages with other system objects::
System procedures and packages are now shown by <<rnfb50-utils-show-system-proc,`SHOW SYSTEM`>>.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/7411[#7411]

Simplify client library build::
Tracker reference: https://github.com/FirebirdSQL/firebird/pull/7399[#7399]

Performance improvement for BLOB copying::
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/7382[#7382]

Cost-based choice between nested loop join and hash join::
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/7331[#7331]

Create Android packages with all necessary files in all architectures (_x86, x64, arm32, arm64_)::
Tracker reference: https://github.com/FirebirdSQL/firebird/pull/7293[#7293]

Unify release filenames::
Tracker reference: https://github.com/FirebirdSQL/firebird/pull/7284[#7284]

Improve ICU version mismatch diagnostics::
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/7169[#7169]

Provide ability to see in the trace log events related to missing security context::
For more details, see <<rnfb50-security-trace-ctx>>.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/7165[#7165]

`ResultSet.getInfo()` new API method::
Tracker reference: https://github.com/FirebirdSQL/firebird/pull/7083[#7083]

Network support for scrollable cursors::
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/7051[#7051]

Add table `MON$COMPILED_STATEMENTS` and also column `MON$COMPILED_STATEMENT_ID` to both `MON$STATEMENTS` and `MON$CALL_STACK` tables::
Tracker reference: https://github.com/FirebirdSQL/firebird/pull/7050[#7050]

Make ability to add comment to mapping ('`COMMENT ON MAPPING ... IS ...`')::
For more details, see <<rnfb50-ddl-comment-mapping>>.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/7046[#7046]

Results of negation must be the same for each datatype (`SMALLINT` / `INT` / `BIGINT` / `INT128`) when argument is minimum value for this type::
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/7025[#7025]

Transform OUTER joins into INNER ones if the WHERE condition violates the outer join rules::
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/6992[#6992]

Add way to retrieve statement BLR with `Statement.getInfo()` and _ISQL_'s `SET EXEC_PATH_DISPLAY BLR`::
For _isql_, see <<rnfb50-utils-exec-path-blr>>.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/6910[#6910]

`SIMILAR TO` should use index when pattern starts with non-wildcard character (as `LIKE` does)::
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/6873[#6873]

Add column `MON$SESSION_TIMEZONE` to the table `MON$ATTACHMENTS`::
Tracker reference: https://github.com/FirebirdSQL/firebird/pull/6794[#6794]

Allow parenthesized query expression for standard-compliance::
For more details, see <<rnfb50-dml-parens-query>>.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/6740[#6740]

System table with keywords::
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/6713[#6713]

Support full SQL standard character string literal syntax::
For more details, see <<rnfb50-dml-literals-char>>.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/5589[#5589]

Support full SQL standard binary string literal syntax::
For more details, see <<rnfb50-dml-literals-binary>>.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/5588[#5588]

Allow subroutines to access variables/parameters defined at the outer/parent level::
For more details, see <<rnfb50-psql-subroutine-param-access>>.
+
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/4769[#4769]

Avoid data retrieval if the `WHERE` clause always evaluates to `FALSE`::
Tracker reference: https://github.com/FirebirdSQL/firebird/issues/1708[#1708]
