[[rnfb50-util]]
= Monitoring & Command-line Utilities

Improvements and additions to the Firebird utilities continue.

[[rnfb50-util-mon]]
== Monitoring

New virtual tables: 

`RDB$KEYWORDS`:

[horizontal]
`RDB$KEYWORD_NAME`:: Keyword name
`RDB$KEYWORD_RESERVED`:: Whether keyword is a reserved word

`MON$COMPILED_STATEMENTS`:

[horizontal]
`MON$COMPILED_STATEMENT_ID`:: Compiled statement ID
`MON$SQL_TEXT`:: Text of the SQL query
`MON$EXPLAINED_PLAN`:: Plan (in the explained form) of the SQL query
`MON$OBJECT_NAME`:: PSQL object name
`MON$OBJECT_TYPE`:: PSQL object type
`MON$PACKAGE_NAME`:: Package name of the PSQL object
`MON$STAT_ID`:: Runtime statistics ID (references `MON$*_STATS` tables)

New columns in the tables: 

In `MON$ATTACHMENTS`:

[horizontal]
`MON$SESSION_TIMEZONE`:: Actual timezone of the session

In `MON$STATEMENTS`:

[horizontal]
`MON$COMPILED_STATEMENT_ID`:: Compiled statement ID (references `MON$COMPILED_STATEMENTS`)

In `MON$CALL_STACK`:

[horizontal]
`MON$COMPILED_STATEMENT_ID`:: Compiled statement ID (references `MON$COMPILED_STATEMENTS`)

In `SEC$GLOBAL_AUTH_MAPPING`:

[horizontal]
`SEC$DESCRIPTION`:: Textual description

== _gbak_ and _gfix_

[[rnfb50-utils-parallel]]
=== Parallel backup/restore and sweep
Vlad Khorsun

Tracker tickets: https://github.com/FirebirdSQL/firebird/issues/1783[#1783],
https://github.com/FirebirdSQL/firebird/issues/3374[#3374]

A new command-line switch has been added to _gbak_ and _gfix_: `-PAR[ALLEL] <N>`.

It defines how many parallel workers will be used for the requested task.

Usage example(s):

[source]
----
gbak -b -par 4 -user <username> -pass <password> <dbname> <backupname>
gbak -r -par 4 -user <username> -pass <password> <backupname> <dbname>
gfix -sweep -par 4 -user <username> -pass <password> <dbname>
----

[[rnfb50-utils-gfix-upgrade]]
=== ODS upgrade
Dmitry Yemanov

Tracker tickets: https://github.com/FirebirdSQL/firebird/pull/7397[#7397]

A new command-line switch has been added to _gfix_: `-UP[GRADE]`.

It allows to upgrade ODS of the database to the latest supported minor version (within the supported major version).

Usage example(s):

[source]
----
gfix -upgrade <dbname> -user <username> -pass <password>
----
