[[rnfb50-util]]
= Monitoring & Command-line Utilities

Improvements and additions to the Firebird utilities continue.

[[rnfb50-util-mon]]
== Monitoring

New virtual tables: 

`RDB$KEYWORDS`:

[horizontal]
`RDB$KEYWORD_NAME`:: Keyword name
`RDB$KEYWORD_RESERVED`:: Whether keyword is a reserved word

`MON$COMPILED_STATEMENTS`:

[horizontal]
`MON$COMPILED_STATEMENT_ID`:: Compiled statement ID
`MON$SQL_TEXT`:: Text of the SQL query
`MON$EXPLAINED_PLAN`:: Plan (in the explained form) of the SQL query
`MON$OBJECT_NAME`:: PSQL object name
`MON$OBJECT_TYPE`:: PSQL object type
`MON$PACKAGE_NAME`:: Package name of the PSQL object
`MON$STAT_ID`:: Runtime statistics ID (references `MON$*_STATS` tables)

New columns in the tables: 

In `MON$ATTACHMENTS`:

[horizontal]
`MON$SESSION_TIMEZONE`:: Actual timezone of the session

In `MON$STATEMENTS`:

[horizontal]
`MON$COMPILED_STATEMENT_ID`:: Compiled statement ID (references `MON$COMPILED_STATEMENTS`)

In `MON$CALL_STACK`:

[horizontal]
`MON$COMPILED_STATEMENT_ID`:: Compiled statement ID (references `MON$COMPILED_STATEMENTS`)

In `SEC$GLOBAL_AUTH_MAPPING`:

[horizontal]
`SEC$DESCRIPTION`:: Textual description

[[rnfb50-util-isql]]
== _isql_

[[rnfb50-utils-show-system-proc]]
=== Unify display of system procedures and functions & packages with other system objects
Alex Peshkov

Tracker tickets: https://github.com/FirebirdSQL/firebird/issues/7411[#7411], https://github.com/FirebirdSQL/firebird/issues/7475[#7475]

The `SHOW SYSTEM` command of _isql_ now lists system packages and their procedures and functions.

[[rnfb50-utils-exec-path-blr]]
=== Display statement BLR
Adriano dos Santos Fernandes

Tracker ticket: https://github.com/FirebirdSQL/firebird/issues/6910[#6910]

The `SET EXEC_PATH_DISPLAY` command is a debug command to show the BLR (compiled form) of the statement.
When a statement is executed, it retrieves the compiled execution path of a DML statement formatted as BLR text.

[listing]
----
SET EXEC_PATH_DISPLAY {BLR | OFF};
----

[WARNING]
====
This feature is intimately tied to engine internals.
Its usage is discouraged if you do not understand very well how these internals are subject to change between versions.
====

=== Replication information added to `SHOW DATABASE` output
Dmitry Yemanov

Tracker tickets: https://github.com/FirebirdSQL/firebird/issues/7001[#7001], https://github.com/FirebirdSQL/firebird/issues/7425[#7425]

The `SHOW DATABASE` command now reports the "`Replica mode`" and "`Publication`" state.

[[rnfb50-utils-gbak]]
== _gbak_

[[rnfb50-utils-gbak-parallel]]
=== Parallel backup/restore
Vlad Khorsun

Tracker tickets: https://github.com/FirebirdSQL/firebird/issues/1783[#1783],
https://github.com/FirebirdSQL/firebird/issues/3374[#3374]

A new command-line switch has been added to _gbak_: `-PAR[ALLEL] <N>`.

It defines how many parallel workers will be used for the requested task.

Usage examples:

[source]
----
gbak -b -par 4 -user <username> -pass <password> <dbname> <backupname>
gbak -r -par 4 -user <username> -pass <password> <backupname> <dbname>
----

[[rnfb50-utils-gfix]]
== _gfix_

[[rnfb50-utils-gfix-parallel]]
=== Parallel sweep and ICU dependencies rebuild
Vlad Khorsun

Tracker tickets: https://github.com/FirebirdSQL/firebird/issues/7447[#7447], https://github.com/FirebirdSQL/firebird/issues/7550[#7550]

A new command-line switch has been added to _gfix_: `-PAR[ALLEL] <N>`.

It defines how many parallel workers will be used for the requested task.

Usage example:

[source]
----
gfix -sweep -par 4 -user <username> -pass <password> <dbname>
gfix -icu -par 4 -user <username> -pass <password> <dbname>
----

The `-parallel` option is only valid in combination with the `-sweep` and `-icu` tasks.

[[rnfb50-utils-gfix-upgrade]]
=== ODS upgrade
Dmitry Yemanov

Tracker tickets: https://github.com/FirebirdSQL/firebird/pull/7397[#7397]

A new command-line switch has been added to _gfix_: `-UP[GRADE]`.

It allows to upgrade ODS of the database to the latest supported minor version (within the supported major version).

Usage example(s):

[source]
----
gfix -upgrade <dbname> -user <username> -pass <password>
----
