/*
 * This file is generated by jOOQ.
*/
package ru.ibase.fbjavaex.exampledb;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Configuration;

import ru.ibase.fbjavaex.exampledb.routines.SpAddInvoice;
import ru.ibase.fbjavaex.exampledb.routines.SpAddInvoiceLine;
import ru.ibase.fbjavaex.exampledb.routines.SpDeleteInvoice;
import ru.ibase.fbjavaex.exampledb.routines.SpDeleteInvoiceLine;
import ru.ibase.fbjavaex.exampledb.routines.SpEditInvoice;
import ru.ibase.fbjavaex.exampledb.routines.SpEditInvoiceLine;
import ru.ibase.fbjavaex.exampledb.routines.SpPayForInovice;


/**
 * Convenience access to all stored procedures and functions in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>SP_ADD_INVOICE</code>
     */
    public static void spAddInvoice(Configuration configuration, Integer invoiceId, Integer customerId, Timestamp invoiceDate) {
        SpAddInvoice p = new SpAddInvoice();
        p.setInvoiceId(invoiceId);
        p.setCustomerId(customerId);
        p.setInvoiceDate(invoiceDate);

        p.execute(configuration);
    }

    /**
     * Call <code>SP_ADD_INVOICE_LINE</code>
     */
    public static void spAddInvoiceLine(Configuration configuration, Integer invoiceId, Integer productId, Integer quantity) {
        SpAddInvoiceLine p = new SpAddInvoiceLine();
        p.setInvoiceId(invoiceId);
        p.setProductId(productId);
        p.setQuantity(quantity);

        p.execute(configuration);
    }

    /**
     * Call <code>SP_DELETE_INVOICE</code>
     */
    public static void spDeleteInvoice(Configuration configuration, Integer invoiceId) {
        SpDeleteInvoice p = new SpDeleteInvoice();
        p.setInvoiceId(invoiceId);

        p.execute(configuration);
    }

    /**
     * Call <code>SP_DELETE_INVOICE_LINE</code>
     */
    public static void spDeleteInvoiceLine(Configuration configuration, Integer invoiceLineId) {
        SpDeleteInvoiceLine p = new SpDeleteInvoiceLine();
        p.setInvoiceLineId(invoiceLineId);

        p.execute(configuration);
    }

    /**
     * Call <code>SP_EDIT_INVOICE</code>
     */
    public static void spEditInvoice(Configuration configuration, Integer invoiceId, Integer customerId, Timestamp invoiceDate) {
        SpEditInvoice p = new SpEditInvoice();
        p.setInvoiceId(invoiceId);
        p.setCustomerId(customerId);
        p.setInvoiceDate(invoiceDate);

        p.execute(configuration);
    }

    /**
     * Call <code>SP_EDIT_INVOICE_LINE</code>
     */
    public static void spEditInvoiceLine(Configuration configuration, Integer invoiceLineId, Integer quantity) {
        SpEditInvoiceLine p = new SpEditInvoiceLine();
        p.setInvoiceLineId(invoiceLineId);
        p.setQuantity(quantity);

        p.execute(configuration);
    }

    /**
     * Call <code>SP_PAY_FOR_INOVICE</code>
     */
    public static void spPayForInovice(Configuration configuration, Integer invoiceId) {
        SpPayForInovice p = new SpPayForInovice();
        p.setInvoiceId(invoiceId);

        p.execute(configuration);
    }
}
