/*
 * This file is generated by jOOQ.
*/
package ru.ibase.fbjavaex.exampledb;


import javax.annotation.Generated;

import ru.ibase.fbjavaex.exampledb.tables.Customer;
import ru.ibase.fbjavaex.exampledb.tables.Invoice;
import ru.ibase.fbjavaex.exampledb.tables.InvoiceLine;
import ru.ibase.fbjavaex.exampledb.tables.Product;
import ru.ibase.fbjavaex.exampledb.tables.Webrole;
import ru.ibase.fbjavaex.exampledb.tables.Webuser;
import ru.ibase.fbjavaex.exampledb.tables.Webuserinrole;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>CUSTOMER</code>.
     */
    public static final Customer CUSTOMER = ru.ibase.fbjavaex.exampledb.tables.Customer.CUSTOMER;

    /**
     * The table <code>INVOICE</code>.
     */
    public static final Invoice INVOICE = ru.ibase.fbjavaex.exampledb.tables.Invoice.INVOICE;

    /**
     * The table <code>INVOICE_LINE</code>.
     */
    public static final InvoiceLine INVOICE_LINE = ru.ibase.fbjavaex.exampledb.tables.InvoiceLine.INVOICE_LINE;

    /**
     * The table <code>PRODUCT</code>.
     */
    public static final Product PRODUCT = ru.ibase.fbjavaex.exampledb.tables.Product.PRODUCT;

    /**
     * The table <code>WEBROLE</code>.
     */
    public static final Webrole WEBROLE = ru.ibase.fbjavaex.exampledb.tables.Webrole.WEBROLE;

    /**
     * The table <code>WEBUSER</code>.
     */
    public static final Webuser WEBUSER = ru.ibase.fbjavaex.exampledb.tables.Webuser.WEBUSER;

    /**
     * The table <code>WEBUSERINROLE</code>.
     */
    public static final Webuserinrole WEBUSERINROLE = ru.ibase.fbjavaex.exampledb.tables.Webuserinrole.WEBUSERINROLE;
}
