[[fblangref40-intro]]
= About the Firebird 4.0 Language Reference

This Language Reference decribes the SQL language supported by Firebird 4.0.

This Firebird 3.0 Language Reference is the second comprehensive manual to cover all aspects of the query language used by developers to communicate, through their applications, with the Firebird relational database management system.

[[fblangref40-intro-subject]]
== Subject

The subject of this volume is wholly Firebird's implementation of the SQL relational database language.
Firebird conforms closely with international standards for SQL, from data type support, data storage structures, referential integrity mechanisms, to data manipulation capabilities and access privileges.
Firebird also implements a robust procedural language -- procedural SQL (PSQL) -- for stored procedures, triggers and dynamically-executable code blocks.
These are the areas addressed in this volume.

This document does not cover configuration of Firebird, Firebird command-line tools, nor its programming APIs.

[[fblangref40-intro-authors]]
== Authorship

For the Firebird 4.0 version, the _Firebird 3.0 Language Reference_ was taken as the base, and Firebird 4.0 information was added based on the Firebird 4.0 release notes, and feature documentation.

[[fblangref40-intro-contributors]]
=== Contributors

[float]
==== Direct Content

* Dmitry Filippov (writer)
* Alexander Karpeykin (writer)
* Alexey Kovyazin (writer, editor)
* Dmitry Kuzmenko (writer, editor)
* Denis Simonov (writer, editor)
* Paul Vinkenoog (writer, designer)
* Dmitry Yemanov (writer)
* Mark Rotteveel (writer)

[float]
==== Resource Content

* Adriano dos Santos Fernandes
* Alexander Peshkov
* Vladyslav Khorsun
* Claudio Valderrama
* Helen Borrie
* and others

[[fblangref40-acknowledgements]]
== Acknowledgments

[float]
[[sponsors-donors]]
=== Sponsors and Other Donors

See also the Firebird 2.5 Language Reference for its donors.

[float]
[[sponsors01-native]]
==== Sponsors of the Russian Language Reference Manual

[none]
* https://www.moex.com[Moscow Exchange] (Russia)
+
_Moscow Exchange is the largest exchange holding in Russia and Eastern Europe, founded on December 19, 2011, through the consolidation of the MICEX (founded in 1992) and RTS (founded in 1995) exchange groups.
Moscow Exchange ranks among the world's top 20 exchanges by trading in bonds and by the total capitalization of shares traded, as well as among the 10 largest exchange platforms for trading derivatives._

* https://www.ib-aid.com[IBSurgeon] (https://ibase.ru[ibase.ru]) (Russia)
+
_Technical support and developer of administrator tools for the Firebird DBMS._

[[fblangref40-contributing]]
== Contributing

There are several ways you can contribute to the documentation of Firebird, or Firebird in general:

* Participate on the mailing lists (see https://www.firebirdsql.org/en/mailing-lists/)
* Report bugs or submit pull requests on GitHub (https://github.com/FirebirdSQL/)
* Become a developer (for documentation contact us on firebird-docs, for Firebird in
general, use the Firebird-devel mailing list)
* Donate to the Firebird Foundation (see https://www.firebirdsql.org/en/donate/)
* Become a paying member or sponsor of the Firebird Foundation (see
https://www.firebirdsql.org/en/firebird-foundation/)
