[[fblangref30-aggfuncs]]
= Aggregate Functions

Aggregate functions operate on groups of records, rather than on individual records or variables.
They are often used in combination with a `GROUP BY` clause.

The aggregate functions can also be used as window functions with the `OVER ()` clause.
See <<fblangref30-windowfuncs,Window (Analytical) Functions>> for more information.

[[fblangref30-aggfuncs-general]]
== General-purpose Aggregate Functions

[[fblangref30-aggfuncs-avg]]
=== `AVG()`

.Available in
DSQL, ESQL, PSQL

.Result type
A numeric data type, the same as the data type of the argument.

.Syntax
[listing]
----
AVG ([ALL | DISTINCT] <expr>)
----

[[fblangref30-aggfuncs-tbl-avg]]
.`AVG` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF that returns a numeric data type.
Aggregate functions are not allowed as expressions
|===

`AVG` returns the average argument value in the group.
`NULL` is ignored.

* Parameter `ALL` (the default) applies the aggregate function to all values.
* Parameter `DISTINCT` directs the `AVG` function to consider only one instance of each unique value, no matter how many times this value occurs.
* If the set of retrieved records is empty or contains only `NULL`, the result will be `NULL`.

[[fblangref30-aggfuncs-avg-exmpl]]
==== `AVG` Examples

[source]
----
SELECT
  dept_no,
  AVG(salary)
FROM employee
GROUP BY dept_no
----

.See also
<<fblangref30-dml-select,`SELECT`>>

[[fblangref30-aggfuncs-count]]
=== `COUNT()`

.Available in
DSQL, ESQL, PSQL

.Result type
`BIGINT`

.Syntax
[listing]
----
COUNT ([ALL | DISTINCT] <expr> | *)
----

[[fblangref30-aggfuncs-tbl-count]]
.`COUNT` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF that returns a numeric data type.
Aggregate functions are not allowed as expressions
|===

`COUNT` returns the number of non-null values in a group.

* `ALL` is the default: it simply counts all values in the set that are not `NULL`.
* If `DISTINCT` is specified, duplicates are excluded from the counted set.
* If `COUNT ({asterisk})` is specified instead of the expression _expr_, all rows will be counted.
`COUNT ({asterisk})` --
** does not accept parameters
** cannot be used with the keyword `DISTINCT`
** does not take an _expr_ argument, since its context is column-unspecific by definition
** counts each row separately and returns the number of rows in the specified table or group without omitting duplicate rows
** counts rows containing `NULL`
* If the result set is empty or contains only `NULL` in the specified column(s), the returned count is zero.

[[fblangref30-aggfuncs-count-exmpl]]
==== `COUNT` Examples

[source]
----
SELECT
  dept_no,
  COUNT(*) AS cnt,
  COUNT(DISTINCT name) AS cnt_name
FROM employee
GROUP BY dept_no
----

.See also
<<fblangref30-dml-select,`SELECT`>>.

[[fblangref30-aggfuncs-list]]
=== `LIST()`

.Available in
DSQL, PSQL

.Result type
`BLOB`

.Syntax
[listing,subs=+quotes]
----
LIST ([ALL | DISTINCT] <expr> [, _separator_ ])
----

[[fblangref30-aggfuncs-tbl-list]]
.`LIST` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF that returns the string data type or a `BLOB`.
Fields of numeric and date/time types are converted to strings.
Aggregate functions are not allowed as expressions.

|separator
|Optional alternative separator, a string expression.
Comma is the default separator
|===

`LIST` returns a string consisting of the non-``NULL`` argument values in the group, separated either by a comma or by a user-supplied separator.
If there are no non-``NULL`` values (this includes the case where the group is empty), ``NULL`` is returned.

* `ALL` (the default) results in all non-``NULL`` values being listed.
With `DISTINCT`, duplicates are removed, except if _expr_ is a `BLOB`.
* In Firebird 2.5 and up, the optional _separator_ argument may be any string expression.
This makes it possible to specify e.g. `ascii_char(13)` as a separator.
(This improvement has also been backported to 2.1.4.)
* The _expr_ and _separator_ arguments support ``BLOB``s of any size and character set.
* Date/time and numeric arguments are implicitly converted to strings before concatenation.
* The result is a text `BLOB`, except when _expr_ is a `BLOB` of another subtype.
* The ordering of the list values is undefined -- the order in which the strings are concatenated is determined by read order from the source set which, in tables, is not generally defined.
If ordering is important, the source data can be pre-sorted using a derived table or similar.

[[fblangref30-aggfuncs-list-exmpl]]
==== `LIST` Examples

. Retrieving the list, order undefined:
+
[source]
----
SELECT LIST (display_name, '; ') FROM GR_WORK;
----
. Retrieving the list in alphabetical order, using a derived table:
+
[source]
----
SELECT LIST (display_name, '; ')
FROM (SELECT display_name
      FROM GR_WORK
      ORDER BY display_name);
----

.See also
<<fblangref30-dml-select,`SELECT`>>

[[fblangref30-aggfuncs-max]]
=== `MAX()`

.Available in
DSQL, ESQL, PSQL

.Result type
Returns a result of the same data type the input expression.

.Syntax
[listing]
----
MAX ([ALL | DISTINCT] <expr>)
----

[[fblangref30-aggfuncs-tbl-max]]
.`MAX` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

`MAX` returns the maximum non-``NULL`` element in the result set.

* If the group is empty or contains only ``NULL``s, the result is `NULL`.
* If the input argument is a string, the function will return the value that will be sorted last if `COLLATE` is used.
* This function fully supports text ``BLOB``s of any size and character set.

[NOTE]
====
The `DISTINCT` parameter makes no sense if used with `MAX()` and is implemented only for compliance with the standard.
====

[[fblangref30-aggfuncs-max-exmpl]]
==== `MAX` Examples

[source]
----
SELECT
  dept_no,
  MAX(salary)
FROM employee
GROUP BY dept_no
----

.See also
<<fblangref30-aggfuncs-min>>, <<fblangref30-dml-select,`SELECT`>>

[[fblangref30-aggfuncs-min]]
=== `MIN()`

.Available in
DSQL, ESQL, PSQL

.Result type
Returns a result of the same data type the input expression.

.Syntax
[listing]
----
MIN ([ALL | DISTINCT] <expr>)
----

[[fblangref30-aggfuncs-tbl-min]]
.`MIN` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

`MIN` returns the minimum non-``NULL`` element in the result set.

* If the group is empty or contains only ``NULL``s, the result is `NULL`.
* If the input argument is a string, the function will return the value that will be sorted first if `COLLATE` is used.
* This function fully supports text ``BLOB``s of any size and character set.

[NOTE]
====
The `DISTINCT` parameter makes no sense if used with `MIN()` and is implemented only for compliance with the standard.
====

[[fblangref30-aggfuncs-min-exmpl]]
==== `MIN` Examples

[source]
----
SELECT
  dept_no,
  MIN(salary)
FROM employee
GROUP BY dept_no
----

.See also
<<fblangref30-aggfuncs-max>>, <<fblangref30-dml-select,`SELECT`>>

[[fblangref30-aggfuncs-sum]]
=== `SUM()`

.Available in
DSQL, ESQL, PSQL

.Result type
Returns a result of the same numeric data type as the input expression.

.Syntax
[listing]
----
SUM ([ALL | DISTINCT] <expr>)
----

[[fblangref30-aggfuncs-tbl-sum]]
.`SUM` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Numeric expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

`SUM` calculates and returns the sum of non-null values in the group.

* If the group is empty or contains only ``NULL``s, the result is `NULL`.
* ALL is the default option -- all values in the set that are not `NULL` are processed.
If `DISTINCT` is specified, duplicates are removed from the set and the `SUM` evaluation is done afterwards.

[[fblangref30-aggfuncs-sum-exmpl]]
==== `SUM` Examples

[source]
----
SELECT
  dept_no,
  SUM (salary),
FROM employee
GROUP BY dept_no
----

.See also
<<fblangref30-dml-select,`SELECT`>>

[[fblangref30-aggfuncs-stats]]
== Statistical Aggregate Functions

[[fblangref30-aggfuncs-corr]]
=== `CORR`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
CORR ( <expr1>, <expr2> )
----

[[fblangref30-aggfuncs-tbl-corr]]
.`CORR` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr__N__
|Numeric expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The `CORR` function return the correlation coefficient for a pair of numerical expressions.

The function `CORR(<expr1>, <expr2>)` is equivalent to

[listing]
----
COVAR_POP(<expr1>, <expr2>) / (STDDEV_POP(<expr2>) * STDDEV_POP(<expr1>))
----

This is also known as the Pearson correlation coefficient.

In a statistical sense, correlation is the degree of to which a pair of variables are linearly related.
A linear relation between variables means that the value of one variable can to a certain extent predict the value of the other.
The correlation coefficient represents the degree of correlation as a number ranging from -1 (high inverse correlation) to 1 (high correlation).
A value of 0 corresponds to no correlation.

If the group or window is empty, or contains only `NULL` values, the result will be `NULL`.

[[fblangref30-aggfuncs-corr-exmpl]]
==== `CORR` Examples

[source]
----
select
  corr(alength, aheight) AS c_corr
from measure
----

.See also
<<fblangref30-aggfuncs-covar-pop>>, <<fblangref30-aggfuncs-stddev-pop>>

[[fblangref30-aggfuncs-covar-pop]]
=== `COVAR_POP`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
COVAR_POP ( <expr1>, <expr2> )
----

[[fblangref30-aggfuncs-tbl-covar-pop]]
.`COVAR_POP` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr__N__
|Numeric expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `COVAR_POP` returns the population covariance for a pair of numerical expressions.

The function `COVAR_POP(<expr1>, <expr2>)` is equivalent to

[listing]
----
(SUM(<expr1> * <expr2>) - SUM(<expr1>) * SUM(<expr2>) / COUNT(*)) / COUNT(*)
----

If the group or window is empty, or contains only `NULL` values, the result will be `NULL`.

[[fblangref30-aggfuncs-covar-pop-exmpl]]
==== `COVAR_POP` Examples

[source]
----
select
  covar_pop(alength, aheight) AS c_covar_pop
from measure
----

.See also
<<fblangref30-aggfuncs-covar-samp>>, <<fblangref30-aggfuncs-sum>>, <<fblangref30-aggfuncs-count>>

[[fblangref30-aggfuncs-covar-samp]]
=== `COVAR_SAMP`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
COVAR_SAMP ( <expr1>, <expr2> )
----

[[fblangref30-aggfuncs-tbl-covar-samp]]
.`COVAR_SAMP` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr__N__
|Numeric expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `COVAR_SAMP` returns the sample covariance for a pair of numerical expressions.

The function `COVAR_SAMP(<expr1>, <expr2>)` is equivalent to

[listing]
----
(SUM(<expr1> * <expr2>) - SUM(<expr1>) * SUM(<expr2>) / COUNT(*)) / (COUNT(*) - 1)
----

If the group or window is empty, contains only 1 row, or contains only `NULL` values, the result will be `NULL`.

[[fblangref30-aggfuncs-covar-samp-exmpl]]
==== `COVAR_SAMP` Examples

[source]
----
select
  covar_samp(alength, aheight) AS c_covar_samp
from measure
----

.See also
<<fblangref30-aggfuncs-covar-pop>>, <<fblangref30-aggfuncs-sum>>, <<fblangref30-aggfuncs-count>>

[[fblangref30-aggfuncs-stddev-pop]]
=== `STDDEV_POP`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION` or `NUMERIC` depending on the type of _expr_

.Syntax
[listing]
----
STDDEV_POP ( <expr> )
----

[[fblangref30-aggfuncs-tbl-stddev-pop]]
.`STDDEV_POP` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Numeric expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `STDDEV_POP` returns the population standard deviation for a group or window.
`NULL` values are skipped.

The function `STDDEV_POP(<expr>)` is equivalent to

[listing]
----
SQRT(VAR_POP(<expr>))
----

If the group or window is empty, or contains only `NULL` values, the result will be `NULL`.

[[fblangref30-aggfuncs-stddev-pop-exmpl]]
==== `STDDEV_POP` Examples

[source]
----
select
  dept_no
  stddev_pop(salary)
from employee
group by dept_no
----

.See also
<<fblangref30-aggfuncs-stddev-samp>>, <<fblangref30-aggfuncs-var-pop>>, <<fblangref30-scalarfuncs-sqrt,`SQRT`>>

[[fblangref30-aggfuncs-stddev-samp]]
=== `STDDEV_SAMP`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION` or `NUMERIC` depending on the type of _expr_

.Syntax
[listing]
----
STDDEV_POP ( <expr> )
----

[[fblangref30-aggfuncs-tbl-stddev-samp]]
.`STDDEV_SAMP` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Numeric expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `STDDEV_SAMP` returns the sample standard deviation for a group or window.
`NULL` values are skipped.

The function `STDDEV_SAMP(<expr>)` is equivalent to

[listing]
----
SQRT(VAR_SAMP(<expr>))
----

If the group or window is empty, contains only 1 row, or contains only `NULL` values, the result will be `NULL`.

[[fblangref30-aggfuncs-stddev-samp-exmpl]]
==== `STDDEV_SAMP` Examples

[source]
----
select
  dept_no
  stddev_samp(salary)
from employee
group by dept_no
----

.See also
<<fblangref30-aggfuncs-stddev-pop>>, <<fblangref30-aggfuncs-var-samp>>, <<fblangref30-scalarfuncs-sqrt,`SQRT`>>

[[fblangref30-aggfuncs-var-pop]]
=== `VAR_POP`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION` or `NUMERIC` depending on the type of _expr_

.Syntax
[listing]
----
VAR_POP ( <expr> )
----

[[fblangref30-aggfuncs-tbl-var-pop]]
.`VAR_POP` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Numeric expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `VAR_POP` returns the population variance for a group or window.
`NULL` values are skipped.

The function `VAR_POP(<expr>)` is equivalent to

[listing]
----
(SUM(<expr> * <expr>) - SUM (<expr>) * SUM (<expr>) / COUNT(<expr>))
  / COUNT (<expr>)
----

If the group or window is empty, or contains only `NULL` values, the result will be `NULL`.

[[fblangref30-aggfuncs-var-pop-exmpl]]
==== `VAR_POP` Examples

[source]
----
select
  dept_no
  var_pop(salary)
from employee
group by dept_no
----

.See also
<<fblangref30-aggfuncs-var-samp>>, <<fblangref30-aggfuncs-sum>>, <<fblangref30-aggfuncs-count>>

[[fblangref30-aggfuncs-var-samp]]
=== `VAR_SAMP`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION` or `NUMERIC` depending on the type of _expr_

.Syntax
[listing]
----
VAR_SAMP ( <expr> )
----

[[fblangref30-aggfuncs-tbl-var-samp]]
.`VAR_SAMP` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr
|Numeric expression.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `VAR_POP` returns the sample variance for a group or window.
`NULL` values are skipped.

The function `VAR_SAMP(<expr>)` is equivalent to

[listing]
----
(SUM(<expr> * <expr>) - SUM(<expr>) * SUM (<expr>) / COUNT (<expr>))
  / (COUNT(<expr>) - 1)
----

If the group or window is empty, contains only 1 row, or contains only `NULL` values, the result will be `NULL`.

[[fblangref30-aggfuncs-var-samp-exmpl]]
==== `VAR_SAMP` Examples

[source]
----
select
  dept_no
  var_samp(salary)
from employee
group by dept_no
----

.See also
<<fblangref30-aggfuncs-var-pop>>, <<fblangref30-aggfuncs-sum>>, <<fblangref30-aggfuncs-count>>

[[fblangref30-aggfuncs-regr]]
== Linear Regression Aggregate Functions

Linear regression functions are useful for trend line continuation.
The trend or regression line is usually a pattern followed by a set of values.
Linear regression is useful to predict future values.
To continue the regression line, you need to know the slope and the point of intersection with the y-axis.
As set of linear functions can be used for calculating these values.

In the function syntax, _y_ is interpreted as an _x_-dependent variable.

The linear regression aggregate functions take a pair of arguments, the dependent variable expression (_y_) and the independent variable expression (_x_), which are both numeric value expressions.
Any row in which either argument evaluates to `NULL` is removed from the rows that qualify.
If there are no rows that qualify, then the result of `REGR_COUNT` is `0` (zero), and the other linear regression aggregate functions result in `NULL`.

[[fblangref30-aggfuncs-regr-avgx]]
=== `REGR_AVGX`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_AVGX ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-avgx]]
.`REGR_AVGX` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `REGR_AVGX` calculates the average of the independent variable (_x_) of the regression line.

The function `REGR_AVGX(<y>, <x>)` is equivalent to

[listing]
----
SUM(<exprX>) / REGR_COUNT(<y>, <x>)

<exprX> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN <x> END
----

.See also
<<fblangref30-aggfuncs-regr-avgy>>, <<fblangref30-aggfuncs-regr-count>>, <<fblangref30-aggfuncs-sum>>

[[fblangref30-aggfuncs-regr-avgy]]
=== `REGR_AVGY`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_AVGY ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-avgy]]
.`REGR_AVGY` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `REGR_AVGY` calculates the average of the dependent variable (_y_) of the regression line.

The function `REGR_AVGY(<y>, <x>)` is equivalent to

[listing]
----
SUM(<exprY>) / REGR_COUNT(<y>, <x>)

<exprY> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN <y> END
----

.See also
<<fblangref30-aggfuncs-regr-avgx>>, <<fblangref30-aggfuncs-regr-count>>, <<fblangref30-aggfuncs-sum>>

[[fblangref30-aggfuncs-regr-count]]
=== `REGR_COUNT`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_COUNT ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-count]]
.`REGR_COUNT` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `REGR_COUNT` counts the number of non-empty pairs of the regression line.

The function `REGR_COUNT(<y>, <x>)` is equivalent to

[listing]
----
SUM(<exprXY>) / REGR_COUNT(<y>, <x>)

<exprXY> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN 1 END
----

.See also
<<fblangref30-aggfuncs-sum>>

[[fblangref30-aggfuncs-regr-intercept]]
=== `REGR_INTERCEPT`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_INTERCEPT ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-intercept]]
.`REGR_INTERCEPT` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `REGR_INTERCEPT` calculates the point of intersection of the regression line with the y-axis.

The function `REGR_INTERCEPT(<y>, <x>)` is equivalent to

[listing]
----
REGR_AVGY(<y>, <x>) - REGR_SLOPE(<y>, <x>) * REGR_AVGX(<y>, <x>)
----

[[fblangref30-aggfuncs-regr-intercept-exmpl]]
==== `REGR_INTERCEPT` Examples

Forecasting sales volume

[source]
----
with recursive years (byyear) as (
  select 1991
  from rdb$database
  union all
  select byyear + 1
  from years
  where byyear < 2020
),
s as (
  select
    extract(year from order_date) as byyear,
    sum(total_value) as total_value
  from sales
  group by 1
),
regr as (
  select
    regr_intercept(total_value, byyear) as intercept,
    regr_slope(total_value, byyear) as slope
  from s
)
select
  years.byyear as byyear,
  intercept + (slope * years.byyear) as total_value
from years
cross join regr
----

[listing]
----
BYYEAR TOTAL_VALUE
------ ------------
  1991    118377.35
  1992    414557.62
  1993    710737.89
  1994   1006918.16
  1995   1303098.43
  1996   1599278.69
  1997   1895458.96
  1998   2191639.23
  1999   2487819.50
  2000   2783999.77
...
----

.See also
<<fblangref30-aggfuncs-regr-avgx>>, <<fblangref30-aggfuncs-regr-avgy>>, <<fblangref30-aggfuncs-regr-slope>>

[[fblangref30-aggfuncs-regr-r2]]
=== `REGR_R2`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_R2 ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-r2]]
.`REGR_R2` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The REGR_R2 function calculates the coefficient of determination, or R-squared, of the regression line.

The function `REGR_R2(<y>, <x>)` is equivalent to

[listing]
----
POWER(CORR(<y>, <x>), 2)
----

.See also
<<fblangref30-aggfuncs-corr>>, <<fblangref30-scalarfuncs-power,`POWER`>>

[[fblangref30-aggfuncs-regr-slope]]
=== `REGR_SLOPE`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_SLOPE ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-slope]]
.`REGR_SLOPE` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `REGR_SLOPE` calculates the slope of the regression line.

The function `REGR_SLOPE(<y>, <x>)` is equivalent to

[listing]
----
COVAR_POP(<y>, <x>) / VAR_POP(<exprX>)

<exprX> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN <x> END
----

.See also
<<fblangref30-aggfuncs-covar-pop>>, <<fblangref30-aggfuncs-var-pop>>

[[fblangref30-aggfuncs-regr-sxx]]
=== `REGR_SXX`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_SXX ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-sxx]]
.`REGR_SXX` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `REGR_SXX` calculates the sum of squares of the independent expression variable (_x_).

The function `REGR_SXX(<y>, <x>)` is equivalent to

[listing]
----
REGR_COUNT(<y>, <x>) * VAR_POP(<exprX>)

<exprX> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN <x> END
----

.See also
<<fblangref30-aggfuncs-regr-count>>, <<fblangref30-aggfuncs-var-pop>>

[[fblangref30-aggfuncs-regr-sxy]]
=== `REGR_SXY`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_SXY ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-sxy]]
.`REGR_SXY` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `REGR_SXY` calculates the sum of products of independent variable expression (_x_) times dependent variable expression (_y_).

The function `REGR_SXY(<y>, <x>)` is equivalent to

[listing]
----
REGR_COUNT(<y>, <x>) * COVAR_POP(<y>, <x>)
----

.See also
<<fblangref30-aggfuncs-covar-pop>>, <<fblangref30-aggfuncs-regr-count>>

[[fblangref30-aggfuncs-regr-syy]]
=== `REGR_SYY`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
REGR_SYY ( <y>, <x> )
----

[[fblangref30-aggfuncs-tbl-regr-syy]]
.`REGR_SYY` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|Dependent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.

|x
|Independent variable of the regression line.
It may contain a table column, a constant, a variable, an expression, a non-aggregate function or a UDF.
Aggregate functions are not allowed as expressions.
|===

The function `REGR_SYY` calculates the sum of squares of the dependent variable (_y_).

The function `REGR_SYY(<y>, <x>)` is equivalent to

[listing]
----
REGR_COUNT(<y>, <x>) * VAR_POP(<exprY>)

<exprY> :==
  CASE WHEN <x> IS NOT NULL AND <y> IS NOT NULL THEN <y> END
----

.See also
<<fblangref30-aggfuncs-regr-count>>, <<fblangref30-aggfuncs-var-pop>>
