[[fblangref40-contextvars]]
= Context Variables

[[fblangref40-contextvars-current-connection]]
== `CURRENT_CONNECTION`

.Available in
DSQL, PSQL

.Type
`BIGINT`

.Syntax
[listing]
----
CURRENT_CONNECTION
----

`CURRENT_CONNECTION` contains the unique identifier of the current connection.

Its value is derived from a counter on the database header page, which is incremented for each new connection.
When a database is restored, this counter is reset to zero.

.Examples
[source]
----
select current_connection from rdb$database

execute procedure P_Login(current_connection)
----

[[fblangref40-contextvars-current-date]]
== `CURRENT_DATE`

.Available in
DSQL, PSQL, ESQL

.Type
`DATE`

.Syntax
[listing]
----
CURRENT_DATE
----

`CURRENT_DATE` returns the current server date.

[NOTE]
====
Within a PSQL module (procedure, trigger or executable block), the value of `CURRENT_DATE` will remain constant every time it is read.
If multiple modules call or trigger each other, the value will remain constant throughout the duration of the outermost module.
If you need a progressing value in PSQL (e.g. to measure time intervals), use <<fblangref40-contextvars-today>>.
====

.Examples
[source]
----
select current_date from rdb$database
-- returns e.g. 2011-10-03
----

[[fblangref40-contextvars-current-role]]
== `CURRENT_ROLE`

.Available in
DSQL, PSQL

.Type
`VARCHAR(63)`

.Syntax
[listing]
----
CURRENT_ROLE
----

`CURRENT_ROLE` is a context variable containing the explicitly specified role of the currently connected user.
If there is no explicitly specified role, `CURRENT_ROLE` is `'NONE'`.

`CURRENT_ROLE` always represents a valid role or `'NONE'`.
If a user connects with a non-existing role, the engine silently resets it to `'NONE'` without returning an error.

[NOTE]
====
Roles that are active by default and not explicitly specified on connect or using `SET ROLE` are not returned by `CURRENT_ROLE`.
Use <<fblangref40-scalarfuncs-roleinuse,`RDB$ROLE_IN_USE`>> to check for all active roles.
====

.Example
[source]
----
if (current_role <> 'MANAGER')
  then exception only_managers_may_delete;
else
  delete from Customers where custno = :custno;
----

.See also
<<fblangref40-scalarfuncs-roleinuse,`RDB$ROLE_IN_USE`>>

[[fblangref40-contextvars-current-time]]
== `CURRENT_TIME`

.Available in
DSQL, PSQL, ESQL

.Type
`TIME WITH TIME ZONE`

[CAUTION]
====
Data type changed in Firebird 4.0 from `TIME WITHOUT TIME ZONE` to `TIME WITH TIME ZONE`.
Use <<fblangref40-contextvars-localtime>> to obtain `TIME WITHOUT TIME ZONE`.
====

.Syntax
[listing]
----
CURRENT_TIME [ (<precision>) ]

<precision> ::= 0 | 1 | 2 | 3
----

The optional _precision_ argument is not supported in ESQL.

[[fblangref40-funcs-tbl-current_time]]
.`CURRENT_TIME` Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|precision
|Precision.
The default value is 0.
Not supported in ESQL
|===

`CURRENT_TIME` returns the current server time in the session time zone.
The default is 0 decimals, i.e. seconds precision.

[NOTE]
====
* `CURRENT_TIME` has a default precision of 0 decimals, where `CURRENT_TIMESTAMP` has a default precision of 3 decimals.
As a result, `CURRENT_TIMESTAMP` is not the exact sum of `CURRENT_DATE` and `CURRENT_TIME`, unless you explicitly specify a precision (i.e. `CURRENT_TIME(3)` or `CURRENT_TIMESTAMP(0)`).
* Within a PSQL module (procedure, trigger or executable block), the value of `CURRENT_TIME` will remain constant every time it is read.
If multiple modules call or trigger each other, the value will remain constant throughout the duration of the outermost module.
If you need a progressing value in PSQL (e.g. to measure time intervals), use <<fblangref40-contextvars-now>>.
====

.`CURRENT_TIME` and Firebird 4.0 Time Zone Support
[WARNING]
====
Firebird 4.0 added support for time zones.
As part of this support, an incompatibility with the `CURRENT_TIME` expression was introduced compared to previous version.

In Firebird 4.0, `CURRENT_TIME` returns the `TIME WITH TIME ZONE` type.
In order for your queries to be compatible with database code of Firebird 4.0 and higher, Firebird 3.0.4 and Firebird 2.5.9 introduced the <<fblangref40-contextvars-localtime>> expression.
In Firebird 3.0.4 and Firebird 2.5.9, `LOCALTIME` is a synonym for `CURRENT_TIME`.

In Firebird 4.0, `LOCALTIME` continues to work as it does in Firebird 3.0.4 and higher and Firebird 2.5.9 (returning `TIME [WITHOUT TIME ZONE]`), while `CURRENT_TIME` now returns a different data type, `TIME WITH TIME ZONE`.
====

.Examples
[source]
----
select current_time from rdb$database
-- returns e.g. 14:20:19.0000

select current_time(2) from rdb$database
-- returns e.g. 14:20:23.1200
----

.See also
<<fblangref40-contextvars-current-timestamp>>, <<fblangref40-contextvars-localtime>>, <<fblangref40-contextvars-localtimestamp>>

[[fblangref40-contextvars-current-timestamp]]
== `CURRENT_TIMESTAMP`

.Available in
DSQL, PSQL, ESQL

.Type
`TIMESTAMP WITH TIME ZONE`

[CAUTION]
====
Data type changed in Firebird 4.0 from `TIMESTAMP WITHOUT TIME ZONE` to `TIMESTAMP WITH TIME ZONE`.
Use <<fblangref40-contextvars-localtimestamp>> to obtain `TIMESTAMP WITHOUT TIME ZONE`.
====

.Syntax
[listing]
----
CURRENT_TIMESTAMP [ (<precision>) ]

<precision> ::= 0 | 1 | 2 | 3
----

The optional _precision_ argument is not supported in ESQL.

[[fblangref40-funcs-tbl-current_timestamp]]
.`CURRENT_TIMESTAMP` Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|precision
|Precision.
The default value is 3.
Not supported in ESQL
|===

`CURRENT_TIMESTAMP` returns the current server date and time in the session time zone.
The default is 3 decimals, i.e. milliseconds precision.

[NOTE]
====
* The default precision of `CURRENT_TIME` is 0 decimals, so `CURRENT_TIMESTAMP` is not the exact sum of `CURRENT_DATE` and `CURRENT_TIME`, unless you explicitly specify a precision (i.e. `CURRENT_TIME(3)` or `CURRENT_TIMESTAMP(0)`).
* Within a PSQL module (procedure, trigger or executable block), the value of `CURRENT_TIMESTAMP` will remain constant every time it is read.
If multiple modules call or trigger each other, the value will remain constant throughout the duration of the outermost module.
If you need a progressing value in PSQL (e.g. to measure time intervals), use <<fblangref40-contextvars-now>>.
====

.`CURRENT_TIMESTAMP` and Firebird 4.0 Time Zone Support
[WARNING]
====
Firebird 4.0 added support for time zones.
As part of this support, an incompatibility with the `CURRENT_TIMESTAMP` expression was introduced compared to previous versions.

In Firebird 4.0, `CURRENT_TIMESTAMP` returns the `TIMESTAMP WITH TIME ZONE` type.
In order for your queries to be compatible with database code of Firebird 4.0 and higher, Firebird 3.0.4 and Firebird 2.5.9 introduced the <<fblangref40-contextvars-localtimestamp>> expression.
In Firebird 3.0.4 and Firebird 2.5.9, `LOCALTIMESTAMP` is a synonym for `CURRENT_TIMESTAMP`.

In Firebird 4.0, `LOCALTIMESTAMP` continues to work as it does in Firebird 3.0.4 and higher and Firebird 2.5.9 (returning `TIMESTAMP [WITHOUT TIME ZONE]`), while `CURRENT_TIMESTAMP` now returns a different data type, `TIMESTAMP WITH TIME ZONE`.
====

.Examples
[source]
----
select current_timestamp from rdb$database
-- returns e.g. 2008-08-13 14:20:19.6170

select current_timestamp(2) from rdb$database
-- returns e.g. 2008-08-13 14:20:23.1200
----

.See also
<<fblangref40-contextvars-current-time>>, <<fblangref40-contextvars-localtime>>, <<fblangref40-contextvars-localtimestamp>>

[[fblangref40-contextvars-current-transaction]]
== `CURRENT_TRANSACTION`

.Available in
DSQL, PSQL

.Type
`BIGINT`

.Syntax
[listing]
----
CURRENT_TRANSACTION
----

`CURRENT_TRANSACTION` contains the unique identifier of the current transaction.

Its value is derived from a counter on the database header page, which is incremented for each new transaction.
When a database is restored, this counter is reset to zero.

.Examples
[source]
----
select current_transaction from rdb$database

New.Txn_ID = current_transaction;
----

[[fblangref40-contextvars-current-user]]
== `CURRENT_USER`

.Available in
DSQL, PSQL

.Type
`VARCHAR(63)`

.Syntax
[listing]
----
CURRENT_USER
----

`CURRENT_USER` is a context variable containing the name of the currently connected user.
It is fully equivalent to <<fblangref40-contextvars-user>>.

.Example
[source]
----
create trigger bi_customers for customers before insert as
begin
    New.added_by  = CURRENT_USER;
    New.purchases = 0;
end
----

[[fblangref40-contextvars-deleting]]
== `DELETING`

.Available in
PSQL

.Type
`BOOLEAN`

.Syntax
[listing]
----
DELETING
----

Available in triggers only, `DELETING` indicates if the trigger fired for a `DELETE` operation.
Intended for use in <<fblangref40-ddl-trgr-relntrigger-rowevent,multi-action triggers>>.

.Example
[source]
----
if (deleting) then
begin
  insert into Removed_Cars (id, make, model, removed)
    values (old.id, old.make, old.model, current_timestamp);
end
----

[[fblangref40-contextvars-gdscode]]
== `GDSCODE`

.Available in
PSQL

.Type
`INTEGER`

.Syntax
[listing]
----
GDSCODE
----

In a "```WHEN ... DO```" error handling block, the `GDSCODE` context variable contains the numerical representation of the current Firebird error code.
Prior to Firebird 2.0, `GDSCODE` was only set in `WHEN GDSCODE` handlers.
Now it may also be non-zero in `WHEN ANY`, `WHEN SQLCODE`, `WHEN SQLSTATE` and `WHEN EXCEPTION` blocks, provided that the condition raising the error corresponds with a Firebird error code.
Outside error handlers, `GDSCODE` is always 0.
Outside PSQL, it doesn't exist at all.

[NOTE]
====
After `WHEN GDSCODE`, you must use symbolic names like `grant_obj_notfound` etc.
But the `GDSCODE` context variable is an `INTEGER`.
If you want to compare it against a specific error, the numeric value must be used, e.g.
`335544551` for `grant_obj_notfound`.
====

.Example
[source]
----
when gdscode grant_obj_notfound, gdscode grant_fld_notfound,
   gdscode grant_nopriv, gdscode grant_nopriv_on_base
do
begin
  execute procedure log_grant_error(gdscode);
  exit;
end
----

[[fblangref40-contextvars-inserting]]
== `INSERTING`

.Available in
PSQL

.Type
`BOOLEAN`

.Syntax
[listing]
----
INSERTING
----

Available in triggers only, `INSERTING` indicates if the trigger fired because of an `INSERT` operation.
Intended for use in <<fblangref40-ddl-trgr-relntrigger-rowevent,multi-action triggers>>.

.Example
[source]
----
if (inserting or updating) then
begin
  if (new.serial_num is null) then
    new.serial_num = gen_id(gen_serials, 1);
end
----

[[fblangref40-contextvars-localtime]]
== `LOCALTIME`

.Available in
DSQL, PSQL, ESQL

.Type
`TIME WITHOUT TIME ZONE`

.Syntax
[listing]
----
LOCALTIME [ (<precision>) ]

<precision> ::= 0 | 1 | 2 | 3
----

The optional _precision_ argument is not supported in ESQL.

[[fblangref40-funcs-tbl-localtime]]
.`LOCALTIME` Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|precision
|Precision.
The default value is 0.
Not supported in ESQL
|===

`LOCALTIME` returns the current server time in the session time zone.
The default is 0 decimals, i.e. seconds precision.

[NOTE]
====
* `LOCALTIME` was introduced in Firebird 3.0.4 and Firebird 2.5.9 as an alias of `CURRENT_TIME`.
In Firebird 4.0, `CURRENT_TIME` returns a `TIME WITH TIME ZONE` instead of a `TIME [WITHOUT TIME ZONE]`, while `LOCALTIME` returns `TIME [WITHOUT TIME ZONE]`.
It is recommended to use `LOCALTIME` when you do not need time zone information.
* `LOCALTIME` has a default precision of 0 decimals, where `LOCALTIMESTAMP` has a default precision of 3 decimals.
As a result, `LOCALTIMESTAMP` is not the exact sum of `CURRENT_DATE` and `LOCALTIME`, unless you explicitly specify a precision (i.e. `LOCALTIME(3)` or `LOCALTIMESTAMP(0)`).
* Within a PSQL module (procedure, trigger or executable block), the value of `LOCALTIME` will remain constant every time it is read.
If multiple modules call or trigger each other, the value will remain constant throughout the duration of the outermost module.
If you need a progressing value in PSQL (e.g. to measure time intervals), use <<fblangref40-contextvars-now>>.
====

.Examples
[source]
----
select localtime from rdb$database
-- returns e.g. 14:20:19.0000

select localtime(2) from rdb$database
-- returns e.g. 14:20:23.1200
----

.See also
<<fblangref40-contextvars-current-time>>, <<fblangref40-contextvars-localtimestamp>>

[[fblangref40-contextvars-localtimestamp]]
== `LOCALTIMESTAMP`

.Available in
DSQL, PSQL, ESQL

.Type
`TIMESTAMP WITHOUT TIME ZONE`

.Syntax
[listing]
----
LOCALTIMESTAMP [ (<precision>) ]

<precision> ::= 0 | 1 | 2 | 3
----

The optional _precision_ argument is not supported in ESQL.

[[fblangref40-funcs-tbl-localtimestamp]]
.`LOCALTIMESTAMP` Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|precision
|Precision.
The default value is 3.
Not supported in ESQL
|===

`LOCALTIMESTAMP` returns the current server date and time in the session time zone.
The default is 3 decimals, i.e. milliseconds precision.

[NOTE]
====
* `LOCALTIMESTAMP` was introduced in Firebird 3.0.4 and Firebird 2.5.9 as a synonym of `CURRENT_TIMESTAMP`.
In Firebird 4.0, `CURRENT_TIMESTAMP` returns a `TIMESTAMP WITH TIME ZONE` instead of a `TIMESTAMP [WITHOUT TIME ZONE]`, while `LOCALTIMESTAMP` returns `TIMESTAMP [WITHOUT TIME ZONE]`.
It is recommended to use `LOCALTIMESTAMP` when you do not need time zone information.
* The default precision of `LOCALTIME` is 0 decimals, so `LOCALTIMESTAMP` is not the exact sum of `CURRENT_DATE` and `LOCALTIME`, unless you explicitly specify a precision (i.e. `LOCATIME(3)` or `LOCALTIMESTAMP(0)`).
* Within a PSQL module (procedure, trigger or executable block), the value of `LOCALTIMESTAMP` will remain constant every time it is read.
If multiple modules call or trigger each other, the value will remain constant throughout the duration of the outermost module.
If you need a progressing value in PSQL (e.g. to measure time intervals), use <<fblangref40-contextvars-now>>.
====

.Examples
[source]
----
select localtimestamp from rdb$database
-- returns e.g. 2008-08-13 14:20:19.6170

select localtimestamp(2) from rdb$database
-- returns e.g. 2008-08-13 14:20:23.1200
----

.See also
<<fblangref40-contextvars-current-timestamp>>, <<fblangref40-contextvars-localtime>>

[[fblangref40-contextvars-new]]
== `NEW`

.Available in
PSQL, triggers only

.Type
Record type

.Syntax
[listing,subs=+quotes]
----
NEW.__column_name__
----

[[fblangref40-funcs-tbl-new]]
.`NEW` Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|column_name
|Column name to access
|===

`NEW` contains the new version of a database record that has just been inserted or updated.
Starting with Firebird 2.0 it is read-only in `AFTER` triggers.

[NOTE]
====
In multi-action triggers -- introduced in Firebird 1.5 -- `NEW` is always available.
However, if the trigger is fired by a `DELETE`, there will be no new version of the record.
In that situation, reading from `NEW` will always return `NULL`;
writing to it will cause a runtime exception.
====

[[fblangref40-contextvars-now]]
== `'NOW'`

.Available in
DSQL, PSQL, ESQL

.Type
`CHAR(3)`

`'NOW'` is not a variable, but a string literal or datetime mnemonic.
It is, however, special in the sense that when you `CAST()` it to a date/time type, you will get the current date and/or time.
Since Firebird 2.0 the precision is 3 decimals, i.e. milliseconds. `'NOW'` is case-insensitive, and the engine ignores leading or trailing spaces when casting.

[NOTE]
====
* `'NOW'` always returns the actual date/time, even in PSQL modules, where <<fblangref40-contextvars-current-date>>, <<fblangref40-contextvars-current-time>> and <<fblangref40-contextvars-current-timestamp>> return the same value throughout the duration of the outermost routine.
This makes `'NOW'` useful for measuring time intervals in triggers, procedures and executable blocks.
* Except in the situation mentioned above, reading <<fblangref40-contextvars-current-date>>, <<fblangref40-contextvars-current-time>> and <<fblangref40-contextvars-current-timestamp>> is generally preferable to casting `'NOW'`.
Be aware though that `CURRENT_TIME` defaults to seconds precision; to get milliseconds precision, use `CURRENT_TIME(3)`.
* Firebird 3.0 and earlier allowed the use of `'NOW'` in datetime literals (a.k.a. "`shorthand casts"`), this is no longer allowed in Firebird 4.0.
====

.Examples
[source]
----
select 'Now' from rdb$database
-- returns 'Now'

select cast('Now' as date) from rdb$database
-- returns e.g. 2008-08-13

select cast('now' as time) from rdb$database
-- returns e.g. 14:20:19.6170

select cast('NOW' as timestamp) from rdb$database
-- returns e.g. 2008-08-13 14:20:19.6170
----

[[fblangref40-contextvars-old]]
== `OLD`

.Available in
PSQL, triggers only

.Type
Record type

.Syntax
[listing,subs=+quotes]
----
OLD.__column_name__
----

[[fblangref40-funcs-tbl-old]]
.`OLD` Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|column_name
|Column name to access
|===

`OLD` contains the existing version of a database record just before a deletion or update.
Starting with Firebird 2.0 it is read-only.

[NOTE]
====
In multi-action triggers -- introduced in Firebird 1.5 -- `OLD` is always available.
However, if the trigger is fired by an `INSERT`, there is obviously no pre-existing version of the record.
In that situation, reading from `OLD` will always return `NULL`;
writing to it will cause a runtime exception.
====

[[fblangref40-contextvars-resetting]]
== `RESETTING`

.Available in
PSQL

.Type
`BOOLEAN`

.Syntax
[listing]
----
RESETTING
----

Available in triggers only, `RESETTING` indicates if the trigger fired during a session reset.
Its value is TRUE if session reset is in progress and FALSE otherwise.
Intended for use in `ON DISCONNECT` and `ON CONNECT` database triggers to detect an <<fblangref40-management-session-reset-alter,`ALTER SESSION RESET`>>.

[[fblangref40-contextvars-row-count]]
== `ROW_COUNT`

.Available in
PSQL

.Type
`INTEGER`

.Syntax
[listing]
----
ROW_COUNT
----

The `ROW_COUNT` context variable contains the number of rows affected by the most recent DML statement (`INSERT`, `UPDATE`, `DELETE`, `SELECT` or `FETCH`) in the current trigger, stored procedure or executable block.

.Behaviour with `SELECT` and `FETCH`
* After a singleton `SELECT`, `ROW_COUNT` is 1 if a data row was retrieved and 0 otherwise.
* In a `FOR SELECT` loop, `ROW_COUNT` is incremented with every iteration (starting at 0 before the first).
* After a `FETCH` from a cursor, `ROW_COUNT` is 1 if a data row was retrieved and 0 otherwise.
Fetching more records from the same cursor does _not_ increment `ROW_COUNT` beyond 1.
* In Firebird 1.5.x, `ROW_COUNT` is 0 after any type of `SELECT` statement.

[NOTE]
====
`ROW_COUNT` cannot be used to determine the number of rows affected by an `EXECUTE STATEMENT` or `EXECUTE PROCEDURE` command.
====

.Example
[source]
----
update Figures set Number = 0 where id = :id;
if (row_count = 0) then
  insert into Figures (id, Number) values (:id, 0);
----

[[fblangref40-contextvars-sqlcode]]
== `SQLCODE`

.Available in
PSQL

.Deprecated in
2.5.1

.Type
`INTEGER`

.Syntax
[listing]
----
SQLCODE
----

In a "```WHEN ... DO```" error handling block, the `SQLCODE` context variable contains the current SQL error code.
Prior to Firebird 2.0, `SQLCODE` was only set in `WHEN SQLCODE` and `WHEN ANY` handlers.
Now it may also be non-zero in `WHEN GDSCODE`, `WHEN SQLSTATE` and `WHEN EXCEPTION` blocks, provided that the condition raising the error corresponds with an SQL error code.
Outside error handlers, `SQLCODE` is always 0.
Outside PSQL, it doesn't exist at all.

[WARNING]
====
`SQLCODE` is now deprecated in favour of the SQL-2003-compliant <<fblangref40-contextvars-sqlstate>> status code.
Support for `SQLCODE` and `WHEN SQLCODE` will be discontinued in some future version of Firebird.
====

.Example
[source]
----
when any
do
begin
  if (sqlcode <> 0) then
    Msg = 'An SQL error occurred!';
  else
    Msg = 'Something bad happened!';
  exception ex_custom Msg;
end
----

[[fblangref40-contextvars-sqlstate]]
== `SQLSTATE`

.Available in
PSQL

.Type
`CHAR(5)`

.Syntax
[listing]
----
SQLSTATE
----

In a "```WHEN ... DO```" error handler, the `SQLSTATE` context variable contains the 5-character, SQL-2003-compliant status code resulting from the statement that raised the error.
Outside error handlers, `SQLSTATE` is always `'00000'`.
Outside PSQL, it is not available at all.

[NOTE]
====
* `SQLSTATE` is destined to replace `SQLCODE`.
The latter is now deprecated in Firebird and will disappear in some future version.
* Firebird does not (yet) support the syntax "```WHEN SQLSTATE ... DO```".
You have to use `WHEN ANY` and test the `SQLSTATE` variable within the handler.
* Each `SQLSTATE` code is the concatenation of a 2-character class and a 3-character subclass.
Classes _00_ (successful completion), _01_ (warning) and _02_ (no data) represent [term]_completion conditions_.
Every status code outside these classes is an [term]_exception_.
Because classes _00_, _01_ and _02_ don't raise an error, they won't ever show up in the `SQLSTATE` variable.
* For a complete listing of `SQLSTATE` codes, consult the <<fblangref40-appx02-tbl-sqlstates,SQLSTATE Codes and Message Texts>> section in [ref]_Appendix B: Exception Handling, Codes and Messages_.
====

.Example
[source]
----
when any
do
begin
  Msg = case sqlstate
          when '22003' then 'Numeric value out of range.'
          when '22012' then 'Division by zero.'
          when '23000' then 'Integrity constraint violation.'
          else 'Something bad happened! SQLSTATE = ' || sqlstate
        end;
  exception ex_custom Msg;
end
----

[[fblangref40-contextvars-today]]
== `'TODAY'`

.Available in
DSQL, PSQL, ESQL

.Type
`CHAR(5)`

`'TODAY'` is not a variable, but a string literal or date mnemonic.
It is, however, special in the sense that when you `CAST()` it to a date/time type, you will get the current date.
`'TODAY'` is case-insensitive, and the engine ignores leading or trailing spaces when casting.

[NOTE]
====
* `'TODAY'` always returns the actual date, even in PSQL modules, where <<fblangref40-contextvars-current-date>>, <<fblangref40-contextvars-current-time>> and <<fblangref40-contextvars-current-timestamp>> return the same value throughout the duration of the outermost routine.
This makes `'TODAY'` useful for measuring time intervals in triggers, procedures and executable blocks (at least if your procedures are running for days).
* Except in the situation mentioned above, reading `CURRENT_DATE`, is generally preferable to casting `'TODAY'`.
* Firebird 3.0 and earlier allowed the use of `'TODAY'` in datetime literals (a.k.a. "`shorthand casts"`), this is no longer allowed in Firebird 4.0.
====

.Examples
[source]
----
select 'Today' from rdb$database
-- returns 'Today'

select cast('Today' as date) from rdb$database
-- returns e.g. 2011-10-03

select cast('TODAY' as timestamp) from rdb$database
-- returns e.g. 2011-10-03 00:00:00.0000
----

[[fblangref40-contextvars-tomorrow]]
== `'TOMORROW'`

.Available in
DSQL, PSQL, ESQL

.Type
`CHAR(8)`

`'TOMORROW'` is not a variable, but a string literal.
It is, however, special in the sense that when you `CAST()` it to a date/time type, you will get the date of the next day.
See also <<fblangref40-contextvars-today>>.

.Examples
[source]
----
select 'Tomorrow' from rdb$database
-- returns 'Tomorrow'

select cast('Tomorrow' as date) from rdb$database
-- returns e.g. 2011-10-04

select cast('TOMORROW' as timestamp) from rdb$database
-- returns e.g. 2011-10-04 00:00:00.0000
----

[[fblangref40-contextvars-updating]]
== `UPDATING`

.Available in
PSQL

.Type
`BOOLEAN`

.Syntax
[listing]
----
UPDATING
----

Available in triggers only, `UPDATING` indicates if the trigger fired because of an `UPDATE` operation.
Intended for use in <<fblangref40-ddl-trgr-relntrigger-rowevent,multi-action triggers>>.

.Example
[source]
----
if (inserting or updating) then
begin
  if (new.serial_num is null) then
    new.serial_num = gen_id(gen_serials, 1);
end
----

[[fblangref40-contextvars-yesterday]]
== `'YESTERDAY'`

.Available in
DSQL, PSQL, ESQL

.Type
`CHAR(9)`

`'YESTERDAY'` is not a variable, but a string literal.
It is, however, special in the sense that when you `CAST()` it to a date/time type, you will get the date of the day before.
See also <<fblangref40-contextvars-today>>.

.Examples
[source]
----
select 'Yesterday' from rdb$database
-- returns 'Yesterday'

select cast('Yesterday as date) from rdb$database
-- returns e.g. 2011-10-02

select cast('YESTERDAY' as timestamp) from rdb$database
-- returns e.g. 2011-10-02 00:00:00.0000
----

[[fblangref40-contextvars-user]]
== `USER`

.Available in
DSQL, PSQL

.Type
`VARCHAR(63)`

.Syntax
[listing]
----
USER
----

`USER` is a context variable containing the name of the currently connected user.
It is fully equivalent to <<fblangref40-contextvars-current-user>>.

.Example
[source]
----
create trigger bi_customers for customers before insert as
begin
  New.added_by  = USER;
  New.purchases = 0;
end
----
