[[fblangref40-functions]]
= Built-in Scalar Functions

[[fblangref40-functions-nameclashes]]
.Upgraders: PLEASE READ!
****
Many functions that were implemented as external functions (UDFs) in earlier versions of Firebird have been progressively re-implemented as internal (built-in) functions.
If some external function of the same name as a built-in one is declared in your database, it will remain there and it will override any internal function of the same name.

To make the internal function available, you need either to <<fblangref40-ddl-extfunc-drop,`DROP`>> the UDF, or to use <<fblangref40-ddl-extfunc-alter,`ALTER EXTERNAL FUNCTION`>> to change the declared name of the UDF.
****

[[fblangref40-functions-workcontext]]
== Context Functions

[[fblangref40-scalarfuncs-get-context]]
=== `RDB$GET_CONTEXT()`

.Available in
DSQL, PSQL{nbsp}* As a declared UDF it should be available in ESQL

.Result type
`VARCHAR(255)`

.Syntax
[listing,subs=+quotes]
----
RDB$GET_CONTEXT ('<namespace>', <varname>)

<namespace> ::= SYSTEM | USER_SESSION | USER_TRANSACTION | DDL_TRIGGER
<varname>   ::= _A case-sensitive quoted string of max. 80 characters_
----

[[fblangref40-funcs-tbl-rdbgetcontext]]
.`RDB$GET_CONTEXT` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|namespace
|Namespace

|varname
|Variable name.
Case-sensitive.
Maximum length is 80 characters
|===

Retrieves the value of a context variable from one of the namespaces `SYSTEM`, `USER_SESSION` and `USER_TRANSACTION`.

.The namespaces
The `USER_SESSION` and `USER_TRANSACTION` namespaces are initially empty.
The user can create and set variables in them with `RDB$SET_CONTEXT()` and retrieve them with `RDB$GET_CONTEXT()`.
The `SYSTEM` namespace is read-only.
The `DDL_TRIGGER` namespace is only valid in DDL triggers, and is read-only.
It contains a number of predefined variables, shown below.

.Return values and error behaviour
If the polled variable exists in the given namespace, its value will be returned as a string of max. 255 characters.
If the namespace doesn't exist or if you try to access a non-existing variable in the `SYSTEM` namespace, an error is raised.
If you request a non-existing variable in one of the other namespaces, `NULL` is returned.
Both namespace and variable names must be given as single-quoted, case-sensitive, non-``NULL`` strings.

[[fblangref40-funcs-tbl-rdbgetcontext-system]]
==== The `SYSTEM` Namespace

[[fblangref40-funcs-tbl-systemnamespace]]
.Context variables in the SYSTEM namespace
`CLIENT_ADDRESS`::
For TCPv4, this is the IP address.
For XNET, the local process ID.
For all other protocols this variable is `NULL`.

`CURRENT_ROLE`::
Same as global <<fblangref40-contextvars-current-role>> variable.

`CURRENT_USER`::
Same as global <<fblangref40-contextvars-current-user>> variable.

`DB_NAME`::
Either the full path to the database or -- if connecting via the path is disallowed -- its alias.

`ENGINE_VERSION`::
The Firebird engine (server) version.

`ISOLATION_LEVEL`::
The isolation level of the current transaction: `'READ COMMITTED'`, `'SNAPSHOT'` or `'CONSISTENCY'`.

`NETWORK_PROTOCOL`::
The protocol used for the connection: `'TCPv4'`, `'WNET'`, `'XNET'` or `NULL`.

`SESSION_ID`::
Same as global <<fblangref40-contextvars-current-connection>> variable.

`TRANSACTION_ID`::
Same as global <<fblangref40-contextvars-current-transaction>> variable.

`WIRE_COMPRESSED`::
Compression status of the current connection.
If the connection is compressed, returns `TRUE`;
if it is not compressed, returns `FALSE`.
Returns `NULL` if the connection is embedded.
+
Introduced in Firebird 3.0.4.

`WIRE_ENCRYPTED`::
Encryption status of the current connection.
If the connection is encrypted, returns `TRUE`;
if it is not encrypted, returns `FALSE`.
Returns `NULL` if the connection is embedded.
+
Introduced in Firebird 3.0.4.

[[fblangref40-funcs-tbl-rdbgetcontext-ddl-trigger]]
==== The `DDL_TRIGGER` Namespace

The `DDL_TRIGGER` namespace is valid only when a DDL trigger is running.
Its use is also valid in stored procedures and functions called by DDL triggers.

The `DDL_TRIGGER` context works like a stack.
Before a DDL trigger is fired, the values relative to the executed command are pushed onto this stack.
After the trigger finishes, the values are popped.
So in the case of cascade DDL statements, when a user DDL command fires a DDL trigger and this trigger executes another DDL command with `EXECUTE STATEMENT`, the values of the `DDL_TRIGGER` namespace are the ones relative to the command that fired the last DDL trigger on the call stack.

.Context variables in the DDL_TRIGGER namespace
`EVENT_TYPE`:: event type (`CREATE`, `ALTER`, `DROP`)
`OBJECT_TYPE`:: object type (`TABLE`, `VIEW`, etc)
`DDL_EVENT`:: event name (`<ddl event item>`), where `<ddl_event_item>` is `EVENT_TYPE || ' ' || OBJECT_TYPE`
`OBJECT_NAME`:: metadata object name
`OLD_OBJECT_NAME`:: for tracking the renaming of a domain (see note)
`NEW_OBJECT_NAME`:: for tracking the renaming of a domain (see note)
`SQL_TEXT`:: sql statement text

[NOTE]
====
`ALTER DOMAIN __old-name__ TO __new-name__` sets `OLD_OBJECT_NAME` and `NEW_OBJECT_NAME` in both `BEFORE` and `AFTER` triggers.
For this command, `OBJECT_NAME` will have the old object name in `BEFORE` triggers, and the new object name in `AFTER` triggers.
====

[[fblangref40-funcs-tbl-rdbgetcontext-exmpl]]
==== Examples

[source]
----
select rdb$get_context('SYSTEM', 'DB_NAME') from rdb$database

New.UserAddr = rdb$get_context('SYSTEM', 'CLIENT_ADDRESS');

insert into MyTable (TestField)
  values (rdb$get_context('USER_SESSION', 'MyVar'))
----

.See also
<<fblangref40-scalarfuncs-set-context>>

[[fblangref40-scalarfuncs-set-context]]
=== `RDB$SET_CONTEXT()`

.Available in
DSQL, PSQL{nbsp}* As a declared UDF it should be available in ESQL

.Result type
`INTEGER`

.Syntax
[listing,subs=+quotes]
----
RDB$SET_CONTEXT ('<namespace>', <varname>, <value> | NULL)

<namespace> ::= USER_SESSION | USER_TRANSACTION
<varname>   ::= _A case-sensitive quoted string of max. 80 characters_
<value>     ::= _A value of any type, as long as it's castable_
                _to a VARCHAR(255)_
----

[[fblangref40-funcs-tbl-rdbsetcontext]]
.`RDB$SET_CONTEXT` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|namespace
|Namespace

|varname
|Variable name.
Case-sensitive.
Maximum length is 80 characters

|value
|Data of any type provided it can be cast to `VARCHAR(255)`
|===

Creates, sets or unsets a variable in one of the user-writable namespaces `USER_SESSION` and `USER_TRANSACTION`.

.The namespaces
The `USER_SESSION` and `USER_TRANSACTION` namespaces are initially empty.
The user can create and set variables in them with `RDB$SET_CONTEXT()` and retrieve them with `RDB$GET_CONTEXT()`.
The `USER_SESSION` context is bound to the current connection.
Variables in `USER_TRANSACTION` only exist in the transaction in which they have been set.
When the transaction ends, the context and all the variables defined in it are destroyed.

.Return values and error behaviour
The function returns `1` when the variable already existed before the call and `0` when it didn't.
To remove a variable from a context, set it to `NULL`.
If the given namespace doesn't exist, an error is raised.
Both namespace and variable names must be entered as single-quoted, case-sensitive, non-``NULL`` strings.

[NOTE]
====
* The maximum number of variables in any single context is 1000.
* All `USER_TRANSACTION` variables will survive a <<fblangref40-transacs-rollback-options,`ROLLBACK RETAIN`>>  (see `ROLLBACK` Options) or <<fblangref40-transacs-rollback-tosavepoint,`ROLLBACK TO SAVEPOINT`>> unaltered, no matter at which point during the transaction they were set.
* Due to its UDF-like nature, `RDB$SET_CONTEXT` can -- in PSQL only -- be called like a void function, without assigning the result, as in the second example above.
Regular internal functions don't allow this type of use.
====

.Examples
[source]
----
select rdb$set_context('USER_SESSION', 'MyVar', 493) from rdb$database

rdb$set_context('USER_SESSION', 'RecordsFound', RecCounter);

select rdb$set_context('USER_TRANSACTION', 'Savepoints', 'Yes')
  from rdb$database
----

.See also
<<fblangref40-scalarfuncs-get-context>>

[[fblangref40-functions-math]]
== Mathematical Functions

[[fblangref40-scalarfuncs-abs]]
=== `ABS()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
Numerical

.Syntax
[listing,subs=+quotes]
----
ABS (_number_)
----

[[fblangref40-funcs-tbl-abs]]
.`ABS` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|An expression of a numeric type
|===

Returns the absolute value of the argument.

[[fblangref40-scalarfuncs-acos]]
=== `ACOS()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
ACOS (_number_)
----

[[fblangref40-funcs-tbl-acos]]
.`ACOS` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|An expression of a numeric type within the range [-1, 1]
|===

Returns the arc cosine of the argument.

* The result is an angle in the range [0, pi].

.See also
<<fblangref40-scalarfuncs-cos>>, <<fblangref40-scalarfuncs-asin>>, <<fblangref40-scalarfuncs-atan>>

[[fblangref40-scalarfuncs-acosh]]
=== `ACOSH()`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
ACOSH (_number_)
----

[[fblangref40-funcs-tbl-acosh]]
.`ACOSH` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|Any non-``NULL`` value in the range [1, INF].
|===

Returns the inverse hyperbolic cosine of the argument.

* The result is in the range [0, INF].

.See also
<<fblangref40-scalarfuncs-cosh>>, <<fblangref40-scalarfuncs-asinh>>, <<fblangref40-scalarfuncs-atanh>>

[[fblangref40-scalarfuncs-asin]]
=== `ASIN()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
ASIN (_number_)
----

[[fblangref40-funcs-tbl-asin]]
.`ASIN` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|An expression of a numeric type within the range [-1, 1]
|===

Returns the arc sine of the argument.

* The result is an angle in the range [-pi/2, pi/2].

.See also
<<fblangref40-scalarfuncs-sin>>, <<fblangref40-scalarfuncs-acos>>, <<fblangref40-scalarfuncs-atan>>

[[fblangref40-scalarfuncs-asinh]]
=== `ASINH()`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
ASINH (_number_)
----

[[fblangref40-funcs-tbl-asinh]]
.`ASINH` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|Any non-``NULL`` value in the range [-INF, INF].
|===

Returns the inverse hyperbolic sine of the argument.

* The result is in the range [-INF, INF].

.See also
<<fblangref40-scalarfuncs-sinh>>, <<fblangref40-scalarfuncs-acosh>>, <<fblangref40-scalarfuncs-atanh>>

[[fblangref40-scalarfuncs-atan]]
=== `ATAN()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
ATAN (_number_)
----

[[fblangref40-funcs-tbl-atan]]
.`ATAN` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|An expression of a numeric type
|===

The function `ATAN` returns the arc tangent of the argument.
The result is an angle in the range ++<-pi/2, pi/2>++.

.See also
<<fblangref40-scalarfuncs-atan2>>, <<fblangref40-scalarfuncs-tan>>, <<fblangref40-scalarfuncs-acos>>, <<fblangref40-scalarfuncs-asin>>

[[fblangref40-scalarfuncs-atan2]]
=== `ATAN2()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

//Note for maintainers/editors: the argument names y and x (in that order!) are chosen on purpose, for geometrical reasons.
.Syntax
[listing,subs=+quotes]
----
ATAN2 (_y_, _x_)
----

[[fblangref40-funcs-tbl-atan2]]
.`ATAN2` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|y
|An expression of a numeric type

|x
|An expression of a numeric type
|===

Returns the angle whose sine-to-cosine _ratio_ is given by the two arguments, and whose sine and cosine _signs_ correspond to the signs of the arguments.
This allows results across the entire circle, including the angles -pi/2 and pi/2. 

* The result is an angle in the range [-pi, pi].
* If _x_ is negative, the result is pi if _y_ is 0, and -pi if _y_ is -0.
* If both _y_ and _x_ are 0, the result is meaningless.
Starting with Firebird 3.0, an error will be raised if both arguments are 0.
At v.2.5.4, it is still not fixed in lower versions.
For more details, visit http://tracker.firebirdsql.org/browse/CORE-3201[Tracker ticket CORE-3201].

[NOTES]
====
* A fully equivalent description of this function is the following: `ATAN2(__y__, __x__)` is the angle between the positive X-axis and the line from the origin to the point _(x, y)_.
This also makes it obvious that `ATAN2(0, 0)` is undefined.
* If _x_ is greater than 0, `ATAN2(__y__, __x__)` is the same as `ATAN(__y__/__x__)`.
* If both sine and cosine of the angle are already known, `ATAN2(__sin__, __cos__)` gives the angle.
====

[[fblangref40-scalarfuncs-atanh]]
=== `ATANH()`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
ATANH (_number_)
----

[[fblangref40-funcs-tbl-atanh]]
.`ATANH` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|Any non-``NULL`` value in the range ++<-1, 1>++.
|===

Returns the inverse hyperbolic tangent of the argument.

* The result is a number in the range [-INF, INF].

.See also
<<fblangref40-scalarfuncs-tanh>>, <<fblangref40-scalarfuncs-acosh>>, <<fblangref40-scalarfuncs-asinh>>

[[fblangref40-scalarfuncs-ceil]]
=== `CEIL()`, `CEILING()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>> (Affects `CEILING` only)

.Result type
`BIGINT` for exact numeric _number_, or `DOUBLE PRECISION` for floating point _number_

.Syntax
[listing,subs=+quotes]
----
CEIL[ING] (_number_)
----

[[fblangref40-funcs-tbl-ceil]]
.`CEIL[ING]` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|An expression of a numeric type
|===

Returns the smallest whole number greater than or equal to the argument.

.See also
<<fblangref40-scalarfuncs-floor>>, <<fblangref40-scalarfuncs-round>>, <<fblangref40-scalarfuncs-trunc>>

[[fblangref40-scalarfuncs-cos]]
=== `COS()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
COS (_angle_)
----

[[fblangref40-funcs-tbl-cos]]
.`COS` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|angle
|An angle in radians
|===

Returns an angle's cosine.
The argument must be given in radians. 

* Any non-``NULL`` result is -- obviously -- in the range [-1, 1].

.See also
<<fblangref40-scalarfuncs-acos>>, <<fblangref40-scalarfuncs-cot>>, <<fblangref40-scalarfuncs-sin>>, <<fblangref40-scalarfuncs-tan>>

[[fblangref40-scalarfuncs-cosh]]
=== `COSH()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
COSH (_number_)
----

[[fblangref40-funcs-tbl-cosh]]
.`COSH` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|A number of a numeric type
|===

Returns the hyperbolic cosine of the argument.

* Any non-``NULL`` result is in the range [1, INF].

.See also
<<fblangref40-scalarfuncs-acosh>>, <<fblangref40-scalarfuncs-sinh>>, <<fblangref40-scalarfuncs-tanh>>

[[fblangref40-scalarfuncs-cot]]
=== `COT()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
COT (_angle_)
----

[[fblangref40-funcs-tbl-cot]]
.`COT` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|angle
|An angle in radians
|===

Returns an angle's cotangent.
The argument must be given in radians.

.See also
<<fblangref40-scalarfuncs-cos>>, <<fblangref40-scalarfuncs-sin>>, <<fblangref40-scalarfuncs-tan>>

[[fblangref40-scalarfuncs-exp]]
=== `EXP()`

.Available in
DSQL, PSQL

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
EXP (_number_)
----

[[fblangref40-funcs-tbl-exp]]
.`EXP` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|A number of a numeric type
|===

Returns the natural exponential, _e_^`number`^

.See also
<<fblangref40-scalarfuncs-ln>>

[[fblangref40-scalarfuncs-floor]]
=== `FLOOR()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`BIGINT` for exact numeric _number_, or `DOUBLE PRECISION` for floating point _number_

.Syntax
[listing,subs=+quotes]
----
FLOOR (_number_)
----

[[fblangref40-funcs-tbl-floor]]
.`FLOOR` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|An expression of a numeric type
|===

Returns the largest whole number smaller than or equal to the argument.

.See also
<<fblangref40-scalarfuncs-ceil>>, <<fblangref40-scalarfuncs-round>>, <<fblangref40-scalarfuncs-trunc>>

[[fblangref40-scalarfuncs-ln]]
=== `LN()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
LN (_number_)
----

[[fblangref40-funcs-tbl-ln]]
.`LN` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|An expression of a numeric type
|===

Returns the natural logarithm of the argument.

* An error is raised if the argument is negative or 0.

.See also
<<fblangref40-scalarfuncs-exp>>, <<fblangref40-scalarfuncs-log>>, <<fblangref40-scalarfuncs-log10>>

[[fblangref40-scalarfuncs-log]]
=== `LOG()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
LOG (_x_, _y_)
----

[[fblangref40-funcs-tbl-log]]
.`LOG` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|x
|Base.
An expression of a numeric type

|y
|An expression of a numeric type
|===

Returns the __x__-based logarithm of _y_.

* If either argument is 0 or below, an error is raised.
(Before 2.5, this would result in `NaN`, `+/-INF` or 0, depending on the exact values of the arguments.)
* If both arguments are 1, `NaN` is returned.
* If _x_ = 1 and _y_ < 1, `-INF` is returned.
* If _x_ = 1 and _y_ > 1, `INF` is returned.

.See also
<<fblangref40-scalarfuncs-power>>, <<fblangref40-scalarfuncs-ln>>, <<fblangref40-scalarfuncs-log10>>

[[fblangref40-scalarfuncs-log10]]
=== `LOG10()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
LOG10 (_number_)
----

[[fblangref40-funcs-tbl-log10]]
.`LOG10` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|An expression of a numeric type
|===

Returns the 10-based logarithm of the argument.

* An error is raised if the argument is negative or 0.
(In versions prior to 2.5, such values would result in `NaN` and `-INF`, respectively.)

.See also
<<fblangref40-scalarfuncs-power>>, <<fblangref40-scalarfuncs-ln>>, <<fblangref40-scalarfuncs-log>>

[[fblangref40-scalarfuncs-mod]]
=== `MOD()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`SMALLINT`, `INTEGER` or `BIGINT` depending on the type of _a_.
If _a_ is a floating-point type, the result is a `BIGINT`.

.Syntax
[listing,subs=+quotes]
----
MOD (_a_, _b_)
----

[[fblangref40-funcs-tbl-mod]]
.`MOD` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|a
|An expression of a numeric type

|b
|An expression of a numeric type
|===

Returns the remainder of an integer division.

* Non-integer arguments are rounded before the division takes place.
So, "```mod(7.5, 2.5)```" gives 2 ("```mod(8, 3)```"), not 0.

[[fblangref40-scalarfuncs-pi]]
=== `PI()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
PI ()
----

Returns an approximation of the value of _pi_.

[[fblangref40-scalarfuncs-power]]
=== `POWER()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
POWER (_x_, _y_)
----

[[fblangref40-funcs-tbl-power]]
.`POWER` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|x
|An expression of a numeric type

|y
|An expression of a numeric type
|===

Returns _x_ to the power of _y_ (_x^y^_).

.See also
<<fblangref40-scalarfuncs-exp>>, <<fblangref40-scalarfuncs-log>>, <<fblangref40-scalarfuncs-log10>>, <<fblangref40-scalarfuncs-sqrt>>

[[fblangref40-scalarfuncs-rand]]
=== `RAND()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing]
----
RAND ()
----

Returns a random number between 0 and 1.

[[fblangref40-scalarfuncs-round]]
=== `ROUND()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`INTEGER`, (scaled) `BIGINT` or `DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
ROUND (_number_ [, _scale_])
----

[[fblangref40-funcs-tbl-round]]
.`ROUND` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^|Parameter
^|Description

|number
|An expression of a numeric type

|scale
a|An integer specifying the number of decimal places toward which rounding is to be performed, e.g.:

* {nbsp}2 for rounding to the nearest multiple of 0.01
* {nbsp}1 for rounding to the nearest multiple of 0.1
* {nbsp}0 for rounding to the nearest whole number
* -1 for rounding to the nearest multiple of 10
* -2 for rounding to the nearest multiple of 100
|===

Rounds a number to the nearest integer.
If the fractional part is exactly `0.5`, rounding is upward for positive numbers and downward for negative numbers.
With the optional _scale_ argument, the number can be rounded to powers-of-ten multiples (tens, hundreds, tenths, hundredths, etc.) instead of just integers.

[IMPORTANT]
====
If you are used to the behaviour of the external function `ROUND`, please notice that the _internal_ function always rounds halves away from zero, i.e. downward for negative numbers.
====

[[fblangref40-scalarfuncs-round-exmpl]]
==== `ROUND` Examples

If the _scale_ argument is present, the result usually has the same scale as the first argument:

[source]
----
ROUND(123.654, 1) -- returns 123.700 (not 123.7)
ROUND(8341.7, -3) -- returns 8000.0 (not 8000)
ROUND(45.1212, 0) -- returns 45.0000 (not 45)
----

Otherwise, the result scale is 0:

[source]
----
ROUND(45.1212) -- returns 45
----

.See also
<<fblangref40-scalarfuncs-ceil>>, <<fblangref40-scalarfuncs-floor>>, <<fblangref40-scalarfuncs-trunc>>

[[fblangref40-scalarfuncs-sign]]
=== `SIGN()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`SMALLINT`

.Syntax
[listing,subs=+quotes]
----
SIGN (_number_)
----

[[fblangref40-funcs-tbl-sign]]
.`SIGN` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|An expression of a numeric type
|===

Returns the sign of the argument: -1, 0 or 1.

[[fblangref40-scalarfuncs-sin]]
=== `SIN()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
SIN (_angle_)
----

[[fblangref40-funcs-tbl-sin]]
.`SIN` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|angle
|An angle, in radians
|===

Returns an angle's sine.
The argument must be given in radians. 

* Any non-`NULL` result is -- obviously -- in the range [-1, 1].

.See also
<<fblangref40-scalarfuncs-asin>>, <<fblangref40-scalarfuncs-cos>>, <<fblangref40-scalarfuncs-cot>>, <<fblangref40-scalarfuncs-tan>>

[[fblangref40-scalarfuncs-sinh]]
=== `SINH()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
SINH (_number_)
----

[[fblangref40-funcs-tbl-sinh]]
.`SINH` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|An expression of a numeric type
|===

Returns the hyperbolic sine of the argument.

.See also
<<fblangref40-scalarfuncs-asinh>>, <<fblangref40-scalarfuncs-cosh>>, <<fblangref40-scalarfuncs-tanh>>

[[fblangref40-scalarfuncs-sqrt]]
=== `SQRT()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
SQRT (_number_)
----

[[fblangref40-funcs-tbl-sqrt]]
.`SQRT` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|An expression of a numeric type
|===

Returns the square root of the argument.

* If _number_ is negative, an error is raised.

.See also
<<fblangref40-scalarfuncs-power>>

[[fblangref40-scalarfuncs-tan]]
=== `TAN()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
TAN (_angle_)
----

[[fblangref40-funcs-tbl-tan]]
.`TAN` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|angle
|An angle, in radians
|===

Returns an angle's tangent.
The argument must be given in radians.

.See also
<<fblangref40-scalarfuncs-atan>>, <<fblangref40-scalarfuncs-atan2>>, <<fblangref40-scalarfuncs-cos>>, <<fblangref40-scalarfuncs-cot>>, <<fblangref40-scalarfuncs-sin>>, <<fblangref40-scalarfuncs-tan>>

[[fblangref40-scalarfuncs-tanh]]
=== `TANH()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
TANH (_number_)
----

[[fblangref40-funcs-tbl-tanh]]
.`TANH` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|An expression of a numeric type
|===

Returns the hyperbolic tangent of the argument.

* Due to rounding, any non-`NULL` result is in the range [-1, 1] (mathematically, it's ++<-1, 1>++).

.See also
<<fblangref40-scalarfuncs-atanh>>, <<fblangref40-scalarfuncs-cosh>>, <<fblangref40-scalarfuncs-tanh>>

[[fblangref40-scalarfuncs-trunc]]
=== `TRUNC()`

.Available in
DSQL, PSQL

.Result type
`INTEGER`, (scaled) `BIGINT` or `DOUBLE PRECISION`

.Syntax
[listing,subs=+quotes]
----
TRUNC (_number_ [, _scale_])
----

[[fblangref40-funcs-tbl-trunc]]
.`TRUNC` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^|Parameter
^|Description

|number
|An expression of a numeric type

|scale
a|An integer specifying the number of decimal places toward which truncating is to be performed, e.g.:

* {nbsp}2 for truncating to the nearest multiple of 0.01
* {nbsp}1 for truncating to the nearest multiple of 0.1
* {nbsp}0 for truncating to the nearest whole number
* -1 for truncating to the nearest multiple of 10
* -2 for truncating to the nearest multiple of 100
|===

Returns the integer part of a number.
With the optional _scale_ argument, the number can be truncated to powers-of-ten multiples (tens, hundreds, tenths, hundredths, etc.) instead of just integers.

[NOTE]
====
* If the _scale_ argument is present, the result usually has the same scale as the first argument, e.g.
** `TRUNC(789.2225, 2)` returns 789.2200 (not 789.22)
** `TRUNC(345.4, -2)` returns 300.0 (not 300)
** `TRUNC(-163.41, 0)` returns -163.00 (not -163)
* Otherwise, the result scale is 0:
** `TRUNC(-163.41)` returns -163
====

[IMPORTANT]
====
If you are used to the behaviour of the https://www.firebirdsql.org/file/documentation/reference_manuals/reference_material/html/langrefupd25-udf-truncate.html[external function `TRUNCATE`], please notice that the _internal_ function `TRUNC` always truncates toward zero, i.e. upward for negative numbers.
====

.See also
<<fblangref40-scalarfuncs-ceil>>, <<fblangref40-scalarfuncs-floor>>, <<fblangref40-scalarfuncs-round>>

[[fblangref40-functions-string]]
== String Functions

[[fblangref40-scalarfuncs-ascii-char]]
=== `ASCII_CHAR()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`CHAR(1) CHARACTER SET NONE`

.Syntax
[listing,subs=+quotes]
----
ASCII_CHAR (_code_)
----

[[fblangref40-funcs-tbl-asciichar]]
.`ASCII_CHAR` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|code
|An integer within the range from 0 to 255
|===

Returns the ASCII character corresponding to the number passed in the argument.

[IMPORTANT]
====
* If you are used to the behaviour of the `ASCII_CHAR` UDF, which returns an empty string if the argument is 0, please notice that the internal function correctly returns a character with ASCII code 0 here.
====

[[fblangref40-scalarfuncs-ascii-val]]
=== `ASCII_VAL()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`SMALLINT`

.Syntax
[listing,subs=+quotes]
----
ASCII_VAL (_ch_)
----

[[fblangref40-funcs-tbl-asciival]]
.`ASCII_VAL` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|ch
|A string of the `[VAR]CHAR` data type or a text `BLOB` with the maximum size of 32,767 bytes
|===

Returns the ASCII code of the character passed in.

* If the argument is a string with more than one character, the ASCII code of the first character is returned.
* If the argument is an empty string, 0 is returned.
* If the argument is `NULL`, `NULL` is returned.
* If the first character of the argument string is multi-byte, an error is raised.
(A bug in Firebird 2.1 - 2.1.3 and 2.5.0 causes an error to be raised if _any_ character in the string is multi-byte.
This is fixed in versions 2.1.4 and 2.5.1.)

[[fblangref40-scalarfuncs-bit-length]]
=== `BIT_LENGTH()`

.Available in
DSQL, PSQL

.Result type
`INTEGER`

.Syntax
[listing,subs=+quotes]
----
BIT_LENGTH (_string_)
----

[[fblangref40-funcs-tbl-bitlength]]
.`BIT_LENGTH` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|string
|An expression of a string type
|===

Gives the length in bits of the input string.
For multi-byte character sets, this may be less than the number of characters times 8 times the "`formal`" number of bytes per character as found in `RDB$CHARACTER_SETS`.

[NOTE]
====
With arguments of type `CHAR`, this function takes the entire formal string length (i.e. the declared length of a field or variable) into account.
If you want to obtain the "`logical`" bit length, not counting the trailing spaces, right-<<fblangref40-scalarfuncs-trim,`TRIM`>> the argument before passing it to `BIT_LENGTH`.
====

.`BLOB` support
Since Firebird 2.1, this function fully supports text ``BLOB``s of any length and character set.

[[fblangref40-scalarfuncs-bit-length-exmpl]]
==== `BIT_LENGTH` Examples

[source]
----
select bit_length('Hello!') from rdb$database
-- returns 48

select bit_length(_iso8859_1 'Grüß di!') from rdb$database
-- returns 64: ü and ß take up one byte each in ISO8859_1

select bit_length
  (cast (_iso8859_1 'Grüß di!' as varchar(24) character set utf8))
from rdb$database
-- returns 80: ü and ß take up two bytes each in UTF8

select bit_length
  (cast (_iso8859_1 'Grüß di!' as char(24) character set utf8))
from rdb$database
-- returns 208: all 24 CHAR positions count, and two of them are 16-bit
----

.See also
<<fblangref40-scalarfuncs-octet-length>>, <<fblangref40-scalarfuncs-char-length>>

[[fblangref40-scalarfuncs-char-length]]
=== `CHAR_LENGTH()`, `CHARACTER_LENGTH()`

.Available in
DSQL, PSQL

.Result type
`INTEGER`

.Syntax
[listing,subs=+quotes]
----
  CHAR_LENGTH (_string_)
| CHARACTER_LENGTH (_string_)
----

[[fblangref40-funcs-tbl-charlength]]
.`CHAR[ACTER]_LENGTH` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|string
|An expression of a string type
|===

Gives the length in characters of the input string.

[NOTE]
====
* With arguments of type `CHAR`, this function returns the formal string length (i.e. the declared length of a field or variable).
If you want to obtain the "`logical`" length, not counting the trailing spaces, right-<<fblangref40-scalarfuncs-trim,`TRIM`>> the argument before passing it to `CHAR[ACTER]_LENGTH`.
* *``BLOB`` support*: Since Firebird 2.1, this function fully supports text ``BLOB``s of any length and character set.
====

[[fblangref40-scalarfuncs-char-length-exmpl]]
==== `CHAR_LENGTH` Examples
[source]
----
select char_length('Hello!') from rdb$database
-- returns 6

select char_length(_iso8859_1 'Grüß di!') from rdb$database
-- returns 8

select char_length
  (cast (_iso8859_1 'Grüß di!' as varchar(24) character set utf8))
from rdb$database
-- returns 8; the fact that ü and ß take up two bytes each is irrelevant

select char_length
  (cast (_iso8859_1 'Grüß di!' as char(24) character set utf8))
from rdb$database
-- returns 24: all 24 CHAR positions count
----

.See also
<<fblangref40-scalarfuncs-bit-length>>, <<fblangref40-scalarfuncs-octet-length>>

[[fblangref40-scalarfuncs-hash]]
=== `HASH()`

.Available in
DSQL, PSQL

.Result type
`BIGINT`

.Syntax
[listing,subs=+quotes]
----
HASH (_string_)
----

[[fblangref40-funcs-tbl-hash]]
.`HASH` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|string
|An expression of a string type
|===

Returns a hash value for the input string.
This function fully supports text ``BLOB``s of any length and character set.

[[fblangref40-scalarfuncs-left]]
=== `LEFT()`

.Available in
DSQL, PSQL

.Result type
`VARCHAR` or `BLOB`

.Syntax
[listing,subs=+quotes]
----
LEFT (_string_, _length_)
----

[[fblangref40-funcs-tbl-left]]
.`LEFT` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|string
|An expression of a string type

|length
|Integer expression.
Defines the number of characters to return
|===

Returns the leftmost part of the argument string.
The number of characters is given in the second argument. 

* This function fully supports text ``BLOB``s of any length, including those with a multi-byte character set.
* If _string_ is a `BLOB`, the result is a `BLOB`.
Otherwise, the result is a `VARCHAR(__n__)` with _n_ the length of the input string.
* If the _length_ argument exceeds the string length, the input string is returned unchanged.
* If the _length_ argument is not a whole number, bankers' rounding (round-to-even) is applied, i.e. 0.5 becomes 0, 1.5 becomes 2, 2.5 becomes 2, 3.5 becomes 4, etc.

.See also
<<fblangref40-scalarfuncs-right>>

[[fblangref40-scalarfuncs-lower]]
=== `LOWER()`

.Available in
DSQL, ESQL, PSQL

.Possible name conflict
YES -> <<lowernote,Read details below>>

.Result type
`(VAR)CHAR` or `BLOB`

.Syntax
[listing,subs=+quotes]
----
LOWER (_string_)
----

[[fblangref40-funcs-tbl-lower]]
.`LOWER` Function ParameterS
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|string
|An expression of a string type
|===

Returns the lower-case equivalent of the input string.
The exact result depends on the character set.
With `ASCII` or `NONE` for instance, only ASCII characters are lowercased;
with `OCTETS`, the entire string is returned unchanged.
Since Firebird 2.1 this function also fully supports text ``BLOB``s of any length and character set.

[[lowernote]]
.Name Clash
[NOTE]
====
Because `LOWER` is a reserved word, the internal function will take precedence even if the external function by that name has also been declared.
To call the (inferior!) external function, use double-quotes and the exact capitalisation, as in `"LOWER"(__string__)`.
====

[[fblangref40-scalarfuncs-lower-exmpl]]
==== `LOWER` Examples

[source]
----
select Sheriff from Towns
  where lower(Name) = 'cooper''s valley'
----

.See also
<<fblangref40-scalarfuncs-upper>>

[[fblangref40-scalarfuncs-lpad]]
=== `LPAD()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`VARCHAR` or `BLOB`

.Syntax
[listing,subs=+quotes]
----
LPAD (_str_, _endlen_ [, _padstr_])
----

[[fblangref40-funcs-tbl-lpad]]
.`LPAD` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|str
|An expression of a string type

|endlen
|Output string length

|padstr
|The character or string to be used to pad the source string up to the specified length.
Default is space ("```' '```")
|===

Left-pads a string with spaces or with a user-supplied string until a given length is reached.

* This function fully supports text ``BLOB``s of any length and character set.
* If _str_ is a `BLOB`, the result is a `BLOB`.
Otherwise, the result is a `VARCHAR(__endlen__)`.
* If _padstr_ is given and equals `''` (empty string), no padding takes place.
* If _endlen_ is less than the current string length, the string is truncated to _endlen_, even if _padstr_ is the empty string.

[NOTE]
====
In Firebird 2.1-2.1.3, all non-``BLOB`` results were of type `VARCHAR(32765)`, which made it advisable to cast them to a more modest size.
This is no longer the case.
====

[WARNING]
====
When used on a `BLOB`, this function may need to load the entire object into memory.
Although it does try to limit memory consumption, this may affect performance if huge ``BLOB``s are involved.
====

[[fblangref40-scalarfuncs-lpad-exmpl]]
==== `LPAD` Examples

[source]
----
lpad ('Hello', 12)               -- returns '       Hello'
lpad ('Hello', 12, '-')          -- returns '-------Hello'
lpad ('Hello', 12, '')           -- returns 'Hello'
lpad ('Hello', 12, 'abc')        -- returns 'abcabcaHello'
lpad ('Hello', 12, 'abcdefghij') -- returns 'abcdefgHello'
lpad ('Hello', 2)                -- returns 'He'
lpad ('Hello', 2, '-')           -- returns 'He'
lpad ('Hello', 2, '')            -- returns 'He'
----

.See also
<<fblangref40-scalarfuncs-rpad>>

[[fblangref40-scalarfuncs-octet-length]]
=== `OCTET_LENGTH()`

.Available in
DSQL, PSQL

.Result type
`INTEGER`

.Syntax
[listing,subs=+quotes]
----
OCTET_LENGTH (_string_)
----

[[fblangref40-funcs-tbl-octetlength]]
.`OCTET_LENGTH` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|string
|An expression of a string type
|===

Gives the length in bytes (octets) of the input string.
For multi-byte character sets, this may be less than the number of characters times the "`formal`" number of bytes per character as found in `RDB$CHARACTER_SETS`.

[NOTE]
====
With arguments of type `CHAR`, this function takes the entire formal string length (i.e. the declared length of a field or variable) into account.
If you want to obtain the "`logical`" byte length, not counting the trailing spaces, right-<<fblangref40-scalarfuncs-trim,`TRIM`>> the argument before passing it to `OCTET_LENGTH`.
====

.`BLOB` support
Since Firebird 2.1, this function fully supports text ``BLOB``s of any length and character set.

[[fblangref40-scalarfuncs-octet-length-exmpl]]
==== `OCTET_LENGTH` Examples

[source]
----
select octet_length('Hello!') from rdb$database
-- returns 6

select octet_length(_iso8859_1 'Grüß di!') from rdb$database
-- returns 8: ü and ß take up one byte each in ISO8859_1

select octet_length
  (cast (_iso8859_1 'Grüß di!' as varchar(24) character set utf8))
from rdb$database
-- returns 10: ü and ß take up two bytes each in UTF8

select octet_length
  (cast (_iso8859_1 'Grüß di!' as char(24) character set utf8))
from rdb$database
-- returns 26: all 24 CHAR positions count, and two of them are 2-byte
----

.See also
<<fblangref40-scalarfuncs-bit-length>>, <<fblangref40-scalarfuncs-char-length>>

[[fblangref40-scalarfuncs-overlay]]
=== `OVERLAY()`

.Available in
DSQL, PSQL

.Result type
`VARCHAR` or `BLOB`

.Syntax
[listing,subs=+quotes]
----
OVERLAY (_string_ PLACING _replacement_ FROM _pos_ [FOR _length_])
----

[[fblangref40-funcs-tbl-overlay]]
.`OVERLAY` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|string
|The string into which the replacement takes place

|replacement
|Replacement string

|pos
|The position from which replacement takes place (starting position)

|length
|The number of characters that are to be overwritten
|===

`OVERLAY()` overwrites part of a string with another string.
By default, the number of characters removed from (overwritten in) the host string equals the length of the replacement string.
With the optional fourth argument, a different number of characters can be specified for removal. 

* This function supports ``BLOB``s of any length.
* If _string_ or _replacement_ is a `BLOB`, the result is a `BLOB`.
Otherwise, the result is a `VARCHAR(__n__)` with _n_ the sum of the lengths of _string_ and _replacement_.
* As usual in SQL string functions, _pos_ is 1-based.
* If _pos_ is beyond the end of _string_, _replacement_ is placed directly after _string_.
* If the number of characters from _pos_ to the end of _string_ is smaller than the length of _replacement_ (or than the _length_ argument, if present), _string_ is truncated at _pos_ and _replacement_ placed after it.
* The effect of a "```FOR 0```" clause is that _replacement_ is simply inserted into _string_.
* If any argument is `NULL`, the result is `NULL`.
* If _pos_ or _length_ is not a whole number, bankers' rounding (round-to-even) is applied, i.e. 0.5 becomes 0, 1.5 becomes 2, 2.5 becomes 2, 3.5 becomes 4, etc.

[WARNING]
====
When used on a `BLOB`, this function may need to load the entire object into memory.
This may affect performance if huge ``BLOB``s are involved.
====

[[fblangref40-scalarfuncs-overlay-exmpl]]
==== `OVERLAY` Examples

[source]
----
overlay ('Goodbye' placing 'Hello' from 2)   -- returns 'GHelloe'
overlay ('Goodbye' placing 'Hello' from 5)   -- returns 'GoodHello'
overlay ('Goodbye' placing 'Hello' from 8)   -- returns 'GoodbyeHello'
overlay ('Goodbye' placing 'Hello' from 20)  -- returns 'GoodbyeHello'

overlay ('Goodbye' placing 'Hello' from 2 for 0) -- r. 'GHellooodbye'
overlay ('Goodbye' placing 'Hello' from 2 for 3) -- r. 'GHellobye'
overlay ('Goodbye' placing 'Hello' from 2 for 6) -- r. 'GHello'
overlay ('Goodbye' placing 'Hello' from 2 for 9) -- r. 'GHello'

overlay ('Goodbye' placing '' from 4)        -- returns 'Goodbye'
overlay ('Goodbye' placing '' from 4 for 3)  -- returns 'Gooe'
overlay ('Goodbye' placing '' from 4 for 20) -- returns 'Goo'

overlay ('' placing 'Hello' from 4)          -- returns 'Hello'
overlay ('' placing 'Hello' from 4 for 0)    -- returns 'Hello'
overlay ('' placing 'Hello' from 4 for 20)   -- returns 'Hello'
----

.See also
<<fblangref40-scalarfuncs-replace>>

[[fblangref40-scalarfuncs-position]]
=== `POSITION()`

.Available in
DSQL, PSQL

.Result type
`INTEGER`

.Syntax
[listing,subs=+quotes]
----
  POSITION (_substr_ IN _string_)
| POSITION (_substr_, _string_ [, _startpos_])
----

[[fblangref40-funcs-tbl-position]]
.`POSITION` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|substr
|The substring whose position is to be searched for

|string
|The string which is to be searched

|startpos
|The position in _string_ where the search is to start
|===

Returns the (1-based) position of the first occurrence of a substring in a host string.
With the optional third argument, the search starts at a given offset, disregarding any matches that may occur earlier in the string.
If no match is found, the result is 0.

[NOTE]
====
* The optional third argument is only supported in the second syntax (comma syntax).
* The empty string is considered a substring of every string.
Therefore, if _substr_ is `''` (empty string) and _string_ is not `NULL`, the result is:
+
--
** 1 if _startpos_ is not given;
** _startpos_ if _startpos_ lies within _string_;
** 0 if _startpos_ lies beyond the end of _string_.
--
+ 
**Notice:** A bug in Firebird 2.1 - 2.1.3 and 2.5.0 causes `POSITION` to _always_ return 1 if _substr_ is the empty string.
This is fixed in 2.1.4 and 2.5.1.
* This function fully supports text ``BLOB``s of any size and character set.
====

[WARNING]
====
When used on a `BLOB`, this function may need to load the entire object into memory.
This may affect performance if huge ``BLOB``s are involved.
====

[[fblangref40-scalarfuncs-position-exmpl]]
==== `POSITION` Examples

[source]
----
position ('be' in 'To be or not to be')   -- returns 4
position ('be', 'To be or not to be')     -- returns 4
position ('be', 'To be or not to be', 4)  -- returns 4
position ('be', 'To be or not to be', 8)  -- returns 17
position ('be', 'To be or not to be', 18) -- returns 0
position ('be' in 'Alas, poor Yorick!')   -- returns 0
----

.See also
<<fblangref40-scalarfuncs-substring>>

[[fblangref40-scalarfuncs-replace]]
=== `REPLACE()`

.Available in
DSQL, PSQL

.Result type
`VARCHAR` or `BLOB`

.Syntax
[listing,subs=+quotes]
----
REPLACE (_str_, _find_, _repl_)
----

[[fblangref40-funcs-tbl-replace]]
.`REPLACE` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|str
|The string in which the replacement is to take place

|find
|The string to search for

|repl
|The replacement string
|===

Replaces all occurrences of a substring in a string.

* This function fully supports text ``BLOB``s of any length and character set.
* If any argument is a `BLOB`, the result is a `BLOB`.
Otherwise, the result is a `VARCHAR(__n__)` with _n_ calculated from the lengths of _str_, _find_ and _repl_ in such a way that even the maximum possible number of replacements won't overflow the field.
* If _find_ is the empty string, _str_ is returned unchanged.
* If _repl_ is the empty string, all occurrences of _find_ are deleted from _str_.
* If any argument is `NULL`, the result is always `NULL`, even if nothing would have been replaced.

[WARNING]
====
When used on a `BLOB`, this function may need to load the entire object into memory.
This may affect performance if huge ``BLOB``s are involved.
====

[[fblangref40-scalarfuncs-replace-exmpl]]
==== `REPLACE` Examples

[source]
----
replace ('Billy Wilder',  'il', 'oog') -- returns 'Boogly Woogder'
replace ('Billy Wilder',  'il',    '') -- returns 'Bly Wder'
replace ('Billy Wilder',  null, 'oog') -- returns NULL
replace ('Billy Wilder',  'il',  null) -- returns NULL
replace ('Billy Wilder', 'xyz',  null) -- returns NULL (!)
replace ('Billy Wilder', 'xyz', 'abc') -- returns 'Billy Wilder'
replace ('Billy Wilder',    '', 'abc') -- returns 'Billy Wilder'
----

.See also
<<fblangref40-scalarfuncs-overlay>>, <<fblangref40-scalarfuncs-substring>>, <<fblangref40-scalarfuncs-position>>, <<fblangref40-scalarfuncs-char-length>>

[[fblangref40-scalarfuncs-reverse]]
=== `REVERSE()`

.Available in
DSQL, PSQL

.Result type
`VARCHAR`

.Syntax
[listing,subs=+quotes]
----
REVERSE (_string_)
----

[[fblangref40-funcs-tbl-reverse]]
.`REVERSE` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|string
|An expression of a string type
|===

Returns a string backwards.

[[fblangref40-scalarfuncs-reverse-exmpl]]
==== `REVERSE` Examples
[source]
----
reverse ('spoonful')            -- returns 'lufnoops'
reverse ('Was it a cat I saw?') -- returns '?was I tac a ti saW'
----

[TIP]
====
This function comes in very handy if you want to group, search or order on string endings, e.g. when dealing with domain names or email addresses:

[source]
----
create index ix_people_email on people
  computed by (reverse(email));

select * from people
  where reverse(email) starting with reverse('.br');
----
====

[[fblangref40-scalarfuncs-right]]
=== `RIGHT()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`VARCHAR` or `BLOB`

.Syntax
[listingstring]
----
RIGHT (_string_, _length_)
----

[[fblangref40-funcs-tbl-right]]
.`RIGHT` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|string
|An expression of a string type

|length
|Integer.
Defines the number of characters to return
|===

Returns the rightmost part of the argument string.
The number of characters is given in the second argument. 

* This function supports text ``BLOB``s of any length, but has a bug in versions 2.1 - 2.1.3 and 2.5.0 that makes it fail with text ``BLOB``s larger than 1024 bytes that have a multi-byte character set.
This has been fixed in versions 2.1.4 and 2.5.1.
* If _string_ is a `BLOB`, the result is a `BLOB`.
Otherwise, the result is a `VARCHAR(__n__)` with _n_ the length of the input string.
* If the _length_ argument exceeds the string length, the input string is returned unchanged.
* If the _length_ argument is not a whole number, bankers' rounding (round-to-even) is applied, i.e. 0.5 becomes 0, 1.5 becomes 2, 2.5 becomes 2, 3.5 becomes 4, etc.

[WARNING]
====
When used on a `BLOB`, this function may need to load the entire object into memory.
This may affect performance if huge ``BLOB``s are involved.
====

.See also
<<fblangref40-scalarfuncs-left>>, <<fblangref40-scalarfuncs-substring>>

[[fblangref40-scalarfuncs-rpad]]
=== `RPAD()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`VARCHAR` or `BLOB`

.Syntax
[listing,subs=+quotes]
----
RPAD (_str_, _endlen_ [, _padstr_])
----

[[fblangref40-funcs-tbl-rpad]]
.`RPAD` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|str
|An expression of a string type

|endlen
|Output string length

|endlen
|The character or string to be used to pad the source string up to the specified length.
Default is space (`' '`)
|===

Right-pads a string with spaces or with a user-supplied string until a given length is reached.

* This function fully supports text ``BLOB``s of any length and character set.
* If _str_ is a `BLOB`, the result is a `BLOB`.
Otherwise, the result is a `VARCHAR(_endlen_)`.
* If _padstr_ is given and equals `''` (empty string), no padding takes place.
* If _endlen_ is less than the current string length, the string is truncated to _endlen_, even if _padstr_ is the empty string.

[NOTE]
====
In Firebird 2.1-2.1.3, all non-``BLOB`` results were of type `VARCHAR(32765)`, which made it advisable to cast them to a more modest size.
This is no longer the case.
====

[WARNING]
====
When used on a `BLOB`, this function may need to load the entire object into memory.
Although it does try to limit memory consumption, this may affect performance if huge ``BLOB``s are involved.
====

[[fblangref40-scalarfuncs-rpad-exmpl]]
==== `RPAD` Examples

[source]
----
rpad ('Hello', 12)               -- returns 'Hello       '
rpad ('Hello', 12, '-')          -- returns 'Hello-------'
rpad ('Hello', 12, '')           -- returns 'Hello'
rpad ('Hello', 12, 'abc')        -- returns 'Helloabcabca'
rpad ('Hello', 12, 'abcdefghij') -- returns 'Helloabcdefg'
rpad ('Hello', 2)                -- returns 'He'
rpad ('Hello', 2, '-')           -- returns 'He'
rpad ('Hello', 2, '')            -- returns 'He'
----

.See also
<<fblangref40-scalarfuncs-lpad>>

[[fblangref40-scalarfuncs-substring]]
=== `SUBSTRING()`

.Available in
DSQL, PSQL

.Result types
`VARCHAR` or `BLOB`

.Syntax
[listing,subs=+quotes]
----
SUBSTRING ( <substring-args> )

<substring-args> ::=
    _str_ FROM _startpos_ [FOR _length_]
  | _str_ SIMILAR <similar-pattern> ESCAPE <escape>

<similar-pattern> ::=
  <similar-pattern-R1>
  <escape> " <similar-pattern-R2> <escape> "
  <similar-pattern-R3>
----

[[fblangref40-funcs-tbl-substring]]
.`SUBSTRING` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|str
|An expression of a string type

|startpos
|Integer expression, the position from which to start retrieving the substring

|length
|The number of characters to retrieve after the _startpos_

|similar-pattern
|SQL regular expression pattern to search for the substring

|escape
|Escape character
|===

Returns a string's substring starting at the given position, either to the end of the string or with a given length, or extracts a substring using an SQL regular expression pattern.

If any argument is `NULL`, the result is also `NULL`.

[WARNING]
====
When used on a `BLOB`, this function may need to load the entire object into memory.
Although it does try to limit memory consumption, this may affect performance if huge ``BLOB``s are involved.
====

[[fblangref40-scalarfuncs-substring-pos]]
==== Positional `SUBSTRING`

In its simple, positional form (with `FROM`), this function returns the substring starting at character position _startpos_ (the first position being 1).
Without the `FOR` argument, it returns all the remaining characters in the string.
With `FOR`, it returns _length_ characters or the remainder of the string, whichever is shorter.

The function fully supports binary and text ``BLOB``s of any length, and with any character set.
If _str_ is a `BLOB`, the result is also a `BLOB`.
For any other argument type, the result is a `VARCHAR`.

For non-``BLOB`` arguments, the width of the result field is always equal to the length of _str_, regardless of _startpos_ and _length_.
So, `substring('pinhead' from 4 for 2)` will return a `VARCHAR(7)` containing the string `'he'`.

.Example
[source]
----
insert into AbbrNames(AbbrName)
  select substring(LongName from 1 for 3) from LongNames
----

[[fblangref40-scalarfuncs-substring-regexp]]
==== Regular Expression `SUBSTRING`

In the regular expression form (with `SIMILAR`), the `SUBSTRING` function returns part of the string matching an SQL regular expression pattern.
If no match is found, `NULL` is returned.

The `SIMILAR` pattern is formed from three SQL regular expression patterns, _R1_, _R2_ and _R3_.
The entire pattern takes the form of `R1 || '__<escape>__"' || R2 || '__<escape>__"' || R3`, where _<escape>_ is the escape character defined in the `ESCAPE` clause.
_R2_ is the pattern that matches the substring to extract, and is enclosed between escaped double quotes (`__<escape>__"`, e.g. "```++#"++```" with escape character '```++#++```').
_R1_ matches the prefix of the string, and _R3_ the suffix of the string.
Both _R1_ and _R3_ are optional (they can be empty), but the pattern must match the entire string.
In other words, it is not sufficient to specify a pattern that only finds the substring to extract.

[TIP]
====
The escaped double quotes around _R2_ can be compared to defining a single capture group in more common regular expression syntax like PCRE.
That is, the full pattern is equivalent to `__R1__(__R2__)__R3__`, which must match the entire input string, and the capture group is the substring to be returned.
====

[NOTE]
====
If any one of _R1_, _R2_, or _R3_ is not a zero-length string and does not have the format of an SQL regular expression, then an exception is raised.
====

The full SQL regular expression format is described in <<fblangref40-commons-syntaxregex,Syntax: SQL Regular Expressions>>

.Examples
[source]
----
substring('abcabc' similar 'a#"bcab#"c' escape '#')  -- bcab
substring('abcabc' similar 'a#"%#"c' escape '#')     -- bcab
substring('abcabc' similar '_#"%#"_' escape '#')     -- bcab
substring('abcabc' similar '#"(abc)*#"' escape '#')  -- abcabc
substring('abcabc' similar '#"abc#"' escape '#')     -- <null>
----

.See also
<<fblangref40-scalarfuncs-position>>, <<fblangref40-scalarfuncs-left>>, <<fblangref40-scalarfuncs-right>>, <<fblangref40-scalarfuncs-char-length>>, <<fblangref40-commons-predsimilarto,`SIMILAR TO`>>

[[fblangref40-scalarfuncs-trim]]
=== `TRIM()`

.Available in
DSQL, PSQL

.Result type
`VARCHAR` or `BLOB`

.Syntax
[listing,subs=+quotes]
----
TRIM ([<adjust>] _str_)

<adjust> ::=  {[<where>] [_what_]} FROM

<where> ::=  BOTH | LEADING | TRAILING
----

[[fblangref40-funcs-tbl-trim]]
.`TRIM` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|str
|An expression of a string type

|where
|The position the substring is to be removed from -- `BOTH` {vbar} `LEADING` {vbar} `TRAILING`.
`BOTH` is the default

|what
|The substring that should be removed (multiple times if there are several matches) from the beginning, the end, or both sides of the input string _str_.
By default it is space (`' '`)
|===

Removes leading and/or trailing spaces (or optionally other strings) from the input string.
Since Firebird 2.1 this function fully supports text ``BLOB``s of any length and character set.

[NOTE]
====
* If _str_ is a `BLOB`, the result is a `BLOB`.
Otherwise, it is a `VARCHAR(__n__)` with _n_ the formal length of _str_.
* Since Firebird 3.0, the maximum size of _what_ -- if a `BLOB -- was increased to 4GB, in previous versions the value of _what_ could not exceed 32767 bytes.
====

[WARNING]
====
When used on a `BLOB`, this function may need to load the entire object into memory.
This may affect performance if huge ``BLOB``s are involved.
====

[[fblangref40-scalarfuncs-trim-exmpl]]
==== `TRIM` Examples
[source]
----
select trim ('  Waste no space   ') from rdb$database
-- returns 'Waste no space'

select trim (leading from '  Waste no space   ') from rdb$database
-- returns 'Waste no space   '

select trim (leading '.' from '  Waste no space   ') from rdb$database
-- returns '  Waste no space   '

select trim (trailing '!' from 'Help!!!!') from rdb$database
-- returns 'Help'

select trim ('la' from 'lalala I love you Ella') from rdb$database
-- returns ' I love you El'

select trim ('la' from 'Lalala I love you Ella') from rdb$database
-- returns 'Lalala I love you El'
----

[[fblangref40-scalarfuncs-upper]]
=== `UPPER()`

.Available in
DSQL, ESQL, PSQL

.Result type
`(VAR)CHAR` or `BLOB`

.Syntax
[listing,subs=+quotes]
----
UPPER (_str_)
----

[[fblangref40-funcs-tbl-upper]]
.`UPPER` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|str
|An expression of a string type
|===

Returns the upper-case equivalent of the input string.
The exact result depends on the character set.
With `ASCII` or `NONE` for instance, only ASCII characters are uppercased;
with `OCTETS`, the entire string is returned unchanged.
Since Firebird 2.1 this function also fully supports text ``BLOB``s of any length and character set.

[[fblangref40-scalarfuncs-upper-exmpl]]
==== `UPPER` Examples

[source]
----
select upper(_iso8859_1 'Débâcle')
from rdb$database
-- returns 'DÉBÂCLE' (before Firebird 2.0: 'DéBâCLE')

select upper(_iso8859_1 'Débâcle' collate fr_fr)
from rdb$database
-- returns 'DEBACLE', following French uppercasing rules
----

.See also
<<fblangref40-scalarfuncs-lower>>

[[fblangref40-functions-datetime]]
== Date and Time Functions

[[fblangref40-scalarfuncs-dateadd]]
=== `DATEADD()`

.Available in
DSQL, PSQL

.Result type
`DATE`, `TIME` or `TIMESTAMP`

.Syntax
[listing,subs=+quotes]
----
DATEADD (<args>)

<args> ::=
    <amount> <unit> TO <datetime>
  | <unit>, <amount>, <datetime>

<amount> ::= _an integer expression (negative to subtract)_
<unit> ::=
    YEAR | MONTH | WEEK | DAY
  | HOUR | MINUTE | SECOND | MILLISECOND
<datetime> ::= _a DATE, TIME or TIMESTAMP expression_
----

[[fblangref40-funcs-tbl-dateadd]]
.`DATEADD` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|amount
|An integer expression of the `SMALLINT`, `INTEGER` or `BIGINT` type.
For unit `MILLISECOND`, the type is `NUMERIC(18, 1)`.
A negative value is subtracted.

|unit
|Date/time unit

|datetime
|An expression of the `DATE`, `TIME` or `TIMESTAMP` type
|===

Adds the specified number of years, months, weeks, days, hours, minutes, seconds or milliseconds to a date/time value.

* The result type is determined by the third argument.
* With `TIMESTAMP` and `DATE` arguments, all units can be used.
* With `TIME` arguments, only `HOUR`, `MINUTE`, `SECOND` and `MILLISECOND` can be used.

[[fblangref40-funcs-tbl-dateadd-exmpl]]
==== Examples of `DATEADD`

[source]
----
dateadd (28 day to current_date)
dateadd (-6 hour to current_time)
dateadd (month, 9, DateOfConception)
dateadd (-38 week to DateOfBirth)
dateadd (minute, 90, time 'now')
dateadd (? year to date '11-Sep-1973')
----

[source]
----
select
  cast(dateadd(-1 * extract(millisecond from ts) millisecond to ts) as varchar(30)) as t,
  extract(millisecond from ts) as ms
from (
  select timestamp '2014-06-09 13:50:17.4971' as ts
  from rdb$database
) a
----

[listing]
----
T                        MS
------------------------ ------
2014-06-09 13:50:17.0000  497.1
----

.See also
<<fblangref40-scalarfuncs-datediff>>, <<fblangref40-datatypes-datetimeops,Operations Using Date and Time Values>>

[[fblangref40-scalarfuncs-datediff]]
=== `DATEDIFF()`

.Available in
DSQL, PSQL

.Result type
`BIGINT`

.Syntax
[listing,subs=+quotes]
----
DATEDIFF (<args>)

<args> ::=
    <unit> FROM <moment1> TO <moment2>
  | <unit>, <moment1>, <moment2>

<unit> ::=
    YEAR | MONTH | WEEK | DAY
  | HOUR | MINUTE | SECOND | MILLISECOND
<momentN> ::= _a DATE, TIME or TIMESTAMP expression_
----

[[fblangref40-funcs-tbl-datediff]]
.`DATEDIFF` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|unit
|Date/time unit

|moment1
|An expression of the `DATE`, `TIME` or `TIMESTAMP` type

|moment2
|An expression of the `DATE`, `TIME` or `TIMESTAMP` type
|===

Returns the number of years, months, weeks, days, hours, minutes, seconds or milliseconds elapsed between two date/time values.
(The `WEEK` unit is new in 2.5.) 

* `DATE` and `TIMESTAMP` arguments can be combined.
No other mixes are allowed.
* With `TIMESTAMP` and `DATE` arguments, all units can be used.
(Prior to Firebird 2.5, units smaller than `DAY` were disallowed for ``DATE``s.)
* With `TIME` arguments, only `HOUR`, `MINUTE`, `SECOND` and `MILLISECOND` can be used.

.Computation
* `DATEDIFF` doesn't look at any smaller units than the one specified in the first argument.
As a result,
** `datediff (year, date '1-Jan-2009', date '31-Dec-2009')` returns 0, but
** `datediff (year, date '31-Dec-2009', date '1-Jan-2010')` returns 1
* It does, however, look at all the _bigger_ units. So:
** `datediff (day, date '26-Jun-1908', date '11-Sep-1973')` returns 23818
* A negative result value indicates that _moment2_ lies before _moment1_.

[[fblangref40-scalarfuncs-datediff-exmpl]]
==== `DATEDIFF` Examples

[source]
----
datediff (hour from current_timestamp to timestamp '12-Jun-2059 06:00')
datediff (minute from time '0:00' to current_time)
datediff (month, current_date, date '1-1-1900')
datediff (day from current_date to cast(? as date))
----

.See also
<<fblangref40-scalarfuncs-dateadd>>, <<fblangref40-datatypes-datetimeops,Operations Using Date and Time Values>>

[[fblangref40-scalarfuncs-extract]]
=== `EXTRACT()`

.Available in
DSQL, ESQL, PSQL

.Result type
`SMALLINT` or `NUMERIC`

.Syntax
[listing,subs=+quotes]
----
EXTRACT (<part> FROM <datetime>)

<part> ::=
    YEAR | MONTH | WEEK
  | DAY | WEEKDAY | YEARDAY
  | HOUR | MINUTE | SECOND | MILLISECOND
<datetime> ::= _a DATE, TIME or TIMESTAMP expression_
----

[[fblangref40-funcs-tbl-extract]]
.`EXTRACT` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|part
|Date/time unit

|datetime
|An expression of the `DATE`, `TIME` or `TIMESTAMP` type
|===

Extracts and returns an element from a `DATE`, `TIME` or `TIMESTAMP` expression.
This function was already added in InterBase 6, but not documented in the _Language Reference_ at the time.

[[fblangref40-scalarfuncs-extract-types]]
==== Returned Data Types and Ranges

The returned data types and possible ranges are shown in the table below.
If you try to extract a part that isn't present in the date/time argument (e.g. `SECOND` from a `DATE` or `YEAR` from a `TIME`), an error occurs.

[[fblangref40-tbl-extractranges]]
.Types and ranges of `EXTRACT` results
[cols="<1m,<1m,<1,<2", options="header"]
|===
| Part
| Type
| Range
| Comment

|YEAR
|SMALLINT
|1-9999
|{nbsp}

|MONTH
|SMALLINT
|1-12
|{nbsp}

|WEEK
|SMALLINT
|1-53
|{nbsp}

|DAY
|SMALLINT
|1-31
|{nbsp}

|WEEKDAY
|SMALLINT
|0-6
|0 = Sunday

|YEARDAY
|SMALLINT
|0-365
|0 = January 1

|HOUR
|SMALLINT
|0-23
|{nbsp}

|MINUTE
|SMALLINT
|0-59
|{nbsp}

|SECOND
|NUMERIC(9,4)
|0.0000-59.9999
|includes millisecond as fraction

|MILLISECOND
|NUMERIC(9,1)
|0.0-999.9
|broken in 2.1, 2.1.1
|===

[[fblangref40-scalarfuncs-extract-millisecond]]
==== `MILLISECOND`

Firebird 2.1 and up support extraction of the millisecond from a `TIME` or `TIMESTAMP`.
The datatype returned is `NUMERIC(9,1)`.

[NOTE]
====
If you extract the millisecond from <<fblangref40-contextvars-current-time>>, be aware that this variable defaults to seconds precision, so the result will always be 0.
Extract from `CURRENT_TIME(3)` or <<fblangref40-contextvars-current-timestamp>> to get milliseconds precision.
====

[[fblangref40-scalarfuncs-extract-week]]
==== `WEEK`

Firebird 2.1 and up support extraction of the ISO-8601 week number from a `DATE` or `TIMESTAMP`.
ISO-8601 weeks start on a Monday and always have the full seven days.
Week 1 is the first week that has a majority (at least 4) of its days in the new year.
The first 1-3 days of the year may belong to the last week (52 or 53) of the previous year.
Likewise, a year's final 1-3 days may belong to week 1 of the following year.

[CAUTION]
====
Be careful when combining `WEEK` and `YEAR` results.
For instance, 30 December 2008 lies in week 1 of 2009, so `extract(week from date '30 Dec 2008')` returns 1.
However, extracting `YEAR` always gives the calendar year, which is 2008.
In this case, `WEEK` and `YEAR` are at odds with each other.
The same happens when the first days of January belong to the last week of the previous year.

Please also notice that `WEEKDAY` is _not_ ISO-8601 compliant: it returns 0 for Sunday, whereas ISO-8601 specifies 7.
====

.See also
<<fblangref40-datatypes-datetime,Data Types for Dates and Times>>

[[fblangref40-functions-casting]]
== Type Casting Functions

[[fblangref40-scalarfuncs-cast]]
=== `CAST()`

.Available in
DSQL, ESQL, PSQL

.Result type
As specified by _target_type_

.Syntax
[listing,subs="+quotes,macros"]
----
CAST (<expression> AS <target_type>)

<target_type> ::= <domain_or_non_array_type> | <array_datatype>

<domain_or_non_array_type> ::=
  !! See <<fblangref40-datatypes-syntax-scalar-syntax,Scalar Data Types Syntax>> !!

<array_datatype> ::=
  !! See <<fblangref40-datatypes-syntax-array,Array Data Types Syntax>> !!
----

[[fblangref40-funcs-tbl-cast]]
.`CAST` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expression
|SQL expression

|sql_datatype
|SQL data type
|===

`CAST` converts an expression to the desired datatype or domain.
If the conversion is not possible, an error is raised.

.Casting ``BLOB``s
Successful casting to and from ``BLOB``s is possible since Firebird 2.1.

[[fblangref40-scalarfuncs-shortcast]]
==== "`Shorthand`" Syntax

Alternative syntax, supported only when casting a string literal to a `DATE`, `TIME` or `TIMESTAMP`:

[source]
----
datatype 'date/timestring'
----

This syntax was already available in InterBase, but was never properly documented.
In the SQL standard, this feature is called "`datetime literals`".

[NOTE]
====
The short syntax is evaluated immediately at parse time, causing the value to stay the same until the statement is unprepared.
For datetime literals like `'12-Oct-2012'` this makes no difference.
For the pseudo-variables `'NOW'`, `'YESTERDAY'`, `'TODAY'` and `'TOMORROW'`, this may not be what you want.
If you need the value to be evaluated at every call, use the full `CAST()` syntax.

Firebird 4 will disallow the use of `'NOW'`, `'YESTERDAY'` and `'TOMORROW'` in the shorthand cast, and only allow literals defining a fixed moment in time.
====

[[fblangref40-scalarfuncs-cast-conv]]
==== Allowed Type Conversions

The following table shows the type conversions possible with `CAST`.

[[fblangref40-tbl-cast]]
.Possible Type-castings with `CAST`
[%autowidth,cols="2*", options="header", stripes="none"]
|===
| From
| To

|Numeric types
|Numeric types +
`[VAR]CHAR` +
`BLOB`

|`[VAR]CHAR` +
`BLOB`
| `[VAR]CHAR` +
`BLOB` +
Numeric types +
`DATE` +
`TIME` +
`TIMESTAMP`

|`DATE` +
`TIME`
|`[VAR]CHAR` +
`BLOB` +
`TIMESTAMP`

|`TIMESTAMP`
|`[VAR]CHAR` +
`BLOB` +
`DATE` +
`TIME`
|===

Keep in mind that sometimes information is lost, for instance when you cast a `TIMESTAMP` to a `DATE`.
Also, the fact that types are ``CAST``-compatible is in itself no guarantee that a conversion will succeed.
"```CAST(123456789 as SMALLINT)```" will definitely result in an error, as will "```CAST('Judgement Day' as DATE)```".

[[fblangref40-scalarfuncs-cast-params]]
==== Casting Parameters

Since Firebird 2.0, you can cast statement parameters to a datatype:

[source]
----
cast (? as integer)
----

This gives you control over the type of the parameter set up by the engine.
Please notice that with statement parameters, you always need a full-syntax cast -- shorthand casts are not supported.

[[fblangref40-scalarfuncs-cast-domain]]
==== Casting to a Domain or its Type

Firebird 2.1 and above support casting to a domain or its base type.
When casting to a domain, any constraints (`NOT NULL` and/or `CHECK`) declared for the domain must be satisfied, or the cast will fail.
Please be aware that a `CHECK` passes if it evaluates to `TRUE` _or_ `NULL`!
So, given the following statements:

[source]
----
create domain quint as int check (value >= 5000);
select cast (2000 as quint) from rdb$database;     -- <1>
select cast (8000 as quint) from rdb$database;     -- <2>
select cast (null as quint) from rdb$database;     -- <3>
----

only cast number _1_ will result in an error.

When the `TYPE OF` modifier is used, the expression is cast to the base type of the domain, ignoring any constraints.
With domain `quint` defined as above, the following two casts are equivalent and will both succeed:

[source]
----
select cast (2000 as type of quint) from rdb$database;
select cast (2000 as int) from rdb$database;
----

If `TYPE OF` is used with a `(VAR)CHAR` type, its character set and collation are retained:

[source]
----
create domain iso20 varchar(20) character set iso8859_1;
create domain dunl20 varchar(20) character set iso8859_1 collate du_nl;
create table zinnen (zin varchar(20));
commit;
insert into zinnen values ('Deze');
insert into zinnen values ('Die');
insert into zinnen values ('die');
insert into zinnen values ('deze');

select cast(zin as type of iso20) from zinnen order by 1;
-- returns Deze -> Die -> deze -> die

select cast(zin as type of dunl20) from zinnen order by 1;
-- returns deze -> Deze -> die -> Die
----

[WARNING]
====
If a domain's definition is changed, existing ``CAST``s to that domain or its type may become invalid.
If these ``CAST``s occur in PSQL modules, their invalidation may be detected.
See the note <<fblangref40-appx01-supp-rdb-validblr,[ref]_The RDB$VALID_BLR field_>>, in Appendix A.
====

[[fblangref40-scalarfuncs-cast-coltype]]
==== Casting to a Column's Type

In Firebird 2.5 and above, it is possible to cast expressions to the type of an existing table or view column.
Only the type itself is used;
in the case of string types, this includes the character set but not the collation.
Constraints and default values of the source column are not applied.

[source]
----
create table ttt (
  s varchar(40) character set utf8 collate unicode_ci_ai
);
commit;

select cast ('Jag har många vänner' as type of column ttt.s)
from rdb$database;
----

.Warnings
[WARNING]
====
If a column's definition is altered, existing ``CAST``s to that column's type may become invalid.
If these ``CAST``s occur in PSQL modules, their invalidation may be detected.
See the note <<fblangref40-appx01-supp-rdb-validblr,[ref]_The RDB$VALID_BLR field_>>, in Appendix A.
====

[[fblangref40-scalarfuncs-cast-exmpl]]
==== Cast Examples

A full-syntax cast:

[source]
----
select cast ('12' || '-June-' || '1959' as date) from rdb$database
----

A shorthand string-to-date cast:

[source]
----
update People set AgeCat = 'Old'
  where BirthDate < date '1-Jan-1943'
----

Notice that you can drop even the shorthand cast from the example above, as the engine will understand from the context (comparison to a `DATE` field) how to interpret the string:

[source]
----
update People set AgeCat = 'Old'
  where BirthDate < '1-Jan-1943'
----

But this is not always possible.
The cast below cannot be dropped, otherwise the engine would find itself with an integer to be subtracted from a string:

[source]
----
select date 'today' - 7 from rdb$database
----

[[fblangref40-functions-bitwise]]
== Bitwise Functions

[[fblangref40-scalarfuncs-bin-and]]
=== `BIN_AND()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`SMALLINT`, `INTEGER` or `BIGINT`

[NOTE]
====
`SMALLINT` result is returned only if all the arguments are explicit ``SMALLINT``s or `NUMERIC(__n__, 0)` with _n_ +<=+ 4;
otherwise small integers return an `INTEGER` result.
====

.Syntax
[listing,subs=+quotes]
----
BIN_AND (_number_, _number_ [, _number_ ...])
----

[[fblangref40-funcs-tbl-binand]]
.`BIN_AND` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|Any integer number (literal, smallint/integer/bigint, numeric/decimal with scale 0)
|===

Returns the result of the bitwise _AND_ operation on the argument(s).

.See also
<<fblangref40-scalarfuncs-bin-or>>, <<fblangref40-scalarfuncs-bin-xor>>

[[fblangref40-scalarfuncs-bin-not]]
=== `BIN_NOT()`

.Available in
DSQL, PSQL

.Result type
`SMALLINT`, `INTEGER` or `BIGINT`

[NOTE]
====
`SMALLINT` result is returned only if all the arguments are explicit ``SMALLINT``s or `NUMERIC(__n__, 0)` with _n_ +<=+ 4;
otherwise small integers return an `INTEGER` result.
====

.Syntax
[listing,subs=+quotes]
----
BIN_NOT (_number_)
----

[[fblangref40-funcs-tbl-binnot]]
.`BIN_NOT` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|Any integer number (literal, smallint/integer/bigint, numeric/decimal with scale 0)
|===

Returns the result of the bitwise _NOT_ operation on the argument, i.e. _one's complement_.

.See also
<<fblangref40-scalarfuncs-bin-or>>, <<fblangref40-scalarfuncs-bin-xor>> and others in this set.

[[fblangref40-scalarfuncs-bin-or]]
=== `BIN_OR()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`SMALLINT`, `INTEGER` or `BIGINT`

[NOTE]
====
`SMALLINT` result is returned only if all the arguments are explicit ``SMALLINT``s or `NUMERIC(__n__, 0)` with _n_ +<=+ 4;
otherwise small integers return an `INTEGER` result.
====

.Syntax
[listing,subs=+quotes]
----
BIN_OR (_number_, _number_ [, _number_ ...])
----

[[fblangref40-funcs-tbl-binor]]
.`BIN_OR` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|Any integer number (literal, smallint/integer/bigint, numeric/decimal with scale 0)
|===

Returns the result of the bitwise _OR_ operation on the argument(s).

.See also
<<fblangref40-scalarfuncs-bin-and>>, <<fblangref40-scalarfuncs-bin-xor>>

[[fblangref40-scalarfuncs-bin-shl]]
=== `BIN_SHL()`

.Available in
DSQL, PSQL

.Result type
`BIGINT`

.Syntax
[listing,subs=+quotes]
----
BIN_SHL (_number_, _shift_)
----

[[fblangref40-funcs-tbl-binshl]]
.`BIN_SHL` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|A number of an integer type

|shift
|The number of bits the number value is shifted by
|===

Returns the first argument bitwise left-shifted by the second argument, i.e. `a << b` or `a·2^b^`.

.See also
<<fblangref40-scalarfuncs-bin-shr>>

[[fblangref40-scalarfuncs-bin-shr]]
=== `BIN_SHR()`

.Available in
DSQL, PSQL

.Result type
`BIGINT`

.Syntax
[listing,subs=+quotes]
----
BIN_SHR (_number_, _shift_)
----

[[fblangref40-funcs-tbl-binshr]]
.`BIN_SHR` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|A number of an integer type

|shift
|The number of bits the number value is shifted by
|===

Returns the first argument bitwise right-shifted by the second argument, i.e. `a >> b` or `a/2^b^`.

* The operation performed is an arithmetic right shift (SAR), meaning that the sign of the first operand is always preserved.

.See also
<<fblangref40-scalarfuncs-bin-shl>>

[[fblangref40-scalarfuncs-bin-xor]]
=== `BIN_XOR()`

.Available in
DSQL, PSQL

.Possible name conflict
YES -> <<fblangref40-functions-nameclashes,Read details>>

.Result type
`SMALLINT`, `INTEGER` or `BIGINT`

[NOTE]
====
`SMALLINT` result is returned only if all the arguments are explicit ``SMALLINT``s or `NUMERIC(__n__, 0)` with _n_ +<=+ 4;
otherwise small integers return an `INTEGER` result.
====

.Syntax
[listing,subs=+quotes]
----
BIN_XOR (_number_, _number_ [, _number_ ...])
----

[[fblangref40-funcs-tbl-binxor]]
.`BIN_XOR` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|number
|Any integer number (literal, smallint/integer/bigint, numeric/decimal with scale 0)
|===

Returns the result of the bitwise _XOR_ operation on the argument(s).

.See also
<<fblangref40-scalarfuncs-bin-and>>, <<fblangref40-scalarfuncs-bin-or>>

[[fblangref40-functions-uuid]]
== UUID Functions

[[fblangref40-scalarfuncs-char-to-uuid]]
=== `CHAR_TO_UUID()`

.Available in
DSQL, PSQL

.Result type
`CHAR(16) CHARACTER SET OCTETS`

.Syntax
[listing,subs=+quotes]
----
CHAR_TO_UUID (_ascii_uuid_)
----

[[fblangref40-funcs-tbl-char-to-uuid]]
.`CHAR_TO_UUID` Function Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|ascii_uuid
|A 36-character representation of UUID.
'```-```' (hyphen) in positions 9, 14, 19 and 24;
valid hexadecimal digits in any other positions, e.g. 'A0bF4E45-3029-2a44-D493-4998c9b439A3'
|===

Converts a human-readable 36-char UUID string to the corresponding 16-byte UUID.

[[fblangref40-scalarfuncs-char-to-uuid-exmpl]]
==== `CHAR_TO_UUID` Examples

[source]
----
select char_to_uuid('A0bF4E45-3029-2a44-D493-4998c9b439A3') from rdb$database
-- returns A0BF4E4530292A44D4934998C9B439A3 (16-byte string)

select char_to_uuid('A0bF4E45-3029-2A44-X493-4998c9b439A3') from rdb$database
-- error: -Human readable UUID argument for CHAR_TO_UUID must
--         have hex digit at position 20 instead of "X (ASCII 88)"
----

.See also
<<fblangref40-scalarfuncs-uuid-to-char>>, <<fblangref40-scalarfuncs-gen-uuid>>

[[fblangref40-scalarfuncs-gen-uuid]]
=== `GEN_UUID()`

.Available in
DSQL, PSQL

.Result type
`CHAR(16) CHARACTER SET OCTETS`

.Syntax
[listing]
----
GEN_UUID ()
----

Returns a universally unique ID as a 16-byte character string.

[[fblangref40-scalarfuncs-gen-uuid-exmpl]]
==== `GEN_UUID` Example

[source]
----
select gen_uuid() from rdb$database
-- returns e.g. 017347BFE212B2479C00FA4323B36320 (16-byte string)
----

.See also
<<fblangref40-scalarfuncs-uuid-to-char>>, <<fblangref40-scalarfuncs-char-to-uuid>>

[[fblangref40-scalarfuncs-uuid-to-char]]
=== `UUID_TO_CHAR()`

.Available in
DSQL, PSQL

.Result type
`CHAR(36)`

.Syntax
[listing,subs=+quotes]
----
UUID_TO_CHAR (_uuid_)
----

[[fblangref40-funcs-tbl-uuid-to-char]]
.`UUID_TO_CHAR` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|uuid
|16-byte UUID
|===

Converts a 16-byte UUID to its 36-character, human-readable ASCII representation.

[[fblangref40-scalarfuncs-uuid-to-char-exmpl]]
==== `UUID_TO_CHAR` Examples

[source]
----
select uuid_to_char(x'876C45F4569B320DBCB4735AC3509E5F') from rdb$database
-- returns '876C45F4-569B-320D-BCB4-735AC3509E5F'

select uuid_to_char(gen_uuid()) from rdb$database
-- returns e.g. '680D946B-45FF-DB4E-B103-BB5711529B86'

select uuid_to_char('Firebird swings!') from rdb$database
-- returns '46697265-6269-7264-2073-77696E677321'
----

.See also
<<fblangref40-scalarfuncs-char-to-uuid>>, <<fblangref40-scalarfuncs-gen-uuid>>

[[fblangref40-functions-generators]]
== Functions for Sequences (Generators)

[[fblangref40-scalarfuncs-gen-id]]
=== `GEN_ID()`

.Available in
DSQL, ESQL, PSQL

.Result type
`BIGINT`

.Syntax
[listing,subs=+quotes]
----
GEN_ID (_generator-name_, _step_)
----

[[fblangref40-funcs-tbl-gen-id]]
.`GEN_ID` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|generator-name
|Name of a generator (sequence) that exists.
If it has been defined in double quotes with a case-sensitive identifier, it must be used in the same form unless the name is all upper-case.

|step
|An integer expression
|===

Increments a generator or sequence and returns its new value.
If step equals 0, the function will leave the value of the generator unchanged and return its current value.
 
* From Firebird 2.0 onward, the SQL-compliant <<fblangref40-commons-conditional-nxtvlufor,`NEXT VALUE FOR`>> syntax is preferred, except when an increment other than 1 is needed.

[WARNING]
====
If the value of the step parameter is less than zero, it will decrease the value of the generator.
Attention! You should be extremely cautious with such manipulations in the database, as they could compromise data integrity.
====

[[fblangref40-scalarfuncs-gen-id-exmpl]]
==== `GEN_ID` Example

[source]
----
new.rec_id = gen_id(gen_recnum, 1);
----

.See also
<<fblangref40-commons-conditional-nxtvlufor,`NEXT VALUE FOR`>>, <<fblangref40-ddl-sequence-create,`CREATE SEQUENCE (GENERATOR)`>>

[[fblangref40-functions-conditional]]
== Conditional Functions

[[fblangref40-scalarfuncs-coalesce]]
=== `COALESCE()`

.Available in
DSQL, PSQL

.Result type
Depends on input

.Syntax
[listing]
----
COALESCE (<exp1>, <exp2> [, <expN> ... ])
----

[[fblangref40-funcs-tbl-coalesce]]
.`COALESCE` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|exp1, exp2 ... expN
|A list of expressions of any compatible types
|===

The `COALESCE` function takes two or more arguments and returns the value of the first non-``NULL`` argument.
If all the arguments evaluate to `NULL`, the result is `NULL`.

[[fblangref40-scalarfuncs-coalesce-exmpl]]
==== `COALESCE` Examples

This example picks the `Nickname` from the `Persons` table.
If it happens to be `NULL`, it goes on to `FirstName`.
If that too is `NULL`, "```'Mr./Mrs.'```" is used.
Finally, it adds the family name.
All in all, it tries to use the available data to compose a full name that is as informal as possible.
Notice that this scheme only works if absent nicknames and first names are really `NULL`: if one of them is an empty string instead, `COALESCE` will happily return that to the caller.

[source]
----
select
  coalesce (Nickname, FirstName, 'Mr./Mrs.') || ' ' || LastName
    as FullName
from Persons
----

.See also
<<fblangref40-scalarfuncs-iif>>, <<fblangref40-scalarfuncs-nullif>>, <<fblangref40-commons-conditional-case,`CASE`>>

[[fblangref40-scalarfuncs-decode]]
=== `DECODE()`

.Available in
DSQL, PSQL

.Result type
Depends on input

.Syntax
[listing]
----
DECODE(<testexpr>,
  <expr1>, <result1>
  [<expr2>, <result2> …]
  [, <defaultresult>])
----

The equivalent `CASE` construct:

[listing]
----
CASE <testexpr>
  WHEN <expr1> THEN <result1>
  [WHEN <expr2> THEN <result2> …]
  [ELSE <defaultresult>]
END
----

[[fblangref40-funcs-tbl-decode]]
.`DECODE` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|testexpr
|An expression of any compatible type that is compared to the expressions expr1, expr2 ... exprN

|expr1, expr2, ... exprN
|Expressions of any compatible types, to which the _testexpr_ expression is compared

|result1, result2, ... resultN
|Returned values of any type

|defaultresult
|The expression to be returned if none of the conditions is met
|===

`DECODE` is a shorthand for the so-called <<fblangref40-commons-conditional-case-simple,"`simple ``CASE```" construct>>, in which a given expression is compared to a number of other expressions until a match is found.
The result is determined by the value listed after the matching expression.
If no match is found, the default result is returned, if present.
Otherwise, `NULL` is returned.

[CAUTION]
====
Matching is done with the '```=```' operator, so if _testexpr_ is `NULL`, it won't match any of the __expr__s, not even those that are `NULL`.
====

[[fblangref40-scalarfuncs-decode-exmpl]]
==== `DECODE` Examples

[source]
----
select name,
  age,
  decode(upper(sex),
         'M', 'Male',
         'F', 'Female',
         'Unknown'),
  religion
from people
----

.See also
<<fblangref40-commons-conditional-case,`CASE`>>, <<fblangref40-commons-conditional-case-simple,Simple `CASE`>>

[[fblangref40-scalarfuncs-iif]]
=== `IIF()`

.Available in
DSQL, PSQL

.Result type
Depends on input

.Syntax
[listing,subs=+quotes]
----
IIF (<condition>, _ResultT_, _ResultF_)
----

[[fblangref40-funcs-tbl-iif]]
.`IIF` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|condition
|A true{vbar}false expression

|resultT
|The value returned if the condition is true

|resultF
|The value returned if the condition is false
|===

`IIF` takes three arguments.
If the first evaluates to `true`, the second argument is returned;
otherwise the third is returned.

`IIF` could be likened to the ternary "```?:```" operator in C-like languages.

[NOTE]
====
`IIF(<Cond>, __Result1__, __Result2__)` is a shorthand for "```CASE WHEN <Cond> THEN __Result1__ ELSE __Result2__ END```".
====

[[fblangref40-scalarfuncs-iif-exmpl]]
==== `IIF` Examples

[source]
----
select iif( sex = 'M', 'Sir', 'Madam' ) from Customers
----

.See also
<<fblangref40-commons-conditional-case,`CASE`>>, <<fblangref40-scalarfuncs-decode>>

[[fblangref40-scalarfuncs-maxvalue]]
=== `MAXVALUE()`

.Available in
DSQL, PSQL

.Result type
Varies according to input -- result will be of the same data type as the first expression in the list (_expr1_).

.Syntax
[listing]
----
MAXVALUE (<expr1> [, ... , <exprN> ])
----

[[fblangref40-funcs-tbl-maxvalue]]
.`MAXVALUE` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr1 ... exprN
|List of expressions of compatible types
|===

Returns the maximum value from a list of numerical, string, or date/time expressions.
This function fully supports text ``BLOB``s of any length and character set. 

If one or more expressions resolve to `NULL`, `MAXVALUE` returns `NULL`.
This behaviour differs from the aggregate function `MAX`.

[[fblangref40-scalarfuncs-maxvalue-exmpl]]
==== `MAXVALUE` Examples

[source]
----
SELECT MAXVALUE(PRICE_1, PRICE_2) AS PRICE
  FROM PRICELIST
----

.See also
<<fblangref40-scalarfuncs-minvalue>>

[[fblangref40-scalarfuncs-minvalue]]
=== `MINVALUE()`

.Available in
DSQL, PSQL

.Result type
Varies according to input -- result will be of the same data type as the first expression in the list (_expr1_).

.Syntax
[listing]
----
MINVALUE (<expr1> [, ... , <exprN> ])
----

[[fblangref40-funcs-tbl-minvalue]]
.`MINVALUE` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|expr1 ... exprN
|List of expressions of compatible types
|===

Returns the minimum value from a list of numerical, string, or date/time expressions.
This function fully supports text ``BLOB``s of any length and character set. 

If one or more expressions resolve to `NULL`, `MINVALUE` returns `NULL`.
This behaviour differs from the aggregate function `MIN`.

[[fblangref40-scalarfuncs-minvalue-exmpl]]
==== `MINVALUE` Examples

[source]
----
SELECT MINVALUE(PRICE_1, PRICE_2) AS PRICE
  FROM PRICELIST
----

.See also
<<fblangref40-scalarfuncs-maxvalue>>

[[fblangref40-scalarfuncs-nullif]]
=== `NULLIF()`

.Available in
DSQL, PSQL

.Result type
Depends on input

.Syntax
[listing]
----
NULLIF (<exp1>, <exp2>)
----

[[fblangref40-funcs-tbl-nullif]]
.`NULLIF` Function Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|exp1
|An expression

|exp2
|Another expression of a data type compatible with _exp1_
|===

`NULLIF` returns the value of the first argument, unless it is equal to the second.
In that case, `NULL` is returned.


[[fblangref40-scalarfuncs-nullif-exmpl]]
==== `NULLIF` Example

[source]
----
select avg( nullif(Weight, -1) ) from FatPeople
----

This will return the average weight of the persons listed in FatPeople, excluding those having a weight of -1, since `AVG` skips `NULL` data.
Presumably, -1 indicates "`weight unknown`" in this table.
A plain `AVG(Weight)` would include the -1 weights, thus skewing the result.

.See also
<<fblangref40-scalarfuncs-coalesce>>, <<fblangref40-scalarfuncs-decode>>, <<fblangref40-scalarfuncs-iif>>, <<fblangref40-commons-conditional-case,`CASE`>>
