[[fblangref40-transacs]]
= Transaction Control

Everything in Firebird happens in transactions.
Units of work are isolated between a start point and end point.
Changes to data remain reversible until the moment the client application instructs the server to commit them.

[[fblangref40-transacs-statements]]
== Transaction Statements

Firebird has a small lexicon of SQL statements that are used by client applications to start, manage, commit and reverse (roll back) the transactions that form the boundaries of all database tasks:

<<fblangref40-transacs-settransac,SET TRANSACTION>>::
for configuring and starting a transaction

<<fblangref40-transacs-commit,COMMIT>>::
to signal the end of a unit of work and write changes permanently to the database

<<fblangref40-transacs-rollback,ROLLBACK>>::
to reverse the changes performed in the transaction

<<fblangref40-transacs-savepoint,SAVEPOINT>>::
to mark a position in the log of work done, in case a partial rollback is needed

<<fblangref40-transacs-releasesp,RELEASE SAVEPOINT>>::
to erase a savepoint

[[fblangref40-transacs-settransac]]
=== `SET TRANSACTION`

.Used for
Configuring and starting a transaction

.Available in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
SET TRANSACTION
   [NAME _tr_name_]
   [<tr_option> ...]

<tr_option> ::=
     READ {ONLY | WRITE}
   | [NO] WAIT
   | [ISOLATION LEVEL]
       { SNAPSHOT [TABLE [STABILITY]]
       | READ {UNCOMMITED | COMMITTED }
         [[NO] RECORD_VERSION] }
   | NO AUTO UNDO
   | RESTART REQUESTS
   | IGNORE LIMBO
   | LOCK TIMEOUT _seconds_
   | RESERVING <tables>
   | USING <dbhandles>

<tables> ::= <table_spec> [, <table_spec> ...]

<table_spec> ::= _tablename_ [, _tablename_ ...]
      [FOR [SHARED | PROTECTED] {READ | WRITE}]

<dbhandles> ::= _dbhandle_ [, _dbhandle_ ...]
----

[[fblangref40-transacs-tbl-settransac]]
.`SET TRANSACTION` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|tr_name
|Transaction name.
Available only in ESQL

|tr_option
|Optional transaction option.
Each option should be specified at most once, some options are mutually exclusive (e.g. `READ ONLY` vs `READ WRITE`, `WAIT` vs `NO WAIT`)

|seconds
|The time in seconds for the statement to wait in case a conflict occurs.
Has to be greater than or equal to `0`.

|tables
|The list of tables to reserve

|dbhandles
|The list of databases the database can access.
Available only in ESQL

|table_spec
|Table reservation specification

|tablename
|The name of the table to reserve

|dbhandle
|The handle of the database the database can access.
Available only in ESQL
|===

The `SET TRANSACTION` statement configures the transaction and starts it.
As a rule, only client applications start transactions.
The exceptions are the occasions when the server starts an autonomous transaction or transactions for certain background system threads/processes, such as sweeping.

A client application can start any number of concurrently running transactions.
A single connection can have multiple concurrent active transactions (though not all drivers or access components support this).
A limit does exist, for the total number of running transactions in all client applications working with one particular database from the moment the database was restored from its backup copy or from the moment the database was created originally.
The limit is 2^48^ -- 281,474,976,710,656 -- in Firebird 3, and 2^31^-1 -- or 2,147,483,647 -- in earlier versions.

All clauses in the `SET TRANSACTION` statement are optional.
If the statement starting a transaction has no clauses specified in it, it the transaction will be started with default values for access mode, lock resolution mode and isolation level, which are:

[source]
----
SET TRANSACTION
  READ WRITE
  WAIT
  ISOLATION LEVEL SNAPSHOT;
----

[WARNING]
====
Database drivers or access components may use different defaults.
Check their documentation for details.
====

The server assigns integer numbers to transactions sequentially.
Whenever a client starts any transaction, either explicitly defined or by default, the server sends the transaction ID to the client.
This number can be retrieved in SQL using the context variable `CURRENT_TRANSACTION`.

[NOTE]
====
Some database drivers -- or their governing specifications -- require that you configure and start transaction through API methods. In that case, using `SET TRANSACTION` is either not supported, or may result in unspecified behaviour. An example of this is JDBC and the Firebird JDBC driver Jaybird.

Check the documentation of your driver for details.
====

The `NAME` and `USING` clauses are only valid in ESQL.

[[fblangref40-transacs-settransac-name]]
==== Transaction Name

The optional `NAME` attribute defines the name of a transaction.
Use of this attribute is available only in Embedded SQL.
In ESQL applications, named transactions make it possible to have several transactions active simultaneously in one application.
If named transactions are used, a host-language variable with the same name must be declared and initialized for each named transaction.
This is a limitation that prevents dynamic specification of transaction names and thus, rules out transaction naming in DSQL.

[[fblangref40-transacs-settransac-params]]
==== Transaction Parameters

The main parameters of a transaction are: 

* data access mode (`READ WRITE`, `READ ONLY`)
* lock resolution mode (`WAIT`, `NO WAIT`) with an optional `LOCK TIMEOUT` specification
* isolation level (`READ COMMITTED`, `SNAPSHOT`, `SNAPSHOT TABLE STABILITY`).
+
[NOTE]
====
The `READ UNCOMMITTED` isolation level is a synonym for `READ COMMITTED`, and provided only for syntax compatibility.
It provides the exact same semantics as `READ COMMITTED`, and does not allow you to view uncommitted changes of other transactions.
====
* a mechanism for reserving or releasing tables (the `RESERVING` clause)

[[fblangref40-transacs-settransac-read]]
===== Access Mode

The two database access modes for transactions are `READ WRITE` and `READ ONLY`.

* If the access mode is `READ WRITE`, operations in the context of this transaction can be both read operations and data update operations.
This is the default mode.
* If the access mode is `READ ONLY`, only `SELECT` operations can be executed in the context of this transaction.
Any attempt to change data in the context of such a transaction will result in database exceptions.
However, this does not apply to global temporary tables (GTT), which are allowed to be changed in `READ ONLY` transactions, see <<fblangref40-ddl-tbl-gtt,_Global Temporary Tables (GTT)_>> in Chapter _Data Definition (DDL) Statements_ for details.

[[fblangref40-transacs-settransac-lock]]
===== Lock Resolution Mode

When several client processes work with the same database, locks may occur when one process makes uncommitted changes in a table row, or deletes a row, and another process tries to update or delete the same row.
Such locks are called _update conflicts_.

Locks may occur in other situations when multiple transaction isolation levels are used.

The two lock resolution modes are `WAIT` and `NO WAIT`.

[[fblangref40-transacs-settransac-wait]]
====== `WAIT` Mode

In the `WAIT` mode (the default mode), if a conflict occurs between two parallel processes executing concurrent data updates in the same database, a `WAIT` transaction will wait till the other transaction has finished -- by committing (`COMMIT`) or rolling back (`ROLLBACK`).
The client application with the `WAIT` transaction will be put on hold until the conflict is resolved.

If a `LOCK TIMEOUT` is specified for the `WAIT` transaction, waiting will continue only for the number of seconds specified in this clause.
If the lock is unresolved at the end of the specified interval, the error message "`Lock time-out on wait transaction`" is returned to the client.

Lock resolution behaviour can vary a little, depending on the transaction isolation level.

[[fblangref40-transacs-settransac-nowait]]
====== `NO WAIT` Mode

In the `NO WAIT` mode, a transaction will immediately throw a database exception if a conflict occurs.

[NOTE]
====
`LOCK TIMEOUT` is a separate transaction option, but can only be used for `WAIT` transactions.
Specifying `LOCK TIMEOUT` with a `NO WAIT` transaction will raise an error "`__invalid parameter in transaction parameter block -Option isc_tpb_lock_timeout is not valid if isc_tpb_nowait was used previously in TPB__`"
====

[[fblangref40-transacs-settransac-iso]]
===== Isolation Level

Keeping the work of one database task separated from others is what isolation is about.
Changes made by one statement become visible to all remaining statements executing within the same transaction, regardless of its isolation level.
Changes that are in progress within other transactions remain invisible to the current transaction as long as they remain uncommitted.
The isolation level and, sometimes, other attributes, determine how transactions will interact when another transaction wants to commit work.

The `ISOLATION LEVEL` attribute defines the isolation level for the transaction being started.
It is the most significant transaction parameter for determining its behavior towards other concurrently running transactions.

The three isolation levels supported in Firebird are: 

* `SNAPSHOT`
* `SNAPSHOT TABLE STABILITY`
* `READ COMMITTED` with two specifications (`NO RECORD_VERSION` and `RECORD_VERSION`)

[[fblangref40-transacs-settransac-snapshot]]
====== `SNAPSHOT` Isolation Level

`SNAPSHOT` isolation level -- the default level -- allows the transaction to see only those changes that were committed before it was started.
Any committed changes made by concurrent transactions will not be seen in a `SNAPSHOT` transaction while it is active.
The changes will become visible to a new transaction once the current transaction is either committed or rolled back completely, but not if it is just rolled back to a savepoint.

The `SNAPSHOT` isolation level is also known as "`__concurrency__`".

.Autonomous Transactions
[NOTE]
====
Changes made by autonomous transactions are not seen in the context of the `SNAPSHOT` transaction that launched it.
====

[[fblangref40-transacs-settransac-snapshottbl]]
====== `SNAPSHOT TABLE STABILITY` Isolation Level

The `SNAPSHOT TABLE STABILITY` -- or `SNAPSHOT TABLE -- isolation level is the most restrictive.
As in `SNAPSHOT`, a transaction in `SNAPSHOT TABLE STABILITY` isolation sees only those changes that were committed before the current transaction was started.
After a `SNAPSHOT TABLE STABILITY` is started, no other transactions can make any changes to any table in the database that has changes pending for this transaction.
Other transactions are able to read other data, but any attempt at inserting, updating or deleting by a parallel process will cause conflict exceptions.

The `RESERVING` clause can be used to allow other transactions to change data in some tables.

If any other transaction has an uncommitted change of data pending in any database table before a transaction with the `SNAPSHOT TABLE STABILITY` isolation level is started, trying to start a `SNAPSHOT TABLE STABILITY` transaction will result in an exception.

The `SNAPSHOT TABLE STABILITY` isolation level is also known as "`__consistency__`".

[[fblangref40-transacs-settransac-readcommit]]
====== `READ COMMITTED` Isolation Level

The `READ COMMITTED` isolation level allows all data changes that other transactions have committed since it started to be seen immediately by the uncommitted current transaction.
Uncommitted changes are not visible to a `READ COMMITTED` transaction.

To retrieve the updated list of rows in the table you are interested in -- "`refresh`" -- the `SELECT` statement just needs to be requested again, whilst still in the uncommitted `READ COMMITTED` transaction.

[float]
[[fblangref40-transacs-settransac-recversion]]
====== `RECORD_VERSION`

One of two modifying parameters can be specified for `READ COMMITTED` transactions, depending on the kind of conflict resolution desired: `RECORD_VERSION` and `NO RECORD_VERSION`.
As the names suggest, they are mutually exclusive. 

* `NO RECORD_VERSION` (the default value) is a kind of two-phase locking mechanism: it will make the transaction unable to write to any row that has an update pending from another transaction.
** if `NO WAIT` is the lock resolution strategy specified, it will throw a lock conflict error immediately
** with `WAIT` specified, it will wait until the other transaction either commits or is rolled back.
If the other transaction is rolled back, or if it is committed and its transaction ID is older than the current transaction's ID, then the current transaction's change is allowed.
A lock conflict error is returned if the other transaction was committed and its ID was newer than that of the current transaction.
* With `RECORD_VERSION` specified, the transaction reads the latest committed version of the row, regardless of other pending versions of the row.
The lock resolution strategy (`WAIT` or `NO WAIT`) does not affect the behavior of the transaction at its start in any way.

[[fblangref40-transacs-settransac-noautoundo]]
===== `NO AUTO UNDO`

The `NO AUTO UNDO` option affects the handling of record versions (garbage) produced by the transaction in the event of rollback.
With `NO AUTO UNDO` flagged, the `ROLLBACK` statement just marks the transaction as rolled back without deleting the record versions created in the transaction.
They are left to be mopped up later by garbage collection.

`NO AUTO UNDO` might be useful when a lot of separate statements are executed that change data in conditions where the transaction is likely to be committed successfully most of the time.

The `NO AUTO UNDO` option is ignored for transactions where no changes are made.


[[fblangref40-transacs-settransac-restartreqs]]
===== `RESTART REQUESTS`

According to the Firebird sources, this will

[quote, src/jrd/tra.cpp]
____
Restart all requests in the current attachment to utilize the passed transaction.
____

The exact semantics and effects of this clause are not clear, and we recommend you do not use this clause.

[[fblangref40-transacs-settransac-ignorelimbo]]
===== `IGNORE LIMBO`

This flag is used to signal that records created by limbo transactions are to be ignored.
Transactions are left "`in limbo`" if the second stage of a two-phase commit fails.

.Historical Note
[NOTE]
====
`IGNORE LIMBO` surfaces the TPB parameter `isc_tpb_ignore_limbo`, available in the API since InterBase times and is mainly used by _gfix_.
====

[[fblangref40-transacs-settransac-reserv]]
===== `RESERVING`

The `RESERVING` clause in the `SET TRANSACTION` statement reserves tables specified in the table list.
Reserving a table prevents other transactions from making changes in them or even, with the inclusion of certain parameters, from reading data from them while this transaction is running.

A `RESERVING` clause can also be used to specify a list of tables that can be changed by other transactions, even if the transaction is started with the `SNAPSHOT TABLE STABILITY` isolation level.

One `RESERVING` clause is used to specify as many reserved tables as required.

[[fblangref40-transacs-settransac-reserv-opt]]
====== Options for `RESERVING` Clause

If one of the keywords `SHARED` or `PROTECTED` is omitted, `SHARED` is assumed.
If the whole `FOR` clause is omitted, `FOR SHARED READ` is assumed.
The names and compatibility of the four access options for reserving tables are not obvious.

[[fblangref40-transacs-tbl-accesscompat]]
.Compatibility of Access Options for `RESERVING`
[cols="<1,^1,^1,^1,^1",stripes="none"]
|===
|{nbsp}
|SHARED READ
|SHARED WRITE
|PROTECTED READ
|PROTECTED WRITE

|SHARED READ
|Yes
|Yes
|Yes
|Yes

|SHARED WRITE
|Yes
|Yes
|No
|No

|PROTECTED READ
|Yes
|No
|Yes
|No

|PROTECTED WRITE
|Yes
|No
|No
|No
|===

The combinations of these `RESERVING` clause flags for concurrent access depend on the isolation levels of the concurrent transactions:

* `SNAPSHOT` isolation
** Concurrent `SNAPSHOT` transactions with `SHARED READ` do not affect one other's access
** A concurrent mix of `SNAPSHOT` and `READ COMMITTED` transactions with `SHARED WRITE` do not affect one another's access, but they block transactions with `SNAPSHOT TABLE STABILITY` isolation from either reading from or writing to the specified table(s)
** Concurrent transactions with any isolation level and `PROTECTED READ` can only read data from the reserved tables.
Any attempt to write to them will cause an exception
** With `PROTECTED WRITE`, concurrent transactions with `SNAPSHOT` and `READ COMMITTED` isolation cannot write to the specified tables.
Transactions with `SNAPSHOT TABLE STABILITY` isolation cannot read from or write to the reserved tables at all.
* `SNAPSHOT TABLE STABILITY` isolation
** All concurrent transactions with `SHARED READ`, regardless of their isolation levels, can read from or write (if in `READ WRITE` mode) to the reserved tables
** Concurrent transactions with `SNAPSHOT` and `READ COMMITTED` isolation levels and `SHARED WRITE` can read data from and write (if in `READ WRITE` mode) to the specified tables but concurrent access to those tables from transactions with `SNAPSHOT TABLE STABILITY` is blocked completely whilst these transactions are active
** Concurrent transactions with any isolation level and `PROTECTED READ` can only read from the reserved tables
** With `PROTECTED WRITE`, concurrent `SNAPSHOT` and `READ COMMITTED` transactions can read from but not write to the reserved tables.
Access by transactions with the `SNAPSHOT TABLE STABILITY` isolation level is blocked completely.
* `READ COMMITTED` isolation
** With `SHARED READ`, all concurrent transactions with any isolation level can both read from and write (if in `READ WRITE` mode) to the reserved tables
** `SHARED WRITE` allows all transactions in `SNAPSHOT` and `READ COMMITTED` isolation to read from and write (if in `READ WRITE` mode) to the specified tables and blocks access completely from transactions with `SNAPSHOT TABLE STABILITY` isolation
** With `PROTECTED READ`, concurrent transactions with any isolation level can only read from the reserved tables
** With `PROTECTED WRITE`, concurrent transactions in `SNAPSHOT` and `READ COMMITTED` isolation can read from but not write to the specified tables.
Access from transactions in `SNAPSHOT TABLE STABILITY` isolation is blocked completely.

[NOTE]
====
In Embedded SQL, the `USING` clause can be used to conserve system resources by
limiting the number of databases a transaction can access.
`USING` is mutually exclusive with `RESERVING`.
A `USING` clause in `SET TRANSACTION` syntax is not supported in DSQL.
====

.See also
<<fblangref40-transacs-commit>>, <<fblangref40-transacs-rollback>>

[[fblangref40-transacs-commit]]
=== `COMMIT`

.Used for
Committing a transaction

.Available in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
COMMIT [TRANSACTION _tr_name_] [WORK]
  [RETAIN [SNAPSHOT] | RELEASE];
----

[[fblangref40-transacs-tbl-commit]]
.`COMMIT` Statement Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|tr_name
|Transaction name.
Available only in ESQL
|===

The `COMMIT` statement commits all work carried out in the context of this transaction (inserts, updates, deletes, selects, execution of procedures).
New record versions become available to other transactions and, unless the `RETAIN` clause is employed, all server resources allocated to its work are released.

If any conflicts or other errors occur in the database during the process of committing the transaction, the transaction is not committed, and the reasons are passed back to the user application for handling, and the opportunity to attempt another commit or to roll the transaction back.

The `TRANSACTION` and `RELEASE` clauses are only valid in ESQL.

[[fblangref40-transacs-commit-options]]
==== `COMMIT` Options

* The optional `TRANSACTION __tr_name__` clause, available only in Embedded SQL, specifies the name of the transaction to be committed.
With no `TRANSACTION` clause, `COMMIT` is applied to the default transaction.
+
[NOTE]
====
In ESQL applications, named transactions make it possible to have several transactions active simultaneously in one application.
If named transactions are used, a host-language variable with the same name must be declared and initialized for each named transaction.
This is a limitation that prevents dynamic specification of transaction names and thus, rules out transaction naming in DSQL.
====
* The optional keyword `WORK` is supported just for compatibility with other relational database management systems that require it.
* The keyword `RELEASE` is available only in Embedded SQL and enables disconnection from all databases after the transaction is committed.
`RELEASE` is retained in Firebird only for compatibility with legacy versions of InterBase.
It has been superseded in ESQL by the `DISCONNECT` statement.
* The `RETAIN [SNAPSHOT]` clause is used for the "`soft`" commit, variously referred to amongst host languages and their practitioners as `COMMIT WITH RETAIN`, "`CommitRetaining`", "`warm commit`", et al.
The transaction is committed, but some server resources are retained and a new transaction is restarted transparently with the same Transaction ID.
The state of row caches and cursors is kept as it was before the soft commit.
+ 
For soft-committed transactions whose isolation level is `SNAPSHOT` or `SNAPSHOT TABLE STABILITY`, the view of database state is not updated to reflect changes by other transactions, and the user of the application instance continues to have the same view as when the transaction started originally.
Changes made during the life of the retained transaction are visible to that transaction, of course.

.Recommendation
[NOTE]
====
Use of the `COMMIT` statement in preference to `ROLLBACK` is recommended for ending transactions that only read data from the database, because `COMMIT` consumes fewer server resources and helps to optimize the performance of subsequent transactions.
====

.See also
<<fblangref40-transacs-settransac>>, <<fblangref40-transacs-rollback>>

[[fblangref40-transacs-rollback]]
=== `ROLLBACK`

.Used for
Rolling back a transaction

.Available in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
  ROLLBACK [TRANSACTION _tr_name_] [WORK]
    [RETAIN [SNAPSHOT] | RELEASE]
| ROLLBACK [WORK] TO [SAVEPOINT] _sp_name_
----

[[fblangref40-transacs-tbl-rollback]]
.ROLLBACK Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|tr_name
|Transaction name.
Available only in ESQL

|sp_name
|Savepoint name.
Available only in DSQL
|===

The `ROLLBACK` statement rolls back all work carried out in the context of this transaction (inserts, updates, deletes, selects, execution of procedures).
`ROLLBACK` never fails and, thus, never causes exceptions.
Unless the `RETAIN` clause is employed, all server resources allocated to the work of the transaction are released.

The `TRANSACTION` and `RELEASE` clauses are only valid in ESQL.
The `ROLLBACK TO SAVEPOINT` statement is not available in ESQL.

[[fblangref40-transacs-rollback-options]]
==== `ROLLBACK` Options

* The optional `TRANSACTION __tr_name__` clause, available only in Embedded SQL, specifies the name of the transaction to be committed.
With no `TRANSACTION` clause, `ROLLBACK` is applied to the default transaction.
+
[NOTE]
====
In ESQL applications, named transactions make it possible to have several transactions active simultaneously in one application.
If named transactions are used, a host-language variable with the same name must be declared and initialized for each named transaction.
This is a limitation that prevents dynamic specification of transaction names and thus, rules out transaction naming in DSQL.
====
* The optional keyword `WORK` is supported just for compatibility with other relational database management systems that require it.
* The keyword `RETAIN` keyword specifies that, although all work of the transaction is to be rolled back, the transaction context is to be retained.
Some server resources are retained, and the transaction is restarted transparently with the same Transaction ID.
The state of row caches and cursors is kept as it was before the "`soft`" rollback.
+ 
For transactions whose isolation level is `SNAPSHOT` or `SNAPSHOT TABLE STABILITY`, the view of database state is not updated by the soft rollback to reflect changes by other transactions.
The user of the application instance continues to have the same view as when the transaction started originally.
Changes that were made and soft-committed during the life of the retained transaction are visible to that transaction, of course.

.See also
<<fblangref40-transacs-settransac>>, <<fblangref40-transacs-commit>>

[[fblangref40-transacs-rollback-tosavepoint]]
===== `ROLLBACK TO SAVEPOINT`

The alternative `ROLLBACK TO SAVEPOINT` statement specifies the name of a savepoint to which changes are to be rolled back.
The effect is to roll back all changes made within the transaction, from the specified savepoint forward until the point when `ROLLBACK TO SAVEPOINT` is requested.

`ROLLBACK TO SAVEPOINT` performs the following operations: 

* Any database mutations performed since the savepoint was created are undone.
User variables set with `RDB$SET_CONTEXT()` remain unchanged.
* Any savepoints that were created after the one named are destroyed.
Savepoints earlier than the one named are preserved, along with the named savepoint itself.
Repeated rollbacks to the same savepoint are thus allowed.
* All implicit and explicit record locks that were acquired since the savepoint are released.
Other transactions that have requested access to rows locked after the savepoint must continue to wait until the transaction is committed or rolled back.
Other transactions that have not already requested the rows can request and access the unlocked rows immediately.

.See also
<<fblangref40-transacs-savepoint>>, <<fblangref40-transacs-releasesp>>

[[fblangref40-transacs-savepoint]]
=== `SAVEPOINT`

.Used for
Creating a savepoint

.Available in
DSQL

.Syntax
[listing,subs=+quotes]
----
SAVEPOINT _sp_name_
----

[[fblangref40-transacs-tbl-savepoint]]
.SAVEPOINT Statement Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|sp_name
|Savepoint name.
Available only in DSQL
|===

The `SAVEPOINT` statement creates an SQL:99-compliant savepoint that acts as a marker in the "`stack`" of data activities within a transaction.
Subsequently, the tasks performed in the "`stack`" can be undone back to this savepoint, leaving the earlier work and older savepoints untouched.
Savepoint mechanisms are sometimes characterised as "`nested transactions`".

If a savepoint already exists with the same name as the name supplied for the new one, the existing savepoint is released, and a new one is created using the supplied name.

To roll changes back to the savepoint, the statement `ROLLBACK TO SAVEPOINT` is used.

.Memory Considerations
[NOTE]
====
The internal mechanism beneath savepoints can consume large amounts of memory, especially if the same rows receive multiple updates in one transaction.
When a savepoint is no longer needed, but the transaction still has work to do, a <<fblangref40-transacs-releasesp>> statement will erase it and thus free the resources.
====

.Sample DSQL session with savepoints
[source]
----
CREATE TABLE TEST (ID INTEGER);
COMMIT;
INSERT INTO TEST VALUES (1);
COMMIT;
INSERT INTO TEST VALUES (2);
SAVEPOINT Y;
DELETE FROM TEST;
SELECT * FROM TEST; -- returns no rows
ROLLBACK TO Y;
SELECT * FROM TEST; -- returns two rows
ROLLBACK;
SELECT * FROM TEST; -- returns one row
----

.See also
<<fblangref40-transacs-rollback-tosavepoint>>, <<fblangref40-transacs-releasesp>>

[[fblangref40-transacs-releasesp]]
=== `RELEASE SAVEPOINT`

.Used for
Erasing a savepoint

.Available in
DSQL

.Syntax
[listing,subs=+quotes]
----
RELEASE SAVEPOINT _sp_name_ [ONLY]
----

[[fblangref40-transacs-tbl-rlssavepoint]]
.RELEASE SAVEPOINT Statement Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|sp_name
|Savepoint name.
Available only in DSQL
|===

The statement `RELEASE SAVEPOINT` erases a named savepoint, freeing up all the resources it encompasses.
By default, all the savepoints created after the named savepoint are released as well.
The qualifier `ONLY` directs the engine to release only the named savepoint.

.See also
<<fblangref40-transacs-savepoint>>

[[fblangref40-transacs-internalsp]]
=== Internal Savepoints

By default, the engine uses an automatic transaction-level system savepoint to perform transaction rollback.
When a `ROLLBACK` statement is issued, all changes performed in this transaction are backed out via a transaction-level savepoint, and the transaction is then committed.
This logic reduces the amount of garbage collection caused by rolled back transactions.

When the volume of changes performed under a transaction-level savepoint is getting large (~50000 records affected), the engine releases the transaction-level savepoint and uses the Transaction Inventory Page (TIP) as a mechanism to roll back the transaction if needed.

[TIP]
====
If you expect the volume of changes in your transaction to be large, you can specify the `NO AUTO UNDO` option in your `SET TRANSACTION` statement to block the creation of the transaction-level savepoint.
Using the API instead, you would set the TPB flag `isc_tpb_no_auto_undo`.
====

[[fblangref40-transacs-psqlandsp]]
=== Savepoints and PSQL

Transaction control statements are not allowed in PSQL, as that would break the atomicity of the statement that calls the procedure.
However, Firebird does support the raising and handling of exceptions in PSQL, so that actions performed in stored procedures and triggers can be selectively undone without the entire procedure failing.

Internally, automatic savepoints are used to: 

* undo all actions in the `BEGIN...END` block where an exception occurs
* undo all actions performed by the procedure or trigger or, in a selectable procedure, all actions performed since the last `SUSPEND`, when execution terminates prematurely because of an uncaught error or exception

Each PSQL exception handling block is also bounded by automatic system savepoints.

[NOTE]
====
A `BEGIN...END` block does not itself create an automatic savepoint.
A savepoint is created only in blocks that contain the WHEN statement for handling exceptions.
====
