[[fblangref30-management]]
= Management Statements

Since Firebird 3.0 a new class of DSQL statement has emerged in Firebird's SQL lexicon, usually for administering aspects of the client/server environment.
Typically, such statements start with the verb `SET`.

[NOTE]
====
The _isql_ tool also has a collection of `SET` commands.
Those commands are not part of Firebird's SQL lexicon.
For information on __isql__s `SET` commands, see https://www.firebirdsql.org/file/documentation/html/en/firebirddocs/isql/firebird-isql.html#isql-set[_Isql_ Set Commands] in _Firebird Interactive SQL Utility_.
====

Most of the management statements affect the current connection (attachment, or "`session`") only, and do not require any authorization over and above the login privileges of the current user without elevated privileges.

[[fblangref30-management-role]]
== Changing the Current Role

[[fblangref30-management-role-set]]
=== `SET ROLE`

.Used for
Changing the role of the current session

.Available in
DSQL

.Syntax
[listing,subs=+quotes]
----
SET ROLE {_role_name_ | NONE}
----

.`SET ROLE` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|role_name
|The name of the role to apply
|===

The `SET ROLE` statement allows a user to assume a different role;
it sets the `CURRENT_ROLE` context variable to _role_name_, if that role has been granted to the `CURRENT_USER`.
For this session, the user receives the privileges granted by that role.
Any rights granted to the previous role are removed from the session.
Use `NONE` instead of _role_name_ to clear the `CURRENT_ROLE`.

When the specified role does not exist or has not been explicitly granted to the user, the error "`__Role *role_name* is invalid or unavailable__`" is raised.

[[fblangref30-management-role-set-exmpl]]
==== `SET ROLE` Examples

. Change the current role to `MANAGER`
+
[source]
----
SET ROLE manager;
select current_role from rdb$database;

ROLE
=======================
MANAGER
----
. Clear the current role
+
[source]
----
SET ROLE NONE;
select current_role from rdb$database;

ROLE
=======================
NONE
----

.See also
<<fblangref30-management-role-set-trusted>>, <<fblangref30-security-grant,`GRANT`>>

[[fblangref30-management-role-set-trusted]]
=== `SET TRUSTED ROLE`

.Used for
Changes role of the current session to the trusted role

.Available in
DSQL

.Syntax
[listing]
----
SET TRUSTED ROLE
----

The `SET TRUSTED ROLE` statement makes it possible to assume the role assigned to the user through a mapping rule (see <<fblangref30-security-mapping,Mapping of Users to Objects>>).
The role assigned through a mapping rule is assumed automatically on connect, if the user hasn't specified an explicit role.
The `SET TRUSTED ROLE` statement makes it possible to assume the mapped (or "`trusted`") role at a later time, or to assume it again after the current role was changed using `SET ROLE`.

A trusted role is not a specific type of role, but can be any role that was created using `CREATE ROLE`, or a predefined system role such as `RDB$ADMIN`.
An attachment (session) has a trusted role when the <<fblangref30-security-mapping,security objects mapping subsystem>> finds a match between the authentication result passed from the plugin and a local or global mapping to a role for the current database.
The role may be one that is not granted explicitly to that user.

When a session has no trusted role, executing `SET TRUSTED ROLE` will raise error "`__Your attachment has no trusted role__`".

[NOTE]
====
While the `CURRENT_ROLE` can be changed using `SET ROLE`, it is not always possible to revert to a trusted role using the same command, because `SET ROLE` checks if the role has been granted to the user.
With `SET TRUSTED ROLE`, the trusted role can be assumed again even when `SET ROLE` fails.
====

[[fblangref30-management-role-set-trusted-exmpl]]
==== `SET TRUSTED ROLE` Examples

. Assuming a mapping rule that assigns the role `ROLE1` to a user `ALEX`:
+
[source]
-----
CONNECT 'employee' USER ALEX PASSWORD 'password';
SELECT CURRENT_ROLE FROM RDB$DATABASE;

ROLE
===============================
ROLE1

SET ROLE ROLE2;
SELECT CURRENT_ROLE FROM RDB$DATABASE;

ROLE
===============================
ROLE2

SET TRUSTED ROLE;
SELECT CURRENT_ROLE FROM RDB$DATABASE;

ROLE
===============================
ROLE1
-----

.See also
<<fblangref30-management-role-set>>, <<fblangref30-security-mapping,Mapping of Users to Objects>>
