[[fblangref25-intro]]
= About the Firebird SQL Language Reference: for Firebird 2.5

This Firebird SQL Language Reference is the first comprehensive manual to cover all aspects of the query language used by developers to communicate, through their applications, with the Firebird relational database management system.
It has a long history.

[[fblangref25-intro-subject]]
== Subject Matter

The subject matter of this volume is wholly Firebird's implementation of the SQL relational database language.
Firebird conforms closely with international standards for SQL, from data type support, data storage structures, referential integrity mechanisms, to data manipulation capabilities and access privileges.
Firebird also implements a robust procedural language -- procedural SQL (PSQL) -- for stored procedures, triggers and dynamically-executable code blocks.
These are the areas addressed in this volume.

[[fblangref25-intro-authors]]
== Authorship

The material for assembling this Language Reference has been accumulating in the tribal lore of the open source community of Firebird core developers and user-developers for 15 years.
The gift of the InterBase 6 open source codebase in July 2000 from the (then) Inprise/Borland conglomerate was warmly welcomed.
However, it came without rights to existing documentation.
Once the code base had been forked by its owners for private, commercial development, it became clear that the open source, non-commercial Firebird community would never be granted right of use.

The two important books from the InterBase 6 published set were the [ref]_Data Definition Guide_ and the [ref]_Language Reference_.
The former covered the data definition language (DDL) subset of the SQL language, while the latter covered most of the rest.
Fortunately for Firebird users over the years, both have been easy to find on-line as PDF books.

[[fblangref25-intro-authors-lru]]
=== Language Reference Updates

The [ref]_Data Definition Guide_, covering the creation and maintenance of metadata for databases, was "`good enough`" for several years: the data definition language (DDL) of a DBMS is stable and grows slowly in comparison to the data manipulation language (DML) employed for queries and the PSQL used for server-based programming.

The leader of the Firebird Project's documentation team, Paul Vinkenoog, took up the cause for documenting the huge volume of improvements and additions to DML and PSQL as Firebird advanced through its releases.
Paul was personally responsible for collating, assembling and, to a great extent, authoring a cumulative series of "`Language Reference Updates`" -- one for every major release from v.1.5 forward.

[[fblangref25-intro-bigbook]]
=== Gestation of the Big Book

From around 2010, Paul, with Firebird Project lead Dmitry Yemanov and a documenter colleague Thomas Woinke, set about the task of designing and assembling a complete SQL language reference for Firebird.
They began with the material from the LangRef Updates, which is voluminous.
It was going to be a big job but, for all concerned, a spare-time one.

Then, in 2013-4, two benefactor companies -- MICEX amd IBSurgeon -- funded three writers to take up this stalled book outline and publish a Firebird 2.5 Language Reference in Russian.
They wrote the bulk of the  missing DDL section from scratch and wrote, translated or reused DML and PSQL material from the LangRef Updates, Russian language support forums, Firebird release notes, read-me files and other sources.
By the end of 2014, they had the task almost complete, in the form of a Microsoft Word document.

[[fblangref25-intro-funding]]
==== Translation ...

The Russian sponsors, recognising that their efforts needed to be shared with the world-wide Firebird community, asked some Project members to initiate a crowd-funding campaign to have the Russian text professionally translated into English.
The translated text would be edited and converted to the Project's standard DocBook format for addition to the open document library of the Firebird Project.
From there, the source text would be available for translation into other languages for addition to the  library.

The fund-raising campaign happened at the end of 2014 and was successful.
In June, 2015, professional translator Dmitry Borodin began translating the Russian text.
From him, the raw English text went in stages for editing and DocBook conversion by Helen Borrie -- and here is [ref]_The Firebird SQL Language Reference for V.2.5_, by...everyone!

[[fblangref25-intro-translation]]
==== ... and More Translation

Once the DocBook source appears in CVS, we hope the trusty translators will start making versions in German, Japanese, Italian, French, Portuguese, Spanish, Czech.
Certainly, we never have enough translators  so please, you Firebirders who have English as a second language, do consider translating some sections into your first language.

[[fblangref25-intro-contributors]]
=== Contributors

[float]
==== Direct Content

* Dmitry Filippov (writer)
* Alexander Karpeykin (writer)
* Alexey Kovyazin (writer, editor)
* Dmitry Kuzmenko (writer, editor)
* Denis Simonov (writer, editor, coordinator)
* Paul Vinkenoog (writer, designer)
* Dmitry Yemanov (writer)

[float]
==== Resource Content

* Adriano dos Santos Fernandes
* Alexander Peshkov
* Vladyslav Khorsun
* Claudio Valderrama
* Helen Borrie
* and others

[float]
==== Translation

* Dmitry Borodin, megaTranslations.ru

[float]
==== Editing and Conversion of English Text

* Helen Borrie

[[fblangref25-acknowledgements]]
== Acknowledgments

The first full language reference manual for Firebird would not have eventuated without the funding that finally brought it to fruition.
We acknowledge these contributions with gratitude and thank you all for stepping up.

[float]
[[sponsors-donors]]
=== Sponsors and Other Donors[[sponsors_donors]]

[float]
[[sponsors01-native]]
==== Sponsors of the Russian Language Reference Manual

[none]
* https://www.moex.com[Moscow Exchange] (Russia)
+
_Moscow Exchange is the largest exchange holding in Russia and Eastern Europe, founded on December 19, 2011, through the consolidation of the MICEX (founded in 1992) and RTS (founded in 1995) exchange groups.
Moscow Exchange ranks among the world's top 20 exchanges by trading in bonds and by the total capitalization of shares traded, as well as among the 10 largest exchange platforms for trading derivatives._

* https://www.ib-aid.com[IBSurgeon] (http://ibase.ru[ibase.ru]) (Russia)
+
_Technical support and developer of administrator tools for the Firebird DBMS._

[float]
[[sponsors01-translate]]
==== Sponsors of the Translation Project

[none]
* https://www.syntess.nl[Syntess Software BV] (Netherlands)
* https://www.mitaro.li[Mitaro Business Solutions] (Liechtenstein)

[float]
[[donors]]
==== Other Donors

Listed below are the names of companies and individuals whose cash contributions covered the costs for translation into English, editing of the raw, translated text and conversion of the whole into the Firebird Project's standard DocBook 4 documentation source format.

[cols="3*",frame=none,grid=none,stripes=none]
|===
|Integrity Software Design, Inc. (U.S.A.)
|dimari GmbH (Germany)
|beta Eigenheim GmbH (Germany)
|KIMData GmbH (Germany)
|Jason Wharton (U.S.A)
|Trans-X (Sweden)
|Sanchez Balcewich (Uruguay)
|Cointec Ingenieros y Consultores, S.L. (Spain)
|Aage Johansen (Norway)
|Mattic Software (Netherlands)
|André Knappstein (Germany)
|Paul F. McGuire (U.S.A.)
|Marcus Marques da Rocha (Brazil)
|Martin Kerkhoff
|Thomas Vedel (Denmark)
|Bulhan Bulhan (Australia)
|Alexandre Benson Smith (Brazil)
|Guillermo Nabrink (Brazil)
|Pierre Voirin (France)
|Heiko Tappe (Germany)
|Doug Chamberlin (U.S.A.)
|Craig Cox (U.S.A.)
|OMNet, Inc. (Switzerland)
|Alfred Steller (Germany)
|Konrad Butz (Germany)
|Thomas Smekal (Canada)
|Carlos H. Cantu (Brazil)
|XTRALOG SARL (France)
|Laszlo Urmenyi (Brazil)
|Fernando Pimenta (Brazil)
|Rudolf Grauberger (Germany)
|Thomas Steinmaurer (Austria)
|Rene Lobsiger (Switzerland)
|Hian Pin Tjioe
|Xavier Codina
|Mick Arundell (Australia)
|Russell Belding (New Zealand)
|Anticlei Scheid (Brazil)
|Luca Minuti (Italy)
|Mark Rotteveel (Netherlands)
|Chris Mathews (U.S.A.)
|Hannes Streicher (Germany)
|Wolfgang Lemmermeyer (Germany)
|Paolo Sciarrini (Italy)
|Acosta Belzusarri
|Daniel Motos Guerra
|Alberto Alfonso Luna
|Simeon Bodurov
|Cees Meijer
|Robert Nixon
|Olivier Dehorter (France)
|András Omacht (Hungary)
|Web Express
|Sergio Conzalez
|Marc Bleuwart
|Gabor Boros
|Shaymon Gracia Campos
|Cserna Zsombor (Hungary)
|David Keith
|Uwe Gerold
|Daniele Teti (Italy)
|Pedro Pablo Busto Criado
|Istvan Szabo
|Spiridon Pavlovic
|J. L. Garcia Naranjo
|A. Morales Morales
|Helen Cullen (New Zealand)
|Francisco Ibarra Ozuna
|{nbsp}
|===
