:sectnums!:

[appendix]
[[fblangref25-dochist]]
= Document History

The exact file history is recorded in our _git_ repository; see https://github.com/FirebirdSQL/firebird-documentation

[%autowidth, width="100%", cols="4", options="header", frame="none", grid="none", role="revhistory"]
|===
4+|Revision History

|1.3
|13 Jun 2020
|MR
|Various minor changes in copy and styling while checking migrating the German version to AsciiDoc

|1.2
|6 Jun 2020
|MR
a|* Split chapter Built-in Functions and Context Variables into two chapters: Built-in Functions, and Context Variables
* Removed incorrect caution on expressions in `ORDER BY`
* Made function and context variable description use consistent order

|1.1
|1 Jun 2020
|MR
|Conversion to AsciiDoc.
Various copy-editing, and fixing factual errors and other problems while checking and correcting AsciiDoc.

|1.001
|22 Jan 2018
|H.E.M.B.
a|Updated the file history link at the top of this chapter to reflect  the migration of the Doc source tree to Github.

Typos fixed/updates by M. Rotteveel Dec. 2017/Jan. 2018

* 14.12.2017 psql.xml line 544 replaced 'stored procedures' with 'triggers'
* 14.12.2017 psql.xml line 1070 removed extraneous '>' symbol
* 21.01.2018 functions-vars.xml line 1222 replaced 'CURRENT_TIME' with 'CURRENT_TIMESTAMP'
* 21.01.2018 dml.xml line 19 switched 'INSERT OR UPDATE' to 'UPDATE OR INSERT'
* 21.01.2018 dml.xml line 3344 removed extraneous 'the'
* 21.01.2018 ddl.xml line 3359 inserted missing keyword 'INDEX' for SET STATISTICS syntax
* 21.01.2018 commons.xml line 1330 switch keywords 'horizontal' and 'vertical'
* 21.01.2018 structure.xml lines 276 to 278 change date literal format to 'yyyy-mm-dd' and include hex representation in example

|1.000
|11 Aug 2017
|H.E.M.B.
a|There have been no further changes to the content during the final review  period.
The chapters DML, PSQL, Functions and Variables, Transactions and Security were not reviewed in this phase.

|0.906
|11 Aug 2016
| H.E.M.B.
a|Several revisions were published during the year, as a Beta 1, with reviews of various sections by Paul Vinkenoog, Aage Johansen and Mark Rotteveel.
This revision (0.906) awaits final revision of some later sections, marked as "`Editor's Note`" in red italics.

|0.900
|1 Sep 2015
| H.E.M.B.
|Original was in Russian, translated by Dmitry Borodin (MegaTranslations).
Raw translation edited and converted to DocBook, as this revison (0.900), by Helen Borrie.

This revision distributed as a PDF build only, for review by Dmitry Yemanov, et al.

Reviewers, please pay attention to the comments like this: _Editor's note {two-colons} The sky is falling, take cover!_
|===

:sectnums:
