:sectnums!:

[appendix]
[[fblangref25-dochist]]
= Document History

The exact file history is recorded in our _git_ repository; see https://github.com/FirebirdSQL/firebird-documentation

[%autowidth, width="100%", cols="4", options="header", frame="none", grid="none", role="revhistory"]
|===
4+|Revision History

|1.14
|20 Jun 2023
|MR
a|* Computed columns can be indexed with expression indexes
* Add caution about relying on ordered derived tables for <<fblangref25-functions-aggfuncs-list>>

|1.13
|26 May 2023
|MR
a|* Added missing context variable names for <<fblangref25-functions-scalarfuncs-get-context>>
* Replaced mention that implicit join is deprecated and might get removed;
its use is merely discouraged.
* Removed incorrect `ROLE` keyword from example in <<fblangref25-security-rdbadmin01>>

|1.12
|10 May 2023
|MR
|Removed incorrect `<common-table-expression>` production in SELECT syntax

|1.11
|30 Jan 2023
|MR
|Fixed typo in collation name `UCS_BASIC`

|1.10
|18 Jul 2022
|MR
|Fix documentation for `RDB$INDICES.RDB$INDEX_TYPE` (https://github.com/FirebirdSQL/firebird-documentation/issues/174[#174])

|1.9
|16 Oct 2021
|MR
|`EXECUTE STATEMENT` named parameters are regular identifiers (https://github.com/FirebirdSQL/firebird-documentation/issues/164[#164])

|1.8
|31 Jul 2021
|MR
|Fix behaviour documented for `SNAPSHOT TABLE STABILITY` (https://github.com/FirebirdSQL/firebird-documentation/issues/158[#158])

|1.7
|23 Jul 2021
|MR
|Remove extra `SELECT` in select syntax

|1.6
|13 Jun 2021
|MR
a|* Fixed wrong table title `NUMERIC` -> `DECIMAL`
* Fixed wrong link title `DATEADD` -> `DATEDIFF`

|1.5
|27 Apr 2021
|MR
a|* Added missing `}` in regular expression special characters (see https://github.com/FirebirdSQL/firebird-documentation/issues/124[issue 124])
* Fixed rendering issue hiding the `_` in regular expression special characters
* Improve wording of `CURRENT_CONNECTION` and `CURRENT_TRANSACTION` (see https://github.com/FirebirdSQL/firebird-documentation/issues/96[issue 96])

|1.4
|27 Apr 2021
|MR
|Fixed `GRANT` syntax (see https://github.com/FirebirdSQL/firebird-documentation/issues/130[issue 130])

|1.3
|13 Jun 2020
|MR
|Various minor changes in copy and styling while checking migrating the German version to AsciiDoc

|1.2
|6 Jun 2020
|MR
a|* Split chapter Built-in Functions and Context Variables into two chapters: Built-in Functions, and Context Variables
* Removed incorrect caution on expressions in `ORDER BY`
* Made function and context variable description use consistent order

|1.1
|1 Jun 2020
|MR
|Conversion to AsciiDoc.
Various copy-editing, and fixing factual errors and other problems while checking and correcting AsciiDoc.

|1.001
|22 Jan 2018
|H.E.M.B.
a|Updated the file history link at the top of this chapter to reflect  the migration of the Doc source tree to Github.

Typos fixed/updates by M. Rotteveel Dec. 2017/Jan. 2018

* 14.12.2017 psql.xml line 544 replaced 'stored procedures' with 'triggers'
* 14.12.2017 psql.xml line 1070 removed extraneous '>' symbol
* 21.01.2018 functions-vars.xml line 1222 replaced 'CURRENT_TIME' with 'CURRENT_TIMESTAMP'
* 21.01.2018 dml.xml line 19 switched 'INSERT OR UPDATE' to 'UPDATE OR INSERT'
* 21.01.2018 dml.xml line 3344 removed extraneous 'the'
* 21.01.2018 ddl.xml line 3359 inserted missing keyword 'INDEX' for SET STATISTICS syntax
* 21.01.2018 commons.xml line 1330 switch keywords 'horizontal' and 'vertical'
* 21.01.2018 structure.xml lines 276 to 278 change date literal format to 'yyyy-mm-dd' and include hex representation in example

|1.000
|11 Aug 2017
|H.E.M.B.
a|There have been no further changes to the content during the final review  period.
The chapters DML, PSQL, Functions and Variables, Transactions and Security were not reviewed in this phase.

|0.906
|11 Aug 2016
| H.E.M.B.
a|Several revisions were published during the year, as a Beta 1, with reviews of various sections by Paul Vinkenoog, Aage Johansen and Mark Rotteveel.
This revision (0.906) awaits final revision of some later sections, marked as "`Editor's Note`" in red italics.

|0.900
|1 Sep 2015
| H.E.M.B.
|Original was in Russian, translated by Dmitry Borodin (MegaTranslations).
Raw translation edited and converted to DocBook, as this revison (0.900), by Helen Borrie.

This revision distributed as a PDF build only, for review by Dmitry Yemanov, et al.

Reviewers, please pay attention to the comments like this: _Editor's note {two-colons} The sky is falling, take cover!_
|===

:sectnums:
