[[fblangref25]]
= Firebird 2.5 Language Reference
Dmitry Filippov; Alexander Karpeykin; Alexey Kovyazin; Dmitry Kuzmenko; Denis Simonov; Paul Vinkenoog; Dmitry Yemanov
1.4, 27 April 2021
:doctype: book
:sectnums:
:sectanchors:
:toc: left
:toclevels: 3
:outlinelevels: 6:0
:icons: font
:experimental:
:imagesdir: ../../images

The source of much copied reference material: Paul Vinkenoog +
Copyright (C) 2017-2020 Firebird Project and all contributing authors, under the https://www.firebirdsql.org/manual/pdl.html[Public Documentation License Version 1.0].
Please refer to the <<fblangref25-license,License Notice in the Appendix>>

[abstract]
--
This volume represents a compilation of topics concerning Firebird's SQL language written by members of the Russian-speaking community of Firebird developers and users.
In 2014, it culminated in a language reference manual, in Russian.
At the instigation of Alexey Kovyazin, a campaign was launched amongst Firebird users world-wide to raise funds to pay for a professional translation into English, from which translations into other languages would proceed under the auspices of the Firebird Documentation Project.
--

toc::[]

include::_fblangref25-intro.adoc[leveloffset=1]


include::_fblangref25-structure.adoc[leveloffset=1]


include::_fblangref25-datatypes.adoc[leveloffset=1]


include::_fblangref25-commons.adoc[leveloffset=1]


include::_fblangref25-ddl.adoc[leveloffset=1]


include::_fblangref25-dml.adoc[leveloffset=1]


include::_fblangref25-psql.adoc[leveloffset=1]


include::_fblangref25-functions.adoc[leveloffset=1]


include::_fblangref25-context-vars.adoc[leveloffset=1]


include::_fblangref25-transacs.adoc[leveloffset=1]


include::_fblangref25-security.adoc[leveloffset=1]


include::_fblangref25-appx01-supplement.adoc[leveloffset=1]


include::_fblangref25-appx02-errorcodes.adoc[leveloffset=1]


include::_fblangref25-appx03-reskeywords.adoc[leveloffset=1]


include::_fblangref25-appx04-systables.adoc[leveloffset=1]


include::_fblangref25-appx05-montables.adoc[leveloffset=1]


include::_fblangref25-appx06-charsets.adoc[leveloffset=1]


include::_fblangref25-appx07-license.adoc[leveloffset=1]


include::_fblangref25-dochist.adoc[leveloffset=1]
