:sectnums!:

[appendix]
[[fblangref30-license]]
= License notice

The contents of this Documentation are subject to the Public Documentation License Version 1.0 (the "`License`");
you may only use this Documentation if you comply with the terms of this License.
Copies of the License are available at https://www.firebirdsql.org/pdfmanual/pdl.pdf (PDF) and https://www.firebirdsql.org/manual/pdl.html (HTML).

The Original Documentation is titled [ref]_Firebird 3.0 Language Reference_.
This Documentation was derived from [ref]_Firebird 2.5 Language Reference_.

The Initial Writers of the Original Documentation are: Paul Vinkenoog, Dmitry Yemanov, Thomas Woinke and Mark Rotteveel.
Writers of text originally in Russian are Denis Simonov, Dmitry Filippov, Alexander Karpeykin, Alexey Kovyazin and Dmitry Kuzmenko.

Copyright (C) 2008-2024.
All Rights Reserved.
Initial Writers contact: paul at vinkenoog dot nl.

Writers and Editors of included PDL-licensed material are: J. Beesley, Helen Borrie, Arno Brinkman, Frank Ingermann, Vlad Khorsun, Alex Peshkov, Nickolay Samofatov, Adriano dos Santos Fernandes, Dmitry Yemanov.

Included portions are Copyright (C) 2001-2024 by their respective authors.
All Rights Reserved.

Contributor(s): Mark Rotteveel.

Portions created by Mark Rotteveel are Copyright (C) 2018-2024.
All Rights Reserved.
(Contributor contact(s): mrotteveel at users dot sourceforge dot net).

:sectnums:
