[[fblangref40-ddl-package-body]]
= `PACKAGE BODY`

[[fblangref40-ddl-pkg-body-create]]
== `CREATE PACKAGE BODY`

.Used for
Creating the package body

.Available in
DSQL

[[fblangref40-ddl-pkg-body-create-syntax]]
.Syntax
[listing,subs="+quotes,macros"]
----
CREATE PACKAGE BODY _name_
AS
BEGIN
  [ <package_item> ... ]
  [ <package_body_item> ... ]
END

<package_item> ::=
  !! See <<fblangref40-ddl-pkg-create-syntax,`CREATE PACKAGE` syntax>> !!

<package_body_item> ::=
  <function_impl> |
  <procedure_impl>

<function_impl> ::=
  FUNCTION _funcname_ [ ( [ <in_params> ] ) ]
  RETURNS <domain_or_non_array_type> [COLLATE _collation_]
  [DETERMINISTIC]
  <module-body>

<procedure_impl> ::=
  PROCEDURE _procname_ [ ( [ <in_params> ] ) ]
  [RETURNS (<out_params>)]
  <module-body>

<module-body> ::=
  !! See <<fblangref40-psql-elements-body-syntax,Syntax of Module Body>> !!

<in_params> ::=
  !! See <<fblangref40-ddl-pkg-create-syntax,`CREATE PACKAGE` syntax>> !!
  !! See also _Rules_ below !!

<out_params> ::=
  !! See <<fblangref40-ddl-pkg-create-syntax,`CREATE PACKAGE` syntax>> !!

<domain_or_non_array_type> ::=
  !! See <<fblangref40-datatypes-syntax-scalar,Scalar Data Types Syntax>> !!
----

[[fblangref40-ddl-tbl-createpkgbdy]]
.`CREATE PACKAGE BODY` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|package_name
|Package name consisting of up to 31 characters.
The package name must be unique among all package names.

|function_impl
|Function implementation.
Essentially a <<fblangref40-ddl-func-create,`CREATE FUNCTION`>> statement without `CREATE`.

|procedure_impl
|Procedure implementation
Essentially a <<fblangref40-ddl-proc-create,`CREATE PROCEDURE`>> statement without `CREATE`.

|func_name
|Function name consisting of up to 31 characters.
The function name must be unique within the package.

|collation
|Collation sequence

|proc_name
|Procedure name consisting of up to 31 characters.
The function name must be unique within the package.
|===

The `CREATE PACKAGE BODY` statement creates a new package body.
The package body can only be created after the package header has been created.
If there is no package header with name _package_name_, an appropriate error will be raised.

All procedures and functions declared in the package header must be implemented in the package body.
Additional procedures and functions may be defined and implemented in the package body only.
Procedure and functions defined in the package body, but not defined in the package header are not visible outside the package body.

The names of procedures and functions defined in the package body must be unique among the names of procedures and functions defined in the package header and implemented in the package body.

[[fblangref40-ddl-pkg-body-routine-shadowing]]
.Package procedure and function names may shadow global routines
[NOTE]
====
If a package header or package body declares a procedure or function with the same name as a stored procedure or function in the global namespace, it is not possible to call that global procedure or function from the package body.
In this case, the procedure or function of the package will always be called.

For this reason, it is recommended that the names of stored procedures and functions in packages do not overlap with names of stored procedures and functions in the global namespace.
====

.Rules
* In the package body, all procedures and functions must be implemented with the same signature as declared in the header and at the beginning of the package body
* The default values for procedure or function parameters cannot be overridden (as specified in the package header or in _<package_item>_).
This means default values can only be defined in _<package_body_item>_ for procedures or functions that have not been defined in the package header or earlier in the package body.

[NOTE]
====
UDF declarations (`DECLARE EXTERNAL FUNCTION`) is not supported for packages.
Use UDR instead.
====

[[fblangref40-ddl-pkg-body-create-who]]
=== Who Can Create a Package Body

The `CREATE PACKAGE BODY` statement can be executed by:

* <<fblangref40-security-administrators,Administrators>>
* The owner of the package
* Users with the `ALTER ANY PACKAGE` privilege

[[fblangref40-ddl-pkg-body-create-example]]
=== Examples of `CREATE PACKAGE BODY`

.Creating the package body
[source]
----
CREATE PACKAGE BODY APP_VAR
AS
BEGIN
  - Returns the start date of the period
  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEBEGIN');
  END
  - Returns the end date of the period
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEEND');
  END
  - Sets the date range of the working period
  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE)
  AS
  BEGIN
    RDB$SET_CONTEXT('USER_SESSION', 'DATEBEGIN', ADATEBEGIN);
    RDB$SET_CONTEXT('USER_SESSION', 'DATEEND', ADATEEND);
  END
END
----

.See also
<<fblangref40-ddl-pkg-body-alter>>, <<fblangref40-ddl-pkg-body-drop>>, <<fblangref40-ddl-pkg-body-recreate>>, <<fblangref40-ddl-pkg-create,`CREATE PACKAGE`>>

[[fblangref40-ddl-pkg-body-alter]]
== `ALTER PACKAGE BODY`

.Used for
Altering the package body

.Available in
DSQL

.Syntax
[listing,subs="+quotes,macros"]
----
ALTER PACKAGE BODY _name_
AS
BEGIN
  [ <package_item> ... ]
  [ <package_body_item> ... ]
END

!! See syntax of <<fblangref40-ddl-pkg-body-create-syntax,`CREATE PACKAGE BODY`>> for further rules !!
----

The `ALTER PACKAGE BODY` statement modifies the package body.
It can be used to change the definition and implementation of procedures and functions of the package body.

See <<fblangref40-ddl-pkg-body-create>> for more details.

[[fblangref40-ddl-pkg-body-alter-who]]
=== Who Can Alter a Package Body

The `ALTER PACKAGE BODY` statement can be executed by:

* <<fblangref40-security-administrators,Administrators>>
* The owner of the package
* Users with the `ALTER ANY PACKAGE` privilege

[[fblangref40-ddl-pkg-body-alter-example]]
=== Examples of `ALTER PACKAGE BODY`

.Modifying the package body
[source]
----
ALTER PACKAGE BODY APP_VAR
AS
BEGIN
  - Returns the start date of the period
  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEBEGIN');
  END
  - Returns the end date of the period
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEEND');
  END
  - Sets the date range of the working period
  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE)
  AS
  BEGIN
    RDB$SET_CONTEXT('USER_SESSION', 'DATEBEGIN', ADATEBEGIN);
    RDB$SET_CONTEXT('USER_SESSION', 'DATEEND', ADATEEND);
  END
END
----

.See also
<<fblangref40-ddl-pkg-body-create>>, <<fblangref40-ddl-pkg-body-drop>>, <<fblangref40-ddl-pkg-body-recreate>>, <<fblangref40-ddl-pkg-alter,`ALTER PACKAGE`>>

[[fblangref40-ddl-pkg-body-drop]]
== `DROP PACKAGE BODY`

.Used for
Dropping a package body

.Available in
DSQL

.Syntax
[listing,subs="+quotes"]
----
DROP PACKAGE _package_name_
----

[[fblangref40-ddl-tbl-droppkg-body]]
.`DROP PACKAGE BODY` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|package_name
|Package name
|===

The `DROP PACKAGE BODY` statement deletes the package body.

[[fblangref40-ddl-pkg-body-drop-who]]
=== Who Can Drop a Package Body

The `DROP PACKAGE BODY` statement can be executed by:

* <<fblangref40-security-administrators,Administrators>>
* The owner of the package
* Users with the `ALTER ANY PACKAGE` privilege

[[fblangref40-ddl-pkg-body-drop-example]]
=== Examples of `DROP PACKAGE BODY`

.Dropping the package body
[source]
----
DROP PACKAGE BODY APP_VAR;
----

.See also
<<fblangref40-ddl-pkg-body-create>>, <<fblangref40-ddl-pkg-body-alter>>, <<fblangref40-ddl-pkg-drop,`DROP PACKAGE`>>

[[fblangref40-ddl-pkg-body-recreate]]
== `RECREATE PACKAGE BODY`

.Used for
Creating a new or recreating an existing package body

.Available in
DSQL

.Syntax
[listing,subs="+quotes,macros"]
----
RECREATE PACKAGE BODY _name_
AS
BEGIN
  [ <package_item> ... ]
  [ <package_body_item> ... ]
END

!! See syntax of <<fblangref40-ddl-pkg-body-create-syntax,`CREATE PACKAGE BODY`>> for further rules !!
----

The `RECREATE PACKAGE BODY` statement creates a new or recreates an existing package body.
If a package body with the same name already exists, the statement will try to drop it and then create a new package body.
After recreating the package body, privileges of the package and its routines are preserved.

See <<fblangref40-ddl-pkg-body-create>> for more details.

[[fblangref40-ddl-pkg-body-recreate-example]]
=== Examples of `RECREATE PACKAGE BODY`

.Recreating the package body
[source]
----
RECREATE PACKAGE BODY APP_VAR
AS
BEGIN
  - Returns the start date of the period
  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEBEGIN');
  END
  - Returns the end date of the period
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEEND');
  END
  - Sets the date range of the working period
  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE)
  AS
  BEGIN
    RDB$SET_CONTEXT('USER_SESSION', 'DATEBEGIN', ADATEBEGIN);
    RDB$SET_CONTEXT('USER_SESSION', 'DATEEND', ADATEEND);
  END
END
----

.See also
<<fblangref40-ddl-pkg-body-create>>, <<fblangref40-ddl-pkg-body-alter>>, <<fblangref40-ddl-pkg-body-drop>>, <<fblangref40-ddl-pkg-alter,`ALTER PACKAGE`>>
