[[fblangref40-ddl-sequence]]
= `SEQUENCE` (`GENERATOR`)

A sequence  -- or generator -- is a database object used to get unique number values to fill a series.
"`Sequence`" is the SQL-compliant term for the same thing which -- in Firebird -- has traditionally been known as "`generator`".
Firebird has syntax for both terms.

Sequences are always stored as 64-bit integers, regardless of the SQL dialect of the database.

[CAUTION]
====
If a client is connected using Dialect 1, the server handles sequence values as 32-bit integers.
Passing a sequence value to a 32-bit field or variable will not cause errors as long as the current value of the sequence does not exceed the limits of a 32-bit number.
However, as soon as the sequence value exceeds this limit, a database in Dialect 3 will produce an error.
A database in Dialect 1 will truncate (overflow) the value, which could compromise the uniqueness of the series.
====

This section describes how to create, alter, set and drop sequences.

[[fblangref40-ddl-sequence-create]]
== `CREATE SEQUENCE`

.Used for
Creating a new `SEQUENCE` (`GENERATOR`)

.Available in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
CREATE {SEQUENCE | GENERATOR} _seq_name_
  [START WITH _start_value_]
  [INCREMENT [BY] _increment_]
----

[[fblangref40-ddl-tbl-crtseq]]
.`CREATE SEQUENCE` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|seq_name
|Sequence (generator) name.
The maximum length is 63 characters

|start_value
|Initial value of the sequence.
Default is 1.

|increment
|Increment of the sequence (when using `NEXT VALUE FOR __seq_name__`);
cannot be `0`.
Default is 1.
|===

The statements `CREATE SEQUENCE` and `CREATE GENERATOR` are synonymous -- both create a new sequence.
Either can be used, but `CREATE SEQUENCE` is recommended as that is the syntax defined in the SQL standard.

When a sequence is created, its current value is set so that the next value obtained from `NEXT VALUE FOR __seq_name__` is equal to _start_value_.
In other words, the current value of the sequence is set to (`__start_value__ - __increment__`).
By default, the _start_value_ is 1 (one).

The optional `INCREMENT [BY]` clause allows you to specify an increment for the <<fblangref40-commons-nxtvlufor,`NEXT VALUE FOR _seq_name_`>> expression.
By default, the increment is 1 (one).
The increment cannot be set to 0 (zero).
The `GEN_ID(seq_name, <step>)` function can be called instead, to "`step`" the series by a different integer number.
The increment specified through `INCREMENT [BY]` is not used for `GEN_ID`.

.Non-standard behaviour for negative increments
[NOTE]
====
The SQL standard specifies that sequences with a negative increment should start at the maximum value of the sequence (2^63^ - 1) and count down.
Firebird does not do that, and instead starts at `1`.

This may change in a future Firebird version.
====

[[fblangref40-ddl-sequence-create-who]]
=== Who Can Create a Sequence?

The `CREATE SEQUENCE` (`CREATE GENERATOR`) statement can be executed by:

* <<fblangref40-security-administrators,Administrators>>
* Users with the `CREATE SEQUENCE` (`CREATE GENERATOR`) privilege

The user executing the `CREATE SEQUENCE` (`CREATE GENERATOR`) statement becomes its owner.

[[fblangref40-ddl-sequence-create-example]]
=== Examples of `CREATE SEQUENCE`

. Creating the `EMP_NO_GEN` sequence using `CREATE SEQUENCE`.
+
[source]
----
CREATE SEQUENCE EMP_NO_GEN;
----
. Creating the `EMP_NO_GEN` sequence using `CREATE GENERATOR`.
+
[source]
----
CREATE GENERATOR EMP_NO_GEN;
----
. Creating the `EMP_NO_GEN` sequence with an initial value of 5 and an increment of 1.
+
[source]
----
CREATE SEQUENCE EMP_NO_GEN START WITH 5;
----
. Creating the `EMP_NO_GEN` sequence with an initial value of 1 and an increment of 10.
+
[source]
----
CREATE SEQUENCE EMP_NO_GEN INCREMENT BY 10;
----
. Creating the `EMP_NO_GEN` sequence with an initial value of 5 and an increment of 10.
+
[source]
----
CREATE SEQUENCE EMP_NO_GEN START WITH 5 INCREMENT BY 10;
----

.See also
<<fblangref40-ddl-sequence-alter>>, <<fblangref40-ddl-sequence-crtoralt>>, <<fblangref40-ddl-sequence-drop>>, <<fblangref40-ddl-sequence-recr>>, <<fblangref40-ddl-sequence-setgen>>, <<fblangref40-commons-nxtvlufor,`NEXT VALUE FOR`>>, <<fblangref40-scalarfuncs-gen-id,`GEN_ID() function`>>

[[fblangref40-ddl-sequence-alter]]
== `ALTER SEQUENCE`

.Used for
Setting the next value of a sequence or changing its increment

.Available in
DSQL

.Syntax
[listing,subs=+quotes]
----
ALTER {SEQUENCE | GENERATOR} _seq_name_
  [RESTART [WITH _newvalue_]]
  [INCREMENT [BY] _increment_]
----

[[fblangref40-ddl-tbl-alterseq]]
.`ALTER SEQUENCE` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|seq_name
|Sequence (generator) name

|newvalue
|New sequence (generator) value.
A 64-bit integer from -2^-63^ to 2^63^-1.

|increment
|Increment of the sequence (when using `NEXT VALUE FOR __seq_name__`);
cannot be `0`.
|===

The `ALTER SEQUENCE` statement sets the current value of a sequence to the specified value
and/or changes the increment of the sequence.

The `RESTART WITH __newvalue__` clause allows you to set the next value generated by `NEXT VALUE FOR __seq_name__`.
To achieve this, the current value of the sequence is set to (`__newvalue__ - __increment__`) with _increment_ either as specified in the statement, or stored in the metadata of the sequence.
The `RESTART` clause (without `WITH`) restarts the sequence with the initial value stored in the metadata of the sequence.

[NOTE]
====
Contrary to Firebird 3.0, in Firebird 4.0 `RESTART WITH __newvalue__` only restarts the sequence with the specified value, and does not store _newvalue_ as the new initial value of the sequence.
A subsequent `ALTER SEQUENCE RESTART` will use the initial value specified when the sequence was created, and not the _newvalue_ of this statement.
This behaviour is specified in the SQL standard.

It is currently not possible to change the initial value stored in the metadata.
====

[WARNING]
====
Incorrect use of the `ALTER SEQUENCE` statement (changing the current value of the sequence or generator) is likely to break the logical integrity of data, or result in primary key or unique constraint violations.
====

`INCREMENT [BY]` allows you to change the sequence increment for the `NEXT VALUE FOR` expression.

[NOTE]
====
Changing the increment value takes effect for all queries that run after the transaction commits.
Procedures that are called for the first time after changing the commit, will use the new value if they use `NEXT VALUE FOR`.
Procedures that were already used (and cached in the metadata cache) will continue to use the old increment.
You may need to close all connections to the database for the metadata cache to clear, and the new increment to be used.
Procedures using `NEXT VALUE FOR` do not need to be recompiled to see the new increment.
Procedures using `GEN_ID(gen, expression)` are not affected when the increment is changed.
====

[[fblangref40-ddl-sequence-alter-who]]
=== Who Can Alter a Sequence?

The `ALTER SEQUENCE` (`ALTER GENERATOR`) statement can be executed by:

* <<fblangref40-security-administrators,Administrators>>
* The owner of the sequence
* Users with the `ALTER ANY SEQUENCE` (`ALTER ANY GENERATOR`) privilege

[[fblangref40-ddl-sequence-alter-example]]
=== Examples of `ALTER SEQUENCE`

. Setting the value of the `EMP_NO_GEN` sequence so the next value is 145.
+
[source]
----
ALTER SEQUENCE EMP_NO_GEN RESTART WITH 145;
----
. Resetting the base value of the sequence `EMP_NO_GEN` to the initial value stored in the metadata
+
[source]
----
ALTER SEQUENCE EMP_NO_GEN RESTART;
----
. Changing the increment of sequence `EMP_NO_GEN` to 10
+
[source]
----
ALTER SEQUENCE EMP_NO_GEN INCREMENT BY 10;
----

.See also
<<fblangref40-ddl-sequence-setgen>>, <<fblangref40-ddl-sequence-create>>, <<fblangref40-ddl-sequence-crtoralt>>, <<fblangref40-ddl-sequence-drop>>, <<fblangref40-ddl-sequence-recr>>, <<fblangref40-commons-nxtvlufor,`NEXT VALUE FOR`>>, <<fblangref40-scalarfuncs-gen-id,`GEN_ID() function`>>

[[fblangref40-ddl-sequence-crtoralt]]
== `CREATE OR ALTER SEQUENCE`

.Used for
Creating a new or modifying an existing sequence

.Available in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
CREATE OR ALTER {SEQUENCE | GENERATOR} _seq_name_
  {RESTART | START WITH _start_value_}
  [INCREMENT [BY] _increment_]
----

[[fblangref40-ddl-sequence-crtoralt-tbl]]
.`CREATE OR ALTER SEQUENCE` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|seq_name
|Sequence (generator) name.
The maximum length is 63 characters

|start_value
|Initial value of the sequence.
Default is 1.

|increment
|Increment of the sequence (when using `NEXT VALUE FOR __seq_name__`);
cannot be `0`.
Default is 1.
|===

If the sequence does not exist, it will be created.
An existing sequence will be changed:

- If `RESTART` is specified, the sequence will restarted with the initial value stored in the metadata
- If the `START WITH` clause is specified, the sequence is restarted with _start_value_, but the _start_value_ is not stored.
In other words, it behaves as `RESTART WITH` in <<fblangref40-ddl-sequence-alter>>.
- If the `INCREMENT [BY]` clause is specified, _increment_ is stored as the increment in the metadata, and used for subsequent calls to `NEXT VALUE FOR`

[[fblangref40-ddl-sequence-crtoralt-example]]
=== Example of `CREATE OR ALTER SEQUENCE`

.Create a new or modify an existing sequence `EMP_NO_GEN`
[source]
----
CREATE OR ALTER SEQUENCE EMP_NO_GEN
  START WITH 10
  INCREMENT BY 1
----

.See also
<<fblangref40-ddl-sequence-create>>, <<fblangref40-ddl-sequence-alter>>, <<fblangref40-ddl-sequence-drop>>, <<fblangref40-ddl-sequence-recr>>, <<fblangref40-ddl-sequence-setgen>>, <<fblangref40-commons-nxtvlufor,`NEXT VALUE FOR`>>, <<fblangref40-scalarfuncs-gen-id,`GEN_ID() function`>>

[[fblangref40-ddl-sequence-drop]]
== `DROP SEQUENCE`

.Used for
Dropping (deleting) a `SEQUENCE` (`GENERATOR`)

.Available in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
DROP {SEQUENCE | GENERATOR} _seq_name_
----

[[fblangref40-ddl-tbl-dropseq]]
.`DROP SEQUENCE` Statement Parameter
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|seq_name
|Sequence (generator) name.
The maximum length is 63 characters
|===

The statements `DROP SEQUENCE` and `DROP GENERATOR` statements are equivalent: both drop (delete) an existing sequence (generator).
Either is valid but `DROP SEQUENCE`, being defined in the SQL standard, is recommended.

The statements will fail if the sequence (generator) has dependencies.

[[fblangref40-ddl-tbl-dropseq-who]]
=== Who Can Drop a Sequence?

The `DROP SEQUENCE` (`DROP GENERATOR`) statement can be executed by:

* <<fblangref40-security-administrators,Administrators>>
* The owner of the sequence
* Users with the `DROP ANY SEQUENCE` (`DROP ANY GENERATOR`) privilege

[[fblangref40-ddl-tbl-dropseq-example]]
=== Example of `DROP SEQUENCE`

.Dropping the `EMP_NO_GEN` series:
[source]
----
DROP SEQUENCE EMP_NO_GEN;
----

.See also
<<fblangref40-ddl-sequence-create>>, <<fblangref40-ddl-sequence-crtoralt>>, <<fblangref40-ddl-sequence-recr>>

[[fblangref40-ddl-sequence-recr]]
== `RECREATE SEQUENCE`

.Used for
Creating or recreating a sequence (generator)

.Available in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
RECREATE {SEQUENCE | GENERATOR} _seq_name_
  [START WITH _start_value_]
  [INCREMENT [BY] _increment_]
----

[[fblangref40-ddl-sequence-recr-tbl]]
.`RECREATE SEQUENCE` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|seq_name
|Sequence (generator) name.
The maximum length is 63 characters

|start_value
|Initial value of the sequence

|increment
|Increment of the sequence (when using `NEXT VALUE FOR __seq_name__`);
cannot be `0`
|===

See <<fblangref40-ddl-sequence-create>> for the full syntax of `CREATE SEQUENCE` and descriptions of defining a sequences and its options.

`RECREATE SEQUENCE` creates or recreates a sequence.
If a sequence with this name already exists, the `RECREATE SEQUENCE` statement will try to drop it and create a new one.
Existing dependencies will prevent the statement from executing.

[[fblangref40-ddl-sequence-recr-example]]
=== Example of `RECREATE SEQUENCE`

.Recreating sequence `EMP_NO_GEN`
[source]
----
RECREATE SEQUENCE EMP_NO_GEN
  START WITH 10
  INCREMENT BY 2;
----

.See also
<<fblangref40-ddl-sequence-create>>, <<fblangref40-ddl-sequence-alter>>, <<fblangref40-ddl-sequence-crtoralt>>, <<fblangref40-ddl-sequence-drop>>, <<fblangref40-ddl-sequence-setgen>>, <<fblangref40-commons-nxtvlufor,`NEXT VALUE FOR`>>, <<fblangref40-scalarfuncs-gen-id,`GEN_ID() function`>>

[[fblangref40-ddl-sequence-setgen]]
== `SET GENERATOR`

.Used for
Setting the current value of a sequence or generator to a specified value

.Available in
DSQL, ESQL

.Syntax
[listing,subs=+quotes]
----
SET GENERATOR _seq_name_ TO _new_val_
----

[[fblangref40-ddl-tbl-setgen]]
.`SET GENERATOR` Statement Parameters
[cols="<1,<3", options="header",stripes="none"]
|===
^| Parameter
^| Description

|seq_name
|Generator (sequence) name

|new_val
|New sequence (generator) value.
A 64-bit integer from -2^-63^ to 2^63^-1.
|===

The `SET GENERATOR` statement sets the current value of a sequence or generator to the specified value.

[NOTE]
====
Although `SET GENERATOR` is considered outdated, it is retained for backward compatibility.
Use of the standards-compliant `ALTER SEQUENCE` is recommended.
====

[[fblangref40-ddl-sequence-setgen-who]]
=== Who Can Use a `SET GENERATOR`?

The `SET GENERATOR` statement can be executed by:

* <<fblangref40-security-administrators,Administrators>>
* The owner of the sequence (generator)
* Users with the `ALTER ANY SEQUENCE` (`ALTER ANY GENERATOR`) privilege

[[fblangref40-ddl-sequence-setgen-example]]
=== Example of `SET GENERATOR`

.Setting the value of the `EMP_NO_GEN` sequence to 145:
[source]
----
SET GENERATOR EMP_NO_GEN TO 145;
----

[NOTE]
====
Similar effects can be achieved with <<fblangref40-ddl-sequence-alter>>:

[listing, subs=+quotes]
----
ALTER SEQUENCE EMP_NO_GEN
  RESTART WITH 145 + _increment_;
----

Here, the value of _increment_ is the current increment of the sequence.
We need add it as `ALTER SEQUENCE` calculates the current value to set based on the next value it should produce.
====

.See also
<<fblangref40-ddl-sequence-alter>>, <<fblangref40-ddl-sequence-create>>, <<fblangref40-ddl-sequence-crtoralt>>, <<fblangref40-ddl-sequence-drop>>, <<fblangref40-commons-nxtvlufor,`NEXT VALUE FOR`>>, <<fblangref40-scalarfuncs-gen-id,`GEN_ID() function`>>
